
var BlinkIDWasmSDK = (() => {
  var _scriptDir = typeof document !== 'undefined' && document.currentScript ? document.currentScript.src : undefined;
  
  return (
function(moduleArg = {}) {

/*

 Copyright 2019 The Emscripten Authors
 SPDX-License-Identifier: MIT

 Copyright 2013 The Emscripten Authors
 SPDX-License-Identifier: MIT

 This file gets implicatly injected as a `--post-js` file when
 emcc is run with `--emrun`
*/
var k=moduleArg,aa,ba;k.ready=new Promise((a,b)=>{aa=a;ba=b});k.Nb||(k.Nb=0);k.Nb++;
k.ENVIRONMENT_IS_PTHREAD||k.$ww||function(a){function b(l,n,q){var p=new XMLHttpRequest;p.open("GET",l,!0);p.responseType="arraybuffer";p.onprogress=function(t){var h=n;t.total&&(h=t.total);if(t.loaded){p.rc?k.nb[l].loaded=t.loaded:(p.rc=!0,k.nb||(k.nb={}),k.nb[l]={loaded:t.loaded,total:h});var r=h=t=0,w;for(w in k.nb){var A=k.nb[w];t+=A.total;h+=A.loaded;r++}t=Math.ceil(t*k.Nb/r);k.setStatus&&k.setStatus(`Downloading data... (${h}/${t})`)}else!k.nb&&k.setStatus&&k.setStatus("Downloading data...")};
p.onerror=function(){throw Error("NetworkError for: "+l);};p.onload=function(){if(200==p.status||304==p.status||206==p.status||0==p.status&&p.response)q(p.response);else throw Error(p.statusText+" : "+p.responseURL);};p.send(null)}function c(l){console.error("package error:",l)}function d(){function l(t,h,r){this.start=t;this.end=h;this.audio=r}function n(t){if(!t)throw"Loading data file failed."+Error().stack;if(t.constructor.name!==ArrayBuffer.name)throw"bad input to processPackageData"+Error().stack;
t=new Uint8Array(t);l.prototype.vc=t;t=a.files;for(var h=0;h<t.length;++h)l.prototype.Vb[t[h].filename].onload();k.removeRunDependency("datafile_/opt/jenkins/jenkinsData/E0/sdk-blinkid-in-browser/resources/full/advanced/BlinkIDWasmSDK.data")}k.FS_createPath("/","microblink",!0,!0);l.prototype={Vb:{},open:function(t,h){this.name=h;this.Vb[h]=this;k.addRunDependency(`fp ${this.name}`)},send:function(){},onload:function(){this.finish(this.vc.subarray(this.start,this.end))},finish:function(t){k.FS_createDataFile(this.name,
null,t,!0,!0,!0);k.removeRunDependency(`fp ${this.name}`);this.Vb[this.name]=null}};for(var q=a.files,p=0;p<q.length;++p)(new l(q[p].start,q[p].end,q[p].audio||0)).open("GET",q[p].filename);k.addRunDependency("datafile_/opt/jenkins/jenkinsData/E0/sdk-blinkid-in-browser/resources/full/advanced/BlinkIDWasmSDK.data");k.ic||(k.ic={});k.ic["/opt/jenkins/jenkinsData/E0/sdk-blinkid-in-browser/resources/full/advanced/BlinkIDWasmSDK.data"]={hd:!1};m?(n(m),m=null):g=n}"object"===typeof window?window.encodeURIComponent(window.location.pathname.toString().substring(0,
window.location.pathname.toString().lastIndexOf("/"))+"/"):"undefined"===typeof process&&"undefined"!==typeof location&&encodeURIComponent(location.pathname.toString().substring(0,location.pathname.toString().lastIndexOf("/"))+"/");"function"!==typeof k.locateFilePackage||k.locateFile||(k.locateFile=k.locateFilePackage,u("warning: you defined Module.locateFilePackage, that has been renamed to Module.locateFile (using your locateFilePackage for now)"));var e=k.locateFile?k.locateFile("BlinkIDWasmSDK.data",
""):"BlinkIDWasmSDK.data",f=a.remote_package_size,g=null,m=k.getPreloadedPackage?k.getPreloadedPackage(e,f):null;m||b(e,f,function(l){g?(g(l),g=null):m=l},c);k.calledRun?d():(k.preRun||(k.preRun=[]),k.preRun.push(d))}({files:[{filename:"/microblink/Model_07c7ab860e77ec2e92bb822f6d62424b8595a5beb4340f6b2f7f6a4cffa5d050.strop",start:0,end:120418},{filename:"/microblink/Model_2880751121560047e6dc571bc8ff4683aeb863886f7c0789234594ceb1e23577.strop",start:120418,end:124356},{filename:"/microblink/Model_36d8e94f4cb46097bd6b7385f2aa91fcdee1a5fefeec59e56d1b9e82c94b00a7.strop",
start:124356,end:494152},{filename:"/microblink/Model_473ac5f5e256623c0a6b282698c1f1b033b9fb5359e6aa142e9fb4a4022afe4e.strop",start:494152,end:501034},{filename:"/microblink/Model_500f4403bf221021bb85c3e758d59f69841635787f6f4201a4ffe5e68733f8bb.strop",start:501034,end:1084172},{filename:"/microblink/Model_63d9b8a72214cdbdfc3eee270a04e2a90adfaf7114fe68898130fa61bac7189d.strop",start:1084172,end:1219566},{filename:"/microblink/Model_80edc20a6f8f633671d2dccf75bb3efc1dc4ffc8873c060c7fad88e4cd22fb5b.strop",
start:1219566,end:2041200},{filename:"/microblink/Model_82ae7b860c6b4cb8249534e0004901bc46dee18fd3adbe535809abeefbf4fd88.strop",start:2041200,end:6759516},{filename:"/microblink/Model_8326c5065a6d8451d6d004db73babf4a4a9f502c68643a14934cc098d04bf44f.strop",start:6759516,end:7176620},{filename:"/microblink/Model_a0fe6f57f1b9be97d6d3c0e8df49805a1b94e638413127c6edd3ce6b7c622e07.strop",start:7176620,end:10140172},{filename:"/microblink/Model_b452fd3cd4037080cfcb4c423dba5bc58c8ceafc28427fdf9c5778fb353f088e.strop",
start:10140172,end:10147022},{filename:"/microblink/Model_d2bcaf18d17504513598e04f472c035b3d4f22d8653d5a79c05b4508a4b547b3.strop",start:10147022,end:10580538},{filename:"/microblink/Model_e4f1f62f68ec44b71ecad3fb3f3b48fe3790beb5ab325611e17d63af06e9f644.strop",start:10580538,end:10637052},{filename:"/microblink/Model_ed586fd6ca47c8eebb513c4ffaaacc2c54e92162b145062d7022519fba0911de.strop",start:10637052,end:11350284},{filename:"/microblink/Model_faf688599c7e261a2a7404730f69ed029115bb0d3e7a3657731d88e701720efe.strop",
start:11350284,end:11367022},{filename:"/microblink/ccc_lookup_table.zzip",start:11367022,end:11387491},{filename:"/microblink/face_detector_model.zzip",start:11387491,end:11484349}],remote_package_size:11484349});k.onAbort=function(a){u("Aborted with message: "+a);try{throw new WebAssembly.RuntimeError(a);}catch(b){u("Stacktrace: "+b.stack)}};
if("object"==typeof window){k.arguments=window.location.search.substr(1).trim().split("&");for(let a=0;a<k.arguments.length;++a)k.arguments[a]=decodeURI(k.arguments[a]);k.arguments[0]||(k.arguments=[])}var ca=Object.assign({},k),da="./this.program",ea=(a,b)=>{throw b;},fa="object"==typeof window,ha="function"==typeof importScripts,ia="",ja,ka,la;
if(fa||ha)ha?ia=self.location.href:"undefined"!=typeof document&&document.currentScript&&(ia=document.currentScript.src),_scriptDir&&(ia=_scriptDir),ia=ia.startsWith("blob:")?"":ia.substr(0,ia.replace(/[?#].*/,"").lastIndexOf("/")+1),ja=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},ha&&(la=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),ka=(a,b,c)=>{var d=new XMLHttpRequest;d.open("GET",
a,!0);d.responseType="arraybuffer";d.onload=()=>{200==d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)};var na=k.print||console.log.bind(console),u=k.printErr||console.error.bind(console);Object.assign(k,ca);ca=null;k.thisProgram&&(da=k.thisProgram);k.quit&&(ea=k.quit);var oa;k.wasmBinary&&(oa=k.wasmBinary);"object"!=typeof WebAssembly&&pa("no native wasm support detected");var qa,ra=!1,sa,v,x,ta,z,B,C,ua,va;
function wa(){var a=qa.buffer;k.HEAP8=v=new Int8Array(a);k.HEAP16=ta=new Int16Array(a);k.HEAPU8=x=new Uint8Array(a);k.HEAPU16=z=new Uint16Array(a);k.HEAP32=B=new Int32Array(a);k.HEAPU32=C=new Uint32Array(a);k.HEAPF32=ua=new Float32Array(a);k.HEAPF64=va=new Float64Array(a)}var xa=k.INITIAL_MEMORY||209715200;qa=k.wasmMemory?k.wasmMemory:new WebAssembly.Memory({initial:xa/65536,maximum:32768});wa();xa=qa.buffer.byteLength;var ya=[],za=[],Aa=[],Ba=[],Ca=!1;
function Da(){var a=k.preRun.shift();ya.unshift(a)}var Ea=0,Fa=null,Ga=null;function Ha(){Ea++;k.monitorRunDependencies?.(Ea)}function Ia(){Ea--;k.monitorRunDependencies?.(Ea);if(0==Ea&&(null!==Fa&&(clearInterval(Fa),Fa=null),Ga)){var a=Ga;Ga=null;a()}}function pa(a){k.onAbort?.(a);a="Aborted("+a+")";u(a);ra=!0;sa=1;a=new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");ba(a);throw a;}var Ja=a=>a.startsWith("data:application/octet-stream;base64,"),Ka;Ka="BlinkIDWasmSDK.wasm";
if(!Ja(Ka)){var La=Ka;Ka=k.locateFile?k.locateFile(La,ia):ia+La}function Ma(a){if(a==Ka&&oa)return new Uint8Array(oa);if(la)return la(a);throw"both async and sync fetching of the wasm failed";}function Na(a){return oa||!fa&&!ha||"function"!=typeof fetch?Promise.resolve().then(()=>Ma(a)):fetch(a,{credentials:"same-origin"}).then(b=>{if(!b.ok)throw`failed to load wasm binary file at '${a}'`;return b.arrayBuffer()}).catch(()=>Ma(a))}
function Oa(a,b,c){return Na(a).then(d=>WebAssembly.instantiate(d,b)).then(d=>d).then(c,d=>{u(`failed to asynchronously prepare wasm: ${d}`);pa(d)})}function Pa(a,b){var c=Ka;return oa||"function"!=typeof WebAssembly.instantiateStreaming||Ja(c)||"function"!=typeof fetch?Oa(c,a,b):fetch(c,{credentials:"same-origin"}).then(d=>WebAssembly.instantiateStreaming(d,a).then(b,function(e){u(`wasm streaming compile failed: ${e}`);u("falling back to ArrayBuffer instantiation");return Oa(c,a,b)}))}
var E,F,Qa={317421:a=>{a=a?I(x,a):"";throw Error("Failed to reconfigure RecognizerRunner due to following error: "+a);},317557:(a,b,c,d)=>{a=a?I(x,a):"";b=b?I(x,b):"";c=c?I(x,c):"";d=d?I(x,d):"";throw Error(a+b+c+d);},317773:(a,b)=>{a=a?I(x,a):"";b=b?I(x,b):"";throw Error(a+b);},317883:()=>{throw Error("Ping Proxy permission not found in license!",{cause:"PERMISSION_NOT_GRANTED"});},317986:a=>{throw Error(a?I(x,a):"");},318029:()=>{throw Error("Unable to perform that operation while recognizer is in use!");
},318112:()=>{throw Error("Unable to perform that operation while recognizer is in use!");},318195:()=>{throw Error("Unable to perform that operation while recognizer is in use!");}};function Ra(a){this.name="ExitStatus";this.message=`Program terminated with exit(${a})`;this.status=a}
var Sa=a=>{for(;0<a.length;)a.shift()(k)},Ua=k.noExitRuntime||!1,Va=(a,b)=>{for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a},Wa=a=>{var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=Va(a.split("/").filter(d=>!!d),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a},Xa=a=>{var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&
!b)return".";b&&=b.substr(0,b.length-1);return a+b},Ya=a=>{if("/"===a)return"/";a=Wa(a);a=a.replace(/\/$/,"");var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)},Za=()=>{if("object"==typeof crypto&&"function"==typeof crypto.getRandomValues)return a=>crypto.getRandomValues(a);pa("initRandomDevice")},$a=a=>($a=Za())(a);
function ab(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:"/";if("string"!=typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=Va(a.split("/").filter(d=>!!d),!b).join("/");return(b?"/":"")+a||"."}
var bb="undefined"!=typeof TextDecoder?new TextDecoder("utf8"):void 0,I=(a,b,c)=>{var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.buffer&&bb)return bb.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var f=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|f);else{var g=a[b++]&63;e=224==(e&240)?(e&15)<<12|f<<6|g:(e&7)<<18|f<<12|g<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d},
cb=[],db=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},K=(a,b,c,d)=>{if(!(0<d))return 0;var e=c;d=c+d-1;for(var f=0;f<a.length;++f){var g=a.charCodeAt(f);if(55296<=g&&57343>=g){var m=a.charCodeAt(++f);g=65536+((g&1023)<<10)|m&1023}if(127>=g){if(c>=d)break;b[c++]=g}else{if(2047>=g){if(c+1>=d)break;b[c++]=192|g>>6}else{if(65535>=g){if(c+2>=d)break;b[c++]=224|g>>12}else{if(c+3>=d)break;b[c++]=240|g>>18;b[c++]=128|g>>12&
63}b[c++]=128|g>>6&63}b[c++]=128|g&63}}b[c]=0;return c-e};function eb(a,b){var c=Array(db(a)+1);a=K(a,c,0,c.length);b&&(c.length=a);return c}var fb=[];function gb(a,b){fb[a]={input:[],Va:[],hb:b};hb(a,ib)}
var ib={open(a){var b=fb[a.node.wb];if(!b)throw new L(43);a.Qa=b;a.seekable=!1},close(a){a.Qa.hb.Cb(a.Qa)},Cb(a){a.Qa.hb.Cb(a.Qa)},read(a,b,c,d){if(!a.Qa||!a.Qa.hb.dc)throw new L(60);for(var e=0,f=0;f<d;f++){try{var g=a.Qa.hb.dc(a.Qa)}catch(m){throw new L(29);}if(void 0===g&&0===e)throw new L(6);if(null===g||void 0===g)break;e++;b[c+f]=g}e&&(a.node.timestamp=Date.now());return e},write(a,b,c,d){if(!a.Qa||!a.Qa.hb.Sb)throw new L(60);try{for(var e=0;e<d;e++)a.Qa.hb.Sb(a.Qa,b[c+e])}catch(f){throw new L(29);
}d&&(a.node.timestamp=Date.now());return e}},jb={dc(){a:{if(!cb.length){var a=null;"undefined"!=typeof window&&"function"==typeof window.prompt?(a=window.prompt("Input: "),null!==a&&(a+="\n")):"function"==typeof readline&&(a=readline(),null!==a&&(a+="\n"));if(!a){a=null;break a}cb=eb(a,!0)}a=cb.shift()}return a},Sb(a,b){null===b||10===b?(na(I(a.Va,0)),a.Va=[]):0!=b&&a.Va.push(b)},Cb(a){a.Va&&0<a.Va.length&&(na(I(a.Va,0)),a.Va=[])},Ic(){return{ed:25856,gd:5,dd:191,fd:35387,cd:[3,28,127,21,4,0,1,0,
17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]}},Jc(){return 0},Kc(){return[24,80]}},kb={Sb(a,b){null===b||10===b?(u(I(a.Va,0)),a.Va=[]):0!=b&&a.Va.push(b)},Cb(a){a.Va&&0<a.Va.length&&(u(I(a.Va,0)),a.Va=[])}},mb=a=>{a=65536*Math.ceil(a/65536);var b=lb(65536,a);b?(x.fill(0,b,b+a),a=b):a=0;return a};function nb(a,b){var c=a.La?a.La.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)>>>0),0!=c&&(b=Math.max(b,256)),c=a.La,a.La=new Uint8Array(b),0<a.Ra&&a.La.set(c.subarray(0,a.Ra),0))}
var M={cb:null,gb(){return M.createNode(null,"/",16895,0)},createNode(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new L(63);M.cb||(M.cb={dir:{node:{bb:M.Ma.bb,Za:M.Ma.Za,sb:M.Ma.sb,Gb:M.Ma.Gb,mc:M.Ma.mc,Mb:M.Ma.Mb,oc:M.Ma.oc,kc:M.Ma.kc,Jb:M.Ma.Jb},stream:{kb:M.Na.kb}},file:{node:{bb:M.Ma.bb,Za:M.Ma.Za},stream:{kb:M.Na.kb,read:M.Na.read,write:M.Na.write,rb:M.Na.rb,tb:M.Na.tb,Hb:M.Na.Hb}},link:{node:{bb:M.Ma.bb,Za:M.Ma.Za,xb:M.Ma.xb},stream:{}},Zb:{node:{bb:M.Ma.bb,Za:M.Ma.Za},stream:ob}});
c=pb(a,b,c,d);N(c.mode)?(c.Ma=M.cb.dir.node,c.Na=M.cb.dir.stream,c.La={}):32768===(c.mode&61440)?(c.Ma=M.cb.file.node,c.Na=M.cb.file.stream,c.Ra=0,c.La=null):40960===(c.mode&61440)?(c.Ma=M.cb.link.node,c.Na=M.cb.link.stream):8192===(c.mode&61440)&&(c.Ma=M.cb.Zb.node,c.Na=M.cb.Zb.stream);c.timestamp=Date.now();a&&(a.La[b]=c,a.timestamp=c.timestamp);return c},jd(a){return a.La?a.La.subarray?a.La.subarray(0,a.Ra):new Uint8Array(a.La):new Uint8Array(0)},Ma:{bb(a){var b={};b.yc=8192===(a.mode&61440)?a.id:
1;b.ec=a.id;b.mode=a.mode;b.Pc=1;b.uid=0;b.Fc=0;b.wb=a.wb;b.size=N(a.mode)?4096:32768===(a.mode&61440)?a.Ra:40960===(a.mode&61440)?a.link.length:0;b.sc=new Date(a.timestamp);b.Oc=new Date(a.timestamp);b.xc=new Date(a.timestamp);b.tc=4096;b.uc=Math.ceil(b.size/b.tc);return b},Za(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);if(void 0!==b.size&&(b=b.size,a.Ra!=b))if(0==b)a.La=null,a.Ra=0;else{var c=a.La;a.La=new Uint8Array(b);c&&a.La.set(c.subarray(0,Math.min(b,
a.Ra)));a.Ra=b}},sb(){throw qb[44];},Gb(a,b,c,d){return M.createNode(a,b,c,d)},mc(a,b,c){if(N(a.mode)){try{var d=rb(b,c)}catch(f){}if(d)for(var e in d.La)throw new L(55);}delete a.parent.La[a.name];a.parent.timestamp=Date.now();a.name=c;b.La[c]=a;b.timestamp=a.parent.timestamp;a.parent=b},Mb(a,b){delete a.La[b];a.timestamp=Date.now()},oc(a,b){var c=rb(a,b),d;for(d in c.La)throw new L(55);delete a.La[b];a.timestamp=Date.now()},kc(a){var b=[".",".."],c;for(c of Object.keys(a.La))b.push(c);return b},
Jb(a,b,c){a=M.createNode(a,b,41471,0);a.link=c;return a},xb(a){if(40960!==(a.mode&61440))throw new L(28);return a.link}},Na:{read(a,b,c,d,e){var f=a.node.La;if(e>=a.node.Ra)return 0;a=Math.min(a.node.Ra-e,d);if(8<a&&f.subarray)b.set(f.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=f[e+d];return a},write(a,b,c,d,e,f){b.buffer===v.buffer&&(f=!1);if(!d)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&(!a.La||a.La.subarray)){if(f)return a.La=b.subarray(c,c+d),a.Ra=d;if(0===a.Ra&&0===e)return a.La=
b.slice(c,c+d),a.Ra=d;if(e+d<=a.Ra)return a.La.set(b.subarray(c,c+d),e),d}nb(a,e+d);if(a.La.subarray&&b.subarray)a.La.set(b.subarray(c,c+d),e);else for(f=0;f<d;f++)a.La[e+f]=b[c+f];a.Ra=Math.max(a.Ra,e+d);return d},kb(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.Ra);if(0>b)throw new L(28);return b},rb(a,b,c){nb(a.node,b+c);a.node.Ra=Math.max(a.node.Ra,b+c)},tb(a,b,c,d,e){if(32768!==(a.node.mode&61440))throw new L(43);a=a.node.La;if(e&2||a.buffer!==v.buffer){if(0<c||c+
b<a.length)a=a.subarray?a.subarray(c,c+b):Array.prototype.slice.call(a,c,c+b);c=!0;b=mb(b);if(!b)throw new L(48);v.set(a,b)}else c=!1,b=a.byteOffset;return{Pa:b,Xa:c}},Hb(a,b,c,d){M.Na.write(a,b,0,d,c,!1);return 0}}},sb=(a,b,c)=>{var d=`al ${a}`;ka(a,e=>{b(new Uint8Array(e));d&&Ia(d)},()=>{if(c)c();else throw`Loading data file "${a}" failed.`;});d&&Ha(d)},tb=k.preloadPlugins||[],ub=(a,b,c,d)=>{"undefined"!=typeof Browser&&Browser.kd();var e=!1;tb.forEach(f=>{!e&&f.canHandle(b)&&(f.handle(a,b,c,d),
e=!0)});return e},wb=(a,b,c,d,e,f,g,m,l,n)=>{function q(h){function r(w){n?.();m||vb(a,b,w,d,e,l);f?.();Ia(t)}ub(h,p,r,()=>{g?.();Ia(t)})||r(h)}var p=b?ab(Wa(a+"/"+b)):a,t=`cp ${p}`;Ha(t);"string"==typeof c?sb(c,q,g):q(c)},xb=(a,b)=>{var c=0;a&&(c|=365);b&&(c|=146);return c},yb=null,zb={},Ab=[],Bb=1,Cb=null,Db=!0,L=class{constructor(a){this.name="ErrnoError";this.Ua=a}},qb={};
function Eb(a,b={}){a=ab(a);if(!a)return{path:"",node:null};b=Object.assign({cc:!0,Ub:0},b);if(8<b.Ub)throw new L(32);a=a.split("/").filter(g=>!!g);for(var c=yb,d="/",e=0;e<a.length;e++){var f=e===a.length-1;if(f&&b.parent)break;c=rb(c,a[e]);d=Wa(d+"/"+a[e]);c.ub&&(!f||f&&b.cc)&&(c=c.ub.root);if(!f||b.Bb)for(f=0;40960===(c.mode&61440);)if(c=Fb(d),d=ab(Xa(d),c),c=Eb(d,{Ub:b.Ub+1}).node,40<f++)throw new L(32);}return{path:d,node:c}}
function Gb(a){for(var b;;){if(a===a.parent)return a=a.gb.hc,b?"/"!==a[a.length-1]?`${a}/${b}`:a+b:a;b=b?`${a.name}/${b}`:a.name;a=a.parent}}function Hb(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%Cb.length}function rb(a,b){var c=N(a.mode)?(c=Ib(a,"x"))?c:a.Ma.sb?0:2:54;if(c)throw new L(c);for(c=Cb[Hb(a.id,b)];c;c=c.qb){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.Ma.sb(a,b)}
function pb(a,b,c,d){a=new Jb(a,b,c,d);b=Hb(a.parent.id,a.name);a.qb=Cb[b];return Cb[b]=a}function N(a){return 16384===(a&61440)}function Kb(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}function Ib(a,b){if(Db)return 0;if(!b.includes("r")||a.mode&292){if(b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73))return 2}else return 2;return 0}function Lb(a,b){try{return rb(a,b),20}catch(c){}return Ib(a,"wx")}function Mb(){for(var a=0;4096>=a;a++)if(!Ab[a])return a;throw new L(33);}
function O(a){a=Ab[a];if(!a)throw new L(8);return a}function Nb(a,b=-1){Ob||(Ob=function(){this.Ib={}},Ob.prototype={},Object.defineProperties(Ob.prototype,{object:{get(){return this.node},set(c){this.node=c}},flags:{get(){return this.Ib.flags},set(c){this.Ib.flags=c}},position:{get(){return this.Ib.position},set(c){this.Ib.position=c}}}));a=Object.assign(new Ob,a);-1==b&&(b=Mb());a.ib=b;return Ab[b]=a}var ob={open(a){a.Na=zb[a.node.wb].Na;a.Na.open?.(a)},kb(){throw new L(70);}};
function hb(a,b){zb[a]={Na:b}}function Pb(a,b){var c="/"===b;if(c&&yb)throw new L(10);if(!c&&b){var d=Eb(b,{cc:!1});b=d.path;d=d.node;if(d.ub)throw new L(10);if(!N(d.mode))throw new L(54);}b={type:a,nd:{},hc:b,Nc:[]};a=a.gb(b);a.gb=b;b.root=a;c?yb=a:d&&(d.ub=b,d.gb&&d.gb.Nc.push(b))}function Qb(a,b,c){var d=Eb(a,{parent:!0}).node;a=Ya(a);if(!a||"."===a||".."===a)throw new L(28);var e=Lb(d,a);if(e)throw new L(e);if(!d.Ma.Gb)throw new L(63);return d.Ma.Gb(d,a,b,c)}
function Rb(a){return Qb(a,16895,0)}function Sb(a,b,c){"undefined"==typeof c&&(c=b,b=438);return Qb(a,b|8192,c)}function Tb(a,b){if(!ab(a))throw new L(44);var c=Eb(b,{parent:!0}).node;if(!c)throw new L(44);b=Ya(b);var d=Lb(c,b);if(d)throw new L(d);if(!c.Ma.Jb)throw new L(63);c.Ma.Jb(c,b,a)}
function Ub(a){var b=Eb(a,{parent:!0}).node;if(!b)throw new L(44);var c=Ya(a);a=rb(b,c);a:{try{var d=rb(b,c)}catch(f){d=f.Ua;break a}var e=Ib(b,"wx");d=e?e:N(d.mode)?31:0}if(d)throw new L(d);if(!b.Ma.Mb)throw new L(63);if(a.ub)throw new L(10);b.Ma.Mb(b,c);b=Hb(a.parent.id,a.name);if(Cb[b]===a)Cb[b]=a.qb;else for(b=Cb[b];b;){if(b.qb===a){b.qb=a.qb;break}b=b.qb}}function Fb(a){a=Eb(a).node;if(!a)throw new L(44);if(!a.Ma.xb)throw new L(28);return ab(Gb(a.parent),a.Ma.xb(a))}
function Vb(a,b){a=Eb(a,{Bb:!b}).node;if(!a)throw new L(44);if(!a.Ma.bb)throw new L(63);return a.Ma.bb(a)}function Wb(a){return Vb(a,!0)}function Xb(a,b){a="string"==typeof a?Eb(a,{Bb:!0}).node:a;if(!a.Ma.Za)throw new L(63);a.Ma.Za(a,{mode:b&4095|a.mode&-4096,timestamp:Date.now()})}
function Yb(a,b,c){if(""===a)throw new L(44);if("string"==typeof b){var d={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090}[b];if("undefined"==typeof d)throw Error(`Unknown file open mode: ${b}`);b=d}c=b&64?("undefined"==typeof c?438:c)&4095|32768:0;if("object"==typeof a)var e=a;else{a=Wa(a);try{e=Eb(a,{Bb:!(b&131072)}).node}catch(f){}}d=!1;if(b&64)if(e){if(b&128)throw new L(20);}else e=Qb(a,c,0),d=!0;if(!e)throw new L(44);8192===(e.mode&61440)&&(b&=-513);if(b&65536&&!N(e.mode))throw new L(54);if(!d&&
(c=e?40960===(e.mode&61440)?32:N(e.mode)&&("r"!==Kb(b)||b&512)?31:Ib(e,Kb(b)):44))throw new L(c);if(b&512&&!d){c=e;c="string"==typeof c?Eb(c,{Bb:!0}).node:c;if(!c.Ma.Za)throw new L(63);if(N(c.mode))throw new L(31);if(32768!==(c.mode&61440))throw new L(28);if(d=Ib(c,"w"))throw new L(d);c.Ma.Za(c,{size:0,timestamp:Date.now()})}b&=-131713;e=Nb({node:e,path:Gb(e),flags:b,seekable:!0,position:0,Na:e.Na,bd:[],error:!1});e.Na.open&&e.Na.open(e);!k.logReadFiles||b&1||(Zb||={},a in Zb||(Zb[a]=1));return e}
function $b(a){if(null===a.ib)throw new L(8);a.Pb&&(a.Pb=null);try{a.Na.close&&a.Na.close(a)}catch(b){throw b;}finally{Ab[a.ib]=null}a.ib=null}function ac(a,b,c){if(null===a.ib)throw new L(8);if(!a.seekable||!a.Na.kb)throw new L(70);if(0!=c&&1!=c&&2!=c)throw new L(28);a.position=a.Na.kb(a,b,c);a.bd=[]}
function bc(a,b,c,d,e,f){if(0>d||0>e)throw new L(28);if(null===a.ib)throw new L(8);if(0===(a.flags&2097155))throw new L(8);if(N(a.node.mode))throw new L(31);if(!a.Na.write)throw new L(28);a.seekable&&a.flags&1024&&ac(a,0,2);var g="undefined"!=typeof e;if(!g)e=a.position;else if(!a.seekable)throw new L(70);b=a.Na.write(a,b,c,d,e,f);g||(a.position+=b);return b}var cc;
function dc(a,b){a="string"==typeof a?a:Gb(a);for(b=b.split("/").reverse();b.length;){var c=b.pop();if(c){var d=Wa(a+"/"+c);try{Rb(d)}catch(e){}a=d}}return d}function ec(a,b,c,d){a=Wa(("string"==typeof a?a:Gb(a))+"/"+b);c=xb(c,d);return Qb(a,(void 0!==c?c:438)&4095|32768,0)}
function vb(a,b,c,d,e,f){var g=b;a&&(a="string"==typeof a?a:Gb(a),g=b?Wa(a+"/"+b):a);a=xb(d,e);g=Qb(g,(void 0!==a?a:438)&4095|32768,0);if(c){if("string"==typeof c){b=Array(c.length);d=0;for(e=c.length;d<e;++d)b[d]=c.charCodeAt(d);c=b}Xb(g,a|146);b=Yb(g,577);bc(b,c,0,c.length,0,f);$b(b);Xb(g,a)}}
function fc(a,b,c,d){a=Wa(("string"==typeof a?a:Gb(a))+"/"+b);b=xb(!!c,!!d);fc.fc||(fc.fc=64);var e=fc.fc++<<8|0;hb(e,{open(f){f.seekable=!1},close(){d?.buffer?.length&&d(10)},read(f,g,m,l){for(var n=0,q=0;q<l;q++){try{var p=c()}catch(t){throw new L(29);}if(void 0===p&&0===n)throw new L(6);if(null===p||void 0===p)break;n++;g[m+q]=p}n&&(f.node.timestamp=Date.now());return n},write(f,g,m,l){for(var n=0;n<l;n++)try{d(g[m+n])}catch(q){throw new L(29);}l&&(f.node.timestamp=Date.now());return n}});return Sb(a,
b,e)}function gc(a){if(!(a.Lc||a.Mc||a.link||a.La)){if("undefined"!=typeof XMLHttpRequest)throw Error("Lazy loading should have been performed (contents set) in createLazyFile, but it was not. Lazy loading only works in web workers. Use --embed-file or --preload-file in emcc on the main thread.");if(ja)try{a.La=eb(ja(a.url),!0),a.Ra=a.La.length}catch(b){throw new L(29);}else throw Error("Cannot load without read() or XMLHttpRequest.");}}
function hc(a,b,c,d,e){function f(){this.Rb=!1;this.Ab=[]}function g(p,t,h,r,w){p=p.node.La;if(w>=p.length)return 0;r=Math.min(p.length-w,r);if(p.slice)for(var A=0;A<r;A++)t[h+A]=p[w+A];else for(A=0;A<r;A++)t[h+A]=p.get(w+A);return r}f.prototype.get=function(p){if(!(p>this.length-1||0>p)){var t=p%this.$b;return this.Db(p/this.$b|0)[t]}};f.prototype.Tc=function(p){this.Db=p};f.prototype.Yb=function(){var p=new XMLHttpRequest;p.open("HEAD",c,!1);p.send(null);if(!(200<=p.status&&300>p.status||304===
p.status))throw Error("Couldn't load "+c+". Status: "+p.status);var t=Number(p.getResponseHeader("Content-length")),h,r=(h=p.getResponseHeader("Accept-Ranges"))&&"bytes"===h;p=(h=p.getResponseHeader("Content-Encoding"))&&"gzip"===h;var w=1048576;r||(w=t);var A=this;A.Tc(J=>{var H=J*w,y=(J+1)*w-1;y=Math.min(y,t-1);if("undefined"==typeof A.Ab[J]){var P=A.Ab;if(H>y)throw Error("invalid range ("+H+", "+y+") or no bytes requested!");if(y>t-1)throw Error("only "+t+" bytes available! programmer error!");
var D=new XMLHttpRequest;D.open("GET",c,!1);t!==w&&D.setRequestHeader("Range","bytes="+H+"-"+y);D.responseType="arraybuffer";D.overrideMimeType&&D.overrideMimeType("text/plain; charset=x-user-defined");D.send(null);if(!(200<=D.status&&300>D.status||304===D.status))throw Error("Couldn't load "+c+". Status: "+D.status);H=void 0!==D.response?new Uint8Array(D.response||[]):eb(D.responseText||"",!0);P[J]=H}if("undefined"==typeof A.Ab[J])throw Error("doXHR failed!");return A.Ab[J]});if(p||!t)w=t=1,w=t=
this.Db(0).length,na("LazyFiles on gzip forces download of the whole file when length is accessed");this.qc=t;this.pc=w;this.Rb=!0};if("undefined"!=typeof XMLHttpRequest){if(!ha)throw"Cannot do synchronous binary XHRs outside webworkers in modern browsers. Use --embed-file or --preload-file in emcc";var m=new f;Object.defineProperties(m,{length:{get:function(){this.Rb||this.Yb();return this.qc}},$b:{get:function(){this.Rb||this.Yb();return this.pc}}});var l=void 0}else l=c,m=void 0;var n=ec(a,b,d,
e);m?n.La=m:l&&(n.La=null,n.url=l);Object.defineProperties(n,{Ra:{get:function(){return this.La.length}}});var q={};Object.keys(n.Na).forEach(p=>{var t=n.Na[p];q[p]=function(){gc(n);return t.apply(null,arguments)}});q.read=(p,t,h,r,w)=>{gc(n);return g(p,t,h,r,w)};q.tb=(p,t,h)=>{gc(n);var r=mb(t);if(!r)throw new L(48);g(p,v,r,t,h);return{Pa:r,Xa:!0}};n.Na=q;return n}var Q={},Ob,Zb,ic=a=>a?I(x,a):"";
function jc(a,b,c){if("/"===b.charAt(0))return b;a=-100===a?"/":O(a).path;if(0==b.length){if(!c)throw new L(44);return a}return Wa(a+"/"+b)}
function kc(a,b,c){a=a(b);B[c>>2]=a.yc;B[c+4>>2]=a.mode;C[c+8>>2]=a.Pc;B[c+12>>2]=a.uid;B[c+16>>2]=a.Fc;B[c+20>>2]=a.wb;F=[a.size>>>0,(E=a.size,1<=+Math.abs(E)?0<E?+Math.floor(E/4294967296)>>>0:~~+Math.ceil((E-+(~~E>>>0))/4294967296)>>>0:0)];B[c+24>>2]=F[0];B[c+28>>2]=F[1];B[c+32>>2]=4096;B[c+36>>2]=a.uc;b=a.sc.getTime();var d=a.Oc.getTime(),e=a.xc.getTime();F=[Math.floor(b/1E3)>>>0,(E=Math.floor(b/1E3),1<=+Math.abs(E)?0<E?+Math.floor(E/4294967296)>>>0:~~+Math.ceil((E-+(~~E>>>0))/4294967296)>>>0:
0)];B[c+40>>2]=F[0];B[c+44>>2]=F[1];C[c+48>>2]=b%1E3*1E3;F=[Math.floor(d/1E3)>>>0,(E=Math.floor(d/1E3),1<=+Math.abs(E)?0<E?+Math.floor(E/4294967296)>>>0:~~+Math.ceil((E-+(~~E>>>0))/4294967296)>>>0:0)];B[c+56>>2]=F[0];B[c+60>>2]=F[1];C[c+64>>2]=d%1E3*1E3;F=[Math.floor(e/1E3)>>>0,(E=Math.floor(e/1E3),1<=+Math.abs(E)?0<E?+Math.floor(E/4294967296)>>>0:~~+Math.ceil((E-+(~~E>>>0))/4294967296)>>>0:0)];B[c+72>>2]=F[0];B[c+76>>2]=F[1];C[c+80>>2]=e%1E3*1E3;F=[a.ec>>>0,(E=a.ec,1<=+Math.abs(E)?0<E?+Math.floor(E/
4294967296)>>>0:~~+Math.ceil((E-+(~~E>>>0))/4294967296)>>>0:0)];B[c+88>>2]=F[0];B[c+92>>2]=F[1];return 0}var lc=void 0;function mc(){var a=B[+lc>>2];lc+=4;return a}var nc={},oc=a=>{for(;a.length;){var b=a.pop();a.pop()(b)}};function pc(a){return this.fromWireType(B[a>>2])}
var qc={},rc={},sc={},tc,vc=(a,b,c)=>{function d(m){m=c(m);if(m.length!==a.length)throw new tc("Mismatched type converter count");for(var l=0;l<a.length;++l)uc(a[l],m[l])}a.forEach(function(m){sc[m]=b});var e=Array(b.length),f=[],g=0;b.forEach((m,l)=>{rc.hasOwnProperty(m)?e[l]=rc[m]:(f.push(m),qc.hasOwnProperty(m)||(qc[m]=[]),qc[m].push(()=>{e[l]=rc[m];++g;g===f.length&&d(e)}))});0===f.length&&d(e)},wc,R=a=>{for(var b="";x[a];)b+=wc[x[a++]];return b},S;
function xc(a,b,c={}){var d=b.name;if(!a)throw new S(`type "${d}" must have a positive integer typeid pointer`);if(rc.hasOwnProperty(a)){if(c.Gc)return;throw new S(`Cannot register type '${d}' twice`);}rc[a]=b;delete sc[a];qc.hasOwnProperty(a)&&(b=qc[a],delete qc[a],b.forEach(e=>e()))}function uc(a,b,c={}){if(!("argPackAdvance"in b))throw new TypeError("registerType registeredInstance requires argPackAdvance");return xc(a,b,c)}
var yc=a=>{throw new S(a.Ka.Sa.Oa.name+" instance already deleted");},zc=!1,Ac=()=>{},Bc=(a,b,c)=>{if(b===c)return a;if(void 0===c.Ya)return null;a=Bc(a,b,c.Ya);return null===a?null:c.zc(a)},Cc={},Dc=[],Ec=()=>{for(;Dc.length;){var a=Dc.pop();a.Ka.ob=!1;a["delete"]()}},Fc,Gc={},Hc=(a,b)=>{if(void 0===b)throw new S("ptr should not be undefined");for(;a.Ya;)b=a.yb(b),a=a.Ya;return Gc[b]},Jc=(a,b)=>{if(!b.Sa||!b.Pa)throw new tc("makeClassHandle requires ptr and ptrType");if(!!b.$a!==!!b.Ta)throw new tc("Both smartPtrType and smartPtr must be specified");
b.count={value:1};return Ic(Object.create(a,{Ka:{value:b,writable:!0}}))},Ic=a=>{if("undefined"===typeof FinalizationRegistry)return Ic=b=>b,a;zc=new FinalizationRegistry(b=>{b=b.Ka;--b.count.value;0===b.count.value&&(b.Ta?b.$a.eb(b.Ta):b.Sa.Oa.eb(b.Pa))});Ic=b=>{var c=b.Ka;c.Ta&&zc.register(b,{Ka:c},b);return b};Ac=b=>{zc.unregister(b)};return Ic(a)};function Kc(){}
var Lc=(a,b)=>Object.defineProperty(b,"name",{value:a}),Mc=(a,b,c)=>{if(void 0===a[b].Wa){var d=a[b];a[b]=function(){if(!a[b].Wa.hasOwnProperty(arguments.length))throw new S(`Function '${c}' called with an invalid number of arguments (${arguments.length}) - expects one of (${a[b].Wa})!`);return a[b].Wa[arguments.length].apply(this,arguments)};a[b].Wa=[];a[b].Wa[d.zb]=d}},Nc=(a,b,c)=>{if(k.hasOwnProperty(a)){if(void 0===c||void 0!==k[a].Wa&&void 0!==k[a].Wa[c])throw new S(`Cannot register public name '${a}' twice`);
Mc(k,a,a);if(k.hasOwnProperty(c))throw new S(`Cannot register multiple overloads of a function with the same number of arguments (${c})!`);k[a].Wa[c]=b}else k[a]=b,void 0!==c&&(k[a].md=c)},Oc=a=>{if(void 0===a)return"_unknown";a=a.replace(/[^a-zA-Z0-9_]/g,"$");var b=a.charCodeAt(0);return 48<=b&&57>=b?`_${a}`:a};function Pc(a,b,c,d,e,f,g,m){this.name=a;this.constructor=b;this.pb=c;this.eb=d;this.Ya=e;this.Bc=f;this.yb=g;this.zc=m;this.Rc=[]}
var Qc=(a,b,c)=>{for(;b!==c;){if(!b.yb)throw new S(`Expected null or instance of ${c.name}, got an instance of ${b.name}`);a=b.yb(a);b=b.Ya}return a};function Rc(a,b){if(null===b){if(this.Qb)throw new S(`null is not a valid ${this.name}`);return 0}if(!b.Ka)throw new S(`Cannot pass "${Sc(b)}" as a ${this.name}`);if(!b.Ka.Pa)throw new S(`Cannot pass deleted object as a pointer of type ${this.name}`);return Qc(b.Ka.Pa,b.Ka.Sa.Oa,this.Oa)}
function Tc(a,b){if(null===b){if(this.Qb)throw new S(`null is not a valid ${this.name}`);if(this.Fb){var c=this.Tb();null!==a&&a.push(this.eb,c);return c}return 0}if(!b||!b.Ka)throw new S(`Cannot pass "${Sc(b)}" as a ${this.name}`);if(!b.Ka.Pa)throw new S(`Cannot pass deleted object as a pointer of type ${this.name}`);if(!this.Eb&&b.Ka.Sa.Eb)throw new S(`Cannot convert argument of type ${b.Ka.$a?b.Ka.$a.name:b.Ka.Sa.name} to parameter type ${this.name}`);c=Qc(b.Ka.Pa,b.Ka.Sa.Oa,this.Oa);if(this.Fb){if(void 0===
b.Ka.Ta)throw new S("Passing raw pointer to smart pointer is illegal");switch(this.Xc){case 0:if(b.Ka.$a===this)c=b.Ka.Ta;else throw new S(`Cannot convert argument of type ${b.Ka.$a?b.Ka.$a.name:b.Ka.Sa.name} to parameter type ${this.name}`);break;case 1:c=b.Ka.Ta;break;case 2:if(b.Ka.$a===this)c=b.Ka.Ta;else{var d=b.clone();c=this.Sc(c,T(()=>d["delete"]()));null!==a&&a.push(this.eb,c)}break;default:throw new S("Unsupporting sharing policy");}}return c}
function Uc(a,b){if(null===b){if(this.Qb)throw new S(`null is not a valid ${this.name}`);return 0}if(!b.Ka)throw new S(`Cannot pass "${Sc(b)}" as a ${this.name}`);if(!b.Ka.Pa)throw new S(`Cannot pass deleted object as a pointer of type ${this.name}`);if(b.Ka.Sa.Eb)throw new S(`Cannot convert argument of type ${b.Ka.Sa.name} to parameter type ${this.name}`);return Qc(b.Ka.Pa,b.Ka.Sa.Oa,this.Oa)}function Vc(a){return this.fromWireType(C[a>>2])}
function Wc(a,b,c,d,e,f,g,m,l,n,q){this.name=a;this.Oa=b;this.Qb=c;this.Eb=d;this.Fb=e;this.Qc=f;this.Xc=g;this.jc=m;this.Tb=l;this.Sc=n;this.eb=q;e||void 0!==b.Ya?this.toWireType=Tc:(this.toWireType=d?Rc:Uc,this.ab=null)}
var Xc=(a,b,c)=>{if(!k.hasOwnProperty(a))throw new tc("Replacing nonexistant public symbol");void 0!==k[a].Wa&&void 0!==c?k[a].Wa[c]=b:(k[a]=b,k[a].zb=c)},Yc=[],Zc,U=a=>{var b=Yc[a];b||(a>=Yc.length&&(Yc.length=a+1),Yc[a]=b=Zc.get(a));return b},$c=(a,b)=>{var c=[];return function(){c.length=0;Object.assign(c,arguments);if(a.includes("j")){var d=k["dynCall_"+a];d=c&&c.length?d.apply(null,[b].concat(c)):d.call(null,b)}else d=U(b).apply(null,c);return d}},ad=(a,b)=>{a=R(a);var c=a.includes("j")?$c(a,
b):U(b);if("function"!=typeof c)throw new S(`unknown function pointer with signature ${a}: ${b}`);return c},bd,ed=a=>{a=cd(a);var b=R(a);dd(a);return b},fd=(a,b)=>{function c(f){e[f]||rc[f]||(sc[f]?sc[f].forEach(c):(d.push(f),e[f]=!0))}var d=[],e={};b.forEach(c);throw new bd(`${a}: `+d.map(ed).join([", "]));},gd=(a,b)=>{for(var c=[],d=0;d<a;d++)c.push(C[b+4*d>>2]);return c};function hd(a){for(var b=1;b<a.length;++b)if(null!==a[b]&&void 0===a[b].ab)return!0;return!1}
function jd(a,b,c,d,e){var f=b.length;if(2>f)throw new S("argTypes array size mismatch! Must at least get return value and 'this' types!");var g=null!==b[1]&&null!==c,m=hd(b),l="void"!==b[0].name,n=f-2,q=Array(n),p=[],t=[];return Lc(a,function(){if(arguments.length!==n)throw new S(`function ${a} called with ${arguments.length} arguments, expected ${n}`);t.length=0;p.length=g?2:1;p[0]=e;if(g){var h=b[1].toWireType(t,this);p[1]=h}for(var r=0;r<n;++r)q[r]=b[r+2].toWireType(t,arguments[r]),p.push(q[r]);
r=d.apply(null,p);if(m)oc(t);else for(var w=g?1:2;w<b.length;w++){var A=1===w?h:q[w-2];null!==b[w].ab&&b[w].ab(A)}h=l?b[0].fromWireType(r):void 0;return h})}var kd=a=>{a=a.trim();const b=a.indexOf("(");return-1!==b?a.substr(0,b):a};class ld{constructor(){this.Xa=[void 0];this.Ob=[]}get(a){return this.Xa[a]}has(a){return void 0!==this.Xa[a]}rb(a){var b=this.Ob.pop()||this.Xa.length;this.Xa[b]=a;return b}}
var V=new ld,md=a=>{a>=V.nc&&0===--V.get(a).lc&&(V.Xa[a]=void 0,V.Ob.push(a))},X=a=>{if(!a)throw new S("Cannot use deleted val. handle = "+a);return V.get(a).value},T=a=>{switch(a){case void 0:return 1;case null:return 2;case !0:return 3;case !1:return 4;default:return V.rb({lc:1,value:a})}},nd={name:"emscripten::val",fromWireType:a=>{var b=X(a);md(a);return b},toWireType:(a,b)=>T(b),argPackAdvance:8,readValueFromPointer:pc,ab:null},Sc=a=>{if(null===a)return"null";var b=typeof a;return"object"===
b||"array"===b||"function"===b?a.toString():""+a},od=(a,b)=>{switch(b){case 4:return function(c){return this.fromWireType(ua[c>>2])};case 8:return function(c){return this.fromWireType(va[c>>3])};default:throw new TypeError(`invalid float width (${b}): ${a}`);}},pd=(a,b,c)=>{switch(b){case 1:return c?d=>v[d>>0]:d=>x[d>>0];case 2:return c?d=>ta[d>>1]:d=>z[d>>1];case 4:return c?d=>B[d>>2]:d=>C[d>>2];default:throw new TypeError(`invalid integer width (${b}): ${a}`);}},qd="undefined"!=typeof TextDecoder?
new TextDecoder("utf-16le"):void 0,rd=(a,b)=>{var c=a>>1;for(var d=c+b/2;!(c>=d)&&z[c];)++c;c<<=1;if(32<c-a&&qd)return qd.decode(x.subarray(a,c));c="";for(d=0;!(d>=b/2);++d){var e=ta[a+2*d>>1];if(0==e)break;c+=String.fromCharCode(e)}return c},sd=(a,b,c)=>{c??=2147483647;if(2>c)return 0;c-=2;var d=b;c=c<2*a.length?c/2:a.length;for(var e=0;e<c;++e)ta[b>>1]=a.charCodeAt(e),b+=2;ta[b>>1]=0;return b-d},td=a=>2*a.length,ud=(a,b)=>{for(var c=0,d="";!(c>=b/4);){var e=B[a+4*c>>2];if(0==e)break;++c;65536<=
e?(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023)):d+=String.fromCharCode(e)}return d},vd=(a,b,c)=>{c??=2147483647;if(4>c)return 0;var d=b;c=d+c-4;for(var e=0;e<a.length;++e){var f=a.charCodeAt(e);if(55296<=f&&57343>=f){var g=a.charCodeAt(++e);f=65536+((f&1023)<<10)|g&1023}B[b>>2]=f;b+=4;if(b+4>c)break}B[b>>2]=0;return b-d},wd=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&++c;b+=4}return b},xd=(a,b)=>{var c=rc[a];if(void 0===c)throw a=b+" has unknown type "+
ed(a),new S(a);return c},yd=(a,b,c)=>{var d=[];a=a.toWireType(d,c);d.length&&(C[b>>2]=T(d));return a},zd=[],Ad={},Bd=a=>{var b=Ad[a];return void 0===b?R(a):b},Cd=()=>{function a(b){b.$$$embind_global$$$=b;var c="object"==typeof $$$embind_global$$$&&b.$$$embind_global$$$==b;c||delete b.$$$embind_global$$$;return c}if("object"==typeof globalThis)return globalThis;if("object"==typeof $$$embind_global$$$)return $$$embind_global$$$;"object"==typeof global&&a(global)?$$$embind_global$$$=global:"object"==
typeof self&&a(self)&&($$$embind_global$$$=self);if("object"==typeof $$$embind_global$$$)return $$$embind_global$$$;throw Error("unable to get global object.");},Dd=a=>{var b=zd.length;zd.push(a);return b},Ed=(a,b)=>{for(var c=Array(a),d=0;d<a;++d)c[d]=xd(C[b+4*d>>2],"parameter "+d);return c},Fd=Reflect.construct,Gd=a=>0===a%4&&(0!==a%100||0===a%400),Hd=[0,31,60,91,121,152,182,213,244,274,305,335],Id=[0,31,59,90,120,151,181,212,243,273,304,334],Jd=(a,b)=>b+2097152>>>0<4194305-!!a?(a>>>0)+4294967296*
b:NaN,Ld=a=>{var b=db(a)+1,c=Kd(b);c&&K(a,x,c,b);return c},Md=[],Nd,Od,Pd=0;
function Qd(a,b,c,d,e){function f(){var D=0,W=0;y.response&&J&&0===C[a+12>>2]&&(W=y.response.byteLength);0<W&&(D=Kd(W),x.set(new Uint8Array(y.response),D));C[a+12>>2]=D;Y(a+16,W);Y(a+24,0);(D=y.response?y.response.byteLength:0)&&Y(a+32,D);z[a+40>>1]=y.readyState;z[a+42>>1]=y.status;y.statusText&&K(y.statusText,x,a+44,64)}var g=C[a+8>>2];if(g){var m=g?I(x,g):"",l=a+112,n=ic(l+0);n||="GET";var q=C[l+56>>2],p=C[l+68>>2],t=C[l+72>>2];g=C[l+76>>2];var h=C[l+80>>2],r=C[l+84>>2],w=C[l+88>>2],A=C[l+52>>2],
J=!!(A&1),H=!!(A&2);A=!!(A&64);p=p?p?I(x,p):"":void 0;t=t?t?I(x,t):"":void 0;var y=new XMLHttpRequest;y.withCredentials=!!x[l+60>>0];y.open(n,m,!A,p,t);A||(y.timeout=q);y.pd=m;y.responseType="arraybuffer";h&&(m=h?I(x,h):"",y.overrideMimeType(m));if(g)for(;;){l=C[g>>2];if(!l)break;m=C[g+4>>2];if(!m)break;g+=8;l=l?I(x,l):"";m=m?I(x,m):"";y.setRequestHeader(l,m)}var P=Nd.rb(y);C[a>>2]=P;g=r&&w?x.slice(r,r+w):null;y.onload=D=>{Nd.has(P)&&(f(),200<=y.status&&300>y.status?b?.(a,y,D):c?.(a,y,D))};y.onerror=
D=>{Nd.has(P)&&(f(),c?.(a,y,D))};y.ontimeout=D=>{Nd.has(P)&&c?.(a,y,D)};y.onprogress=D=>{if(Nd.has(P)){var W=J&&H&&y.response?y.response.byteLength:0,G=0;0<W&&J&&H&&(G=Kd(W),x.set(new Uint8Array(y.response),G));C[a+12>>2]=G;Y(a+16,W);Y(a+24,D.loaded-W);Y(a+32,D.total);z[a+40>>1]=y.readyState;3<=y.readyState&&0===y.status&&0<D.loaded&&(y.status=200);z[a+42>>1]=y.status;y.statusText&&K(y.statusText,x,a+44,64);d?.(a,y,D);G&&dd(G)}};y.onreadystatechange=D=>{Nd.has(P)?(z[a+40>>1]=y.readyState,2<=y.readyState&&
(z[a+42>>1]=y.status),e?.(a,y,D)):--Pd};try{y.send(g)}catch(D){c?.(a,y,D)}}else c(a,0,"no url specified!")}var Td=a=>{sa=a;if(!(Ua||0<Pd)){Rd();Sa(Aa);cc=!1;Sd(0);for(var b=0;b<Ab.length;b++){var c=Ab[b];c&&$b(c)}Ca=!0}sa=a;Ua||0<Pd||(k.onExit?.(a),ra=!0);ea(a,new Ra(a))},Y=(a,b)=>{C[a>>2]=b;C[a+4>>2]=(b-C[a>>2])/4294967296};
function Ud(a,b,c,d){var e=Od;if(e){var f=C[a+112+64>>2];f||=C[a+8>>2];var g=f?I(x,f):"";try{var m=e.transaction(["FILES"],"readwrite").objectStore("FILES").put(b,g);m.onsuccess=()=>{z[a+40>>1]=4;z[a+42>>1]=200;K("OK",x,a+44,64);c(a,0,g)};m.onerror=l=>{z[a+40>>1]=4;z[a+42>>1]=413;K("Payload Too Large",x,a+44,64);d(a,0,l)}}catch(l){d(a,0,l)}}else d(a,0,"IndexedDB not available!")}
function Vd(a,b,c){var d=Od;if(d){var e=C[a+112+64>>2];e||=C[a+8>>2];e=e?I(x,e):"";try{var f=d.transaction(["FILES"],"readonly").objectStore("FILES").get(e);f.onsuccess=g=>{if(g.target.result){g=g.target.result;var m=g.byteLength||g.length,l=Kd(m);x.set(new Uint8Array(g),l);C[a+12>>2]=l;Y(a+16,m);Y(a+24,0);Y(a+32,m);z[a+40>>1]=4;z[a+42>>1]=200;K("OK",x,a+44,64);b(a,0,g)}else z[a+40>>1]=4,z[a+42>>1]=404,K("Not Found",x,a+44,64),c(a,0,"no data")};f.onerror=g=>{z[a+40>>1]=4;z[a+42>>1]=404;K("Not Found",
x,a+44,64);c(a,0,g)}}catch(g){c(a,0,g)}}else c(a,0,"IndexedDB not available!")}
function Wd(a,b,c){var d=Od;if(d){var e=C[a+112+64>>2];e||=C[a+8>>2];e=e?I(x,e):"";try{var f=d.transaction(["FILES"],"readwrite").objectStore("FILES").delete(e);f.onsuccess=g=>{g=g.target.result;C[a+12>>2]=0;Y(a+16,0);Y(a+24,0);Y(a+32,0);z[a+40>>1]=4;z[a+42>>1]=200;K("OK",x,a+44,64);b(a,0,g)};f.onerror=g=>{z[a+40>>1]=4;z[a+42>>1]=404;K("Not Found",x,a+44,64);c(a,0,g)}}catch(g){c(a,0,g)}}else c(a,0,"IndexedDB not available!")}
var Xd={},Zd=()=>{if(!Yd){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"==typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:da||"./this.program"},b;for(b in Xd)void 0===Xd[b]?delete a[b]:a[b]=Xd[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);Yd=c}return Yd},Yd,$d=[31,29,31,30,31,30,31,31,30,31,30,31],ae=[31,28,31,30,31,30,31,31,30,31,30,31],be=(a,b,c,d)=>{function e(h,r,w){for(h="number"==typeof h?h.toString():
h||"";h.length<r;)h=w[0]+h;return h}function f(h,r){return e(h,r,"0")}function g(h,r){function w(J){return 0>J?-1:0<J?1:0}var A;0===(A=w(h.getFullYear()-r.getFullYear()))&&0===(A=w(h.getMonth()-r.getMonth()))&&(A=w(h.getDate()-r.getDate()));return A}function m(h){switch(h.getDay()){case 0:return new Date(h.getFullYear()-1,11,29);case 1:return h;case 2:return new Date(h.getFullYear(),0,3);case 3:return new Date(h.getFullYear(),0,2);case 4:return new Date(h.getFullYear(),0,1);case 5:return new Date(h.getFullYear()-
1,11,31);case 6:return new Date(h.getFullYear()-1,11,30)}}function l(h){var r=h.lb;for(h=new Date((new Date(h.mb+1900,0,1)).getTime());0<r;){var w=h.getMonth(),A=(Gd(h.getFullYear())?$d:ae)[w];if(r>A-h.getDate())r-=A-h.getDate()+1,h.setDate(1),11>w?h.setMonth(w+1):(h.setMonth(0),h.setFullYear(h.getFullYear()+1));else{h.setDate(h.getDate()+r);break}}w=new Date(h.getFullYear()+1,0,4);r=m(new Date(h.getFullYear(),0,4));w=m(w);return 0>=g(r,h)?0>=g(w,h)?h.getFullYear()+1:h.getFullYear():h.getFullYear()-
1}var n=C[d+40>>2];d={$c:B[d>>2],Zc:B[d+4>>2],Kb:B[d+8>>2],Wb:B[d+12>>2],Lb:B[d+16>>2],mb:B[d+20>>2],fb:B[d+24>>2],lb:B[d+28>>2],od:B[d+32>>2],Yc:B[d+36>>2],ad:n?n?I(x,n):"":""};c=c?I(x,c):"";n={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S","%x":"%m/%d/%y","%X":"%H:%M:%S","%Ec":"%c","%EC":"%C","%Ex":"%m/%d/%y","%EX":"%H:%M:%S","%Ey":"%y","%EY":"%Y","%Od":"%d","%Oe":"%e","%OH":"%H","%OI":"%I","%Om":"%m","%OM":"%M","%OS":"%S","%Ou":"%u",
"%OU":"%U","%OV":"%V","%Ow":"%w","%OW":"%W","%Oy":"%y"};for(var q in n)c=c.replace(new RegExp(q,"g"),n[q]);var p="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),t="January February March April May June July August September October November December".split(" ");n={"%a":h=>p[h.fb].substring(0,3),"%A":h=>p[h.fb],"%b":h=>t[h.Lb].substring(0,3),"%B":h=>t[h.Lb],"%C":h=>f((h.mb+1900)/100|0,2),"%d":h=>f(h.Wb,2),"%e":h=>e(h.Wb,2," "),"%g":h=>l(h).toString().substring(2),"%G":l,"%H":h=>
f(h.Kb,2),"%I":h=>{h=h.Kb;0==h?h=12:12<h&&(h-=12);return f(h,2)},"%j":h=>{for(var r=0,w=0;w<=h.Lb-1;r+=(Gd(h.mb+1900)?$d:ae)[w++]);return f(h.Wb+r,3)},"%m":h=>f(h.Lb+1,2),"%M":h=>f(h.Zc,2),"%n":()=>"\n","%p":h=>0<=h.Kb&&12>h.Kb?"AM":"PM","%S":h=>f(h.$c,2),"%t":()=>"\t","%u":h=>h.fb||7,"%U":h=>f(Math.floor((h.lb+7-h.fb)/7),2),"%V":h=>{var r=Math.floor((h.lb+7-(h.fb+6)%7)/7);2>=(h.fb+371-h.lb-2)%7&&r++;if(r)53==r&&(w=(h.fb+371-h.lb)%7,4==w||3==w&&Gd(h.mb)||(r=1));else{r=52;var w=(h.fb+7-h.lb-1)%7;(4==
w||5==w&&Gd(h.mb%400-1))&&r++}return f(r,2)},"%w":h=>h.fb,"%W":h=>f(Math.floor((h.lb+7-(h.fb+6)%7)/7),2),"%y":h=>(h.mb+1900).toString().substring(2),"%Y":h=>h.mb+1900,"%z":h=>{h=h.Yc;var r=0<=h;h=Math.abs(h)/60;return(r?"+":"-")+String("0000"+(h/60*100+h%60)).slice(-4)},"%Z":h=>h.ad,"%%":()=>"%"};c=c.replace(/%%/g,"\x00\x00");for(q in n)c.includes(q)&&(c=c.replace(new RegExp(q,"g"),n[q](d)));c=c.replace(/\0\0/g,"%");q=eb(c,!1);if(q.length>b)return 0;v.set(q,a);return q.length-1};
function Jb(a,b,c,d){a||=this;this.parent=a;this.gb=a.gb;this.ub=null;this.id=Bb++;this.name=b;this.mode=c;this.Ma={};this.Na={};this.wb=d}Object.defineProperties(Jb.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}},Mc:{get:function(){return N(this.mode)}},Lc:{get:function(){return 8192===(this.mode&61440)}}});
[44].forEach(a=>{qb[a]=new L(a);qb[a].stack="<generic error, no stack>"});Cb=Array(4096);Pb(M,"/");Rb("/tmp");Rb("/home");Rb("/home/web_user");(function(){Rb("/dev");hb(259,{read:()=>0,write:(d,e,f,g)=>g});Sb("/dev/null",259);gb(1280,jb);gb(1536,kb);Sb("/dev/tty",1280);Sb("/dev/tty1",1536);var a=new Uint8Array(1024),b=0,c=()=>{0===b&&(b=$a(a).byteLength);return a[--b]};fc("/dev","random",c);fc("/dev","urandom",c);Rb("/dev/shm");Rb("/dev/shm/tmp")})();
(function(){Rb("/proc");var a=Rb("/proc/self");Rb("/proc/self/fd");Pb({gb(){var b=pb(a,"fd",16895,73);b.Ma={sb(c,d){var e=O(+d);c={parent:null,gb:{hc:"fake"},Ma:{xb:()=>e.path}};return c.parent=c}};return b}},"/proc/self/fd")})();k.FS_createPath=dc;k.FS_createDataFile=vb;k.FS_createPreloadedFile=wb;k.FS_unlink=Ub;k.FS_createLazyFile=hc;k.FS_createDevice=fc;tc=k.InternalError=class extends Error{constructor(a){super(a);this.name="InternalError"}};for(var ce=Array(256),de=0;256>de;++de)ce[de]=String.fromCharCode(de);
wc=ce;S=k.BindingError=class extends Error{constructor(a){super(a);this.name="BindingError"}};
Object.assign(Kc.prototype,{isAliasOf:function(a){if(!(this instanceof Kc&&a instanceof Kc))return!1;var b=this.Ka.Sa.Oa,c=this.Ka.Pa;a.Ka=a.Ka;var d=a.Ka.Sa.Oa;for(a=a.Ka.Pa;b.Ya;)c=b.yb(c),b=b.Ya;for(;d.Ya;)a=d.yb(a),d=d.Ya;return b===d&&c===a},clone:function(){this.Ka.Pa||yc(this);if(this.Ka.vb)return this.Ka.count.value+=1,this;var a=Ic,b=Object,c=b.create,d=Object.getPrototypeOf(this),e=this.Ka;a=a(c.call(b,d,{Ka:{value:{count:e.count,ob:e.ob,vb:e.vb,Pa:e.Pa,Sa:e.Sa,Ta:e.Ta,$a:e.$a}}}));a.Ka.count.value+=
1;a.Ka.ob=!1;return a},["delete"](){this.Ka.Pa||yc(this);if(this.Ka.ob&&!this.Ka.vb)throw new S("Object already scheduled for deletion");Ac(this);var a=this.Ka;--a.count.value;0===a.count.value&&(a.Ta?a.$a.eb(a.Ta):a.Sa.Oa.eb(a.Pa));this.Ka.vb||(this.Ka.Ta=void 0,this.Ka.Pa=void 0)},isDeleted:function(){return!this.Ka.Pa},deleteLater:function(){this.Ka.Pa||yc(this);if(this.Ka.ob&&!this.Ka.vb)throw new S("Object already scheduled for deletion");Dc.push(this);1===Dc.length&&Fc&&Fc(Ec);this.Ka.ob=!0;
return this}});k.getInheritedInstanceCount=()=>Object.keys(Gc).length;k.getLiveInheritedInstances=()=>{var a=[],b;for(b in Gc)Gc.hasOwnProperty(b)&&a.push(Gc[b]);return a};k.flushPendingDeletes=Ec;k.setDelayFunction=a=>{Fc=a;Dc.length&&Fc&&Fc(Ec)};
Object.assign(Wc.prototype,{Cc(a){this.jc&&(a=this.jc(a));return a},ac(a){this.eb?.(a)},argPackAdvance:8,readValueFromPointer:Vc,fromWireType:function(a){function b(){return this.Fb?Jc(this.Oa.pb,{Sa:this.Qc,Pa:c,$a:this,Ta:a}):Jc(this.Oa.pb,{Sa:this,Pa:a})}var c=this.Cc(a);if(!c)return this.ac(a),null;var d=Hc(this.Oa,c);if(void 0!==d){if(0===d.Ka.count.value)return d.Ka.Pa=c,d.Ka.Ta=a,d.clone();d=d.clone();this.ac(a);return d}d=this.Oa.Bc(c);d=Cc[d];if(!d)return b.call(this);d=this.Eb?d.wc:d.pointerType;
var e=Bc(c,this.Oa,d.Oa);return null===e?b.call(this):this.Fb?Jc(d.Oa.pb,{Sa:d,Pa:e,$a:this,Ta:a}):Jc(d.Oa.pb,{Sa:d,Pa:e})}});bd=k.UnboundTypeError=((a,b)=>{var c=Lc(b,function(d){this.name=b;this.message=d;d=Error(d).stack;void 0!==d&&(this.stack=this.toString()+"\n"+d.replace(/^Error(:[^\n]*)?\n/,""))});c.prototype=Object.create(a.prototype);c.prototype.constructor=c;c.prototype.toString=function(){return void 0===this.message?this.name:`${this.name}: ${this.message}`};return c})(Error,"UnboundTypeError");
V.Xa.push({value:void 0},{value:null},{value:!0},{value:!1});Object.assign(V,{nc:V.Xa.length});k.count_emval_handles=()=>{for(var a=0,b=V.nc;b<V.Xa.length;++b)void 0!==V.Xa[b]&&++a;return a};Nd=new ld;Ha("library_fetch_init");
(function(a,b){try{var c=indexedDB.open("emscripten_filesystem",1)}catch(d){b(d);return}c.onupgradeneeded=d=>{d=d.target.result;d.objectStoreNames.contains("FILES")&&d.deleteObjectStore("FILES");d.createObjectStore("FILES")};c.onsuccess=d=>a(d.target.result);c.onerror=b})(a=>{Od=a;Ia("library_fetch_init")},()=>{Od=!1;Ia("library_fetch_init")});
var je={A:function(a,b,c){lc=c;try{var d=O(a);switch(b){case 0:var e=mc();if(0>e)break;for(;Ab[e];)e++;return Nb(d,e).ib;case 1:case 2:return 0;case 3:return d.flags;case 4:return e=mc(),d.flags|=e,0;case 12:return e=mc(),ta[e+0>>1]=2,0;case 13:case 14:return 0}return-28}catch(f){if("undefined"==typeof Q||"ErrnoError"!==f.name)throw f;return-f.Ua}},ba:function(a,b){try{var c=O(a);return kc(Vb,c.path,b)}catch(d){if("undefined"==typeof Q||"ErrnoError"!==d.name)throw d;return-d.Ua}},ca:function(a,b,
c){lc=c;try{var d=O(a);switch(b){case 21509:return d.Qa?0:-59;case 21505:if(!d.Qa)return-59;if(d.Qa.hb.Ic){a=[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0];var e=mc();B[e>>2]=25856;B[e+4>>2]=5;B[e+8>>2]=191;B[e+12>>2]=35387;for(var f=0;32>f;f++)v[e+f+17>>0]=a[f]||0}return 0;case 21510:case 21511:case 21512:return d.Qa?0:-59;case 21506:case 21507:case 21508:if(!d.Qa)return-59;if(d.Qa.hb.Jc)for(e=mc(),a=[],f=0;32>f;f++)a.push(v[e+f+17>>0]);return 0;case 21519:if(!d.Qa)return-59;
e=mc();return B[e>>2]=0;case 21520:return d.Qa?-28:-59;case 21531:e=mc();if(!d.Na.Hc)throw new L(59);return d.Na.Hc(d,b,e);case 21523:if(!d.Qa)return-59;d.Qa.hb.Kc&&(f=[24,80],e=mc(),ta[e>>1]=f[0],ta[e+2>>1]=f[1]);return 0;case 21524:return d.Qa?0:-59;case 21515:return d.Qa?0:-59;default:return-28}}catch(g){if("undefined"==typeof Q||"ErrnoError"!==g.name)throw g;return-g.Ua}},_:function(a,b){try{return a=a?I(x,a):"",kc(Wb,a,b)}catch(c){if("undefined"==typeof Q||"ErrnoError"!==c.name)throw c;return-c.Ua}},
Z:function(a,b,c,d){try{b=b?I(x,b):"";var e=d&256;b=jc(a,b,d&4096);return kc(e?Wb:Vb,b,c)}catch(f){if("undefined"==typeof Q||"ErrnoError"!==f.name)throw f;return-f.Ua}},B:function(a,b,c,d){lc=d;try{b=b?I(x,b):"";b=jc(a,b);var e=d?mc():0;return Yb(b,c,e).ib}catch(f){if("undefined"==typeof Q||"ErrnoError"!==f.name)throw f;return-f.Ua}},$:function(a,b){try{return a=a?I(x,a):"",kc(Vb,a,b)}catch(c){if("undefined"==typeof Q||"ErrnoError"!==c.name)throw c;return-c.Ua}},d:a=>{var b=nc[a];delete nc[a];var c=
b.Tb,d=b.eb,e=b.bc,f=e.map(g=>g.Ec).concat(e.map(g=>g.Vc));vc([a],f,g=>{var m={};e.forEach((l,n)=>{var q=g[n],p=l.Db,t=l.Dc,h=g[n+e.length],r=l.Uc,w=l.Wc;m[l.Ac]={read:A=>q.fromWireType(p(t,A)),write:(A,J)=>{var H=[];r(w,A,h.toWireType(H,J));oc(H)}}});return[{name:b.name,fromWireType:l=>{var n={},q;for(q in m)n[q]=m[q].read(l);d(l);return n},toWireType:(l,n)=>{for(var q in m)if(!(q in n))throw new TypeError(`Missing field: "${q}"`);var p=c();for(q in m)m[q].write(p,n[q]);null!==l&&l.push(d,p);return p},
argPackAdvance:8,readValueFromPointer:pc,ab:d}]})},M:()=>{},fa:(a,b,c,d)=>{b=R(b);uc(a,{name:b,fromWireType:function(e){return!!e},toWireType:function(e,f){return f?c:d},argPackAdvance:8,readValueFromPointer:function(e){return this.fromWireType(x[e])},ab:null})},n:(a,b,c,d,e,f,g,m,l,n,q,p,t)=>{q=R(q);f=ad(e,f);m&&=ad(g,m);n&&=ad(l,n);t=ad(p,t);var h=Oc(q);Nc(h,function(){fd(`Cannot construct ${q} due to unbound types`,[d])});vc([a,b,c],d?[d]:[],function(r){r=r[0];if(d){var w=r.Oa;var A=w.pb}else A=
Kc.prototype;r=Lc(q,function(){if(Object.getPrototypeOf(this)!==J)throw new S("Use 'new' to construct "+q);if(void 0===H.jb)throw new S(q+" has no accessible constructor");var P=H.jb[arguments.length];if(void 0===P)throw new S(`Tried to invoke ctor of ${q} with invalid number of parameters (${arguments.length}) - expected (${Object.keys(H.jb).toString()}) parameters instead!`);return P.apply(this,arguments)});var J=Object.create(A,{constructor:{value:r}});r.prototype=J;var H=new Pc(q,r,J,t,w,f,m,
n);if(H.Ya){var y;(y=H.Ya).Xb??(y.Xb=[]);H.Ya.Xb.push(H)}w=new Wc(q,H,!0,!1,!1);y=new Wc(q+"*",H,!1,!1,!1);A=new Wc(q+" const*",H,!1,!0,!1);Cc[a]={pointerType:y,wc:A};Xc(h,r);return[w,y,A]})},r:(a,b,c,d,e,f)=>{var g=gd(b,c);e=ad(d,e);vc([],[a],function(m){m=m[0];var l=`constructor ${m.name}`;void 0===m.Oa.jb&&(m.Oa.jb=[]);if(void 0!==m.Oa.jb[b-1])throw new S(`Cannot register multiple constructors with identical number of parameters (${b-1}) for class '${m.name}'! Overload resolution is currently only performed using the parameter count, not actual type info!`);
m.Oa.jb[b-1]=()=>{fd(`Cannot construct ${m.name} due to unbound types`,g)};vc([],g,n=>{n.splice(1,0,null);m.Oa.jb[b-1]=jd(l,n,null,e,f);return[]});return[]})},h:(a,b,c,d,e,f,g,m)=>{var l=gd(c,d);b=R(b);b=kd(b);f=ad(e,f);vc([],[a],function(n){function q(){fd(`Cannot call ${p} due to unbound types`,l)}n=n[0];var p=`${n.name}.${b}`;b.startsWith("@@")&&(b=Symbol[b.substring(2)]);m&&n.Oa.Rc.push(b);var t=n.Oa.pb,h=t[b];void 0===h||void 0===h.Wa&&h.className!==n.name&&h.zb===c-2?(q.zb=c-2,q.className=n.name,
t[b]=q):(Mc(t,b,p),t[b].Wa[c-2]=q);vc([],l,function(r){r=jd(p,r,n,f,g);void 0===t[b].Wa?(r.zb=c-2,t[b]=r):t[b].Wa[c-2]=r;return[]});return[]})},ea:a=>uc(a,nd),D:(a,b,c)=>{b=R(b);uc(a,{name:b,fromWireType:d=>d,toWireType:(d,e)=>e,argPackAdvance:8,readValueFromPointer:od(b,c),ab:null})},w:(a,b,c,d,e,f)=>{var g=gd(b,c);a=R(a);a=kd(a);e=ad(d,e);Nc(a,function(){fd(`Cannot call ${a} due to unbound types`,g)},b-1);vc([],g,function(m){Xc(a,jd(a,[m[0],null].concat(m.slice(1)),null,e,f),b-1);return[]})},l:(a,
b,c,d,e)=>{b=R(b);-1===e&&(e=4294967295);e=m=>m;if(0===d){var f=32-8*c;e=m=>m<<f>>>f}var g=b.includes("unsigned")?function(m,l){return l>>>0}:function(m,l){return l};uc(a,{name:b,fromWireType:e,toWireType:g,argPackAdvance:8,readValueFromPointer:pd(b,c,0!==d),ab:null})},g:(a,b,c)=>{function d(f){return new e(v.buffer,C[f+4>>2],C[f>>2])}var e=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array][b];c=R(c);uc(a,{name:c,fromWireType:d,argPackAdvance:8,readValueFromPointer:d},
{Gc:!0})},E:(a,b)=>{b=R(b);var c="std::string"===b;uc(a,{name:b,fromWireType:function(d){var e=C[d>>2],f=d+4;if(c)for(var g=f,m=0;m<=e;++m){var l=f+m;if(m==e||0==x[l]){g=g?I(x,g,l-g):"";if(void 0===n)var n=g;else n+=String.fromCharCode(0),n+=g;g=l+1}}else{n=Array(e);for(m=0;m<e;++m)n[m]=String.fromCharCode(x[f+m]);n=n.join("")}dd(d);return n},toWireType:function(d,e){e instanceof ArrayBuffer&&(e=new Uint8Array(e));var f="string"==typeof e;if(!(f||e instanceof Uint8Array||e instanceof Uint8ClampedArray||
e instanceof Int8Array))throw new S("Cannot pass non-string to std::string");var g=c&&f?db(e):e.length;var m=Kd(4+g+1),l=m+4;C[m>>2]=g;if(c&&f)K(e,x,l,g+1);else if(f)for(f=0;f<g;++f){var n=e.charCodeAt(f);if(255<n)throw dd(l),new S("String has UTF-16 code units that do not fit in 8 bits");x[l+f]=n}else for(f=0;f<g;++f)x[l+f]=e[f];null!==d&&d.push(dd,m);return m},argPackAdvance:8,readValueFromPointer:Vc,ab(d){dd(d)}})},v:(a,b,c)=>{c=R(c);if(2===b){var d=rd;var e=sd;var f=td;var g=()=>z;var m=1}else 4===
b&&(d=ud,e=vd,f=wd,g=()=>C,m=2);uc(a,{name:c,fromWireType:l=>{for(var n=C[l>>2],q=g(),p,t=l+4,h=0;h<=n;++h){var r=l+4+h*b;if(h==n||0==q[r>>m])t=d(t,r-t),void 0===p?p=t:(p+=String.fromCharCode(0),p+=t),t=r+b}dd(l);return p},toWireType:(l,n)=>{if("string"!=typeof n)throw new S(`Cannot pass non-string to C++ string type ${c}`);var q=f(n),p=Kd(4+q+b);C[p>>2]=q>>m;e(n,p+4,q+b);null!==l&&l.push(dd,p);return p},argPackAdvance:8,readValueFromPointer:pc,ab(l){dd(l)}})},e:(a,b,c,d,e,f)=>{nc[a]={name:R(b),Tb:ad(c,
d),eb:ad(e,f),bc:[]}},c:(a,b,c,d,e,f,g,m,l,n)=>{nc[a].bc.push({Ac:R(b),Ec:c,Db:ad(d,e),Dc:f,Vc:g,Uc:ad(m,l),Wc:n})},ga:(a,b)=>{b=R(b);uc(a,{ld:!0,name:b,argPackAdvance:0,fromWireType:()=>{},toWireType:()=>{}})},ha:function(a){if(Nd.has(a)){var b=Nd.get(a),c=Nd;c.Xa[a]=void 0;c.Ob.push(a);0<b.readyState&&4>b.readyState&&b.abort()}},da:()=>1,Q:()=>{throw Infinity;},j:(a,b,c)=>{a=X(a);b=xd(b,"emval::as");return yd(b,c,a)},o:(a,b,c,d)=>{a=zd[a];b=X(b);return a(null,b,c,d)},p:(a,b,c,d,e)=>{a=zd[a];b=X(b);
c=Bd(c);return a(b,b[c],d,e)},R:md,G:(a,b)=>{a=X(a);b=X(b);return a==b},oa:a=>{if(0===a)return T(Cd());a=Bd(a);return T(Cd()[a])},k:(a,b,c)=>{var d=Ed(a,b),e=d.shift();a--;var f=Array(a);b=`methodCaller<(${d.map(g=>g.name).join(", ")}) => ${e.name}>`;return Dd(Lc(b,(g,m,l,n)=>{for(var q=0,p=0;p<a;++p)f[p]=d[p].readValueFromPointer(n+q),q+=d[p].argPackAdvance;g=1===c?Fd(m,f):m.apply(g,f);return yd(e,l,g)}))},x:(a,b)=>{a=X(a);b=X(b);return T(a[b])},q:a=>{4<a&&(V.get(a).lc+=1)},pa:(a,b)=>{a=X(a);b=X(b);
return a instanceof b},qa:()=>T([]),na:a=>T(Bd(a)),aa:()=>T({}),ra:a=>{var b=X(a);oc(b);md(a)},f:(a,b,c)=>{a=X(a);b=X(b);c=X(c);a[b]=c},i:(a,b)=>{a=xd(a,"_emval_take_value");a=a.readValueFromPointer(b);return T(a)},ma:a=>{a=X(a);return T(typeof a)},J:function(a,b,c){a=new Date(1E3*Jd(a,b));B[c>>2]=a.getSeconds();B[c+4>>2]=a.getMinutes();B[c+8>>2]=a.getHours();B[c+12>>2]=a.getDate();B[c+16>>2]=a.getMonth();B[c+20>>2]=a.getFullYear()-1900;B[c+24>>2]=a.getDay();B[c+28>>2]=(Gd(a.getFullYear())?Hd:Id)[a.getMonth()]+
a.getDate()-1|0;B[c+36>>2]=-(60*a.getTimezoneOffset());b=(new Date(a.getFullYear(),6,1)).getTimezoneOffset();var d=(new Date(a.getFullYear(),0,1)).getTimezoneOffset();B[c+32>>2]=(b!=d&&a.getTimezoneOffset()==Math.min(d,b))|0},K:function(a){var b=new Date(B[a+20>>2]+1900,B[a+16>>2],B[a+12>>2],B[a+8>>2],B[a+4>>2],B[a>>2],0),c=B[a+32>>2],d=b.getTimezoneOffset(),e=(new Date(b.getFullYear(),6,1)).getTimezoneOffset(),f=(new Date(b.getFullYear(),0,1)).getTimezoneOffset(),g=Math.min(f,e);0>c?B[a+32>>2]=Number(e!=
f&&g==d):0<c!=(g==d)&&(e=Math.max(f,e),b.setTime(b.getTime()+6E4*((0<c?g:e)-d)));B[a+24>>2]=b.getDay();B[a+28>>2]=(Gd(b.getFullYear())?Hd:Id)[b.getMonth()]+b.getDate()-1|0;B[a>>2]=b.getSeconds();B[a+4>>2]=b.getMinutes();B[a+8>>2]=b.getHours();B[a+12>>2]=b.getDate();B[a+16>>2]=b.getMonth();B[a+20>>2]=b.getYear();a=b.getTime();a=isNaN(a)?-1:a/1E3;return ee((E=a,1<=+Math.abs(E)?0<E?+Math.floor(E/4294967296)>>>0:~~+Math.ceil((E-+(~~E>>>0))/4294967296)>>>0:0)),a>>>0},H:function(a,b,c,d,e,f,g,m){e=Jd(e,
f);try{if(isNaN(e))return 61;var l=O(d);if(0!==(b&2)&&0===(c&2)&&2!==(l.flags&2097155))throw new L(2);if(1===(l.flags&2097155))throw new L(2);if(!l.Na.tb)throw new L(43);var n=l.Na.tb(l,a,e,b,c);var q=n.Pa;B[g>>2]=n.Xa;C[m>>2]=q;return 0}catch(p){if("undefined"==typeof Q||"ErrnoError"!==p.name)throw p;return-p.Ua}},I:function(a,b,c,d,e,f,g){f=Jd(f,g);try{if(isNaN(f))return 61;var m=O(e);if(c&2){if(32768!==(m.node.mode&61440))throw new L(43);d&2||m.Na.Hb&&m.Na.Hb(m,x.slice(a,a+b),f,b,d)}}catch(l){if("undefined"==
typeof Q||"ErrnoError"!==l.name)throw l;return-l.Ua}},V:(a,b,c)=>{function d(l){return(l=l.toTimeString().match(/\(([A-Za-z ]+)\)$/))?l[1]:"GMT"}var e=(new Date).getFullYear(),f=new Date(e,0,1),g=new Date(e,6,1);e=f.getTimezoneOffset();var m=g.getTimezoneOffset();C[a>>2]=60*Math.max(e,m);B[b>>2]=Number(e!=m);a=d(f);b=d(g);a=Ld(a);b=Ld(b);m<e?(C[c>>2]=a,C[c+4>>2]=b):(C[c>>2]=b,C[c+4>>2]=a)},b:()=>{pa("")},m:(a,b,c)=>{Md.length=0;for(var d;d=x[b++];){var e=105!=d;e&=112!=d;c+=e&&c%8?4:0;Md.push(112==
d?C[c>>2]:105==d?B[c>>2]:va[c>>3]);c+=e?8:4}return Qa[a].apply(null,Md)},C:()=>Date.now(),W:()=>2147483648,t:()=>performance.now(),ja:()=>!ha,U:a=>{var b=x.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=Math,e=Math.max(a,b+2097152/c);a:{d=(d.min.call(d,2147483648,e+(65536-e%65536)%65536)-qa.buffer.byteLength+65535)/65536;try{qa.grow(d);wa();var f=1;break a}catch(g){}f=void 0}if(f)return!0}return!1},ia:function(a,b,c,d,e){function f(G){if(t)G();else if(!Ca&&!ra)try{if(G(),!(Ca||
Ua||0<Pd))try{Td(sa)}catch(ma){ma instanceof Ra||"unwind"==ma||ea(1,ma)}}catch(ma){ma instanceof Ra||"unwind"==ma||ea(1,ma)}}Pd+=1;var g=a+112,m=C[g+36>>2],l=C[g+40>>2],n=C[g+44>>2],q=C[g+48>>2],p=C[g+52>>2],t=!!(p&64),h=G=>{--Pd;f(()=>{m?U(m)(G):b?.(G)})},r=G=>{f(()=>{n?U(n)(G):d?.(G)})},w=G=>{--Pd;f(()=>{l?U(l)(G):c?.(G)})},A=G=>{f(()=>{q?U(q)(G):e?.(G)})},J=G=>{Qd(G,h,w,r,A)},H=(G,ma)=>{Ud(G,ma.response,Ta=>{--Pd;f(()=>{m?U(m)(Ta):b?.(Ta)})},Ta=>{--Pd;f(()=>{m?U(m)(Ta):b?.(Ta)})})},y=G=>{Qd(G,
H,w,r,A)},P=ic(g+0),D=!!(p&16),W=!!(p&4);p=!!(p&32);if("EM_IDB_STORE"===P)J=C[g+84>>2],Ud(a,x.slice(J,J+C[g+88>>2]),h,w);else if("EM_IDB_DELETE"===P)Wd(a,h,w);else if(D){if(p)return 0;Qd(a,W?H:h,w,r,A)}else Vd(a,h,p?w:W?y:J);return a},X:(a,b)=>{var c=0;Zd().forEach((d,e)=>{var f=b+c;e=C[a+4*e>>2]=f;for(f=0;f<d.length;++f)v[e++>>0]=d.charCodeAt(f);v[e>>0]=0;c+=d.length+1});return 0},Y:(a,b)=>{var c=Zd();C[a>>2]=c.length;var d=0;c.forEach(e=>d+=e.length+1);C[b>>2]=d;return 0},F:Td,u:function(a){try{var b=
O(a);$b(b);return 0}catch(c){if("undefined"==typeof Q||"ErrnoError"!==c.name)throw c;return c.Ua}},z:function(a,b,c,d){try{a:{var e=O(a);a=b;for(var f,g=b=0;g<c;g++){var m=C[a>>2],l=C[a+4>>2];a+=8;var n=e,q=f,p=v;if(0>l||0>q)throw new L(28);if(null===n.ib)throw new L(8);if(1===(n.flags&2097155))throw new L(8);if(N(n.node.mode))throw new L(31);if(!n.Na.read)throw new L(28);var t="undefined"!=typeof q;if(!t)q=n.position;else if(!n.seekable)throw new L(70);var h=n.Na.read(n,p,m,l,q);t||(n.position+=
h);var r=h;if(0>r){var w=-1;break a}b+=r;if(r<l)break;"undefined"!==typeof f&&(f+=r)}w=b}C[d>>2]=w;return 0}catch(A){if("undefined"==typeof Q||"ErrnoError"!==A.name)throw A;return A.Ua}},L:function(a,b,c,d,e){b=Jd(b,c);try{if(isNaN(b))return 61;var f=O(a);ac(f,b,d);F=[f.position>>>0,(E=f.position,1<=+Math.abs(E)?0<E?+Math.floor(E/4294967296)>>>0:~~+Math.ceil((E-+(~~E>>>0))/4294967296)>>>0:0)];B[e>>2]=F[0];B[e+4>>2]=F[1];f.Pb&&0===b&&0===d&&(f.Pb=null);return 0}catch(g){if("undefined"==typeof Q||"ErrnoError"!==
g.name)throw g;return g.Ua}},s:function(a,b,c,d){try{a:{var e=O(a);a=b;for(var f,g=b=0;g<c;g++){var m=C[a>>2],l=C[a+4>>2];a+=8;var n=bc(e,v,m,l,f);if(0>n){var q=-1;break a}b+=n;"undefined"!==typeof f&&(f+=n)}q=b}C[d>>2]=q;return 0}catch(p){if("undefined"==typeof Q||"ErrnoError"!==p.name)throw p;return p.Ua}},ka:function(){var a=stackTrace(),b=db(a)+1,c=Kd(b);K(a,x,c,b);return c},S:(a,b)=>{$a(x.subarray(a,a+b));return 0},N:fe,y:ge,O:he,P:ie,a:qa,la:be,T:(a,b,c,d)=>be(a,b,c,d)},Z=function(){function a(c){Z=
c.exports;Zc=Z.va;za.unshift(Z.sa);Ia("wasm-instantiate");return Z}var b={a:je};Ha("wasm-instantiate");if(k.instantiateWasm)try{return k.instantiateWasm(b,a)}catch(c){u(`Module.instantiateWasm callback failed with error: ${c}`),ba(c)}Pa(b,function(c){a(c.instance)}).catch(ba);return{}}(),dd=a=>(dd=Z.ta)(a),Kd=a=>(Kd=Z.ua)(a),Sd=a=>(Sd=Z.wa)(a),cd=a=>(cd=Z.xa)(a),Rd=()=>(Rd=Z.ya)(),lb=(a,b)=>(lb=Z.za)(a,b),ke=(a,b)=>(ke=Z.Aa)(a,b),ee=a=>(ee=Z.Ba)(a),le=()=>(le=Z.Ca)(),me=a=>(me=Z.Da)(a);
k.dynCall_ji=(a,b)=>(k.dynCall_ji=Z.Ea)(a,b);k.dynCall_jiji=(a,b,c,d,e)=>(k.dynCall_jiji=Z.Fa)(a,b,c,d,e);k.dynCall_viijii=(a,b,c,d,e,f,g)=>(k.dynCall_viijii=Z.Ga)(a,b,c,d,e,f,g);k.dynCall_iiiiij=(a,b,c,d,e,f,g)=>(k.dynCall_iiiiij=Z.Ha)(a,b,c,d,e,f,g);k.dynCall_iiiiijj=(a,b,c,d,e,f,g,m,l)=>(k.dynCall_iiiiijj=Z.Ia)(a,b,c,d,e,f,g,m,l);k.dynCall_iiiiiijj=(a,b,c,d,e,f,g,m,l,n)=>(k.dynCall_iiiiiijj=Z.Ja)(a,b,c,d,e,f,g,m,l,n);k.__ZN2MB2NN28LinearDefragmentingAllocator10Allocation4nullE=1024;
k.___start_em_js=316548;k.___stop_em_js=317421;function ge(a,b){var c=le();try{U(a)(b)}catch(d){me(c);if(d!==d+0)throw d;ke(1,0)}}function ie(a,b,c,d){var e=le();try{U(a)(b,c,d)}catch(f){me(e);if(f!==f+0)throw f;ke(1,0)}}function he(a,b,c){var d=le();try{U(a)(b,c)}catch(e){me(d);if(e!==e+0)throw e;ke(1,0)}}function fe(a,b,c,d){var e=le();try{return U(a)(b,c,d)}catch(f){me(e);if(f!==f+0)throw f;ke(1,0)}}k.addRunDependency=Ha;k.removeRunDependency=Ia;k.FS_createPath=dc;k.FS_createLazyFile=hc;
k.FS_createDevice=fc;k.FS_createPreloadedFile=wb;k.FS_createDataFile=vb;k.FS_unlink=Ub;var ne;Ga=function oe(){ne||pe();ne||(Ga=oe)};
function pe(){function a(){if(!ne&&(ne=!0,k.calledRun=!0,!ra)){k.noFSInit||cc||(cc=!0,k.stdin=k.stdin,k.stdout=k.stdout,k.stderr=k.stderr,k.stdin?fc("/dev","stdin",k.stdin):Tb("/dev/tty","/dev/stdin"),k.stdout?fc("/dev","stdout",null,k.stdout):Tb("/dev/tty","/dev/stdout"),k.stderr?fc("/dev","stderr",null,k.stderr):Tb("/dev/tty1","/dev/stderr"),Yb("/dev/stdin",0),Yb("/dev/stdout",1),Yb("/dev/stderr",1));Db=!1;Sa(za);aa(k);if(k.onRuntimeInitialized)k.onRuntimeInitialized();if(k.postRun)for("function"==
typeof k.postRun&&(k.postRun=[k.postRun]);k.postRun.length;){var b=k.postRun.shift();Ba.unshift(b)}Sa(Ba)}}if(!(0<Ea)){if(k.preRun)for("function"==typeof k.preRun&&(k.preRun=[k.preRun]);k.preRun.length;)Da();Sa(ya);0<Ea||(k.setStatus?(k.setStatus("Running..."),setTimeout(function(){setTimeout(function(){k.setStatus("")},1);a()},1)):a())}}if(k.preInit)for("function"==typeof k.preInit&&(k.preInit=[k.preInit]);0<k.preInit.length;)k.preInit.pop()();pe();
if("object"==typeof window&&("undefined"==typeof ENVIRONMENT_IS_PTHREAD||!ENVIRONMENT_IS_PTHREAD)){var qe=()=>{var a=0,b=!1,c=l=>{var n=new XMLHttpRequest;n.open("POST","stdio.html",!1);n.send(l);try{window.close()}catch(q){}},d=l=>{var n=new XMLHttpRequest;++a;n.onreadystatechange=()=>{4==n.readyState&&0==--a&&b&&c("^exit^"+sa)};n.open("POST","stdio.html",!0);n.send(l)};if(-1!=document.URL.search("localhost")||-1!=document.URL.search(":6931/")){var e=1,f=na,g=u;Aa.unshift(()=>{0==a?c("^exit^"+sa):
b=!0});na=l=>{d("^out^"+e++ +"^"+encodeURIComponent(l));f(l)};u=l=>{d("^err^"+e++ +"^"+encodeURIComponent(l));g(l)};var m=()=>{try{d("^pageload^")}catch(l){setTimeout(m,50)}};m()}};"undefined"!=typeof document&&qe()};


  return moduleArg.ready
}
);
})();
if (typeof exports === 'object' && typeof module === 'object')
  module.exports = BlinkIDWasmSDK;
else if (typeof define === 'function' && define['amd'])
  define([], () => BlinkIDWasmSDK);
