
var BlinkIDWasmSDK = (() => {
  var _scriptDir = typeof document !== 'undefined' && document.currentScript ? document.currentScript.src : undefined;
  
  return (
function(config) {
  var BlinkIDWasmSDK = config || {};


function g(){q.buffer!=aa.buffer&&ba();return aa}function v(){q.buffer!=aa.buffer&&ba();return ca}function ea(){q.buffer!=aa.buffer&&ba();return fa}function w(){q.buffer!=aa.buffer&&ba();return ha}function A(){q.buffer!=aa.buffer&&ba();return ia}function B(){q.buffer!=aa.buffer&&ba();return ja}function ka(){q.buffer!=aa.buffer&&ba();return la}var D;D||(D=typeof BlinkIDWasmSDK !== 'undefined' ? BlinkIDWasmSDK : {});var ma,na;D.ready=new Promise(function(a,b){ma=a;na=b});D.lc||(D.lc=0);D.lc++;
D.ENVIRONMENT_IS_PTHREAD||function(a){function b(m,n,r){var p=new XMLHttpRequest;p.open("GET",m,!0);p.responseType="arraybuffer";p.onprogress=function(t){var k=n;t.total&&(k=t.total);if(t.loaded){p.Xc?D.Kb[m].loaded=t.loaded:(p.Xc=!0,D.Kb||(D.Kb={}),D.Kb[m]={loaded:t.loaded,total:k});var u=k=t=0,x;for(x in D.Kb){var z=D.Kb[x];t+=z.total;k+=z.loaded;u++}t=Math.ceil(t*D.lc/u);D.setStatus&&D.setStatus("Downloading data... ("+k+"/"+t+")")}else!D.Kb&&D.setStatus&&D.setStatus("Downloading data...")};p.onerror=
function(){throw Error("NetworkError for: "+m);};p.onload=function(){if(200==p.status||304==p.status||206==p.status||0==p.status&&p.response)r(p.response);else throw Error(p.statusText+" : "+p.responseURL);};p.send(null)}function c(m){console.error("package error:",m)}function d(){function m(t,k,u){this.start=t;this.end=k;this.audio=u}function n(t){if(!t)throw"Loading data file failed."+Error().stack;if(t.constructor.name!==ArrayBuffer.name)throw"bad input to processPackageData"+Error().stack;t=new Uint8Array(t);
m.prototype.bd=t;t=a.files;for(var k=0;k<t.length;++k)m.prototype.vc[t[k].filename].onload();D.removeRunDependency("datafile_/opt/jenkins/jenkinsData/E4/core-webassembly-sdks/SDKs/BlinkID/resources-lightweight/advanced-threads/BlinkIDWasmSDK.data")}D.FS_createPath("/","microblink",!0,!0);m.prototype={vc:{},open:function(t,k){this.name=k;this.vc[k]=this;D.addRunDependency("fp "+this.name)},send:function(){},onload:function(){this.finish(this.bd.subarray(this.start,this.end))},finish:function(t){D.FS_createDataFile(this.name,
null,t,!0,!0,!0);D.removeRunDependency("fp "+this.name);this.vc[this.name]=null}};for(var r=a.files,p=0;p<r.length;++p)(new m(r[p].start,r[p].end,r[p].audio||0)).open("GET",r[p].filename);D.addRunDependency("datafile_/opt/jenkins/jenkinsData/E4/core-webassembly-sdks/SDKs/BlinkID/resources-lightweight/advanced-threads/BlinkIDWasmSDK.data");D.Lc||(D.Lc={});D.Lc["/opt/jenkins/jenkinsData/E4/core-webassembly-sdks/SDKs/BlinkID/resources-lightweight/advanced-threads/BlinkIDWasmSDK.data"]={be:!1};l?(n(l),
l=null):h=n}"object"===typeof window?window.encodeURIComponent(window.location.pathname.toString().substring(0,window.location.pathname.toString().lastIndexOf("/"))+"/"):"undefined"===typeof process&&"undefined"!==typeof location&&encodeURIComponent(location.pathname.toString().substring(0,location.pathname.toString().lastIndexOf("/"))+"/");"function"!==typeof D.locateFilePackage||D.locateFile||(D.locateFile=D.locateFilePackage,E("warning: you defined Module.locateFilePackage, that has been renamed to Module.locateFile (using your locateFilePackage for now)"));
var e=D.locateFile?D.locateFile("BlinkIDWasmSDK.data",""):"BlinkIDWasmSDK.data",f=a.remote_package_size,h=null,l=D.getPreloadedPackage?D.getPreloadedPackage(e,f):null;l||b(e,f,function(m){h?(h(m),h=null):l=m},c);D.calledRun?d():(D.preRun||(D.preRun=[]),D.preRun.push(d))}({files:[{filename:"/microblink/Model_19d332fd742e2cc1f4d925a61caceb93ee3b225b3bad0c3966df7d1e3c9f6e0b.strop",start:0,end:430042},{filename:"/microblink/Model_2880751121560047e6dc571bc8ff4683aeb863886f7c0789234594ceb1e23577.strop",
start:430042,end:433980},{filename:"/microblink/Model_36d8e94f4cb46097bd6b7385f2aa91fcdee1a5fefeec59e56d1b9e82c94b00a7.strop",start:433980,end:803808},{filename:"/microblink/Model_473ac5f5e256623c0a6b282698c1f1b033b9fb5359e6aa142e9fb4a4022afe4e.strop",start:803808,end:810690},{filename:"/microblink/Model_500f4403bf221021bb85c3e758d59f69841635787f6f4201a4ffe5e68733f8bb.strop",start:810690,end:1393828},{filename:"/microblink/Model_5b6ea9ea320cf60db51d28292a50330f5915638e7bdcc0c7c2dc6d6c3e3d9655.strop",
start:1393828,end:2135910},{filename:"/microblink/Model_b452fd3cd4037080cfcb4c423dba5bc58c8ceafc28427fdf9c5778fb353f088e.strop",start:2135910,end:2142760},{filename:"/microblink/Model_e4f1f62f68ec44b71ecad3fb3f3b48fe3790beb5ab325611e17d63af06e9f644.strop",start:2142760,end:2199274},{filename:"/microblink/Model_ed586fd6ca47c8eebb513c4ffaaacc2c54e92162b145062d7022519fba0911de.strop",start:2199274,end:2912506},{filename:"/microblink/Model_f7f2ce138860672abe85ef788b82633f674cde6b121a6017be15f41f2451017a.strop",
start:2912506,end:5359030},{filename:"/microblink/Model_faf688599c7e261a2a7404730f69ed029115bb0d3e7a3657731d88e701720efe.strop",start:5359030,end:5375768},{filename:"/microblink/ccc_lookup_table.zzip",start:5375768,end:5396237},{filename:"/microblink/face_detector_model.zzip",start:5396237,end:5493095}],remote_package_size:5493095});D.onAbort=function(a){E("Aborted with message: "+a);try{throw new WebAssembly.RuntimeError(a);}catch(b){E("Stacktrace: "+b.stack)}};
var crypto={getRandomValues:function(a){for(var b=0;b<a.length;b++)a[b]=256*Math.random()|0}},oa=Object.assign({},D),pa="./this.program",qa=(a,b)=>{throw b;},ra="object"==typeof window,sa="function"==typeof importScripts,ta="object"==typeof process&&"object"==typeof process.$d&&"string"==typeof process.$d.node,F=D.ENVIRONMENT_IS_PTHREAD||!1,ua="";function va(a){return D.locateFile?D.locateFile(a,ua):ua+a}var wa,xa,ya;
if(ra||sa)sa?ua=self.location.href:"undefined"!=typeof document&&document.currentScript&&(ua=document.currentScript.src),_scriptDir&&(ua=_scriptDir),ua=0!==ua.indexOf("blob:")?ua.substr(0,ua.replace(/[?#].*/,"").lastIndexOf("/")+1):"",wa=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},sa&&(ya=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),xa=(a,b,c)=>{var d=new XMLHttpRequest;d.open("GET",
a,!0);d.responseType="arraybuffer";d.onload=()=>{200==d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)};var za=D.print||console.log.bind(console),E=D.printErr||console.warn.bind(console);Object.assign(D,oa);oa=null;D.thisProgram&&(pa=D.thisProgram);D.quit&&(qa=D.quit);var Aa;D.wasmBinary&&(Aa=D.wasmBinary);var noExitRuntime=D.noExitRuntime||!0;"object"!=typeof WebAssembly&&Ba("no native wasm support detected");
var q,Ca,Da=!1,Ea="undefined"!=typeof TextDecoder?new TextDecoder("utf8"):void 0;
function Fa(a,b,c){var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.buffer&&Ea)return Ea.decode(a.buffer instanceof SharedArrayBuffer?a.slice(b,c):a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var f=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|f);else{var h=a[b++]&63;e=224==(e&240)?(e&15)<<12|f<<6|h:(e&7)<<18|f<<12|h<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d}
function G(a,b){return a?Fa(v(),a,b):""}function Ga(a,b,c,d){if(!(0<d))return 0;var e=c;d=c+d-1;for(var f=0;f<a.length;++f){var h=a.charCodeAt(f);if(55296<=h&&57343>=h){var l=a.charCodeAt(++f);h=65536+((h&1023)<<10)|l&1023}if(127>=h){if(c>=d)break;b[c++]=h}else{if(2047>=h){if(c+1>=d)break;b[c++]=192|h>>6}else{if(65535>=h){if(c+2>=d)break;b[c++]=224|h>>12}else{if(c+3>=d)break;b[c++]=240|h>>18;b[c++]=128|h>>12&63}b[c++]=128|h>>6&63}b[c++]=128|h&63}}b[c]=0;return c-e}
function Ha(a,b,c){Ga(a,v(),b,c)}function Ia(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b}var aa,ca,fa,ha,ia,ja,Ja,la;function ba(){var a=q.buffer;D.HEAP8=aa=new Int8Array(a);D.HEAP16=fa=new Int16Array(a);D.HEAP32=ia=new Int32Array(a);D.HEAPU8=ca=new Uint8Array(a);D.HEAPU16=ha=new Uint16Array(a);D.HEAPU32=ja=new Uint32Array(a);D.HEAPF32=Ja=new Float32Array(a);D.HEAPF64=la=new Float64Array(a)}var Ka=D.INITIAL_MEMORY||209715200;
if(F)q=D.wasmMemory;else if(D.wasmMemory)q=D.wasmMemory;else if(q=new WebAssembly.Memory({initial:Ka/65536,maximum:12800,shared:!0}),!(q.buffer instanceof SharedArrayBuffer))throw E("requested a shared WebAssembly.Memory but the returned buffer is not a SharedArrayBuffer, indicating that while the browser has SharedArrayBuffer it does not have WebAssembly threads support - you may need to set a flag"),ta&&E("(on node you may need: --experimental-wasm-threads --experimental-wasm-bulk-memory and/or recent version)"),
Error("bad memory");ba();Ka=q.buffer.byteLength;var La,Ma=[],Na=[],Oa=[];function Pa(){F||(D.noFSInit||Qa||(Qa=!0,Ra(),D.stdin=D.stdin,D.stdout=D.stdout,D.stderr=D.stderr,D.stdin?Sa("/dev","stdin",D.stdin):Ta("/dev/tty","/dev/stdin"),D.stdout?Sa("/dev","stdout",null,D.stdout):Ta("/dev/tty","/dev/stdout"),D.stderr?Sa("/dev","stderr",null,D.stderr):Ta("/dev/tty1","/dev/stderr"),Ua("/dev/stdin",0),Ua("/dev/stdout",1),Ua("/dev/stderr",1)),Va=!1,Wa(Na))}
function Xa(){var a=D.preRun.shift();Ma.unshift(a)}var Za=0,$a=null,ab=null;function bb(){Za++;D.monitorRunDependencies&&D.monitorRunDependencies(Za)}function cb(){Za--;D.monitorRunDependencies&&D.monitorRunDependencies(Za);if(0==Za&&(null!==$a&&(clearInterval($a),$a=null),ab)){var a=ab;ab=null;a()}}function Ba(a){if(D.onAbort)D.onAbort(a);a="Aborted("+a+")";E(a);Da=!0;a=new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");na(a);throw a;}
function db(){return eb.startsWith("data:application/octet-stream;base64,")}var eb;eb="BlinkIDWasmSDK.wasm";db()||(eb=va(eb));function fb(){var a=eb;try{if(a==eb&&Aa)return new Uint8Array(Aa);if(ya)return ya(a);throw"both async and sync fetching of the wasm failed";}catch(b){Ba(b)}}
function gb(){return Aa||!ra&&!sa||"function"!=typeof fetch?Promise.resolve().then(function(){return fb()}):fetch(eb,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+eb+"'";return a.arrayBuffer()}).catch(function(){return fb()})}
var K,L,hb={449383:a=>{a=G(a);throw Error("Failed to reconfigure RecognizerRunner due to following error: "+a);},449519:(a,b,c,d)=>{a=G(a);b=G(b);c=G(c);d=G(d);throw Error(a+b+c+d);},449735:(a,b)=>{a=G(a);b=G(b);throw Error(a+b);},449845:(a,b)=>{a=G(a);b=G(b);console.log(a+b)},449943:a=>{throw Error(G(a));},449986:()=>{throw Error("Unable to perform that operation while recognizer is in use!");},450069:()=>{throw Error("Unable to perform that operation while recognizer is in use!");},450152:()=>{throw Error("Unable to perform that operation while recognizer is in use!");
}};function ib(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}function jb(a){(a=M.Cb[a])||Ba();M.Qc(a)}function kb(a){var b=M.ld();if(!b)return 6;M.Vb.push(b);M.Cb[a.Bb]=b;b.Bb=a.Bb;b.postMessage({cmd:"run",start_routine:a.Sd,arg:a.Yc,pthread_ptr:a.Bb},a.Yd);return 0}
var lb=(a,b)=>{for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a},mb=a=>{var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=lb(a.split("/").filter(d=>!!d),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a},nb=a=>{var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,b.length-1));return a+b},ob=a=>
{if("/"===a)return"/";a=mb(a);a=a.replace(/\/$/,"");var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)};function pb(){if("object"==typeof crypto&&"function"==typeof crypto.getRandomValues){var a=new Uint8Array(1);return()=>{crypto.getRandomValues(a);return a[0]}}return()=>Ba("randomDevice")}
function qb(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:"/";if("string"!=typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=lb(a.split("/").filter(d=>!!d),!b).join("/");return(b?"/":"")+a||"."}function rb(a,b){var c=Array(Ia(a)+1);a=Ga(a,c,0,c.length);b&&(c.length=a);return c}var sb=[];function tb(a,b){sb[a]={input:[],qb:[],Ob:b};ub(a,vb)}
var vb={open:function(a){var b=sb[a.node.Tb];if(!b)throw new N(43);a.ob=b;a.seekable=!1},close:function(a){a.ob.Ob.$b(a.ob)},$b:function(a){a.ob.Ob.$b(a.ob)},read:function(a,b,c,d){if(!a.ob||!a.ob.Ob.Hc)throw new N(60);for(var e=0,f=0;f<d;f++){try{var h=a.ob.Ob.Hc(a.ob)}catch(l){throw new N(29);}if(void 0===h&&0===e)throw new N(6);if(null===h||void 0===h)break;e++;b[c+f]=h}e&&(a.node.timestamp=Date.now());return e},write:function(a,b,c,d){if(!a.ob||!a.ob.Ob.rc)throw new N(60);try{for(var e=0;e<d;e++)a.ob.Ob.rc(a.ob,
b[c+e])}catch(f){throw new N(29);}d&&(a.node.timestamp=Date.now());return e}},wb={Hc:function(a){if(!a.input.length){var b=null;"undefined"!=typeof window&&"function"==typeof window.prompt?(b=window.prompt("Input: "),null!==b&&(b+="\n")):"function"==typeof readline&&(b=readline(),null!==b&&(b+="\n"));if(!b)return null;a.input=rb(b,!0)}return a.input.shift()},rc:function(a,b){null===b||10===b?(za(Fa(a.qb,0)),a.qb=[]):0!=b&&a.qb.push(b)},$b:function(a){a.qb&&0<a.qb.length&&(za(Fa(a.qb,0)),a.qb=[])}},
xb={rc:function(a,b){null===b||10===b?(E(Fa(a.qb,0)),a.qb=[]):0!=b&&a.qb.push(b)},$b:function(a){a.qb&&0<a.qb.length&&(E(Fa(a.qb,0)),a.qb=[])}};function yb(a){a=65536*Math.ceil(a/65536);var b=zb(65536,a);b?v().fill(0,b,b+a):b=0;return b}
var O={yb:null,Ab:function(){return O.createNode(null,"/",16895,0)},createNode:function(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new N(63);O.yb||(O.yb={dir:{node:{xb:O.ib.xb,tb:O.ib.tb,Pb:O.ib.Pb,dc:O.ib.dc,Pc:O.ib.Pc,kc:O.ib.kc,Rc:O.ib.Rc,Oc:O.ib.Oc,hc:O.ib.hc},stream:{Hb:O.jb.Hb}},file:{node:{xb:O.ib.xb,tb:O.ib.tb},stream:{Hb:O.jb.Hb,read:O.jb.read,write:O.jb.write,xc:O.jb.xc,Qb:O.jb.Qb,ec:O.jb.ec}},link:{node:{xb:O.ib.xb,tb:O.ib.tb,Ub:O.ib.Ub},stream:{}},Bc:{node:{xb:O.ib.xb,tb:O.ib.tb},
stream:Ab}});c=Bb(a,b,c,d);16384===(c.mode&61440)?(c.ib=O.yb.dir.node,c.jb=O.yb.dir.stream,c.hb={}):32768===(c.mode&61440)?(c.ib=O.yb.file.node,c.jb=O.yb.file.stream,c.mb=0,c.hb=null):40960===(c.mode&61440)?(c.ib=O.yb.link.node,c.jb=O.yb.link.stream):8192===(c.mode&61440)&&(c.ib=O.yb.Bc.node,c.jb=O.yb.Bc.stream);c.timestamp=Date.now();a&&(a.hb[b]=c,a.timestamp=c.timestamp);return c},ce:function(a){return a.hb?a.hb.subarray?a.hb.subarray(0,a.mb):new Uint8Array(a.hb):new Uint8Array(0)},Ec:function(a,
b){var c=a.hb?a.hb.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)>>>0),0!=c&&(b=Math.max(b,256)),c=a.hb,a.hb=new Uint8Array(b),0<a.mb&&a.hb.set(c.subarray(0,a.mb),0))},Fd:function(a,b){if(a.mb!=b)if(0==b)a.hb=null,a.mb=0;else{var c=a.hb;a.hb=new Uint8Array(b);c&&a.hb.set(c.subarray(0,Math.min(b,a.mb)));a.mb=b}},ib:{xb:function(a){var b={};b.gd=8192===(a.mode&61440)?a.id:1;b.oc=a.id;b.mode=a.mode;b.Ad=1;b.uid=0;b.pd=0;b.Tb=a.Tb;b.size=16384===(a.mode&61440)?4096:32768===(a.mode&61440)?a.mb:40960===
(a.mode&61440)?a.link.length:0;b.Zc=new Date(a.timestamp);b.zd=new Date(a.timestamp);b.dd=new Date(a.timestamp);b.$c=4096;b.ad=Math.ceil(b.size/b.$c);return b},tb:function(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);void 0!==b.size&&O.Fd(a,b.size)},Pb:function(){throw Cb[44];},dc:function(a,b,c,d){return O.createNode(a,b,c,d)},Pc:function(a,b,c){if(16384===(a.mode&61440)){try{var d=Db(b,c)}catch(f){}if(d)for(var e in d.hb)throw new N(55);}delete a.parent.hb[a.name];
a.parent.timestamp=Date.now();a.name=c;b.hb[c]=a;b.timestamp=a.parent.timestamp;a.parent=b},kc:function(a,b){delete a.hb[b];a.timestamp=Date.now()},Rc:function(a,b){var c=Db(a,b),d;for(d in c.hb)throw new N(55);delete a.hb[b];a.timestamp=Date.now()},Oc:function(a){var b=[".",".."],c;for(c in a.hb)a.hb.hasOwnProperty(c)&&b.push(c);return b},hc:function(a,b,c){a=O.createNode(a,b,41471,0);a.link=c;return a},Ub:function(a){if(40960!==(a.mode&61440))throw new N(28);return a.link}},jb:{read:function(a,
b,c,d,e){var f=a.node.hb;if(e>=a.node.mb)return 0;a=Math.min(a.node.mb-e,d);if(8<a&&f.subarray)b.set(f.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=f[e+d];return a},write:function(a,b,c,d,e,f){b.buffer===g().buffer&&(f=!1);if(!d)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&(!a.hb||a.hb.subarray)){if(f)return a.hb=b.subarray(c,c+d),a.mb=d;if(0===a.mb&&0===e)return a.hb=b.slice(c,c+d),a.mb=d;if(e+d<=a.mb)return a.hb.set(b.subarray(c,c+d),e),d}O.Ec(a,e+d);if(a.hb.subarray&&b.subarray)a.hb.set(b.subarray(c,
c+d),e);else for(f=0;f<d;f++)a.hb[e+f]=b[c+f];a.mb=Math.max(a.mb,e+d);return d},Hb:function(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.mb);if(0>b)throw new N(28);return b},xc:function(a,b,c){O.Ec(a.node,b+c);a.node.mb=Math.max(a.node.mb,b+c)},Qb:function(a,b,c,d,e){if(32768!==(a.node.mode&61440))throw new N(43);a=a.node.hb;if(e&2||a.buffer!==g().buffer){if(0<c||c+b<a.length)a=a.subarray?a.subarray(c,c+b):Array.prototype.slice.call(a,c,c+b);c=!0;b=yb(b);if(!b)throw new N(48);
g().set(a,b)}else c=!1,b=a.byteOffset;return{kb:b,zc:c}},ec:function(a,b,c,d){O.jb.write(a,b,0,d,c,!1);return 0}}};function Eb(a,b,c){var d="al "+a;xa(a,e=>{e||Ba('Loading data file "'+a+'" failed (no arrayBuffer).');b(new Uint8Array(e));d&&cb(d)},()=>{if(c)c();else throw'Loading data file "'+a+'" failed.';});d&&bb(d)}
var Fb=null,Gb={},Hb=[],Ib=1,Jb=null,Va=!0,N=null,Cb={},Lb=(a,b={})=>{a=qb(a);if(!a)return{path:"",node:null};b=Object.assign({Gc:!0,tc:0},b);if(8<b.tc)throw new N(32);a=a.split("/").filter(h=>!!h);for(var c=Fb,d="/",e=0;e<a.length;e++){var f=e===a.length-1;if(f&&b.parent)break;c=Db(c,a[e]);d=mb(d+"/"+a[e]);c.Rb&&(!f||f&&b.Gc)&&(c=c.Rb.root);if(!f||b.Zb)for(f=0;40960===(c.mode&61440);)if(c=Kb(d),d=qb(nb(d),c),c=Lb(d,{tc:b.tc+1}).node,40<f++)throw new N(32);}return{path:d,node:c}},Mb=a=>{for(var b;;){if(a===
a.parent)return a=a.Ab.Kc,b?"/"!==a[a.length-1]?a+"/"+b:a+b:a;b=b?a.name+"/"+b:a.name;a=a.parent}},Nb=(a,b)=>{for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%Jb.length},Db=(a,b)=>{var c;if(c=(c=Ob(a,"x"))?c:a.ib.Pb?0:2)throw new N(c,a);for(c=Jb[Nb(a.id,b)];c;c=c.Nb){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.ib.Pb(a,b)},Bb=(a,b,c,d)=>{a=new Pb(a,b,c,d);b=Nb(a.parent.id,a.name);a.Nb=Jb[b];return Jb[b]=a},Qb={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090},Rb=
a=>{var b=["r","w","rw"][a&3];a&512&&(b+="w");return b},Ob=(a,b)=>{if(Va)return 0;if(!b.includes("r")||a.mode&292){if(b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73))return 2}else return 2;return 0},Sb=(a,b)=>{try{return Db(a,b),20}catch(c){}return Ob(a,"wx")},Tb=(a=0)=>{for(;4096>=a;a++)if(!Hb[a])return a;throw new N(33);},Vb=(a,b)=>{Ub||(Ub=function(){this.fc={}},Ub.prototype={},Object.defineProperties(Ub.prototype,{object:{get:function(){return this.node},set:function(c){this.node=
c}},flags:{get:function(){return this.fc.flags},set:function(c){this.fc.flags=c}},position:{get:function(){return this.fc.position},set:function(c){this.fc.position=c}}}));a=Object.assign(new Ub,a);b=Tb(b);a.Eb=b;return Hb[b]=a},Ab={open:a=>{a.jb=Gb[a.node.Tb].jb;a.jb.open&&a.jb.open(a)},Hb:()=>{throw new N(70);}},ub=(a,b)=>{Gb[a]={jb:b}},Wb=(a,b)=>{var c="/"===b,d=!b;if(c&&Fb)throw new N(10);if(!c&&!d){var e=Lb(b,{Gc:!1});b=e.path;e=e.node;if(e.Rb)throw new N(10);if(16384!==(e.mode&61440))throw new N(54);
}b={type:a,fe:{},Kc:b,yd:[]};a=a.Ab(b);a.Ab=b;b.root=a;c?Fb=a:e&&(e.Rb=b,e.Ab&&e.Ab.yd.push(b))},P=(a,b,c)=>{var d=Lb(a,{parent:!0}).node;a=ob(a);if(!a||"."===a||".."===a)throw new N(28);var e=Sb(d,a);if(e)throw new N(e);if(!d.ib.dc)throw new N(63);return d.ib.dc(d,a,b,c)},Xb=(a,b,c)=>{"undefined"==typeof c&&(c=b,b=438);return P(a,b|8192,c)},Ta=(a,b)=>{if(!qb(a))throw new N(44);var c=Lb(b,{parent:!0}).node;if(!c)throw new N(44);b=ob(b);var d=Sb(c,b);if(d)throw new N(d);if(!c.ib.hc)throw new N(63);
c.ib.hc(c,b,a)},Yb=a=>{var b=Lb(a,{parent:!0}).node;if(!b)throw new N(44);var c=ob(a);a=Db(b,c);a:{try{var d=Db(b,c)}catch(f){d=f.pb;break a}var e=Ob(b,"wx");d=e?e:16384===(d.mode&61440)?31:0}if(d)throw new N(d);if(!b.ib.kc)throw new N(63);if(a.Rb)throw new N(10);b.ib.kc(b,c);b=Nb(a.parent.id,a.name);if(Jb[b]===a)Jb[b]=a.Nb;else for(b=Jb[b];b;){if(b.Nb===a){b.Nb=a.Nb;break}b=b.Nb}},Kb=a=>{a=Lb(a).node;if(!a)throw new N(44);if(!a.ib.Ub)throw new N(28);return qb(Mb(a.parent),a.ib.Ub(a))},Zb=(a,b)=>
{a=Lb(a,{Zb:!b}).node;if(!a)throw new N(44);if(!a.ib.xb)throw new N(63);return a.ib.xb(a)},$b=a=>Zb(a,!0),ac=(a,b)=>{a="string"==typeof a?Lb(a,{Zb:!0}).node:a;if(!a.ib.tb)throw new N(63);a.ib.tb(a,{mode:b&4095|a.mode&-4096,timestamp:Date.now()})},Ua=(a,b,c)=>{if(""===a)throw new N(44);if("string"==typeof b){var d=Qb[b];if("undefined"==typeof d)throw Error("Unknown file open mode: "+b);b=d}c=b&64?("undefined"==typeof c?438:c)&4095|32768:0;if("object"==typeof a)var e=a;else{a=mb(a);try{e=Lb(a,{Zb:!(b&
131072)}).node}catch(f){}}d=!1;if(b&64)if(e){if(b&128)throw new N(20);}else e=P(a,c,0),d=!0;if(!e)throw new N(44);8192===(e.mode&61440)&&(b&=-513);if(b&65536&&16384!==(e.mode&61440))throw new N(54);if(!d&&(c=e?40960===(e.mode&61440)?32:16384===(e.mode&61440)&&("r"!==Rb(b)||b&512)?31:Ob(e,Rb(b)):44))throw new N(c);if(b&512&&!d){c=e;c="string"==typeof c?Lb(c,{Zb:!0}).node:c;if(!c.ib.tb)throw new N(63);if(16384===(c.mode&61440))throw new N(31);if(32768!==(c.mode&61440))throw new N(28);if(d=Ob(c,"w"))throw new N(d);
c.ib.tb(c,{size:0,timestamp:Date.now()})}b&=-131713;e=Vb({node:e,path:Mb(e),flags:b,seekable:!0,position:0,jb:e.jb,Zd:[],error:!1});e.jb.open&&e.jb.open(e);!D.logReadFiles||b&1||(bc||(bc={}),a in bc||(bc[a]=1));return e},cc=a=>{if(null===a.Eb)throw new N(8);a.mc&&(a.mc=null);try{a.jb.close&&a.jb.close(a)}catch(b){throw b;}finally{Hb[a.Eb]=null}a.Eb=null},dc=(a,b,c)=>{if(null===a.Eb)throw new N(8);if(!a.seekable||!a.jb.Hb)throw new N(70);if(0!=c&&1!=c&&2!=c)throw new N(28);a.position=a.jb.Hb(a,b,c);
a.Zd=[]},ec=(a,b,c,d,e,f)=>{if(0>d||0>e)throw new N(28);if(null===a.Eb)throw new N(8);if(0===(a.flags&2097155))throw new N(8);if(16384===(a.node.mode&61440))throw new N(31);if(!a.jb.write)throw new N(28);a.seekable&&a.flags&1024&&dc(a,0,2);var h="undefined"!=typeof e;if(!h)e=a.position;else if(!a.seekable)throw new N(70);b=a.jb.write(a,b,c,d,e,f);h||(a.position+=b);return b},Ra=()=>{N||(N=function(a,b){this.node=b;this.Hd=function(c){this.pb=c};this.Hd(a);this.message="FS error"},N.prototype=Error(),
N.prototype.constructor=N,[44].forEach(a=>{Cb[a]=new N(a);Cb[a].stack="<generic error, no stack>"}))},Qa,fc=(a,b)=>{var c=0;a&&(c|=365);b&&(c|=146);return c},gc=(a,b)=>{a="string"==typeof a?a:Mb(a);for(b=b.split("/").reverse();b.length;){var c=b.pop();if(c){var d=mb(a+"/"+c);try{P(d,16895,0)}catch(e){}a=d}}return d},ic=(a,b,c,d)=>{a=mb(("string"==typeof a?a:Mb(a))+"/"+b);c=fc(c,d);return P(a,(void 0!==c?c:438)&4095|32768,0)},jc=(a,b,c,d,e,f)=>{var h=b;a&&(a="string"==typeof a?a:Mb(a),h=b?mb(a+"/"+
b):a);a=fc(d,e);h=P(h,(void 0!==a?a:438)&4095|32768,0);if(c){if("string"==typeof c){b=Array(c.length);d=0;for(e=c.length;d<e;++d)b[d]=c.charCodeAt(d);c=b}ac(h,a|146);b=Ua(h,577);ec(b,c,0,c.length,0,f);cc(b);ac(h,a)}return h},Sa=(a,b,c,d)=>{a=mb(("string"==typeof a?a:Mb(a))+"/"+b);b=fc(!!c,!!d);Sa.Jc||(Sa.Jc=64);var e=Sa.Jc++<<8|0;ub(e,{open:f=>{f.seekable=!1},close:()=>{d&&d.buffer&&d.buffer.length&&d(10)},read:(f,h,l,m)=>{for(var n=0,r=0;r<m;r++){try{var p=c()}catch(t){throw new N(29);}if(void 0===
p&&0===n)throw new N(6);if(null===p||void 0===p)break;n++;h[l+r]=p}n&&(f.node.timestamp=Date.now());return n},write:(f,h,l,m)=>{for(var n=0;n<m;n++)try{d(h[l+n])}catch(r){throw new N(29);}m&&(f.node.timestamp=Date.now());return n}});return Xb(a,b,e)},kc=a=>{if(!(a.ud||a.vd||a.link||a.hb)){if("undefined"!=typeof XMLHttpRequest)throw Error("Lazy loading should have been performed (contents set) in createLazyFile, but it was not. Lazy loading only works in web workers. Use --embed-file or --preload-file in emcc on the main thread.");
if(wa)try{a.hb=rb(wa(a.url),!0),a.mb=a.hb.length}catch(b){throw new N(29);}else throw Error("Cannot load without read() or XMLHttpRequest.");}},lc=(a,b,c,d,e)=>{function f(){this.qc=!1;this.Yb=[]}function h(p,t,k,u,x){p=p.node.hb;if(x>=p.length)return 0;u=Math.min(p.length-x,u);if(p.slice)for(var z=0;z<u;z++)t[k+z]=p[x+z];else for(z=0;z<u;z++)t[k+z]=p.get(x+z);return u}f.prototype.get=function(p){if(!(p>this.length-1||0>p)){var t=p%this.Cc;return this.ac(p/this.Cc|0)[t]}};f.prototype.Gd=function(p){this.ac=
p};f.prototype.Ac=function(){var p=new XMLHttpRequest;p.open("HEAD",c,!1);p.send(null);if(!(200<=p.status&&300>p.status||304===p.status))throw Error("Couldn't load "+c+". Status: "+p.status);var t=Number(p.getResponseHeader("Content-length")),k,u=(k=p.getResponseHeader("Accept-Ranges"))&&"bytes"===k;p=(k=p.getResponseHeader("Content-Encoding"))&&"gzip"===k;var x=1048576;u||(x=t);var z=this;z.Gd(H=>{var I=H*x,y=(H+1)*x-1;y=Math.min(y,t-1);if("undefined"==typeof z.Yb[H]){var T=z.Yb;if(I>y)throw Error("invalid range ("+
I+", "+y+") or no bytes requested!");if(y>t-1)throw Error("only "+t+" bytes available! programmer error!");var C=new XMLHttpRequest;C.open("GET",c,!1);t!==x&&C.setRequestHeader("Range","bytes="+I+"-"+y);C.responseType="arraybuffer";C.overrideMimeType&&C.overrideMimeType("text/plain; charset=x-user-defined");C.send(null);if(!(200<=C.status&&300>C.status||304===C.status))throw Error("Couldn't load "+c+". Status: "+C.status);I=void 0!==C.response?new Uint8Array(C.response||[]):rb(C.responseText||"",
!0);T[H]=I}if("undefined"==typeof z.Yb[H])throw Error("doXHR failed!");return z.Yb[H]});if(p||!t)x=t=1,x=t=this.ac(0).length,za("LazyFiles on gzip forces download of the whole file when length is accessed");this.Wc=t;this.Vc=x;this.qc=!0};if("undefined"!=typeof XMLHttpRequest){if(!sa)throw"Cannot do synchronous binary XHRs outside webworkers in modern browsers. Use --embed-file or --preload-file in emcc";var l=new f;Object.defineProperties(l,{length:{get:function(){this.qc||this.Ac();return this.Wc}},
Cc:{get:function(){this.qc||this.Ac();return this.Vc}}});var m=void 0}else m=c,l=void 0;var n=ic(a,b,d,e);l?n.hb=l:m&&(n.hb=null,n.url=m);Object.defineProperties(n,{mb:{get:function(){return this.hb.length}}});var r={};Object.keys(n.jb).forEach(p=>{var t=n.jb[p];r[p]=function(){kc(n);return t.apply(null,arguments)}});r.read=(p,t,k,u,x)=>{kc(n);return h(p,t,k,u,x)};r.Qb=(p,t,k)=>{kc(n);var u=yb(t);if(!u)throw new N(48);h(p,g(),u,t,k);return{kb:u,zc:!0}};n.jb=r;return n},nc=(a,b,c,d,e,f,h,l,m,n)=>{function r(k){function u(x){n&&
n();l||jc(a,b,x,d,e,m);f&&f();cb(t)}mc.de(k,p,u,()=>{h&&h();cb(t)})||u(k)}var p=b?qb(mb(a+"/"+b)):a,t="cp "+p;bb(t);"string"==typeof c?Eb(c,k=>r(k),h):r(c)},Q={},Ub,bc;function oc(a,b,c){if("/"===b.charAt(0))return b;a=-100===a?"/":pc(a).path;if(0==b.length){if(!c)throw new N(44);return a}return mb(a+"/"+b)}
function qc(a,b,c){try{var d=a(b)}catch(f){if(f&&f.node&&mb(b)!==mb(Mb(f.node)))return-54;throw f;}A()[c>>2]=d.gd;A()[c+8>>2]=d.oc;A()[c+12>>2]=d.mode;B()[c+16>>2]=d.Ad;A()[c+20>>2]=d.uid;A()[c+24>>2]=d.pd;A()[c+28>>2]=d.Tb;L=[d.size>>>0,(K=d.size,1<=+Math.abs(K)?0<K?(Math.min(+Math.floor(K/4294967296),4294967295)|0)>>>0:~~+Math.ceil((K-+(~~K>>>0))/4294967296)>>>0:0)];A()[c+40>>2]=L[0];A()[c+44>>2]=L[1];A()[c+48>>2]=4096;A()[c+52>>2]=d.ad;a=d.Zc.getTime();b=d.zd.getTime();var e=d.dd.getTime();L=[Math.floor(a/
1E3)>>>0,(K=Math.floor(a/1E3),1<=+Math.abs(K)?0<K?(Math.min(+Math.floor(K/4294967296),4294967295)|0)>>>0:~~+Math.ceil((K-+(~~K>>>0))/4294967296)>>>0:0)];A()[c+56>>2]=L[0];A()[c+60>>2]=L[1];B()[c+64>>2]=a%1E3*1E3;L=[Math.floor(b/1E3)>>>0,(K=Math.floor(b/1E3),1<=+Math.abs(K)?0<K?(Math.min(+Math.floor(K/4294967296),4294967295)|0)>>>0:~~+Math.ceil((K-+(~~K>>>0))/4294967296)>>>0:0)];A()[c+72>>2]=L[0];A()[c+76>>2]=L[1];B()[c+80>>2]=b%1E3*1E3;L=[Math.floor(e/1E3)>>>0,(K=Math.floor(e/1E3),1<=+Math.abs(K)?
0<K?(Math.min(+Math.floor(K/4294967296),4294967295)|0)>>>0:~~+Math.ceil((K-+(~~K>>>0))/4294967296)>>>0:0)];A()[c+88>>2]=L[0];A()[c+92>>2]=L[1];B()[c+96>>2]=e%1E3*1E3;L=[d.oc>>>0,(K=d.oc,1<=+Math.abs(K)?0<K?(Math.min(+Math.floor(K/4294967296),4294967295)|0)>>>0:~~+Math.ceil((K-+(~~K>>>0))/4294967296)>>>0:0)];A()[c+104>>2]=L[0];A()[c+108>>2]=L[1];return 0}var rc=void 0;function sc(){rc+=4;return A()[rc-4>>2]}function pc(a){a=Hb[a];if(!a)throw new N(8);return a}
function tc(a){if(F)return R(1,1,a);if(!noExitRuntime){M.Td();if(D.onExit)D.onExit(a);Da=!0}qa(a,new ib(a))}function uc(a,b){if(!b&&F)throw vc(a),"unwind";tc(a)}function wc(a){a instanceof ib||"unwind"==a||qa(1,a)}
var M={Fb:[],Vb:[],Uc:[],Cb:{},nc:function(){F?M.sd():M.rd()},rd:function(){for(var a=navigator.hardwareConcurrency;a--;)M.yc()},sd:function(){M.receiveObjectTransfer=M.Ed;M.threadInitTLS=M.Tc;M.setExitStatus=M.Sc;noExitRuntime=!1},Sc:function(){},Td:function(){for(var a of Object.values(M.Cb))M.Qc(a);for(a of M.Fb)a.terminate();M.Fb=[]},Qc:function(a){var b=a.Bb;delete M.Cb[b];M.Fb.push(a);M.Vb.splice(M.Vb.indexOf(a),1);a.Bb=0;xc(b)},Ed:function(){},Tc:function(){M.Uc.forEach(a=>a())},Ic:a=>new Promise(b=>
{a.onmessage=f=>{f=f.data;var h=f.cmd;a.Bb&&(M.ed=a.Bb);if(f.targetThread&&f.targetThread!=yc()){var l=M.Cb[f.ge];l?l.postMessage(f,f.transferList):E('Internal error! Worker sent a message "'+h+'" to target pthread '+f.targetThread+", but that thread no longer exists!")}else if("processProxyingQueue"===h)zc(f.queue);else if("spawnThread"===h)kb(f);else if("cleanupThread"===h)jb(f.thread);else if("killThread"===h)f=f.thread,h=M.Cb[f],delete M.Cb[f],h.terminate(),xc(f),M.Vb.splice(M.Vb.indexOf(h),1),
h.Bb=0;else if("cancelThread"===h)M.Cb[f.thread].postMessage({cmd:"cancel"});else if("loaded"===h)a.loaded=!0,b(a);else if("print"===h)za("Thread "+f.threadId+": "+f.text);else if("printErr"===h)E("Thread "+f.threadId+": "+f.text);else if("alert"===h)alert("Thread "+f.threadId+": "+f.text);else if("setimmediate"===f.target)a.postMessage(f);else if("callHandler"===h)D[f.handler](...f.args);else h&&E("worker sent an unknown command "+h);M.ed=void 0};a.onerror=f=>{E("worker sent an error! "+f.filename+
":"+f.lineno+": "+f.message);throw f;};var c=[],d=["onExit","onAbort","print","printErr"],e;for(e of d)D.hasOwnProperty(e)&&c.push(e);a.postMessage({cmd:"load",handlers:c,urlOrBlob:D.mainScriptUrlOrBlob||_scriptDir,wasmMemory:q,wasmModule:Ca})}),xd:function(a){if(F)return a();Promise.all(M.Fb.map(M.Ic)).then(a)},yc:function(){var a=va("BlinkIDWasmSDK.worker.js");a=new Worker(a);M.Fb.push(a)},ld:function(){0==M.Fb.length&&(M.yc(),M.Ic(M.Fb[0]));return M.Fb.pop()}};D.PThread=M;
function Wa(a){for(;0<a.length;)a.shift()(D)}D.establishStackSpace=function(){var a=yc(),b=A()[a+52>>2];a=A()[a+56>>2];Ac(b,b-a);Bc(b)};function vc(a){if(F)return R(2,0,a);try{uc(a)}catch(b){wc(b)}}var Cc=[];function S(a){var b=Cc[a];b||(a>=Cc.length&&(Cc.length=a+1),Cc[a]=b=La.get(a));return b}D.invokeEntryPoint=function(a,b){a=S(a)(b);noExitRuntime?M.Sc(a):Dc(a)};
function Ec(a){this.kb=a-24;this.Nd=function(b){B()[this.kb+4>>2]=b};this.Kd=function(b){B()[this.kb+8>>2]=b};this.Ld=function(){A()[this.kb>>2]=0};this.Jd=function(){var b=0;g()[this.kb+12>>0]=b};this.Md=function(){var b=0;g()[this.kb+13>>0]=b};this.nc=function(b,c){this.Id();this.Nd(b);this.Kd(c);this.Ld();this.Jd();this.Md()};this.Id=function(){B()[this.kb+16>>2]=0}}var Fc=0;function Gc(a,b,c,d){return F?R(3,1,a,b,c,d):Hc(a,b,c,d)}
function Hc(a,b,c,d){if("undefined"==typeof SharedArrayBuffer)return E("Current environment does not support SharedArrayBuffer, pthreads are not available!"),6;var e=[];if(F&&0===e.length)return Gc(a,b,c,d);a={Sd:c,Bb:a,Yc:d,Yd:e};return F?(a.ae="spawnThread",postMessage(a,e),0):kb(a)}
function Ic(a,b,c){if(F)return R(4,1,a,b,c);rc=c;try{var d=pc(a);switch(b){case 0:var e=sc();return 0>e?-28:Vb(d,e).Eb;case 1:case 2:return 0;case 3:return d.flags;case 4:return e=sc(),d.flags|=e,0;case 5:return e=sc(),ea()[e+0>>1]=2,0;case 6:case 7:return 0;case 16:case 8:return-28;case 9:return-1;default:return-28}}catch(f){if("undefined"==typeof Q||!(f instanceof N))throw f;return-f.pb}}
function Jc(a,b){if(F)return R(5,1,a,b);try{var c=pc(a);return qc(Zb,c.path,b)}catch(d){if("undefined"==typeof Q||!(d instanceof N))throw d;return-d.pb}}
function Kc(a,b,c){if(F)return R(6,1,a,b,c);rc=c;try{var d=pc(a);switch(b){case 21509:case 21505:return d.ob?0:-59;case 21510:case 21511:case 21512:case 21506:case 21507:case 21508:return d.ob?0:-59;case 21519:if(!d.ob)return-59;var e=sc();return A()[e>>2]=0;case 21520:return d.ob?-28:-59;case 21531:a=e=sc();if(!d.jb.td)throw new N(59);return d.jb.td(d,b,a);case 21523:return d.ob?0:-59;case 21524:return d.ob?0:-59;default:return-28}}catch(f){if("undefined"==typeof Q||!(f instanceof N))throw f;return-f.pb}}
function Lc(a,b,c,d){if(F)return R(8,1,a,b,c,d);try{b=G(b);var e=d&256;b=oc(a,b,d&4096);return qc(e?$b:Zb,b,c)}catch(f){if("undefined"==typeof Q||!(f instanceof N))throw f;return-f.pb}}function Mc(a,b,c,d){if(F)return R(9,1,a,b,c,d);rc=d;try{b=G(b);b=oc(a,b);var e=d?sc():0;return Ua(b,c,e).Eb}catch(f){if("undefined"==typeof Q||!(f instanceof N))throw f;return-f.pb}}
function Nc(a,b){if(F)return R(10,1,a,b);try{return a=G(a),qc(Zb,a,b)}catch(c){if("undefined"==typeof Q||!(c instanceof N))throw c;return-c.pb}}var Oc={};function Pc(a){for(;a.length;){var b=a.pop();a.pop()(b)}}function Qc(a){return this.fromWireType(A()[a>>2])}var Rc={},Sc={},Tc={};function Uc(a){if(void 0===a)return"_unknown";a=a.replace(/[^a-zA-Z0-9_]/g,"$");var b=a.charCodeAt(0);return 48<=b&&57>=b?"_"+a:a}function Vc(a,b){a=Uc(a);return function(){return b.apply(this,arguments)}}
function Wc(a){var b=Error,c=Vc(a,function(d){this.name=a;this.message=d;d=Error(d).stack;void 0!==d&&(this.stack=this.toString()+"\n"+d.replace(/^Error(:[^\n]*)?\n/,""))});c.prototype=Object.create(b.prototype);c.prototype.constructor=c;c.prototype.toString=function(){return void 0===this.message?this.name:this.name+": "+this.message};return c}var Xc=void 0;function Yc(a){throw new Xc(a);}
function Zc(a,b,c){function d(l){l=c(l);l.length!==a.length&&Yc("Mismatched type converter count");for(var m=0;m<a.length;++m)$c(a[m],l[m])}a.forEach(function(l){Tc[l]=b});var e=Array(b.length),f=[],h=0;b.forEach((l,m)=>{Sc.hasOwnProperty(l)?e[m]=Sc[l]:(f.push(l),Rc.hasOwnProperty(l)||(Rc[l]=[]),Rc[l].push(()=>{e[m]=Sc[l];++h;h===f.length&&d(e)}))});0===f.length&&d(e)}
function ad(a){switch(a){case 1:return 0;case 2:return 1;case 4:return 2;case 8:return 3;default:throw new TypeError("Unknown type size: "+a);}}var bd=void 0;function U(a){for(var b="";v()[a];)b+=bd[v()[a++]];return b}var cd=void 0;function V(a){throw new cd(a);}
function $c(a,b,c={}){if(!("argPackAdvance"in b))throw new TypeError("registerType registeredInstance requires argPackAdvance");var d=b.name;a||V('type "'+d+'" must have a positive integer typeid pointer');if(Sc.hasOwnProperty(a)){if(c.qd)return;V("Cannot register type '"+d+"' twice")}Sc[a]=b;delete Tc[a];Rc.hasOwnProperty(a)&&(b=Rc[a],delete Rc[a],b.forEach(e=>e()))}function dd(a){V(a.gb.nb.lb.name+" instance already deleted")}var ed=!1;function fd(){}
function gd(a){--a.count.value;0===a.count.value&&(a.sb?a.ub.Db(a.sb):a.nb.lb.Db(a.kb))}function hd(a,b,c){if(b===c)return a;if(void 0===c.vb)return null;a=hd(a,b,c.vb);return null===a?null:c.hd(a)}var jd={},kd=[];function ld(){for(;kd.length;){var a=kd.pop();a.gb.Lb=!1;a["delete"]()}}var md=void 0,nd={};function od(a,b){for(void 0===b&&V("ptr should not be undefined");a.vb;)b=a.Wb(b),a=a.vb;return nd[b]}
function pd(a,b){b.nb&&b.kb||Yc("makeClassHandle requires ptr and ptrType");!!b.ub!==!!b.sb&&Yc("Both smartPtrType and smartPtr must be specified");b.count={value:1};return qd(Object.create(a,{gb:{value:b}}))}function qd(a){if("undefined"===typeof FinalizationRegistry)return qd=b=>b,a;ed=new FinalizationRegistry(b=>{gd(b.gb)});qd=b=>{var c=b.gb;c.sb&&ed.register(b,{gb:c},b);return b};fd=b=>{ed.unregister(b)};return qd(a)}function rd(){}
function sd(a,b,c){if(void 0===a[b].rb){var d=a[b];a[b]=function(){a[b].rb.hasOwnProperty(arguments.length)||V("Function '"+c+"' called with an invalid number of arguments ("+arguments.length+") - expects one of ("+a[b].rb+")!");return a[b].rb[arguments.length].apply(this,arguments)};a[b].rb=[];a[b].rb[d.Xb]=d}}
function td(a,b,c){D.hasOwnProperty(a)?((void 0===c||void 0!==D[a].rb&&void 0!==D[a].rb[c])&&V("Cannot register public name '"+a+"' twice"),sd(D,a,a),D.hasOwnProperty(c)&&V("Cannot register multiple overloads of a function with the same number of arguments ("+c+")!"),D[a].rb[c]=b):(D[a]=b,void 0!==c&&(D[a].ee=c))}function ud(a,b,c,d,e,f,h,l){this.name=a;this.constructor=b;this.Mb=c;this.Db=d;this.vb=e;this.kd=f;this.Wb=h;this.hd=l;this.Cd=[]}
function vd(a,b,c){for(;b!==c;)b.Wb||V("Expected null or instance of "+c.name+", got an instance of "+b.name),a=b.Wb(a),b=b.vb;return a}function wd(a,b){if(null===b)return this.pc&&V("null is not a valid "+this.name),0;b.gb||V('Cannot pass "'+xd(b)+'" as a '+this.name);b.gb.kb||V("Cannot pass deleted object as a pointer of type "+this.name);return vd(b.gb.kb,b.gb.nb.lb,this.lb)}
function yd(a,b){if(null===b){this.pc&&V("null is not a valid "+this.name);if(this.cc){var c=this.sc();null!==a&&a.push(this.Db,c);return c}return 0}b.gb||V('Cannot pass "'+xd(b)+'" as a '+this.name);b.gb.kb||V("Cannot pass deleted object as a pointer of type "+this.name);!this.bc&&b.gb.nb.bc&&V("Cannot convert argument of type "+(b.gb.ub?b.gb.ub.name:b.gb.nb.name)+" to parameter type "+this.name);c=vd(b.gb.kb,b.gb.nb.lb,this.lb);if(this.cc)switch(void 0===b.gb.sb&&V("Passing raw pointer to smart pointer is illegal"),
this.Rd){case 0:b.gb.ub===this?c=b.gb.sb:V("Cannot convert argument of type "+(b.gb.ub?b.gb.ub.name:b.gb.nb.name)+" to parameter type "+this.name);break;case 1:c=b.gb.sb;break;case 2:if(b.gb.ub===this)c=b.gb.sb;else{var d=b.clone();c=this.Dd(c,W(function(){d["delete"]()}));null!==a&&a.push(this.Db,c)}break;default:V("Unsupporting sharing policy")}return c}
function zd(a,b){if(null===b)return this.pc&&V("null is not a valid "+this.name),0;b.gb||V('Cannot pass "'+xd(b)+'" as a '+this.name);b.gb.kb||V("Cannot pass deleted object as a pointer of type "+this.name);b.gb.nb.bc&&V("Cannot convert argument of type "+b.gb.nb.name+" to parameter type "+this.name);return vd(b.gb.kb,b.gb.nb.lb,this.lb)}
function Ad(a,b,c,d){this.name=a;this.lb=b;this.pc=c;this.bc=d;this.cc=!1;this.Db=this.Dd=this.sc=this.Nc=this.Rd=this.Bd=void 0;void 0!==b.vb?this.toWireType=yd:(this.toWireType=d?wd:zd,this.wb=null)}function Bd(a,b,c){D.hasOwnProperty(a)||Yc("Replacing nonexistant public symbol");void 0!==D[a].rb&&void 0!==c?D[a].rb[c]=b:(D[a]=b,D[a].Xb=c)}
function Cd(a,b){var c=[];return function(){c.length=0;Object.assign(c,arguments);if(a.includes("j")){var d=D["dynCall_"+a];d=c&&c.length?d.apply(null,[b].concat(c)):d.call(null,b)}else d=S(b).apply(null,c);return d}}function Dd(a,b){a=U(a);var c=a.includes("j")?Cd(a,b):S(b);"function"!=typeof c&&V("unknown function pointer with signature "+a+": "+b);return c}var Ed=void 0;function Fd(a){a=Gd(a);var b=U(a);Hd(a);return b}
function Id(a,b){function c(f){e[f]||Sc[f]||(Tc[f]?Tc[f].forEach(c):(d.push(f),e[f]=!0))}var d=[],e={};b.forEach(c);throw new Ed(a+": "+d.map(Fd).join([", "]));}function Jd(a,b){for(var c=[],d=0;d<a;d++)c.push(B()[b+4*d>>2]);return c}
function Kd(a,b,c,d,e){var f=b.length;2>f&&V("argTypes array size mismatch! Must at least get return value and 'this' types!");var h=null!==b[1]&&null!==c,l=!1;for(c=1;c<b.length;++c)if(null!==b[c]&&void 0===b[c].wb){l=!0;break}var m="void"!==b[0].name,n=f-2,r=Array(n),p=[],t=[];return function(){arguments.length!==n&&V("function "+a+" called with "+arguments.length+" arguments, expected "+n+" args!");t.length=0;p.length=h?2:1;p[0]=e;if(h){var k=b[1].toWireType(t,this);p[1]=k}for(var u=0;u<n;++u)r[u]=
b[u+2].toWireType(t,arguments[u]),p.push(r[u]);u=d.apply(null,p);if(l)Pc(t);else for(var x=h?1:2;x<b.length;x++){var z=1===x?k:r[x-2];null!==b[x].wb&&b[x].wb(z)}k=m?b[0].fromWireType(u):void 0;return k}}var Ld=[],X=[{},{value:void 0},{value:null},{value:!0},{value:!1}];function Md(a){4<a&&0===--X[a].uc&&(X[a]=void 0,Ld.push(a))}
var Y=a=>{a||V("Cannot use deleted val. handle = "+a);return X[a].value},W=a=>{switch(a){case void 0:return 1;case null:return 2;case !0:return 3;case !1:return 4;default:var b=Ld.length?Ld.pop():X.length;X[b]={uc:1,value:a};return b}};function xd(a){if(null===a)return"null";var b=typeof a;return"object"===b||"array"===b||"function"===b?a.toString():""+a}
function Nd(a,b){switch(b){case 2:return function(c){var d=this.fromWireType;q.buffer!=aa.buffer&&ba();return d.call(this,Ja[c>>2])};case 3:return function(c){return this.fromWireType(ka()[c>>3])};default:throw new TypeError("Unknown float type: "+a);}}
function Od(a,b,c){switch(b){case 0:return c?function(d){return g()[d]}:function(d){return v()[d]};case 1:return c?function(d){return ea()[d>>1]}:function(d){return w()[d>>1]};case 2:return c?function(d){return A()[d>>2]}:function(d){return B()[d>>2]};default:throw new TypeError("Unknown integer type: "+a);}}var Pd="undefined"!=typeof TextDecoder?new TextDecoder("utf-16le"):void 0;
function Qd(a,b){var c=a>>1;for(var d=c+b/2;!(c>=d)&&w()[c];)++c;c<<=1;if(32<c-a&&Pd)return Pd.decode(v().slice(a,c));c="";for(d=0;!(d>=b/2);++d){var e=ea()[a+2*d>>1];if(0==e)break;c+=String.fromCharCode(e)}return c}function Rd(a,b,c){void 0===c&&(c=2147483647);if(2>c)return 0;c-=2;var d=b;c=c<2*a.length?c/2:a.length;for(var e=0;e<c;++e){var f=a.charCodeAt(e);ea()[b>>1]=f;b+=2}ea()[b>>1]=0;return b-d}function Sd(a){return 2*a.length}
function Td(a,b){for(var c=0,d="";!(c>=b/4);){var e=A()[a+4*c>>2];if(0==e)break;++c;65536<=e?(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023)):d+=String.fromCharCode(e)}return d}function Ud(a,b,c){void 0===c&&(c=2147483647);if(4>c)return 0;var d=b;c=d+c-4;for(var e=0;e<a.length;++e){var f=a.charCodeAt(e);if(55296<=f&&57343>=f){var h=a.charCodeAt(++e);f=65536+((f&1023)<<10)|h&1023}A()[b>>2]=f;b+=4;if(b+4>c)break}A()[b>>2]=0;return b-d}
function Vd(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&++c;b+=4}return b}function zc(a){Atomics.store(A(),a>>2,1);yc()&&Wd(a);Atomics.compareExchange(A(),a>>2,1,0)}D.executeNotifiedProxyingQueue=zc;function Xd(a,b){var c=Sc[a];void 0===c&&V(b+" has unknown type "+Fd(a));return c}function Yd(a,b){for(var c=Array(a),d=0;d<a;++d)c[d]=Xd(B()[b+4*d>>2],"parameter "+d);return c}var Zd={};function $d(a){var b=Zd[a];return void 0===b?U(a):b}var ae=[];
function be(){function a(b){b.$$$embind_global$$$=b;var c="object"==typeof $$$embind_global$$$&&b.$$$embind_global$$$==b;c||delete b.$$$embind_global$$$;return c}if("object"==typeof globalThis)return globalThis;if("object"==typeof $$$embind_global$$$)return $$$embind_global$$$;"object"==typeof global&&a(global)?$$$embind_global$$$=global:"object"==typeof self&&a(self)&&($$$embind_global$$$=self);if("object"==typeof $$$embind_global$$$)return $$$embind_global$$$;throw Error("unable to get global object.");
}function ce(a){var b=ae.length;ae.push(a);return b}var de=[];function ee(a){var b=Array(a+1);return function(c,d,e){b[0]=c;for(var f=0;f<a;++f){var h=Xd(B()[d+4*f>>2],"parameter "+f);b[f+1]=h.readValueFromPointer(e);e+=h.argPackAdvance}c=new (c.bind.apply(c,b));return W(c)}}var fe={};function ge(a){return 0===a%4&&(0!==a%100||0===a%400)}var he=[0,31,60,91,121,152,182,213,244,274,305,335],ie=[0,31,59,90,120,151,181,212,243,273,304,334];
function je(a){return(ge(a.getFullYear())?he:ie)[a.getMonth()]+a.getDate()-1}function ke(a,b,c,d,e,f,h){if(F)return R(11,1,a,b,c,d,e,f,h);try{var l=pc(d);if(0!==(b&2)&&0===(c&2)&&2!==(l.flags&2097155))throw new N(2);if(1===(l.flags&2097155))throw new N(2);if(!l.jb.Qb)throw new N(43);var m=l.jb.Qb(l,a,e,b,c);var n=m.kb;A()[f>>2]=m.zc;B()[h>>2]=n;return 0}catch(r){if("undefined"==typeof Q||!(r instanceof N))throw r;return-r.pb}}
function le(a,b,c,d,e,f){if(F)return R(12,1,a,b,c,d,e,f);try{var h=pc(e);if(c&2){if(32768!==(h.node.mode&61440))throw new N(43);if(!(d&2)){var l=v().slice(a,a+b);h.jb.ec&&h.jb.ec(h,l,f,b,d)}}}catch(m){if("undefined"==typeof Q||!(m instanceof N))throw m;return-m.pb}}function me(a){var b=Ia(a)+1,c=ne(b);c&&Ga(a,g(),c,b);return c}var oe=[],pe;function qe(a){var b=re();a=a();Bc(b);return a}
function R(a,b){var c=arguments.length-2,d=arguments;return qe(()=>{for(var e=se(8*c),f=e>>3,h=0;h<c;h++){var l=d[2+h];ka()[f+h]=l}return te(a,c,e,b)})}var ue=[],ve={};function Z(a,b){B()[a>>2]=b;B()[a+4>>2]=b/4294967296|0}
function we(a,b){try{var c=indexedDB.open("emscripten_filesystem",1)}catch(d){b(d);return}c.onupgradeneeded=d=>{d=d.target.result;d.objectStoreNames.contains("FILES")&&d.deleteObjectStore("FILES");d.createObjectStore("FILES")};c.onsuccess=d=>a(d.target.result);c.onerror=d=>b(d)}var xe;
function ye(a,b,c,d,e){function f(){var C=0,da=0;y.response&&H&&0===B()[a+12>>2]&&(da=y.response.byteLength);0<da&&(C=ne(da),v().set(new Uint8Array(y.response),C));B()[a+12>>2]=C;Z(a+16,da);Z(a+24,0);(C=y.response?y.response.byteLength:0)&&Z(a+32,C);w()[a+40>>1]=y.readyState;w()[a+42>>1]=y.status;y.statusText&&Ha(y.statusText,a+44,64)}var h=B()[a+8>>2];if(h){var l=G(h),m=a+112,n=G(m);n||(n="GET");B();var r=B()[m+52>>2],p=B()[m+56>>2],t=!!B()[m+60>>2];B();var k=B()[m+68>>2],u=B()[m+72>>2];h=B()[m+
76>>2];var x=B()[m+80>>2],z=B()[m+84>>2];m=B()[m+88>>2];var H=!!(r&1),I=!!(r&2);r=!!(r&64);k=k?G(k):void 0;u=u?G(u):void 0;var y=new XMLHttpRequest;y.withCredentials=t;y.open(n,l,!r,k,u);r||(y.timeout=p);y.ie=l;y.responseType="arraybuffer";x&&(l=G(x),y.overrideMimeType(l));if(h)for(;;){n=B()[h>>2];if(!n)break;l=B()[h+4>>2];if(!l)break;h+=8;n=G(n);l=G(l);y.setRequestHeader(n,l)}var T=B()[a+0>>2];ve[T]=y;h=z&&m?v().slice(z,z+m):null;y.onload=C=>{T in ve&&(f(),200<=y.status&&300>y.status?b&&b(a,y,C):
c&&c(a,y,C))};y.onerror=C=>{T in ve&&(f(),c&&c(a,y,C))};y.ontimeout=C=>{T in ve&&c&&c(a,y,C)};y.onprogress=C=>{if(T in ve){var da=H&&I&&y.response?y.response.byteLength:0,J=0;0<da&&H&&I&&(J=ne(da),v().set(new Uint8Array(y.response),J));B()[a+12>>2]=J;Z(a+16,da);Z(a+24,C.loaded-da);Z(a+32,C.total);w()[a+40>>1]=y.readyState;3<=y.readyState&&0===y.status&&0<C.loaded&&(y.status=200);w()[a+42>>1]=y.status;y.statusText&&Ha(y.statusText,a+44,64);d&&d(a,y,C);J&&Hd(J)}};y.onreadystatechange=C=>{T in ve&&(w()[a+
40>>1]=y.readyState,2<=y.readyState&&(w()[a+42>>1]=y.status),e&&e(a,y,C))};try{y.send(h)}catch(C){c&&c(a,y,C)}}else c(a,0,"no url specified!")}
function ze(a,b,c,d){var e=xe;if(e){var f=a+112;(f=B()[f+64>>2])||(f=B()[a+8>>2]);var h=G(f);try{var l=e.transaction(["FILES"],"readwrite").objectStore("FILES").put(b,h);l.onsuccess=()=>{w()[a+40>>1]=4;w()[a+42>>1]=200;Ha("OK",a+44,64);c(a,0,h)};l.onerror=m=>{w()[a+40>>1]=4;w()[a+42>>1]=413;Ha("Payload Too Large",a+44,64);d(a,0,m)}}catch(m){d(a,0,m)}}else d(a,0,"IndexedDB not available!")}
function Ae(a,b,c){var d=xe;if(d){var e=a+112;(e=B()[e+64>>2])||(e=B()[a+8>>2]);e=G(e);try{var f=d.transaction(["FILES"],"readonly").objectStore("FILES").get(e);f.onsuccess=h=>{if(h.target.result){h=h.target.result;var l=h.byteLength||h.length,m=ne(l);v().set(new Uint8Array(h),m);B()[a+12>>2]=m;Z(a+16,l);Z(a+24,0);Z(a+32,l);w()[a+40>>1]=4;w()[a+42>>1]=200;Ha("OK",a+44,64);b(a,0,h)}else w()[a+40>>1]=4,w()[a+42>>1]=404,Ha("Not Found",a+44,64),c(a,0,"no data")};f.onerror=h=>{w()[a+40>>1]=4;w()[a+42>>
1]=404;Ha("Not Found",a+44,64);c(a,0,h)}}catch(h){c(a,0,h)}}else c(a,0,"IndexedDB not available!")}
function Be(a,b,c){var d=xe;if(d){var e=a+112;(e=B()[e+64>>2])||(e=B()[a+8>>2]);e=G(e);try{var f=d.transaction(["FILES"],"readwrite").objectStore("FILES").delete(e);f.onsuccess=h=>{h=h.target.result;B()[a+12>>2]=0;Z(a+16,0);Z(a+24,0);Z(a+32,0);w()[a+40>>1]=4;w()[a+42>>1]=200;Ha("OK",a+44,64);b(a,0,h)};f.onerror=h=>{w()[a+40>>1]=4;w()[a+42>>1]=404;Ha("Not Found",a+44,64);c(a,0,h)}}catch(h){c(a,0,h)}}else c(a,0,"IndexedDB not available!")}var Ce={};
function De(){if(!Ee){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"==typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:pa||"./this.program"},b;for(b in Ce)void 0===Ce[b]?delete a[b]:a[b]=Ce[b];var c=[];for(b in a)c.push(b+"="+a[b]);Ee=c}return Ee}var Ee;
function Fe(a,b){if(F)return R(13,1,a,b);var c=0;De().forEach(function(d,e){var f=b+c;e=B()[a+4*e>>2]=f;for(f=0;f<d.length;++f)g()[e++>>0]=d.charCodeAt(f);g()[e>>0]=0;c+=d.length+1});return 0}function Ge(a,b){if(F)return R(14,1,a,b);var c=De();B()[a>>2]=c.length;var d=0;c.forEach(function(e){d+=e.length+1});B()[b>>2]=d;return 0}function He(a){if(F)return R(15,1,a);try{var b=pc(a);cc(b);return 0}catch(c){if("undefined"==typeof Q||!(c instanceof N))throw c;return c.pb}}
function Ie(a,b,c,d){if(F)return R(16,1,a,b,c,d);try{a:{var e=pc(a);a=b;for(var f,h=b=0;h<c;h++){var l=B()[a>>2],m=B()[a+4>>2];a+=8;var n=e,r=g(),p=l,t=m,k=f;if(0>t||0>k)throw new N(28);if(null===n.Eb)throw new N(8);if(1===(n.flags&2097155))throw new N(8);if(16384===(n.node.mode&61440))throw new N(31);if(!n.jb.read)throw new N(28);var u="undefined"!=typeof k;if(!u)k=n.position;else if(!n.seekable)throw new N(70);var x=n.jb.read(n,r,p,t,k);u||(n.position+=x);var z=x;if(0>z){var H=-1;break a}b+=z;if(z<
m)break;"undefined"!==typeof f&&(f+=z)}H=b}B()[d>>2]=H;return 0}catch(I){if("undefined"==typeof Q||!(I instanceof N))throw I;return I.pb}}
function Je(a,b,c,d,e){if(F)return R(17,1,a,b,c,d,e);try{b=c+2097152>>>0<4194305-!!b?(b>>>0)+4294967296*c:NaN;if(isNaN(b))return 61;var f=pc(a);dc(f,b,d);L=[f.position>>>0,(K=f.position,1<=+Math.abs(K)?0<K?(Math.min(+Math.floor(K/4294967296),4294967295)|0)>>>0:~~+Math.ceil((K-+(~~K>>>0))/4294967296)>>>0:0)];A()[e>>2]=L[0];A()[e+4>>2]=L[1];f.mc&&0===b&&0===d&&(f.mc=null);return 0}catch(h){if("undefined"==typeof Q||!(h instanceof N))throw h;return h.pb}}
function Ke(a,b,c,d){if(F)return R(18,1,a,b,c,d);try{a:{var e=pc(a);a=b;for(var f,h=b=0;h<c;h++){var l=B()[a>>2],m=B()[a+4>>2];a+=8;var n=ec(e,g(),l,m,f);if(0>n){var r=-1;break a}b+=n;"undefined"!==typeof f&&(f+=n)}r=b}B()[d>>2]=r;return 0}catch(p){if("undefined"==typeof Q||!(p instanceof N))throw p;return p.pb}}function Le(a,b){Le.Mc||(Le.Mc=pb());for(var c=0;c<b;c++)g()[a+c>>0]=Le.Mc();return 0}var Me=[31,29,31,30,31,30,31,31,30,31,30,31],Ne=[31,28,31,30,31,30,31,31,30,31,30,31];
function Oe(a,b){g().set(a,b)}
function Pe(a,b,c,d){function e(k,u,x){for(k="number"==typeof k?k.toString():k||"";k.length<u;)k=x[0]+k;return k}function f(k,u){return e(k,u,"0")}function h(k,u){function x(H){return 0>H?-1:0<H?1:0}var z;0===(z=x(k.getFullYear()-u.getFullYear()))&&0===(z=x(k.getMonth()-u.getMonth()))&&(z=x(k.getDate()-u.getDate()));return z}function l(k){switch(k.getDay()){case 0:return new Date(k.getFullYear()-1,11,29);case 1:return k;case 2:return new Date(k.getFullYear(),0,3);case 3:return new Date(k.getFullYear(),0,
2);case 4:return new Date(k.getFullYear(),0,1);case 5:return new Date(k.getFullYear()-1,11,31);case 6:return new Date(k.getFullYear()-1,11,30)}}function m(k){var u=k.Ib;for(k=new Date((new Date(k.Jb+1900,0,1)).getTime());0<u;){var x=k.getMonth(),z=(ge(k.getFullYear())?Me:Ne)[x];if(u>z-k.getDate())u-=z-k.getDate()+1,k.setDate(1),11>x?k.setMonth(x+1):(k.setMonth(0),k.setFullYear(k.getFullYear()+1));else{k.setDate(k.getDate()+u);break}}x=new Date(k.getFullYear()+1,0,4);u=l(new Date(k.getFullYear(),0,
4));x=l(x);return 0>=h(u,k)?0>=h(x,k)?k.getFullYear()+1:k.getFullYear():k.getFullYear()-1}var n=A()[d+40>>2];d={Wd:A()[d>>2],Vd:A()[d+4>>2],ic:A()[d+8>>2],wc:A()[d+12>>2],jc:A()[d+16>>2],Jb:A()[d+20>>2],zb:A()[d+24>>2],Ib:A()[d+28>>2],he:A()[d+32>>2],Ud:A()[d+36>>2],Xd:n?G(n):""};c=G(c);n={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S","%x":"%m/%d/%y","%X":"%H:%M:%S","%Ec":"%c","%EC":"%C","%Ex":"%m/%d/%y","%EX":"%H:%M:%S","%Ey":"%y",
"%EY":"%Y","%Od":"%d","%Oe":"%e","%OH":"%H","%OI":"%I","%Om":"%m","%OM":"%M","%OS":"%S","%Ou":"%u","%OU":"%U","%OV":"%V","%Ow":"%w","%OW":"%W","%Oy":"%y"};for(var r in n)c=c.replace(new RegExp(r,"g"),n[r]);var p="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),t="January February March April May June July August September October November December".split(" ");n={"%a":function(k){return p[k.zb].substring(0,3)},"%A":function(k){return p[k.zb]},"%b":function(k){return t[k.jc].substring(0,
3)},"%B":function(k){return t[k.jc]},"%C":function(k){return f((k.Jb+1900)/100|0,2)},"%d":function(k){return f(k.wc,2)},"%e":function(k){return e(k.wc,2," ")},"%g":function(k){return m(k).toString().substring(2)},"%G":function(k){return m(k)},"%H":function(k){return f(k.ic,2)},"%I":function(k){k=k.ic;0==k?k=12:12<k&&(k-=12);return f(k,2)},"%j":function(k){for(var u=0,x=0;x<=k.jc-1;u+=(ge(k.Jb+1900)?Me:Ne)[x++]);return f(k.wc+u,3)},"%m":function(k){return f(k.jc+1,2)},"%M":function(k){return f(k.Vd,
2)},"%n":function(){return"\n"},"%p":function(k){return 0<=k.ic&&12>k.ic?"AM":"PM"},"%S":function(k){return f(k.Wd,2)},"%t":function(){return"\t"},"%u":function(k){return k.zb||7},"%U":function(k){return f(Math.floor((k.Ib+7-k.zb)/7),2)},"%V":function(k){var u=Math.floor((k.Ib+7-(k.zb+6)%7)/7);2>=(k.zb+371-k.Ib-2)%7&&u++;if(u)53==u&&(x=(k.zb+371-k.Ib)%7,4==x||3==x&&ge(k.Jb)||(u=1));else{u=52;var x=(k.zb+7-k.Ib-1)%7;(4==x||5==x&&ge(k.Jb%400-1))&&u++}return f(u,2)},"%w":function(k){return k.zb},"%W":function(k){return f(Math.floor((k.Ib+
7-(k.zb+6)%7)/7),2)},"%y":function(k){return(k.Jb+1900).toString().substring(2)},"%Y":function(k){return k.Jb+1900},"%z":function(k){k=k.Ud;var u=0<=k;k=Math.abs(k)/60;return(u?"+":"-")+String("0000"+(k/60*100+k%60)).slice(-4)},"%Z":function(k){return k.Xd},"%%":function(){return"%"}};c=c.replace(/%%/g,"\x00\x00");for(r in n)c.includes(r)&&(c=c.replace(new RegExp(r,"g"),n[r](d)));c=c.replace(/\0\0/g,"%");r=rb(c,!1);if(r.length>b)return 0;Oe(r,a);return r.length-1}M.nc();
function Pb(a,b,c,d){a||(a=this);this.parent=a;this.Ab=a.Ab;this.Rb=null;this.id=Ib++;this.name=b;this.mode=c;this.ib={};this.jb={};this.Tb=d}Object.defineProperties(Pb.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}},vd:{get:function(){return 16384===(this.mode&61440)}},ud:{get:function(){return 8192===(this.mode&61440)}}});Ra();
Jb=Array(4096);Wb(O,"/");P("/tmp",16895,0);P("/home",16895,0);P("/home/web_user",16895,0);(()=>{P("/dev",16895,0);ub(259,{read:()=>0,write:(b,c,d,e)=>e});Xb("/dev/null",259);tb(1280,wb);tb(1536,xb);Xb("/dev/tty",1280);Xb("/dev/tty1",1536);var a=pb();Sa("/dev","random",a);Sa("/dev","urandom",a);P("/dev/shm",16895,0);P("/dev/shm/tmp",16895,0)})();
(()=>{P("/proc",16895,0);var a=P("/proc/self",16895,0);P("/proc/self/fd",16895,0);Wb({Ab:()=>{var b=Bb(a,"fd",16895,73);b.ib={Pb:(c,d)=>{var e=Hb[+d];if(!e)throw new N(8);c={parent:null,Ab:{Kc:"fake"},ib:{Ub:()=>e.path}};return c.parent=c}};return b}},"/proc/self/fd")})();var mc;D.FS_createPath=gc;D.FS_createDataFile=jc;D.FS_createPreloadedFile=nc;D.FS_unlink=Yb;D.FS_createLazyFile=lc;D.FS_createDevice=Sa;Xc=D.InternalError=Wc("InternalError");for(var Qe=Array(256),Re=0;256>Re;++Re)Qe[Re]=String.fromCharCode(Re);
bd=Qe;cd=D.BindingError=Wc("BindingError");rd.prototype.isAliasOf=function(a){if(!(this instanceof rd&&a instanceof rd))return!1;var b=this.gb.nb.lb,c=this.gb.kb,d=a.gb.nb.lb;for(a=a.gb.kb;b.vb;)c=b.Wb(c),b=b.vb;for(;d.vb;)a=d.Wb(a),d=d.vb;return b===d&&c===a};
rd.prototype.clone=function(){this.gb.kb||dd(this);if(this.gb.Sb)return this.gb.count.value+=1,this;var a=qd,b=Object,c=b.create,d=Object.getPrototypeOf(this),e=this.gb;a=a(c.call(b,d,{gb:{value:{count:e.count,Lb:e.Lb,Sb:e.Sb,kb:e.kb,nb:e.nb,sb:e.sb,ub:e.ub}}}));a.gb.count.value+=1;a.gb.Lb=!1;return a};rd.prototype["delete"]=function(){this.gb.kb||dd(this);this.gb.Lb&&!this.gb.Sb&&V("Object already scheduled for deletion");fd(this);gd(this.gb);this.gb.Sb||(this.gb.sb=void 0,this.gb.kb=void 0)};
rd.prototype.isDeleted=function(){return!this.gb.kb};rd.prototype.deleteLater=function(){this.gb.kb||dd(this);this.gb.Lb&&!this.gb.Sb&&V("Object already scheduled for deletion");kd.push(this);1===kd.length&&md&&md(ld);this.gb.Lb=!0;return this};D.getInheritedInstanceCount=function(){return Object.keys(nd).length};D.getLiveInheritedInstances=function(){var a=[],b;for(b in nd)nd.hasOwnProperty(b)&&a.push(nd[b]);return a};D.flushPendingDeletes=ld;D.setDelayFunction=function(a){md=a;kd.length&&md&&md(ld)};
Ad.prototype.md=function(a){this.Nc&&(a=this.Nc(a));return a};Ad.prototype.Dc=function(a){this.Db&&this.Db(a)};Ad.prototype.argPackAdvance=8;Ad.prototype.readValueFromPointer=Qc;Ad.prototype.deleteObject=function(a){if(null!==a)a["delete"]()};
Ad.prototype.fromWireType=function(a){function b(){return this.cc?pd(this.lb.Mb,{nb:this.Bd,kb:c,ub:this,sb:a}):pd(this.lb.Mb,{nb:this,kb:a})}var c=this.md(a);if(!c)return this.Dc(a),null;var d=od(this.lb,c);if(void 0!==d){if(0===d.gb.count.value)return d.gb.kb=c,d.gb.sb=a,d.clone();d=d.clone();this.Dc(a);return d}d=this.lb.kd(c);d=jd[d];if(!d)return b.call(this);d=this.bc?d.cd:d.pointerType;var e=hd(c,this.lb,d.lb);return null===e?b.call(this):this.cc?pd(d.lb.Mb,{nb:d,kb:e,ub:this,sb:a}):pd(d.lb.Mb,
{nb:d,kb:e})};Ed=D.UnboundTypeError=Wc("UnboundTypeError");D.count_emval_handles=function(){for(var a=0,b=5;b<X.length;++b)void 0!==X[b]&&++a;return a};D.get_first_emval=function(){for(var a=5;a<X.length;++a)if(void 0!==X[a])return X[a];return null};F||(bb("library_fetch_init"),we(a=>{xe=a;cb("library_fetch_init")},()=>{xe=!1;cb("library_fetch_init")}));
var Se=[null,tc,vc,Gc,Ic,Jc,Kc,function(a,b){if(F)return R(7,1,a,b);try{return a=G(a),qc($b,a,b)}catch(c){if("undefined"==typeof Q||!(c instanceof N))throw c;return-c.pb}},Lc,Mc,Nc,ke,le,Fe,Ge,He,Ie,Je,Ke],Ye={Fa:function(a,b,c){(new Ec(a)).nc(b,c);Fc++;throw a;},ja:function(a){Te(a,!sa,1,!ra);M.Tc()},H:function(a){F?postMessage({cmd:"cleanupThread",thread:a}):jb(a)},ca:Hc,K:Ic,oa:Jc,pa:Kc,ma:Lc,L:Mc,na:Nc,xa:function(){},ya:function(){Ba("To use dlopen, you need enable dynamic linking, see https://github.com/emscripten-core/emscripten/wiki/Linking")},
e:function(a){var b=Oc[a];delete Oc[a];var c=b.sc,d=b.Db,e=b.Fc,f=e.map(h=>h.od).concat(e.map(h=>h.Pd));Zc([a],f,h=>{var l={};e.forEach((m,n)=>{var r=h[n],p=m.ac,t=m.nd,k=h[n+e.length],u=m.Od,x=m.Qd;l[m.jd]={read:z=>r.fromWireType(p(t,z)),write:(z,H)=>{var I=[];u(x,z,k.toWireType(I,H));Pc(I)}}});return[{name:b.name,fromWireType:function(m){var n={},r;for(r in l)n[r]=l[r].read(m);d(m);return n},toWireType:function(m,n){for(var r in l)if(!(r in n))throw new TypeError('Missing field:  "'+r+'"');var p=
c();for(r in l)l[r].write(p,n[r]);null!==m&&m.push(d,p);return p},argPackAdvance:8,readValueFromPointer:Qc,wb:d}]})},V:function(){},Aa:function(a,b,c,d,e){var f=ad(c);b=U(b);$c(a,{name:b,fromWireType:function(h){return!!h},toWireType:function(h,l){return l?d:e},argPackAdvance:8,readValueFromPointer:function(h){if(1===c)var l=g();else if(2===c)l=ea();else if(4===c)l=A();else throw new TypeError("Unknown boolean type size: "+b);return this.fromWireType(l[h>>f])},wb:null})},u:function(a,b,c,d,e,f,h,
l,m,n,r,p,t){r=U(r);f=Dd(e,f);l&&(l=Dd(h,l));n&&(n=Dd(m,n));t=Dd(p,t);var k=Uc(r);td(k,function(){Id("Cannot construct "+r+" due to unbound types",[d])});Zc([a,b,c],d?[d]:[],function(u){u=u[0];if(d){var x=u.lb;var z=x.Mb}else z=rd.prototype;u=Vc(k,function(){if(Object.getPrototypeOf(this)!==H)throw new cd("Use 'new' to construct "+r);if(void 0===I.Gb)throw new cd(r+" has no accessible constructor");var T=I.Gb[arguments.length];if(void 0===T)throw new cd("Tried to invoke ctor of "+r+" with invalid number of parameters ("+
arguments.length+") - expected ("+Object.keys(I.Gb).toString()+") parameters instead!");return T.apply(this,arguments)});var H=Object.create(z,{constructor:{value:u}});u.prototype=H;var I=new ud(r,u,H,t,x,f,l,n);x=new Ad(r,I,!0,!1);z=new Ad(r+"*",I,!1,!1);var y=new Ad(r+" const*",I,!1,!0);jd[a]={pointerType:z,cd:y};Bd(k,u);return[x,z,y]})},w:function(a,b,c,d,e,f){0<b||Ba();var h=Jd(b,c);e=Dd(d,e);Zc([],[a],function(l){l=l[0];var m="constructor "+l.name;void 0===l.lb.Gb&&(l.lb.Gb=[]);if(void 0!==l.lb.Gb[b-
1])throw new cd("Cannot register multiple constructors with identical number of parameters ("+(b-1)+") for class '"+l.name+"'! Overload resolution is currently only performed using the parameter count, not actual type info!");l.lb.Gb[b-1]=()=>{Id("Cannot construct "+l.name+" due to unbound types",h)};Zc([],h,function(n){n.splice(1,0,null);l.lb.Gb[b-1]=Kd(m,n,null,e,f);return[]});return[]})},j:function(a,b,c,d,e,f,h,l){var m=Jd(c,d);b=U(b);f=Dd(e,f);Zc([],[a],function(n){function r(){Id("Cannot call "+
p+" due to unbound types",m)}n=n[0];var p=n.name+"."+b;b.startsWith("@@")&&(b=Symbol[b.substring(2)]);l&&n.lb.Cd.push(b);var t=n.lb.Mb,k=t[b];void 0===k||void 0===k.rb&&k.className!==n.name&&k.Xb===c-2?(r.Xb=c-2,r.className=n.name,t[b]=r):(sd(t,b,p),t[b].rb[c-2]=r);Zc([],m,function(u){u=Kd(p,u,n,f,h);void 0===t[b].rb?(u.Xb=c-2,t[b]=u):t[b].rb[c-2]=u;return[]});return[]})},za:function(a,b){b=U(b);$c(a,{name:b,fromWireType:function(c){var d=Y(c);Md(c);return d},toWireType:function(c,d){return W(d)},
argPackAdvance:8,readValueFromPointer:Qc,wb:null})},N:function(a,b,c){c=ad(c);b=U(b);$c(a,{name:b,fromWireType:function(d){return d},toWireType:function(d,e){return e},argPackAdvance:8,readValueFromPointer:Nd(b,c),wb:null})},D:function(a,b,c,d,e,f){var h=Jd(b,c);a=U(a);e=Dd(d,e);td(a,function(){Id("Cannot call "+a+" due to unbound types",h)},b-1);Zc([],h,function(l){Bd(a,Kd(a,[l[0],null].concat(l.slice(1)),null,e,f),b-1);return[]})},o:function(a,b,c,d,e){b=U(b);-1===e&&(e=4294967295);e=ad(c);var f=
l=>l;if(0===d){var h=32-8*c;f=l=>l<<h>>>h}c=b.includes("unsigned")?function(l,m){return m>>>0}:function(l,m){return m};$c(a,{name:b,fromWireType:f,toWireType:c,argPackAdvance:8,readValueFromPointer:Od(b,e,0!==d),wb:null})},i:function(a,b,c){function d(f){f>>=2;var h=B();return new e(h.buffer,h[f+1],h[f])}var e=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array][b];c=U(c);$c(a,{name:c,fromWireType:d,argPackAdvance:8,readValueFromPointer:d},{qd:!0})},O:function(a,
b){b=U(b);var c="std::string"===b;$c(a,{name:b,fromWireType:function(d){var e=B()[d>>2],f=d+4;if(c)for(var h=f,l=0;l<=e;++l){var m=f+l;if(l==e||0==v()[m]){h=G(h,m-h);if(void 0===n)var n=h;else n+=String.fromCharCode(0),n+=h;h=m+1}}else{n=Array(e);for(l=0;l<e;++l)n[l]=String.fromCharCode(v()[f+l]);n=n.join("")}Hd(d);return n},toWireType:function(d,e){e instanceof ArrayBuffer&&(e=new Uint8Array(e));var f="string"==typeof e;f||e instanceof Uint8Array||e instanceof Uint8ClampedArray||e instanceof Int8Array||
V("Cannot pass non-string to std::string");var h=c&&f?Ia(e):e.length;var l=ne(4+h+1),m=l+4;B()[l>>2]=h;if(c&&f)Ha(e,m,h+1);else if(f)for(f=0;f<h;++f){var n=e.charCodeAt(f);255<n&&(Hd(m),V("String has UTF-16 code units that do not fit in 8 bits"));v()[m+f]=n}else for(f=0;f<h;++f)v()[m+f]=e[f];null!==d&&d.push(Hd,l);return l},argPackAdvance:8,readValueFromPointer:Qc,wb:function(d){Hd(d)}})},B:function(a,b,c){c=U(c);if(2===b){var d=Qd;var e=Rd;var f=Sd;var h=()=>w();var l=1}else 4===b&&(d=Td,e=Ud,f=
Vd,h=()=>B(),l=2);$c(a,{name:c,fromWireType:function(m){for(var n=B()[m>>2],r=h(),p,t=m+4,k=0;k<=n;++k){var u=m+4+k*b;if(k==n||0==r[u>>l])t=d(t,u-t),void 0===p?p=t:(p+=String.fromCharCode(0),p+=t),t=u+b}Hd(m);return p},toWireType:function(m,n){"string"!=typeof n&&V("Cannot pass non-string to C++ string type "+c);var r=f(n),p=ne(4+r+b);B()[p>>2]=r>>l;e(n,p+4,r+b);null!==m&&m.push(Hd,p);return p},argPackAdvance:8,readValueFromPointer:Qc,wb:function(m){Hd(m)}})},f:function(a,b,c,d,e,f){Oc[a]={name:U(b),
sc:Dd(c,d),Db:Dd(e,f),Fc:[]}},d:function(a,b,c,d,e,f,h,l,m,n){Oc[a].Fc.push({jd:U(b),od:c,ac:Dd(d,e),nd:f,Pd:h,Od:Dd(l,m),Qd:n})},Ba:function(a,b){b=U(b);$c(a,{wd:!0,name:b,argPackAdvance:0,fromWireType:function(){},toWireType:function(){}})},da:function(){return 262144},wa:function(a){E(G(a))},Ca:function(a){var b=ve[a];b&&(delete ve[a],0<b.readyState&&4>b.readyState&&b.abort())},sa:function(){return!0},ea:function(a,b,c,d){if(a==b)setTimeout(()=>zc(d));else if(F)postMessage({targetThread:a,cmd:"processProxyingQueue",
queue:d});else{a=M.Cb[a];if(!a)return;a.postMessage({cmd:"processProxyingQueue",queue:d})}return 1},ia:function(){return-1},Z:function(){throw Infinity;},q:function(a,b,c){a=Y(a);b=Xd(b,"emval::as");var d=[],e=W(d);B()[c>>2]=e;return b.toWireType(d,a)},R:function(a,b,c,d){a=Y(a);c=Yd(b,c);for(var e=Array(b),f=0;f<b;++f){var h=c[f];e[f]=h.readValueFromPointer(d);d+=h.argPackAdvance}a=a.apply(void 0,e);return W(a)},t:function(a,b,c,d){a=ae[a];b=Y(b);c=$d(c);a(b,c,null,d)},c:Md,S:function(a,b){a=Y(a);
b=Y(b);return a==b},v:function(a){if(0===a)return W(be());a=$d(a);return W(be()[a])},s:function(a,b){var c=Yd(a,b),d=c[0];b=d.name+"_$"+c.slice(1).map(function(h){return h.name}).join("_")+"$";var e=de[b];if(void 0!==e)return e;var f=Array(a-1);e=ce((h,l,m,n)=>{for(var r=0,p=0;p<a-1;++p)f[p]=c[p+1].readValueFromPointer(n+r),r+=c[p+1].argPackAdvance;h=h[l].apply(h,f);for(p=0;p<a-1;++p)c[p+1].fd&&c[p+1].fd(f[p]);if(!d.wd)return d.toWireType(m,h)});return de[b]=e},E:function(a,b){a=Y(a);b=Y(b);return W(a[b])},
x:function(a){4<a&&(X[a].uc+=1)},Ga:function(a,b){a=Y(a);b=Y(b);return a instanceof b},y:function(a,b,c,d){a=Y(a);var e=fe[b];e||(e=ee(b),fe[b]=e);return e(a,c,d)},m:function(){return W([])},g:function(a){return W($d(a))},n:function(){return W({})},p:function(a){var b=Y(a);Pc(b);Md(a)},h:function(a,b,c){a=Y(a);b=Y(b);c=Y(c);a[b]=c},k:function(a,b){a=Xd(a,"_emval_take_value");a=a.readValueFromPointer(b);return W(a)},T:function(a){a=Y(a);return W(typeof a)},ta:function(a,b){var c=Date;a=B()[a>>2]+4294967296*
A()[a+4>>2];c=new c(1E3*a);A()[b>>2]=c.getSeconds();A()[b+4>>2]=c.getMinutes();A()[b+8>>2]=c.getHours();A()[b+12>>2]=c.getDate();A()[b+16>>2]=c.getMonth();A()[b+20>>2]=c.getFullYear()-1900;A()[b+24>>2]=c.getDay();a=je(c)|0;A()[b+28>>2]=a;A()[b+36>>2]=-(60*c.getTimezoneOffset());a=(new Date(c.getFullYear(),6,1)).getTimezoneOffset();var d=(new Date(c.getFullYear(),0,1)).getTimezoneOffset();c=(a!=d&&c.getTimezoneOffset()==Math.min(d,a))|0;A()[b+32>>2]=c},ua:function(a){var b=new Date(A()[a+20>>2]+1900,
A()[a+16>>2],A()[a+12>>2],A()[a+8>>2],A()[a+4>>2],A()[a>>2],0),c=A()[a+32>>2],d=b.getTimezoneOffset(),e=(new Date(b.getFullYear(),6,1)).getTimezoneOffset(),f=(new Date(b.getFullYear(),0,1)).getTimezoneOffset(),h=Math.min(f,e);0>c?A()[a+32>>2]=Number(e!=f&&h==d):0<c!=(h==d)&&(e=Math.max(f,e),b.setTime(b.getTime()+6E4*((0<c?h:e)-d)));A()[a+24>>2]=b.getDay();c=je(b)|0;A()[a+28>>2]=c;A()[a>>2]=b.getSeconds();A()[a+4>>2]=b.getMinutes();A()[a+8>>2]=b.getHours();A()[a+12>>2]=b.getDate();A()[a+16>>2]=b.getMonth();
A()[a+20>>2]=b.getYear();return b.getTime()/1E3|0},fa:ke,ga:le,va:function(a,b,c){function d(n){return(n=n.toTimeString().match(/\(([A-Za-z ]+)\)$/))?n[1]:"GMT"}var e=(new Date).getFullYear(),f=new Date(e,0,1),h=new Date(e,6,1);e=f.getTimezoneOffset();var l=h.getTimezoneOffset(),m=Math.max(e,l);B()[a>>2]=60*m;A()[b>>2]=Number(e!=l);a=d(f);b=d(h);a=me(a);b=me(b);l<e?(B()[c>>2]=a,B()[c+4>>2]=b):(B()[c>>2]=b,B()[c+4>>2]=a)},b:function(){Ba("")},F:function(){var a=D.allowedThreads;return a?a:navigator.hardwareConcurrency},
r:function(a,b,c){oe.length=0;var d;for(c>>=2;d=v()[b++];)c+=105!=d&c,oe.push(105==d?A()[c]:ka()[c++>>1]),++c;return hb[a].apply(null,oe)},I:function(){sa||(pe||(pe={}),pe["Blocking on the main thread is very dangerous, see https://emscripten.org/docs/porting/pthreads.html#blocking-on-the-main-browser-thread"]||(pe["Blocking on the main thread is very dangerous, see https://emscripten.org/docs/porting/pthreads.html#blocking-on-the-main-browser-thread"]=1,E("Blocking on the main thread is very dangerous, see https://emscripten.org/docs/porting/pthreads.html#blocking-on-the-main-browser-thread")))},
M:function(){return Date.now()},ba:function(){return 838860800},l:()=>performance.timeOrigin+performance.now(),Q:function(){return"undefined"!=typeof SharedArrayBuffer},qa:function(a,b,c){v().copyWithin(a,b,b+c)},ha:function(a,b,c){ue.length=b;c>>=3;for(var d=0;d<b;d++)ue[d]=ka()[c+d];return(0>a?hb[-a-1]:Se[a]).apply(null,ue)},aa:function(a){var b=v().length;a>>>=0;if(a<=b||838860800<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);var e=Math,f=e.min;d=Math.max(a,d);d+=
(65536-d%65536)%65536;a:{var h=q.buffer;try{q.grow(f.call(e,838860800,d)-h.byteLength+65535>>>16);ba();var l=1;break a}catch(m){}l=void 0}if(l)return!0}return!1},Da:function(a,b,c,d,e){function f(J){if(z)J();else if(!Da)try{J()}catch(hc){wc(hc)}}var h=a+112,l=G(h),m=B()[h+36>>2],n=B()[h+40>>2],r=B()[h+44>>2],p=B()[h+48>>2],t=B()[h+52>>2],k=!!(t&4),u=!!(t&32),x=!!(t&16),z=!!(t&64),H=J=>{f(()=>{m?S(m)(J):b&&b(J)})},I=J=>{f(()=>{r?S(r)(J):d&&d(J)})},y=J=>{f(()=>{n?S(n)(J):c&&c(J)})},T=J=>{f(()=>{p?S(p)(J):
e&&e(J)})};t=J=>{ye(J,H,y,I,T)};var C=(J,hc)=>{ze(J,hc.response,Ya=>{f(()=>{m?S(m)(Ya):b&&b(Ya)})},Ya=>{f(()=>{m?S(m)(Ya):b&&b(Ya)})})},da=J=>{ye(J,C,y,I,T)};if("EM_IDB_STORE"===l)l=B()[h+84>>2],ze(a,v().slice(l,l+B()[h+88>>2]),H,y);else if("EM_IDB_DELETE"===l)Be(a,H,y);else if(x){if(u)return 0;ye(a,k?C:H,y,I,T)}else Ae(a,H,u?y:k?da:t);return a},ra:function(){throw"unwind";},ka:Fe,la:Ge,C:uc,A:He,J:Ie,U:Je,z:Ke,Ea:function(){var a=stackTrace(),b=Ia(a)+1,c=ne(b);Ha(a,c,b);return c},_:Le,W:Ue,G:Ve,
X:We,Y:Xe,a:q||D.wasmMemory,P:Pe,$:function(a,b,c,d){return Pe(a,b,c,d)}};
(function(){function a(e,f){D.asm=e.exports;M.Uc.push(D.asm.La);La=D.asm.Ra;Na.unshift(D.asm.Ha);Ca=f;M.xd(()=>cb("wasm-instantiate"))}function b(e){a(e.instance,e.module)}function c(e){return gb().then(function(f){return WebAssembly.instantiate(f,d)}).then(function(f){return f}).then(e,function(f){E("failed to asynchronously prepare wasm: "+f);Ba(f)})}var d={a:Ye};bb("wasm-instantiate");if(D.instantiateWasm)try{return D.instantiateWasm(d,a)}catch(e){E("Module.instantiateWasm callback failed with error: "+
e),na(e)}(function(){return Aa||"function"!=typeof WebAssembly.instantiateStreaming||db()||"function"!=typeof fetch?c(b):fetch(eb,{credentials:"same-origin"}).then(function(e){return WebAssembly.instantiateStreaming(e,d).then(b,function(f){E("wasm streaming compile failed: "+f);E("falling back to ArrayBuffer instantiation");return c(b)})})})().catch(na);return{}})();D.___wasm_call_ctors=function(){return(D.___wasm_call_ctors=D.asm.Ha).apply(null,arguments)};
var ne=D._malloc=function(){return(ne=D._malloc=D.asm.Ia).apply(null,arguments)},Hd=D._free=function(){return(Hd=D._free=D.asm.Ja).apply(null,arguments)},yc=D._pthread_self=function(){return(yc=D._pthread_self=D.asm.Ka).apply(null,arguments)};D.__emscripten_tls_init=function(){return(D.__emscripten_tls_init=D.asm.La).apply(null,arguments)};
var zb=D._emscripten_builtin_memalign=function(){return(zb=D._emscripten_builtin_memalign=D.asm.Ma).apply(null,arguments)},Gd=D.___getTypeName=function(){return(Gd=D.___getTypeName=D.asm.Na).apply(null,arguments)};D.__embind_initialize_bindings=function(){return(D.__embind_initialize_bindings=D.asm.Oa).apply(null,arguments)};var Te=D.__emscripten_thread_init=function(){return(Te=D.__emscripten_thread_init=D.asm.Pa).apply(null,arguments)};
D.__emscripten_thread_crashed=function(){return(D.__emscripten_thread_crashed=D.asm.Qa).apply(null,arguments)};
var te=D._emscripten_run_in_main_runtime_thread_js=function(){return(te=D._emscripten_run_in_main_runtime_thread_js=D.asm.Sa).apply(null,arguments)},Wd=D.__emscripten_proxy_execute_task_queue=function(){return(Wd=D.__emscripten_proxy_execute_task_queue=D.asm.Ta).apply(null,arguments)},xc=D.__emscripten_thread_free_data=function(){return(xc=D.__emscripten_thread_free_data=D.asm.Ua).apply(null,arguments)},Dc=D.__emscripten_thread_exit=function(){return(Dc=D.__emscripten_thread_exit=D.asm.Va).apply(null,
arguments)},Ze=D._setThrew=function(){return(Ze=D._setThrew=D.asm.Wa).apply(null,arguments)},Ac=D._emscripten_stack_set_limits=function(){return(Ac=D._emscripten_stack_set_limits=D.asm.Xa).apply(null,arguments)},re=D.stackSave=function(){return(re=D.stackSave=D.asm.Ya).apply(null,arguments)},Bc=D.stackRestore=function(){return(Bc=D.stackRestore=D.asm.Za).apply(null,arguments)},se=D.stackAlloc=function(){return(se=D.stackAlloc=D.asm._a).apply(null,arguments)};
D.___cxa_is_pointer_type=function(){return(D.___cxa_is_pointer_type=D.asm.$a).apply(null,arguments)};D.dynCall_ji=function(){return(D.dynCall_ji=D.asm.ab).apply(null,arguments)};D.dynCall_jiji=function(){return(D.dynCall_jiji=D.asm.bb).apply(null,arguments)};D.dynCall_viijii=function(){return(D.dynCall_viijii=D.asm.cb).apply(null,arguments)};D.dynCall_iiiiij=function(){return(D.dynCall_iiiiij=D.asm.db).apply(null,arguments)};
D.dynCall_iiiiijj=function(){return(D.dynCall_iiiiijj=D.asm.eb).apply(null,arguments)};D.dynCall_iiiiiijj=function(){return(D.dynCall_iiiiiijj=D.asm.fb).apply(null,arguments)};D.__ZN2MB2NN28LinearDefragmentingAllocator10Allocation4nullE=169488;D.___start_em_js=448840;D.___stop_em_js=449383;function Ve(a,b){var c=re();try{S(a)(b)}catch(d){Bc(c);if(d!==d+0)throw d;Ze(1,0)}}function Xe(a,b,c,d){var e=re();try{S(a)(b,c,d)}catch(f){Bc(e);if(f!==f+0)throw f;Ze(1,0)}}
function We(a,b,c){var d=re();try{S(a)(b,c)}catch(e){Bc(d);if(e!==e+0)throw e;Ze(1,0)}}function Ue(a,b,c,d){var e=re();try{return S(a)(b,c,d)}catch(f){Bc(e);if(f!==f+0)throw f;Ze(1,0)}}D.addRunDependency=bb;D.removeRunDependency=cb;D.FS_createPath=gc;D.FS_createDataFile=jc;D.FS_createPreloadedFile=nc;D.FS_createLazyFile=lc;D.FS_createDevice=Sa;D.FS_unlink=Yb;D.keepRuntimeAlive=function(){return noExitRuntime};D.wasmMemory=q;D.ExitStatus=ib;D.PThread=M;var $e;ab=function af(){$e||bf();$e||(ab=af)};
function bf(){function a(){if(!$e&&($e=!0,D.calledRun=!0,!Da)){Pa();ma(D);if(D.onRuntimeInitialized)D.onRuntimeInitialized();if(!F){if(D.postRun)for("function"==typeof D.postRun&&(D.postRun=[D.postRun]);D.postRun.length;){var b=D.postRun.shift();Oa.unshift(b)}Wa(Oa)}}}if(!(0<Za))if(F)ma(D),Pa(),startWorker(D);else{if(D.preRun)for("function"==typeof D.preRun&&(D.preRun=[D.preRun]);D.preRun.length;)Xa();Wa(Ma);0<Za||(D.setStatus?(D.setStatus("Running..."),setTimeout(function(){setTimeout(function(){D.setStatus("")},
1);a()},1)):a())}}if(D.preInit)for("function"==typeof D.preInit&&(D.preInit=[D.preInit]);0<D.preInit.length;)D.preInit.pop()();bf();


  return BlinkIDWasmSDK.ready
}
);
})();
if (typeof exports === 'object' && typeof module === 'object')
  module.exports = BlinkIDWasmSDK;
else if (typeof define === 'function' && define['amd'])
  define([], function() { return BlinkIDWasmSDK; });
else if (typeof exports === 'object')
  exports["BlinkIDWasmSDK"] = BlinkIDWasmSDK;
