
var BlinkIDWasmSDK = (() => {
  var _scriptDir = typeof document !== 'undefined' && document.currentScript ? document.currentScript.src : undefined;
  
  return (
function(BlinkIDWasmSDK) {
  BlinkIDWasmSDK = BlinkIDWasmSDK || {};


function g(){q.buffer!=r&&aa(q.buffer);return ba}function y(){q.buffer!=r&&aa(q.buffer);return ca}function da(){q.buffer!=r&&aa(q.buffer);return ea}function z(){q.buffer!=r&&aa(q.buffer);return fa}function A(){q.buffer!=r&&aa(q.buffer);return ha}function D(){q.buffer!=r&&aa(q.buffer);return ia}function ja(){q.buffer!=r&&aa(q.buffer);return ka}var E;E||(E=typeof BlinkIDWasmSDK !== 'undefined' ? BlinkIDWasmSDK : {});var la,ma;E.ready=new Promise(function(a,b){la=a;ma=b});E.kc||(E.kc=0);E.kc++;
E.ENVIRONMENT_IS_PTHREAD||function(a){function b(m,p,n){var t=new XMLHttpRequest;t.open("GET",m,!0);t.responseType="arraybuffer";t.onprogress=function(v){var k=p;v.total&&(k=v.total);if(v.loaded){t.Tc?E.Hb[m].loaded=v.loaded:(t.Tc=!0,E.Hb||(E.Hb={}),E.Hb[m]={loaded:v.loaded,total:k});var u=k=v=0,w;for(w in E.Hb){var B=E.Hb[w];v+=B.total;k+=B.loaded;u++}v=Math.ceil(v*E.kc/u);E.setStatus&&E.setStatus("Downloading data... ("+k+"/"+v+")")}else!E.Hb&&E.setStatus&&E.setStatus("Downloading data...")};t.onerror=
function(){throw Error("NetworkError for: "+m);};t.onload=function(){if(200==t.status||304==t.status||206==t.status||0==t.status&&t.response)n(t.response);else throw Error(t.statusText+" : "+t.responseURL);};t.send(null)}function c(m){console.error("package error:",m)}function d(){function m(v,k,u){this.start=v;this.end=k;this.audio=u}function p(v){if(!v)throw"Loading data file failed."+Error().stack;if(!(v instanceof ArrayBuffer))throw"bad input to processPackageData"+Error().stack;v=new Uint8Array(v);
m.prototype.Zc=v;v=a.files;for(var k=0;k<v.length;++k)m.prototype.vc[v[k].filename].onload();E.removeRunDependency("datafile_../../resources-lightweight/advanced-threads/BlinkIDWasmSDK.data")}E.FS_createPath("/","microblink",!0,!0);m.prototype={vc:{},open:function(v,k){this.name=k;this.vc[k]=this;E.addRunDependency("fp "+this.name)},send:function(){},onload:function(){this.finish(this.Zc.subarray(this.start,this.end))},finish:function(v){E.FS_createDataFile(this.name,null,v,!0,!0,!0);E.removeRunDependency("fp "+
this.name);this.vc[this.name]=null}};for(var n=a.files,t=0;t<n.length;++t)(new m(n[t].start,n[t].end,n[t].audio||0)).open("GET",n[t].filename);E.addRunDependency("datafile_../../resources-lightweight/advanced-threads/BlinkIDWasmSDK.data");E.Jc||(E.Jc={});E.Jc["../../resources-lightweight/advanced-threads/BlinkIDWasmSDK.data"]={Ud:!1};l?(p(l),l=null):h=p}"object"===typeof window?window.encodeURIComponent(window.location.pathname.toString().substring(0,window.location.pathname.toString().lastIndexOf("/"))+
"/"):"undefined"===typeof process&&"undefined"!==typeof location&&encodeURIComponent(location.pathname.toString().substring(0,location.pathname.toString().lastIndexOf("/"))+"/");"function"!==typeof E.locateFilePackage||E.locateFile||(E.locateFile=E.locateFilePackage,F("warning: you defined Module.locateFilePackage, that has been renamed to Module.locateFile (using your locateFilePackage for now)"));var e=E.locateFile?E.locateFile("BlinkIDWasmSDK.data",""):"BlinkIDWasmSDK.data",f=a.remote_package_size,
h=null,l=E.getPreloadedPackage?E.getPreloadedPackage(e,f):null;l||b(e,f,function(m){h?(h(m),h=null):l=m},c);E.calledRun?d():(E.preRun||(E.preRun=[]),E.preRun.push(d))}({files:[{filename:"/microblink/Model_ed586fd6ca47c8eebb513c4ffaaacc2c54e92162b145062d7022519fba0911de.strop",start:0,end:713232},{filename:"/microblink/Model_e4f1f62f68ec44b71ecad3fb3f3b48fe3790beb5ab325611e17d63af06e9f644.strop",start:713232,end:769746},{filename:"/microblink/Model_26abb1accd3147801c9070f367d68903d55fee884a3870d78f7053360da50e30.strop",
start:769746,end:2839210},{filename:"/microblink/Model_36d8e94f4cb46097bd6b7385f2aa91fcdee1a5fefeec59e56d1b9e82c94b00a7.strop",start:2839210,end:3209002},{filename:"/microblink/face_detector_model.zzip",start:3209002,end:3305860},{filename:"/microblink/Model_faf688599c7e261a2a7404730f69ed029115bb0d3e7a3657731d88e701720efe.strop",start:3305860,end:3322598},{filename:"/microblink/ccc_lookup_table.zzip",start:3322598,end:3343067},{filename:"/microblink/Model_9728a773c1b4698cf671cb4a5babc846265c5f7ab0fe34b27cb15c6c50d2881b.strop",
start:3343067,end:4040637},{filename:"/microblink/Model_8322bc53f683fdb17f42124244cf6469a82e1c00ec8c43c5d7939ae25ee8c006.strop",start:4040637,end:4560239},{filename:"/microblink/Model_2880751121560047e6dc571bc8ff4683aeb863886f7c0789234594ceb1e23577.strop",start:4560239,end:4564177},{filename:"/microblink/Model_473ac5f5e256623c0a6b282698c1f1b033b9fb5359e6aa142e9fb4a4022afe4e.strop",start:4564177,end:4571059},{filename:"/microblink/Model_b452fd3cd4037080cfcb4c423dba5bc58c8ceafc28427fdf9c5778fb353f088e.strop",
start:4571059,end:4577877}],remote_package_size:4577877,package_uuid:"9a5176ff-4a96-4461-93b3-95cd0f584e78"});var crypto={getRandomValues:function(a){for(var b=0;b<a.length;b++)a[b]=256*Math.random()|0}},na;na=E.allowedThreads&&0<E.allowedThreads?E.allowedThreads-1:navigator.hardwareConcurrency-1;var oa=0,pa;0<na&&(E.threadWorkersReadyPromise=new Promise(function(a){pa=a}));E.preRun||(E.preRun=[]);
E.preRun.push(function(a){function b(){oa++;oa==na&&pa()}var c=a.PThread.pc;a.PThread.pc=function(d){c(d,b)}});var qa=Object.assign({},E),ra="./this.program",sa=(a,b)=>{throw b;},ta="object"==typeof window,ua="function"==typeof importScripts,va="object"==typeof process&&"object"==typeof process.Sd&&"string"==typeof process.Sd.node,G=E.ENVIRONMENT_IS_PTHREAD||!1,wa="";function xa(a){return E.locateFile?E.locateFile(a,wa):wa+a}var ya,za,Aa;
if(ta||ua)ua?wa=self.location.href:"undefined"!=typeof document&&document.currentScript&&(wa=document.currentScript.src),_scriptDir&&(wa=_scriptDir),wa=0!==wa.indexOf("blob:")?wa.substr(0,wa.replace(/[?#].*/,"").lastIndexOf("/")+1):"",ya=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},ua&&(Aa=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),za=(a,b,c)=>{var d=new XMLHttpRequest;d.open("GET",
a,!0);d.responseType="arraybuffer";d.onload=()=>{200==d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)};var Ba=E.print||console.log.bind(console),F=E.printErr||console.warn.bind(console);Object.assign(E,qa);qa=null;E.thisProgram&&(ra=E.thisProgram);E.quit&&(sa=E.quit);var Ca,Da=0,Ea;E.wasmBinary&&(Ea=E.wasmBinary);var noExitRuntime=E.noExitRuntime||!0;"object"!=typeof WebAssembly&&Fa("no native wasm support detected");
var q,Ga,Ha=!1,Ia="undefined"!=typeof TextDecoder?new TextDecoder("utf8"):void 0;
function Ja(a,b,c){var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.buffer&&Ia)return Ia.decode(a.buffer instanceof SharedArrayBuffer?a.slice(b,c):a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var f=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|f);else{var h=a[b++]&63;e=224==(e&240)?(e&15)<<12|f<<6|h:(e&7)<<18|f<<12|h<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d}
function K(a,b){return a?Ja(y(),a,b):""}function Ka(a,b,c,d){if(!(0<d))return 0;var e=c;d=c+d-1;for(var f=0;f<a.length;++f){var h=a.charCodeAt(f);if(55296<=h&&57343>=h){var l=a.charCodeAt(++f);h=65536+((h&1023)<<10)|l&1023}if(127>=h){if(c>=d)break;b[c++]=h}else{if(2047>=h){if(c+1>=d)break;b[c++]=192|h>>6}else{if(65535>=h){if(c+2>=d)break;b[c++]=224|h>>12}else{if(c+3>=d)break;b[c++]=240|h>>18;b[c++]=128|h>>12&63}b[c++]=128|h>>6&63}b[c++]=128|h&63}}b[c]=0;return c-e}
function La(a,b,c){Ka(a,y(),b,c)}function Ma(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:b+4}return b}var Na="undefined"!=typeof TextDecoder?new TextDecoder("utf-16le"):void 0;
function Oa(a,b){var c=a>>1;for(var d=c+b/2;!(c>=d)&&z()[c];)++c;c<<=1;if(32<c-a&&Na)return Na.decode(y().slice(a,c));c="";for(d=0;!(d>=b/2);++d){var e=da()[a+2*d>>1];if(0==e)break;c+=String.fromCharCode(e)}return c}function Pa(a,b,c){void 0===c&&(c=2147483647);if(2>c)return 0;c-=2;var d=b;c=c<2*a.length?c/2:a.length;for(var e=0;e<c;++e){var f=a.charCodeAt(e);da()[b>>1]=f;b+=2}da()[b>>1]=0;return b-d}function Qa(a){return 2*a.length}
function Ra(a,b){for(var c=0,d="";!(c>=b/4);){var e=A()[a+4*c>>2];if(0==e)break;++c;65536<=e?(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023)):d+=String.fromCharCode(e)}return d}function Sa(a,b,c){void 0===c&&(c=2147483647);if(4>c)return 0;var d=b;c=d+c-4;for(var e=0;e<a.length;++e){var f=a.charCodeAt(e);if(55296<=f&&57343>=f){var h=a.charCodeAt(++e);f=65536+((f&1023)<<10)|h&1023}A()[b>>2]=f;b+=4;if(b+4>c)break}A()[b>>2]=0;return b-d}
function Ta(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&++c;b+=4}return b}function Ua(a){var b=Ma(a)+1,c=Wa(b);c&&Ka(a,g(),c,b);return c}function Xa(a,b){g().set(a,b)}var r,ba,ca,ea,fa,ha,ia,Ya,ka;G&&(r=E.buffer);
function aa(a){r=a;E.HEAP8=ba=new Int8Array(a);E.HEAP16=ea=new Int16Array(a);E.HEAP32=ha=new Int32Array(a);E.HEAPU8=ca=new Uint8Array(a);E.HEAPU16=fa=new Uint16Array(a);E.HEAPU32=ia=new Uint32Array(a);E.HEAPF32=Ya=new Float32Array(a);E.HEAPF64=ka=new Float64Array(a)}var Za=E.INITIAL_MEMORY||209715200;
if(G)q=E.wasmMemory,r=E.buffer;else if(E.wasmMemory)q=E.wasmMemory;else if(q=new WebAssembly.Memory({initial:Za/65536,maximum:12800,shared:!0}),!(q.buffer instanceof SharedArrayBuffer))throw F("requested a shared WebAssembly.Memory but the returned buffer is not a SharedArrayBuffer, indicating that while the browser has SharedArrayBuffer it does not have WebAssembly threads support - you may need to set a flag"),va&&console.log("(on node you may need: --experimental-wasm-threads --experimental-wasm-bulk-memory and also use a recent version)"),
Error("bad memory");q&&(r=q.buffer);Za=r.byteLength;aa(r);var $a,ab=[],bb=[],cb=[];function db(){G||(E.noFSInit||eb||(eb=!0,fb(),E.stdin=E.stdin,E.stdout=E.stdout,E.stderr=E.stderr,E.stdin?gb("/dev","stdin",E.stdin):hb("/dev/tty","/dev/stdin"),E.stdout?gb("/dev","stdout",null,E.stdout):hb("/dev/tty","/dev/stdout"),E.stderr?gb("/dev","stderr",null,E.stderr):hb("/dev/tty1","/dev/stderr"),ib("/dev/stdin",0),ib("/dev/stdout",1),ib("/dev/stderr",1)),jb=!1,kb(bb))}
function lb(){var a=E.preRun.shift();ab.unshift(a)}var mb=0,nb=null,ob=null;function pb(){mb++;E.monitorRunDependencies&&E.monitorRunDependencies(mb)}function qb(){mb--;E.monitorRunDependencies&&E.monitorRunDependencies(mb);if(0==mb&&(null!==nb&&(clearInterval(nb),nb=null),ob)){var a=ob;ob=null;a()}}E.preloadedImages={};E.preloadedAudios={};
function Fa(a){if(G)postMessage({cmd:"onAbort",arg:a});else if(E.onAbort)E.onAbort(a);a="Aborted("+a+")";F(a);Ha=!0;a=new WebAssembly.RuntimeError(a+". Build with -s ASSERTIONS=1 for more info.");ma(a);throw a;}function rb(){return sb.startsWith("data:application/octet-stream;base64,")}var sb;sb="BlinkIDWasmSDK.wasm";rb()||(sb=xa(sb));function tb(){var a=sb;try{if(a==sb&&Ea)return new Uint8Array(Ea);if(Aa)return Aa(a);throw"both async and sync fetching of the wasm failed";}catch(b){Fa(b)}}
function ub(){return Ea||!ta&&!ua||"function"!=typeof fetch?Promise.resolve().then(function(){return tb()}):fetch(sb,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+sb+"'";return a.arrayBuffer()}).catch(function(){return tb()})}
var L,vb,wb={385789:function(a){a=K(a);throw Error("Failed to reconfigure RecognizerRunner due to following error: "+a);},385925:function(a,b,c,d){a=K(a);b=K(b);c=K(c);d=K(d);throw Error(a+b+c+d);},386141:function(a,b){a=K(a);b=K(b);throw Error(a+b);},386251:function(a,b){a=K(a);b=K(b);console.log(a+b)},386349:function(a){throw Error(K(a));},386392:function(){throw Error("Unable to perform that operation while recognizer is in use!");},386475:function(){throw Error("Unable to perform that operation while recognizer is in use!");
},386558:function(){throw Error("Unable to perform that operation while recognizer is in use!");}};function kb(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b(E);else{var c=b.Vd;"number"==typeof c?void 0===b.Nb?M(c)():M(c)(b.Nb):c(void 0===b.Nb?null:b.Nb)}}}function xb(a){var b=yb();a=a();zb(b);return a}function Ab(a){var b=N.xb[a];b&&(A()[a>>2]=0,N.Oc(b.worker))}
function Bb(a){var b=N.hd();if(!b)return 6;N.Ub.push(b);var c=N.xb[a.qc]={worker:b,wc:a.qc};b.Mb=c;var d={cmd:"run",start_routine:a.Kd,arg:a.Nb,threadInfoStruct:a.qc};b.Tb=()=>{d.time=performance.now();b.postMessage(d,a.Qd)};b.loaded&&(b.Tb(),delete b.Tb);return 0}function Cb(a){a instanceof Db||"unwind"==a||sa(1,a)}
var N={Cb:[],Ub:[],fc:[],od:function(){G&&N.pd()},Yd:function(){},pd:function(){N.receiveObjectTransfer=N.Ad;N.threadInit=N.Qc;N.setExitStatus=N.Fd;noExitRuntime=!1},xb:{},Fd:function(){},Ld:function(){for(var a in N.xb){var b=N.xb[a];b&&b.worker&&N.Oc(b.worker)}for(a=0;a<N.Cb.length;++a)N.Cb[a].terminate();N.Cb=[]},Oc:function(a){N.Cd(function(){delete N.xb[a.Mb.wc];N.Cb.push(a);N.Ub.splice(N.Ub.indexOf(a),1);Eb(a.Mb.wc);a.Mb=void 0})},Cd:function(a){A()[Fb>>2]=0;try{a()}finally{A()[Fb>>2]=1}},Ad:function(){},
Qc:function(){for(var a in N.fc)if(N.fc.hasOwnProperty(a))N.fc[a]()},pc:function(a,b){a.onmessage=c=>{c=c.data;var d=c.cmd;a.Mb&&(N.cd=a.Mb.wc);if(c.targetThread&&c.targetThread!=Gb()){var e=N.xb[c.ae];e?e.worker.postMessage(c,c.transferList):F('Internal error! Worker sent a message "'+d+'" to target pthread '+c.targetThread+", but that thread no longer exists!")}else if("processProxyingQueue"===d)Hb(c.queue),Atomics.sub(A(),c.queue>>2,1);else if("spawnThread"===d)Bb(c);else if("cleanupThread"===
d)Ab(c.thread);else if("killThread"===d)c=c.thread,A()[c>>2]=0,d=N.xb[c],delete N.xb[c],d.worker.terminate(),Eb(c),N.Ub.splice(N.Ub.indexOf(d.worker),1),d.worker.Mb=void 0;else if("cancelThread"===d)N.xb[c.thread].worker.postMessage({cmd:"cancel"});else if("loaded"===d)a.loaded=!0,b&&b(a),a.Tb&&(a.Tb(),delete a.Tb);else if("print"===d)Ba("Thread "+c.threadId+": "+c.text);else if("printErr"===d)F("Thread "+c.threadId+": "+c.text);else if("alert"===d)alert("Thread "+c.threadId+": "+c.text);else if("setimmediate"===
c.target)a.postMessage(c);else if("onAbort"===d){if(E.onAbort)E.onAbort(c.arg)}else d&&F("worker sent an unknown command "+d);N.cd=void 0};a.onerror=c=>{F("worker sent an error! "+c.filename+":"+c.lineno+": "+c.message);throw c;};a.postMessage({cmd:"load",urlOrBlob:E.mainScriptUrlOrBlob||_scriptDir,wasmMemory:q,wasmModule:Ga})},Uc:function(){var a=xa("BlinkIDWasmSDK.worker.js");N.Cb.push(new Worker(a))},hd:function(){0==N.Cb.length&&(N.Uc(),N.pc(N.Cb[0]));return N.Cb.pop()}};
E.establishStackSpace=function(){var a=Gb(),b=A()[a+44>>2];a=A()[a+48>>2];Ib(b,b-a);zb(b)};function Jb(a){if(G)return O(1,0,a);try{Kb(a)}catch(b){Cb(b)}}var Lb=[];function M(a){var b=Lb[a];b||(a>=Lb.length&&(Lb.length=a+1),Lb[a]=b=$a.get(a));return b}E.invokeEntryPoint=function(a,b){return M(a)(b)};function Mb(a,b,c,d){return G?O(2,1,a,b,c,d):Nb(a,b,c,d)}
function Nb(a,b,c,d){if("undefined"==typeof SharedArrayBuffer)return F("Current environment does not support SharedArrayBuffer, pthreads are not available!"),6;var e=[];if(G&&0===e.length)return Mb(a,b,c,d);a={Kd:c,qc:a,Nb:d,Qd:e};return G?(a.Td="spawnThread",postMessage(a,e),0):Bb(a)}function Ob(a,b){for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a}
function Pb(a){var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=Ob(a.split("/").filter(function(d){return!!d}),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a}function Qb(a){var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,b.length-1));return a+b}function Rb(a){if("/"===a)return"/";a=Pb(a);a=a.replace(/\/$/,"");var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)}
function Sb(){if("object"==typeof crypto&&"function"==typeof crypto.getRandomValues){var a=new Uint8Array(1);return function(){crypto.getRandomValues(a);return a[0]}}return function(){Fa("randomDevice")}}
function Tb(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:"/";if("string"!=typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=Ob(a.split("/").filter(function(d){return!!d}),!b).join("/");return(b?"/":"")+a||"."}var Ub=[];function Vb(a,b){Ub[a]={input:[],ob:[],Lb:b};Wb(a,Xb)}
var Xb={open:function(a){var b=Ub[a.node.Rb];if(!b)throw new P(43);a.mb=b;a.seekable=!1},close:function(a){a.mb.Lb.flush(a.mb)},flush:function(a){a.mb.Lb.flush(a.mb)},read:function(a,b,c,d){if(!a.mb||!a.mb.Lb.Gc)throw new P(60);for(var e=0,f=0;f<d;f++){try{var h=a.mb.Lb.Gc(a.mb)}catch(l){throw new P(29);}if(void 0===h&&0===e)throw new P(6);if(null===h||void 0===h)break;e++;b[c+f]=h}e&&(a.node.timestamp=Date.now());return e},write:function(a,b,c,d){if(!a.mb||!a.mb.Lb.rc)throw new P(60);try{for(var e=
0;e<d;e++)a.mb.Lb.rc(a.mb,b[c+e])}catch(f){throw new P(29);}d&&(a.node.timestamp=Date.now());return e}},Zb={Gc:function(a){if(!a.input.length){var b=null;"undefined"!=typeof window&&"function"==typeof window.prompt?(b=window.prompt("Input: "),null!==b&&(b+="\n")):"function"==typeof readline&&(b=readline(),null!==b&&(b+="\n"));if(!b)return null;a.input=Yb(b,!0)}return a.input.shift()},rc:function(a,b){null===b||10===b?(Ba(Ja(a.ob,0)),a.ob=[]):0!=b&&a.ob.push(b)},flush:function(a){a.ob&&0<a.ob.length&&
(Ba(Ja(a.ob,0)),a.ob=[])}},$b={rc:function(a,b){null===b||10===b?(F(Ja(a.ob,0)),a.ob=[]):0!=b&&a.ob.push(b)},flush:function(a){a.ob&&0<a.ob.length&&(F(Ja(a.ob,0)),a.ob=[])}},Q={wb:null,zb:function(){return Q.createNode(null,"/",16895,0)},createNode:function(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new P(63);Q.wb||(Q.wb={dir:{node:{vb:Q.gb.vb,rb:Q.gb.rb,Ob:Q.gb.Ob,bc:Q.gb.bc,Nc:Q.gb.Nc,jc:Q.gb.jc,Pc:Q.gb.Pc,Mc:Q.gb.Mc,ec:Q.gb.ec},stream:{Eb:Q.hb.Eb}},file:{node:{vb:Q.gb.vb,rb:Q.gb.rb},
stream:{Eb:Q.hb.Eb,read:Q.hb.read,write:Q.hb.write,yc:Q.hb.yc,cc:Q.hb.cc,dc:Q.hb.dc}},link:{node:{vb:Q.gb.vb,rb:Q.gb.rb,Sb:Q.gb.Sb},stream:{}},Ac:{node:{vb:Q.gb.vb,rb:Q.gb.rb},stream:ac}});c=bc(a,b,c,d);16384===(c.mode&61440)?(c.gb=Q.wb.dir.node,c.hb=Q.wb.dir.stream,c.fb={}):32768===(c.mode&61440)?(c.gb=Q.wb.file.node,c.hb=Q.wb.file.stream,c.kb=0,c.fb=null):40960===(c.mode&61440)?(c.gb=Q.wb.link.node,c.hb=Q.wb.link.stream):8192===(c.mode&61440)&&(c.gb=Q.wb.Ac.node,c.hb=Q.wb.Ac.stream);c.timestamp=
Date.now();a&&(a.fb[b]=c,a.timestamp=c.timestamp);return c},Wd:function(a){return a.fb?a.fb.subarray?a.fb.subarray(0,a.kb):new Uint8Array(a.fb):new Uint8Array(0)},Dc:function(a,b){var c=a.fb?a.fb.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)>>>0),0!=c&&(b=Math.max(b,256)),c=a.fb,a.fb=new Uint8Array(b),0<a.kb&&a.fb.set(c.subarray(0,a.kb),0))},Bd:function(a,b){if(a.kb!=b)if(0==b)a.fb=null,a.kb=0;else{var c=a.fb;a.fb=new Uint8Array(b);c&&a.fb.set(c.subarray(0,Math.min(b,a.kb)));a.kb=b}},gb:{vb:function(a){var b=
{};b.dd=8192===(a.mode&61440)?a.id:1;b.mc=a.id;b.mode=a.mode;b.wd=1;b.uid=0;b.md=0;b.Rb=a.Rb;b.size=16384===(a.mode&61440)?4096:32768===(a.mode&61440)?a.kb:40960===(a.mode&61440)?a.link.length:0;b.Wc=new Date(a.timestamp);b.vd=new Date(a.timestamp);b.bd=new Date(a.timestamp);b.Xc=4096;b.Yc=Math.ceil(b.size/b.Xc);return b},rb:function(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);void 0!==b.size&&Q.Bd(a,b.size)},Ob:function(){throw cc[44];},bc:function(a,b,c,
d){return Q.createNode(a,b,c,d)},Nc:function(a,b,c){if(16384===(a.mode&61440)){try{var d=dc(b,c)}catch(f){}if(d)for(var e in d.fb)throw new P(55);}delete a.parent.fb[a.name];a.parent.timestamp=Date.now();a.name=c;b.fb[c]=a;b.timestamp=a.parent.timestamp;a.parent=b},jc:function(a,b){delete a.fb[b];a.timestamp=Date.now()},Pc:function(a,b){var c=dc(a,b),d;for(d in c.fb)throw new P(55);delete a.fb[b];a.timestamp=Date.now()},Mc:function(a){var b=[".",".."],c;for(c in a.fb)a.fb.hasOwnProperty(c)&&b.push(c);
return b},ec:function(a,b,c){a=Q.createNode(a,b,41471,0);a.link=c;return a},Sb:function(a){if(40960!==(a.mode&61440))throw new P(28);return a.link}},hb:{read:function(a,b,c,d,e){var f=a.node.fb;if(e>=a.node.kb)return 0;a=Math.min(a.node.kb-e,d);if(8<a&&f.subarray)b.set(f.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=f[e+d];return a},write:function(a,b,c,d,e,f){b.buffer===g().buffer&&(f=!1);if(!d)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&(!a.fb||a.fb.subarray)){if(f)return a.fb=b.subarray(c,
c+d),a.kb=d;if(0===a.kb&&0===e)return a.fb=b.slice(c,c+d),a.kb=d;if(e+d<=a.kb)return a.fb.set(b.subarray(c,c+d),e),d}Q.Dc(a,e+d);if(a.fb.subarray&&b.subarray)a.fb.set(b.subarray(c,c+d),e);else for(f=0;f<d;f++)a.fb[e+f]=b[c+f];a.kb=Math.max(a.kb,e+d);return d},Eb:function(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.kb);if(0>b)throw new P(28);return b},yc:function(a,b,c){Q.Dc(a.node,b+c);a.node.kb=Math.max(a.node.kb,b+c)},cc:function(a,b,c,d,e,f){if(0!==b)throw new P(28);
if(32768!==(a.node.mode&61440))throw new P(43);a=a.node.fb;if(f&2||a.buffer!==r){if(0<d||d+c<a.length)a=a.subarray?a.subarray(d,d+c):Array.prototype.slice.call(a,d,d+c);d=!0;f=65536*Math.ceil(c/65536);(c=ec(65536,f))?y().fill(0,c,c+f):c=0;if(!c)throw new P(48);g().set(a,c)}else d=!1,c=a.byteOffset;return{jb:c,Vc:d}},dc:function(a,b,c,d,e){if(32768!==(a.node.mode&61440))throw new P(43);if(e&2)return 0;Q.hb.write(a,b,0,d,c,!1);return 0}}};
function fc(a,b,c){var d="al "+a;za(a,function(e){e||Fa('Loading data file "'+a+'" failed (no arrayBuffer).');b(new Uint8Array(e));d&&qb(d)},function(){if(c)c();else throw'Loading data file "'+a+'" failed.';});d&&pb(d)}
var gc=null,hc={},ic=[],jc=1,kc=null,jb=!0,P=null,cc={},mc=(a,b={})=>{a=Tb("/",a);if(!a)return{path:"",node:null};b=Object.assign({Fc:!0,tc:0},b);if(8<b.tc)throw new P(32);a=Ob(a.split("/").filter(h=>!!h),!1);for(var c=gc,d="/",e=0;e<a.length;e++){var f=e===a.length-1;if(f&&b.parent)break;c=dc(c,a[e]);d=Pb(d+"/"+a[e]);c.Pb&&(!f||f&&b.Fc)&&(c=c.Pb.root);if(!f||b.Yb)for(f=0;40960===(c.mode&61440);)if(c=lc(d),d=Tb(Qb(d),c),c=mc(d,{tc:b.tc+1}).node,40<f++)throw new P(32);}return{path:d,node:c}},nc=a=>
{for(var b;;){if(a===a.parent)return a=a.zb.Ic,b?"/"!==a[a.length-1]?a+"/"+b:a+b:a;b=b?a.name+"/"+b:a.name;a=a.parent}},oc=(a,b)=>{for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%kc.length},dc=(a,b)=>{var c;if(c=(c=pc(a,"x"))?c:a.gb.Ob?0:2)throw new P(c,a);for(c=kc[oc(a.id,b)];c;c=c.Kb){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.gb.Ob(a,b)},bc=(a,b,c,d)=>{a=new qc(a,b,c,d);b=oc(a.parent.id,a.name);a.Kb=kc[b];return kc[b]=a},rc={r:0,"r+":2,w:577,"w+":578,
a:1089,"a+":1090},sc=a=>{var b=["r","w","rw"][a&3];a&512&&(b+="w");return b},pc=(a,b)=>{if(jb)return 0;if(!b.includes("r")||a.mode&292){if(b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73))return 2}else return 2;return 0},tc=(a,b)=>{try{return dc(a,b),20}catch(c){}return pc(a,"wx")},uc=(a=0,b=4096)=>{for(;a<=b;a++)if(!ic[a])return a;throw new P(33);},wc=(a,b)=>{vc||(vc=function(){},vc.prototype={object:{get:function(){return this.node},set:function(c){this.node=c}}});a=Object.assign(new vc,
a);b=uc(b,void 0);a.Bb=b;return ic[b]=a},ac={open:a=>{a.hb=hc[a.node.Rb].hb;a.hb.open&&a.hb.open(a)},Eb:()=>{throw new P(70);}},Wb=(a,b)=>{hc[a]={hb:b}},xc=(a,b)=>{var c="/"===b,d=!b;if(c&&gc)throw new P(10);if(!c&&!d){var e=mc(b,{Fc:!1});b=e.path;e=e.node;if(e.Pb)throw new P(10);if(16384!==(e.mode&61440))throw new P(54);}b={type:a,$d:{},Ic:b,ud:[]};a=a.zb(b);a.zb=b;b.root=a;c?gc=a:e&&(e.Pb=b,e.zb&&e.zb.ud.push(b))},R=(a,b,c)=>{var d=mc(a,{parent:!0}).node;a=Rb(a);if(!a||"."===a||".."===a)throw new P(28);
var e=tc(d,a);if(e)throw new P(e);if(!d.gb.bc)throw new P(63);return d.gb.bc(d,a,b,c)},yc=(a,b,c)=>{"undefined"==typeof c&&(c=b,b=438);return R(a,b|8192,c)},hb=(a,b)=>{if(!Tb(a))throw new P(44);var c=mc(b,{parent:!0}).node;if(!c)throw new P(44);b=Rb(b);var d=tc(c,b);if(d)throw new P(d);if(!c.gb.ec)throw new P(63);c.gb.ec(c,b,a)},zc=a=>{var b=mc(a,{parent:!0}).node;if(!b)throw new P(44);var c=Rb(a);a=dc(b,c);a:{try{var d=dc(b,c)}catch(f){d=f.nb;break a}var e=pc(b,"wx");d=e?e:16384===(d.mode&61440)?
31:0}if(d)throw new P(d);if(!b.gb.jc)throw new P(63);if(a.Pb)throw new P(10);b.gb.jc(b,c);b=oc(a.parent.id,a.name);if(kc[b]===a)kc[b]=a.Kb;else for(b=kc[b];b;){if(b.Kb===a){b.Kb=a.Kb;break}b=b.Kb}},lc=a=>{a=mc(a).node;if(!a)throw new P(44);if(!a.gb.Sb)throw new P(28);return Tb(nc(a.parent),a.gb.Sb(a))},Ac=(a,b)=>{a=mc(a,{Yb:!b}).node;if(!a)throw new P(44);if(!a.gb.vb)throw new P(63);return a.gb.vb(a)},Bc=a=>Ac(a,!0),Cc=(a,b)=>{a="string"==typeof a?mc(a,{Yb:!0}).node:a;if(!a.gb.rb)throw new P(63);
a.gb.rb(a,{mode:b&4095|a.mode&-4096,timestamp:Date.now()})},ib=(a,b,c,d)=>{if(""===a)throw new P(44);if("string"==typeof b){var e=rc[b];if("undefined"==typeof e)throw Error("Unknown file open mode: "+b);b=e}c=b&64?("undefined"==typeof c?438:c)&4095|32768:0;if("object"==typeof a)var f=a;else{a=Pb(a);try{f=mc(a,{Yb:!(b&131072)}).node}catch(h){}}e=!1;if(b&64)if(f){if(b&128)throw new P(20);}else f=R(a,c,0),e=!0;if(!f)throw new P(44);8192===(f.mode&61440)&&(b&=-513);if(b&65536&&16384!==(f.mode&61440))throw new P(54);
if(!e&&(c=f?40960===(f.mode&61440)?32:16384===(f.mode&61440)&&("r"!==sc(b)||b&512)?31:pc(f,sc(b)):44))throw new P(c);if(b&512){c=f;c="string"==typeof c?mc(c,{Yb:!0}).node:c;if(!c.gb.rb)throw new P(63);if(16384===(c.mode&61440))throw new P(31);if(32768!==(c.mode&61440))throw new P(28);if(e=pc(c,"w"))throw new P(e);c.gb.rb(c,{size:0,timestamp:Date.now()})}b&=-131713;d=wc({node:f,path:nc(f),flags:b,seekable:!0,position:0,hb:f.hb,Rd:[],error:!1},d);d.hb.open&&d.hb.open(d);!E.logReadFiles||b&1||(Dc||(Dc=
{}),a in Dc||(Dc[a]=1));return d},Ec=a=>{if(null===a.Bb)throw new P(8);a.lc&&(a.lc=null);try{a.hb.close&&a.hb.close(a)}catch(b){throw b;}finally{ic[a.Bb]=null}a.Bb=null},Fc=(a,b,c)=>{if(null===a.Bb)throw new P(8);if(!a.seekable||!a.hb.Eb)throw new P(70);if(0!=c&&1!=c&&2!=c)throw new P(28);a.position=a.hb.Eb(a,b,c);a.Rd=[]},Gc=(a,b,c,d,e,f)=>{if(0>d||0>e)throw new P(28);if(null===a.Bb)throw new P(8);if(0===(a.flags&2097155))throw new P(8);if(16384===(a.node.mode&61440))throw new P(31);if(!a.hb.write)throw new P(28);
a.seekable&&a.flags&1024&&Fc(a,0,2);var h="undefined"!=typeof e;if(!h)e=a.position;else if(!a.seekable)throw new P(70);b=a.hb.write(a,b,c,d,e,f);h||(a.position+=b);return b},fb=()=>{P||(P=function(a,b){this.node=b;this.Ed=function(c){this.nb=c};this.Ed(a);this.message="FS error"},P.prototype=Error(),P.prototype.constructor=P,[44].forEach(a=>{cc[a]=new P(a);cc[a].stack="<generic error, no stack>"}))},eb,Hc=(a,b)=>{var c=0;a&&(c|=365);b&&(c|=146);return c},Ic=(a,b)=>{a="string"==typeof a?a:nc(a);for(b=
b.split("/").reverse();b.length;){var c=b.pop();if(c){var d=Pb(a+"/"+c);try{R(d,16895,0)}catch(e){}a=d}}return d},Jc=(a,b,c,d)=>{a=Pb(("string"==typeof a?a:nc(a))+"/"+b);c=Hc(c,d);return R(a,(void 0!==c?c:438)&4095|32768,0)},Kc=(a,b,c,d,e,f)=>{var h=b;a&&(a="string"==typeof a?a:nc(a),h=b?Pb(a+"/"+b):a);a=Hc(d,e);h=R(h,(void 0!==a?a:438)&4095|32768,0);if(c){if("string"==typeof c){b=Array(c.length);d=0;for(e=c.length;d<e;++d)b[d]=c.charCodeAt(d);c=b}Cc(h,a|146);b=ib(h,577);Gc(b,c,0,c.length,0,f);Ec(b);
Cc(h,a)}return h},gb=(a,b,c,d)=>{a=Pb(("string"==typeof a?a:nc(a))+"/"+b);b=Hc(!!c,!!d);gb.Hc||(gb.Hc=64);var e=gb.Hc++<<8|0;Wb(e,{open:f=>{f.seekable=!1},close:()=>{d&&d.buffer&&d.buffer.length&&d(10)},read:(f,h,l,m)=>{for(var p=0,n=0;n<m;n++){try{var t=c()}catch(v){throw new P(29);}if(void 0===t&&0===p)throw new P(6);if(null===t||void 0===t)break;p++;h[l+n]=t}p&&(f.node.timestamp=Date.now());return p},write:(f,h,l,m)=>{for(var p=0;p<m;p++)try{d(h[l+p])}catch(n){throw new P(29);}m&&(f.node.timestamp=
Date.now());return p}});return yc(a,b,e)},Lc=a=>{if(!(a.rd||a.sd||a.link||a.fb)){if("undefined"!=typeof XMLHttpRequest)throw Error("Lazy loading should have been performed (contents set) in createLazyFile, but it was not. Lazy loading only works in web workers. Use --embed-file or --preload-file in emcc on the main thread.");if(ya)try{a.fb=Yb(ya(a.url),!0),a.kb=a.fb.length}catch(b){throw new P(29);}else throw Error("Cannot load without read() or XMLHttpRequest.");}},Mc=(a,b,c,d,e)=>{function f(){this.oc=
!1;this.Xb=[]}f.prototype.get=function(n){if(!(n>this.length-1||0>n)){var t=n%this.Bc;return this.Zb(n/this.Bc|0)[t]}};f.prototype.Dd=function(n){this.Zb=n};f.prototype.zc=function(){var n=new XMLHttpRequest;n.open("HEAD",c,!1);n.send(null);if(!(200<=n.status&&300>n.status||304===n.status))throw Error("Couldn't load "+c+". Status: "+n.status);var t=Number(n.getResponseHeader("Content-length")),v,k=(v=n.getResponseHeader("Accept-Ranges"))&&"bytes"===v;n=(v=n.getResponseHeader("Content-Encoding"))&&
"gzip"===v;var u=1048576;k||(u=t);var w=this;w.Dd(B=>{var H=B*u,I=(B+1)*u-1;I=Math.min(I,t-1);if("undefined"==typeof w.Xb[B]){var x=w.Xb;if(H>I)throw Error("invalid range ("+H+", "+I+") or no bytes requested!");if(I>t-1)throw Error("only "+t+" bytes available! programmer error!");var C=new XMLHttpRequest;C.open("GET",c,!1);t!==u&&C.setRequestHeader("Range","bytes="+H+"-"+I);C.responseType="arraybuffer";C.overrideMimeType&&C.overrideMimeType("text/plain; charset=x-user-defined");C.send(null);if(!(200<=
C.status&&300>C.status||304===C.status))throw Error("Couldn't load "+c+". Status: "+C.status);H=void 0!==C.response?new Uint8Array(C.response||[]):Yb(C.responseText||"",!0);x[B]=H}if("undefined"==typeof w.Xb[B])throw Error("doXHR failed!");return w.Xb[B]});if(n||!t)u=t=1,u=t=this.Zb(0).length,Ba("LazyFiles on gzip forces download of the whole file when length is accessed");this.Sc=t;this.Rc=u;this.oc=!0};if("undefined"!=typeof XMLHttpRequest){if(!ua)throw"Cannot do synchronous binary XHRs outside webworkers in modern browsers. Use --embed-file or --preload-file in emcc";
var h=new f;Object.defineProperties(h,{length:{get:function(){this.oc||this.zc();return this.Sc}},Bc:{get:function(){this.oc||this.zc();return this.Rc}}});var l=void 0}else l=c,h=void 0;var m=Jc(a,b,d,e);h?m.fb=h:l&&(m.fb=null,m.url=l);Object.defineProperties(m,{kb:{get:function(){return this.fb.length}}});var p={};Object.keys(m.hb).forEach(n=>{var t=m.hb[n];p[n]=function(){Lc(m);return t.apply(null,arguments)}});p.read=(n,t,v,k,u)=>{Lc(m);n=n.node.fb;if(u>=n.length)return 0;k=Math.min(n.length-u,
k);if(n.slice)for(var w=0;w<k;w++)t[v+w]=n[u+w];else for(w=0;w<k;w++)t[v+w]=n.get(u+w);return k};m.hb=p;return m},Oc=(a,b,c,d,e,f,h,l,m,p)=>{function n(k){function u(w){p&&p();l||Kc(a,b,w,d,e,m);f&&f();qb(v)}Nc.Xd(k,t,u,()=>{h&&h();qb(v)})||u(k)}var t=b?Tb(Pb(a+"/"+b)):a,v="cp "+t;pb(v);"string"==typeof c?fc(c,k=>n(k),h):n(c)},S={},vc,Dc;
function Pc(a,b,c){if("/"===b[0])return b;if(-100===a)a="/";else{a=ic[a];if(!a)throw new P(8);a=a.path}if(0==b.length){if(!c)throw new P(44);return a}return Pb(a+"/"+b)}
function Qc(a,b,c){try{var d=a(b)}catch(e){if(e&&e.node&&Pb(b)!==Pb(nc(e.node)))return-54;throw e;}A()[c>>2]=d.dd;A()[c+4>>2]=0;A()[c+8>>2]=d.mc;A()[c+12>>2]=d.mode;A()[c+16>>2]=d.wd;A()[c+20>>2]=d.uid;A()[c+24>>2]=d.md;A()[c+28>>2]=d.Rb;A()[c+32>>2]=0;vb=[d.size>>>0,(L=d.size,1<=+Math.abs(L)?0<L?(Math.min(+Math.floor(L/4294967296),4294967295)|0)>>>0:~~+Math.ceil((L-+(~~L>>>0))/4294967296)>>>0:0)];A()[c+40>>2]=vb[0];A()[c+44>>2]=vb[1];A()[c+48>>2]=4096;A()[c+52>>2]=d.Yc;A()[c+56>>2]=d.Wc.getTime()/
1E3|0;A()[c+60>>2]=0;A()[c+64>>2]=d.vd.getTime()/1E3|0;A()[c+68>>2]=0;A()[c+72>>2]=d.bd.getTime()/1E3|0;A()[c+76>>2]=0;vb=[d.mc>>>0,(L=d.mc,1<=+Math.abs(L)?0<L?(Math.min(+Math.floor(L/4294967296),4294967295)|0)>>>0:~~+Math.ceil((L-+(~~L>>>0))/4294967296)>>>0:0)];A()[c+80>>2]=vb[0];A()[c+84>>2]=vb[1];return 0}var Rc=void 0;function Sc(){Rc+=4;return A()[Rc-4>>2]}function Tc(a){a=ic[a];if(!a)throw new P(8);return a}
function Uc(a,b,c){if(G)return O(3,1,a,b,c);Rc=c;try{var d=Tc(a);switch(b){case 0:var e=Sc();return 0>e?-28:ib(d.path,d.flags,0,e).Bb;case 1:case 2:return 0;case 3:return d.flags;case 4:return e=Sc(),d.flags|=e,0;case 5:return e=Sc(),da()[e+0>>1]=2,0;case 6:case 7:return 0;case 16:case 8:return-28;case 9:return-1;default:return-28}}catch(f){if("undefined"==typeof S||!(f instanceof P))throw f;return-f.nb}}
function Vc(a,b){if(G)return O(4,1,a,b);try{var c=Tc(a);return Qc(Ac,c.path,b)}catch(d){if("undefined"==typeof S||!(d instanceof P))throw d;return-d.nb}}
function Wc(a,b,c){if(G)return O(5,1,a,b,c);Rc=c;try{var d=Tc(a);switch(b){case 21509:case 21505:return d.mb?0:-59;case 21510:case 21511:case 21512:case 21506:case 21507:case 21508:return d.mb?0:-59;case 21519:if(!d.mb)return-59;var e=Sc();return A()[e>>2]=0;case 21520:return d.mb?-28:-59;case 21531:a=e=Sc();if(!d.hb.qd)throw new P(59);return d.hb.qd(d,b,a);case 21523:return d.mb?0:-59;case 21524:return d.mb?0:-59;default:Fa("bad ioctl syscall "+b)}}catch(f){if("undefined"==typeof S||!(f instanceof
P))throw f;return-f.nb}}function Xc(a,b,c,d){if(G)return O(7,1,a,b,c,d);try{b=K(b);var e=d&256;b=Pc(a,b,d&4096);return Qc(e?Bc:Ac,b,c)}catch(f){if("undefined"==typeof S||!(f instanceof P))throw f;return-f.nb}}function Yc(a,b,c,d){if(G)return O(8,1,a,b,c,d);Rc=d;try{b=K(b);b=Pc(a,b);var e=d?Sc():0;return ib(b,c,e).Bb}catch(f){if("undefined"==typeof S||!(f instanceof P))throw f;return-f.nb}}
function Zc(a,b){if(G)return O(9,1,a,b);try{return a=K(a),Qc(Ac,a,b)}catch(c){if("undefined"==typeof S||!(c instanceof P))throw c;return-c.nb}}var $c={};function ad(a){for(;a.length;){var b=a.pop();a.pop()(b)}}function bd(a){return this.fromWireType(D()[a>>2])}var cd={},dd={},ed={};function fd(a){if(void 0===a)return"_unknown";a=a.replace(/[^a-zA-Z0-9_]/g,"$");var b=a.charCodeAt(0);return 48<=b&&57>=b?"_"+a:a}
function gd(a,b){a=fd(a);return(new Function("body","return function "+a+'() {\n    "use strict";    return body.apply(this, arguments);\n};\n'))(b)}function hd(a){var b=Error,c=gd(a,function(d){this.name=a;this.message=d;d=Error(d).stack;void 0!==d&&(this.stack=this.toString()+"\n"+d.replace(/^Error(:[^\n]*)?\n/,""))});c.prototype=Object.create(b.prototype);c.prototype.constructor=c;c.prototype.toString=function(){return void 0===this.message?this.name:this.name+": "+this.message};return c}
var jd=void 0;function kd(a){throw new jd(a);}function ld(a,b,c){function d(l){l=c(l);l.length!==a.length&&kd("Mismatched type converter count");for(var m=0;m<a.length;++m)md(a[m],l[m])}a.forEach(function(l){ed[l]=b});var e=Array(b.length),f=[],h=0;b.forEach((l,m)=>{dd.hasOwnProperty(l)?e[m]=dd[l]:(f.push(l),cd.hasOwnProperty(l)||(cd[l]=[]),cd[l].push(()=>{e[m]=dd[l];++h;h===f.length&&d(e)}))});0===f.length&&d(e)}
function nd(a){switch(a){case 1:return 0;case 2:return 1;case 4:return 2;case 8:return 3;default:throw new TypeError("Unknown type size: "+a);}}var od=void 0;function T(a){for(var b="";y()[a];)b+=od[y()[a++]];return b}var pd=void 0;function U(a){throw new pd(a);}
function md(a,b,c={}){if(!("argPackAdvance"in b))throw new TypeError("registerType registeredInstance requires argPackAdvance");var d=b.name;a||U('type "'+d+'" must have a positive integer typeid pointer');if(dd.hasOwnProperty(a)){if(c.nd)return;U("Cannot register type '"+d+"' twice")}dd[a]=b;delete ed[a];cd.hasOwnProperty(a)&&(b=cd[a],delete cd[a],b.forEach(e=>e()))}function qd(a){U(a.eb.lb.ib.name+" instance already deleted")}var rd=!1;function sd(){}
function td(a){--a.count.value;0===a.count.value&&(a.qb?a.sb.Ab(a.qb):a.lb.ib.Ab(a.jb))}function ud(a,b,c){if(b===c)return a;if(void 0===c.tb)return null;a=ud(a,b,c.tb);return null===a?null:c.ed(a)}var vd={},wd=[];function xd(){for(;wd.length;){var a=wd.pop();a.eb.Ib=!1;a["delete"]()}}var yd=void 0,zd={};function Ad(a,b){for(void 0===b&&U("ptr should not be undefined");a.tb;)b=a.Vb(b),a=a.tb;return zd[b]}
function Bd(a,b){b.lb&&b.jb||kd("makeClassHandle requires ptr and ptrType");!!b.sb!==!!b.qb&&kd("Both smartPtrType and smartPtr must be specified");b.count={value:1};return Cd(Object.create(a,{eb:{value:b}}))}function Cd(a){if("undefined"===typeof FinalizationRegistry)return Cd=b=>b,a;rd=new FinalizationRegistry(b=>{td(b.eb)});Cd=b=>{var c=b.eb;c.qb&&rd.register(b,{eb:c},b);return b};sd=b=>{rd.unregister(b)};return Cd(a)}function Dd(){}
function Ed(a,b,c){if(void 0===a[b].pb){var d=a[b];a[b]=function(){a[b].pb.hasOwnProperty(arguments.length)||U("Function '"+c+"' called with an invalid number of arguments ("+arguments.length+") - expects one of ("+a[b].pb+")!");return a[b].pb[arguments.length].apply(this,arguments)};a[b].pb=[];a[b].pb[d.Wb]=d}}
function Fd(a,b,c){E.hasOwnProperty(a)?((void 0===c||void 0!==E[a].pb&&void 0!==E[a].pb[c])&&U("Cannot register public name '"+a+"' twice"),Ed(E,a,a),E.hasOwnProperty(c)&&U("Cannot register multiple overloads of a function with the same number of arguments ("+c+")!"),E[a].pb[c]=b):(E[a]=b,void 0!==c&&(E[a].Zd=c))}function Gd(a,b,c,d,e,f,h,l){this.name=a;this.constructor=b;this.Jb=c;this.Ab=d;this.tb=e;this.gd=f;this.Vb=h;this.ed=l;this.yd=[]}
function Hd(a,b,c){for(;b!==c;)b.Vb||U("Expected null or instance of "+c.name+", got an instance of "+b.name),a=b.Vb(a),b=b.tb;return a}function Id(a,b){if(null===b)return this.nc&&U("null is not a valid "+this.name),0;b.eb||U('Cannot pass "'+Jd(b)+'" as a '+this.name);b.eb.jb||U("Cannot pass deleted object as a pointer of type "+this.name);return Hd(b.eb.jb,b.eb.lb.ib,this.ib)}
function Kd(a,b){if(null===b){this.nc&&U("null is not a valid "+this.name);if(this.ac){var c=this.sc();null!==a&&a.push(this.Ab,c);return c}return 0}b.eb||U('Cannot pass "'+Jd(b)+'" as a '+this.name);b.eb.jb||U("Cannot pass deleted object as a pointer of type "+this.name);!this.$b&&b.eb.lb.$b&&U("Cannot convert argument of type "+(b.eb.sb?b.eb.sb.name:b.eb.lb.name)+" to parameter type "+this.name);c=Hd(b.eb.jb,b.eb.lb.ib,this.ib);if(this.ac)switch(void 0===b.eb.qb&&U("Passing raw pointer to smart pointer is illegal"),
this.Jd){case 0:b.eb.sb===this?c=b.eb.qb:U("Cannot convert argument of type "+(b.eb.sb?b.eb.sb.name:b.eb.lb.name)+" to parameter type "+this.name);break;case 1:c=b.eb.qb;break;case 2:if(b.eb.sb===this)c=b.eb.qb;else{var d=b.clone();c=this.zd(c,W(function(){d["delete"]()}));null!==a&&a.push(this.Ab,c)}break;default:U("Unsupporting sharing policy")}return c}
function Ld(a,b){if(null===b)return this.nc&&U("null is not a valid "+this.name),0;b.eb||U('Cannot pass "'+Jd(b)+'" as a '+this.name);b.eb.jb||U("Cannot pass deleted object as a pointer of type "+this.name);b.eb.lb.$b&&U("Cannot convert argument of type "+b.eb.lb.name+" to parameter type "+this.name);return Hd(b.eb.jb,b.eb.lb.ib,this.ib)}
function Md(a,b,c,d){this.name=a;this.ib=b;this.nc=c;this.$b=d;this.ac=!1;this.Ab=this.zd=this.sc=this.Lc=this.Jd=this.xd=void 0;void 0!==b.tb?this.toWireType=Kd:(this.toWireType=d?Id:Ld,this.ub=null)}function Nd(a,b,c){E.hasOwnProperty(a)||kd("Replacing nonexistant public symbol");void 0!==E[a].pb&&void 0!==c?E[a].pb[c]=b:(E[a]=b,E[a].Wb=c)}
function Od(a,b){var c=[];return function(){c.length=0;Object.assign(c,arguments);if(a.includes("j")){var d=E["dynCall_"+a];d=c&&c.length?d.apply(null,[b].concat(c)):d.call(null,b)}else d=M(b).apply(null,c);return d}}function Pd(a,b){a=T(a);var c=a.includes("j")?Od(a,b):M(b);"function"!=typeof c&&U("unknown function pointer with signature "+a+": "+b);return c}var Qd=void 0;function Rd(a){a=Sd(a);var b=T(a);Td(a);return b}
function Ud(a,b){function c(f){e[f]||dd[f]||(ed[f]?ed[f].forEach(c):(d.push(f),e[f]=!0))}var d=[],e={};b.forEach(c);throw new Qd(a+": "+d.map(Rd).join([", "]));}function Vd(a,b){for(var c=[],d=0;d<a;d++)c.push(A()[(b>>2)+d]);return c}
function Wd(a){var b=Function;if(!(b instanceof Function))throw new TypeError("new_ called with constructor type "+typeof b+" which is not a function");var c=gd(b.name||"unknownFunctionName",function(){});c.prototype=b.prototype;c=new c;a=b.apply(c,a);return a instanceof Object?a:c}
function Xd(a,b,c,d,e){var f=b.length;2>f&&U("argTypes array size mismatch! Must at least get return value and 'this' types!");var h=null!==b[1]&&null!==c,l=!1;for(c=1;c<b.length;++c)if(null!==b[c]&&void 0===b[c].ub){l=!0;break}var m="void"!==b[0].name,p="",n="";for(c=0;c<f-2;++c)p+=(0!==c?", ":"")+"arg"+c,n+=(0!==c?", ":"")+"arg"+c+"Wired";a="return function "+fd(a)+"("+p+") {\nif (arguments.length !== "+(f-2)+") {\nthrowBindingError('function "+a+" called with ' + arguments.length + ' arguments, expected "+
(f-2)+" args!');\n}\n";l&&(a+="var destructors = [];\n");var t=l?"destructors":"null";p="throwBindingError invoker fn runDestructors retType classParam".split(" ");d=[U,d,e,ad,b[0],b[1]];h&&(a+="var thisWired = classParam.toWireType("+t+", this);\n");for(c=0;c<f-2;++c)a+="var arg"+c+"Wired = argType"+c+".toWireType("+t+", arg"+c+"); // "+b[c+2].name+"\n",p.push("argType"+c),d.push(b[c+2]);h&&(n="thisWired"+(0<n.length?", ":"")+n);a+=(m?"var rv = ":"")+"invoker(fn"+(0<n.length?", ":"")+n+");\n";if(l)a+=
"runDestructors(destructors);\n";else for(c=h?1:2;c<b.length;++c)f=1===c?"thisWired":"arg"+(c-2)+"Wired",null!==b[c].ub&&(a+=f+"_dtor("+f+"); // "+b[c].name+"\n",p.push(f+"_dtor"),d.push(b[c].ub));m&&(a+="var ret = retType.fromWireType(rv);\nreturn ret;\n");p.push(a+"}\n");return Wd(p).apply(null,d)}var Yd=[],X=[{},{value:void 0},{value:null},{value:!0},{value:!1}];function Zd(a){4<a&&0===--X[a].uc&&(X[a]=void 0,Yd.push(a))}
var Y=a=>{a||U("Cannot use deleted val. handle = "+a);return X[a].value},W=a=>{switch(a){case void 0:return 1;case null:return 2;case !0:return 3;case !1:return 4;default:var b=Yd.length?Yd.pop():X.length;X[b]={uc:1,value:a};return b}};function Jd(a){if(null===a)return"null";var b=typeof a;return"object"===b||"array"===b||"function"===b?a.toString():""+a}
function $d(a,b){switch(b){case 2:return function(c){var d=this.fromWireType;q.buffer!=r&&aa(q.buffer);return d.call(this,Ya[c>>2])};case 3:return function(c){return this.fromWireType(ja()[c>>3])};default:throw new TypeError("Unknown float type: "+a);}}
function ae(a,b,c){switch(b){case 0:return c?function(d){return g()[d]}:function(d){return y()[d]};case 1:return c?function(d){return da()[d>>1]}:function(d){return z()[d>>1]};case 2:return c?function(d){return A()[d>>2]}:function(d){return D()[d>>2]};default:throw new TypeError("Unknown integer type: "+a);}}function be(a,b){var c=dd[a];void 0===c&&U(b+" has unknown type "+Rd(a));return c}function ce(a,b){for(var c=Array(a),d=0;d<a;++d)c[d]=be(A()[(b>>2)+d],"parameter "+d);return c}var de={};
function ee(a){var b=de[a];return void 0===b?T(a):b}var fe=[];function ge(){return"object"==typeof globalThis?globalThis:Function("return this")()}function he(a){var b=fe.length;fe.push(a);return b}var ie=[],je={};
function ke(a,b,c,d,e,f,h,l){if(G)return O(10,1,a,b,c,d,e,f,h,l);try{var m=ic[e];if(!m)return-8;if(0!==(c&2)&&0===(d&2)&&2!==(m.flags&2097155))throw new P(2);if(1===(m.flags&2097155))throw new P(2);if(!m.hb.cc)throw new P(43);var p=m.hb.cc(m,a,b,f,c,d);var n=p.jb;A()[h>>2]=p.Vc;return n}catch(t){if("undefined"==typeof S||!(t instanceof P))throw t;return-t.nb}}
function le(a,b,c,d,e,f){if(G)return O(11,1,a,b,c,d,e,f);try{var h=ic[e];if(h&&c&2){var l=y().slice(a,a+b);h&&h.hb.dc&&h.hb.dc(h,l,f,b,d)}}catch(m){if("undefined"==typeof S||!(m instanceof P))throw m;return-m.nb}}
function me(a,b,c){function d(p){return(p=p.toTimeString().match(/\(([A-Za-z ]+)\)$/))?p[1]:"GMT"}if(G)return O(12,1,a,b,c);var e=(new Date).getFullYear(),f=new Date(e,0,1),h=new Date(e,6,1);e=f.getTimezoneOffset();var l=h.getTimezoneOffset(),m=Math.max(e,l);A()[a>>2]=60*m;A()[b>>2]=Number(e!=l);a=d(f);b=d(h);a=Ua(a);b=Ua(b);l<e?(A()[c>>2]=a,A()[c+4>>2]=b):(A()[c>>2]=b,A()[c+4>>2]=a)}function ne(a,b,c){ne.$c||(ne.$c=!0,me(a,b,c))}var oe=[],pe;
pe=G?()=>performance.now()-E.__performance_now_clock_drift:()=>performance.now();function O(a,b){var c=arguments.length-2,d=arguments;return xb(function(){for(var e=qe(8*c),f=e>>3,h=0;h<c;h++){var l=d[2+h];ja()[f+h]=l}return re(a,c,e,b)})}var se=[],te=[];function Z(a,b){D()[a>>2]=b;D()[a+4>>2]=b/4294967296|0}
function ue(a,b){try{var c=indexedDB.open("emscripten_filesystem",1)}catch(d){b(d);return}c.onupgradeneeded=d=>{d=d.target.result;d.objectStoreNames.contains("FILES")&&d.deleteObjectStore("FILES");d.createObjectStore("FILES")};c.onsuccess=d=>a(d.target.result);c.onerror=d=>b(d)}var ve;
function we(a,b,c,d,e){function f(C){var V=0,J=0;C&&(J=x.response?x.response.byteLength:0,V=Wa(J),y().set(new Uint8Array(x.response),V));D()[a+12>>2]=V;Z(a+16,J)}var h=D()[a+8>>2];if(h){var l=K(h),m=a+112,p=K(m);p||(p="GET");D();var n=D()[m+52>>2],t=D()[m+56>>2],v=!!D()[m+60>>2];D();var k=D()[m+68>>2],u=D()[m+72>>2],w=D()[m+76>>2],B=D()[m+80>>2];h=D()[m+84>>2];m=D()[m+88>>2];var H=!!(n&1),I=!!(n&2);n=!!(n&64);k=k?K(k):void 0;u=u?K(u):void 0;var x=new XMLHttpRequest;x.withCredentials=v;x.open(p,l,
!n,k,u);n||(x.timeout=t);x.ce=l;x.responseType="arraybuffer";B&&(l=K(B),x.overrideMimeType(l));if(w)for(;;){p=D()[w>>2];if(!p)break;l=D()[w+4>>2];if(!l)break;w+=8;p=K(p);l=K(l);x.setRequestHeader(p,l)}te.push(x);w=te.length;D()[a+0>>2]=w;h=h&&m?y().slice(h,h+m):null;x.onload=C=>{f(H&&!I);var V=x.response?x.response.byteLength:0;Z(a+24,0);V&&Z(a+32,V);z()[a+40>>1]=x.readyState;z()[a+42>>1]=x.status;x.statusText&&La(x.statusText,a+44,64);200<=x.status&&300>x.status?b&&b(a,x,C):c&&c(a,x,C)};x.onerror=
C=>{f(H);var V=x.status;Z(a+24,0);Z(a+32,x.response?x.response.byteLength:0);z()[a+40>>1]=x.readyState;z()[a+42>>1]=V;c&&c(a,x,C)};x.ontimeout=C=>{c&&c(a,x,C)};x.onprogress=C=>{var V=H&&I&&x.response?x.response.byteLength:0,J=0;H&&I&&(J=Wa(V),y().set(new Uint8Array(x.response),J));D()[a+12>>2]=J;Z(a+16,V);Z(a+24,C.loaded-V);Z(a+32,C.total);z()[a+40>>1]=x.readyState;3<=x.readyState&&0===x.status&&0<C.loaded&&(x.status=200);z()[a+42>>1]=x.status;x.statusText&&La(x.statusText,a+44,64);d&&d(a,x,C);J&&
Td(J)};x.onreadystatechange=C=>{z()[a+40>>1]=x.readyState;2<=x.readyState&&(z()[a+42>>1]=x.status);e&&e(a,x,C)};try{x.send(h)}catch(C){c&&c(a,x,C)}}else c(a,0,"no url specified!")}function xe(a,b){if(!Ha)if(b)a();else try{a()}catch(c){Cb(c)}}
function ye(a,b,c,d){var e=ve;if(e){var f=a+112;(f=D()[f+64>>2])||(f=D()[a+8>>2]);var h=K(f);try{var l=e.transaction(["FILES"],"readwrite").objectStore("FILES").put(b,h);l.onsuccess=()=>{z()[a+40>>1]=4;z()[a+42>>1]=200;La("OK",a+44,64);c(a,0,h)};l.onerror=m=>{z()[a+40>>1]=4;z()[a+42>>1]=413;La("Payload Too Large",a+44,64);d(a,0,m)}}catch(m){d(a,0,m)}}else d(a,0,"IndexedDB not available!")}
function ze(a,b,c){var d=ve;if(d){var e=a+112;(e=D()[e+64>>2])||(e=D()[a+8>>2]);e=K(e);try{var f=d.transaction(["FILES"],"readonly").objectStore("FILES").get(e);f.onsuccess=h=>{if(h.target.result){h=h.target.result;var l=h.byteLength||h.length,m=Wa(l);y().set(new Uint8Array(h),m);D()[a+12>>2]=m;Z(a+16,l);Z(a+24,0);Z(a+32,l);z()[a+40>>1]=4;z()[a+42>>1]=200;La("OK",a+44,64);b(a,0,h)}else z()[a+40>>1]=4,z()[a+42>>1]=404,La("Not Found",a+44,64),c(a,0,"no data")};f.onerror=h=>{z()[a+40>>1]=4;z()[a+42>>
1]=404;La("Not Found",a+44,64);c(a,0,h)}}catch(h){c(a,0,h)}}else c(a,0,"IndexedDB not available!")}
function Ae(a,b,c){var d=ve;if(d){var e=a+112;(e=D()[e+64>>2])||(e=D()[a+8>>2]);e=K(e);try{var f=d.transaction(["FILES"],"readwrite").objectStore("FILES").delete(e);f.onsuccess=h=>{h=h.target.result;D()[a+12>>2]=0;Z(a+16,0);Z(a+24,0);Z(a+32,0);z()[a+40>>1]=4;z()[a+42>>1]=200;La("OK",a+44,64);b(a,0,h)};f.onerror=h=>{z()[a+40>>1]=4;z()[a+42>>1]=404;La("Not Found",a+44,64);c(a,0,h)}}catch(h){c(a,0,h)}}else c(a,0,"IndexedDB not available!")}var Be={};
function Ce(){if(!De){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"==typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:ra||"./this.program"},b;for(b in Be)void 0===Be[b]?delete a[b]:a[b]=Be[b];var c=[];for(b in a)c.push(b+"="+a[b]);De=c}return De}var De;
function Ee(a,b){if(G)return O(13,1,a,b);var c=0;Ce().forEach(function(d,e){var f=b+c;e=A()[a+4*e>>2]=f;for(f=0;f<d.length;++f)g()[e++>>0]=d.charCodeAt(f);g()[e>>0]=0;c+=d.length+1});return 0}function Fe(a,b){if(G)return O(14,1,a,b);var c=Ce();A()[a>>2]=c.length;var d=0;c.forEach(function(e){d+=e.length+1});A()[b>>2]=d;return 0}function Ge(a){if(G)return O(15,1,a);try{var b=Tc(a);Ec(b);return 0}catch(c){if("undefined"==typeof S||!(c instanceof P))throw c;return c.nb}}
function He(a,b,c,d){if(G)return O(16,1,a,b,c,d);try{a:{for(var e=Tc(a),f=a=0;f<c;f++){var h=A()[b+8*f>>2],l=A()[b+(8*f+4)>>2],m=e,p=g(),n=h,t=l,v=void 0;if(0>t||0>v)throw new P(28);if(null===m.Bb)throw new P(8);if(1===(m.flags&2097155))throw new P(8);if(16384===(m.node.mode&61440))throw new P(31);if(!m.hb.read)throw new P(28);var k="undefined"!=typeof v;if(!k)v=m.position;else if(!m.seekable)throw new P(70);var u=m.hb.read(m,p,n,t,v);k||(m.position+=u);var w=u;if(0>w){var B=-1;break a}a+=w;if(w<
l)break}B=a}A()[d>>2]=B;return 0}catch(H){if("undefined"==typeof S||!(H instanceof P))throw H;return H.nb}}
function Ie(a,b,c,d,e){if(G)return O(17,1,a,b,c,d,e);try{var f=Tc(a);a=4294967296*c+(b>>>0);if(-9007199254740992>=a||9007199254740992<=a)return-61;Fc(f,a,d);vb=[f.position>>>0,(L=f.position,1<=+Math.abs(L)?0<L?(Math.min(+Math.floor(L/4294967296),4294967295)|0)>>>0:~~+Math.ceil((L-+(~~L>>>0))/4294967296)>>>0:0)];A()[e>>2]=vb[0];A()[e+4>>2]=vb[1];f.lc&&0===a&&0===d&&(f.lc=null);return 0}catch(h){if("undefined"==typeof S||!(h instanceof P))throw h;return h.nb}}
function Je(a,b,c,d){if(G)return O(18,1,a,b,c,d);try{a:{for(var e=Tc(a),f=a=0;f<c;f++){var h=A()[b+8*f>>2],l=A()[b+(8*f+4)>>2],m=Gc(e,g(),h,l,void 0);if(0>m){var p=-1;break a}a+=m}p=a}A()[d>>2]=p;return 0}catch(n){if("undefined"==typeof S||!(n instanceof P))throw n;return n.nb}}function Ke(a,b){Ke.Kc||(Ke.Kc=Sb());for(var c=0;c<b;c++)g()[a+c>>0]=Ke.Kc();return 0}function Le(a){return 0===a%4&&(0!==a%100||0===a%400)}
var Me=[31,29,31,30,31,30,31,31,30,31,30,31],Ne=[31,28,31,30,31,30,31,31,30,31,30,31];
function Oe(a,b,c,d){function e(k,u,w){for(k="number"==typeof k?k.toString():k||"";k.length<u;)k=w[0]+k;return k}function f(k,u){return e(k,u,"0")}function h(k,u){function w(H){return 0>H?-1:0<H?1:0}var B;0===(B=w(k.getFullYear()-u.getFullYear()))&&0===(B=w(k.getMonth()-u.getMonth()))&&(B=w(k.getDate()-u.getDate()));return B}function l(k){switch(k.getDay()){case 0:return new Date(k.getFullYear()-1,11,29);case 1:return k;case 2:return new Date(k.getFullYear(),0,3);case 3:return new Date(k.getFullYear(),
0,2);case 4:return new Date(k.getFullYear(),0,1);case 5:return new Date(k.getFullYear()-1,11,31);case 6:return new Date(k.getFullYear()-1,11,30)}}function m(k){var u=k.Fb;for(k=new Date((new Date(k.Gb+1900,0,1)).getTime());0<u;){var w=k.getMonth(),B=(Le(k.getFullYear())?Me:Ne)[w];if(u>B-k.getDate())u-=B-k.getDate()+1,k.setDate(1),11>w?k.setMonth(w+1):(k.setMonth(0),k.setFullYear(k.getFullYear()+1));else{k.setDate(k.getDate()+u);break}}w=new Date(k.getFullYear()+1,0,4);u=l(new Date(k.getFullYear(),
0,4));w=l(w);return 0>=h(u,k)?0>=h(w,k)?k.getFullYear()+1:k.getFullYear():k.getFullYear()-1}var p=A()[d+40>>2];d={Od:A()[d>>2],Nd:A()[d+4>>2],hc:A()[d+8>>2],xc:A()[d+12>>2],ic:A()[d+16>>2],Gb:A()[d+20>>2],yb:A()[d+24>>2],Fb:A()[d+28>>2],be:A()[d+32>>2],Md:A()[d+36>>2],Pd:p?K(p):""};c=K(c);p={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S","%x":"%m/%d/%y","%X":"%H:%M:%S","%Ec":"%c","%EC":"%C","%Ex":"%m/%d/%y","%EX":"%H:%M:%S","%Ey":"%y",
"%EY":"%Y","%Od":"%d","%Oe":"%e","%OH":"%H","%OI":"%I","%Om":"%m","%OM":"%M","%OS":"%S","%Ou":"%u","%OU":"%U","%OV":"%V","%Ow":"%w","%OW":"%W","%Oy":"%y"};for(var n in p)c=c.replace(new RegExp(n,"g"),p[n]);var t="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),v="January February March April May June July August September October November December".split(" ");p={"%a":function(k){return t[k.yb].substring(0,3)},"%A":function(k){return t[k.yb]},"%b":function(k){return v[k.ic].substring(0,
3)},"%B":function(k){return v[k.ic]},"%C":function(k){return f((k.Gb+1900)/100|0,2)},"%d":function(k){return f(k.xc,2)},"%e":function(k){return e(k.xc,2," ")},"%g":function(k){return m(k).toString().substring(2)},"%G":function(k){return m(k)},"%H":function(k){return f(k.hc,2)},"%I":function(k){k=k.hc;0==k?k=12:12<k&&(k-=12);return f(k,2)},"%j":function(k){for(var u=0,w=0;w<=k.ic-1;u+=(Le(k.Gb+1900)?Me:Ne)[w++]);return f(k.xc+u,3)},"%m":function(k){return f(k.ic+1,2)},"%M":function(k){return f(k.Nd,
2)},"%n":function(){return"\n"},"%p":function(k){return 0<=k.hc&&12>k.hc?"AM":"PM"},"%S":function(k){return f(k.Od,2)},"%t":function(){return"\t"},"%u":function(k){return k.yb||7},"%U":function(k){return f(Math.floor((k.Fb+7-k.yb)/7),2)},"%V":function(k){var u=Math.floor((k.Fb+7-(k.yb+6)%7)/7);2>=(k.yb+371-k.Fb-2)%7&&u++;if(u)53==u&&(w=(k.yb+371-k.Fb)%7,4==w||3==w&&Le(k.Gb)||(u=1));else{u=52;var w=(k.yb+7-k.Fb-1)%7;(4==w||5==w&&Le(k.Gb%400-1))&&u++}return f(u,2)},"%w":function(k){return k.yb},"%W":function(k){return f(Math.floor((k.Fb+
7-(k.yb+6)%7)/7),2)},"%y":function(k){return(k.Gb+1900).toString().substring(2)},"%Y":function(k){return k.Gb+1900},"%z":function(k){k=k.Md;var u=0<=k;k=Math.abs(k)/60;return(u?"+":"-")+String("0000"+(k/60*100+k%60)).slice(-4)},"%Z":function(k){return k.Pd},"%%":function(){return"%"}};c=c.replace(/%%/g,"\x00\x00");for(n in p)c.includes(n)&&(c=c.replace(new RegExp(n,"g"),p[n](d)));c=c.replace(/\0\0/g,"%");n=Yb(c,!1);if(n.length>b)return 0;Xa(n,a);return n.length-1}N.od();
function qc(a,b,c,d){a||(a=this);this.parent=a;this.zb=a.zb;this.Pb=null;this.id=jc++;this.name=b;this.mode=c;this.gb={};this.hb={};this.Rb=d}Object.defineProperties(qc.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}},sd:{get:function(){return 16384===(this.mode&61440)}},rd:{get:function(){return 8192===(this.mode&61440)}}});fb();
kc=Array(4096);xc(Q,"/");R("/tmp",16895,0);R("/home",16895,0);R("/home/web_user",16895,0);(()=>{R("/dev",16895,0);Wb(259,{read:()=>0,write:(b,c,d,e)=>e});yc("/dev/null",259);Vb(1280,Zb);Vb(1536,$b);yc("/dev/tty",1280);yc("/dev/tty1",1536);var a=Sb();gb("/dev","random",a);gb("/dev","urandom",a);R("/dev/shm",16895,0);R("/dev/shm/tmp",16895,0)})();
(()=>{R("/proc",16895,0);var a=R("/proc/self",16895,0);R("/proc/self/fd",16895,0);xc({zb:()=>{var b=bc(a,"fd",16895,73);b.gb={Ob:(c,d)=>{var e=ic[+d];if(!e)throw new P(8);c={parent:null,zb:{Ic:"fake"},gb:{Sb:()=>e.path}};return c.parent=c}};return b}},"/proc/self/fd")})();var Nc;E.FS_createPath=Ic;E.FS_createDataFile=Kc;E.FS_createPreloadedFile=Oc;E.FS_createLazyFile=Mc;E.FS_createDevice=gb;E.FS_unlink=zc;jd=E.InternalError=hd("InternalError");for(var Pe=Array(256),Qe=0;256>Qe;++Qe)Pe[Qe]=String.fromCharCode(Qe);
od=Pe;pd=E.BindingError=hd("BindingError");Dd.prototype.isAliasOf=function(a){if(!(this instanceof Dd&&a instanceof Dd))return!1;var b=this.eb.lb.ib,c=this.eb.jb,d=a.eb.lb.ib;for(a=a.eb.jb;b.tb;)c=b.Vb(c),b=b.tb;for(;d.tb;)a=d.Vb(a),d=d.tb;return b===d&&c===a};
Dd.prototype.clone=function(){this.eb.jb||qd(this);if(this.eb.Qb)return this.eb.count.value+=1,this;var a=Cd,b=Object,c=b.create,d=Object.getPrototypeOf(this),e=this.eb;a=a(c.call(b,d,{eb:{value:{count:e.count,Ib:e.Ib,Qb:e.Qb,jb:e.jb,lb:e.lb,qb:e.qb,sb:e.sb}}}));a.eb.count.value+=1;a.eb.Ib=!1;return a};Dd.prototype["delete"]=function(){this.eb.jb||qd(this);this.eb.Ib&&!this.eb.Qb&&U("Object already scheduled for deletion");sd(this);td(this.eb);this.eb.Qb||(this.eb.qb=void 0,this.eb.jb=void 0)};
Dd.prototype.isDeleted=function(){return!this.eb.jb};Dd.prototype.deleteLater=function(){this.eb.jb||qd(this);this.eb.Ib&&!this.eb.Qb&&U("Object already scheduled for deletion");wd.push(this);1===wd.length&&yd&&yd(xd);this.eb.Ib=!0;return this};E.getInheritedInstanceCount=function(){return Object.keys(zd).length};E.getLiveInheritedInstances=function(){var a=[],b;for(b in zd)zd.hasOwnProperty(b)&&a.push(zd[b]);return a};E.flushPendingDeletes=xd;E.setDelayFunction=function(a){yd=a;wd.length&&yd&&yd(xd)};
Md.prototype.jd=function(a){this.Lc&&(a=this.Lc(a));return a};Md.prototype.Cc=function(a){this.Ab&&this.Ab(a)};Md.prototype.argPackAdvance=8;Md.prototype.readValueFromPointer=bd;Md.prototype.deleteObject=function(a){if(null!==a)a["delete"]()};
Md.prototype.fromWireType=function(a){function b(){return this.ac?Bd(this.ib.Jb,{lb:this.xd,jb:c,sb:this,qb:a}):Bd(this.ib.Jb,{lb:this,jb:a})}var c=this.jd(a);if(!c)return this.Cc(a),null;var d=Ad(this.ib,c);if(void 0!==d){if(0===d.eb.count.value)return d.eb.jb=c,d.eb.qb=a,d.clone();d=d.clone();this.Cc(a);return d}d=this.ib.gd(c);d=vd[d];if(!d)return b.call(this);d=this.$b?d.ad:d.pointerType;var e=ud(c,this.ib,d.ib);return null===e?b.call(this):this.ac?Bd(d.ib.Jb,{lb:d,jb:e,sb:this,qb:a}):Bd(d.ib.Jb,
{lb:d,jb:e})};Qd=E.UnboundTypeError=hd("UnboundTypeError");E.count_emval_handles=function(){for(var a=0,b=5;b<X.length;++b)void 0!==X[b]&&++a;return a};E.get_first_emval=function(){for(var a=5;a<X.length;++a)if(void 0!==X[a])return X[a];return null};G||(ue(a=>{ve=a;qb("library_fetch_init")},()=>{ve=!1;qb("library_fetch_init")}),"undefined"!=typeof ENVIRONMENT_IS_FETCH_WORKER&&ENVIRONMENT_IS_FETCH_WORKER||pb("library_fetch_init"));
var Re=[null,Jb,Mb,Uc,Vc,Wc,function(a,b){if(G)return O(6,1,a,b);try{return a=K(a),Qc(Bc,a,b)}catch(c){if("undefined"==typeof S||!(c instanceof P))throw c;return-c.nb}},Xc,Yc,Zc,ke,le,me,Ee,Fe,Ge,He,Ie,Je];function Yb(a,b){var c=Array(Ma(a)+1);a=Ka(a,c,0,c.length);b&&(c.length=a);return c}
var Ye={ea:function(a){Se(a,!ua,1,!ta);N.Qc()},B:function(a){G?postMessage({cmd:"cleanupThread",thread:a}):Ab(a)},Z:Nb,F:Uc,ja:Vc,ka:Wc,ha:Xc,G:Yc,ia:Zc,c:function(a){var b=$c[a];delete $c[a];var c=b.sc,d=b.Ab,e=b.Ec,f=e.map(h=>h.ld).concat(e.map(h=>h.Hd));ld([a],f,h=>{var l={};e.forEach((m,p)=>{var n=h[p],t=m.Zb,v=m.kd,k=h[p+e.length],u=m.Gd,w=m.Id;l[m.fd]={read:B=>n.fromWireType(t(v,B)),write:(B,H)=>{var I=[];u(w,B,k.toWireType(I,H));ad(I)}}});return[{name:b.name,fromWireType:function(m){var p=
{},n;for(n in l)p[n]=l[n].read(m);d(m);return p},toWireType:function(m,p){for(var n in l)if(!(n in p))throw new TypeError('Missing field:  "'+n+'"');var t=c();for(n in l)l[n].write(t,p[n]);null!==m&&m.push(d,t);return t},argPackAdvance:8,readValueFromPointer:bd,ub:d}]})},P:function(){},sa:function(a,b,c,d,e){var f=nd(c);b=T(b);md(a,{name:b,fromWireType:function(h){return!!h},toWireType:function(h,l){return l?d:e},argPackAdvance:8,readValueFromPointer:function(h){if(1===c)var l=g();else if(2===c)l=
da();else if(4===c)l=A();else throw new TypeError("Unknown boolean type size: "+b);return this.fromWireType(l[h>>f])},ub:null})},s:function(a,b,c,d,e,f,h,l,m,p,n,t,v){n=T(n);f=Pd(e,f);l&&(l=Pd(h,l));p&&(p=Pd(m,p));v=Pd(t,v);var k=fd(n);Fd(k,function(){Ud("Cannot construct "+n+" due to unbound types",[d])});ld([a,b,c],d?[d]:[],function(u){u=u[0];if(d){var w=u.ib;var B=w.Jb}else B=Dd.prototype;u=gd(k,function(){if(Object.getPrototypeOf(this)!==H)throw new pd("Use 'new' to construct "+n);if(void 0===
I.Db)throw new pd(n+" has no accessible constructor");var C=I.Db[arguments.length];if(void 0===C)throw new pd("Tried to invoke ctor of "+n+" with invalid number of parameters ("+arguments.length+") - expected ("+Object.keys(I.Db).toString()+") parameters instead!");return C.apply(this,arguments)});var H=Object.create(B,{constructor:{value:u}});u.prototype=H;var I=new Gd(n,u,H,v,w,f,l,p);w=new Md(n,I,!0,!1);B=new Md(n+"*",I,!1,!1);var x=new Md(n+" const*",I,!1,!0);vd[a]={pointerType:B,ad:x};Nd(k,u);
return[w,B,x]})},t:function(a,b,c,d,e,f){0<b||Fa(void 0);var h=Vd(b,c);e=Pd(d,e);ld([],[a],function(l){l=l[0];var m="constructor "+l.name;void 0===l.ib.Db&&(l.ib.Db=[]);if(void 0!==l.ib.Db[b-1])throw new pd("Cannot register multiple constructors with identical number of parameters ("+(b-1)+") for class '"+l.name+"'! Overload resolution is currently only performed using the parameter count, not actual type info!");l.ib.Db[b-1]=()=>{Ud("Cannot construct "+l.name+" due to unbound types",h)};ld([],h,
function(p){p.splice(1,0,null);l.ib.Db[b-1]=Xd(m,p,null,e,f);return[]});return[]})},f:function(a,b,c,d,e,f,h,l){var m=Vd(c,d);b=T(b);f=Pd(e,f);ld([],[a],function(p){function n(){Ud("Cannot call "+t+" due to unbound types",m)}p=p[0];var t=p.name+"."+b;b.startsWith("@@")&&(b=Symbol[b.substring(2)]);l&&p.ib.yd.push(b);var v=p.ib.Jb,k=v[b];void 0===k||void 0===k.pb&&k.className!==p.name&&k.Wb===c-2?(n.Wb=c-2,n.className=p.name,v[b]=n):(Ed(v,b,t),v[b].pb[c-2]=n);ld([],m,function(u){u=Xd(t,u,p,f,h);void 0===
v[b].pb?(u.Wb=c-2,v[b]=u):v[b].pb[c-2]=u;return[]});return[]})},ra:function(a,b){b=T(b);md(a,{name:b,fromWireType:function(c){var d=Y(c);Zd(c);return d},toWireType:function(c,d){return W(d)},argPackAdvance:8,readValueFromPointer:bd,ub:null})},I:function(a,b,c){c=nd(c);b=T(b);md(a,{name:b,fromWireType:function(d){return d},toWireType:function(d,e){return e},argPackAdvance:8,readValueFromPointer:$d(b,c),ub:null})},z:function(a,b,c,d,e,f){var h=Vd(b,c);a=T(a);e=Pd(d,e);Fd(a,function(){Ud("Cannot call "+
a+" due to unbound types",h)},b-1);ld([],h,function(l){Nd(a,Xd(a,[l[0],null].concat(l.slice(1)),null,e,f),b-1);return[]})},k:function(a,b,c,d,e){b=T(b);-1===e&&(e=4294967295);e=nd(c);var f=l=>l;if(0===d){var h=32-8*c;f=l=>l<<h>>>h}c=b.includes("unsigned")?function(l,m){return m>>>0}:function(l,m){return m};md(a,{name:b,fromWireType:f,toWireType:c,argPackAdvance:8,readValueFromPointer:ae(b,e,0!==d),ub:null})},e:function(a,b,c){function d(f){f>>=2;var h=D();return new e(r,h[f+1],h[f])}var e=[Int8Array,
Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array][b];c=T(c);md(a,{name:c,fromWireType:d,argPackAdvance:8,readValueFromPointer:d},{nd:!0})},J:function(a,b){b=T(b);var c="std::string"===b;md(a,{name:b,fromWireType:function(d){var e=D()[d>>2];if(c)for(var f=d+4,h=0;h<=e;++h){var l=d+4+h;if(h==e||0==y()[l]){f=K(f,l-f);if(void 0===m)var m=f;else m+=String.fromCharCode(0),m+=f;f=l+1}}else{m=Array(e);for(h=0;h<e;++h)m[h]=String.fromCharCode(y()[d+4+h]);m=m.join("")}Td(d);
return m},toWireType:function(d,e){e instanceof ArrayBuffer&&(e=new Uint8Array(e));var f="string"==typeof e;f||e instanceof Uint8Array||e instanceof Uint8ClampedArray||e instanceof Int8Array||U("Cannot pass non-string to std::string");var h=(c&&f?()=>Ma(e):()=>e.length)(),l=Wa(4+h+1);D()[l>>2]=h;if(c&&f)La(e,l+4,h+1);else if(f)for(f=0;f<h;++f){var m=e.charCodeAt(f);255<m&&(Td(l),U("String has UTF-16 code units that do not fit in 8 bits"));y()[l+4+f]=m}else for(f=0;f<h;++f)y()[l+4+f]=e[f];null!==d&&
d.push(Td,l);return l},argPackAdvance:8,readValueFromPointer:bd,ub:function(d){Td(d)}})},x:function(a,b,c){c=T(c);if(2===b){var d=Oa;var e=Pa;var f=Qa;var h=()=>z();var l=1}else 4===b&&(d=Ra,e=Sa,f=Ta,h=()=>D(),l=2);md(a,{name:c,fromWireType:function(m){for(var p=D()[m>>2],n=h(),t,v=m+4,k=0;k<=p;++k){var u=m+4+k*b;if(k==p||0==n[u>>l])v=d(v,u-v),void 0===t?t=v:(t+=String.fromCharCode(0),t+=v),v=u+b}Td(m);return t},toWireType:function(m,p){"string"!=typeof p&&U("Cannot pass non-string to C++ string type "+
c);var n=f(p),t=Wa(4+n+b);D()[t>>2]=n>>l;e(p,t+4,n+b);null!==m&&m.push(Td,t);return t},argPackAdvance:8,readValueFromPointer:bd,ub:function(m){Td(m)}})},d:function(a,b,c,d,e,f){$c[a]={name:T(b),sc:Pd(c,d),Ab:Pd(e,f),Ec:[]}},b:function(a,b,c,d,e,f,h,l,m,p){$c[a].Ec.push({fd:T(b),ld:c,Zb:Pd(d,e),kd:f,Hd:h,Gd:Pd(l,m),Id:p})},ta:function(a,b){b=T(b);md(a,{td:!0,name:b,argPackAdvance:0,fromWireType:function(){},toWireType:function(){}})},H:function(){return Date.now()},_:function(){return 2097152},ua:function(a){delete te[a-
1]},na:function(){return!0},$:function(a,b,c,d){if(a==b)setTimeout(()=>{Gb()&&Hb(d);Atomics.sub(A(),d>>2,1)});else if(G)postMessage({targetThread:a,cmd:"processProxyingQueue",queue:d});else{a=(a=N.xb[a])&&a.worker;if(!a)return;a.postMessage({cmd:"processProxyingQueue",queue:d})}return 1},da:function(){return-1},U:function(){throw Infinity;},l:function(a,b,c){a=Y(a);b=be(b,"emval::as");var d=[],e=W(d);A()[c>>2]=e;return b.toWireType(d,a)},Aa:function(a,b,c,d){a=Y(a);c=ce(b,c);for(var e=Array(b),f=
0;f<b;++f){var h=c[f];e[f]=h.readValueFromPointer(d);d+=h.argPackAdvance}a=a.apply(void 0,e);return W(a)},r:function(a,b,c,d){a=fe[a];b=Y(b);c=ee(c);a(b,c,null,d)},C:Zd,Ba:function(a,b){a=Y(a);b=Y(b);return a==b},xa:function(a){if(0===a)return W(ge());a=ee(a);return W(ge()[a])},q:function(a,b){var c=ce(a,b),d=c[0];b=d.name+"_$"+c.slice(1).map(function(n){return n.name}).join("_")+"$";var e=ie[b];if(void 0!==e)return e;e=["retType"];for(var f=[d],h="",l=0;l<a-1;++l)h+=(0!==l?", ":"")+"arg"+l,e.push("argType"+
l),f.push(c[1+l]);var m="return function "+fd("methodCaller_"+b)+"(handle, name, destructors, args) {\n",p=0;for(l=0;l<a-1;++l)m+="    var arg"+l+" = argType"+l+".readValueFromPointer(args"+(p?"+"+p:"")+");\n",p+=c[l+1].argPackAdvance;m+="    var rv = handle[name]("+h+");\n";for(l=0;l<a-1;++l)c[l+1].deleteObject&&(m+="    argType"+l+".deleteObject(arg"+l+");\n");d.td||(m+="    return retType.toWireType(destructors, rv);\n");e.push(m+"};\n");a=Wd(e).apply(null,f);e=he(a);return ie[b]=e},p:function(a,
b){a=Y(a);b=Y(b);return W(a[b])},L:function(a){4<a&&(X[a].uc+=1)},ya:function(a,b){a=Y(a);b=Y(b);return a instanceof b},y:function(a,b,c,d){a=Y(a);var e=je[b];if(!e){e="";for(var f=0;f<b;++f)e+=(0!==f?", ":"")+"arg"+f;var h="return function emval_allocator_"+b+"(constructor, argTypes, args) {\n";for(f=0;f<b;++f)h+="var argType"+f+" = requireRegisteredType(Module['HEAP32'][(argTypes >>> 2) + "+f+'], "parameter '+f+'");\nvar arg'+f+" = argType"+f+".readValueFromPointer(args);\nargs += argType"+f+"['argPackAdvance'];\n";
e=(new Function("requireRegisteredType","Module","valueToHandle",h+("var obj = new constructor("+e+");\nreturn valueToHandle(obj);\n}\n")))(be,E,W);je[b]=e}return e(a,c,d)},S:function(){return W([])},Ea:function(a){return W(ee(a))},N:function(){return W({})},Da:function(a){var b=Y(a);ad(b);Zd(a)},h:function(a,b,c){a=Y(a);b=Y(b);c=Y(c);a[b]=c},j:function(a,b){a=be(a,"_emval_take_value");a=a.readValueFromPointer(b);return W(a)},Ca:function(a){a=Y(a);return W(typeof a)},oa:function(a,b){a=new Date(1E3*
A()[a>>2]);A()[b>>2]=a.getSeconds();A()[b+4>>2]=a.getMinutes();A()[b+8>>2]=a.getHours();A()[b+12>>2]=a.getDate();A()[b+16>>2]=a.getMonth();A()[b+20>>2]=a.getFullYear()-1900;A()[b+24>>2]=a.getDay();var c=new Date(a.getFullYear(),0,1),d=(a.getTime()-c.getTime())/864E5|0;A()[b+28>>2]=d;A()[b+36>>2]=-(60*a.getTimezoneOffset());d=(new Date(a.getFullYear(),6,1)).getTimezoneOffset();c=c.getTimezoneOffset();a=(d!=c&&a.getTimezoneOffset()==Math.min(c,d))|0;A()[b+32>>2]=a},pa:function(a){var b=new Date(A()[a+
20>>2]+1900,A()[a+16>>2],A()[a+12>>2],A()[a+8>>2],A()[a+4>>2],A()[a>>2],0),c=A()[a+32>>2],d=b.getTimezoneOffset(),e=new Date(b.getFullYear(),0,1),f=(new Date(b.getFullYear(),6,1)).getTimezoneOffset(),h=e.getTimezoneOffset(),l=Math.min(h,f);0>c?A()[a+32>>2]=Number(f!=h&&l==d):0<c!=(l==d)&&(f=Math.max(h,f),b.setTime(b.getTime()+6E4*((0<c?l:f)-d)));A()[a+24>>2]=b.getDay();c=(b.getTime()-e.getTime())/864E5|0;A()[a+28>>2]=c;A()[a>>2]=b.getSeconds();A()[a+4>>2]=b.getMinutes();A()[a+8>>2]=b.getHours();A()[a+
12>>2]=b.getDate();A()[a+16>>2]=b.getMonth();return b.getTime()/1E3|0},aa:ke,ba:le,qa:ne,m:function(){Fa("")},M:function(){var a=E.allowedThreads;return a?a:navigator.hardwareConcurrency},o:function(a,b,c){oe.length=0;var d;for(c>>=2;d=y()[b++];)(d=105>d)&&c&1&&c++,oe.push(d?ja()[c++>>1]:A()[c]),++c;return wb[a].apply(null,oe)},D:function(){ua||(Ca||(Ca={}),Ca["Blocking on the main thread is very dangerous, see https://emscripten.org/docs/porting/pthreads.html#blocking-on-the-main-browser-thread"]||
(Ca["Blocking on the main thread is very dangerous, see https://emscripten.org/docs/porting/pthreads.html#blocking-on-the-main-browser-thread"]=1,F("Blocking on the main thread is very dangerous, see https://emscripten.org/docs/porting/pthreads.html#blocking-on-the-main-browser-thread")))},Y:function(){return 838860800},n:pe,wa:function(){return"undefined"!=typeof SharedArrayBuffer},la:function(a,b,c){y().copyWithin(a,b,b+c)},ca:function(a,b,c){se.length=b;c>>=3;for(var d=0;d<b;d++)se[d]=ja()[c+d];
return(0>a?wb[-a-1]:Re[a]).apply(null,se)},X:function(a){var b=y().length;a>>>=0;if(a<=b||838860800<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);var e=Math;d=Math.max(a,d);e=e.min.call(e,838860800,d+(65536-d%65536)%65536);a:{try{q.grow(e-r.byteLength+65535>>>16);aa(q.buffer);var f=1;break a}catch(h){}f=void 0}if(f)return!0}return!1},va:function(a,b,c,d,e){var f=a+112,h=K(f),l=D()[f+36>>2],m=D()[f+40>>2],p=D()[f+44>>2],n=D()[f+48>>2],t=D()[f+52>>2],v=!!(t&4),k=!!(t&
32),u=!!(t&16),w=!!(t&64),B=J=>{xe(()=>{l?M(l)(J):b&&b(J)},w)},H=J=>{xe(()=>{p?M(p)(J):d&&d(J)},w)},I=J=>{xe(()=>{m?M(m)(J):c&&c(J)},w)},x=J=>{xe(()=>{n?M(n)(J):e&&e(J)},w)};t=J=>{we(J,B,I,H,x)};var C=(J,We)=>{ye(J,We.response,Va=>{xe(()=>{l?M(l)(Va):b&&b(Va)},w)},Va=>{xe(()=>{l?M(l)(Va):b&&b(Va)},w)})},V=J=>{we(J,C,I,H,x)};if("EM_IDB_STORE"===h)h=D()[f+84>>2],ye(a,y().slice(h,h+D()[f+88>>2]),B,I);else if("EM_IDB_DELETE"===h)Ae(a,B,I);else if(u){if(k)return 0;we(a,v?C:B,I,H,x)}else ze(a,B,k?I:v?V:
t);return a},ma:function(){throw"unwind";},fa:Ee,ga:Fe,u:function(a){Kb(a)},w:Ge,E:He,O:Ie,v:Je,i:function(){return Da},za:function(){var a=self.navigator.userAgent,b=Ma(a)+1,c=Wa(b);La(a,c,b);return c},V:Ke,Q:Te,A:Ue,R:Ve,T:Xe,a:q||E.wasmMemory,g:function(a){Da=a},K:Oe,W:function(a,b,c,d){return Oe(a,b,c,d)}};
(function(){function a(e,f){E.asm=e.exports;N.fc.push(E.asm.Ja);$a=E.asm.Pa;bb.unshift(E.asm.Fa);Ga=f;G||qb("wasm-instantiate")}function b(e){a(e.instance,e.module)}function c(e){return ub().then(function(f){return WebAssembly.instantiate(f,d)}).then(function(f){return f}).then(e,function(f){F("failed to asynchronously prepare wasm: "+f);Fa(f)})}var d={a:Ye};G||pb("wasm-instantiate");if(E.instantiateWasm)try{return E.instantiateWasm(d,a)}catch(e){return F("Module.instantiateWasm callback failed with error: "+
e),!1}(function(){return Ea||"function"!=typeof WebAssembly.instantiateStreaming||rb()||"function"!=typeof fetch?c(b):fetch(sb,{credentials:"same-origin"}).then(function(e){return WebAssembly.instantiateStreaming(e,d).then(b,function(f){F("wasm streaming compile failed: "+f);F("falling back to ArrayBuffer instantiation");return c(b)})})})().catch(ma);return{}})();E.___wasm_call_ctors=function(){return(E.___wasm_call_ctors=E.asm.Fa).apply(null,arguments)};
var Td=E._free=function(){return(Td=E._free=E.asm.Ga).apply(null,arguments)},Wa=E._malloc=function(){return(Wa=E._malloc=E.asm.Ha).apply(null,arguments)},Gb=E._pthread_self=function(){return(Gb=E._pthread_self=E.asm.Ia).apply(null,arguments)};E._emscripten_tls_init=function(){return(E._emscripten_tls_init=E.asm.Ja).apply(null,arguments)};
var ec=E._emscripten_builtin_memalign=function(){return(ec=E._emscripten_builtin_memalign=E.asm.Ka).apply(null,arguments)},Sd=E.___getTypeName=function(){return(Sd=E.___getTypeName=E.asm.La).apply(null,arguments)};E.___embind_register_native_and_builtin_types=function(){return(E.___embind_register_native_and_builtin_types=E.asm.Ma).apply(null,arguments)};var Se=E.__emscripten_thread_init=function(){return(Se=E.__emscripten_thread_init=E.asm.Na).apply(null,arguments)};
E.__emscripten_thread_crashed=function(){return(E.__emscripten_thread_crashed=E.asm.Oa).apply(null,arguments)};var Hb=E._emscripten_proxy_execute_queue=function(){return(Hb=E._emscripten_proxy_execute_queue=E.asm.Qa).apply(null,arguments)},re=E._emscripten_run_in_main_runtime_thread_js=function(){return(re=E._emscripten_run_in_main_runtime_thread_js=E.asm.Ra).apply(null,arguments)},Eb=E.__emscripten_thread_free_data=function(){return(Eb=E.__emscripten_thread_free_data=E.asm.Sa).apply(null,arguments)};
E.__emscripten_thread_exit=function(){return(E.__emscripten_thread_exit=E.asm.Ta).apply(null,arguments)};
var Ze=E._setThrew=function(){return(Ze=E._setThrew=E.asm.Ua).apply(null,arguments)},Ib=E._emscripten_stack_set_limits=function(){return(Ib=E._emscripten_stack_set_limits=E.asm.Va).apply(null,arguments)},yb=E.stackSave=function(){return(yb=E.stackSave=E.asm.Wa).apply(null,arguments)},zb=E.stackRestore=function(){return(zb=E.stackRestore=E.asm.Xa).apply(null,arguments)},qe=E.stackAlloc=function(){return(qe=E.stackAlloc=E.asm.Ya).apply(null,arguments)};
E.dynCall_ji=function(){return(E.dynCall_ji=E.asm.Za).apply(null,arguments)};E.dynCall_jiji=function(){return(E.dynCall_jiji=E.asm._a).apply(null,arguments)};E.dynCall_viijii=function(){return(E.dynCall_viijii=E.asm.$a).apply(null,arguments)};E.dynCall_iiiiij=function(){return(E.dynCall_iiiiij=E.asm.ab).apply(null,arguments)};E.dynCall_iiiiijj=function(){return(E.dynCall_iiiiijj=E.asm.bb).apply(null,arguments)};E.dynCall_iiiiiijj=function(){return(E.dynCall_iiiiiijj=E.asm.cb).apply(null,arguments)};
var Fb=E.__emscripten_allow_main_runtime_queued_calls=384996;function Ue(a,b){var c=yb();try{M(a)(b)}catch(d){zb(c);if(d!==d+0)throw d;Ze(1,0)}}function Xe(a,b,c,d){var e=yb();try{M(a)(b,c,d)}catch(f){zb(e);if(f!==f+0)throw f;Ze(1,0)}}function Ve(a,b,c){var d=yb();try{M(a)(b,c)}catch(e){zb(d);if(e!==e+0)throw e;Ze(1,0)}}function Te(a,b,c,d){var e=yb();try{return M(a)(b,c,d)}catch(f){zb(e);if(f!==f+0)throw f;Ze(1,0)}}E.addRunDependency=pb;E.removeRunDependency=qb;E.FS_createPath=Ic;
E.FS_createDataFile=Kc;E.FS_createPreloadedFile=Oc;E.FS_createLazyFile=Mc;E.FS_createDevice=gb;E.FS_unlink=zc;E.keepRuntimeAlive=function(){return noExitRuntime};E.PThread=N;E.PThread=N;E.wasmMemory=q;E.ExitStatus=Db;var $e;function Db(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}ob=function af(){$e||bf();$e||(ob=af)};
function bf(){function a(){if(!$e&&($e=!0,E.calledRun=!0,!Ha)){db();la(E);if(E.onRuntimeInitialized)E.onRuntimeInitialized();if(!G){if(E.postRun)for("function"==typeof E.postRun&&(E.postRun=[E.postRun]);E.postRun.length;){var b=E.postRun.shift();cb.unshift(b)}kb(cb)}}}if(!(0<mb))if(G)la(E),db(),postMessage({cmd:"loaded"});else{if(E.preRun)for("function"==typeof E.preRun&&(E.preRun=[E.preRun]);E.preRun.length;)lb();kb(ab);0<mb||(E.setStatus?(E.setStatus("Running..."),setTimeout(function(){setTimeout(function(){E.setStatus("")},
1);a()},1)):a())}}E.run=bf;function Kb(a){if(G)throw Jb(a),"unwind";if(!noExitRuntime){N.Ld();if(E.onExit)E.onExit(a);Ha=!0}sa(a,new Db(a))}if(E.preInit)for("function"==typeof E.preInit&&(E.preInit=[E.preInit]);0<E.preInit.length;)E.preInit.pop()();bf();


  return BlinkIDWasmSDK.ready
}
);
})();
if (typeof exports === 'object' && typeof module === 'object')
  module.exports = BlinkIDWasmSDK;
else if (typeof define === 'function' && define['amd'])
  define([], function() { return BlinkIDWasmSDK; });
else if (typeof exports === 'object')
  exports["BlinkIDWasmSDK"] = BlinkIDWasmSDK;
