
var BlinkIDWasmSDK = (() => {
  var _scriptDir = typeof document !== 'undefined' && document.currentScript ? document.currentScript.src : undefined;
  
  return (
function(BlinkIDWasmSDK) {
  BlinkIDWasmSDK = BlinkIDWasmSDK || {};


function g(){q.buffer!=t&&aa(q.buffer);return ba}function y(){q.buffer!=t&&aa(q.buffer);return ca}function da(){q.buffer!=t&&aa(q.buffer);return ea}function z(){q.buffer!=t&&aa(q.buffer);return fa}function B(){q.buffer!=t&&aa(q.buffer);return ha}function D(){q.buffer!=t&&aa(q.buffer);return ia}function ja(){q.buffer!=t&&aa(q.buffer);return ka}var E;E||(E=typeof BlinkIDWasmSDK !== 'undefined' ? BlinkIDWasmSDK : {});var la,ma;E.ready=new Promise(function(a,b){la=a;ma=b});E.kc||(E.kc=0);E.kc++;
E.ENVIRONMENT_IS_PTHREAD||function(a){function b(l,r,n){var p=new XMLHttpRequest;p.open("GET",l,!0);p.responseType="arraybuffer";p.onprogress=function(v){var k=r;v.total&&(k=v.total);if(v.loaded){p.Tc?E.Hb[l].loaded=v.loaded:(p.Tc=!0,E.Hb||(E.Hb={}),E.Hb[l]={loaded:v.loaded,total:k});var u=k=v=0,w;for(w in E.Hb){var A=E.Hb[w];v+=A.total;k+=A.loaded;u++}v=Math.ceil(v*E.kc/u);E.setStatus&&E.setStatus("Downloading data... ("+k+"/"+v+")")}else!E.Hb&&E.setStatus&&E.setStatus("Downloading data...")};p.onerror=
function(){throw Error("NetworkError for: "+l);};p.onload=function(){if(200==p.status||304==p.status||206==p.status||0==p.status&&p.response)n(p.response);else throw Error(p.statusText+" : "+p.responseURL);};p.send(null)}function c(l){console.error("package error:",l)}function d(){function l(v,k,u){this.start=v;this.end=k;this.audio=u}function r(v){if(!v)throw"Loading data file failed."+Error().stack;if(!(v instanceof ArrayBuffer))throw"bad input to processPackageData"+Error().stack;v=new Uint8Array(v);
l.prototype.Zc=v;v=a.files;for(var k=0;k<v.length;++k)l.prototype.vc[v[k].filename].onload();E.removeRunDependency("datafile_/opt/jenkins/jenkinsData/E3/core-webassembly-sdks/SDKs/BlinkID/resources-lightweight/advanced-threads/BlinkIDWasmSDK.data")}E.FS_createPath("/","microblink",!0,!0);l.prototype={vc:{},open:function(v,k){this.name=k;this.vc[k]=this;E.addRunDependency("fp "+this.name)},send:function(){},onload:function(){this.finish(this.Zc.subarray(this.start,this.end))},finish:function(v){E.FS_createDataFile(this.name,
null,v,!0,!0,!0);E.removeRunDependency("fp "+this.name);this.vc[this.name]=null}};for(var n=a.files,p=0;p<n.length;++p)(new l(n[p].start,n[p].end,n[p].audio||0)).open("GET",n[p].filename);E.addRunDependency("datafile_/opt/jenkins/jenkinsData/E3/core-webassembly-sdks/SDKs/BlinkID/resources-lightweight/advanced-threads/BlinkIDWasmSDK.data");E.Jc||(E.Jc={});E.Jc["/opt/jenkins/jenkinsData/E3/core-webassembly-sdks/SDKs/BlinkID/resources-lightweight/advanced-threads/BlinkIDWasmSDK.data"]={Vd:!1};m?(r(m),
m=null):h=r}"object"===typeof window?window.encodeURIComponent(window.location.pathname.toString().substring(0,window.location.pathname.toString().lastIndexOf("/"))+"/"):"undefined"===typeof process&&"undefined"!==typeof location&&encodeURIComponent(location.pathname.toString().substring(0,location.pathname.toString().lastIndexOf("/"))+"/");"function"!==typeof E.locateFilePackage||E.locateFile||(E.locateFile=E.locateFilePackage,F("warning: you defined Module.locateFilePackage, that has been renamed to Module.locateFile (using your locateFilePackage for now)"));
var e=E.locateFile?E.locateFile("BlinkIDWasmSDK.data",""):"BlinkIDWasmSDK.data",f=a.remote_package_size,h=null,m=E.getPreloadedPackage?E.getPreloadedPackage(e,f):null;m||b(e,f,function(l){h?(h(l),h=null):m=l},c);E.calledRun?d():(E.preRun||(E.preRun=[]),E.preRun.push(d))}({files:[{filename:"/microblink/Model_ed586fd6ca47c8eebb513c4ffaaacc2c54e92162b145062d7022519fba0911de.strop",start:0,end:713232},{filename:"/microblink/Model_e4f1f62f68ec44b71ecad3fb3f3b48fe3790beb5ab325611e17d63af06e9f644.strop",
start:713232,end:769746},{filename:"/microblink/Model_250e3cb8bb8603d4798b31c1fb8be2ca1f79b1c969eded62e916932dad3ff3f1.strop",start:769746,end:1485780},{filename:"/microblink/Model_36d8e94f4cb46097bd6b7385f2aa91fcdee1a5fefeec59e56d1b9e82c94b00a7.strop",start:1485780,end:1855608},{filename:"/microblink/face_detector_model.zzip",start:1855608,end:1952466},{filename:"/microblink/Model_81920c94b1bec5cdde53fcf13dfbcfbf7ddeb711c202ecd7a02f7baa974f216e.strop",start:1952466,end:2530964},{filename:"/microblink/Model_faf688599c7e261a2a7404730f69ed029115bb0d3e7a3657731d88e701720efe.strop",
start:2530964,end:2547702},{filename:"/microblink/ccc_lookup_table.zzip",start:2547702,end:2568171},{filename:"/microblink/Model_2880751121560047e6dc571bc8ff4683aeb863886f7c0789234594ceb1e23577.strop",start:2568171,end:2572109},{filename:"/microblink/Model_9de7d469718644b95e36b2d4456f3c8360e4d04575ca172aa0062bbb1edd4141.strop",start:2572109,end:4995241},{filename:"/microblink/Model_473ac5f5e256623c0a6b282698c1f1b033b9fb5359e6aa142e9fb4a4022afe4e.strop",start:4995241,end:5002123},{filename:"/microblink/Model_b452fd3cd4037080cfcb4c423dba5bc58c8ceafc28427fdf9c5778fb353f088e.strop",
start:5002123,end:5008973},{filename:"/microblink/Model_19d332fd742e2cc1f4d925a61caceb93ee3b225b3bad0c3966df7d1e3c9f6e0b.strop",start:5008973,end:5439015}],remote_package_size:5439015,package_uuid:"7554a9dd-4a79-48a4-9392-578044a0e6ce"});E.onAbort=function(a){F("Aborted with message: "+a);F("Stacktrace: "+na())};var crypto={getRandomValues:function(a){for(var b=0;b<a.length;b++)a[b]=256*Math.random()|0}},oa;oa=E.allowedThreads&&0<E.allowedThreads?E.allowedThreads-1:navigator.hardwareConcurrency-1;
var pa=0,qa;0<oa&&(E.threadWorkersReadyPromise=new Promise(function(a){qa=a}));E.preRun||(E.preRun=[]);E.preRun.push(function(a){function b(){pa++;pa==oa&&qa()}var c=a.PThread.pc;a.PThread.pc=function(d){c(d,b)}});var ra=Object.assign({},E),sa="./this.program",ta=(a,b)=>{throw b;},ua="object"==typeof window,va="function"==typeof importScripts,wa="object"==typeof process&&"object"==typeof process.Td&&"string"==typeof process.Td.node,G=E.ENVIRONMENT_IS_PTHREAD||!1,xa="";
function ya(a){return E.locateFile?E.locateFile(a,xa):xa+a}var za,Aa,Ba;
if(ua||va)va?xa=self.location.href:"undefined"!=typeof document&&document.currentScript&&(xa=document.currentScript.src),_scriptDir&&(xa=_scriptDir),xa=0!==xa.indexOf("blob:")?xa.substr(0,xa.replace(/[?#].*/,"").lastIndexOf("/")+1):"",za=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},va&&(Ba=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),Aa=(a,b,c)=>{var d=new XMLHttpRequest;d.open("GET",
a,!0);d.responseType="arraybuffer";d.onload=()=>{200==d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)};var Ca=E.print||console.log.bind(console),F=E.printErr||console.warn.bind(console);Object.assign(E,ra);ra=null;E.thisProgram&&(sa=E.thisProgram);E.quit&&(ta=E.quit);var Da,Ea=0,Fa;E.wasmBinary&&(Fa=E.wasmBinary);var noExitRuntime=E.noExitRuntime||!0;"object"!=typeof WebAssembly&&Ga("no native wasm support detected");
var q,Ha,Ia=!1,Ja="undefined"!=typeof TextDecoder?new TextDecoder("utf8"):void 0;
function Ka(a,b,c){var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.buffer&&Ja)return Ja.decode(a.buffer instanceof SharedArrayBuffer?a.slice(b,c):a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var f=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|f);else{var h=a[b++]&63;e=224==(e&240)?(e&15)<<12|f<<6|h:(e&7)<<18|f<<12|h<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d}
function K(a,b){return a?Ka(y(),a,b):""}function La(a,b,c,d){if(!(0<d))return 0;var e=c;d=c+d-1;for(var f=0;f<a.length;++f){var h=a.charCodeAt(f);if(55296<=h&&57343>=h){var m=a.charCodeAt(++f);h=65536+((h&1023)<<10)|m&1023}if(127>=h){if(c>=d)break;b[c++]=h}else{if(2047>=h){if(c+1>=d)break;b[c++]=192|h>>6}else{if(65535>=h){if(c+2>=d)break;b[c++]=224|h>>12}else{if(c+3>=d)break;b[c++]=240|h>>18;b[c++]=128|h>>12&63}b[c++]=128|h>>6&63}b[c++]=128|h&63}}b[c]=0;return c-e}
function Ma(a,b,c){La(a,y(),b,c)}function Na(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:b+4}return b}var Oa="undefined"!=typeof TextDecoder?new TextDecoder("utf-16le"):void 0;
function Pa(a,b){var c=a>>1;for(var d=c+b/2;!(c>=d)&&z()[c];)++c;c<<=1;if(32<c-a&&Oa)return Oa.decode(y().slice(a,c));c="";for(d=0;!(d>=b/2);++d){var e=da()[a+2*d>>1];if(0==e)break;c+=String.fromCharCode(e)}return c}function Qa(a,b,c){void 0===c&&(c=2147483647);if(2>c)return 0;c-=2;var d=b;c=c<2*a.length?c/2:a.length;for(var e=0;e<c;++e){var f=a.charCodeAt(e);da()[b>>1]=f;b+=2}da()[b>>1]=0;return b-d}function Ra(a){return 2*a.length}
function Sa(a,b){for(var c=0,d="";!(c>=b/4);){var e=B()[a+4*c>>2];if(0==e)break;++c;65536<=e?(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023)):d+=String.fromCharCode(e)}return d}function Ta(a,b,c){void 0===c&&(c=2147483647);if(4>c)return 0;var d=b;c=d+c-4;for(var e=0;e<a.length;++e){var f=a.charCodeAt(e);if(55296<=f&&57343>=f){var h=a.charCodeAt(++e);f=65536+((f&1023)<<10)|h&1023}B()[b>>2]=f;b+=4;if(b+4>c)break}B()[b>>2]=0;return b-d}
function Ua(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&++c;b+=4}return b}function Wa(a){var b=Na(a)+1,c=Xa(b);c&&La(a,g(),c,b);return c}function Ya(a,b){g().set(a,b)}var t,ba,ca,ea,fa,ha,ia,Za,ka;G&&(t=E.buffer);
function aa(a){t=a;E.HEAP8=ba=new Int8Array(a);E.HEAP16=ea=new Int16Array(a);E.HEAP32=ha=new Int32Array(a);E.HEAPU8=ca=new Uint8Array(a);E.HEAPU16=fa=new Uint16Array(a);E.HEAPU32=ia=new Uint32Array(a);E.HEAPF32=Za=new Float32Array(a);E.HEAPF64=ka=new Float64Array(a)}var $a=E.INITIAL_MEMORY||209715200;
if(G)q=E.wasmMemory,t=E.buffer;else if(E.wasmMemory)q=E.wasmMemory;else if(q=new WebAssembly.Memory({initial:$a/65536,maximum:12800,shared:!0}),!(q.buffer instanceof SharedArrayBuffer))throw F("requested a shared WebAssembly.Memory but the returned buffer is not a SharedArrayBuffer, indicating that while the browser has SharedArrayBuffer it does not have WebAssembly threads support - you may need to set a flag"),wa&&console.log("(on node you may need: --experimental-wasm-threads --experimental-wasm-bulk-memory and also use a recent version)"),
Error("bad memory");q&&(t=q.buffer);$a=t.byteLength;aa(t);var ab,bb=[],cb=[],db=[];function eb(){G||(E.noFSInit||fb||(fb=!0,gb(),E.stdin=E.stdin,E.stdout=E.stdout,E.stderr=E.stderr,E.stdin?hb("/dev","stdin",E.stdin):ib("/dev/tty","/dev/stdin"),E.stdout?hb("/dev","stdout",null,E.stdout):ib("/dev/tty","/dev/stdout"),E.stderr?hb("/dev","stderr",null,E.stderr):ib("/dev/tty1","/dev/stderr"),jb("/dev/stdin",0),jb("/dev/stdout",1),jb("/dev/stderr",1)),kb=!1,lb(cb))}
function mb(){var a=E.preRun.shift();bb.unshift(a)}var nb=0,ob=null,pb=null;function qb(){nb++;E.monitorRunDependencies&&E.monitorRunDependencies(nb)}function rb(){nb--;E.monitorRunDependencies&&E.monitorRunDependencies(nb);if(0==nb&&(null!==ob&&(clearInterval(ob),ob=null),pb)){var a=pb;pb=null;a()}}E.preloadedImages={};E.preloadedAudios={};
function Ga(a){if(G)postMessage({cmd:"onAbort",arg:a});else if(E.onAbort)E.onAbort(a);a="Aborted("+a+")";F(a);Ia=!0;a=new WebAssembly.RuntimeError(a+". Build with -s ASSERTIONS=1 for more info.");ma(a);throw a;}function sb(){return tb.startsWith("data:application/octet-stream;base64,")}var tb;tb="BlinkIDWasmSDK.wasm";sb()||(tb=ya(tb));function ub(){var a=tb;try{if(a==tb&&Fa)return new Uint8Array(Fa);if(Ba)return Ba(a);throw"both async and sync fetching of the wasm failed";}catch(b){Ga(b)}}
function vb(){return Fa||!ua&&!va||"function"!=typeof fetch?Promise.resolve().then(function(){return ub()}):fetch(tb,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+tb+"'";return a.arrayBuffer()}).catch(function(){return ub()})}
var L,wb,xb={469647:function(a){a=K(a);throw Error("Failed to reconfigure RecognizerRunner due to following error: "+a);},469783:function(a,b,c,d){a=K(a);b=K(b);c=K(c);d=K(d);throw Error(a+b+c+d);},469999:function(a,b){a=K(a);b=K(b);throw Error(a+b);},470109:function(a,b){a=K(a);b=K(b);console.log(a+b)},470207:function(a){throw Error(K(a));},470250:function(){throw Error("Unable to perform that operation while recognizer is in use!");},470333:function(){throw Error("Unable to perform that operation while recognizer is in use!");
},470416:function(){throw Error("Unable to perform that operation while recognizer is in use!");}};function lb(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b(E);else{var c=b.Wd;"number"==typeof c?void 0===b.Nb?M(c)():M(c)(b.Nb):c(void 0===b.Nb?null:b.Nb)}}}function yb(a){var b=zb();a=a();Ab(b);return a}function Bb(a){return a.replace(/\b_Z[\w\d_]+/g,function(b){return b===b?b:b+" ["+b+"]"})}function Cb(a){var b=N.xb[a];b&&(B()[a>>2]=0,N.Oc(b.worker))}
function Db(a){var b=N.jd();if(!b)return 6;N.Ub.push(b);var c=N.xb[a.qc]={worker:b,wc:a.qc};b.Mb=c;var d={cmd:"run",start_routine:a.Ld,arg:a.Nb,threadInfoStruct:a.qc};b.Tb=()=>{d.time=performance.now();b.postMessage(d,a.Rd)};b.loaded&&(b.Tb(),delete b.Tb);return 0}function Eb(a){a instanceof Fb||"unwind"==a||ta(1,a)}
var N={Cb:[],Ub:[],fc:[],pd:function(){G&&N.qd()},Zd:function(){},qd:function(){N.receiveObjectTransfer=N.Bd;N.threadInit=N.Qc;N.setExitStatus=N.Gd;noExitRuntime=!1},xb:{},Gd:function(){},Md:function(){for(var a in N.xb){var b=N.xb[a];b&&b.worker&&N.Oc(b.worker)}for(a=0;a<N.Cb.length;++a)N.Cb[a].terminate();N.Cb=[]},Oc:function(a){N.Dd(function(){delete N.xb[a.Mb.wc];N.Cb.push(a);N.Ub.splice(N.Ub.indexOf(a),1);Gb(a.Mb.wc);a.Mb=void 0})},Dd:function(a){B()[Hb>>2]=0;try{a()}finally{B()[Hb>>2]=1}},Bd:function(){},
Qc:function(){for(var a in N.fc)if(N.fc.hasOwnProperty(a))N.fc[a]()},pc:function(a,b){a.onmessage=c=>{c=c.data;var d=c.cmd;a.Mb&&(N.cd=a.Mb.wc);if(c.targetThread&&c.targetThread!=Ib()){var e=N.xb[c.be];e?e.worker.postMessage(c,c.transferList):F('Internal error! Worker sent a message "'+d+'" to target pthread '+c.targetThread+", but that thread no longer exists!")}else if("processProxyingQueue"===d)Jb(c.queue),Atomics.sub(B(),c.queue>>2,1);else if("spawnThread"===d)Db(c);else if("cleanupThread"===
d)Cb(c.thread);else if("killThread"===d)c=c.thread,B()[c>>2]=0,d=N.xb[c],delete N.xb[c],d.worker.terminate(),Gb(c),N.Ub.splice(N.Ub.indexOf(d.worker),1),d.worker.Mb=void 0;else if("cancelThread"===d)N.xb[c.thread].worker.postMessage({cmd:"cancel"});else if("loaded"===d)a.loaded=!0,b&&b(a),a.Tb&&(a.Tb(),delete a.Tb);else if("print"===d)Ca("Thread "+c.threadId+": "+c.text);else if("printErr"===d)F("Thread "+c.threadId+": "+c.text);else if("alert"===d)alert("Thread "+c.threadId+": "+c.text);else if("setimmediate"===
c.target)a.postMessage(c);else if("onAbort"===d){if(E.onAbort)E.onAbort(c.arg)}else d&&F("worker sent an unknown command "+d);N.cd=void 0};a.onerror=c=>{F("worker sent an error! "+c.filename+":"+c.lineno+": "+c.message);throw c;};a.postMessage({cmd:"load",urlOrBlob:E.mainScriptUrlOrBlob||_scriptDir,wasmMemory:q,wasmModule:Ha})},Uc:function(){var a=ya("BlinkIDWasmSDK.worker.js");N.Cb.push(new Worker(a))},jd:function(){0==N.Cb.length&&(N.Uc(),N.pc(N.Cb[0]));return N.Cb.pop()}};
E.establishStackSpace=function(){var a=Ib(),b=B()[a+44>>2];a=B()[a+48>>2];Kb(b,b-a);Ab(b)};function Lb(a){if(G)return O(1,0,a);try{Mb(a)}catch(b){Eb(b)}}var Nb=[];function M(a){var b=Nb[a];b||(a>=Nb.length&&(Nb.length=a+1),Nb[a]=b=ab.get(a));return b}E.invokeEntryPoint=function(a,b){return M(a)(b)};
function na(){a:{var a=Error();if(!a.stack){try{throw Error();}catch(b){a=b}if(!a.stack){a="(no stack trace available)";break a}}a=a.stack.toString()}E.extraStackTrace&&(a+="\n"+E.extraStackTrace());return Bb(a)}function Ob(a,b,c,d){return G?O(2,1,a,b,c,d):Pb(a,b,c,d)}
function Pb(a,b,c,d){if("undefined"==typeof SharedArrayBuffer)return F("Current environment does not support SharedArrayBuffer, pthreads are not available!"),6;var e=[];if(G&&0===e.length)return Ob(a,b,c,d);a={Ld:c,qc:a,Nb:d,Rd:e};return G?(a.Ud="spawnThread",postMessage(a,e),0):Db(a)}function Qb(a,b){for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a}
function Rb(a){var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=Qb(a.split("/").filter(function(d){return!!d}),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a}function Sb(a){var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,b.length-1));return a+b}function Tb(a){if("/"===a)return"/";a=Rb(a);a=a.replace(/\/$/,"");var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)}
function Ub(){if("object"==typeof crypto&&"function"==typeof crypto.getRandomValues){var a=new Uint8Array(1);return function(){crypto.getRandomValues(a);return a[0]}}return function(){Ga("randomDevice")}}
function Vb(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:"/";if("string"!=typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=Qb(a.split("/").filter(function(d){return!!d}),!b).join("/");return(b?"/":"")+a||"."}var Wb=[];function Xb(a,b){Wb[a]={input:[],ob:[],Lb:b};Yb(a,Zb)}
var Zb={open:function(a){var b=Wb[a.node.Rb];if(!b)throw new P(43);a.mb=b;a.seekable=!1},close:function(a){a.mb.Lb.flush(a.mb)},flush:function(a){a.mb.Lb.flush(a.mb)},read:function(a,b,c,d){if(!a.mb||!a.mb.Lb.Gc)throw new P(60);for(var e=0,f=0;f<d;f++){try{var h=a.mb.Lb.Gc(a.mb)}catch(m){throw new P(29);}if(void 0===h&&0===e)throw new P(6);if(null===h||void 0===h)break;e++;b[c+f]=h}e&&(a.node.timestamp=Date.now());return e},write:function(a,b,c,d){if(!a.mb||!a.mb.Lb.rc)throw new P(60);try{for(var e=
0;e<d;e++)a.mb.Lb.rc(a.mb,b[c+e])}catch(f){throw new P(29);}d&&(a.node.timestamp=Date.now());return e}},ac={Gc:function(a){if(!a.input.length){var b=null;"undefined"!=typeof window&&"function"==typeof window.prompt?(b=window.prompt("Input: "),null!==b&&(b+="\n")):"function"==typeof readline&&(b=readline(),null!==b&&(b+="\n"));if(!b)return null;a.input=$b(b,!0)}return a.input.shift()},rc:function(a,b){null===b||10===b?(Ca(Ka(a.ob,0)),a.ob=[]):0!=b&&a.ob.push(b)},flush:function(a){a.ob&&0<a.ob.length&&
(Ca(Ka(a.ob,0)),a.ob=[])}},bc={rc:function(a,b){null===b||10===b?(F(Ka(a.ob,0)),a.ob=[]):0!=b&&a.ob.push(b)},flush:function(a){a.ob&&0<a.ob.length&&(F(Ka(a.ob,0)),a.ob=[])}},Q={wb:null,zb:function(){return Q.createNode(null,"/",16895,0)},createNode:function(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new P(63);Q.wb||(Q.wb={dir:{node:{vb:Q.gb.vb,rb:Q.gb.rb,Ob:Q.gb.Ob,bc:Q.gb.bc,Nc:Q.gb.Nc,jc:Q.gb.jc,Pc:Q.gb.Pc,Mc:Q.gb.Mc,ec:Q.gb.ec},stream:{Eb:Q.hb.Eb}},file:{node:{vb:Q.gb.vb,rb:Q.gb.rb},
stream:{Eb:Q.hb.Eb,read:Q.hb.read,write:Q.hb.write,yc:Q.hb.yc,cc:Q.hb.cc,dc:Q.hb.dc}},link:{node:{vb:Q.gb.vb,rb:Q.gb.rb,Sb:Q.gb.Sb},stream:{}},Ac:{node:{vb:Q.gb.vb,rb:Q.gb.rb},stream:cc}});c=dc(a,b,c,d);16384===(c.mode&61440)?(c.gb=Q.wb.dir.node,c.hb=Q.wb.dir.stream,c.fb={}):32768===(c.mode&61440)?(c.gb=Q.wb.file.node,c.hb=Q.wb.file.stream,c.kb=0,c.fb=null):40960===(c.mode&61440)?(c.gb=Q.wb.link.node,c.hb=Q.wb.link.stream):8192===(c.mode&61440)&&(c.gb=Q.wb.Ac.node,c.hb=Q.wb.Ac.stream);c.timestamp=
Date.now();a&&(a.fb[b]=c,a.timestamp=c.timestamp);return c},Xd:function(a){return a.fb?a.fb.subarray?a.fb.subarray(0,a.kb):new Uint8Array(a.fb):new Uint8Array(0)},Dc:function(a,b){var c=a.fb?a.fb.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)>>>0),0!=c&&(b=Math.max(b,256)),c=a.fb,a.fb=new Uint8Array(b),0<a.kb&&a.fb.set(c.subarray(0,a.kb),0))},Cd:function(a,b){if(a.kb!=b)if(0==b)a.fb=null,a.kb=0;else{var c=a.fb;a.fb=new Uint8Array(b);c&&a.fb.set(c.subarray(0,Math.min(b,a.kb)));a.kb=b}},gb:{vb:function(a){var b=
{};b.ed=8192===(a.mode&61440)?a.id:1;b.mc=a.id;b.mode=a.mode;b.xd=1;b.uid=0;b.nd=0;b.Rb=a.Rb;b.size=16384===(a.mode&61440)?4096:32768===(a.mode&61440)?a.kb:40960===(a.mode&61440)?a.link.length:0;b.Wc=new Date(a.timestamp);b.wd=new Date(a.timestamp);b.bd=new Date(a.timestamp);b.Xc=4096;b.Yc=Math.ceil(b.size/b.Xc);return b},rb:function(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);void 0!==b.size&&Q.Cd(a,b.size)},Ob:function(){throw ec[44];},bc:function(a,b,c,
d){return Q.createNode(a,b,c,d)},Nc:function(a,b,c){if(16384===(a.mode&61440)){try{var d=fc(b,c)}catch(f){}if(d)for(var e in d.fb)throw new P(55);}delete a.parent.fb[a.name];a.parent.timestamp=Date.now();a.name=c;b.fb[c]=a;b.timestamp=a.parent.timestamp;a.parent=b},jc:function(a,b){delete a.fb[b];a.timestamp=Date.now()},Pc:function(a,b){var c=fc(a,b),d;for(d in c.fb)throw new P(55);delete a.fb[b];a.timestamp=Date.now()},Mc:function(a){var b=[".",".."],c;for(c in a.fb)a.fb.hasOwnProperty(c)&&b.push(c);
return b},ec:function(a,b,c){a=Q.createNode(a,b,41471,0);a.link=c;return a},Sb:function(a){if(40960!==(a.mode&61440))throw new P(28);return a.link}},hb:{read:function(a,b,c,d,e){var f=a.node.fb;if(e>=a.node.kb)return 0;a=Math.min(a.node.kb-e,d);if(8<a&&f.subarray)b.set(f.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=f[e+d];return a},write:function(a,b,c,d,e,f){b.buffer===g().buffer&&(f=!1);if(!d)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&(!a.fb||a.fb.subarray)){if(f)return a.fb=b.subarray(c,
c+d),a.kb=d;if(0===a.kb&&0===e)return a.fb=b.slice(c,c+d),a.kb=d;if(e+d<=a.kb)return a.fb.set(b.subarray(c,c+d),e),d}Q.Dc(a,e+d);if(a.fb.subarray&&b.subarray)a.fb.set(b.subarray(c,c+d),e);else for(f=0;f<d;f++)a.fb[e+f]=b[c+f];a.kb=Math.max(a.kb,e+d);return d},Eb:function(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.kb);if(0>b)throw new P(28);return b},yc:function(a,b,c){Q.Dc(a.node,b+c);a.node.kb=Math.max(a.node.kb,b+c)},cc:function(a,b,c,d,e,f){if(0!==b)throw new P(28);
if(32768!==(a.node.mode&61440))throw new P(43);a=a.node.fb;if(f&2||a.buffer!==t){if(0<d||d+c<a.length)a=a.subarray?a.subarray(d,d+c):Array.prototype.slice.call(a,d,d+c);d=!0;f=65536*Math.ceil(c/65536);(c=gc(65536,f))?y().fill(0,c,c+f):c=0;if(!c)throw new P(48);g().set(a,c)}else d=!1,c=a.byteOffset;return{jb:c,Vc:d}},dc:function(a,b,c,d,e){if(32768!==(a.node.mode&61440))throw new P(43);if(e&2)return 0;Q.hb.write(a,b,0,d,c,!1);return 0}}};
function hc(a,b,c){var d="al "+a;Aa(a,function(e){e||Ga('Loading data file "'+a+'" failed (no arrayBuffer).');b(new Uint8Array(e));d&&rb(d)},function(){if(c)c();else throw'Loading data file "'+a+'" failed.';});d&&qb(d)}
var ic=null,jc={},kc=[],lc=1,mc=null,kb=!0,P=null,ec={},oc=(a,b={})=>{a=Vb("/",a);if(!a)return{path:"",node:null};b=Object.assign({Fc:!0,tc:0},b);if(8<b.tc)throw new P(32);a=Qb(a.split("/").filter(h=>!!h),!1);for(var c=ic,d="/",e=0;e<a.length;e++){var f=e===a.length-1;if(f&&b.parent)break;c=fc(c,a[e]);d=Rb(d+"/"+a[e]);c.Pb&&(!f||f&&b.Fc)&&(c=c.Pb.root);if(!f||b.Yb)for(f=0;40960===(c.mode&61440);)if(c=nc(d),d=Vb(Sb(d),c),c=oc(d,{tc:b.tc+1}).node,40<f++)throw new P(32);}return{path:d,node:c}},pc=a=>
{for(var b;;){if(a===a.parent)return a=a.zb.Ic,b?"/"!==a[a.length-1]?a+"/"+b:a+b:a;b=b?a.name+"/"+b:a.name;a=a.parent}},qc=(a,b)=>{for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%mc.length},fc=(a,b)=>{var c;if(c=(c=rc(a,"x"))?c:a.gb.Ob?0:2)throw new P(c,a);for(c=mc[qc(a.id,b)];c;c=c.Kb){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.gb.Ob(a,b)},dc=(a,b,c,d)=>{a=new sc(a,b,c,d);b=qc(a.parent.id,a.name);a.Kb=mc[b];return mc[b]=a},tc={r:0,"r+":2,w:577,"w+":578,
a:1089,"a+":1090},uc=a=>{var b=["r","w","rw"][a&3];a&512&&(b+="w");return b},rc=(a,b)=>{if(kb)return 0;if(!b.includes("r")||a.mode&292){if(b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73))return 2}else return 2;return 0},vc=(a,b)=>{try{return fc(a,b),20}catch(c){}return rc(a,"wx")},wc=(a=0,b=4096)=>{for(;a<=b;a++)if(!kc[a])return a;throw new P(33);},yc=(a,b)=>{xc||(xc=function(){},xc.prototype={object:{get:function(){return this.node},set:function(c){this.node=c}}});a=Object.assign(new xc,
a);b=wc(b,void 0);a.Bb=b;return kc[b]=a},cc={open:a=>{a.hb=jc[a.node.Rb].hb;a.hb.open&&a.hb.open(a)},Eb:()=>{throw new P(70);}},Yb=(a,b)=>{jc[a]={hb:b}},zc=(a,b)=>{var c="/"===b,d=!b;if(c&&ic)throw new P(10);if(!c&&!d){var e=oc(b,{Fc:!1});b=e.path;e=e.node;if(e.Pb)throw new P(10);if(16384!==(e.mode&61440))throw new P(54);}b={type:a,ae:{},Ic:b,vd:[]};a=a.zb(b);a.zb=b;b.root=a;c?ic=a:e&&(e.Pb=b,e.zb&&e.zb.vd.push(b))},R=(a,b,c)=>{var d=oc(a,{parent:!0}).node;a=Tb(a);if(!a||"."===a||".."===a)throw new P(28);
var e=vc(d,a);if(e)throw new P(e);if(!d.gb.bc)throw new P(63);return d.gb.bc(d,a,b,c)},Ac=(a,b,c)=>{"undefined"==typeof c&&(c=b,b=438);return R(a,b|8192,c)},ib=(a,b)=>{if(!Vb(a))throw new P(44);var c=oc(b,{parent:!0}).node;if(!c)throw new P(44);b=Tb(b);var d=vc(c,b);if(d)throw new P(d);if(!c.gb.ec)throw new P(63);c.gb.ec(c,b,a)},Bc=a=>{var b=oc(a,{parent:!0}).node;if(!b)throw new P(44);var c=Tb(a);a=fc(b,c);a:{try{var d=fc(b,c)}catch(f){d=f.nb;break a}var e=rc(b,"wx");d=e?e:16384===(d.mode&61440)?
31:0}if(d)throw new P(d);if(!b.gb.jc)throw new P(63);if(a.Pb)throw new P(10);b.gb.jc(b,c);b=qc(a.parent.id,a.name);if(mc[b]===a)mc[b]=a.Kb;else for(b=mc[b];b;){if(b.Kb===a){b.Kb=a.Kb;break}b=b.Kb}},nc=a=>{a=oc(a).node;if(!a)throw new P(44);if(!a.gb.Sb)throw new P(28);return Vb(pc(a.parent),a.gb.Sb(a))},Cc=(a,b)=>{a=oc(a,{Yb:!b}).node;if(!a)throw new P(44);if(!a.gb.vb)throw new P(63);return a.gb.vb(a)},Dc=a=>Cc(a,!0),Ec=(a,b)=>{a="string"==typeof a?oc(a,{Yb:!0}).node:a;if(!a.gb.rb)throw new P(63);
a.gb.rb(a,{mode:b&4095|a.mode&-4096,timestamp:Date.now()})},jb=(a,b,c,d)=>{if(""===a)throw new P(44);if("string"==typeof b){var e=tc[b];if("undefined"==typeof e)throw Error("Unknown file open mode: "+b);b=e}c=b&64?("undefined"==typeof c?438:c)&4095|32768:0;if("object"==typeof a)var f=a;else{a=Rb(a);try{f=oc(a,{Yb:!(b&131072)}).node}catch(h){}}e=!1;if(b&64)if(f){if(b&128)throw new P(20);}else f=R(a,c,0),e=!0;if(!f)throw new P(44);8192===(f.mode&61440)&&(b&=-513);if(b&65536&&16384!==(f.mode&61440))throw new P(54);
if(!e&&(c=f?40960===(f.mode&61440)?32:16384===(f.mode&61440)&&("r"!==uc(b)||b&512)?31:rc(f,uc(b)):44))throw new P(c);if(b&512){c=f;c="string"==typeof c?oc(c,{Yb:!0}).node:c;if(!c.gb.rb)throw new P(63);if(16384===(c.mode&61440))throw new P(31);if(32768!==(c.mode&61440))throw new P(28);if(e=rc(c,"w"))throw new P(e);c.gb.rb(c,{size:0,timestamp:Date.now()})}b&=-131713;d=yc({node:f,path:pc(f),flags:b,seekable:!0,position:0,hb:f.hb,Sd:[],error:!1},d);d.hb.open&&d.hb.open(d);!E.logReadFiles||b&1||(Fc||(Fc=
{}),a in Fc||(Fc[a]=1));return d},Gc=a=>{if(null===a.Bb)throw new P(8);a.lc&&(a.lc=null);try{a.hb.close&&a.hb.close(a)}catch(b){throw b;}finally{kc[a.Bb]=null}a.Bb=null},Hc=(a,b,c)=>{if(null===a.Bb)throw new P(8);if(!a.seekable||!a.hb.Eb)throw new P(70);if(0!=c&&1!=c&&2!=c)throw new P(28);a.position=a.hb.Eb(a,b,c);a.Sd=[]},Ic=(a,b,c,d,e,f)=>{if(0>d||0>e)throw new P(28);if(null===a.Bb)throw new P(8);if(0===(a.flags&2097155))throw new P(8);if(16384===(a.node.mode&61440))throw new P(31);if(!a.hb.write)throw new P(28);
a.seekable&&a.flags&1024&&Hc(a,0,2);var h="undefined"!=typeof e;if(!h)e=a.position;else if(!a.seekable)throw new P(70);b=a.hb.write(a,b,c,d,e,f);h||(a.position+=b);return b},gb=()=>{P||(P=function(a,b){this.node=b;this.Fd=function(c){this.nb=c};this.Fd(a);this.message="FS error"},P.prototype=Error(),P.prototype.constructor=P,[44].forEach(a=>{ec[a]=new P(a);ec[a].stack="<generic error, no stack>"}))},fb,Jc=(a,b)=>{var c=0;a&&(c|=365);b&&(c|=146);return c},Kc=(a,b)=>{a="string"==typeof a?a:pc(a);for(b=
b.split("/").reverse();b.length;){var c=b.pop();if(c){var d=Rb(a+"/"+c);try{R(d,16895,0)}catch(e){}a=d}}return d},Lc=(a,b,c,d)=>{a=Rb(("string"==typeof a?a:pc(a))+"/"+b);c=Jc(c,d);return R(a,(void 0!==c?c:438)&4095|32768,0)},Mc=(a,b,c,d,e,f)=>{var h=b;a&&(a="string"==typeof a?a:pc(a),h=b?Rb(a+"/"+b):a);a=Jc(d,e);h=R(h,(void 0!==a?a:438)&4095|32768,0);if(c){if("string"==typeof c){b=Array(c.length);d=0;for(e=c.length;d<e;++d)b[d]=c.charCodeAt(d);c=b}Ec(h,a|146);b=jb(h,577);Ic(b,c,0,c.length,0,f);Gc(b);
Ec(h,a)}return h},hb=(a,b,c,d)=>{a=Rb(("string"==typeof a?a:pc(a))+"/"+b);b=Jc(!!c,!!d);hb.Hc||(hb.Hc=64);var e=hb.Hc++<<8|0;Yb(e,{open:f=>{f.seekable=!1},close:()=>{d&&d.buffer&&d.buffer.length&&d(10)},read:(f,h,m,l)=>{for(var r=0,n=0;n<l;n++){try{var p=c()}catch(v){throw new P(29);}if(void 0===p&&0===r)throw new P(6);if(null===p||void 0===p)break;r++;h[m+n]=p}r&&(f.node.timestamp=Date.now());return r},write:(f,h,m,l)=>{for(var r=0;r<l;r++)try{d(h[m+r])}catch(n){throw new P(29);}l&&(f.node.timestamp=
Date.now());return r}});return Ac(a,b,e)},Nc=a=>{if(!(a.sd||a.td||a.link||a.fb)){if("undefined"!=typeof XMLHttpRequest)throw Error("Lazy loading should have been performed (contents set) in createLazyFile, but it was not. Lazy loading only works in web workers. Use --embed-file or --preload-file in emcc on the main thread.");if(za)try{a.fb=$b(za(a.url),!0),a.kb=a.fb.length}catch(b){throw new P(29);}else throw Error("Cannot load without read() or XMLHttpRequest.");}},Oc=(a,b,c,d,e)=>{function f(){this.oc=
!1;this.Xb=[]}f.prototype.get=function(n){if(!(n>this.length-1||0>n)){var p=n%this.Bc;return this.Zb(n/this.Bc|0)[p]}};f.prototype.Ed=function(n){this.Zb=n};f.prototype.zc=function(){var n=new XMLHttpRequest;n.open("HEAD",c,!1);n.send(null);if(!(200<=n.status&&300>n.status||304===n.status))throw Error("Couldn't load "+c+". Status: "+n.status);var p=Number(n.getResponseHeader("Content-length")),v,k=(v=n.getResponseHeader("Accept-Ranges"))&&"bytes"===v;n=(v=n.getResponseHeader("Content-Encoding"))&&
"gzip"===v;var u=1048576;k||(u=p);var w=this;w.Ed(A=>{var H=A*u,I=(A+1)*u-1;I=Math.min(I,p-1);if("undefined"==typeof w.Xb[A]){var x=w.Xb;if(H>I)throw Error("invalid range ("+H+", "+I+") or no bytes requested!");if(I>p-1)throw Error("only "+p+" bytes available! programmer error!");var C=new XMLHttpRequest;C.open("GET",c,!1);p!==u&&C.setRequestHeader("Range","bytes="+H+"-"+I);C.responseType="arraybuffer";C.overrideMimeType&&C.overrideMimeType("text/plain; charset=x-user-defined");C.send(null);if(!(200<=
C.status&&300>C.status||304===C.status))throw Error("Couldn't load "+c+". Status: "+C.status);H=void 0!==C.response?new Uint8Array(C.response||[]):$b(C.responseText||"",!0);x[A]=H}if("undefined"==typeof w.Xb[A])throw Error("doXHR failed!");return w.Xb[A]});if(n||!p)u=p=1,u=p=this.Zb(0).length,Ca("LazyFiles on gzip forces download of the whole file when length is accessed");this.Sc=p;this.Rc=u;this.oc=!0};if("undefined"!=typeof XMLHttpRequest){if(!va)throw"Cannot do synchronous binary XHRs outside webworkers in modern browsers. Use --embed-file or --preload-file in emcc";
var h=new f;Object.defineProperties(h,{length:{get:function(){this.oc||this.zc();return this.Sc}},Bc:{get:function(){this.oc||this.zc();return this.Rc}}});var m=void 0}else m=c,h=void 0;var l=Lc(a,b,d,e);h?l.fb=h:m&&(l.fb=null,l.url=m);Object.defineProperties(l,{kb:{get:function(){return this.fb.length}}});var r={};Object.keys(l.hb).forEach(n=>{var p=l.hb[n];r[n]=function(){Nc(l);return p.apply(null,arguments)}});r.read=(n,p,v,k,u)=>{Nc(l);n=n.node.fb;if(u>=n.length)return 0;k=Math.min(n.length-u,
k);if(n.slice)for(var w=0;w<k;w++)p[v+w]=n[u+w];else for(w=0;w<k;w++)p[v+w]=n.get(u+w);return k};l.hb=r;return l},Qc=(a,b,c,d,e,f,h,m,l,r)=>{function n(k){function u(w){r&&r();m||Mc(a,b,w,d,e,l);f&&f();rb(v)}Pc.Yd(k,p,u,()=>{h&&h();rb(v)})||u(k)}var p=b?Vb(Rb(a+"/"+b)):a,v="cp "+p;qb(v);"string"==typeof c?hc(c,k=>n(k),h):n(c)},S={},xc,Fc;
function Rc(a,b,c){if("/"===b[0])return b;if(-100===a)a="/";else{a=kc[a];if(!a)throw new P(8);a=a.path}if(0==b.length){if(!c)throw new P(44);return a}return Rb(a+"/"+b)}
function Sc(a,b,c){try{var d=a(b)}catch(e){if(e&&e.node&&Rb(b)!==Rb(pc(e.node)))return-54;throw e;}B()[c>>2]=d.ed;B()[c+4>>2]=0;B()[c+8>>2]=d.mc;B()[c+12>>2]=d.mode;B()[c+16>>2]=d.xd;B()[c+20>>2]=d.uid;B()[c+24>>2]=d.nd;B()[c+28>>2]=d.Rb;B()[c+32>>2]=0;wb=[d.size>>>0,(L=d.size,1<=+Math.abs(L)?0<L?(Math.min(+Math.floor(L/4294967296),4294967295)|0)>>>0:~~+Math.ceil((L-+(~~L>>>0))/4294967296)>>>0:0)];B()[c+40>>2]=wb[0];B()[c+44>>2]=wb[1];B()[c+48>>2]=4096;B()[c+52>>2]=d.Yc;B()[c+56>>2]=d.Wc.getTime()/
1E3|0;B()[c+60>>2]=0;B()[c+64>>2]=d.wd.getTime()/1E3|0;B()[c+68>>2]=0;B()[c+72>>2]=d.bd.getTime()/1E3|0;B()[c+76>>2]=0;wb=[d.mc>>>0,(L=d.mc,1<=+Math.abs(L)?0<L?(Math.min(+Math.floor(L/4294967296),4294967295)|0)>>>0:~~+Math.ceil((L-+(~~L>>>0))/4294967296)>>>0:0)];B()[c+80>>2]=wb[0];B()[c+84>>2]=wb[1];return 0}var Tc=void 0;function Uc(){Tc+=4;return B()[Tc-4>>2]}function Vc(a){a=kc[a];if(!a)throw new P(8);return a}
function Wc(a,b,c){if(G)return O(3,1,a,b,c);Tc=c;try{var d=Vc(a);switch(b){case 0:var e=Uc();return 0>e?-28:jb(d.path,d.flags,0,e).Bb;case 1:case 2:return 0;case 3:return d.flags;case 4:return e=Uc(),d.flags|=e,0;case 5:return e=Uc(),da()[e+0>>1]=2,0;case 6:case 7:return 0;case 16:case 8:return-28;case 9:return-1;default:return-28}}catch(f){if("undefined"==typeof S||!(f instanceof P))throw f;return-f.nb}}
function Xc(a,b){if(G)return O(4,1,a,b);try{var c=Vc(a);return Sc(Cc,c.path,b)}catch(d){if("undefined"==typeof S||!(d instanceof P))throw d;return-d.nb}}
function Yc(a,b,c){if(G)return O(5,1,a,b,c);Tc=c;try{var d=Vc(a);switch(b){case 21509:case 21505:return d.mb?0:-59;case 21510:case 21511:case 21512:case 21506:case 21507:case 21508:return d.mb?0:-59;case 21519:if(!d.mb)return-59;var e=Uc();return B()[e>>2]=0;case 21520:return d.mb?-28:-59;case 21531:a=e=Uc();if(!d.hb.rd)throw new P(59);return d.hb.rd(d,b,a);case 21523:return d.mb?0:-59;case 21524:return d.mb?0:-59;default:Ga("bad ioctl syscall "+b)}}catch(f){if("undefined"==typeof S||!(f instanceof
P))throw f;return-f.nb}}function Zc(a,b,c,d){if(G)return O(7,1,a,b,c,d);try{b=K(b);var e=d&256;b=Rc(a,b,d&4096);return Sc(e?Dc:Cc,b,c)}catch(f){if("undefined"==typeof S||!(f instanceof P))throw f;return-f.nb}}function $c(a,b,c,d){if(G)return O(8,1,a,b,c,d);Tc=d;try{b=K(b);b=Rc(a,b);var e=d?Uc():0;return jb(b,c,e).Bb}catch(f){if("undefined"==typeof S||!(f instanceof P))throw f;return-f.nb}}
function ad(a,b){if(G)return O(9,1,a,b);try{return a=K(a),Sc(Cc,a,b)}catch(c){if("undefined"==typeof S||!(c instanceof P))throw c;return-c.nb}}var bd={};function cd(a){for(;a.length;){var b=a.pop();a.pop()(b)}}function dd(a){return this.fromWireType(D()[a>>2])}var ed={},fd={},gd={};function hd(a){if(void 0===a)return"_unknown";a=a.replace(/[^a-zA-Z0-9_]/g,"$");var b=a.charCodeAt(0);return 48<=b&&57>=b?"_"+a:a}function jd(a,b){a=hd(a);return function(){null;return b.apply(this,arguments)}}
function kd(a){var b=Error,c=jd(a,function(d){this.name=a;this.message=d;d=Error(d).stack;void 0!==d&&(this.stack=this.toString()+"\n"+d.replace(/^Error(:[^\n]*)?\n/,""))});c.prototype=Object.create(b.prototype);c.prototype.constructor=c;c.prototype.toString=function(){return void 0===this.message?this.name:this.name+": "+this.message};return c}var ld=void 0;function md(a){throw new ld(a);}
function nd(a,b,c){function d(m){m=c(m);m.length!==a.length&&md("Mismatched type converter count");for(var l=0;l<a.length;++l)od(a[l],m[l])}a.forEach(function(m){gd[m]=b});var e=Array(b.length),f=[],h=0;b.forEach((m,l)=>{fd.hasOwnProperty(m)?e[l]=fd[m]:(f.push(m),ed.hasOwnProperty(m)||(ed[m]=[]),ed[m].push(()=>{e[l]=fd[m];++h;h===f.length&&d(e)}))});0===f.length&&d(e)}
function pd(a){switch(a){case 1:return 0;case 2:return 1;case 4:return 2;case 8:return 3;default:throw new TypeError("Unknown type size: "+a);}}var qd=void 0;function T(a){for(var b="";y()[a];)b+=qd[y()[a++]];return b}var rd=void 0;function U(a){throw new rd(a);}
function od(a,b,c={}){if(!("argPackAdvance"in b))throw new TypeError("registerType registeredInstance requires argPackAdvance");var d=b.name;a||U('type "'+d+'" must have a positive integer typeid pointer');if(fd.hasOwnProperty(a)){if(c.od)return;U("Cannot register type '"+d+"' twice")}fd[a]=b;delete gd[a];ed.hasOwnProperty(a)&&(b=ed[a],delete ed[a],b.forEach(e=>e()))}function sd(a){U(a.eb.lb.ib.name+" instance already deleted")}var td=!1;function ud(){}
function vd(a){--a.count.value;0===a.count.value&&(a.qb?a.sb.Ab(a.qb):a.lb.ib.Ab(a.jb))}function wd(a,b,c){if(b===c)return a;if(void 0===c.tb)return null;a=wd(a,b,c.tb);return null===a?null:c.fd(a)}var xd={},yd=[];function zd(){for(;yd.length;){var a=yd.pop();a.eb.Ib=!1;a["delete"]()}}var Ad=void 0,Bd={};function Cd(a,b){for(void 0===b&&U("ptr should not be undefined");a.tb;)b=a.Vb(b),a=a.tb;return Bd[b]}
function Dd(a,b){b.lb&&b.jb||md("makeClassHandle requires ptr and ptrType");!!b.sb!==!!b.qb&&md("Both smartPtrType and smartPtr must be specified");b.count={value:1};return Ed(Object.create(a,{eb:{value:b}}))}function Ed(a){if("undefined"===typeof FinalizationRegistry)return Ed=b=>b,a;td=new FinalizationRegistry(b=>{vd(b.eb)});Ed=b=>{var c=b.eb;c.qb&&td.register(b,{eb:c},b);return b};ud=b=>{td.unregister(b)};return Ed(a)}function Fd(){}
function Gd(a,b,c){if(void 0===a[b].pb){var d=a[b];a[b]=function(){a[b].pb.hasOwnProperty(arguments.length)||U("Function '"+c+"' called with an invalid number of arguments ("+arguments.length+") - expects one of ("+a[b].pb+")!");return a[b].pb[arguments.length].apply(this,arguments)};a[b].pb=[];a[b].pb[d.Wb]=d}}
function Hd(a,b,c){E.hasOwnProperty(a)?((void 0===c||void 0!==E[a].pb&&void 0!==E[a].pb[c])&&U("Cannot register public name '"+a+"' twice"),Gd(E,a,a),E.hasOwnProperty(c)&&U("Cannot register multiple overloads of a function with the same number of arguments ("+c+")!"),E[a].pb[c]=b):(E[a]=b,void 0!==c&&(E[a].$d=c))}function Id(a,b,c,d,e,f,h,m){this.name=a;this.constructor=b;this.Jb=c;this.Ab=d;this.tb=e;this.hd=f;this.Vb=h;this.fd=m;this.zd=[]}
function Jd(a,b,c){for(;b!==c;)b.Vb||U("Expected null or instance of "+c.name+", got an instance of "+b.name),a=b.Vb(a),b=b.tb;return a}function Kd(a,b){if(null===b)return this.nc&&U("null is not a valid "+this.name),0;b.eb||U('Cannot pass "'+Ld(b)+'" as a '+this.name);b.eb.jb||U("Cannot pass deleted object as a pointer of type "+this.name);return Jd(b.eb.jb,b.eb.lb.ib,this.ib)}
function Md(a,b){if(null===b){this.nc&&U("null is not a valid "+this.name);if(this.ac){var c=this.sc();null!==a&&a.push(this.Ab,c);return c}return 0}b.eb||U('Cannot pass "'+Ld(b)+'" as a '+this.name);b.eb.jb||U("Cannot pass deleted object as a pointer of type "+this.name);!this.$b&&b.eb.lb.$b&&U("Cannot convert argument of type "+(b.eb.sb?b.eb.sb.name:b.eb.lb.name)+" to parameter type "+this.name);c=Jd(b.eb.jb,b.eb.lb.ib,this.ib);if(this.ac)switch(void 0===b.eb.qb&&U("Passing raw pointer to smart pointer is illegal"),
this.Kd){case 0:b.eb.sb===this?c=b.eb.qb:U("Cannot convert argument of type "+(b.eb.sb?b.eb.sb.name:b.eb.lb.name)+" to parameter type "+this.name);break;case 1:c=b.eb.qb;break;case 2:if(b.eb.sb===this)c=b.eb.qb;else{var d=b.clone();c=this.Ad(c,W(function(){d["delete"]()}));null!==a&&a.push(this.Ab,c)}break;default:U("Unsupporting sharing policy")}return c}
function Nd(a,b){if(null===b)return this.nc&&U("null is not a valid "+this.name),0;b.eb||U('Cannot pass "'+Ld(b)+'" as a '+this.name);b.eb.jb||U("Cannot pass deleted object as a pointer of type "+this.name);b.eb.lb.$b&&U("Cannot convert argument of type "+b.eb.lb.name+" to parameter type "+this.name);return Jd(b.eb.jb,b.eb.lb.ib,this.ib)}
function Od(a,b,c,d){this.name=a;this.ib=b;this.nc=c;this.$b=d;this.ac=!1;this.Ab=this.Ad=this.sc=this.Lc=this.Kd=this.yd=void 0;void 0!==b.tb?this.toWireType=Md:(this.toWireType=d?Kd:Nd,this.ub=null)}function Pd(a,b,c){E.hasOwnProperty(a)||md("Replacing nonexistant public symbol");void 0!==E[a].pb&&void 0!==c?E[a].pb[c]=b:(E[a]=b,E[a].Wb=c)}
function Qd(a,b){var c=[];return function(){c.length=0;Object.assign(c,arguments);if(a.includes("j")){var d=E["dynCall_"+a];d=c&&c.length?d.apply(null,[b].concat(c)):d.call(null,b)}else d=M(b).apply(null,c);return d}}function Rd(a,b){a=T(a);var c=a.includes("j")?Qd(a,b):M(b);"function"!=typeof c&&U("unknown function pointer with signature "+a+": "+b);return c}var Sd=void 0;function Td(a){a=Ud(a);var b=T(a);Vd(a);return b}
function Wd(a,b){function c(f){e[f]||fd[f]||(gd[f]?gd[f].forEach(c):(d.push(f),e[f]=!0))}var d=[],e={};b.forEach(c);throw new Sd(a+": "+d.map(Td).join([", "]));}function Xd(a,b){for(var c=[],d=0;d<a;d++)c.push(B()[(b>>2)+d]);return c}
function Yd(a,b,c,d,e){var f=b.length;2>f&&U("argTypes array size mismatch! Must at least get return value and 'this' types!");var h=null!==b[1]&&null!==c,m=!1;for(c=1;c<b.length;++c)if(null!==b[c]&&void 0===b[c].ub){m=!0;break}var l="void"!==b[0].name,r=f-2,n=Array(r),p=[],v=[];return function(){arguments.length!==r&&U("function "+a+" called with "+arguments.length+" arguments, expected "+r+" args!");v.length=0;p.length=h?2:1;p[0]=e;if(h){var k=b[1].toWireType(v,this);p[1]=k}for(var u=0;u<r;++u)n[u]=
b[u+2].toWireType(v,arguments[u]),p.push(n[u]);u=d.apply(null,p);if(m)cd(v);else for(var w=h?1:2;w<b.length;w++){var A=1===w?k:n[w-2];null!==b[w].ub&&b[w].ub(A)}k=l?b[0].fromWireType(u):void 0;return k}}var Zd=[],X=[{},{value:void 0},{value:null},{value:!0},{value:!1}];function $d(a){4<a&&0===--X[a].uc&&(X[a]=void 0,Zd.push(a))}
var Y=a=>{a||U("Cannot use deleted val. handle = "+a);return X[a].value},W=a=>{switch(a){case void 0:return 1;case null:return 2;case !0:return 3;case !1:return 4;default:var b=Zd.length?Zd.pop():X.length;X[b]={uc:1,value:a};return b}};function Ld(a){if(null===a)return"null";var b=typeof a;return"object"===b||"array"===b||"function"===b?a.toString():""+a}
function ae(a,b){switch(b){case 2:return function(c){var d=this.fromWireType;q.buffer!=t&&aa(q.buffer);return d.call(this,Za[c>>2])};case 3:return function(c){return this.fromWireType(ja()[c>>3])};default:throw new TypeError("Unknown float type: "+a);}}
function be(a,b,c){switch(b){case 0:return c?function(d){return g()[d]}:function(d){return y()[d]};case 1:return c?function(d){return da()[d>>1]}:function(d){return z()[d>>1]};case 2:return c?function(d){return B()[d>>2]}:function(d){return D()[d>>2]};default:throw new TypeError("Unknown integer type: "+a);}}function ce(a,b){var c=fd[a];void 0===c&&U(b+" has unknown type "+Td(a));return c}function de(a,b){for(var c=Array(a),d=0;d<a;++d)c[d]=ce(B()[(b>>2)+d],"parameter "+d);return c}var ee={};
function fe(a){var b=ee[a];return void 0===b?T(a):b}var ge=[];
function he(){function a(b){b.$$$embind_global$$$=b;var c="object"==typeof $$$embind_global$$$&&b.$$$embind_global$$$==b;c||delete b.$$$embind_global$$$;return c}if("object"==typeof globalThis)return globalThis;if("object"==typeof $$$embind_global$$$)return $$$embind_global$$$;"object"==typeof global&&a(global)?$$$embind_global$$$=global:"object"==typeof self&&a(self)&&($$$embind_global$$$=self);if("object"==typeof $$$embind_global$$$)return $$$embind_global$$$;throw Error("unable to get global object.");
}function ie(a){var b=ge.length;ge.push(a);return b}var je=[];function ke(a){var b=Array(a+1);return function(c,d,e){b[0]=c;for(var f=0;f<a;++f){var h=ce(B()[(d>>2)+f],"parameter "+f);b[f+1]=h.readValueFromPointer(e);e+=h.argPackAdvance}c=new (c.bind.apply(c,b));return W(c)}}var le={};
function me(a,b,c,d,e,f,h,m){if(G)return O(10,1,a,b,c,d,e,f,h,m);try{var l=kc[e];if(!l)return-8;if(0!==(c&2)&&0===(d&2)&&2!==(l.flags&2097155))throw new P(2);if(1===(l.flags&2097155))throw new P(2);if(!l.hb.cc)throw new P(43);var r=l.hb.cc(l,a,b,f,c,d);var n=r.jb;B()[h>>2]=r.Vc;return n}catch(p){if("undefined"==typeof S||!(p instanceof P))throw p;return-p.nb}}
function ne(a,b,c,d,e,f){if(G)return O(11,1,a,b,c,d,e,f);try{var h=kc[e];if(h&&c&2){var m=y().slice(a,a+b);h&&h.hb.dc&&h.hb.dc(h,m,f,b,d)}}catch(l){if("undefined"==typeof S||!(l instanceof P))throw l;return-l.nb}}
function oe(a,b,c){function d(r){return(r=r.toTimeString().match(/\(([A-Za-z ]+)\)$/))?r[1]:"GMT"}if(G)return O(12,1,a,b,c);var e=(new Date).getFullYear(),f=new Date(e,0,1),h=new Date(e,6,1);e=f.getTimezoneOffset();var m=h.getTimezoneOffset(),l=Math.max(e,m);B()[a>>2]=60*l;B()[b>>2]=Number(e!=m);a=d(f);b=d(h);a=Wa(a);b=Wa(b);m<e?(B()[c>>2]=a,B()[c+4>>2]=b):(B()[c>>2]=b,B()[c+4>>2]=a)}function pe(a,b,c){pe.$c||(pe.$c=!0,oe(a,b,c))}var qe=[],re;
re=G?()=>performance.now()-E.__performance_now_clock_drift:()=>performance.now();function O(a,b){var c=arguments.length-2,d=arguments;return yb(function(){for(var e=se(8*c),f=e>>3,h=0;h<c;h++){var m=d[2+h];ja()[f+h]=m}return te(a,c,e,b)})}var ue=[],ve=[];function Z(a,b){D()[a>>2]=b;D()[a+4>>2]=b/4294967296|0}
function we(a,b){try{var c=indexedDB.open("emscripten_filesystem",1)}catch(d){b(d);return}c.onupgradeneeded=d=>{d=d.target.result;d.objectStoreNames.contains("FILES")&&d.deleteObjectStore("FILES");d.createObjectStore("FILES")};c.onsuccess=d=>a(d.target.result);c.onerror=d=>b(d)}var xe;
function ye(a,b,c,d,e){function f(C){var V=0,J=0;C&&(J=x.response?x.response.byteLength:0,V=Xa(J),y().set(new Uint8Array(x.response),V));D()[a+12>>2]=V;Z(a+16,J)}var h=D()[a+8>>2];if(h){var m=K(h),l=a+112,r=K(l);r||(r="GET");D();var n=D()[l+52>>2],p=D()[l+56>>2],v=!!D()[l+60>>2];D();var k=D()[l+68>>2],u=D()[l+72>>2],w=D()[l+76>>2],A=D()[l+80>>2];h=D()[l+84>>2];l=D()[l+88>>2];var H=!!(n&1),I=!!(n&2);n=!!(n&64);k=k?K(k):void 0;u=u?K(u):void 0;var x=new XMLHttpRequest;x.withCredentials=v;x.open(r,m,
!n,k,u);n||(x.timeout=p);x.de=m;x.responseType="arraybuffer";A&&(m=K(A),x.overrideMimeType(m));if(w)for(;;){r=D()[w>>2];if(!r)break;m=D()[w+4>>2];if(!m)break;w+=8;r=K(r);m=K(m);x.setRequestHeader(r,m)}ve.push(x);w=ve.length;D()[a+0>>2]=w;h=h&&l?y().slice(h,h+l):null;x.onload=C=>{f(H&&!I);var V=x.response?x.response.byteLength:0;Z(a+24,0);V&&Z(a+32,V);z()[a+40>>1]=x.readyState;z()[a+42>>1]=x.status;x.statusText&&Ma(x.statusText,a+44,64);200<=x.status&&300>x.status?b&&b(a,x,C):c&&c(a,x,C)};x.onerror=
C=>{f(H);var V=x.status;Z(a+24,0);Z(a+32,x.response?x.response.byteLength:0);z()[a+40>>1]=x.readyState;z()[a+42>>1]=V;c&&c(a,x,C)};x.ontimeout=C=>{c&&c(a,x,C)};x.onprogress=C=>{var V=H&&I&&x.response?x.response.byteLength:0,J=0;H&&I&&(J=Xa(V),y().set(new Uint8Array(x.response),J));D()[a+12>>2]=J;Z(a+16,V);Z(a+24,C.loaded-V);Z(a+32,C.total);z()[a+40>>1]=x.readyState;3<=x.readyState&&0===x.status&&0<C.loaded&&(x.status=200);z()[a+42>>1]=x.status;x.statusText&&Ma(x.statusText,a+44,64);d&&d(a,x,C);J&&
Vd(J)};x.onreadystatechange=C=>{z()[a+40>>1]=x.readyState;2<=x.readyState&&(z()[a+42>>1]=x.status);e&&e(a,x,C)};try{x.send(h)}catch(C){c&&c(a,x,C)}}else c(a,0,"no url specified!")}function ze(a,b){if(!Ia)if(b)a();else try{a()}catch(c){Eb(c)}}
function Ae(a,b,c,d){var e=xe;if(e){var f=a+112;(f=D()[f+64>>2])||(f=D()[a+8>>2]);var h=K(f);try{var m=e.transaction(["FILES"],"readwrite").objectStore("FILES").put(b,h);m.onsuccess=()=>{z()[a+40>>1]=4;z()[a+42>>1]=200;Ma("OK",a+44,64);c(a,0,h)};m.onerror=l=>{z()[a+40>>1]=4;z()[a+42>>1]=413;Ma("Payload Too Large",a+44,64);d(a,0,l)}}catch(l){d(a,0,l)}}else d(a,0,"IndexedDB not available!")}
function Be(a,b,c){var d=xe;if(d){var e=a+112;(e=D()[e+64>>2])||(e=D()[a+8>>2]);e=K(e);try{var f=d.transaction(["FILES"],"readonly").objectStore("FILES").get(e);f.onsuccess=h=>{if(h.target.result){h=h.target.result;var m=h.byteLength||h.length,l=Xa(m);y().set(new Uint8Array(h),l);D()[a+12>>2]=l;Z(a+16,m);Z(a+24,0);Z(a+32,m);z()[a+40>>1]=4;z()[a+42>>1]=200;Ma("OK",a+44,64);b(a,0,h)}else z()[a+40>>1]=4,z()[a+42>>1]=404,Ma("Not Found",a+44,64),c(a,0,"no data")};f.onerror=h=>{z()[a+40>>1]=4;z()[a+42>>
1]=404;Ma("Not Found",a+44,64);c(a,0,h)}}catch(h){c(a,0,h)}}else c(a,0,"IndexedDB not available!")}
function Ce(a,b,c){var d=xe;if(d){var e=a+112;(e=D()[e+64>>2])||(e=D()[a+8>>2]);e=K(e);try{var f=d.transaction(["FILES"],"readwrite").objectStore("FILES").delete(e);f.onsuccess=h=>{h=h.target.result;D()[a+12>>2]=0;Z(a+16,0);Z(a+24,0);Z(a+32,0);z()[a+40>>1]=4;z()[a+42>>1]=200;Ma("OK",a+44,64);b(a,0,h)};f.onerror=h=>{z()[a+40>>1]=4;z()[a+42>>1]=404;Ma("Not Found",a+44,64);c(a,0,h)}}catch(h){c(a,0,h)}}else c(a,0,"IndexedDB not available!")}var De={};
function Ee(){if(!Fe){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"==typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:sa||"./this.program"},b;for(b in De)void 0===De[b]?delete a[b]:a[b]=De[b];var c=[];for(b in a)c.push(b+"="+a[b]);Fe=c}return Fe}var Fe;
function Ge(a,b){if(G)return O(13,1,a,b);var c=0;Ee().forEach(function(d,e){var f=b+c;e=B()[a+4*e>>2]=f;for(f=0;f<d.length;++f)g()[e++>>0]=d.charCodeAt(f);g()[e>>0]=0;c+=d.length+1});return 0}function He(a,b){if(G)return O(14,1,a,b);var c=Ee();B()[a>>2]=c.length;var d=0;c.forEach(function(e){d+=e.length+1});B()[b>>2]=d;return 0}function Ie(a){if(G)return O(15,1,a);try{var b=Vc(a);Gc(b);return 0}catch(c){if("undefined"==typeof S||!(c instanceof P))throw c;return c.nb}}
function Je(a,b,c,d){if(G)return O(16,1,a,b,c,d);try{a:{for(var e=Vc(a),f=a=0;f<c;f++){var h=B()[b+8*f>>2],m=B()[b+(8*f+4)>>2],l=e,r=g(),n=h,p=m,v=void 0;if(0>p||0>v)throw new P(28);if(null===l.Bb)throw new P(8);if(1===(l.flags&2097155))throw new P(8);if(16384===(l.node.mode&61440))throw new P(31);if(!l.hb.read)throw new P(28);var k="undefined"!=typeof v;if(!k)v=l.position;else if(!l.seekable)throw new P(70);var u=l.hb.read(l,r,n,p,v);k||(l.position+=u);var w=u;if(0>w){var A=-1;break a}a+=w;if(w<
m)break}A=a}B()[d>>2]=A;return 0}catch(H){if("undefined"==typeof S||!(H instanceof P))throw H;return H.nb}}
function Ke(a,b,c,d,e){if(G)return O(17,1,a,b,c,d,e);try{var f=Vc(a);a=4294967296*c+(b>>>0);if(-9007199254740992>=a||9007199254740992<=a)return-61;Hc(f,a,d);wb=[f.position>>>0,(L=f.position,1<=+Math.abs(L)?0<L?(Math.min(+Math.floor(L/4294967296),4294967295)|0)>>>0:~~+Math.ceil((L-+(~~L>>>0))/4294967296)>>>0:0)];B()[e>>2]=wb[0];B()[e+4>>2]=wb[1];f.lc&&0===a&&0===d&&(f.lc=null);return 0}catch(h){if("undefined"==typeof S||!(h instanceof P))throw h;return h.nb}}
function Le(a,b,c,d){if(G)return O(18,1,a,b,c,d);try{a:{for(var e=Vc(a),f=a=0;f<c;f++){var h=B()[b+8*f>>2],m=B()[b+(8*f+4)>>2],l=Ic(e,g(),h,m,void 0);if(0>l){var r=-1;break a}a+=l}r=a}B()[d>>2]=r;return 0}catch(n){if("undefined"==typeof S||!(n instanceof P))throw n;return n.nb}}function Me(a,b){Me.Kc||(Me.Kc=Ub());for(var c=0;c<b;c++)g()[a+c>>0]=Me.Kc();return 0}function Ne(a){return 0===a%4&&(0!==a%100||0===a%400)}
var Oe=[31,29,31,30,31,30,31,31,30,31,30,31],Pe=[31,28,31,30,31,30,31,31,30,31,30,31];
function Qe(a,b,c,d){function e(k,u,w){for(k="number"==typeof k?k.toString():k||"";k.length<u;)k=w[0]+k;return k}function f(k,u){return e(k,u,"0")}function h(k,u){function w(H){return 0>H?-1:0<H?1:0}var A;0===(A=w(k.getFullYear()-u.getFullYear()))&&0===(A=w(k.getMonth()-u.getMonth()))&&(A=w(k.getDate()-u.getDate()));return A}function m(k){switch(k.getDay()){case 0:return new Date(k.getFullYear()-1,11,29);case 1:return k;case 2:return new Date(k.getFullYear(),0,3);case 3:return new Date(k.getFullYear(),
0,2);case 4:return new Date(k.getFullYear(),0,1);case 5:return new Date(k.getFullYear()-1,11,31);case 6:return new Date(k.getFullYear()-1,11,30)}}function l(k){var u=k.Fb;for(k=new Date((new Date(k.Gb+1900,0,1)).getTime());0<u;){var w=k.getMonth(),A=(Ne(k.getFullYear())?Oe:Pe)[w];if(u>A-k.getDate())u-=A-k.getDate()+1,k.setDate(1),11>w?k.setMonth(w+1):(k.setMonth(0),k.setFullYear(k.getFullYear()+1));else{k.setDate(k.getDate()+u);break}}w=new Date(k.getFullYear()+1,0,4);u=m(new Date(k.getFullYear(),
0,4));w=m(w);return 0>=h(u,k)?0>=h(w,k)?k.getFullYear()+1:k.getFullYear():k.getFullYear()-1}var r=B()[d+40>>2];d={Pd:B()[d>>2],Od:B()[d+4>>2],hc:B()[d+8>>2],xc:B()[d+12>>2],ic:B()[d+16>>2],Gb:B()[d+20>>2],yb:B()[d+24>>2],Fb:B()[d+28>>2],ce:B()[d+32>>2],Nd:B()[d+36>>2],Qd:r?K(r):""};c=K(c);r={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S","%x":"%m/%d/%y","%X":"%H:%M:%S","%Ec":"%c","%EC":"%C","%Ex":"%m/%d/%y","%EX":"%H:%M:%S","%Ey":"%y",
"%EY":"%Y","%Od":"%d","%Oe":"%e","%OH":"%H","%OI":"%I","%Om":"%m","%OM":"%M","%OS":"%S","%Ou":"%u","%OU":"%U","%OV":"%V","%Ow":"%w","%OW":"%W","%Oy":"%y"};for(var n in r)c=c.replace(new RegExp(n,"g"),r[n]);var p="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),v="January February March April May June July August September October November December".split(" ");r={"%a":function(k){return p[k.yb].substring(0,3)},"%A":function(k){return p[k.yb]},"%b":function(k){return v[k.ic].substring(0,
3)},"%B":function(k){return v[k.ic]},"%C":function(k){return f((k.Gb+1900)/100|0,2)},"%d":function(k){return f(k.xc,2)},"%e":function(k){return e(k.xc,2," ")},"%g":function(k){return l(k).toString().substring(2)},"%G":function(k){return l(k)},"%H":function(k){return f(k.hc,2)},"%I":function(k){k=k.hc;0==k?k=12:12<k&&(k-=12);return f(k,2)},"%j":function(k){for(var u=0,w=0;w<=k.ic-1;u+=(Ne(k.Gb+1900)?Oe:Pe)[w++]);return f(k.xc+u,3)},"%m":function(k){return f(k.ic+1,2)},"%M":function(k){return f(k.Od,
2)},"%n":function(){return"\n"},"%p":function(k){return 0<=k.hc&&12>k.hc?"AM":"PM"},"%S":function(k){return f(k.Pd,2)},"%t":function(){return"\t"},"%u":function(k){return k.yb||7},"%U":function(k){return f(Math.floor((k.Fb+7-k.yb)/7),2)},"%V":function(k){var u=Math.floor((k.Fb+7-(k.yb+6)%7)/7);2>=(k.yb+371-k.Fb-2)%7&&u++;if(u)53==u&&(w=(k.yb+371-k.Fb)%7,4==w||3==w&&Ne(k.Gb)||(u=1));else{u=52;var w=(k.yb+7-k.Fb-1)%7;(4==w||5==w&&Ne(k.Gb%400-1))&&u++}return f(u,2)},"%w":function(k){return k.yb},"%W":function(k){return f(Math.floor((k.Fb+
7-(k.yb+6)%7)/7),2)},"%y":function(k){return(k.Gb+1900).toString().substring(2)},"%Y":function(k){return k.Gb+1900},"%z":function(k){k=k.Nd;var u=0<=k;k=Math.abs(k)/60;return(u?"+":"-")+String("0000"+(k/60*100+k%60)).slice(-4)},"%Z":function(k){return k.Qd},"%%":function(){return"%"}};c=c.replace(/%%/g,"\x00\x00");for(n in r)c.includes(n)&&(c=c.replace(new RegExp(n,"g"),r[n](d)));c=c.replace(/\0\0/g,"%");n=$b(c,!1);if(n.length>b)return 0;Ya(n,a);return n.length-1}N.pd();
function sc(a,b,c,d){a||(a=this);this.parent=a;this.zb=a.zb;this.Pb=null;this.id=lc++;this.name=b;this.mode=c;this.gb={};this.hb={};this.Rb=d}Object.defineProperties(sc.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}},td:{get:function(){return 16384===(this.mode&61440)}},sd:{get:function(){return 8192===(this.mode&61440)}}});gb();
mc=Array(4096);zc(Q,"/");R("/tmp",16895,0);R("/home",16895,0);R("/home/web_user",16895,0);(()=>{R("/dev",16895,0);Yb(259,{read:()=>0,write:(b,c,d,e)=>e});Ac("/dev/null",259);Xb(1280,ac);Xb(1536,bc);Ac("/dev/tty",1280);Ac("/dev/tty1",1536);var a=Ub();hb("/dev","random",a);hb("/dev","urandom",a);R("/dev/shm",16895,0);R("/dev/shm/tmp",16895,0)})();
(()=>{R("/proc",16895,0);var a=R("/proc/self",16895,0);R("/proc/self/fd",16895,0);zc({zb:()=>{var b=dc(a,"fd",16895,73);b.gb={Ob:(c,d)=>{var e=kc[+d];if(!e)throw new P(8);c={parent:null,zb:{Ic:"fake"},gb:{Sb:()=>e.path}};return c.parent=c}};return b}},"/proc/self/fd")})();var Pc;E.FS_createPath=Kc;E.FS_createDataFile=Mc;E.FS_createPreloadedFile=Qc;E.FS_createLazyFile=Oc;E.FS_createDevice=hb;E.FS_unlink=Bc;ld=E.InternalError=kd("InternalError");for(var Re=Array(256),Se=0;256>Se;++Se)Re[Se]=String.fromCharCode(Se);
qd=Re;rd=E.BindingError=kd("BindingError");Fd.prototype.isAliasOf=function(a){if(!(this instanceof Fd&&a instanceof Fd))return!1;var b=this.eb.lb.ib,c=this.eb.jb,d=a.eb.lb.ib;for(a=a.eb.jb;b.tb;)c=b.Vb(c),b=b.tb;for(;d.tb;)a=d.Vb(a),d=d.tb;return b===d&&c===a};
Fd.prototype.clone=function(){this.eb.jb||sd(this);if(this.eb.Qb)return this.eb.count.value+=1,this;var a=Ed,b=Object,c=b.create,d=Object.getPrototypeOf(this),e=this.eb;a=a(c.call(b,d,{eb:{value:{count:e.count,Ib:e.Ib,Qb:e.Qb,jb:e.jb,lb:e.lb,qb:e.qb,sb:e.sb}}}));a.eb.count.value+=1;a.eb.Ib=!1;return a};Fd.prototype["delete"]=function(){this.eb.jb||sd(this);this.eb.Ib&&!this.eb.Qb&&U("Object already scheduled for deletion");ud(this);vd(this.eb);this.eb.Qb||(this.eb.qb=void 0,this.eb.jb=void 0)};
Fd.prototype.isDeleted=function(){return!this.eb.jb};Fd.prototype.deleteLater=function(){this.eb.jb||sd(this);this.eb.Ib&&!this.eb.Qb&&U("Object already scheduled for deletion");yd.push(this);1===yd.length&&Ad&&Ad(zd);this.eb.Ib=!0;return this};E.getInheritedInstanceCount=function(){return Object.keys(Bd).length};E.getLiveInheritedInstances=function(){var a=[],b;for(b in Bd)Bd.hasOwnProperty(b)&&a.push(Bd[b]);return a};E.flushPendingDeletes=zd;E.setDelayFunction=function(a){Ad=a;yd.length&&Ad&&Ad(zd)};
Od.prototype.kd=function(a){this.Lc&&(a=this.Lc(a));return a};Od.prototype.Cc=function(a){this.Ab&&this.Ab(a)};Od.prototype.argPackAdvance=8;Od.prototype.readValueFromPointer=dd;Od.prototype.deleteObject=function(a){if(null!==a)a["delete"]()};
Od.prototype.fromWireType=function(a){function b(){return this.ac?Dd(this.ib.Jb,{lb:this.yd,jb:c,sb:this,qb:a}):Dd(this.ib.Jb,{lb:this,jb:a})}var c=this.kd(a);if(!c)return this.Cc(a),null;var d=Cd(this.ib,c);if(void 0!==d){if(0===d.eb.count.value)return d.eb.jb=c,d.eb.qb=a,d.clone();d=d.clone();this.Cc(a);return d}d=this.ib.hd(c);d=xd[d];if(!d)return b.call(this);d=this.$b?d.ad:d.pointerType;var e=wd(c,this.ib,d.ib);return null===e?b.call(this):this.ac?Dd(d.ib.Jb,{lb:d,jb:e,sb:this,qb:a}):Dd(d.ib.Jb,
{lb:d,jb:e})};Sd=E.UnboundTypeError=kd("UnboundTypeError");E.count_emval_handles=function(){for(var a=0,b=5;b<X.length;++b)void 0!==X[b]&&++a;return a};E.get_first_emval=function(){for(var a=5;a<X.length;++a)if(void 0!==X[a])return X[a];return null};G||(we(a=>{xe=a;rb("library_fetch_init")},()=>{xe=!1;rb("library_fetch_init")}),"undefined"!=typeof ENVIRONMENT_IS_FETCH_WORKER&&ENVIRONMENT_IS_FETCH_WORKER||qb("library_fetch_init"));
var Te=[null,Lb,Ob,Wc,Xc,Yc,function(a,b){if(G)return O(6,1,a,b);try{return a=K(a),Sc(Dc,a,b)}catch(c){if("undefined"==typeof S||!(c instanceof P))throw c;return-c.nb}},Zc,$c,ad,me,ne,oe,Ge,He,Ie,Je,Ke,Le];function $b(a,b){var c=Array(Na(a)+1);a=La(a,c,0,c.length);b&&(c.length=a);return c}
var $e={da:function(a){Ue(a,!va,1,!ua);N.Qc()},B:function(a){G?postMessage({cmd:"cleanupThread",thread:a}):Cb(a)},Y:Pb,F:Wc,ja:Xc,ka:Yc,ha:Zc,G:$c,ia:ad,d:function(a){var b=bd[a];delete bd[a];var c=b.sc,d=b.Ab,e=b.Ec,f=e.map(h=>h.md).concat(e.map(h=>h.Id));nd([a],f,h=>{var m={};e.forEach((l,r)=>{var n=h[r],p=l.Zb,v=l.ld,k=h[r+e.length],u=l.Hd,w=l.Jd;m[l.gd]={read:A=>n.fromWireType(p(v,A)),write:(A,H)=>{var I=[];u(w,A,k.toWireType(I,H));cd(I)}}});return[{name:b.name,fromWireType:function(l){var r=
{},n;for(n in m)r[n]=m[n].read(l);d(l);return r},toWireType:function(l,r){for(var n in m)if(!(n in r))throw new TypeError('Missing field:  "'+n+'"');var p=c();for(n in m)m[n].write(p,r[n]);null!==l&&l.push(d,p);return p},argPackAdvance:8,readValueFromPointer:dd,ub:d}]})},O:function(){},sa:function(a,b,c,d,e){var f=pd(c);b=T(b);od(a,{name:b,fromWireType:function(h){return!!h},toWireType:function(h,m){return m?d:e},argPackAdvance:8,readValueFromPointer:function(h){if(1===c)var m=g();else if(2===c)m=
da();else if(4===c)m=B();else throw new TypeError("Unknown boolean type size: "+b);return this.fromWireType(m[h>>f])},ub:null})},s:function(a,b,c,d,e,f,h,m,l,r,n,p,v){n=T(n);f=Rd(e,f);m&&(m=Rd(h,m));r&&(r=Rd(l,r));v=Rd(p,v);var k=hd(n);Hd(k,function(){Wd("Cannot construct "+n+" due to unbound types",[d])});nd([a,b,c],d?[d]:[],function(u){u=u[0];if(d){var w=u.ib;var A=w.Jb}else A=Fd.prototype;u=jd(k,function(){if(Object.getPrototypeOf(this)!==H)throw new rd("Use 'new' to construct "+n);if(void 0===
I.Db)throw new rd(n+" has no accessible constructor");var C=I.Db[arguments.length];if(void 0===C)throw new rd("Tried to invoke ctor of "+n+" with invalid number of parameters ("+arguments.length+") - expected ("+Object.keys(I.Db).toString()+") parameters instead!");return C.apply(this,arguments)});var H=Object.create(A,{constructor:{value:u}});u.prototype=H;var I=new Id(n,u,H,v,w,f,m,r);w=new Od(n,I,!0,!1);A=new Od(n+"*",I,!1,!1);var x=new Od(n+" const*",I,!1,!0);xd[a]={pointerType:A,ad:x};Pd(k,u);
return[w,A,x]})},t:function(a,b,c,d,e,f){0<b||Ga(void 0);var h=Xd(b,c);e=Rd(d,e);nd([],[a],function(m){m=m[0];var l="constructor "+m.name;void 0===m.ib.Db&&(m.ib.Db=[]);if(void 0!==m.ib.Db[b-1])throw new rd("Cannot register multiple constructors with identical number of parameters ("+(b-1)+") for class '"+m.name+"'! Overload resolution is currently only performed using the parameter count, not actual type info!");m.ib.Db[b-1]=()=>{Wd("Cannot construct "+m.name+" due to unbound types",h)};nd([],h,
function(r){r.splice(1,0,null);m.ib.Db[b-1]=Yd(l,r,null,e,f);return[]});return[]})},g:function(a,b,c,d,e,f,h,m){var l=Xd(c,d);b=T(b);f=Rd(e,f);nd([],[a],function(r){function n(){Wd("Cannot call "+p+" due to unbound types",l)}r=r[0];var p=r.name+"."+b;b.startsWith("@@")&&(b=Symbol[b.substring(2)]);m&&r.ib.zd.push(b);var v=r.ib.Jb,k=v[b];void 0===k||void 0===k.pb&&k.className!==r.name&&k.Wb===c-2?(n.Wb=c-2,n.className=r.name,v[b]=n):(Gd(v,b,p),v[b].pb[c-2]=n);nd([],l,function(u){u=Yd(p,u,r,f,h);void 0===
v[b].pb?(u.Wb=c-2,v[b]=u):v[b].pb[c-2]=u;return[]});return[]})},ra:function(a,b){b=T(b);od(a,{name:b,fromWireType:function(c){var d=Y(c);$d(c);return d},toWireType:function(c,d){return W(d)},argPackAdvance:8,readValueFromPointer:dd,ub:null})},I:function(a,b,c){c=pd(c);b=T(b);od(a,{name:b,fromWireType:function(d){return d},toWireType:function(d,e){return e},argPackAdvance:8,readValueFromPointer:ae(b,c),ub:null})},z:function(a,b,c,d,e,f){var h=Xd(b,c);a=T(a);e=Rd(d,e);Hd(a,function(){Wd("Cannot call "+
a+" due to unbound types",h)},b-1);nd([],h,function(m){Pd(a,Yd(a,[m[0],null].concat(m.slice(1)),null,e,f),b-1);return[]})},l:function(a,b,c,d,e){b=T(b);-1===e&&(e=4294967295);e=pd(c);var f=m=>m;if(0===d){var h=32-8*c;f=m=>m<<h>>>h}c=b.includes("unsigned")?function(m,l){return l>>>0}:function(m,l){return l};od(a,{name:b,fromWireType:f,toWireType:c,argPackAdvance:8,readValueFromPointer:be(b,e,0!==d),ub:null})},f:function(a,b,c){function d(f){f>>=2;var h=D();return new e(t,h[f+1],h[f])}var e=[Int8Array,
Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array][b];c=T(c);od(a,{name:c,fromWireType:d,argPackAdvance:8,readValueFromPointer:d},{od:!0})},J:function(a,b){b=T(b);var c="std::string"===b;od(a,{name:b,fromWireType:function(d){var e=D()[d>>2];if(c)for(var f=d+4,h=0;h<=e;++h){var m=d+4+h;if(h==e||0==y()[m]){f=K(f,m-f);if(void 0===l)var l=f;else l+=String.fromCharCode(0),l+=f;f=m+1}}else{l=Array(e);for(h=0;h<e;++h)l[h]=String.fromCharCode(y()[d+4+h]);l=l.join("")}Vd(d);
return l},toWireType:function(d,e){e instanceof ArrayBuffer&&(e=new Uint8Array(e));var f="string"==typeof e;f||e instanceof Uint8Array||e instanceof Uint8ClampedArray||e instanceof Int8Array||U("Cannot pass non-string to std::string");var h=(c&&f?()=>Na(e):()=>e.length)(),m=Xa(4+h+1);D()[m>>2]=h;if(c&&f)Ma(e,m+4,h+1);else if(f)for(f=0;f<h;++f){var l=e.charCodeAt(f);255<l&&(Vd(m),U("String has UTF-16 code units that do not fit in 8 bits"));y()[m+4+f]=l}else for(f=0;f<h;++f)y()[m+4+f]=e[f];null!==d&&
d.push(Vd,m);return m},argPackAdvance:8,readValueFromPointer:dd,ub:function(d){Vd(d)}})},x:function(a,b,c){c=T(c);if(2===b){var d=Pa;var e=Qa;var f=Ra;var h=()=>z();var m=1}else 4===b&&(d=Sa,e=Ta,f=Ua,h=()=>D(),m=2);od(a,{name:c,fromWireType:function(l){for(var r=D()[l>>2],n=h(),p,v=l+4,k=0;k<=r;++k){var u=l+4+k*b;if(k==r||0==n[u>>m])v=d(v,u-v),void 0===p?p=v:(p+=String.fromCharCode(0),p+=v),v=u+b}Vd(l);return p},toWireType:function(l,r){"string"!=typeof r&&U("Cannot pass non-string to C++ string type "+
c);var n=f(r),p=Xa(4+n+b);D()[p>>2]=n>>m;e(r,p+4,n+b);null!==l&&l.push(Vd,p);return p},argPackAdvance:8,readValueFromPointer:dd,ub:function(l){Vd(l)}})},e:function(a,b,c,d,e,f){bd[a]={name:T(b),sc:Rd(c,d),Ab:Rd(e,f),Ec:[]}},b:function(a,b,c,d,e,f,h,m,l,r){bd[a].Ec.push({gd:T(b),md:c,Zb:Rd(d,e),ld:f,Id:h,Hd:Rd(m,l),Jd:r})},ta:function(a,b){b=T(b);od(a,{ud:!0,name:b,argPackAdvance:0,fromWireType:function(){},toWireType:function(){}})},H:function(){return Date.now()},Z:function(){return 2097152},ua:function(a){delete ve[a-
1]},na:function(){return!0},_:function(a,b,c,d){if(a==b)setTimeout(()=>{Ib()&&Jb(d);Atomics.sub(B(),d>>2,1)});else if(G)postMessage({targetThread:a,cmd:"processProxyingQueue",queue:d});else{a=(a=N.xb[a])&&a.worker;if(!a)return;a.postMessage({cmd:"processProxyingQueue",queue:d})}return 1},ca:function(){return-1},T:function(){throw Infinity;},m:function(a,b,c){a=Y(a);b=ce(b,"emval::as");var d=[],e=W(d);B()[c>>2]=e;return b.toWireType(d,a)},Aa:function(a,b,c,d){a=Y(a);c=de(b,c);for(var e=Array(b),f=
0;f<b;++f){var h=c[f];e[f]=h.readValueFromPointer(d);d+=h.argPackAdvance}a=a.apply(void 0,e);return W(a)},r:function(a,b,c,d){a=ge[a];b=Y(b);c=fe(c);a(b,c,null,d)},C:$d,Ba:function(a,b){a=Y(a);b=Y(b);return a==b},ya:function(a){if(0===a)return W(he());a=fe(a);return W(he()[a])},q:function(a,b){var c=de(a,b),d=c[0];b=d.name+"_$"+c.slice(1).map(function(h){return h.name}).join("_")+"$";var e=je[b];if(void 0!==e)return e;var f=Array(a-1);e=ie((h,m,l,r)=>{for(var n=0,p=0;p<a-1;++p)f[p]=c[p+1].readValueFromPointer(r+
n),n+=c[p+1].argPackAdvance;h=h[m].apply(h,f);for(p=0;p<a-1;++p)c[p+1].dd&&c[p+1].dd(f[p]);if(!d.ud)return d.toWireType(l,h)});return je[b]=e},p:function(a,b){a=Y(a);b=Y(b);return W(a[b])},L:function(a){4<a&&(X[a].uc+=1)},za:function(a,b){a=Y(a);b=Y(b);return a instanceof b},y:function(a,b,c,d){a=Y(a);var e=le[b];e||(e=ke(b),le[b]=e);return e(a,c,d)},R:function(){return W([])},Ea:function(a){return W(fe(a))},fa:function(){return W({})},Da:function(a){var b=Y(a);cd(b);$d(a)},c:function(a,b,c){a=Y(a);
b=Y(b);c=Y(c);a[b]=c},j:function(a,b){a=ce(a,"_emval_take_value");a=a.readValueFromPointer(b);return W(a)},Ca:function(a){a=Y(a);return W(typeof a)},oa:function(a,b){a=new Date(1E3*B()[a>>2]);B()[b>>2]=a.getSeconds();B()[b+4>>2]=a.getMinutes();B()[b+8>>2]=a.getHours();B()[b+12>>2]=a.getDate();B()[b+16>>2]=a.getMonth();B()[b+20>>2]=a.getFullYear()-1900;B()[b+24>>2]=a.getDay();var c=new Date(a.getFullYear(),0,1),d=(a.getTime()-c.getTime())/864E5|0;B()[b+28>>2]=d;B()[b+36>>2]=-(60*a.getTimezoneOffset());
d=(new Date(a.getFullYear(),6,1)).getTimezoneOffset();c=c.getTimezoneOffset();a=(d!=c&&a.getTimezoneOffset()==Math.min(c,d))|0;B()[b+32>>2]=a},pa:function(a){var b=new Date(B()[a+20>>2]+1900,B()[a+16>>2],B()[a+12>>2],B()[a+8>>2],B()[a+4>>2],B()[a>>2],0),c=B()[a+32>>2],d=b.getTimezoneOffset(),e=new Date(b.getFullYear(),0,1),f=(new Date(b.getFullYear(),6,1)).getTimezoneOffset(),h=e.getTimezoneOffset(),m=Math.min(h,f);0>c?B()[a+32>>2]=Number(f!=h&&m==d):0<c!=(m==d)&&(f=Math.max(h,f),b.setTime(b.getTime()+
6E4*((0<c?m:f)-d)));B()[a+24>>2]=b.getDay();c=(b.getTime()-e.getTime())/864E5|0;B()[a+28>>2]=c;B()[a>>2]=b.getSeconds();B()[a+4>>2]=b.getMinutes();B()[a+8>>2]=b.getHours();B()[a+12>>2]=b.getDate();B()[a+16>>2]=b.getMonth();return b.getTime()/1E3|0},$:me,aa:ne,qa:pe,n:function(){Ga("")},M:function(){var a=E.allowedThreads;return a?a:navigator.hardwareConcurrency},o:function(a,b,c){qe.length=0;var d;for(c>>=2;d=y()[b++];)(d=105>d)&&c&1&&c++,qe.push(d?ja()[c++>>1]:B()[c]),++c;return xb[a].apply(null,
qe)},D:function(){va||(Da||(Da={}),Da["Blocking on the main thread is very dangerous, see https://emscripten.org/docs/porting/pthreads.html#blocking-on-the-main-browser-thread"]||(Da["Blocking on the main thread is very dangerous, see https://emscripten.org/docs/porting/pthreads.html#blocking-on-the-main-browser-thread"]=1,F("Blocking on the main thread is very dangerous, see https://emscripten.org/docs/porting/pthreads.html#blocking-on-the-main-browser-thread")))},X:function(){return 838860800},
k:re,xa:function(){return"undefined"!=typeof SharedArrayBuffer},la:function(a,b,c){y().copyWithin(a,b,b+c)},ba:function(a,b,c){ue.length=b;c>>=3;for(var d=0;d<b;d++)ue[d]=ja()[c+d];return(0>a?xb[-a-1]:Te[a]).apply(null,ue)},W:function(a){var b=y().length;a>>>=0;if(a<=b||838860800<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);var e=Math;d=Math.max(a,d);e=e.min.call(e,838860800,d+(65536-d%65536)%65536);a:{try{q.grow(e-t.byteLength+65535>>>16);aa(q.buffer);var f=1;break a}catch(h){}f=
void 0}if(f)return!0}return!1},va:function(a,b,c,d,e){var f=a+112,h=K(f),m=D()[f+36>>2],l=D()[f+40>>2],r=D()[f+44>>2],n=D()[f+48>>2],p=D()[f+52>>2],v=!!(p&4),k=!!(p&32),u=!!(p&16),w=!!(p&64),A=J=>{ze(()=>{m?M(m)(J):b&&b(J)},w)},H=J=>{ze(()=>{r?M(r)(J):d&&d(J)},w)},I=J=>{ze(()=>{l?M(l)(J):c&&c(J)},w)},x=J=>{ze(()=>{n?M(n)(J):e&&e(J)},w)};p=J=>{ye(J,A,I,H,x)};var C=(J,Ye)=>{Ae(J,Ye.response,Va=>{ze(()=>{m?M(m)(Va):b&&b(Va)},w)},Va=>{ze(()=>{m?M(m)(Va):b&&b(Va)},w)})},V=J=>{ye(J,C,I,H,x)};if("EM_IDB_STORE"===
h)h=D()[f+84>>2],Ae(a,y().slice(h,h+D()[f+88>>2]),A,I);else if("EM_IDB_DELETE"===h)Ce(a,A,I);else if(u){if(k)return 0;ye(a,v?C:A,I,H,x)}else Be(a,A,k?I:v?V:p);return a},ma:function(){throw"unwind";},ea:Ge,ga:He,u:function(a){Mb(a)},w:Ie,E:Je,N:Ke,v:Le,wa:function(){var a=na(),b=Na(a)+1,c=Xa(b);Ma(a,c,b);return c},i:function(){return Ea},U:Me,P:Ve,A:We,Q:Xe,S:Ze,a:q||E.wasmMemory,h:function(a){Ea=a},K:Qe,V:function(a,b,c,d){return Qe(a,b,c,d)}};
(function(){function a(e,f){E.asm=e.exports;N.fc.push(E.asm.Ja);ab=E.asm.Pa;cb.unshift(E.asm.Fa);Ha=f;G||rb("wasm-instantiate")}function b(e){a(e.instance,e.module)}function c(e){return vb().then(function(f){return WebAssembly.instantiate(f,d)}).then(function(f){return f}).then(e,function(f){F("failed to asynchronously prepare wasm: "+f);Ga(f)})}var d={a:$e};G||qb("wasm-instantiate");if(E.instantiateWasm)try{return E.instantiateWasm(d,a)}catch(e){return F("Module.instantiateWasm callback failed with error: "+
e),!1}(function(){return Fa||"function"!=typeof WebAssembly.instantiateStreaming||sb()||"function"!=typeof fetch?c(b):fetch(tb,{credentials:"same-origin"}).then(function(e){return WebAssembly.instantiateStreaming(e,d).then(b,function(f){F("wasm streaming compile failed: "+f);F("falling back to ArrayBuffer instantiation");return c(b)})})})().catch(ma);return{}})();E.___wasm_call_ctors=function(){return(E.___wasm_call_ctors=E.asm.Fa).apply(null,arguments)};
var Xa=E._malloc=function(){return(Xa=E._malloc=E.asm.Ga).apply(null,arguments)},Vd=E._free=function(){return(Vd=E._free=E.asm.Ha).apply(null,arguments)},Ib=E._pthread_self=function(){return(Ib=E._pthread_self=E.asm.Ia).apply(null,arguments)};E._emscripten_tls_init=function(){return(E._emscripten_tls_init=E.asm.Ja).apply(null,arguments)};
var gc=E._emscripten_builtin_memalign=function(){return(gc=E._emscripten_builtin_memalign=E.asm.Ka).apply(null,arguments)},Ud=E.___getTypeName=function(){return(Ud=E.___getTypeName=E.asm.La).apply(null,arguments)};E.___embind_register_native_and_builtin_types=function(){return(E.___embind_register_native_and_builtin_types=E.asm.Ma).apply(null,arguments)};var Ue=E.__emscripten_thread_init=function(){return(Ue=E.__emscripten_thread_init=E.asm.Na).apply(null,arguments)};
E.__emscripten_thread_crashed=function(){return(E.__emscripten_thread_crashed=E.asm.Oa).apply(null,arguments)};var Jb=E._emscripten_proxy_execute_queue=function(){return(Jb=E._emscripten_proxy_execute_queue=E.asm.Qa).apply(null,arguments)},te=E._emscripten_run_in_main_runtime_thread_js=function(){return(te=E._emscripten_run_in_main_runtime_thread_js=E.asm.Ra).apply(null,arguments)},Gb=E.__emscripten_thread_free_data=function(){return(Gb=E.__emscripten_thread_free_data=E.asm.Sa).apply(null,arguments)};
E.__emscripten_thread_exit=function(){return(E.__emscripten_thread_exit=E.asm.Ta).apply(null,arguments)};
var af=E._setThrew=function(){return(af=E._setThrew=E.asm.Ua).apply(null,arguments)},Kb=E._emscripten_stack_set_limits=function(){return(Kb=E._emscripten_stack_set_limits=E.asm.Va).apply(null,arguments)},zb=E.stackSave=function(){return(zb=E.stackSave=E.asm.Wa).apply(null,arguments)},Ab=E.stackRestore=function(){return(Ab=E.stackRestore=E.asm.Xa).apply(null,arguments)},se=E.stackAlloc=function(){return(se=E.stackAlloc=E.asm.Ya).apply(null,arguments)};
E.dynCall_ji=function(){return(E.dynCall_ji=E.asm.Za).apply(null,arguments)};E.dynCall_jiji=function(){return(E.dynCall_jiji=E.asm._a).apply(null,arguments)};E.dynCall_viijii=function(){return(E.dynCall_viijii=E.asm.$a).apply(null,arguments)};E.dynCall_iiiiij=function(){return(E.dynCall_iiiiij=E.asm.ab).apply(null,arguments)};E.dynCall_iiiiijj=function(){return(E.dynCall_iiiiijj=E.asm.bb).apply(null,arguments)};E.dynCall_iiiiiijj=function(){return(E.dynCall_iiiiiijj=E.asm.cb).apply(null,arguments)};
var Hb=E.__emscripten_allow_main_runtime_queued_calls=468644;function We(a,b){var c=zb();try{M(a)(b)}catch(d){Ab(c);if(d!==d+0)throw d;af(1,0)}}function Ze(a,b,c,d){var e=zb();try{M(a)(b,c,d)}catch(f){Ab(e);if(f!==f+0)throw f;af(1,0)}}function Xe(a,b,c){var d=zb();try{M(a)(b,c)}catch(e){Ab(d);if(e!==e+0)throw e;af(1,0)}}function Ve(a,b,c,d){var e=zb();try{return M(a)(b,c,d)}catch(f){Ab(e);if(f!==f+0)throw f;af(1,0)}}E.addRunDependency=qb;E.removeRunDependency=rb;E.FS_createPath=Kc;
E.FS_createDataFile=Mc;E.FS_createPreloadedFile=Qc;E.FS_createLazyFile=Oc;E.FS_createDevice=hb;E.FS_unlink=Bc;E.keepRuntimeAlive=function(){return noExitRuntime};E.PThread=N;E.PThread=N;E.wasmMemory=q;E.ExitStatus=Fb;var bf;function Fb(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}pb=function cf(){bf||df();bf||(pb=cf)};
function df(){function a(){if(!bf&&(bf=!0,E.calledRun=!0,!Ia)){eb();la(E);if(E.onRuntimeInitialized)E.onRuntimeInitialized();if(!G){if(E.postRun)for("function"==typeof E.postRun&&(E.postRun=[E.postRun]);E.postRun.length;){var b=E.postRun.shift();db.unshift(b)}lb(db)}}}if(!(0<nb))if(G)la(E),eb(),postMessage({cmd:"loaded"});else{if(E.preRun)for("function"==typeof E.preRun&&(E.preRun=[E.preRun]);E.preRun.length;)mb();lb(bb);0<nb||(E.setStatus?(E.setStatus("Running..."),setTimeout(function(){setTimeout(function(){E.setStatus("")},
1);a()},1)):a())}}E.run=df;function Mb(a){if(G)throw Lb(a),"unwind";if(!noExitRuntime){N.Md();if(E.onExit)E.onExit(a);Ia=!0}ta(a,new Fb(a))}if(E.preInit)for("function"==typeof E.preInit&&(E.preInit=[E.preInit]);0<E.preInit.length;)E.preInit.pop()();df();


  return BlinkIDWasmSDK.ready
}
);
})();
if (typeof exports === 'object' && typeof module === 'object')
  module.exports = BlinkIDWasmSDK;
else if (typeof define === 'function' && define['amd'])
  define([], function() { return BlinkIDWasmSDK; });
else if (typeof exports === 'object')
  exports["BlinkIDWasmSDK"] = BlinkIDWasmSDK;
