
var BlinkIDWasmSDK = (() => {
  var _scriptDir = typeof document !== 'undefined' && document.currentScript ? document.currentScript.src : undefined;
  
  return (
function(moduleArg = {}) {

/*

 Copyright 2019 The Emscripten Authors
 SPDX-License-Identifier: MIT

 Copyright 2013 The Emscripten Authors
 SPDX-License-Identifier: MIT

 This file gets implicatly injected as a `--post-js` file when
 emcc is run with `--emrun`
*/
function h(){u.buffer!=aa.buffer&&ba();return aa}function v(){u.buffer!=aa.buffer&&ba();return ca}function da(){u.buffer!=aa.buffer&&ba();return ea}function x(){u.buffer!=aa.buffer&&ba();return fa}function A(){u.buffer!=aa.buffer&&ba();return ha}function B(){u.buffer!=aa.buffer&&ba();return ia}function ja(){u.buffer!=aa.buffer&&ba();return ka}var D=moduleArg,la,ma;D.ready=new Promise((a,b)=>{la=a;ma=b});D.lc||(D.lc=0);D.lc++;
D.ENVIRONMENT_IS_PTHREAD||D.$ww||function(a){function b(m,n,t){var p=new XMLHttpRequest;p.open("GET",m,!0);p.responseType="arraybuffer";p.onprogress=function(r){var k=n;r.total&&(k=r.total);if(r.loaded){p.Vc?D.Lb[m].loaded=r.loaded:(p.Vc=!0,D.Lb||(D.Lb={}),D.Lb[m]={loaded:r.loaded,total:k});var q=k=r=0,w;for(w in D.Lb){var z=D.Lb[w];r+=z.total;k+=z.loaded;q++}r=Math.ceil(r*D.lc/q);D.setStatus&&D.setStatus(`Downloading data... (${k}/${r})`)}else!D.Lb&&D.setStatus&&D.setStatus("Downloading data...")};
p.onerror=function(){throw Error("NetworkError for: "+m);};p.onload=function(){if(200==p.status||304==p.status||206==p.status||0==p.status&&p.response)t(p.response);else throw Error(p.statusText+" : "+p.responseURL);};p.send(null)}function c(m){console.error("package error:",m)}function d(){function m(r,k,q){this.start=r;this.end=k;this.audio=q}function n(r){if(!r)throw"Loading data file failed."+Error().stack;if(r.constructor.name!==ArrayBuffer.name)throw"bad input to processPackageData"+Error().stack;
r=new Uint8Array(r);m.prototype.$c=r;r=a.files;for(var k=0;k<r.length;++k)m.prototype.tc[r[k].filename].onload();D.removeRunDependency("datafile_/opt/jenkins/jenkinsData/E0/sdk-blinkid-in-browser/resources/full/advanced-threads/BlinkIDWasmSDK.data")}D.FS_createPath("/","microblink",!0,!0);m.prototype={tc:{},open:function(r,k){this.name=k;this.tc[k]=this;D.addRunDependency(`fp ${this.name}`)},send:function(){},onload:function(){this.finish(this.$c.subarray(this.start,this.end))},finish:function(r){D.FS_createDataFile(this.name,
null,r,!0,!0,!0);D.removeRunDependency(`fp ${this.name}`);this.tc[this.name]=null}};for(var t=a.files,p=0;p<t.length;++p)(new m(t[p].start,t[p].end,t[p].audio||0)).open("GET",t[p].filename);D.addRunDependency("datafile_/opt/jenkins/jenkinsData/E0/sdk-blinkid-in-browser/resources/full/advanced-threads/BlinkIDWasmSDK.data");D.Hc||(D.Hc={});D.Hc["/opt/jenkins/jenkinsData/E0/sdk-blinkid-in-browser/resources/full/advanced-threads/BlinkIDWasmSDK.data"]={Ud:!1};l?(n(l),l=null):g=n}"object"===typeof window?
window.encodeURIComponent(window.location.pathname.toString().substring(0,window.location.pathname.toString().lastIndexOf("/"))+"/"):"undefined"===typeof process&&"undefined"!==typeof location&&encodeURIComponent(location.pathname.toString().substring(0,location.pathname.toString().lastIndexOf("/"))+"/");"function"!==typeof D.locateFilePackage||D.locateFile||(D.locateFile=D.locateFilePackage,E("warning: you defined Module.locateFilePackage, that has been renamed to Module.locateFile (using your locateFilePackage for now)"));
var e=D.locateFile?D.locateFile("BlinkIDWasmSDK.data",""):"BlinkIDWasmSDK.data",f=a.remote_package_size,g=null,l=D.getPreloadedPackage?D.getPreloadedPackage(e,f):null;l||b(e,f,function(m){g?(g(m),g=null):l=m},c);D.calledRun?d():(D.preRun||(D.preRun=[]),D.preRun.push(d))}({files:[{filename:"/microblink/Model_07c7ab860e77ec2e92bb822f6d62424b8595a5beb4340f6b2f7f6a4cffa5d050.strop",start:0,end:120418},{filename:"/microblink/Model_2880751121560047e6dc571bc8ff4683aeb863886f7c0789234594ceb1e23577.strop",
start:120418,end:124356},{filename:"/microblink/Model_36d8e94f4cb46097bd6b7385f2aa91fcdee1a5fefeec59e56d1b9e82c94b00a7.strop",start:124356,end:494152},{filename:"/microblink/Model_473ac5f5e256623c0a6b282698c1f1b033b9fb5359e6aa142e9fb4a4022afe4e.strop",start:494152,end:501034},{filename:"/microblink/Model_500f4403bf221021bb85c3e758d59f69841635787f6f4201a4ffe5e68733f8bb.strop",start:501034,end:1084172},{filename:"/microblink/Model_63d9b8a72214cdbdfc3eee270a04e2a90adfaf7114fe68898130fa61bac7189d.strop",
start:1084172,end:1219566},{filename:"/microblink/Model_80edc20a6f8f633671d2dccf75bb3efc1dc4ffc8873c060c7fad88e4cd22fb5b.strop",start:1219566,end:2041200},{filename:"/microblink/Model_82ae7b860c6b4cb8249534e0004901bc46dee18fd3adbe535809abeefbf4fd88.strop",start:2041200,end:6759516},{filename:"/microblink/Model_8326c5065a6d8451d6d004db73babf4a4a9f502c68643a14934cc098d04bf44f.strop",start:6759516,end:7176620},{filename:"/microblink/Model_a0fe6f57f1b9be97d6d3c0e8df49805a1b94e638413127c6edd3ce6b7c622e07.strop",
start:7176620,end:10140172},{filename:"/microblink/Model_b452fd3cd4037080cfcb4c423dba5bc58c8ceafc28427fdf9c5778fb353f088e.strop",start:10140172,end:10147022},{filename:"/microblink/Model_d2bcaf18d17504513598e04f472c035b3d4f22d8653d5a79c05b4508a4b547b3.strop",start:10147022,end:10580538},{filename:"/microblink/Model_e4f1f62f68ec44b71ecad3fb3f3b48fe3790beb5ab325611e17d63af06e9f644.strop",start:10580538,end:10637052},{filename:"/microblink/Model_ed586fd6ca47c8eebb513c4ffaaacc2c54e92162b145062d7022519fba0911de.strop",
start:10637052,end:11350284},{filename:"/microblink/Model_faf688599c7e261a2a7404730f69ed029115bb0d3e7a3657731d88e701720efe.strop",start:11350284,end:11367022},{filename:"/microblink/ccc_lookup_table.zzip",start:11367022,end:11387491},{filename:"/microblink/face_detector_model.zzip",start:11387491,end:11484349}],remote_package_size:11484349});D.onAbort=function(a){E("Aborted with message: "+a);try{throw new WebAssembly.RuntimeError(a);}catch(b){E("Stacktrace: "+b.stack)}};
if("object"==typeof window){D.arguments=window.location.search.substr(1).trim().split("&");for(let a=0;a<D.arguments.length;++a)D.arguments[a]=decodeURI(D.arguments[a]);D.arguments[0]||(D.arguments=[])}var na=Object.assign({},D),oa="./this.program",pa=(a,b)=>{throw b;},qa="object"==typeof window,ra="function"==typeof importScripts,sa="object"==typeof process&&"object"==typeof process.Md&&"string"==typeof process.Md.node,F=D.ENVIRONMENT_IS_PTHREAD||!1,ta="";
function ua(a){return D.locateFile?D.locateFile(a,ta):ta+a}var va,wa,xa;
if(qa||ra)ra?ta=self.location.href:"undefined"!=typeof document&&document.currentScript&&(ta=document.currentScript.src),_scriptDir&&(ta=_scriptDir),ta=ta.startsWith("blob:")?"":ta.substr(0,ta.replace(/[?#].*/,"").lastIndexOf("/")+1),va=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},ra&&(xa=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),wa=(a,b,c)=>{var d=new XMLHttpRequest;d.open("GET",
a,!0);d.responseType="arraybuffer";d.onload=()=>{200==d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)};var ya=D.print||console.log.bind(console),E=D.printErr||console.error.bind(console);Object.assign(D,na);na=null;D.thisProgram&&(oa=D.thisProgram);D.quit&&(pa=D.quit);var za;D.wasmBinary&&(za=D.wasmBinary);"object"!=typeof WebAssembly&&Aa("no native wasm support detected");var u,Ba,Ca=!1,Da,aa,ca,ea,fa,ha,ia,Ea,ka;
function ba(){var a=u.buffer;D.HEAP8=aa=new Int8Array(a);D.HEAP16=ea=new Int16Array(a);D.HEAPU8=ca=new Uint8Array(a);D.HEAPU16=fa=new Uint16Array(a);D.HEAP32=ha=new Int32Array(a);D.HEAPU32=ia=new Uint32Array(a);D.HEAPF32=Ea=new Float32Array(a);D.HEAPF64=ka=new Float64Array(a)}var Fa=D.INITIAL_MEMORY||209715200;
if(F)u=D.wasmMemory;else if(D.wasmMemory)u=D.wasmMemory;else if(u=new WebAssembly.Memory({initial:Fa/65536,maximum:32768,shared:!0}),!(u.buffer instanceof SharedArrayBuffer))throw E("requested a shared WebAssembly.Memory but the returned buffer is not a SharedArrayBuffer, indicating that while the browser has SharedArrayBuffer it does not have WebAssembly threads support - you may need to set a flag"),sa&&E("(on node you may need: --experimental-wasm-threads --experimental-wasm-bulk-memory and/or recent version)"),
Error("bad memory");ba();Fa=u.buffer.byteLength;var Ga=[],Ha=[],Ia=[],Ja=[],Ka=!1;function La(){F||(D.noFSInit||Ma||(Ma=!0,D.stdin=D.stdin,D.stdout=D.stdout,D.stderr=D.stderr,D.stdin?Na("/dev","stdin",D.stdin):Oa("/dev/tty","/dev/stdin"),D.stdout?Na("/dev","stdout",null,D.stdout):Oa("/dev/tty","/dev/stdout"),D.stderr?Na("/dev","stderr",null,D.stderr):Oa("/dev/tty1","/dev/stderr"),Pa("/dev/stdin",0),Pa("/dev/stdout",1),Pa("/dev/stderr",1)),Qa=!1,Ra(Ha))}var Sa=0,Ta=null,Ua=null;
function Va(){Sa++;D.monitorRunDependencies?.(Sa)}function Wa(){Sa--;D.monitorRunDependencies?.(Sa);if(0==Sa&&(null!==Ta&&(clearInterval(Ta),Ta=null),Ua)){var a=Ua;Ua=null;a()}}function Aa(a){D.onAbort?.(a);a="Aborted("+a+")";E(a);Ca=!0;Da=1;a=new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");ma(a);throw a;}var Xa=a=>a.startsWith("data:application/octet-stream;base64,"),Ya;Ya="BlinkIDWasmSDK.wasm";Xa(Ya)||(Ya=ua(Ya));
function Za(a){if(a==Ya&&za)return new Uint8Array(za);if(xa)return xa(a);throw"both async and sync fetching of the wasm failed";}function $a(a){return za||!qa&&!ra||"function"!=typeof fetch?Promise.resolve().then(()=>Za(a)):fetch(a,{credentials:"same-origin"}).then(b=>{if(!b.ok)throw`failed to load wasm binary file at '${a}'`;return b.arrayBuffer()}).catch(()=>Za(a))}
function bb(a,b,c){return $a(a).then(d=>WebAssembly.instantiate(d,b)).then(d=>d).then(c,d=>{E(`failed to asynchronously prepare wasm: ${d}`);Aa(d)})}function cb(a,b){var c=Ya;return za||"function"!=typeof WebAssembly.instantiateStreaming||Xa(c)||"function"!=typeof fetch?bb(c,a,b):fetch(c,{credentials:"same-origin"}).then(d=>WebAssembly.instantiateStreaming(d,a).then(b,function(e){E(`wasm streaming compile failed: ${e}`);E("falling back to ArrayBuffer instantiation");return bb(c,a,b)}))}
var G,H,db={319105:a=>{a=I(a);throw Error("Failed to reconfigure RecognizerRunner due to following error: "+a);},319241:(a,b,c,d)=>{a=I(a);b=I(b);c=I(c);d=I(d);throw Error(a+b+c+d);},319457:(a,b)=>{a=I(a);b=I(b);throw Error(a+b);},319567:()=>{throw Error("Ping Proxy permission not found in license!",{cause:"PERMISSION_NOT_GRANTED"});},319670:a=>{throw Error(I(a));},319713:()=>{throw Error("Unable to perform that operation while recognizer is in use!");},319796:()=>{throw Error("Unable to perform that operation while recognizer is in use!");
},319879:()=>{throw Error("Unable to perform that operation while recognizer is in use!");}};function eb(a){this.name="ExitStatus";this.message=`Program terminated with exit(${a})`;this.status=a}
var fb=a=>{a.terminate();a.onmessage=()=>{}},hb=a=>{0==M.Eb.length&&(gb(),M.Ec(M.Eb[0]));var b=M.Eb.pop();if(!b)return 6;M.Ib.push(b);M.yb[a.Hb]=b;b.Hb=a.Hb;b.postMessage({cmd:"run",start_routine:a.Fd,arg:a.Wc,pthread_ptr:a.Hb},a.Kd);return 0},N=0,kb=a=>{var b=ib();a=a();jb(b);return a},lb=(a,b)=>b+2097152>>>0<4194305-!!a?(a>>>0)+4294967296*b:NaN;
function O(a,b){var c=arguments.length-2,d=arguments;return kb(()=>{for(var e=mb(8*c),f=e>>3,g=0;g<c;g++){var l=d[2+g];ja()[f+g]=l}return nb(a,c,e,b)})}function ob(a){if(F)return O(0,1,a);Da=a;pb||0<N||(M.Qc(),D.onExit?.(a),Ca=!0);pa(a,new eb(a))}var vb=a=>{Da=a;if(F)throw qb(a),"unwind";if(!(pb||0<N||F)){rb();Ra(Ia);Ma=!1;sb(0);for(var b=0;b<tb.length;b++){var c=tb[b];c&&ub(c)}M.Qc();Ka=!0}ob(a)};function wb(){M.receiveObjectTransfer=M.zd;M.threadInitTLS=M.Rc;M.setExitStatus=M.Pc;pb=!1}
function xb(){for(var a=navigator.hardwareConcurrency;a--;)gb();Ga.unshift(()=>{Va("loading-workers");yb(()=>Wa("loading-workers"))})}function gb(){var a=ua("BlinkIDWasmSDK.worker.js");a=new Worker(a);M.Eb.push(a)}function yb(a){F?a():Promise.all(M.Eb.map(M.Ec)).then(a)}
var M={Eb:[],Ib:[],Sc:[],yb:{},Pc:a=>Da=a,Zd:["$terminateWorker"],Qc:()=>{for(var a of M.Ib)fb(a);for(a of M.Eb)fb(a);M.Eb=[];M.Ib=[];M.yb=[]},Nc:a=>{var b=a.Hb;delete M.yb[b];M.Eb.push(a);M.Ib.splice(M.Ib.indexOf(a),1);a.Hb=0;zb(b)},zd(){},Rc(){M.Sc.forEach(a=>a())},Ec:a=>new Promise(b=>{a.onmessage=f=>{f=f.data;var g=f.cmd;if(f.targetThread&&f.targetThread!=Ab()){var l=M.yb[f.targetThread];l?l.postMessage(f,f.transferList):E(`Internal error! Worker sent a message "${g}" to target pthread ${f.targetThread}, but that thread no longer exists!`)}else if("checkMailbox"===
g)Bb();else if("spawnThread"===g)hb(f);else if("cleanupThread"===g)M.Nc(M.yb[f.thread]);else if("killThread"===g)f=f.thread,g=M.yb[f],delete M.yb[f],fb(g),zb(f),M.Ib.splice(M.Ib.indexOf(g),1),g.Hb=0;else if("cancelThread"===g)M.yb[f.thread].postMessage({cmd:"cancel"});else if("loaded"===g)a.loaded=!0,b(a);else if("alert"===g)alert(`Thread ${f.threadId}: ${f.text}`);else if("setimmediate"===f.target)a.postMessage(f);else if("callHandler"===g)D[f.handler](...f.args);else g&&E(`worker sent an unknown command ${g}`)};
a.onerror=f=>{E(`${"worker sent an error!"} ${f.filename}:${f.lineno}: ${f.message}`);throw f;};var c=[],d=["onExit","onAbort","print","printErr"],e;for(e of d)D.hasOwnProperty(e)&&c.push(e);a.postMessage({cmd:"load",handlers:c,urlOrBlob:D.mainScriptUrlOrBlob||_scriptDir,wasmMemory:u,wasmModule:Ba})})};D.PThread=M;var Ra=a=>{for(;0<a.length;)a.shift()(D)};D.establishStackSpace=()=>{var a=Ab(),b=B()[a+52>>2];a=B()[a+56>>2];Cb(b,b-a);jb(b)};function qb(a){if(F)return O(1,0,a);vb(a)}
var Db=[],Eb,P=a=>{var b=Db[a];b||(a>=Db.length&&(Db.length=a+1),Db[a]=b=Eb.get(a));return b};D.invokeEntryPoint=(a,b)=>{N=0;a=P(a)(b);pb||0<N?M.Pc(a):Fb(a)};var pb=D.noExitRuntime||!1;function Gb(a,b,c,d){return F?O(2,1,a,b,c,d):Hb(a,b,c,d)}
var Hb=(a,b,c,d)=>{if("undefined"==typeof SharedArrayBuffer)return E("Current environment does not support SharedArrayBuffer, pthreads are not available!"),6;var e=[];if(F&&0===e.length)return Gb(a,b,c,d);a={Fd:c,Hb:a,Wc:d,Kd:e};return F?(a.Td="spawnThread",postMessage(a,e),0):hb(a)},Ib=(a,b)=>{for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a},Jb=a=>{var b="/"===a.charAt(0),c="/"===a.substr(-1);
(a=Ib(a.split("/").filter(d=>!!d),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a},Kb=a=>{var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&=b.substr(0,b.length-1);return a+b},Lb=a=>{if("/"===a)return"/";a=Jb(a);a=a.replace(/\/$/,"");var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)},Mb=()=>{if("object"==typeof crypto&&"function"==typeof crypto.getRandomValues)return a=>(a.set(crypto.getRandomValues(new Uint8Array(a.byteLength))),
a);Aa("initRandomDevice")},Nb=a=>(Nb=Mb())(a);function Ob(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:"/";if("string"!=typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=Ib(a.split("/").filter(d=>!!d),!b).join("/");return(b?"/":"")+a||"."}
var Pb="undefined"!=typeof TextDecoder?new TextDecoder("utf8"):void 0,Qb=(a,b,c)=>{var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.buffer&&Pb)return Pb.decode(a.buffer instanceof SharedArrayBuffer?a.slice(b,c):a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var f=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|f);else{var g=a[b++]&63;e=224==(e&240)?(e&15)<<12|f<<6|g:(e&7)<<18|f<<12|g<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|
e&1023))}}else d+=String.fromCharCode(e)}return d},Rb=[],Sb=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},Q=(a,b,c,d)=>{if(!(0<d))return 0;var e=c;d=c+d-1;for(var f=0;f<a.length;++f){var g=a.charCodeAt(f);if(55296<=g&&57343>=g){var l=a.charCodeAt(++f);g=65536+((g&1023)<<10)|l&1023}if(127>=g){if(c>=d)break;b[c++]=g}else{if(2047>=g){if(c+1>=d)break;b[c++]=192|g>>6}else{if(65535>=g){if(c+2>=d)break;b[c++]=224|g>>12}else{if(c+
3>=d)break;b[c++]=240|g>>18;b[c++]=128|g>>12&63}b[c++]=128|g>>6&63}b[c++]=128|g&63}}b[c]=0;return c-e};function Tb(a,b){var c=Array(Sb(a)+1);a=Q(a,c,0,c.length);b&&(c.length=a);return c}var Ub=[];function Vb(a,b){Ub[a]={input:[],pb:[],Cb:b};Wb(a,Xb)}
var Xb={open(a){var b=Ub[a.node.Ub];if(!b)throw new R(43);a.kb=b;a.seekable=!1},close(a){a.kb.Cb.$b(a.kb)},$b(a){a.kb.Cb.$b(a.kb)},read(a,b,c,d){if(!a.kb||!a.kb.Cb.Cc)throw new R(60);for(var e=0,f=0;f<d;f++){try{var g=a.kb.Cb.Cc(a.kb)}catch(l){throw new R(29);}if(void 0===g&&0===e)throw new R(6);if(null===g||void 0===g)break;e++;b[c+f]=g}e&&(a.node.timestamp=Date.now());return e},write(a,b,c,d){if(!a.kb||!a.kb.Cb.qc)throw new R(60);try{for(var e=0;e<d;e++)a.kb.Cb.qc(a.kb,b[c+e])}catch(f){throw new R(29);
}d&&(a.node.timestamp=Date.now());return e}},Yb={Cc(){a:{if(!Rb.length){var a=null;"undefined"!=typeof window&&"function"==typeof window.prompt?(a=window.prompt("Input: "),null!==a&&(a+="\n")):"function"==typeof readline&&(a=readline(),null!==a&&(a+="\n"));if(!a){a=null;break a}Rb=Tb(a,!0)}a=Rb.shift()}return a},qc(a,b){null===b||10===b?(ya(Qb(a.pb,0)),a.pb=[]):0!=b&&a.pb.push(b)},$b(a){a.pb&&0<a.pb.length&&(ya(Qb(a.pb,0)),a.pb=[])},od(){return{Qd:25856,Sd:5,Pd:191,Rd:35387,Od:[3,28,127,21,4,0,1,
0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]}},pd(){return 0},qd(){return[24,80]}},Zb={qc(a,b){null===b||10===b?(E(Qb(a.pb,0)),a.pb=[]):0!=b&&a.pb.push(b)},$b(a){a.pb&&0<a.pb.length&&(E(Qb(a.pb,0)),a.pb=[])}},ac=a=>{a=65536*Math.ceil(a/65536);var b=$b(65536,a);b?v().fill(0,b,b+a):b=0;return b};function bc(a,b){var c=a.fb?a.fb.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)>>>0),0!=c&&(b=Math.max(b,256)),c=a.fb,a.fb=new Uint8Array(b),0<a.lb&&a.fb.set(c.subarray(0,a.lb),0))}
var S={xb:null,Bb(){return S.createNode(null,"/",16895,0)},createNode(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new R(63);S.xb||(S.xb={dir:{node:{wb:S.gb.wb,tb:S.gb.tb,Qb:S.gb.Qb,dc:S.gb.dc,Lc:S.gb.Lc,kc:S.gb.kc,Oc:S.gb.Oc,Jc:S.gb.Jc,hc:S.gb.hc},stream:{Gb:S.hb.Gb}},file:{node:{wb:S.gb.wb,tb:S.gb.tb},stream:{Gb:S.hb.Gb,read:S.hb.read,write:S.hb.write,Pb:S.hb.Pb,Rb:S.hb.Rb,ec:S.hb.ec}},link:{node:{wb:S.gb.wb,tb:S.gb.tb,Vb:S.gb.Vb},stream:{}},xc:{node:{wb:S.gb.wb,tb:S.gb.tb},stream:cc}});
c=dc(a,b,c,d);ec(c.mode)?(c.gb=S.xb.dir.node,c.hb=S.xb.dir.stream,c.fb={}):32768===(c.mode&61440)?(c.gb=S.xb.file.node,c.hb=S.xb.file.stream,c.lb=0,c.fb=null):40960===(c.mode&61440)?(c.gb=S.xb.link.node,c.hb=S.xb.link.stream):8192===(c.mode&61440)&&(c.gb=S.xb.xc.node,c.hb=S.xb.xc.stream);c.timestamp=Date.now();a&&(a.fb[b]=c,a.timestamp=c.timestamp);return c},Vd(a){return a.fb?a.fb.subarray?a.fb.subarray(0,a.lb):new Uint8Array(a.fb):new Uint8Array(0)},gb:{wb(a){var b={};b.dd=8192===(a.mode&61440)?
a.id:1;b.Dc=a.id;b.mode=a.mode;b.vd=1;b.uid=0;b.ld=0;b.Ub=a.Ub;b.size=ec(a.mode)?4096:32768===(a.mode&61440)?a.lb:40960===(a.mode&61440)?a.link.length:0;b.Xc=new Date(a.timestamp);b.ud=new Date(a.timestamp);b.bd=new Date(a.timestamp);b.Yc=4096;b.Zc=Math.ceil(b.size/b.Yc);return b},tb(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);if(void 0!==b.size&&(b=b.size,a.lb!=b))if(0==b)a.fb=null,a.lb=0;else{var c=a.fb;a.fb=new Uint8Array(b);c&&a.fb.set(c.subarray(0,Math.min(b,
a.lb)));a.lb=b}},Qb(){throw fc[44];},dc(a,b,c,d){return S.createNode(a,b,c,d)},Lc(a,b,c){if(ec(a.mode)){try{var d=gc(b,c)}catch(f){}if(d)for(var e in d.fb)throw new R(55);}delete a.parent.fb[a.name];a.parent.timestamp=Date.now();a.name=c;b.fb[c]=a;b.timestamp=a.parent.timestamp;a.parent=b},kc(a,b){delete a.fb[b];a.timestamp=Date.now()},Oc(a,b){var c=gc(a,b),d;for(d in c.fb)throw new R(55);delete a.fb[b];a.timestamp=Date.now()},Jc(a){var b=[".",".."],c;for(c of Object.keys(a.fb))b.push(c);return b},
hc(a,b,c){a=S.createNode(a,b,41471,0);a.link=c;return a},Vb(a){if(40960!==(a.mode&61440))throw new R(28);return a.link}},hb:{read(a,b,c,d,e){var f=a.node.fb;if(e>=a.node.lb)return 0;a=Math.min(a.node.lb-e,d);if(8<a&&f.subarray)b.set(f.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=f[e+d];return a},write(a,b,c,d,e,f){b.buffer===h().buffer&&(f=!1);if(!d)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&(!a.fb||a.fb.subarray)){if(f)return a.fb=b.subarray(c,c+d),a.lb=d;if(0===a.lb&&0===e)return a.fb=
b.slice(c,c+d),a.lb=d;if(e+d<=a.lb)return a.fb.set(b.subarray(c,c+d),e),d}bc(a,e+d);if(a.fb.subarray&&b.subarray)a.fb.set(b.subarray(c,c+d),e);else for(f=0;f<d;f++)a.fb[e+f]=b[c+f];a.lb=Math.max(a.lb,e+d);return d},Gb(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.lb);if(0>b)throw new R(28);return b},Pb(a,b,c){bc(a.node,b+c);a.node.lb=Math.max(a.node.lb,b+c)},Rb(a,b,c,d,e){if(32768!==(a.node.mode&61440))throw new R(43);a=a.node.fb;if(e&2||a.buffer!==h().buffer){if(0<c||
c+b<a.length)a=a.subarray?a.subarray(c,c+b):Array.prototype.slice.call(a,c,c+b);c=!0;b=ac(b);if(!b)throw new R(48);h().set(a,b)}else c=!1,b=a.byteOffset;return{jb:b,rb:c}},ec(a,b,c,d){S.hb.write(a,b,0,d,c,!1);return 0}}},hc=(a,b,c)=>{var d=`al ${a}`;wa(a,e=>{b(new Uint8Array(e));d&&Wa(d)},()=>{if(c)c();else throw`Loading data file "${a}" failed.`;});d&&Va(d)},ic=D.preloadPlugins||[],jc=(a,b,c,d)=>{"undefined"!=typeof Browser&&(F?wb():xb());var e=!1;ic.forEach(f=>{!e&&f.canHandle(b)&&(f.handle(a,b,
c,d),e=!0)});return e},lc=(a,b,c,d,e,f,g,l,m,n)=>{function t(k){function q(w){n?.();l||kc(a,b,w,d,e,m);f?.();Wa(r)}jc(k,p,q,()=>{g?.();Wa(r)})||q(k)}var p=b?Ob(Jb(a+"/"+b)):a,r=`cp ${p}`;Va(r);"string"==typeof c?hc(c,t,g):t(c)},mc=(a,b)=>{var c=0;a&&(c|=365);b&&(c|=146);return c},nc=null,oc={},tb=[],pc=1,qc=null,Qa=!0,R=class{constructor(a){this.name="ErrnoError";this.ob=a}},fc={};
function rc(a,b={}){a=Ob(a);if(!a)return{path:"",node:null};b=Object.assign({Bc:!0,sc:0},b);if(8<b.sc)throw new R(32);a=a.split("/").filter(g=>!!g);for(var c=nc,d="/",e=0;e<a.length;e++){var f=e===a.length-1;if(f&&b.parent)break;c=gc(c,a[e]);d=Jb(d+"/"+a[e]);c.Sb&&(!f||f&&b.Bc)&&(c=c.Sb.root);if(!f||b.Zb)for(f=0;40960===(c.mode&61440);)if(c=sc(d),d=Ob(Kb(d),c),c=rc(d,{sc:b.sc+1}).node,40<f++)throw new R(32);}return{path:d,node:c}}
function tc(a){for(var b;;){if(a===a.parent)return a=a.Bb.Gc,b?"/"!==a[a.length-1]?`${a}/${b}`:a+b:a;b=b?`${a.name}/${b}`:a.name;a=a.parent}}function uc(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%qc.length}function gc(a,b){var c=ec(a.mode)?(c=vc(a,"x"))?c:a.gb.Qb?0:2:54;if(c)throw new R(c);for(c=qc[uc(a.id,b)];c;c=c.Ob){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.gb.Qb(a,b)}
function dc(a,b,c,d){a=new wc(a,b,c,d);b=uc(a.parent.id,a.name);a.Ob=qc[b];return qc[b]=a}function ec(a){return 16384===(a&61440)}function xc(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}function vc(a,b){if(Qa)return 0;if(!b.includes("r")||a.mode&292){if(b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73))return 2}else return 2;return 0}function yc(a,b){try{return gc(a,b),20}catch(c){}return vc(a,"wx")}function zc(){for(var a=0;4096>=a;a++)if(!tb[a])return a;throw new R(33);}
function Ac(a){a=tb[a];if(!a)throw new R(8);return a}function Bc(a,b=-1){Cc||(Cc=function(){this.fc={}},Cc.prototype={},Object.defineProperties(Cc.prototype,{object:{get(){return this.node},set(c){this.node=c}},flags:{get(){return this.fc.flags},set(c){this.fc.flags=c}},position:{get(){return this.fc.position},set(c){this.fc.position=c}}}));a=Object.assign(new Cc,a);-1==b&&(b=zc());a.Db=b;return tb[b]=a}var cc={open(a){a.hb=oc[a.node.Ub].hb;a.hb.open?.(a)},Gb(){throw new R(70);}};
function Wb(a,b){oc[a]={hb:b}}function Dc(a,b){var c="/"===b;if(c&&nc)throw new R(10);if(!c&&b){var d=rc(b,{Bc:!1});b=d.path;d=d.node;if(d.Sb)throw new R(10);if(!ec(d.mode))throw new R(54);}b={type:a,Yd:{},Gc:b,td:[]};a=a.Bb(b);a.Bb=b;b.root=a;c?nc=a:d&&(d.Sb=b,d.Bb&&d.Bb.td.push(b))}function Ec(a,b,c){var d=rc(a,{parent:!0}).node;a=Lb(a);if(!a||"."===a||".."===a)throw new R(28);var e=yc(d,a);if(e)throw new R(e);if(!d.gb.dc)throw new R(63);return d.gb.dc(d,a,b,c)}
function Fc(a){return Ec(a,16895,0)}function Gc(a,b,c){"undefined"==typeof c&&(c=b,b=438);return Ec(a,b|8192,c)}function Oa(a,b){if(!Ob(a))throw new R(44);var c=rc(b,{parent:!0}).node;if(!c)throw new R(44);b=Lb(b);var d=yc(c,b);if(d)throw new R(d);if(!c.gb.hc)throw new R(63);c.gb.hc(c,b,a)}
function Hc(a){var b=rc(a,{parent:!0}).node;if(!b)throw new R(44);var c=Lb(a);a=gc(b,c);a:{try{var d=gc(b,c)}catch(f){d=f.ob;break a}var e=vc(b,"wx");d=e?e:ec(d.mode)?31:0}if(d)throw new R(d);if(!b.gb.kc)throw new R(63);if(a.Sb)throw new R(10);b.gb.kc(b,c);b=uc(a.parent.id,a.name);if(qc[b]===a)qc[b]=a.Ob;else for(b=qc[b];b;){if(b.Ob===a){b.Ob=a.Ob;break}b=b.Ob}}function sc(a){a=rc(a).node;if(!a)throw new R(44);if(!a.gb.Vb)throw new R(28);return Ob(tc(a.parent),a.gb.Vb(a))}
function Ic(a,b){a=rc(a,{Zb:!b}).node;if(!a)throw new R(44);if(!a.gb.wb)throw new R(63);return a.gb.wb(a)}function Jc(a){return Ic(a,!0)}function Kc(a,b){a="string"==typeof a?rc(a,{Zb:!0}).node:a;if(!a.gb.tb)throw new R(63);a.gb.tb(a,{mode:b&4095|a.mode&-4096,timestamp:Date.now()})}
function Pa(a,b,c){if(""===a)throw new R(44);if("string"==typeof b){var d={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090}[b];if("undefined"==typeof d)throw Error(`Unknown file open mode: ${b}`);b=d}c=b&64?("undefined"==typeof c?438:c)&4095|32768:0;if("object"==typeof a)var e=a;else{a=Jb(a);try{e=rc(a,{Zb:!(b&131072)}).node}catch(f){}}d=!1;if(b&64)if(e){if(b&128)throw new R(20);}else e=Ec(a,c,0),d=!0;if(!e)throw new R(44);8192===(e.mode&61440)&&(b&=-513);if(b&65536&&!ec(e.mode))throw new R(54);if(!d&&
(c=e?40960===(e.mode&61440)?32:ec(e.mode)&&("r"!==xc(b)||b&512)?31:vc(e,xc(b)):44))throw new R(c);if(b&512&&!d){c=e;c="string"==typeof c?rc(c,{Zb:!0}).node:c;if(!c.gb.tb)throw new R(63);if(ec(c.mode))throw new R(31);if(32768!==(c.mode&61440))throw new R(28);if(d=vc(c,"w"))throw new R(d);c.gb.tb(c,{size:0,timestamp:Date.now()})}b&=-131713;e=Bc({node:e,path:tc(e),flags:b,seekable:!0,position:0,hb:e.hb,Ld:[],error:!1});e.hb.open&&e.hb.open(e);!D.logReadFiles||b&1||(Lc||={},a in Lc||(Lc[a]=1));return e}
function ub(a){if(null===a.Db)throw new R(8);a.nc&&(a.nc=null);try{a.hb.close&&a.hb.close(a)}catch(b){throw b;}finally{tb[a.Db]=null}a.Db=null}function Mc(a,b,c){if(null===a.Db)throw new R(8);if(!a.seekable||!a.hb.Gb)throw new R(70);if(0!=c&&1!=c&&2!=c)throw new R(28);a.position=a.hb.Gb(a,b,c);a.Ld=[]}
function Nc(a,b,c,d,e,f){if(0>d||0>e)throw new R(28);if(null===a.Db)throw new R(8);if(0===(a.flags&2097155))throw new R(8);if(ec(a.node.mode))throw new R(31);if(!a.hb.write)throw new R(28);a.seekable&&a.flags&1024&&Mc(a,0,2);var g="undefined"!=typeof e;if(!g)e=a.position;else if(!a.seekable)throw new R(70);b=a.hb.write(a,b,c,d,e,f);g||(a.position+=b);return b}var Ma;
function Oc(a,b){a="string"==typeof a?a:tc(a);for(b=b.split("/").reverse();b.length;){var c=b.pop();if(c){var d=Jb(a+"/"+c);try{Fc(d)}catch(e){}a=d}}return d}function Pc(a,b,c,d){a=Jb(("string"==typeof a?a:tc(a))+"/"+b);c=mc(c,d);return Ec(a,(void 0!==c?c:438)&4095|32768,0)}
function kc(a,b,c,d,e,f){var g=b;a&&(a="string"==typeof a?a:tc(a),g=b?Jb(a+"/"+b):a);a=mc(d,e);g=Ec(g,(void 0!==a?a:438)&4095|32768,0);if(c){if("string"==typeof c){b=Array(c.length);d=0;for(e=c.length;d<e;++d)b[d]=c.charCodeAt(d);c=b}Kc(g,a|146);b=Pa(g,577);Nc(b,c,0,c.length,0,f);ub(b);Kc(g,a)}}
function Na(a,b,c,d){a=Jb(("string"==typeof a?a:tc(a))+"/"+b);b=mc(!!c,!!d);Na.Fc||(Na.Fc=64);var e=Na.Fc++<<8|0;Wb(e,{open(f){f.seekable=!1},close(){d?.buffer?.length&&d(10)},read(f,g,l,m){for(var n=0,t=0;t<m;t++){try{var p=c()}catch(r){throw new R(29);}if(void 0===p&&0===n)throw new R(6);if(null===p||void 0===p)break;n++;g[l+t]=p}n&&(f.node.timestamp=Date.now());return n},write(f,g,l,m){for(var n=0;n<m;n++)try{d(g[l+n])}catch(t){throw new R(29);}m&&(f.node.timestamp=Date.now());return n}});return Gc(a,
b,e)}function Qc(a){if(!(a.rd||a.sd||a.link||a.fb)){if("undefined"!=typeof XMLHttpRequest)throw Error("Lazy loading should have been performed (contents set) in createLazyFile, but it was not. Lazy loading only works in web workers. Use --embed-file or --preload-file in emcc on the main thread.");if(va)try{a.fb=Tb(va(a.url),!0),a.lb=a.fb.length}catch(b){throw new R(29);}else throw Error("Cannot load without read() or XMLHttpRequest.");}}
function Rc(a,b,c,d,e){function f(){this.pc=!1;this.Yb=[]}function g(p,r,k,q,w){p=p.node.fb;if(w>=p.length)return 0;q=Math.min(p.length-w,q);if(p.slice)for(var z=0;z<q;z++)r[k+z]=p[w+z];else for(z=0;z<q;z++)r[k+z]=p.get(w+z);return q}f.prototype.get=function(p){if(!(p>this.length-1||0>p)){var r=p%this.yc;return this.ac(p/this.yc|0)[r]}};f.prototype.Ad=function(p){this.ac=p};f.prototype.wc=function(){var p=new XMLHttpRequest;p.open("HEAD",c,!1);p.send(null);if(!(200<=p.status&&300>p.status||304===
p.status))throw Error("Couldn't load "+c+". Status: "+p.status);var r=Number(p.getResponseHeader("Content-length")),k,q=(k=p.getResponseHeader("Accept-Ranges"))&&"bytes"===k;p=(k=p.getResponseHeader("Content-Encoding"))&&"gzip"===k;var w=1048576;q||(w=r);var z=this;z.Ad(L=>{var K=L*w,y=(L+1)*w-1;y=Math.min(y,r-1);if("undefined"==typeof z.Yb[L]){var T=z.Yb;if(K>y)throw Error("invalid range ("+K+", "+y+") or no bytes requested!");if(y>r-1)throw Error("only "+r+" bytes available! programmer error!");
var C=new XMLHttpRequest;C.open("GET",c,!1);r!==w&&C.setRequestHeader("Range","bytes="+K+"-"+y);C.responseType="arraybuffer";C.overrideMimeType&&C.overrideMimeType("text/plain; charset=x-user-defined");C.send(null);if(!(200<=C.status&&300>C.status||304===C.status))throw Error("Couldn't load "+c+". Status: "+C.status);K=void 0!==C.response?new Uint8Array(C.response||[]):Tb(C.responseText||"",!0);T[L]=K}if("undefined"==typeof z.Yb[L])throw Error("doXHR failed!");return z.Yb[L]});if(p||!r)w=r=1,w=r=
this.ac(0).length,ya("LazyFiles on gzip forces download of the whole file when length is accessed");this.Uc=r;this.Tc=w;this.pc=!0};if("undefined"!=typeof XMLHttpRequest){if(!ra)throw"Cannot do synchronous binary XHRs outside webworkers in modern browsers. Use --embed-file or --preload-file in emcc";var l=new f;Object.defineProperties(l,{length:{get:function(){this.pc||this.wc();return this.Uc}},yc:{get:function(){this.pc||this.wc();return this.Tc}}});var m=void 0}else m=c,l=void 0;var n=Pc(a,b,d,
e);l?n.fb=l:m&&(n.fb=null,n.url=m);Object.defineProperties(n,{lb:{get:function(){return this.fb.length}}});var t={};Object.keys(n.hb).forEach(p=>{var r=n.hb[p];t[p]=function(){Qc(n);return r.apply(null,arguments)}});t.read=(p,r,k,q,w)=>{Qc(n);return g(p,r,k,q,w)};t.Rb=(p,r,k)=>{Qc(n);var q=ac(r);if(!q)throw new R(48);g(p,h(),q,r,k);return{jb:q,rb:!0}};n.hb=t;return n}var V={},Cc,Lc,I=(a,b)=>a?Qb(v(),a,b):"";
function Sc(a,b,c){if("/"===b.charAt(0))return b;a=-100===a?"/":Ac(a).path;if(0==b.length){if(!c)throw new R(44);return a}return Jb(a+"/"+b)}
function Tc(a,b,c){a=a(b);A()[c>>2]=a.dd;A()[c+4>>2]=a.mode;B()[c+8>>2]=a.vd;A()[c+12>>2]=a.uid;A()[c+16>>2]=a.ld;A()[c+20>>2]=a.Ub;H=[a.size>>>0,(G=a.size,1<=+Math.abs(G)?0<G?+Math.floor(G/4294967296)>>>0:~~+Math.ceil((G-+(~~G>>>0))/4294967296)>>>0:0)];A()[c+24>>2]=H[0];A()[c+28>>2]=H[1];A()[c+32>>2]=4096;A()[c+36>>2]=a.Zc;b=a.Xc.getTime();var d=a.ud.getTime(),e=a.bd.getTime();H=[Math.floor(b/1E3)>>>0,(G=Math.floor(b/1E3),1<=+Math.abs(G)?0<G?+Math.floor(G/4294967296)>>>0:~~+Math.ceil((G-+(~~G>>>
0))/4294967296)>>>0:0)];A()[c+40>>2]=H[0];A()[c+44>>2]=H[1];B()[c+48>>2]=b%1E3*1E3;H=[Math.floor(d/1E3)>>>0,(G=Math.floor(d/1E3),1<=+Math.abs(G)?0<G?+Math.floor(G/4294967296)>>>0:~~+Math.ceil((G-+(~~G>>>0))/4294967296)>>>0:0)];A()[c+56>>2]=H[0];A()[c+60>>2]=H[1];B()[c+64>>2]=d%1E3*1E3;H=[Math.floor(e/1E3)>>>0,(G=Math.floor(e/1E3),1<=+Math.abs(G)?0<G?+Math.floor(G/4294967296)>>>0:~~+Math.ceil((G-+(~~G>>>0))/4294967296)>>>0:0)];A()[c+72>>2]=H[0];A()[c+76>>2]=H[1];B()[c+80>>2]=e%1E3*1E3;H=[a.Dc>>>0,
(G=a.Dc,1<=+Math.abs(G)?0<G?+Math.floor(G/4294967296)>>>0:~~+Math.ceil((G-+(~~G>>>0))/4294967296)>>>0:0)];A()[c+88>>2]=H[0];A()[c+92>>2]=H[1];return 0}var Uc=void 0;function Vc(){var a=A()[+Uc>>2];Uc+=4;return a}
function Wc(a,b,c){if(F)return O(3,1,a,b,c);Uc=c;try{var d=Ac(a);switch(b){case 0:var e=Vc();if(0>e)break;for(;tb[e];)e++;return Bc(d,e).Db;case 1:case 2:return 0;case 3:return d.flags;case 4:return e=Vc(),d.flags|=e,0;case 12:return e=Vc(),da()[e+0>>1]=2,0;case 13:case 14:return 0}return-28}catch(f){if("undefined"==typeof V||"ErrnoError"!==f.name)throw f;return-f.ob}}
function Xc(a,b){if(F)return O(4,1,a,b);try{var c=Ac(a);return Tc(Ic,c.path,b)}catch(d){if("undefined"==typeof V||"ErrnoError"!==d.name)throw d;return-d.ob}}
function Yc(a,b,c){if(F)return O(5,1,a,b,c);Uc=c;try{var d=Ac(a);switch(b){case 21509:return d.kb?0:-59;case 21505:if(!d.kb)return-59;if(d.kb.Cb.od){a=[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0];var e=Vc();A()[e>>2]=25856;A()[e+4>>2]=5;A()[e+8>>2]=191;A()[e+12>>2]=35387;for(var f=0;32>f;f++)h()[e+f+17>>0]=a[f]||0}return 0;case 21510:case 21511:case 21512:return d.kb?0:-59;case 21506:case 21507:case 21508:if(!d.kb)return-59;if(d.kb.Cb.pd)for(e=Vc(),A(),A(),A(),A(),
a=[],f=0;32>f;f++)a.push(h()[e+f+17>>0]);return 0;case 21519:if(!d.kb)return-59;e=Vc();return A()[e>>2]=0;case 21520:return d.kb?-28:-59;case 21531:e=Vc();if(!d.hb.nd)throw new R(59);return d.hb.nd(d,b,e);case 21523:if(!d.kb)return-59;d.kb.Cb.qd&&(f=[24,80],e=Vc(),da()[e>>1]=f[0],da()[e+2>>1]=f[1]);return 0;case 21524:return d.kb?0:-59;case 21515:return d.kb?0:-59;default:return-28}}catch(g){if("undefined"==typeof V||"ErrnoError"!==g.name)throw g;return-g.ob}}
function Zc(a,b){if(F)return O(6,1,a,b);try{return a=I(a),Tc(Jc,a,b)}catch(c){if("undefined"==typeof V||"ErrnoError"!==c.name)throw c;return-c.ob}}function $c(a,b,c,d){if(F)return O(7,1,a,b,c,d);try{b=I(b);var e=d&256;b=Sc(a,b,d&4096);return Tc(e?Jc:Ic,b,c)}catch(f){if("undefined"==typeof V||"ErrnoError"!==f.name)throw f;return-f.ob}}
function ad(a,b,c,d){if(F)return O(8,1,a,b,c,d);Uc=d;try{b=I(b);b=Sc(a,b);var e=d?Vc():0;return Pa(b,c,e).Db}catch(f){if("undefined"==typeof V||"ErrnoError"!==f.name)throw f;return-f.ob}}function bd(a,b){if(F)return O(9,1,a,b);try{return a=I(a),Tc(Ic,a,b)}catch(c){if("undefined"==typeof V||"ErrnoError"!==c.name)throw c;return-c.ob}}var cd={},dd=a=>{for(;a.length;){var b=a.pop();a.pop()(b)}};function ed(a){return this.fromWireType(A()[a>>2])}
var fd={},gd={},hd={},jd,ld=(a,b,c)=>{function d(l){l=c(l);if(l.length!==a.length)throw new jd("Mismatched type converter count");for(var m=0;m<a.length;++m)kd(a[m],l[m])}a.forEach(function(l){hd[l]=b});var e=Array(b.length),f=[],g=0;b.forEach((l,m)=>{gd.hasOwnProperty(l)?e[m]=gd[l]:(f.push(l),fd.hasOwnProperty(l)||(fd[l]=[]),fd[l].push(()=>{e[m]=gd[l];++g;g===f.length&&d(e)}))});0===f.length&&d(e)},md,W=a=>{for(var b="";v()[a];)b+=md[v()[a++]];return b},X;
function nd(a,b,c={}){var d=b.name;if(!a)throw new X(`type "${d}" must have a positive integer typeid pointer`);if(gd.hasOwnProperty(a)){if(c.md)return;throw new X(`Cannot register type '${d}' twice`);}gd[a]=b;delete hd[a];fd.hasOwnProperty(a)&&(b=fd[a],delete fd[a],b.forEach(e=>e()))}function kd(a,b,c={}){if(!("argPackAdvance"in b))throw new TypeError("registerType registeredInstance requires argPackAdvance");return nd(a,b,c)}
var od=a=>{throw new X(a.eb.mb.ib.name+" instance already deleted");},pd=!1,qd=()=>{},rd=(a,b,c)=>{if(b===c)return a;if(void 0===c.sb)return null;a=rd(a,b,c.sb);return null===a?null:c.ed(a)},sd={},td=[],ud=()=>{for(;td.length;){var a=td.pop();a.eb.Mb=!1;a["delete"]()}},vd,wd={},xd=(a,b)=>{if(void 0===b)throw new X("ptr should not be undefined");for(;a.sb;)b=a.Wb(b),a=a.sb;return wd[b]},zd=(a,b)=>{if(!b.mb||!b.jb)throw new jd("makeClassHandle requires ptr and ptrType");if(!!b.ub!==!!b.nb)throw new jd("Both smartPtrType and smartPtr must be specified");
b.count={value:1};return yd(Object.create(a,{eb:{value:b,writable:!0}}))},yd=a=>{if("undefined"===typeof FinalizationRegistry)return yd=b=>b,a;pd=new FinalizationRegistry(b=>{b=b.eb;--b.count.value;0===b.count.value&&(b.nb?b.ub.zb(b.nb):b.mb.ib.zb(b.jb))});yd=b=>{var c=b.eb;c.nb&&pd.register(b,{eb:c},b);return b};qd=b=>{pd.unregister(b)};return yd(a)};function Ad(){}
var Bd=(a,b)=>Object.defineProperty(b,"name",{value:a}),Cd=(a,b,c)=>{if(void 0===a[b].qb){var d=a[b];a[b]=function(){if(!a[b].qb.hasOwnProperty(arguments.length))throw new X(`Function '${c}' called with an invalid number of arguments (${arguments.length}) - expects one of (${a[b].qb})!`);return a[b].qb[arguments.length].apply(this,arguments)};a[b].qb=[];a[b].qb[d.Xb]=d}},Dd=(a,b,c)=>{if(D.hasOwnProperty(a)){if(void 0===c||void 0!==D[a].qb&&void 0!==D[a].qb[c])throw new X(`Cannot register public name '${a}' twice`);
Cd(D,a,a);if(D.hasOwnProperty(c))throw new X(`Cannot register multiple overloads of a function with the same number of arguments (${c})!`);D[a].qb[c]=b}else D[a]=b,void 0!==c&&(D[a].Xd=c)},Ed=a=>{if(void 0===a)return"_unknown";a=a.replace(/[^a-zA-Z0-9_]/g,"$");var b=a.charCodeAt(0);return 48<=b&&57>=b?`_${a}`:a};function Fd(a,b,c,d,e,f,g,l){this.name=a;this.constructor=b;this.Nb=c;this.zb=d;this.sb=e;this.gd=f;this.Wb=g;this.ed=l;this.xd=[]}
var Gd=(a,b,c)=>{for(;b!==c;){if(!b.Wb)throw new X(`Expected null or instance of ${c.name}, got an instance of ${b.name}`);a=b.Wb(a);b=b.sb}return a};function Hd(a,b){if(null===b){if(this.oc)throw new X(`null is not a valid ${this.name}`);return 0}if(!b.eb)throw new X(`Cannot pass "${Id(b)}" as a ${this.name}`);if(!b.eb.jb)throw new X(`Cannot pass deleted object as a pointer of type ${this.name}`);return Gd(b.eb.jb,b.eb.mb.ib,this.ib)}
function Jd(a,b){if(null===b){if(this.oc)throw new X(`null is not a valid ${this.name}`);if(this.cc){var c=this.rc();null!==a&&a.push(this.zb,c);return c}return 0}if(!b||!b.eb)throw new X(`Cannot pass "${Id(b)}" as a ${this.name}`);if(!b.eb.jb)throw new X(`Cannot pass deleted object as a pointer of type ${this.name}`);if(!this.bc&&b.eb.mb.bc)throw new X(`Cannot convert argument of type ${b.eb.ub?b.eb.ub.name:b.eb.mb.name} to parameter type ${this.name}`);c=Gd(b.eb.jb,b.eb.mb.ib,this.ib);if(this.cc){if(void 0===
b.eb.nb)throw new X("Passing raw pointer to smart pointer is illegal");switch(this.Ed){case 0:if(b.eb.ub===this)c=b.eb.nb;else throw new X(`Cannot convert argument of type ${b.eb.ub?b.eb.ub.name:b.eb.mb.name} to parameter type ${this.name}`);break;case 1:c=b.eb.nb;break;case 2:if(b.eb.ub===this)c=b.eb.nb;else{var d=b.clone();c=this.yd(c,Kd(()=>d["delete"]()));null!==a&&a.push(this.zb,c)}break;default:throw new X("Unsupporting sharing policy");}}return c}
function Ld(a,b){if(null===b){if(this.oc)throw new X(`null is not a valid ${this.name}`);return 0}if(!b.eb)throw new X(`Cannot pass "${Id(b)}" as a ${this.name}`);if(!b.eb.jb)throw new X(`Cannot pass deleted object as a pointer of type ${this.name}`);if(b.eb.mb.bc)throw new X(`Cannot convert argument of type ${b.eb.mb.name} to parameter type ${this.name}`);return Gd(b.eb.jb,b.eb.mb.ib,this.ib)}function Md(a){return this.fromWireType(B()[a>>2])}
function Nd(a,b,c,d,e,f,g,l,m,n,t){this.name=a;this.ib=b;this.oc=c;this.bc=d;this.cc=e;this.wd=f;this.Ed=g;this.Ic=l;this.rc=m;this.yd=n;this.zb=t;e||void 0!==b.sb?this.toWireType=Jd:(this.toWireType=d?Hd:Ld,this.vb=null)}
var Od=(a,b,c)=>{if(!D.hasOwnProperty(a))throw new jd("Replacing nonexistant public symbol");void 0!==D[a].qb&&void 0!==c?D[a].qb[c]=b:(D[a]=b,D[a].Xb=c)},Pd=(a,b)=>{var c=[];return function(){c.length=0;Object.assign(c,arguments);if(a.includes("j")){var d=D["dynCall_"+a];d=c&&c.length?d.apply(null,[b].concat(c)):d.call(null,b)}else d=P(b).apply(null,c);return d}},Qd=(a,b)=>{a=W(a);var c=a.includes("j")?Pd(a,b):P(b);if("function"!=typeof c)throw new X(`unknown function pointer with signature ${a}: ${b}`);
return c},Rd,Ud=a=>{a=Sd(a);var b=W(a);Td(a);return b},Vd=(a,b)=>{function c(f){e[f]||gd[f]||(hd[f]?hd[f].forEach(c):(d.push(f),e[f]=!0))}var d=[],e={};b.forEach(c);throw new Rd(`${a}: `+d.map(Ud).join([", "]));},Wd=(a,b)=>{for(var c=[],d=0;d<a;d++)c.push(B()[b+4*d>>2]);return c};function Xd(a){for(var b=1;b<a.length;++b)if(null!==a[b]&&void 0===a[b].vb)return!0;return!1}
function Yd(a,b,c,d,e){var f=b.length;if(2>f)throw new X("argTypes array size mismatch! Must at least get return value and 'this' types!");var g=null!==b[1]&&null!==c,l=Xd(b),m="void"!==b[0].name,n=f-2,t=Array(n),p=[],r=[];return Bd(a,function(){if(arguments.length!==n)throw new X(`function ${a} called with ${arguments.length} arguments, expected ${n}`);r.length=0;p.length=g?2:1;p[0]=e;if(g){var k=b[1].toWireType(r,this);p[1]=k}for(var q=0;q<n;++q)t[q]=b[q+2].toWireType(r,arguments[q]),p.push(t[q]);
q=d.apply(null,p);if(l)dd(r);else for(var w=g?1:2;w<b.length;w++){var z=1===w?k:t[w-2];null!==b[w].vb&&b[w].vb(z)}k=m?b[0].fromWireType(q):void 0;return k})}var Zd=a=>{a=a.trim();const b=a.indexOf("(");return-1!==b?a.substr(0,b):a};class $d{constructor(){this.rb=[void 0];this.mc=[]}get(a){return this.rb[a]}has(a){return void 0!==this.rb[a]}Pb(a){var b=this.mc.pop()||this.rb.length;this.rb[b]=a;return b}}
var ae=new $d,be=a=>{a>=ae.Mc&&0===--ae.get(a).Kc&&(ae.rb[a]=void 0,ae.mc.push(a))},Y=a=>{if(!a)throw new X("Cannot use deleted val. handle = "+a);return ae.get(a).value},Kd=a=>{switch(a){case void 0:return 1;case null:return 2;case !0:return 3;case !1:return 4;default:return ae.Pb({Kc:1,value:a})}},ce={name:"emscripten::val",fromWireType:a=>{var b=Y(a);be(a);return b},toWireType:(a,b)=>Kd(b),argPackAdvance:8,readValueFromPointer:ed,vb:null},Id=a=>{if(null===a)return"null";var b=typeof a;return"object"===
b||"array"===b||"function"===b?a.toString():""+a},de=(a,b)=>{switch(b){case 4:return function(c){var d=this.fromWireType;u.buffer!=aa.buffer&&ba();return d.call(this,Ea[c>>2])};case 8:return function(c){return this.fromWireType(ja()[c>>3])};default:throw new TypeError(`invalid float width (${b}): ${a}`);}},ee=(a,b,c)=>{switch(b){case 1:return c?d=>h()[d>>0]:d=>v()[d>>0];case 2:return c?d=>da()[d>>1]:d=>x()[d>>1];case 4:return c?d=>A()[d>>2]:d=>B()[d>>2];default:throw new TypeError(`invalid integer width (${b}): ${a}`);
}},fe="undefined"!=typeof TextDecoder?new TextDecoder("utf-16le"):void 0,ge=(a,b)=>{var c=a>>1;for(var d=c+b/2;!(c>=d)&&x()[c];)++c;c<<=1;if(32<c-a&&fe)return fe.decode(v().slice(a,c));c="";for(d=0;!(d>=b/2);++d){var e=da()[a+2*d>>1];if(0==e)break;c+=String.fromCharCode(e)}return c},he=(a,b,c)=>{c??=2147483647;if(2>c)return 0;c-=2;var d=b;c=c<2*a.length?c/2:a.length;for(var e=0;e<c;++e){var f=a.charCodeAt(e);da()[b>>1]=f;b+=2}da()[b>>1]=0;return b-d},ie=a=>2*a.length,je=(a,b)=>{for(var c=0,d="";!(c>=
b/4);){var e=A()[a+4*c>>2];if(0==e)break;++c;65536<=e?(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023)):d+=String.fromCharCode(e)}return d},ke=(a,b,c)=>{c??=2147483647;if(4>c)return 0;var d=b;c=d+c-4;for(var e=0;e<a.length;++e){var f=a.charCodeAt(e);if(55296<=f&&57343>=f){var g=a.charCodeAt(++e);f=65536+((f&1023)<<10)|g&1023}A()[b>>2]=f;b+=4;if(b+4>c)break}A()[b>>2]=0;return b-d},le=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&++c;b+=4}return b},me=a=>{if(!Ka&&
!Ca)try{if(a(),!(Ka||pb||0<N))try{F?Fb(Da):vb(Da)}catch(b){b instanceof eb||"unwind"==b||pa(1,b)}}catch(b){b instanceof eb||"unwind"==b||pa(1,b)}},ne=a=>{"function"===typeof Atomics.Nd&&(Atomics.Nd(A(),a>>2,a).value.then(Bb),a+=128,Atomics.store(A(),a>>2,1))};D.__emscripten_thread_mailbox_await=ne;var Bb=()=>{var a=Ab();a&&(ne(a),me(oe))};D.checkMailbox=Bb;
var pe=[],qe=(a,b)=>{var c=gd[a];if(void 0===c)throw a=b+" has unknown type "+Ud(a),new X(a);return c},re=(a,b,c)=>{var d=[];a=a.toWireType(d,c);d.length&&(B()[b>>2]=Kd(d));return a},se=[],te={},ue=a=>{var b=te[a];return void 0===b?W(a):b},ve=()=>{function a(b){b.$$$embind_global$$$=b;var c="object"==typeof $$$embind_global$$$&&b.$$$embind_global$$$==b;c||delete b.$$$embind_global$$$;return c}if("object"==typeof globalThis)return globalThis;if("object"==typeof $$$embind_global$$$)return $$$embind_global$$$;
"object"==typeof global&&a(global)?$$$embind_global$$$=global:"object"==typeof self&&a(self)&&($$$embind_global$$$=self);if("object"==typeof $$$embind_global$$$)return $$$embind_global$$$;throw Error("unable to get global object.");},we=a=>{var b=se.length;se.push(a);return b},xe=(a,b)=>{for(var c=Array(a),d=0;d<a;++d)c[d]=qe(B()[b+4*d>>2],"parameter "+d);return c},ye=Reflect.construct,ze=a=>0===a%4&&(0!==a%100||0===a%400),Ae=[0,31,60,91,121,152,182,213,244,274,305,335],Be=[0,31,59,90,120,151,181,
212,243,273,304,334];function Ce(a,b,c,d,e,f,g,l){if(F)return O(10,1,a,b,c,d,e,f,g,l);e=lb(e,f);try{if(isNaN(e))return 61;var m=Ac(d);if(0!==(b&2)&&0===(c&2)&&2!==(m.flags&2097155))throw new R(2);if(1===(m.flags&2097155))throw new R(2);if(!m.hb.Rb)throw new R(43);var n=m.hb.Rb(m,a,e,b,c);var t=n.jb;A()[g>>2]=n.rb;B()[l>>2]=t;return 0}catch(p){if("undefined"==typeof V||"ErrnoError"!==p.name)throw p;return-p.ob}}
function De(a,b,c,d,e,f,g){if(F)return O(11,1,a,b,c,d,e,f,g);f=lb(f,g);try{if(isNaN(f))return 61;var l=Ac(e);if(c&2){if(32768!==(l.node.mode&61440))throw new R(43);if(!(d&2)){var m=v().slice(a,a+b);l.hb.ec&&l.hb.ec(l,m,f,b,d)}}}catch(n){if("undefined"==typeof V||"ErrnoError"!==n.name)throw n;return-n.ob}}var Fe=a=>{var b=Sb(a)+1,c=Ee(b);c&&Q(a,v(),c,b);return c},Ge=[];
function He(a,b){try{var c=indexedDB.open("emscripten_filesystem",1)}catch(d){b(d);return}c.onupgradeneeded=d=>{d=d.target.result;d.objectStoreNames.contains("FILES")&&d.deleteObjectStore("FILES");d.createObjectStore("FILES")};c.onsuccess=d=>a(d.target.result);c.onerror=b}var Ie,Je;
function Ke(a,b,c,d,e){function f(){var C=0,U=0;y.response&&L&&0===B()[a+12>>2]&&(U=y.response.byteLength);0<U&&(C=Ee(U),v().set(new Uint8Array(y.response),C));B()[a+12>>2]=C;Le(a+16,U);Le(a+24,0);(C=y.response?y.response.byteLength:0)&&Le(a+32,C);x()[a+40>>1]=y.readyState;x()[a+42>>1]=y.status;y.statusText&&(C=a+44,Q(y.statusText,v(),C,64))}var g=B()[a+8>>2];if(g){var l=I(g),m=a+112,n=I(m+0);n||="GET";var t=B()[m+56>>2],p=B()[m+68>>2],r=B()[m+72>>2];g=B()[m+76>>2];var k=B()[m+80>>2],q=B()[m+84>>
2],w=B()[m+88>>2],z=B()[m+52>>2],L=!!(z&1),K=!!(z&2);z=!!(z&64);p=p?I(p):void 0;r=r?I(r):void 0;var y=new XMLHttpRequest;y.withCredentials=!!v()[m+60>>0];y.open(n,l,!z,p,r);z||(y.timeout=t);y.ae=l;y.responseType="arraybuffer";k&&(l=I(k),y.overrideMimeType(l));if(g)for(;;){m=B()[g>>2];if(!m)break;l=B()[g+4>>2];if(!l)break;g+=8;m=I(m);l=I(l);y.setRequestHeader(m,l)}var T=Ie.Pb(y);B()[a>>2]=T;g=q&&w?v().slice(q,q+w):null;y.onload=C=>{Ie.has(T)&&(f(),200<=y.status&&300>y.status?b?.(a,y,C):c?.(a,y,C))};
y.onerror=C=>{Ie.has(T)&&(f(),c?.(a,y,C))};y.ontimeout=C=>{Ie.has(T)&&c?.(a,y,C)};y.onprogress=C=>{if(Ie.has(T)){var U=L&&K&&y.response?y.response.byteLength:0,J=0;0<U&&L&&K&&(J=Ee(U),v().set(new Uint8Array(y.response),J));B()[a+12>>2]=J;Le(a+16,U);Le(a+24,C.loaded-U);Le(a+32,C.total);x()[a+40>>1]=y.readyState;3<=y.readyState&&0===y.status&&0<C.loaded&&(y.status=200);x()[a+42>>1]=y.status;y.statusText&&(U=a+44,Q(y.statusText,v(),U,64));d?.(a,y,C);J&&Td(J)}};y.onreadystatechange=C=>{Ie.has(T)?(x()[a+
40>>1]=y.readyState,2<=y.readyState&&(x()[a+42>>1]=y.status),e?.(a,y,C)):--N};try{y.send(g)}catch(C){c?.(a,y,C)}}else c(a,0,"no url specified!")}var Le=(a,b)=>{B()[a>>2]=b;var c=B()[a>>2];B()[a+4>>2]=(b-c)/4294967296};
function Me(a,b,c,d){var e=Je;if(e){var f=a+112;(f=B()[f+64>>2])||(f=B()[a+8>>2]);var g=I(f);try{var l=e.transaction(["FILES"],"readwrite").objectStore("FILES").put(b,g);l.onsuccess=()=>{x()[a+40>>1]=4;x()[a+42>>1]=200;var m=a+44;Q("OK",v(),m,64);c(a,0,g)};l.onerror=m=>{x()[a+40>>1]=4;x()[a+42>>1]=413;var n=a+44;Q("Payload Too Large",v(),n,64);d(a,0,m)}}catch(m){d(a,0,m)}}else d(a,0,"IndexedDB not available!")}
function Ne(a,b,c){var d=Je;if(d){var e=a+112;(e=B()[e+64>>2])||(e=B()[a+8>>2]);e=I(e);try{var f=d.transaction(["FILES"],"readonly").objectStore("FILES").get(e);f.onsuccess=g=>{if(g.target.result){g=g.target.result;var l=g.byteLength||g.length,m=Ee(l);v().set(new Uint8Array(g),m);B()[a+12>>2]=m;Le(a+16,l);Le(a+24,0);Le(a+32,l);x()[a+40>>1]=4;x()[a+42>>1]=200;l=a+44;Q("OK",v(),l,64);b(a,0,g)}else x()[a+40>>1]=4,x()[a+42>>1]=404,g=a+44,Q("Not Found",v(),g,64),c(a,0,"no data")};f.onerror=g=>{x()[a+40>>
1]=4;x()[a+42>>1]=404;var l=a+44;Q("Not Found",v(),l,64);c(a,0,g)}}catch(g){c(a,0,g)}}else c(a,0,"IndexedDB not available!")}
function Oe(a,b,c){var d=Je;if(d){var e=a+112;(e=B()[e+64>>2])||(e=B()[a+8>>2]);e=I(e);try{var f=d.transaction(["FILES"],"readwrite").objectStore("FILES").delete(e);f.onsuccess=g=>{g=g.target.result;B()[a+12>>2]=0;Le(a+16,0);Le(a+24,0);Le(a+32,0);x()[a+40>>1]=4;x()[a+42>>1]=200;var l=a+44;Q("OK",v(),l,64);b(a,0,g)};f.onerror=g=>{x()[a+40>>1]=4;x()[a+42>>1]=404;var l=a+44;Q("Not Found",v(),l,64);c(a,0,g)}}catch(g){c(a,0,g)}}else c(a,0,"IndexedDB not available!")}
var Pe={},Re=()=>{if(!Qe){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"==typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:oa||"./this.program"},b;for(b in Pe)void 0===Pe[b]?delete a[b]:a[b]=Pe[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);Qe=c}return Qe},Qe;
function Se(a,b){if(F)return O(12,1,a,b);var c=0;Re().forEach((d,e)=>{var f=b+c;e=B()[a+4*e>>2]=f;for(f=0;f<d.length;++f)h()[e++>>0]=d.charCodeAt(f);h()[e>>0]=0;c+=d.length+1});return 0}function Te(a,b){if(F)return O(13,1,a,b);var c=Re();B()[a>>2]=c.length;var d=0;c.forEach(e=>d+=e.length+1);B()[b>>2]=d;return 0}function Ue(a){if(F)return O(14,1,a);try{var b=Ac(a);ub(b);return 0}catch(c){if("undefined"==typeof V||"ErrnoError"!==c.name)throw c;return c.ob}}
function Ve(a,b,c,d){if(F)return O(15,1,a,b,c,d);try{a:{var e=Ac(a);a=b;for(var f,g=b=0;g<c;g++){var l=B()[a>>2],m=B()[a+4>>2];a+=8;var n=e,t=h(),p=f;if(0>m||0>p)throw new R(28);if(null===n.Db)throw new R(8);if(1===(n.flags&2097155))throw new R(8);if(ec(n.node.mode))throw new R(31);if(!n.hb.read)throw new R(28);var r="undefined"!=typeof p;if(!r)p=n.position;else if(!n.seekable)throw new R(70);var k=n.hb.read(n,t,l,m,p);r||(n.position+=k);var q=k;if(0>q){var w=-1;break a}b+=q;if(q<m)break;"undefined"!==
typeof f&&(f+=q)}w=b}B()[d>>2]=w;return 0}catch(z){if("undefined"==typeof V||"ErrnoError"!==z.name)throw z;return z.ob}}
function We(a,b,c,d,e){if(F)return O(16,1,a,b,c,d,e);b=lb(b,c);try{if(isNaN(b))return 61;var f=Ac(a);Mc(f,b,d);H=[f.position>>>0,(G=f.position,1<=+Math.abs(G)?0<G?+Math.floor(G/4294967296)>>>0:~~+Math.ceil((G-+(~~G>>>0))/4294967296)>>>0:0)];A()[e>>2]=H[0];A()[e+4>>2]=H[1];f.nc&&0===b&&0===d&&(f.nc=null);return 0}catch(g){if("undefined"==typeof V||"ErrnoError"!==g.name)throw g;return g.ob}}
function Xe(a,b,c,d){if(F)return O(17,1,a,b,c,d);try{a:{var e=Ac(a);a=b;for(var f,g=b=0;g<c;g++){var l=B()[a>>2],m=B()[a+4>>2];a+=8;var n=Nc(e,h(),l,m,f);if(0>n){var t=-1;break a}b+=n;"undefined"!==typeof f&&(f+=n)}t=b}B()[d>>2]=t;return 0}catch(p){if("undefined"==typeof V||"ErrnoError"!==p.name)throw p;return p.ob}}
var Ye=[31,29,31,30,31,30,31,31,30,31,30,31],Ze=[31,28,31,30,31,30,31,31,30,31,30,31],$e=(a,b)=>{h().set(a,b)},af=(a,b,c,d)=>{function e(k,q,w){for(k="number"==typeof k?k.toString():k||"";k.length<q;)k=w[0]+k;return k}function f(k,q){return e(k,q,"0")}function g(k,q){function w(L){return 0>L?-1:0<L?1:0}var z;0===(z=w(k.getFullYear()-q.getFullYear()))&&0===(z=w(k.getMonth()-q.getMonth()))&&(z=w(k.getDate()-q.getDate()));return z}function l(k){switch(k.getDay()){case 0:return new Date(k.getFullYear()-
1,11,29);case 1:return k;case 2:return new Date(k.getFullYear(),0,3);case 3:return new Date(k.getFullYear(),0,2);case 4:return new Date(k.getFullYear(),0,1);case 5:return new Date(k.getFullYear()-1,11,31);case 6:return new Date(k.getFullYear()-1,11,30)}}function m(k){var q=k.Jb;for(k=new Date((new Date(k.Kb+1900,0,1)).getTime());0<q;){var w=k.getMonth(),z=(ze(k.getFullYear())?Ye:Ze)[w];if(q>z-k.getDate())q-=z-k.getDate()+1,k.setDate(1),11>w?k.setMonth(w+1):(k.setMonth(0),k.setFullYear(k.getFullYear()+
1));else{k.setDate(k.getDate()+q);break}}w=new Date(k.getFullYear()+1,0,4);q=l(new Date(k.getFullYear(),0,4));w=l(w);return 0>=g(q,k)?0>=g(w,k)?k.getFullYear()+1:k.getFullYear():k.getFullYear()-1}var n=B()[d+40>>2];d={Id:A()[d>>2],Hd:A()[d+4>>2],ic:A()[d+8>>2],uc:A()[d+12>>2],jc:A()[d+16>>2],Kb:A()[d+20>>2],Ab:A()[d+24>>2],Jb:A()[d+28>>2],$d:A()[d+32>>2],Gd:A()[d+36>>2],Jd:n?I(n):""};c=I(c);n={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S",
"%x":"%m/%d/%y","%X":"%H:%M:%S","%Ec":"%c","%EC":"%C","%Ex":"%m/%d/%y","%EX":"%H:%M:%S","%Ey":"%y","%EY":"%Y","%Od":"%d","%Oe":"%e","%OH":"%H","%OI":"%I","%Om":"%m","%OM":"%M","%OS":"%S","%Ou":"%u","%OU":"%U","%OV":"%V","%Ow":"%w","%OW":"%W","%Oy":"%y"};for(var t in n)c=c.replace(new RegExp(t,"g"),n[t]);var p="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),r="January February March April May June July August September October November December".split(" ");n={"%a":k=>p[k.Ab].substring(0,
3),"%A":k=>p[k.Ab],"%b":k=>r[k.jc].substring(0,3),"%B":k=>r[k.jc],"%C":k=>f((k.Kb+1900)/100|0,2),"%d":k=>f(k.uc,2),"%e":k=>e(k.uc,2," "),"%g":k=>m(k).toString().substring(2),"%G":m,"%H":k=>f(k.ic,2),"%I":k=>{k=k.ic;0==k?k=12:12<k&&(k-=12);return f(k,2)},"%j":k=>{for(var q=0,w=0;w<=k.jc-1;q+=(ze(k.Kb+1900)?Ye:Ze)[w++]);return f(k.uc+q,3)},"%m":k=>f(k.jc+1,2),"%M":k=>f(k.Hd,2),"%n":()=>"\n","%p":k=>0<=k.ic&&12>k.ic?"AM":"PM","%S":k=>f(k.Id,2),"%t":()=>"\t","%u":k=>k.Ab||7,"%U":k=>f(Math.floor((k.Jb+
7-k.Ab)/7),2),"%V":k=>{var q=Math.floor((k.Jb+7-(k.Ab+6)%7)/7);2>=(k.Ab+371-k.Jb-2)%7&&q++;if(q)53==q&&(w=(k.Ab+371-k.Jb)%7,4==w||3==w&&ze(k.Kb)||(q=1));else{q=52;var w=(k.Ab+7-k.Jb-1)%7;(4==w||5==w&&ze(k.Kb%400-1))&&q++}return f(q,2)},"%w":k=>k.Ab,"%W":k=>f(Math.floor((k.Jb+7-(k.Ab+6)%7)/7),2),"%y":k=>(k.Kb+1900).toString().substring(2),"%Y":k=>k.Kb+1900,"%z":k=>{k=k.Gd;var q=0<=k;k=Math.abs(k)/60;return(q?"+":"-")+String("0000"+(k/60*100+k%60)).slice(-4)},"%Z":k=>k.Jd,"%%":()=>"%"};c=c.replace(/%%/g,
"\x00\x00");for(t in n)c.includes(t)&&(c=c.replace(new RegExp(t,"g"),n[t](d)));c=c.replace(/\0\0/g,"%");t=Tb(c,!1);if(t.length>b)return 0;$e(t,a);return t.length-1};F?wb():xb();function wc(a,b,c,d){a||=this;this.parent=a;this.Bb=a.Bb;this.Sb=null;this.id=pc++;this.name=b;this.mode=c;this.gb={};this.hb={};this.Ub=d}
Object.defineProperties(wc.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}},sd:{get:function(){return ec(this.mode)}},rd:{get:function(){return 8192===(this.mode&61440)}}});[44].forEach(a=>{fc[a]=new R(a);fc[a].stack="<generic error, no stack>"});qc=Array(4096);Dc(S,"/");Fc("/tmp");Fc("/home");Fc("/home/web_user");
(function(){Fc("/dev");Wb(259,{read:()=>0,write:(d,e,f,g)=>g});Gc("/dev/null",259);Vb(1280,Yb);Vb(1536,Zb);Gc("/dev/tty",1280);Gc("/dev/tty1",1536);var a=new Uint8Array(1024),b=0,c=()=>{0===b&&(b=Nb(a).byteLength);return a[--b]};Na("/dev","random",c);Na("/dev","urandom",c);Fc("/dev/shm");Fc("/dev/shm/tmp")})();
(function(){Fc("/proc");var a=Fc("/proc/self");Fc("/proc/self/fd");Dc({Bb(){var b=dc(a,"fd",16895,73);b.gb={Qb(c,d){var e=Ac(+d);c={parent:null,Bb:{Gc:"fake"},gb:{Vb:()=>e.path}};return c.parent=c}};return b}},"/proc/self/fd")})();D.FS_createPath=Oc;D.FS_createDataFile=kc;D.FS_createPreloadedFile=lc;D.FS_unlink=Hc;D.FS_createLazyFile=Rc;D.FS_createDevice=Na;jd=D.InternalError=class extends Error{constructor(a){super(a);this.name="InternalError"}};for(var bf=Array(256),cf=0;256>cf;++cf)bf[cf]=String.fromCharCode(cf);
md=bf;X=D.BindingError=class extends Error{constructor(a){super(a);this.name="BindingError"}};
Object.assign(Ad.prototype,{isAliasOf:function(a){if(!(this instanceof Ad&&a instanceof Ad))return!1;var b=this.eb.mb.ib,c=this.eb.jb;a.eb=a.eb;var d=a.eb.mb.ib;for(a=a.eb.jb;b.sb;)c=b.Wb(c),b=b.sb;for(;d.sb;)a=d.Wb(a),d=d.sb;return b===d&&c===a},clone:function(){this.eb.jb||od(this);if(this.eb.Tb)return this.eb.count.value+=1,this;var a=yd,b=Object,c=b.create,d=Object.getPrototypeOf(this),e=this.eb;a=a(c.call(b,d,{eb:{value:{count:e.count,Mb:e.Mb,Tb:e.Tb,jb:e.jb,mb:e.mb,nb:e.nb,ub:e.ub}}}));a.eb.count.value+=
1;a.eb.Mb=!1;return a},["delete"](){this.eb.jb||od(this);if(this.eb.Mb&&!this.eb.Tb)throw new X("Object already scheduled for deletion");qd(this);var a=this.eb;--a.count.value;0===a.count.value&&(a.nb?a.ub.zb(a.nb):a.mb.ib.zb(a.jb));this.eb.Tb||(this.eb.nb=void 0,this.eb.jb=void 0)},isDeleted:function(){return!this.eb.jb},deleteLater:function(){this.eb.jb||od(this);if(this.eb.Mb&&!this.eb.Tb)throw new X("Object already scheduled for deletion");td.push(this);1===td.length&&vd&&vd(ud);this.eb.Mb=!0;
return this}});D.getInheritedInstanceCount=()=>Object.keys(wd).length;D.getLiveInheritedInstances=()=>{var a=[],b;for(b in wd)wd.hasOwnProperty(b)&&a.push(wd[b]);return a};D.flushPendingDeletes=ud;D.setDelayFunction=a=>{vd=a;td.length&&vd&&vd(ud)};
Object.assign(Nd.prototype,{hd(a){this.Ic&&(a=this.Ic(a));return a},zc(a){this.zb?.(a)},argPackAdvance:8,readValueFromPointer:Md,fromWireType:function(a){function b(){return this.cc?zd(this.ib.Nb,{mb:this.wd,jb:c,ub:this,nb:a}):zd(this.ib.Nb,{mb:this,jb:a})}var c=this.hd(a);if(!c)return this.zc(a),null;var d=xd(this.ib,c);if(void 0!==d){if(0===d.eb.count.value)return d.eb.jb=c,d.eb.nb=a,d.clone();d=d.clone();this.zc(a);return d}d=this.ib.gd(c);d=sd[d];if(!d)return b.call(this);d=this.bc?d.ad:d.pointerType;
var e=rd(c,this.ib,d.ib);return null===e?b.call(this):this.cc?zd(d.ib.Nb,{mb:d,jb:e,ub:this,nb:a}):zd(d.ib.Nb,{mb:d,jb:e})}});Rd=D.UnboundTypeError=((a,b)=>{var c=Bd(b,function(d){this.name=b;this.message=d;d=Error(d).stack;void 0!==d&&(this.stack=this.toString()+"\n"+d.replace(/^Error(:[^\n]*)?\n/,""))});c.prototype=Object.create(a.prototype);c.prototype.constructor=c;c.prototype.toString=function(){return void 0===this.message?this.name:`${this.name}: ${this.message}`};return c})(Error,"UnboundTypeError");
ae.rb.push({value:void 0},{value:null},{value:!0},{value:!1});Object.assign(ae,{Mc:ae.rb.length});D.count_emval_handles=()=>{for(var a=0,b=ae.Mc;b<ae.rb.length;++b)void 0!==ae.rb[b]&&++a;return a};Ie=new $d;F||(Va("library_fetch_init"),He(a=>{Je=a;Wa("library_fetch_init")},()=>{Je=!1;Wa("library_fetch_init")}));
var df=[ob,qb,Gb,Wc,Xc,Yc,Zc,$c,ad,bd,Ce,De,Se,Te,Ue,Ve,We,Xe],mf={ea:a=>{ef(a,!ra,1,!qa,5242880,!1);M.Rc()},B:a=>{F?postMessage({cmd:"cleanupThread",thread:a}):M.Nc(M.yb[a])},aa:Hb,E:Wc,ka:Xc,la:Yc,ia:Zc,ha:$c,F:ad,ja:bd,d:a=>{var b=cd[a];delete cd[a];var c=b.rc,d=b.zb,e=b.Ac,f=e.map(g=>g.kd).concat(e.map(g=>g.Cd));ld([a],f,g=>{var l={};e.forEach((m,n)=>{var t=g[n],p=m.ac,r=m.jd,k=g[n+e.length],q=m.Bd,w=m.Dd;l[m.fd]={read:z=>t.fromWireType(p(r,z)),write:(z,L)=>{var K=[];q(w,z,k.toWireType(K,L));
dd(K)}}});return[{name:b.name,fromWireType:m=>{var n={},t;for(t in l)n[t]=l[t].read(m);d(m);return n},toWireType:(m,n)=>{for(var t in l)if(!(t in n))throw new TypeError(`Missing field: "${t}"`);var p=c();for(t in l)l[t].write(p,n[t]);null!==m&&m.push(d,p);return p},argPackAdvance:8,readValueFromPointer:ed,vb:d}]})},Q:()=>{},qa:(a,b,c,d)=>{b=W(b);kd(a,{name:b,fromWireType:function(e){return!!e},toWireType:function(e,f){return f?c:d},argPackAdvance:8,readValueFromPointer:function(e){return this.fromWireType(v()[e])},
vb:null})},o:(a,b,c,d,e,f,g,l,m,n,t,p,r)=>{t=W(t);f=Qd(e,f);l&&=Qd(g,l);n&&=Qd(m,n);r=Qd(p,r);var k=Ed(t);Dd(k,function(){Vd(`Cannot construct ${t} due to unbound types`,[d])});ld([a,b,c],d?[d]:[],function(q){q=q[0];if(d){var w=q.ib;var z=w.Nb}else z=Ad.prototype;q=Bd(t,function(){if(Object.getPrototypeOf(this)!==L)throw new X("Use 'new' to construct "+t);if(void 0===K.Fb)throw new X(t+" has no accessible constructor");var T=K.Fb[arguments.length];if(void 0===T)throw new X(`Tried to invoke ctor of ${t} with invalid number of parameters (${arguments.length}) - expected (${Object.keys(K.Fb).toString()}) parameters instead!`);
return T.apply(this,arguments)});var L=Object.create(z,{constructor:{value:q}});q.prototype=L;var K=new Fd(t,q,L,r,w,f,l,n);if(K.sb){var y;(y=K.sb).vc??(y.vc=[]);K.sb.vc.push(K)}w=new Nd(t,K,!0,!1,!1);y=new Nd(t+"*",K,!1,!1,!1);z=new Nd(t+" const*",K,!1,!0,!1);sd[a]={pointerType:y,ad:z};Od(k,q);return[w,y,z]})},s:(a,b,c,d,e,f)=>{var g=Wd(b,c);e=Qd(d,e);ld([],[a],function(l){l=l[0];var m=`constructor ${l.name}`;void 0===l.ib.Fb&&(l.ib.Fb=[]);if(void 0!==l.ib.Fb[b-1])throw new X(`Cannot register multiple constructors with identical number of parameters (${b-
1}) for class '${l.name}'! Overload resolution is currently only performed using the parameter count, not actual type info!`);l.ib.Fb[b-1]=()=>{Vd(`Cannot construct ${l.name} due to unbound types`,g)};ld([],g,n=>{n.splice(1,0,null);l.ib.Fb[b-1]=Yd(m,n,null,e,f);return[]});return[]})},h:(a,b,c,d,e,f,g,l)=>{var m=Wd(c,d);b=W(b);b=Zd(b);f=Qd(e,f);ld([],[a],function(n){function t(){Vd(`Cannot call ${p} due to unbound types`,m)}n=n[0];var p=`${n.name}.${b}`;b.startsWith("@@")&&(b=Symbol[b.substring(2)]);
l&&n.ib.xd.push(b);var r=n.ib.Nb,k=r[b];void 0===k||void 0===k.qb&&k.className!==n.name&&k.Xb===c-2?(t.Xb=c-2,t.className=n.name,r[b]=t):(Cd(r,b,p),r[b].qb[c-2]=t);ld([],m,function(q){q=Yd(p,q,n,f,g);void 0===r[b].qb?(q.Xb=c-2,r[b]=q):r[b].qb[c-2]=q;return[]});return[]})},pa:a=>kd(a,ce),H:(a,b,c)=>{b=W(b);kd(a,{name:b,fromWireType:d=>d,toWireType:(d,e)=>e,argPackAdvance:8,readValueFromPointer:de(b,c),vb:null})},x:(a,b,c,d,e,f)=>{var g=Wd(b,c);a=W(a);a=Zd(a);e=Qd(d,e);Dd(a,function(){Vd(`Cannot call ${a} due to unbound types`,
g)},b-1);ld([],g,function(l){Od(a,Yd(a,[l[0],null].concat(l.slice(1)),null,e,f),b-1);return[]})},m:(a,b,c,d,e)=>{b=W(b);-1===e&&(e=4294967295);e=l=>l;if(0===d){var f=32-8*c;e=l=>l<<f>>>f}var g=b.includes("unsigned")?function(l,m){return m>>>0}:function(l,m){return m};kd(a,{name:b,fromWireType:e,toWireType:g,argPackAdvance:8,readValueFromPointer:ee(b,c,0!==d),vb:null})},g:(a,b,c)=>{function d(f){var g=B()[f>>2];f=B()[f+4>>2];return new e(h().buffer,f,g)}var e=[Int8Array,Uint8Array,Int16Array,Uint16Array,
Int32Array,Uint32Array,Float32Array,Float64Array][b];c=W(c);kd(a,{name:c,fromWireType:d,argPackAdvance:8,readValueFromPointer:d},{md:!0})},I:(a,b)=>{b=W(b);var c="std::string"===b;kd(a,{name:b,fromWireType:function(d){var e=B()[d>>2],f=d+4;if(c)for(var g=f,l=0;l<=e;++l){var m=f+l;if(l==e||0==v()[m]){g=I(g,m-g);if(void 0===n)var n=g;else n+=String.fromCharCode(0),n+=g;g=m+1}}else{n=Array(e);for(l=0;l<e;++l)n[l]=String.fromCharCode(v()[f+l]);n=n.join("")}Td(d);return n},toWireType:function(d,e){e instanceof
ArrayBuffer&&(e=new Uint8Array(e));var f="string"==typeof e;if(!(f||e instanceof Uint8Array||e instanceof Uint8ClampedArray||e instanceof Int8Array))throw new X("Cannot pass non-string to std::string");var g=c&&f?Sb(e):e.length;var l=Ee(4+g+1),m=l+4;B()[l>>2]=g;if(c&&f)g+=1,Q(e,v(),m,g);else if(f)for(f=0;f<g;++f){var n=e.charCodeAt(f);if(255<n)throw Td(m),new X("String has UTF-16 code units that do not fit in 8 bits");v()[m+f]=n}else for(f=0;f<g;++f)v()[m+f]=e[f];null!==d&&d.push(Td,l);return l},
argPackAdvance:8,readValueFromPointer:Md,vb(d){Td(d)}})},v:(a,b,c)=>{c=W(c);if(2===b){var d=ge;var e=he;var f=ie;var g=()=>x();var l=1}else 4===b&&(d=je,e=ke,f=le,g=()=>B(),l=2);kd(a,{name:c,fromWireType:m=>{for(var n=B()[m>>2],t=g(),p,r=m+4,k=0;k<=n;++k){var q=m+4+k*b;if(k==n||0==t[q>>l])r=d(r,q-r),void 0===p?p=r:(p+=String.fromCharCode(0),p+=r),r=q+b}Td(m);return p},toWireType:(m,n)=>{if("string"!=typeof n)throw new X(`Cannot pass non-string to C++ string type ${c}`);var t=f(n),p=Ee(4+t+b);B()[p>>
2]=t>>l;e(n,p+4,t+b);null!==m&&m.push(Td,p);return p},argPackAdvance:8,readValueFromPointer:ed,vb(m){Td(m)}})},e:(a,b,c,d,e,f)=>{cd[a]={name:W(b),rc:Qd(c,d),zb:Qd(e,f),Ac:[]}},c:(a,b,c,d,e,f,g,l,m,n)=>{cd[a].Ac.push({fd:W(b),kd:c,ac:Qd(d,e),jd:f,Cd:g,Bd:Qd(l,m),Dd:n})},ra:(a,b)=>{b=W(b);kd(a,{Wd:!0,name:b,argPackAdvance:0,fromWireType:()=>{},toWireType:()=>{}})},sa:function(a){if(Ie.has(a)){var b=Ie.get(a),c=Ie;c.rb[a]=void 0;c.mc.push(a);0<b.readyState&&4>b.readyState&&b.abort()}},oa:()=>1,_:(a,
b)=>{a==b?setTimeout(Bb):F?postMessage({targetThread:a,cmd:"checkMailbox"}):(a=M.yb[a])&&a.postMessage({cmd:"checkMailbox"})},ba:(a,b,c,d)=>{pe.length=c;d>>=3;for(var e=0;e<c;e++)pe[e]=ja()[d+e];a=0>a?db[-a-1]:df[a];M.cd=b;b=a.apply(null,pe);M.cd=0;return b},da:ne,na:()=>{},U:()=>{throw Infinity;},j:(a,b,c)=>{a=Y(a);b=qe(b,"emval::as");return re(b,c,a)},p:(a,b,c,d)=>{a=se[a];b=Y(b);return a(null,b,c,d)},q:(a,b,c,d,e)=>{a=se[a];b=Y(b);c=ue(c);return a(b,b[c],d,e)},V:be,K:(a,b)=>{a=Y(a);b=Y(b);return a==
b},ya:a=>{if(0===a)return Kd(ve());a=ue(a);return Kd(ve()[a])},k:(a,b,c)=>{var d=xe(a,b),e=d.shift();a--;var f=Array(a);b=`methodCaller<(${d.map(g=>g.name).join(", ")}) => ${e.name}>`;return we(Bd(b,(g,l,m,n)=>{for(var t=0,p=0;p<a;++p)f[p]=d[p].readValueFromPointer(n+t),t+=d[p].argPackAdvance;g=1===c?ye(l,f):l.apply(g,f);return re(e,m,g)}))},y:(a,b)=>{a=Y(a);b=Y(b);return Kd(a[b])},r:a=>{4<a&&(ae.get(a).Kc+=1)},za:(a,b)=>{a=Y(a);b=Y(b);return a instanceof b},Aa:()=>Kd([]),xa:a=>Kd(ue(a)),ca:()=>Kd({}),
Ba:a=>{var b=Y(a);dd(b);be(a)},f:(a,b,c)=>{a=Y(a);b=Y(b);c=Y(c);a[b]=c},i:(a,b)=>{a=qe(a,"_emval_take_value");a=a.readValueFromPointer(b);return Kd(a)},wa:a=>{a=Y(a);return Kd(typeof a)},N:function(a,b,c){a=new Date(1E3*lb(a,b));A()[c>>2]=a.getSeconds();A()[c+4>>2]=a.getMinutes();A()[c+8>>2]=a.getHours();A()[c+12>>2]=a.getDate();A()[c+16>>2]=a.getMonth();A()[c+20>>2]=a.getFullYear()-1900;A()[c+24>>2]=a.getDay();b=(ze(a.getFullYear())?Ae:Be)[a.getMonth()]+a.getDate()-1|0;A()[c+28>>2]=b;A()[c+36>>2]=
-(60*a.getTimezoneOffset());b=(new Date(a.getFullYear(),6,1)).getTimezoneOffset();var d=(new Date(a.getFullYear(),0,1)).getTimezoneOffset();a=(b!=d&&a.getTimezoneOffset()==Math.min(d,b))|0;A()[c+32>>2]=a},O:function(a){var b=new Date(A()[a+20>>2]+1900,A()[a+16>>2],A()[a+12>>2],A()[a+8>>2],A()[a+4>>2],A()[a>>2],0),c=A()[a+32>>2],d=b.getTimezoneOffset(),e=(new Date(b.getFullYear(),6,1)).getTimezoneOffset(),f=(new Date(b.getFullYear(),0,1)).getTimezoneOffset(),g=Math.min(f,e);0>c?A()[a+32>>2]=Number(e!=
f&&g==d):0<c!=(g==d)&&(e=Math.max(f,e),b.setTime(b.getTime()+6E4*((0<c?g:e)-d)));A()[a+24>>2]=b.getDay();c=(ze(b.getFullYear())?Ae:Be)[b.getMonth()]+b.getDate()-1|0;A()[a+28>>2]=c;A()[a>>2]=b.getSeconds();A()[a+4>>2]=b.getMinutes();A()[a+8>>2]=b.getHours();A()[a+12>>2]=b.getDate();A()[a+16>>2]=b.getMonth();A()[a+20>>2]=b.getYear();a=b.getTime();a=isNaN(a)?-1:a/1E3;return ff((G=a,1<=+Math.abs(G)?0<G?+Math.floor(G/4294967296)>>>0:~~+Math.ceil((G-+(~~G>>>0))/4294967296)>>>0:0)),a>>>0},L:Ce,M:De,Z:(a,
b,c)=>{function d(n){return(n=n.toTimeString().match(/\(([A-Za-z ]+)\)$/))?n[1]:"GMT"}var e=(new Date).getFullYear(),f=new Date(e,0,1),g=new Date(e,6,1);e=f.getTimezoneOffset();var l=g.getTimezoneOffset(),m=Math.max(e,l);B()[a>>2]=60*m;A()[b>>2]=Number(e!=l);a=d(f);b=d(g);a=Fe(a);b=Fe(b);l<e?(B()[c>>2]=a,B()[c+4>>2]=b):(B()[c>>2]=b,B()[c+4>>2]=a)},b:()=>{Aa("")},z:function(){var a=D.allowedThreads;return a?a:navigator.hardwareConcurrency},n:(a,b,c)=>{Ge.length=0;for(var d;d=v()[b++];){var e=105!=
d;e&=112!=d;c+=e&&c%8?4:0;Ge.push(112==d?B()[c>>2]:105==d?A()[c>>2]:ja()[c>>3]);c+=e?8:4}return db[a].apply(null,Ge)},C:()=>{},G:()=>Date.now(),ma:()=>{N+=1;throw"unwind";},$:()=>2147483648,l:()=>performance.timeOrigin+performance.now(),J:()=>"undefined"!=typeof SharedArrayBuffer,Y:a=>{var b=v().length;a>>>=0;if(a<=b||2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=Math,e=Math.max(a,b+2097152/c);a:{d=(d.min.call(d,2147483648,e+(65536-e%65536)%65536)-u.buffer.byteLength+65535)/65536;try{u.grow(d);
ba();var f=1;break a}catch(g){}f=void 0}if(f)return!0}return!1},ta:function(a,b,c,d,e){function f(J){r?J():me(J)}N+=1;var g=a+112,l=B()[g+36>>2],m=B()[g+40>>2],n=B()[g+44>>2],t=B()[g+48>>2],p=B()[g+52>>2],r=!!(p&64),k=J=>{--N;f(()=>{l?P(l)(J):b?.(J)})},q=J=>{f(()=>{n?P(n)(J):d?.(J)})},w=J=>{--N;f(()=>{m?P(m)(J):c?.(J)})},z=J=>{f(()=>{t?P(t)(J):e?.(J)})},L=J=>{Ke(J,k,w,q,z)},K=(J,kf)=>{Me(J,kf.response,ab=>{--N;f(()=>{l?P(l)(ab):b?.(ab)})},ab=>{--N;f(()=>{l?P(l)(ab):b?.(ab)})})},y=J=>{Ke(J,K,w,q,z)},
T=I(g+0),C=!!(p&16),U=!!(p&4);p=!!(p&32);if("EM_IDB_STORE"===T)L=B()[g+84>>2],g=B()[g+88>>2],Me(a,v().slice(L,L+g),k,w);else if("EM_IDB_DELETE"===T)Oe(a,k,w);else if(C){if(p)return 0;Ke(a,U?K:k,w,q,z)}else Ne(a,k,p?w:U?y:L);return a},fa:Se,ga:Te,w:vb,u:Ue,D:Ve,P:We,t:Xe,ua:function(){var a=stackTrace(),b=Sb(a)+1,c=Ee(b);Q(a,v(),c,b);return c},W:(a,b)=>{Nb(v().subarray(a,a+b));return 0},R:gf,A:hf,S:jf,T:lf,a:u||D.wasmMemory,va:af,X:(a,b,c,d)=>af(a,b,c,d)},Z=function(){function a(c,d){Z=c.exports;M.Sc.push(Z.Ha);
Eb=Z.La;Ha.unshift(Z.Ca);Ba=d;Wa("wasm-instantiate");return Z}var b={a:mf};Va("wasm-instantiate");if(D.instantiateWasm)try{return D.instantiateWasm(b,a)}catch(c){E(`Module.instantiateWasm callback failed with error: ${c}`),ma(c)}cb(b,function(c){a(c.instance,c.module)}).catch(ma);return{}}(),Td=a=>(Td=Z.Da)(a),Ee=a=>(Ee=Z.Ea)(a),Ab=D._pthread_self=()=>(Ab=D._pthread_self=Z.Fa)(),sb=a=>(sb=Z.Ga)(a);D.__emscripten_tls_init=()=>(D.__emscripten_tls_init=Z.Ha)();
var $b=(a,b)=>($b=Z.Ia)(a,b),Sd=a=>(Sd=Z.Ja)(a);D.__embind_initialize_bindings=()=>(D.__embind_initialize_bindings=Z.Ka)();var rb=()=>(rb=Z.Ma)(),ef=D.__emscripten_thread_init=(a,b,c,d,e,f)=>(ef=D.__emscripten_thread_init=Z.Na)(a,b,c,d,e,f);D.__emscripten_thread_crashed=()=>(D.__emscripten_thread_crashed=Z.Oa)();
var nb=(a,b,c,d)=>(nb=Z.Pa)(a,b,c,d),zb=a=>(zb=Z.Qa)(a),Fb=D.__emscripten_thread_exit=a=>(Fb=D.__emscripten_thread_exit=Z.Ra)(a),oe=()=>(oe=Z.Sa)(),nf=(a,b)=>(nf=Z.Ta)(a,b),ff=a=>(ff=Z.Ua)(a),Cb=(a,b)=>(Cb=Z.Va)(a,b),ib=()=>(ib=Z.Wa)(),jb=a=>(jb=Z.Xa)(a),mb=a=>(mb=Z.Ya)(a);D.dynCall_ji=(a,b)=>(D.dynCall_ji=Z.Za)(a,b);D.dynCall_jiji=(a,b,c,d,e)=>(D.dynCall_jiji=Z._a)(a,b,c,d,e);D.dynCall_viijii=(a,b,c,d,e,f,g)=>(D.dynCall_viijii=Z.$a)(a,b,c,d,e,f,g);
D.dynCall_iiiiij=(a,b,c,d,e,f,g)=>(D.dynCall_iiiiij=Z.ab)(a,b,c,d,e,f,g);D.dynCall_iiiiijj=(a,b,c,d,e,f,g,l,m)=>(D.dynCall_iiiiijj=Z.bb)(a,b,c,d,e,f,g,l,m);D.dynCall_iiiiiijj=(a,b,c,d,e,f,g,l,m,n)=>(D.dynCall_iiiiiijj=Z.cb)(a,b,c,d,e,f,g,l,m,n);D.__ZN2MB2NN28LinearDefragmentingAllocator10Allocation4nullE=85152;D.___start_em_js=318112;D.___stop_em_js=319105;function hf(a,b){var c=ib();try{P(a)(b)}catch(d){jb(c);if(d!==d+0)throw d;nf(1,0)}}
function lf(a,b,c,d){var e=ib();try{P(a)(b,c,d)}catch(f){jb(e);if(f!==f+0)throw f;nf(1,0)}}function jf(a,b,c){var d=ib();try{P(a)(b,c)}catch(e){jb(d);if(e!==e+0)throw e;nf(1,0)}}function gf(a,b,c,d){var e=ib();try{return P(a)(b,c,d)}catch(f){jb(e);if(f!==f+0)throw f;nf(1,0)}}D.addRunDependency=Va;D.removeRunDependency=Wa;D.FS_createPath=Oc;D.FS_createLazyFile=Rc;D.FS_createDevice=Na;D.wasmMemory=u;D.keepRuntimeAlive=()=>pb||0<N;D.ExitStatus=eb;D.FS_createPreloadedFile=lc;D.FS_createDataFile=kc;
D.FS_unlink=Hc;D.PThread=M;var of;Ua=function pf(){of||qf();of||(Ua=pf)};
function qf(){function a(){if(!of&&(of=!0,D.calledRun=!0,!Ca)){La();la(D);if(D.onRuntimeInitialized)D.onRuntimeInitialized();if(!F){if(D.postRun)for("function"==typeof D.postRun&&(D.postRun=[D.postRun]);D.postRun.length;){var b=D.postRun.shift();Ja.unshift(b)}Ra(Ja)}}}if(!(0<Sa))if(F)la(D),La(),startWorker(D);else{if(D.preRun)for("function"==typeof D.preRun&&(D.preRun=[D.preRun]);D.preRun.length;)Ga.unshift(D.preRun.shift());Ra(Ga);0<Sa||(D.setStatus?(D.setStatus("Running..."),setTimeout(function(){setTimeout(function(){D.setStatus("")},
1);a()},1)):a())}}if(D.preInit)for("function"==typeof D.preInit&&(D.preInit=[D.preInit]);0<D.preInit.length;)D.preInit.pop()();qf();
if("object"==typeof window&&("undefined"==typeof F||!F)){var rf=()=>{var a=0,b=!1,c=m=>{var n=new XMLHttpRequest;n.open("POST","stdio.html",!1);n.send(m);try{window.close()}catch(t){}},d=m=>{var n=new XMLHttpRequest;++a;n.onreadystatechange=()=>{4==n.readyState&&0==--a&&b&&c("^exit^"+Da)};n.open("POST","stdio.html",!0);n.send(m)};if(-1!=document.URL.search("localhost")||-1!=document.URL.search(":6931/")){var e=1,f=ya,g=E;Ia.unshift(()=>{0==a?c("^exit^"+Da):b=!0});ya=m=>{d("^out^"+e++ +"^"+encodeURIComponent(m));
f(m)};E=m=>{d("^err^"+e++ +"^"+encodeURIComponent(m));g(m)};var l=()=>{try{d("^pageload^")}catch(m){setTimeout(l,50)}};l()}};"undefined"!=typeof document&&rf()};


  return moduleArg.ready
}
);
})();
if (typeof exports === 'object' && typeof module === 'object')
  module.exports = BlinkIDWasmSDK;
else if (typeof define === 'function' && define['amd'])
  define([], () => BlinkIDWasmSDK);
