
var BlinkIDWasmSDK = (() => {
  var _scriptDir = typeof document != 'undefined' ? document.currentScript?.src : undefined;
  
  return (
function(moduleArg = {}) {

/*

 Copyright 2019 The Emscripten Authors
 SPDX-License-Identifier: MIT

 Copyright 2024 The Emscripten Authors
 SPDX-License-Identifier: MIT

 Copyright 2013 The Emscripten Authors
 SPDX-License-Identifier: MIT

 This file gets implicatly injected as a `--post-js` file when
 emcc is run with `--emrun`
*/
var k=moduleArg,aa,ba,readyPromise=new Promise((a,b)=>{aa=a;ba=b});k.Ob||(k.Ob=0);k.Ob++;
k.ENVIRONMENT_IS_PTHREAD||k.$ww||function(a){function b(m,n,q){var p=new XMLHttpRequest;p.open("GET",m,!0);p.responseType="arraybuffer";p.onprogress=function(r){var h=n;r.total&&(h=r.total);if(r.loaded){p.rc?k.nb[m].loaded=r.loaded:(p.rc=!0,k.nb||(k.nb={}),k.nb[m]={loaded:r.loaded,total:h});var t=h=r=0,u;for(u in k.nb){var A=k.nb[u];r+=A.total;h+=A.loaded;t++}r=Math.ceil(r*k.Ob/t);k.setStatus&&k.setStatus(`Downloading data... (${h}/${r})`)}else!k.nb&&k.setStatus&&k.setStatus("Downloading data...")};
p.onerror=function(){throw Error("NetworkError for: "+m);};p.onload=function(){if(200==p.status||304==p.status||206==p.status||0==p.status&&p.response)q(p.response);else throw Error(p.statusText+" : "+p.responseURL);};p.send(null)}function c(m){console.error("package error:",m)}function d(){function m(r,h,t){this.start=r;this.end=h;this.audio=t}function n(r){if(!r)throw"Loading data file failed."+Error().stack;if(r.constructor.name!==ArrayBuffer.name)throw"bad input to processPackageData"+Error().stack;
r=new Uint8Array(r);m.prototype.vc=r;r=a.files;for(var h=0;h<r.length;++h)m.prototype.Wb[r[h].filename].onload();k.removeRunDependency("datafile_/opt/jenkins/android-arm64-huawei-p30-pro/root/E0/sdk-blinkid-in-browser/resources/lightweight/advanced/BlinkIDWasmSDK.data")}k.FS_createPath("/","microblink",!0,!0);m.prototype={Wb:{},open:function(r,h){this.name=h;this.Wb[h]=this;k.addRunDependency(`fp ${this.name}`)},send:function(){},onload:function(){this.finish(this.vc.subarray(this.start,this.end))},
finish:function(r){k.FS_createDataFile(this.name,null,r,!0,!0,!0);k.removeRunDependency(`fp ${this.name}`);this.Wb[this.name]=null}};for(var q=a.files,p=0;p<q.length;++p)(new m(q[p].start,q[p].end,q[p].audio||0)).open("GET",q[p].filename);k.addRunDependency("datafile_/opt/jenkins/android-arm64-huawei-p30-pro/root/E0/sdk-blinkid-in-browser/resources/lightweight/advanced/BlinkIDWasmSDK.data");k.mc||(k.mc={});k.mc["/opt/jenkins/android-arm64-huawei-p30-pro/root/E0/sdk-blinkid-in-browser/resources/lightweight/advanced/BlinkIDWasmSDK.data"]=
{jd:!1};l?(n(l),l=null):g=n}"object"===typeof window?window.encodeURIComponent(window.location.pathname.toString().substring(0,window.location.pathname.toString().lastIndexOf("/"))+"/"):"undefined"===typeof process&&"undefined"!==typeof location&&encodeURIComponent(location.pathname.toString().substring(0,location.pathname.toString().lastIndexOf("/"))+"/");"function"!==typeof k.locateFilePackage||k.locateFile||(k.locateFile=k.locateFilePackage,v("warning: you defined Module.locateFilePackage, that has been renamed to Module.locateFile (using your locateFilePackage for now)"));
var e=k.locateFile?k.locateFile("BlinkIDWasmSDK.data",""):"BlinkIDWasmSDK.data",f=a.remote_package_size,g=null,l=k.getPreloadedPackage?k.getPreloadedPackage(e,f):null;l||b(e,f,function(m){g?(g(m),g=null):l=m},c);k.calledRun?d():(k.preRun||(k.preRun=[]),k.preRun.push(d))}({files:[{filename:"/microblink/Model_07c7ab860e77ec2e92bb822f6d62424b8595a5beb4340f6b2f7f6a4cffa5d050.strop",start:0,end:120418},{filename:"/microblink/Model_2880751121560047e6dc571bc8ff4683aeb863886f7c0789234594ceb1e23577.strop",
start:120418,end:124356},{filename:"/microblink/Model_28a32f25173781f9315925a0b1aae79cbe30fcb5971e870d548c0b07f505fa74.strop",start:124356,end:1033542},{filename:"/microblink/Model_36d8e94f4cb46097bd6b7385f2aa91fcdee1a5fefeec59e56d1b9e82c94b00a7.strop",start:1033542,end:1403338},{filename:"/microblink/Model_473ac5f5e256623c0a6b282698c1f1b033b9fb5359e6aa142e9fb4a4022afe4e.strop",start:1403338,end:1410220},{filename:"/microblink/Model_7449c8658cb4f2272b20b3e1e59488558badfb94d78ed9bc37bdaaffe7400078.strop",
start:1410220,end:1994516},{filename:"/microblink/Model_8c7727da554fd257fa758787ca3d0f517b47f6c5ba791792f516da7dd210fde8.strop",start:1994516,end:3103584},{filename:"/microblink/Model_b452fd3cd4037080cfcb4c423dba5bc58c8ceafc28427fdf9c5778fb353f088e.strop",start:3103584,end:3110434},{filename:"/microblink/Model_cf1186bbf6553c03f45bb0918ec5039629b4e4460941a917199f3b8ee0b115be.strop",start:3110434,end:6388670},{filename:"/microblink/Model_d2bcaf18d17504513598e04f472c035b3d4f22d8653d5a79c05b4508a4b547b3.strop",
start:6388670,end:6822186},{filename:"/microblink/Model_dc2c0f42def7aab10489790c240770787f9ef5580a2c4695402237ee9f17d12f.strop",start:6822186,end:6957580},{filename:"/microblink/Model_e4f1f62f68ec44b71ecad3fb3f3b48fe3790beb5ab325611e17d63af06e9f644.strop",start:6957580,end:7014094},{filename:"/microblink/Model_ed586fd6ca47c8eebb513c4ffaaacc2c54e92162b145062d7022519fba0911de.strop",start:7014094,end:7727326},{filename:"/microblink/Model_f2874f5766b779c063dbe30467979163497dc4b29c43bab23d70c798ee32993a.strop",
start:7727326,end:7808832},{filename:"/microblink/Model_faf688599c7e261a2a7404730f69ed029115bb0d3e7a3657731d88e701720efe.strop",start:7808832,end:7825570},{filename:"/microblink/ccc_lookup_table.zzip",start:7825570,end:7846039}],remote_package_size:7846039});k.onAbort=function(a){v("Aborted with message: "+a);try{throw new WebAssembly.RuntimeError(a);}catch(b){v("Stacktrace: "+b.stack)}};
if("object"==typeof window){k.arguments=window.location.search.substr(1).trim().split("&");for(let a=0;a<k.arguments.length;++a)k.arguments[a]=decodeURI(k.arguments[a]);k.arguments[0]||(k.arguments=[])}var ca=Object.assign({},k),da="./this.program",ea=(a,b)=>{throw b;},fa="object"==typeof window,ha="function"==typeof importScripts,ia="",ja,ka,la;
if(fa||ha)ha?ia=self.location.href:"undefined"!=typeof document&&document.currentScript&&(ia=document.currentScript.src),_scriptDir&&(ia=_scriptDir),ia=ia.startsWith("blob:")?"":ia.substr(0,ia.replace(/[?#].*/,"").lastIndexOf("/")+1),ja=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},ha&&(la=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),ka=(a,b,c)=>{var d=new XMLHttpRequest;d.open("GET",
a,!0);d.responseType="arraybuffer";d.onload=()=>{200==d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)};var na=k.print||console.log.bind(console),v=k.printErr||console.error.bind(console);Object.assign(k,ca);ca=null;k.thisProgram&&(da=k.thisProgram);k.quit&&(ea=k.quit);var oa;k.wasmBinary&&(oa=k.wasmBinary);var pa,qa=!1,ra,w,x,y,sa,B,D,ta,ua;
function va(){var a=pa.buffer;k.HEAP8=w=new Int8Array(a);k.HEAP16=y=new Int16Array(a);k.HEAPU8=x=new Uint8Array(a);k.HEAPU16=sa=new Uint16Array(a);k.HEAP32=B=new Int32Array(a);k.HEAPU32=D=new Uint32Array(a);k.HEAPF32=ta=new Float32Array(a);k.HEAPF64=ua=new Float64Array(a)}var wa=k.INITIAL_MEMORY||209715200;pa=k.wasmMemory?k.wasmMemory:new WebAssembly.Memory({initial:wa/65536,maximum:32768});va();wa=pa.buffer.byteLength;var xa=[],ya=[],za=[],Aa=[],Ba=!1;
function Ca(){var a=k.preRun.shift();xa.unshift(a)}var Da=0,Ea=null,Fa=null;function Ga(){Da++;k.monitorRunDependencies?.(Da)}function Ha(){Da--;k.monitorRunDependencies?.(Da);if(0==Da&&(null!==Ea&&(clearInterval(Ea),Ea=null),Fa)){var a=Fa;Fa=null;a()}}function Ia(a){k.onAbort?.(a);a="Aborted("+a+")";v(a);qa=!0;ra=1;a=new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");ba(a);throw a;}var Ja=a=>a.startsWith("data:application/octet-stream;base64,"),Ka;Ka="BlinkIDWasmSDK.wasm";
if(!Ja(Ka)){var La=Ka;Ka=k.locateFile?k.locateFile(La,ia):ia+La}function Ma(a){if(a==Ka&&oa)return new Uint8Array(oa);if(la)return la(a);throw"both async and sync fetching of the wasm failed";}function Na(a){return oa||!fa&&!ha||"function"!=typeof fetch?Promise.resolve().then(()=>Ma(a)):fetch(a,{credentials:"same-origin"}).then(b=>{if(!b.ok)throw`failed to load wasm binary file at '${a}'`;return b.arrayBuffer()}).catch(()=>Ma(a))}
function Oa(a,b,c){return Na(a).then(d=>WebAssembly.instantiate(d,b)).then(c,d=>{v(`failed to asynchronously prepare wasm: ${d}`);Ia(d)})}function Pa(a,b){var c=Ka;return oa||"function"!=typeof WebAssembly.instantiateStreaming||Ja(c)||"function"!=typeof fetch?Oa(c,a,b):fetch(c,{credentials:"same-origin"}).then(d=>WebAssembly.instantiateStreaming(d,a).then(b,function(e){v(`wasm streaming compile failed: ${e}`);v("falling back to ArrayBuffer instantiation");return Oa(c,a,b)}))}
var E,F,Qa={332997:a=>{a=a?G(x,a):"";throw Error("Failed to reconfigure RecognizerRunner due to following error: "+a);},333133:(a,b,c,d)=>{a=a?G(x,a):"";b=b?G(x,b):"";c=c?G(x,c):"";d=d?G(x,d):"";throw Error(a+b+c+d);},333349:(a,b)=>{a=a?G(x,a):"";b=b?G(x,b):"";throw Error(a+b);},333459:()=>{throw Error("Ping Proxy permission not found in license!",{cause:"PERMISSION_NOT_GRANTED"});},333562:a=>{throw Error(a?G(x,a):"");},333605:()=>{throw Error("Unable to perform that operation while recognizer is in use!");
},333688:()=>{throw Error("Unable to perform that operation while recognizer is in use!");},333771:()=>{throw Error("Unable to perform that operation while recognizer is in use!");},333854:(a,b)=>{throw Error(a?G(x,a):"",{cause:b?G(x,b):""});},333928:(a,b)=>{throw Error(a?G(x,a):"",{cause:b?G(x,b):""});},334002:(a,b)=>{throw Error(a?G(x,a):"",{cause:b?G(x,b):""});}};function Ra(a){this.name="ExitStatus";this.message=`Program terminated with exit(${a})`;this.status=a}
var Ta=a=>{for(;0<a.length;)a.shift()(k)},Ua=k.noExitRuntime||!1;function Va(){var a=B[+Wa>>2];Wa+=4;return a}
var Xa=(a,b)=>{for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a},Ya=a=>{var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=Xa(a.split("/").filter(d=>!!d),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a},Za=a=>{var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&=b.substr(0,b.length-1);return a+b},$a=a=>{if("/"===
a)return"/";a=Ya(a);a=a.replace(/\/$/,"");var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)},ab=()=>{if("object"==typeof crypto&&"function"==typeof crypto.getRandomValues)return a=>crypto.getRandomValues(a);Ia("initRandomDevice")},bb=a=>(bb=ab())(a),cb=(...a)=>{for(var b="",c=!1,d=a.length-1;-1<=d&&!c;d--){c=0<=d?a[d]:"/";if("string"!=typeof c)throw new TypeError("Arguments to path.resolve must be strings");if(!c)return"";b=c+"/"+b;c="/"===c.charAt(0)}b=Xa(b.split("/").filter(e=>!!e),!c).join("/");
return(c?"/":"")+b||"."},db="undefined"!=typeof TextDecoder?new TextDecoder("utf8"):void 0,G=(a,b,c)=>{var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.buffer&&db)return db.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var f=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|f);else{var g=a[b++]&63;e=224==(e&240)?(e&15)<<12|f<<6|g:(e&7)<<18|f<<12|g<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d},
eb=[],fb=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},K=(a,b,c,d)=>{if(!(0<d))return 0;var e=c;d=c+d-1;for(var f=0;f<a.length;++f){var g=a.charCodeAt(f);if(55296<=g&&57343>=g){var l=a.charCodeAt(++f);g=65536+((g&1023)<<10)|l&1023}if(127>=g){if(c>=d)break;b[c++]=g}else{if(2047>=g){if(c+1>=d)break;b[c++]=192|g>>6}else{if(65535>=g){if(c+2>=d)break;b[c++]=224|g>>12}else{if(c+3>=d)break;b[c++]=240|g>>18;b[c++]=128|g>>12&
63}b[c++]=128|g>>6&63}b[c++]=128|g&63}}b[c]=0;return c-e};function gb(a,b){var c=Array(fb(a)+1);a=K(a,c,0,c.length);b&&(c.length=a);return c}var hb=[];function ib(a,b){hb[a]={input:[],Ua:[],gb:b};jb(a,kb)}
var kb={open(a){var b=hb[a.node.vb];if(!b)throw new L(43);a.Qa=b;a.seekable=!1},close(a){a.Qa.gb.Cb(a.Qa)},Cb(a){a.Qa.gb.Cb(a.Qa)},read(a,b,c,d){if(!a.Qa||!a.Qa.gb.ic)throw new L(60);for(var e=0,f=0;f<d;f++){try{var g=a.Qa.gb.ic(a.Qa)}catch(l){throw new L(29);}if(void 0===g&&0===e)throw new L(6);if(null===g||void 0===g)break;e++;b[c+f]=g}e&&(a.node.timestamp=Date.now());return e},write(a,b,c,d){if(!a.Qa||!a.Qa.gb.Tb)throw new L(60);try{for(var e=0;e<d;e++)a.Qa.gb.Tb(a.Qa,b[c+e])}catch(f){throw new L(29);
}d&&(a.node.timestamp=Date.now());return e}},lb={ic(){a:{if(!eb.length){var a=null;"undefined"!=typeof window&&"function"==typeof window.prompt?(a=window.prompt("Input: "),null!==a&&(a+="\n")):"function"==typeof readline&&(a=readline(),null!==a&&(a+="\n"));if(!a){a=null;break a}eb=gb(a,!0)}a=eb.shift()}return a},Tb(a,b){null===b||10===b?(na(G(a.Ua,0)),a.Ua=[]):0!=b&&a.Ua.push(b)},Cb(a){a.Ua&&0<a.Ua.length&&(na(G(a.Ua,0)),a.Ua=[])},Ic(){return{ed:25856,gd:5,dd:191,fd:35387,cd:[3,28,127,21,4,0,1,0,
17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]}},Jc(){return 0},Kc(){return[24,80]}},mb={Tb(a,b){null===b||10===b?(v(G(a.Ua,0)),a.Ua=[]):0!=b&&a.Ua.push(b)},Cb(a){a.Ua&&0<a.Ua.length&&(v(G(a.Ua,0)),a.Ua=[])}},ob=a=>{a=65536*Math.ceil(a/65536);var b=nb(65536,a);b?(x.fill(0,b,b+a),a=b):a=0;return a};function pb(a,b){var c=a.La?a.La.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)>>>0),0!=c&&(b=Math.max(b,256)),c=a.La,a.La=new Uint8Array(b),0<a.Ra&&a.La.set(c.subarray(0,a.Ra),0))}
var M={bb:null,fb(){return M.createNode(null,"/",16895,0)},createNode(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new L(63);M.bb||(M.bb={dir:{node:{ab:M.Ma.ab,Ya:M.Ma.Ya,sb:M.Ma.sb,Fb:M.Ma.Fb,pc:M.Ma.pc,Mb:M.Ma.Mb,qc:M.Ma.qc,oc:M.Ma.oc,Jb:M.Ma.Jb},stream:{kb:M.Na.kb}},file:{node:{ab:M.Ma.ab,Ya:M.Ma.Ya},stream:{kb:M.Na.kb,read:M.Na.read,write:M.Na.write,yb:M.Na.yb,Sb:M.Na.Sb,Gb:M.Na.Gb}},link:{node:{ab:M.Ma.ab,Ya:M.Ma.Ya,wb:M.Ma.wb},stream:{}},bc:{node:{ab:M.Ma.ab,Ya:M.Ma.Ya},stream:qb}});
c=rb(a,b,c,d);O(c.mode)?(c.Ma=M.bb.dir.node,c.Na=M.bb.dir.stream,c.La={}):32768===(c.mode&61440)?(c.Ma=M.bb.file.node,c.Na=M.bb.file.stream,c.Ra=0,c.La=null):40960===(c.mode&61440)?(c.Ma=M.bb.link.node,c.Na=M.bb.link.stream):8192===(c.mode&61440)&&(c.Ma=M.bb.bc.node,c.Na=M.bb.bc.stream);c.timestamp=Date.now();a&&(a.La[b]=c,a.timestamp=c.timestamp);return c},kd(a){return a.La?a.La.subarray?a.La.subarray(0,a.Ra):new Uint8Array(a.La):new Uint8Array(0)},Ma:{ab(a){var b={};b.yc=8192===(a.mode&61440)?a.id:
1;b.jc=a.id;b.mode=a.mode;b.Pc=1;b.uid=0;b.Fc=0;b.vb=a.vb;b.size=O(a.mode)?4096:32768===(a.mode&61440)?a.Ra:40960===(a.mode&61440)?a.link.length:0;b.sc=new Date(a.timestamp);b.Oc=new Date(a.timestamp);b.xc=new Date(a.timestamp);b.tc=4096;b.uc=Math.ceil(b.size/b.tc);return b},Ya(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);if(void 0!==b.size&&(b=b.size,a.Ra!=b))if(0==b)a.La=null,a.Ra=0;else{var c=a.La;a.La=new Uint8Array(b);c&&a.La.set(c.subarray(0,Math.min(b,
a.Ra)));a.Ra=b}},sb(){throw sb[44];},Fb(a,b,c,d){return M.createNode(a,b,c,d)},pc(a,b,c){if(O(a.mode)){try{var d=tb(b,c)}catch(f){}if(d)for(var e in d.La)throw new L(55);}delete a.parent.La[a.name];a.parent.timestamp=Date.now();a.name=c;b.La[c]=a;b.timestamp=a.parent.timestamp;a.parent=b},Mb(a,b){delete a.La[b];a.timestamp=Date.now()},qc(a,b){var c=tb(a,b),d;for(d in c.La)throw new L(55);delete a.La[b];a.timestamp=Date.now()},oc(a){var b=[".",".."],c;for(c of Object.keys(a.La))b.push(c);return b},
Jb(a,b,c){a=M.createNode(a,b,41471,0);a.link=c;return a},wb(a){if(40960!==(a.mode&61440))throw new L(28);return a.link}},Na:{read(a,b,c,d,e){var f=a.node.La;if(e>=a.node.Ra)return 0;a=Math.min(a.node.Ra-e,d);if(8<a&&f.subarray)b.set(f.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=f[e+d];return a},write(a,b,c,d,e,f){b.buffer===w.buffer&&(f=!1);if(!d)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&(!a.La||a.La.subarray)){if(f)return a.La=b.subarray(c,c+d),a.Ra=d;if(0===a.Ra&&0===e)return a.La=
b.slice(c,c+d),a.Ra=d;if(e+d<=a.Ra)return a.La.set(b.subarray(c,c+d),e),d}pb(a,e+d);if(a.La.subarray&&b.subarray)a.La.set(b.subarray(c,c+d),e);else for(f=0;f<d;f++)a.La[e+f]=b[c+f];a.Ra=Math.max(a.Ra,e+d);return d},kb(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.Ra);if(0>b)throw new L(28);return b},yb(a,b,c){pb(a.node,b+c);a.node.Ra=Math.max(a.node.Ra,b+c)},Sb(a,b,c,d,e){if(32768!==(a.node.mode&61440))throw new L(43);a=a.node.La;if(e&2||a.buffer!==w.buffer){if(0<c||c+
b<a.length)a=a.subarray?a.subarray(c,c+b):Array.prototype.slice.call(a,c,c+b);c=!0;b=ob(b);if(!b)throw new L(48);w.set(a,b)}else c=!1,b=a.byteOffset;return{Pa:b,ib:c}},Gb(a,b,c,d){M.Na.write(a,b,0,d,c,!1);return 0}}},ub=(a,b,c)=>{var d=`al ${a}`;ka(a,e=>{b(new Uint8Array(e));d&&Ha(d)},()=>{if(c)c();else throw`Loading data file "${a}" failed.`;});d&&Ga(d)},vb=k.preloadPlugins||[],wb=(a,b,c,d)=>{"undefined"!=typeof Browser&&Browser.ld();var e=!1;vb.forEach(f=>{!e&&f.canHandle(b)&&(f.handle(a,b,c,d),
e=!0)});return e},yb=(a,b,c,d,e,f,g,l,m,n)=>{function q(h){function t(u){n?.();l||xb(a,b,u,d,e,m);f?.();Ha(r)}wb(h,p,t,()=>{g?.();Ha(r)})||t(h)}var p=b?cb(Ya(a+"/"+b)):a,r=`cp ${p}`;Ga(r);"string"==typeof c?ub(c,q,g):q(c)},zb=(a,b)=>{var c=0;a&&(c|=365);b&&(c|=146);return c},Ab=null,Bb={},Cb=[],Db=1,Eb=null,Fb=!0,L=class{constructor(a){this.name="ErrnoError";this.Xa=a}},sb={},Gb=class{constructor(){this.Ib={};this.node=null}get object(){return this.node}set object(a){this.node=a}get flags(){return this.Ib.flags}set flags(a){this.Ib.flags=
a}get position(){return this.Ib.position}set position(a){this.Ib.position=a}},Hb=class{constructor(a,b,c,d){a||=this;this.parent=a;this.fb=a.fb;this.tb=null;this.id=Db++;this.name=b;this.mode=c;this.Ma={};this.Na={};this.vb=d;this.Hb=365;this.Nb=146}get read(){return(this.mode&this.Hb)===this.Hb}set read(a){a?this.mode|=this.Hb:this.mode&=~this.Hb}get write(){return(this.mode&this.Nb)===this.Nb}set write(a){a?this.mode|=this.Nb:this.mode&=~this.Nb}get Mc(){return O(this.mode)}get Lc(){return 8192===
(this.mode&61440)}};function P(a,b={}){a=cb(a);if(!a)return{path:"",node:null};b=Object.assign({fc:!0,Vb:0},b);if(8<b.Vb)throw new L(32);a=a.split("/").filter(g=>!!g);for(var c=Ab,d="/",e=0;e<a.length;e++){var f=e===a.length-1;if(f&&b.parent)break;c=tb(c,a[e]);d=Ya(d+"/"+a[e]);c.tb&&(!f||f&&b.fc)&&(c=c.tb.root);if(!f||b.Bb)for(f=0;40960===(c.mode&61440);)if(c=Ib(d),d=cb(Za(d),c),c=P(d,{Vb:b.Vb+1}).node,40<f++)throw new L(32);}return{path:d,node:c}}
function Jb(a){for(var b;;){if(a===a.parent)return a=a.fb.lc,b?"/"!==a[a.length-1]?`${a}/${b}`:a+b:a;b=b?`${a.name}/${b}`:a.name;a=a.parent}}function Kb(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%Eb.length}function tb(a,b){var c=O(a.mode)?(c=Lb(a,"x"))?c:a.Ma.sb?0:2:54;if(c)throw new L(c);for(c=Eb[Kb(a.id,b)];c;c=c.qb){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.Ma.sb(a,b)}
function rb(a,b,c,d){a=new Hb(a,b,c,d);b=Kb(a.parent.id,a.name);a.qb=Eb[b];return Eb[b]=a}function O(a){return 16384===(a&61440)}function Mb(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}function Lb(a,b){if(Fb)return 0;if(!b.includes("r")||a.mode&292){if(b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73))return 2}else return 2;return 0}function Nb(a,b){try{return tb(a,b),20}catch(c){}return Lb(a,"wx")}function Ob(a){a=Cb[a];if(!a)throw new L(8);return a}
function Pb(a,b=-1){a=Object.assign(new Gb,a);if(-1==b)a:{for(b=0;4096>=b;b++)if(!Cb[b])break a;throw new L(33);}a.hb=b;return Cb[b]=a}function Qb(a,b=-1){a=Pb(a,b);a.Na?.hd?.(a);return a}var qb={open(a){a.Na=Bb[a.node.vb].Na;a.Na.open?.(a)},kb(){throw new L(70);}};function jb(a,b){Bb[a]={Na:b}}
function Rb(a,b){var c="/"===b;if(c&&Ab)throw new L(10);if(!c&&b){var d=P(b,{fc:!1});b=d.path;d=d.node;if(d.tb)throw new L(10);if(!O(d.mode))throw new L(54);}b={type:a,od:{},lc:b,Nc:[]};a=a.fb(b);a.fb=b;b.root=a;c?Ab=a:d&&(d.tb=b,d.fb&&d.fb.Nc.push(b))}function Sb(a,b,c){var d=P(a,{parent:!0}).node;a=$a(a);if(!a||"."===a||".."===a)throw new L(28);var e=Nb(d,a);if(e)throw new L(e);if(!d.Ma.Fb)throw new L(63);return d.Ma.Fb(d,a,b,c)}function Tb(a){return Sb(a,16895,0)}
function Ub(a,b,c){"undefined"==typeof c&&(c=b,b=438);return Sb(a,b|8192,c)}function Vb(a,b){if(!cb(a))throw new L(44);var c=P(b,{parent:!0}).node;if(!c)throw new L(44);b=$a(b);var d=Nb(c,b);if(d)throw new L(d);if(!c.Ma.Jb)throw new L(63);c.Ma.Jb(c,b,a)}
function Wb(a){var b=P(a,{parent:!0}).node;if(!b)throw new L(44);var c=$a(a);a=tb(b,c);a:{try{var d=tb(b,c)}catch(f){d=f.Xa;break a}var e=Lb(b,"wx");d=e?e:O(d.mode)?31:0}if(d)throw new L(d);if(!b.Ma.Mb)throw new L(63);if(a.tb)throw new L(10);b.Ma.Mb(b,c);b=Kb(a.parent.id,a.name);if(Eb[b]===a)Eb[b]=a.qb;else for(b=Eb[b];b;){if(b.qb===a){b.qb=a.qb;break}b=b.qb}}function Ib(a){a=P(a).node;if(!a)throw new L(44);if(!a.Ma.wb)throw new L(28);return cb(Jb(a.parent),a.Ma.wb(a))}
function Xb(a,b){a=P(a,{Bb:!b}).node;if(!a)throw new L(44);if(!a.Ma.ab)throw new L(63);return a.Ma.ab(a)}function Yb(a){return Xb(a,!0)}function Zb(a,b){a="string"==typeof a?P(a,{Bb:!0}).node:a;if(!a.Ma.Ya)throw new L(63);a.Ma.Ya(a,{mode:b&4095|a.mode&-4096,timestamp:Date.now()})}
function $b(a,b,c){if(""===a)throw new L(44);if("string"==typeof b){var d={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090}[b];if("undefined"==typeof d)throw Error(`Unknown file open mode: ${b}`);b=d}c=b&64?("undefined"==typeof c?438:c)&4095|32768:0;if("object"==typeof a)var e=a;else{a=Ya(a);try{e=P(a,{Bb:!(b&131072)}).node}catch(f){}}d=!1;if(b&64)if(e){if(b&128)throw new L(20);}else e=Sb(a,c,0),d=!0;if(!e)throw new L(44);8192===(e.mode&61440)&&(b&=-513);if(b&65536&&!O(e.mode))throw new L(54);if(!d&&(c=
e?40960===(e.mode&61440)?32:O(e.mode)&&("r"!==Mb(b)||b&512)?31:Lb(e,Mb(b)):44))throw new L(c);if(b&512&&!d){c=e;c="string"==typeof c?P(c,{Bb:!0}).node:c;if(!c.Ma.Ya)throw new L(63);if(O(c.mode))throw new L(31);if(32768!==(c.mode&61440))throw new L(28);if(d=Lb(c,"w"))throw new L(d);c.Ma.Ya(c,{size:0,timestamp:Date.now()})}b&=-131713;e=Pb({node:e,path:Jb(e),flags:b,seekable:!0,position:0,Na:e.Na,bd:[],error:!1});e.Na.open&&e.Na.open(e);!k.logReadFiles||b&1||(ac||={},a in ac||(ac[a]=1));return e}
function bc(a){if(null===a.hb)throw new L(8);a.Pb&&(a.Pb=null);try{a.Na.close&&a.Na.close(a)}catch(b){throw b;}finally{Cb[a.hb]=null}a.hb=null}function cc(a,b,c){if(null===a.hb)throw new L(8);if(!a.seekable||!a.Na.kb)throw new L(70);if(0!=c&&1!=c&&2!=c)throw new L(28);a.position=a.Na.kb(a,b,c);a.bd=[]}
function dc(a,b,c,d,e,f){if(0>d||0>e)throw new L(28);if(null===a.hb)throw new L(8);if(0===(a.flags&2097155))throw new L(8);if(O(a.node.mode))throw new L(31);if(!a.Na.write)throw new L(28);a.seekable&&a.flags&1024&&cc(a,0,2);var g="undefined"!=typeof e;if(!g)e=a.position;else if(!a.seekable)throw new L(70);b=a.Na.write(a,b,c,d,e,f);g||(a.position+=b);return b}var ec;
function fc(a,b){a="string"==typeof a?a:Jb(a);for(b=b.split("/").reverse();b.length;){var c=b.pop();if(c){var d=Ya(a+"/"+c);try{Tb(d)}catch(e){}a=d}}return d}function gc(a,b,c,d){a=Ya(("string"==typeof a?a:Jb(a))+"/"+b);c=zb(c,d);return Sb(a,(void 0!==c?c:438)&4095|32768,0)}
function xb(a,b,c,d,e,f){var g=b;a&&(a="string"==typeof a?a:Jb(a),g=b?Ya(a+"/"+b):a);a=zb(d,e);g=Sb(g,(void 0!==a?a:438)&4095|32768,0);if(c){if("string"==typeof c){b=Array(c.length);d=0;for(e=c.length;d<e;++d)b[d]=c.charCodeAt(d);c=b}Zb(g,a|146);b=$b(g,577);dc(b,c,0,c.length,0,f);bc(b);Zb(g,a)}}
function hc(a,b,c,d){a=Ya(("string"==typeof a?a:Jb(a))+"/"+b);b=zb(!!c,!!d);hc.kc||(hc.kc=64);var e=hc.kc++<<8|0;jb(e,{open(f){f.seekable=!1},close(){d?.buffer?.length&&d(10)},read(f,g,l,m){for(var n=0,q=0;q<m;q++){try{var p=c()}catch(r){throw new L(29);}if(void 0===p&&0===n)throw new L(6);if(null===p||void 0===p)break;n++;g[l+q]=p}n&&(f.node.timestamp=Date.now());return n},write(f,g,l,m){for(var n=0;n<m;n++)try{d(g[l+n])}catch(q){throw new L(29);}m&&(f.node.timestamp=Date.now());return n}});return Ub(a,
b,e)}function ic(a){if(!(a.Lc||a.Mc||a.link||a.La)){if("undefined"!=typeof XMLHttpRequest)throw Error("Lazy loading should have been performed (contents set) in createLazyFile, but it was not. Lazy loading only works in web workers. Use --embed-file or --preload-file in emcc on the main thread.");if(ja)try{a.La=gb(ja(a.url),!0),a.Ra=a.La.length}catch(b){throw new L(29);}else throw Error("Cannot load without read() or XMLHttpRequest.");}}
function jc(a,b,c,d,e){function f(p,r,h,t,u){p=p.node.La;if(u>=p.length)return 0;t=Math.min(p.length-u,t);if(p.slice)for(var A=0;A<t;A++)r[h+A]=p[u+A];else for(A=0;A<t;A++)r[h+A]=p.get(u+A);return t}class g{constructor(){this.Rb=!1;this.Ab=[];this.rb=void 0;this.Zb=this.$b=0}get(p){if(!(p>this.length-1||0>p)){var r=p%this.cc;return this.rb(p/this.cc|0)[r]}}Tc(p){this.rb=p}ac(){var p=new XMLHttpRequest;p.open("HEAD",c,!1);p.send(null);if(!(200<=p.status&&300>p.status||304===p.status))throw Error("Couldn't load "+
c+". Status: "+p.status);var r=Number(p.getResponseHeader("Content-length")),h,t=(h=p.getResponseHeader("Accept-Ranges"))&&"bytes"===h;p=(h=p.getResponseHeader("Content-Encoding"))&&"gzip"===h;var u=1048576;t||(u=r);var A=this;A.Tc(J=>{var I=J*u,z=(J+1)*u-1;z=Math.min(z,r-1);if("undefined"==typeof A.Ab[J]){var N=A.Ab;if(I>z)throw Error("invalid range ("+I+", "+z+") or no bytes requested!");if(z>r-1)throw Error("only "+r+" bytes available! programmer error!");var C=new XMLHttpRequest;C.open("GET",
c,!1);r!==u&&C.setRequestHeader("Range","bytes="+I+"-"+z);C.responseType="arraybuffer";C.overrideMimeType&&C.overrideMimeType("text/plain; charset=x-user-defined");C.send(null);if(!(200<=C.status&&300>C.status||304===C.status))throw Error("Couldn't load "+c+". Status: "+C.status);I=void 0!==C.response?new Uint8Array(C.response||[]):gb(C.responseText||"",!0);N[J]=I}if("undefined"==typeof A.Ab[J])throw Error("doXHR failed!");return A.Ab[J]});if(p||!r)u=r=1,u=r=this.rb(0).length,na("LazyFiles on gzip forces download of the whole file when length is accessed");
this.$b=r;this.Zb=u;this.Rb=!0}get length(){this.Rb||this.ac();return this.$b}get cc(){this.Rb||this.ac();return this.Zb}}if("undefined"!=typeof XMLHttpRequest){if(!ha)throw"Cannot do synchronous binary XHRs outside webworkers in modern browsers. Use --embed-file or --preload-file in emcc";var l=new g;var m=void 0}else m=c,l=void 0;var n=gc(a,b,d,e);l?n.La=l:m&&(n.La=null,n.url=m);Object.defineProperties(n,{Ra:{get:function(){return this.La.length}}});var q={};Object.keys(n.Na).forEach(p=>{var r=
n.Na[p];q[p]=(...h)=>{ic(n);return r(...h)}});q.read=(p,r,h,t,u)=>{ic(n);return f(p,r,h,t,u)};q.Sb=(p,r,h)=>{ic(n);var t=ob(r);if(!t)throw new L(48);f(p,w,t,r,h);return{Pa:t,ib:!0}};n.Na=q;return n}var Q={},ac,kc=a=>a?G(x,a):"";function lc(a,b,c){if("/"===b.charAt(0))return b;a=-100===a?"/":Ob(a).path;if(0==b.length){if(!c)throw new L(44);return a}return Ya(a+"/"+b)}
function mc(a,b,c){a=a(b);B[c>>2]=a.yc;B[c+4>>2]=a.mode;D[c+8>>2]=a.Pc;B[c+12>>2]=a.uid;B[c+16>>2]=a.Fc;B[c+20>>2]=a.vb;F=[a.size>>>0,(E=a.size,1<=+Math.abs(E)?0<E?+Math.floor(E/4294967296)>>>0:~~+Math.ceil((E-+(~~E>>>0))/4294967296)>>>0:0)];B[c+24>>2]=F[0];B[c+28>>2]=F[1];B[c+32>>2]=4096;B[c+36>>2]=a.uc;b=a.sc.getTime();var d=a.Oc.getTime(),e=a.xc.getTime();F=[Math.floor(b/1E3)>>>0,(E=Math.floor(b/1E3),1<=+Math.abs(E)?0<E?+Math.floor(E/4294967296)>>>0:~~+Math.ceil((E-+(~~E>>>0))/4294967296)>>>0:
0)];B[c+40>>2]=F[0];B[c+44>>2]=F[1];D[c+48>>2]=b%1E3*1E3;F=[Math.floor(d/1E3)>>>0,(E=Math.floor(d/1E3),1<=+Math.abs(E)?0<E?+Math.floor(E/4294967296)>>>0:~~+Math.ceil((E-+(~~E>>>0))/4294967296)>>>0:0)];B[c+56>>2]=F[0];B[c+60>>2]=F[1];D[c+64>>2]=d%1E3*1E3;F=[Math.floor(e/1E3)>>>0,(E=Math.floor(e/1E3),1<=+Math.abs(E)?0<E?+Math.floor(E/4294967296)>>>0:~~+Math.ceil((E-+(~~E>>>0))/4294967296)>>>0:0)];B[c+72>>2]=F[0];B[c+76>>2]=F[1];D[c+80>>2]=e%1E3*1E3;F=[a.jc>>>0,(E=a.jc,1<=+Math.abs(E)?0<E?+Math.floor(E/
4294967296)>>>0:~~+Math.ceil((E-+(~~E>>>0))/4294967296)>>>0:0)];B[c+88>>2]=F[0];B[c+92>>2]=F[1];return 0}var Wa=void 0,nc={},oc=a=>{for(;a.length;){var b=a.pop();a.pop()(b)}};function pc(a){return this.fromWireType(D[a>>2])}
var qc={},rc={},sc={},tc,vc=(a,b,c)=>{function d(l){l=c(l);if(l.length!==a.length)throw new tc("Mismatched type converter count");for(var m=0;m<a.length;++m)uc(a[m],l[m])}a.forEach(function(l){sc[l]=b});var e=Array(b.length),f=[],g=0;b.forEach((l,m)=>{rc.hasOwnProperty(l)?e[m]=rc[l]:(f.push(l),qc.hasOwnProperty(l)||(qc[l]=[]),qc[l].push(()=>{e[m]=rc[l];++g;g===f.length&&d(e)}))});0===f.length&&d(e)},wc,R=a=>{for(var b="";x[a];)b+=wc[x[a++]];return b},S;
function xc(a,b,c={}){var d=b.name;if(!a)throw new S(`type "${d}" must have a positive integer typeid pointer`);if(rc.hasOwnProperty(a)){if(c.Gc)return;throw new S(`Cannot register type '${d}' twice`);}rc[a]=b;delete sc[a];qc.hasOwnProperty(a)&&(b=qc[a],delete qc[a],b.forEach(e=>e()))}function uc(a,b,c={}){if(!("argPackAdvance"in b))throw new TypeError("registerType registeredInstance requires argPackAdvance");return xc(a,b,c)}
var yc=a=>{throw new S(a.Ka.Sa.Oa.name+" instance already deleted");},zc=!1,Ac=()=>{},Bc=(a,b,c)=>{if(b===c)return a;if(void 0===c.Wa)return null;a=Bc(a,b,c.Wa);return null===a?null:c.zc(a)},Cc={},Dc=[],Ec=()=>{for(;Dc.length;){var a=Dc.pop();a.Ka.ob=!1;a["delete"]()}},Fc,Gc={},Hc=(a,b)=>{if(void 0===b)throw new S("ptr should not be undefined");for(;a.Wa;)b=a.xb(b),a=a.Wa;return Gc[b]},Jc=(a,b)=>{if(!b.Sa||!b.Pa)throw new tc("makeClassHandle requires ptr and ptrType");if(!!b.Za!==!!b.Ta)throw new tc("Both smartPtrType and smartPtr must be specified");
b.count={value:1};return Ic(Object.create(a,{Ka:{value:b,writable:!0}}))},Ic=a=>{if("undefined"===typeof FinalizationRegistry)return Ic=b=>b,a;zc=new FinalizationRegistry(b=>{b=b.Ka;--b.count.value;0===b.count.value&&(b.Ta?b.Za.cb(b.Ta):b.Sa.Oa.cb(b.Pa))});Ic=b=>{var c=b.Ka;c.Ta&&zc.register(b,{Ka:c},b);return b};Ac=b=>{zc.unregister(b)};return Ic(a)};function Kc(){}
var Lc=(a,b)=>Object.defineProperty(b,"name",{value:a}),Mc=(a,b,c)=>{if(void 0===a[b].Va){var d=a[b];a[b]=function(...e){if(!a[b].Va.hasOwnProperty(e.length))throw new S(`Function '${c}' called with an invalid number of arguments (${e.length}) - expects one of (${a[b].Va})!`);return a[b].Va[e.length].apply(this,e)};a[b].Va=[];a[b].Va[d.zb]=d}},Nc=(a,b,c)=>{if(k.hasOwnProperty(a)){if(void 0===c||void 0!==k[a].Va&&void 0!==k[a].Va[c])throw new S(`Cannot register public name '${a}' twice`);Mc(k,a,a);
if(k.hasOwnProperty(c))throw new S(`Cannot register multiple overloads of a function with the same number of arguments (${c})!`);k[a].Va[c]=b}else k[a]=b,void 0!==c&&(k[a].nd=c)},Oc=a=>{if(void 0===a)return"_unknown";a=a.replace(/[^a-zA-Z0-9_]/g,"$");var b=a.charCodeAt(0);return 48<=b&&57>=b?`_${a}`:a};function Pc(a,b,c,d,e,f,g,l){this.name=a;this.constructor=b;this.pb=c;this.cb=d;this.Wa=e;this.Bc=f;this.xb=g;this.zc=l;this.Rc=[]}
var Qc=(a,b,c)=>{for(;b!==c;){if(!b.xb)throw new S(`Expected null or instance of ${c.name}, got an instance of ${b.name}`);a=b.xb(a);b=b.Wa}return a};function Rc(a,b){if(null===b){if(this.Qb)throw new S(`null is not a valid ${this.name}`);return 0}if(!b.Ka)throw new S(`Cannot pass "${Sc(b)}" as a ${this.name}`);if(!b.Ka.Pa)throw new S(`Cannot pass deleted object as a pointer of type ${this.name}`);return Qc(b.Ka.Pa,b.Ka.Sa.Oa,this.Oa)}
function Tc(a,b){if(null===b){if(this.Qb)throw new S(`null is not a valid ${this.name}`);if(this.Eb){var c=this.Ub();null!==a&&a.push(this.cb,c);return c}return 0}if(!b||!b.Ka)throw new S(`Cannot pass "${Sc(b)}" as a ${this.name}`);if(!b.Ka.Pa)throw new S(`Cannot pass deleted object as a pointer of type ${this.name}`);if(!this.Db&&b.Ka.Sa.Db)throw new S(`Cannot convert argument of type ${b.Ka.Za?b.Ka.Za.name:b.Ka.Sa.name} to parameter type ${this.name}`);c=Qc(b.Ka.Pa,b.Ka.Sa.Oa,this.Oa);if(this.Eb){if(void 0===
b.Ka.Ta)throw new S("Passing raw pointer to smart pointer is illegal");switch(this.Xc){case 0:if(b.Ka.Za===this)c=b.Ka.Ta;else throw new S(`Cannot convert argument of type ${b.Ka.Za?b.Ka.Za.name:b.Ka.Sa.name} to parameter type ${this.name}`);break;case 1:c=b.Ka.Ta;break;case 2:if(b.Ka.Za===this)c=b.Ka.Ta;else{var d=b.clone();c=this.Sc(c,T(()=>d["delete"]()));null!==a&&a.push(this.cb,c)}break;default:throw new S("Unsupporting sharing policy");}}return c}
function Uc(a,b){if(null===b){if(this.Qb)throw new S(`null is not a valid ${this.name}`);return 0}if(!b.Ka)throw new S(`Cannot pass "${Sc(b)}" as a ${this.name}`);if(!b.Ka.Pa)throw new S(`Cannot pass deleted object as a pointer of type ${this.name}`);if(b.Ka.Sa.Db)throw new S(`Cannot convert argument of type ${b.Ka.Sa.name} to parameter type ${this.name}`);return Qc(b.Ka.Pa,b.Ka.Sa.Oa,this.Oa)}
function Vc(a,b,c,d,e,f,g,l,m,n,q){this.name=a;this.Oa=b;this.Qb=c;this.Db=d;this.Eb=e;this.Qc=f;this.Xc=g;this.nc=l;this.Ub=m;this.Sc=n;this.cb=q;e||void 0!==b.Wa?this.toWireType=Tc:(this.toWireType=d?Rc:Uc,this.$a=null)}
var Wc=(a,b,c)=>{if(!k.hasOwnProperty(a))throw new tc("Replacing nonexistent public symbol");void 0!==k[a].Va&&void 0!==c?k[a].Va[c]=b:(k[a]=b,k[a].zb=c)},Xc=[],Yc,U=a=>{var b=Xc[a];b||(a>=Xc.length&&(Xc.length=a+1),Xc[a]=b=Yc.get(a));return b},Zc=(a,b,c=[])=>{a.includes("j")?(a=a.replace(/p/g,"i"),b=(0,k["dynCall_"+a])(b,...c)):b=U(b)(...c);return b},$c=(a,b)=>(...c)=>Zc(a,b,c),W=(a,b)=>{a=R(a);var c=a.includes("j")?$c(a,b):U(b);if("function"!=typeof c)throw new S(`unknown function pointer with signature ${a}: ${b}`);
return c},ad,dd=a=>{a=bd(a);var b=R(a);cd(a);return b},ed=(a,b)=>{function c(f){e[f]||rc[f]||(sc[f]?sc[f].forEach(c):(d.push(f),e[f]=!0))}var d=[],e={};b.forEach(c);throw new ad(`${a}: `+d.map(dd).join([", "]));},fd=(a,b)=>{for(var c=[],d=0;d<a;d++)c.push(D[b+4*d>>2]);return c};function gd(a){for(var b=1;b<a.length;++b)if(null!==a[b]&&void 0===a[b].$a)return!0;return!1}
function hd(a,b,c,d,e){var f=b.length;if(2>f)throw new S("argTypes array size mismatch! Must at least get return value and 'this' types!");var g=null!==b[1]&&null!==c,l=gd(b),m="void"!==b[0].name,n=f-2,q=Array(n),p=[],r=[];return Lc(a,function(...h){if(h.length!==n)throw new S(`function ${a} called with ${h.length} arguments, expected ${n}`);r.length=0;p.length=g?2:1;p[0]=e;if(g){var t=b[1].toWireType(r,this);p[1]=t}for(var u=0;u<n;++u)q[u]=b[u+2].toWireType(r,h[u]),p.push(q[u]);h=d(...p);if(l)oc(r);
else for(u=g?1:2;u<b.length;u++){var A=1===u?t:q[u-2];null!==b[u].$a&&b[u].$a(A)}t=m?b[0].fromWireType(h):void 0;return t})}
var jd=a=>{a=a.trim();const b=a.indexOf("(");return-1!==b?a.substr(0,b):a},kd=[],ld=[],md=a=>{9<a&&0===--ld[a+1]&&(ld[a]=void 0,kd.push(a))},X=a=>{if(!a)throw new S("Cannot use deleted val. handle = "+a);return ld[a]},T=a=>{switch(a){case void 0:return 2;case null:return 4;case !0:return 6;case !1:return 8;default:const b=kd.pop()||ld.length;ld[b]=a;ld[b+1]=1;return b}},nd={name:"emscripten::val",fromWireType:a=>{var b=X(a);md(a);return b},toWireType:(a,b)=>T(b),argPackAdvance:8,readValueFromPointer:pc,
$a:null},Sc=a=>{if(null===a)return"null";var b=typeof a;return"object"===b||"array"===b||"function"===b?a.toString():""+a},od=(a,b)=>{switch(b){case 4:return function(c){return this.fromWireType(ta[c>>2])};case 8:return function(c){return this.fromWireType(ua[c>>3])};default:throw new TypeError(`invalid float width (${b}): ${a}`);}},pd=(a,b,c)=>{switch(b){case 1:return c?d=>w[d]:d=>x[d];case 2:return c?d=>y[d>>1]:d=>sa[d>>1];case 4:return c?d=>B[d>>2]:d=>D[d>>2];default:throw new TypeError(`invalid integer width (${b}): ${a}`);
}},qd="undefined"!=typeof TextDecoder?new TextDecoder("utf-16le"):void 0,rd=(a,b)=>{var c=a>>1;for(var d=c+b/2;!(c>=d)&&sa[c];)++c;c<<=1;if(32<c-a&&qd)return qd.decode(x.subarray(a,c));c="";for(d=0;!(d>=b/2);++d){var e=y[a+2*d>>1];if(0==e)break;c+=String.fromCharCode(e)}return c},sd=(a,b,c)=>{c??=2147483647;if(2>c)return 0;c-=2;var d=b;c=c<2*a.length?c/2:a.length;for(var e=0;e<c;++e)y[b>>1]=a.charCodeAt(e),b+=2;y[b>>1]=0;return b-d},td=a=>2*a.length,ud=(a,b)=>{for(var c=0,d="";!(c>=b/4);){var e=B[a+
4*c>>2];if(0==e)break;++c;65536<=e?(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023)):d+=String.fromCharCode(e)}return d},vd=(a,b,c)=>{c??=2147483647;if(4>c)return 0;var d=b;c=d+c-4;for(var e=0;e<a.length;++e){var f=a.charCodeAt(e);if(55296<=f&&57343>=f){var g=a.charCodeAt(++e);f=65536+((f&1023)<<10)|g&1023}B[b>>2]=f;b+=4;if(b+4>c)break}B[b>>2]=0;return b-d},wd=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&++c;b+=4}return b},xd=(a,b)=>{var c=rc[a];if(void 0===
c)throw a=`${b} has unknown type ${dd(a)}`,new S(a);return c},yd=(a,b,c)=>{var d=[];a=a.toWireType(d,c);d.length&&(D[b>>2]=T(d));return a},zd=[],Ad={},Bd=a=>{var b=Ad[a];return void 0===b?R(a):b},Cd=()=>{function a(b){b.$$$embind_global$$$=b;var c="object"==typeof $$$embind_global$$$&&b.$$$embind_global$$$==b;c||delete b.$$$embind_global$$$;return c}if("object"==typeof globalThis)return globalThis;if("object"==typeof $$$embind_global$$$)return $$$embind_global$$$;"object"==typeof global&&a(global)?
$$$embind_global$$$=global:"object"==typeof self&&a(self)&&($$$embind_global$$$=self);if("object"==typeof $$$embind_global$$$)return $$$embind_global$$$;throw Error("unable to get global object.");},Dd=a=>{var b=zd.length;zd.push(a);return b},Ed=(a,b)=>{for(var c=Array(a),d=0;d<a;++d)c[d]=xd(D[b+4*d>>2],"parameter "+d);return c},Fd=Reflect.construct,Gd=a=>0===a%4&&(0!==a%100||0===a%400),Hd=[0,31,60,91,121,152,182,213,244,274,305,335],Id=[0,31,59,90,120,151,181,212,243,273,304,334],Jd=[];
class Kd{constructor(){this.ib=[void 0];this.hc=[]}get(a){return this.ib[a]}has(a){return void 0!==this.ib[a]}yb(a){var b=this.hc.pop()||this.ib.length;this.ib[b]=a;return b}}var Ld,Md,Nd=0;
function Od(a,b,c,d,e){function f(){var C=0,V=0;z.response&&J&&0===D[a+12>>2]&&(V=z.response.byteLength);0<V&&(C=Pd(V),x.set(new Uint8Array(z.response),C));D[a+12>>2]=C;Y(a+16,V);Y(a+24,0);(C=z.response?z.response.byteLength:0)&&Y(a+32,C);y[a+40>>1]=z.readyState;y[a+42>>1]=z.status;z.statusText&&K(z.statusText,x,a+44,64)}var g=D[a+8>>2];if(g){var l=g?G(x,g):"",m=a+112,n=kc(m+0);n||="GET";var q=D[m+56>>2],p=D[m+68>>2],r=D[m+72>>2];g=D[m+76>>2];var h=D[m+80>>2],t=D[m+84>>2],u=D[m+88>>2],A=D[m+52>>2],
J=!!(A&1),I=!!(A&2);A=!!(A&64);p=p?p?G(x,p):"":void 0;r=r?r?G(x,r):"":void 0;var z=new XMLHttpRequest;z.withCredentials=!!x[m+60];z.open(n,l,!A,p,r);A||(z.timeout=q);z.qd=l;z.responseType="arraybuffer";h&&(l=h?G(x,h):"",z.overrideMimeType(l));if(g)for(;;){m=D[g>>2];if(!m)break;l=D[g+4>>2];if(!l)break;g+=8;m=m?G(x,m):"";l=l?G(x,l):"";z.setRequestHeader(m,l)}var N=Ld.yb(z);D[a>>2]=N;g=t&&u?x.slice(t,t+u):null;z.onload=C=>{Ld.has(N)&&(f(),200<=z.status&&300>z.status?b?.(a,z,C):c?.(a,z,C))};z.onerror=
C=>{Ld.has(N)&&(f(),c?.(a,z,C))};z.ontimeout=C=>{Ld.has(N)&&c?.(a,z,C)};z.onprogress=C=>{if(Ld.has(N)){var V=J&&I&&z.response?z.response.byteLength:0,H=0;0<V&&J&&I&&(H=Pd(V),x.set(new Uint8Array(z.response),H));D[a+12>>2]=H;Y(a+16,V);Y(a+24,C.loaded-V);Y(a+32,C.total);y[a+40>>1]=z.readyState;3<=z.readyState&&0===z.status&&0<C.loaded&&(z.status=200);y[a+42>>1]=z.status;z.statusText&&K(z.statusText,x,a+44,64);d?.(a,z,C);H&&cd(H)}};z.onreadystatechange=C=>{Ld.has(N)?(y[a+40>>1]=z.readyState,2<=z.readyState&&
(y[a+42>>1]=z.status),e?.(a,z,C)):--Nd};try{z.send(g)}catch(C){c?.(a,z,C)}}else c(a,0,"no url specified!")}var Sd=a=>{ra=a;if(!(Ua||0<Nd)){Qd();Ta(za);ec=!1;Rd(0);for(var b=0;b<Cb.length;b++){var c=Cb[b];c&&bc(c)}Ba=!0}ra=a;Ua||0<Nd||(k.onExit?.(a),qa=!0);ea(a,new Ra(a))},Y=(a,b)=>{D[a>>2]=b;D[a+4>>2]=(b-D[a>>2])/4294967296};
function Td(a,b,c,d){var e=Md;if(e){var f=D[a+112+64>>2];f||=D[a+8>>2];var g=f?G(x,f):"";try{var l=e.transaction(["FILES"],"readwrite").objectStore("FILES").put(b,g);l.onsuccess=()=>{y[a+40>>1]=4;y[a+42>>1]=200;K("OK",x,a+44,64);c(a,0,g)};l.onerror=m=>{y[a+40>>1]=4;y[a+42>>1]=413;K("Payload Too Large",x,a+44,64);d(a,0,m)}}catch(m){d(a,0,m)}}else d(a,0,"IndexedDB not available!")}
function Ud(a,b,c){var d=Md;if(d){var e=D[a+112+64>>2];e||=D[a+8>>2];e=e?G(x,e):"";try{var f=d.transaction(["FILES"],"readonly").objectStore("FILES").get(e);f.onsuccess=g=>{if(g.target.result){g=g.target.result;var l=g.byteLength||g.length,m=Pd(l);x.set(new Uint8Array(g),m);D[a+12>>2]=m;Y(a+16,l);Y(a+24,0);Y(a+32,l);y[a+40>>1]=4;y[a+42>>1]=200;K("OK",x,a+44,64);b(a,0,g)}else y[a+40>>1]=4,y[a+42>>1]=404,K("Not Found",x,a+44,64),c(a,0,"no data")};f.onerror=g=>{y[a+40>>1]=4;y[a+42>>1]=404;K("Not Found",
x,a+44,64);c(a,0,g)}}catch(g){c(a,0,g)}}else c(a,0,"IndexedDB not available!")}
function Vd(a,b,c){var d=Md;if(d){var e=D[a+112+64>>2];e||=D[a+8>>2];e=e?G(x,e):"";try{var f=d.transaction(["FILES"],"readwrite").objectStore("FILES").delete(e);f.onsuccess=g=>{g=g.target.result;D[a+12>>2]=0;Y(a+16,0);Y(a+24,0);Y(a+32,0);y[a+40>>1]=4;y[a+42>>1]=200;K("OK",x,a+44,64);b(a,0,g)};f.onerror=g=>{y[a+40>>1]=4;y[a+42>>1]=404;K("Not Found",x,a+44,64);c(a,0,g)}}catch(g){c(a,0,g)}}else c(a,0,"IndexedDB not available!")}
var Wd={},Yd=()=>{if(!Xd){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"==typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:da||"./this.program"},b;for(b in Wd)void 0===Wd[b]?delete a[b]:a[b]=Wd[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);Xd=c}return Xd},Xd,Zd=[31,29,31,30,31,30,31,31,30,31,30,31],$d=[31,28,31,30,31,30,31,31,30,31,30,31],ae=(a,b,c,d)=>{function e(h,t,u){for(h="number"==typeof h?h.toString():
h||"";h.length<t;)h=u[0]+h;return h}function f(h,t){return e(h,t,"0")}function g(h,t){function u(J){return 0>J?-1:0<J?1:0}var A;0===(A=u(h.getFullYear()-t.getFullYear()))&&0===(A=u(h.getMonth()-t.getMonth()))&&(A=u(h.getDate()-t.getDate()));return A}function l(h){switch(h.getDay()){case 0:return new Date(h.getFullYear()-1,11,29);case 1:return h;case 2:return new Date(h.getFullYear(),0,3);case 3:return new Date(h.getFullYear(),0,2);case 4:return new Date(h.getFullYear(),0,1);case 5:return new Date(h.getFullYear()-
1,11,31);case 6:return new Date(h.getFullYear()-1,11,30)}}function m(h){var t=h.lb;for(h=new Date((new Date(h.mb+1900,0,1)).getTime());0<t;){var u=h.getMonth(),A=(Gd(h.getFullYear())?Zd:$d)[u];if(t>A-h.getDate())t-=A-h.getDate()+1,h.setDate(1),11>u?h.setMonth(u+1):(h.setMonth(0),h.setFullYear(h.getFullYear()+1));else{h.setDate(h.getDate()+t);break}}u=new Date(h.getFullYear()+1,0,4);t=l(new Date(h.getFullYear(),0,4));u=l(u);return 0>=g(t,h)?0>=g(u,h)?h.getFullYear()+1:h.getFullYear():h.getFullYear()-
1}var n=D[d+40>>2];d={$c:B[d>>2],Zc:B[d+4>>2],Kb:B[d+8>>2],Xb:B[d+12>>2],Lb:B[d+16>>2],mb:B[d+20>>2],eb:B[d+24>>2],lb:B[d+28>>2],pd:B[d+32>>2],Yc:B[d+36>>2],ad:n?n?G(x,n):"":""};c=c?G(x,c):"";n={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S","%x":"%m/%d/%y","%X":"%H:%M:%S","%Ec":"%c","%EC":"%C","%Ex":"%m/%d/%y","%EX":"%H:%M:%S","%Ey":"%y","%EY":"%Y","%Od":"%d","%Oe":"%e","%OH":"%H","%OI":"%I","%Om":"%m","%OM":"%M","%OS":"%S","%Ou":"%u",
"%OU":"%U","%OV":"%V","%Ow":"%w","%OW":"%W","%Oy":"%y"};for(var q in n)c=c.replace(new RegExp(q,"g"),n[q]);var p="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),r="January February March April May June July August September October November December".split(" ");n={"%a":h=>p[h.eb].substring(0,3),"%A":h=>p[h.eb],"%b":h=>r[h.Lb].substring(0,3),"%B":h=>r[h.Lb],"%C":h=>f((h.mb+1900)/100|0,2),"%d":h=>f(h.Xb,2),"%e":h=>e(h.Xb,2," "),"%g":h=>m(h).toString().substring(2),"%G":m,"%H":h=>
f(h.Kb,2),"%I":h=>{h=h.Kb;0==h?h=12:12<h&&(h-=12);return f(h,2)},"%j":h=>{for(var t=0,u=0;u<=h.Lb-1;t+=(Gd(h.mb+1900)?Zd:$d)[u++]);return f(h.Xb+t,3)},"%m":h=>f(h.Lb+1,2),"%M":h=>f(h.Zc,2),"%n":()=>"\n","%p":h=>0<=h.Kb&&12>h.Kb?"AM":"PM","%S":h=>f(h.$c,2),"%t":()=>"\t","%u":h=>h.eb||7,"%U":h=>f(Math.floor((h.lb+7-h.eb)/7),2),"%V":h=>{var t=Math.floor((h.lb+7-(h.eb+6)%7)/7);2>=(h.eb+371-h.lb-2)%7&&t++;if(t)53==t&&(u=(h.eb+371-h.lb)%7,4==u||3==u&&Gd(h.mb)||(t=1));else{t=52;var u=(h.eb+7-h.lb-1)%7;(4==
u||5==u&&Gd(h.mb%400-1))&&t++}return f(t,2)},"%w":h=>h.eb,"%W":h=>f(Math.floor((h.lb+7-(h.eb+6)%7)/7),2),"%y":h=>(h.mb+1900).toString().substring(2),"%Y":h=>h.mb+1900,"%z":h=>{h=h.Yc;var t=0<=h;h=Math.abs(h)/60;return(t?"+":"-")+String("0000"+(h/60*100+h%60)).slice(-4)},"%Z":h=>h.ad,"%%":()=>"%"};c=c.replace(/%%/g,"\x00\x00");for(q in n)c.includes(q)&&(c=c.replace(new RegExp(q,"g"),n[q](d)));c=c.replace(/\0\0/g,"%");q=gb(c,!1);if(q.length>b)return 0;w.set(q,a);return q.length-1};
[44].forEach(a=>{sb[a]=new L(a);sb[a].stack="<generic error, no stack>"});Eb=Array(4096);Rb(M,"/");Tb("/tmp");Tb("/home");Tb("/home/web_user");(function(){Tb("/dev");jb(259,{read:()=>0,write:(d,e,f,g)=>g});Ub("/dev/null",259);ib(1280,lb);ib(1536,mb);Ub("/dev/tty",1280);Ub("/dev/tty1",1536);var a=new Uint8Array(1024),b=0,c=()=>{0===b&&(b=bb(a).byteLength);return a[--b]};hc("/dev","random",c);hc("/dev","urandom",c);Tb("/dev/shm");Tb("/dev/shm/tmp")})();
(function(){Tb("/proc");var a=Tb("/proc/self");Tb("/proc/self/fd");Rb({fb(){var b=rb(a,"fd",16895,73);b.Ma={sb(c,d){var e=Ob(+d);c={parent:null,fb:{lc:"fake"},Ma:{wb:()=>e.path}};return c.parent=c}};return b}},"/proc/self/fd")})();k.FS_createPath=fc;k.FS_createDataFile=xb;k.FS_createPreloadedFile=yb;k.FS_unlink=Wb;k.FS_createLazyFile=jc;k.FS_createDevice=hc;tc=k.InternalError=class extends Error{constructor(a){super(a);this.name="InternalError"}};for(var be=Array(256),ce=0;256>ce;++ce)be[ce]=String.fromCharCode(ce);
wc=be;S=k.BindingError=class extends Error{constructor(a){super(a);this.name="BindingError"}};
Object.assign(Kc.prototype,{isAliasOf:function(a){if(!(this instanceof Kc&&a instanceof Kc))return!1;var b=this.Ka.Sa.Oa,c=this.Ka.Pa;a.Ka=a.Ka;var d=a.Ka.Sa.Oa;for(a=a.Ka.Pa;b.Wa;)c=b.xb(c),b=b.Wa;for(;d.Wa;)a=d.xb(a),d=d.Wa;return b===d&&c===a},clone:function(){this.Ka.Pa||yc(this);if(this.Ka.ub)return this.Ka.count.value+=1,this;var a=Ic,b=Object,c=b.create,d=Object.getPrototypeOf(this),e=this.Ka;a=a(c.call(b,d,{Ka:{value:{count:e.count,ob:e.ob,ub:e.ub,Pa:e.Pa,Sa:e.Sa,Ta:e.Ta,Za:e.Za}}}));a.Ka.count.value+=
1;a.Ka.ob=!1;return a},["delete"](){this.Ka.Pa||yc(this);if(this.Ka.ob&&!this.Ka.ub)throw new S("Object already scheduled for deletion");Ac(this);var a=this.Ka;--a.count.value;0===a.count.value&&(a.Ta?a.Za.cb(a.Ta):a.Sa.Oa.cb(a.Pa));this.Ka.ub||(this.Ka.Ta=void 0,this.Ka.Pa=void 0)},isDeleted:function(){return!this.Ka.Pa},deleteLater:function(){this.Ka.Pa||yc(this);if(this.Ka.ob&&!this.Ka.ub)throw new S("Object already scheduled for deletion");Dc.push(this);1===Dc.length&&Fc&&Fc(Ec);this.Ka.ob=!0;
return this}});k.getInheritedInstanceCount=()=>Object.keys(Gc).length;k.getLiveInheritedInstances=()=>{var a=[],b;for(b in Gc)Gc.hasOwnProperty(b)&&a.push(Gc[b]);return a};k.flushPendingDeletes=Ec;k.setDelayFunction=a=>{Fc=a;Dc.length&&Fc&&Fc(Ec)};
Object.assign(Vc.prototype,{Cc(a){this.nc&&(a=this.nc(a));return a},dc(a){this.cb?.(a)},argPackAdvance:8,readValueFromPointer:pc,fromWireType:function(a){function b(){return this.Eb?Jc(this.Oa.pb,{Sa:this.Qc,Pa:c,Za:this,Ta:a}):Jc(this.Oa.pb,{Sa:this,Pa:a})}var c=this.Cc(a);if(!c)return this.dc(a),null;var d=Hc(this.Oa,c);if(void 0!==d){if(0===d.Ka.count.value)return d.Ka.Pa=c,d.Ka.Ta=a,d.clone();d=d.clone();this.dc(a);return d}d=this.Oa.Bc(c);d=Cc[d];if(!d)return b.call(this);d=this.Db?d.wc:d.pointerType;
var e=Bc(c,this.Oa,d.Oa);return null===e?b.call(this):this.Eb?Jc(d.Oa.pb,{Sa:d,Pa:e,Za:this,Ta:a}):Jc(d.Oa.pb,{Sa:d,Pa:e})}});ad=k.UnboundTypeError=((a,b)=>{var c=Lc(b,function(d){this.name=b;this.message=d;d=Error(d).stack;void 0!==d&&(this.stack=this.toString()+"\n"+d.replace(/^Error(:[^\n]*)?\n/,""))});c.prototype=Object.create(a.prototype);c.prototype.constructor=c;c.prototype.toString=function(){return void 0===this.message?this.name:`${this.name}: ${this.message}`};return c})(Error,"UnboundTypeError");
ld.push(0,1,void 0,1,null,1,!0,1,!1,1);k.count_emval_handles=()=>ld.length/2-5-kd.length;Ld=new Kd;Ga("library_fetch_init");(function(a,b){try{var c=indexedDB.open("emscripten_filesystem",1)}catch(d){b(d);return}c.onupgradeneeded=d=>{d=d.target.result;d.objectStoreNames.contains("FILES")&&d.deleteObjectStore("FILES");d.createObjectStore("FILES")};c.onsuccess=d=>a(d.target.result);c.onerror=b})(a=>{Md=a;Ha("library_fetch_init")},()=>{Md=!1;Ha("library_fetch_init")});
var ie={A:function(a,b,c){Wa=c;try{var d=Ob(a);switch(b){case 0:var e=Va();if(0>e)break;for(;Cb[e];)e++;return Qb(d,e).hb;case 1:case 2:return 0;case 3:return d.flags;case 4:return e=Va(),d.flags|=e,0;case 12:return e=Va(),y[e+0>>1]=2,0;case 13:case 14:return 0}return-28}catch(f){if("undefined"==typeof Q||"ErrnoError"!==f.name)throw f;return-f.Xa}},aa:function(a,b){try{var c=Ob(a);return mc(Xb,c.path,b)}catch(d){if("undefined"==typeof Q||"ErrnoError"!==d.name)throw d;return-d.Xa}},ba:function(a,b,
c){Wa=c;try{var d=Ob(a);switch(b){case 21509:return d.Qa?0:-59;case 21505:if(!d.Qa)return-59;if(d.Qa.gb.Ic){a=[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0];var e=Va();B[e>>2]=25856;B[e+4>>2]=5;B[e+8>>2]=191;B[e+12>>2]=35387;for(var f=0;32>f;f++)w[e+f+17]=a[f]||0}return 0;case 21510:case 21511:case 21512:return d.Qa?0:-59;case 21506:case 21507:case 21508:if(!d.Qa)return-59;if(d.Qa.gb.Jc)for(e=Va(),a=[],f=0;32>f;f++)a.push(w[e+f+17]);return 0;case 21519:if(!d.Qa)return-59;
e=Va();return B[e>>2]=0;case 21520:return d.Qa?-28:-59;case 21531:e=Va();if(!d.Na.Hc)throw new L(59);return d.Na.Hc(d,b,e);case 21523:if(!d.Qa)return-59;d.Qa.gb.Kc&&(f=[24,80],e=Va(),y[e>>1]=f[0],y[e+2>>1]=f[1]);return 0;case 21524:return d.Qa?0:-59;case 21515:return d.Qa?0:-59;default:return-28}}catch(g){if("undefined"==typeof Q||"ErrnoError"!==g.name)throw g;return-g.Xa}},_:function(a,b){try{return a=a?G(x,a):"",mc(Yb,a,b)}catch(c){if("undefined"==typeof Q||"ErrnoError"!==c.name)throw c;return-c.Xa}},
Z:function(a,b,c,d){try{b=b?G(x,b):"";var e=d&256;b=lc(a,b,d&4096);return mc(e?Yb:Xb,b,c)}catch(f){if("undefined"==typeof Q||"ErrnoError"!==f.name)throw f;return-f.Xa}},B:function(a,b,c,d){Wa=d;try{b=b?G(x,b):"";b=lc(a,b);var e=d?Va():0;return $b(b,c,e).hb}catch(f){if("undefined"==typeof Q||"ErrnoError"!==f.name)throw f;return-f.Xa}},$:function(a,b){try{return a=a?G(x,a):"",mc(Xb,a,b)}catch(c){if("undefined"==typeof Q||"ErrnoError"!==c.name)throw c;return-c.Xa}},d:a=>{var b=nc[a];delete nc[a];var c=
b.Ub,d=b.cb,e=b.ec,f=e.map(g=>g.Ec).concat(e.map(g=>g.Vc));vc([a],f,g=>{var l={};e.forEach((m,n)=>{var q=g[n],p=m.rb,r=m.Dc,h=g[n+e.length],t=m.Uc,u=m.Wc;l[m.Ac]={read:A=>q.fromWireType(p(r,A)),write:(A,J)=>{var I=[];t(u,A,h.toWireType(I,J));oc(I)}}});return[{name:b.name,fromWireType:m=>{var n={},q;for(q in l)n[q]=l[q].read(m);d(m);return n},toWireType:(m,n)=>{for(var q in l)if(!(q in n))throw new TypeError(`Missing field: "${q}"`);var p=c();for(q in l)l[q].write(p,n[q]);null!==m&&m.push(d,p);return p},
argPackAdvance:8,readValueFromPointer:pc,$a:d}]})},M:()=>{},I:(a,b,c,d)=>{b=R(b);uc(a,{name:b,fromWireType:function(e){return!!e},toWireType:function(e,f){return f?c:d},argPackAdvance:8,readValueFromPointer:function(e){return this.fromWireType(x[e])},$a:null})},o:(a,b,c,d,e,f,g,l,m,n,q,p,r)=>{q=R(q);f=W(e,f);l&&=W(g,l);n&&=W(m,n);r=W(p,r);var h=Oc(q);Nc(h,function(){ed(`Cannot construct ${q} due to unbound types`,[d])});vc([a,b,c],d?[d]:[],t=>{t=t[0];if(d){var u=t.Oa;var A=u.pb}else A=Kc.prototype;
t=Lc(q,function(...N){if(Object.getPrototypeOf(this)!==J)throw new S("Use 'new' to construct "+q);if(void 0===I.jb)throw new S(q+" has no accessible constructor");var C=I.jb[N.length];if(void 0===C)throw new S(`Tried to invoke ctor of ${q} with invalid number of parameters (${N.length}) - expected (${Object.keys(I.jb).toString()}) parameters instead!`);return C.apply(this,N)});var J=Object.create(A,{constructor:{value:t}});t.prototype=J;var I=new Pc(q,t,J,r,u,f,l,n);if(I.Wa){var z;(z=I.Wa).Yb??(z.Yb=
[]);I.Wa.Yb.push(I)}u=new Vc(q,I,!0,!1,!1);z=new Vc(q+"*",I,!1,!1,!1);A=new Vc(q+" const*",I,!1,!0,!1);Cc[a]={pointerType:z,wc:A};Wc(h,t);return[u,z,A]})},q:(a,b,c,d,e,f)=>{var g=fd(b,c);e=W(d,e);vc([],[a],l=>{l=l[0];var m=`constructor ${l.name}`;void 0===l.Oa.jb&&(l.Oa.jb=[]);if(void 0!==l.Oa.jb[b-1])throw new S(`Cannot register multiple constructors with identical number of parameters (${b-1}) for class '${l.name}'! Overload resolution is currently only performed using the parameter count, not actual type info!`);
l.Oa.jb[b-1]=()=>{ed(`Cannot construct ${l.name} due to unbound types`,g)};vc([],g,n=>{n.splice(1,0,null);l.Oa.jb[b-1]=hd(m,n,null,e,f);return[]});return[]})},h:(a,b,c,d,e,f,g,l)=>{var m=fd(c,d);b=R(b);b=jd(b);f=W(e,f);vc([],[a],n=>{function q(){ed(`Cannot call ${p} due to unbound types`,m)}n=n[0];var p=`${n.name}.${b}`;b.startsWith("@@")&&(b=Symbol[b.substring(2)]);l&&n.Oa.Rc.push(b);var r=n.Oa.pb,h=r[b];void 0===h||void 0===h.Va&&h.className!==n.name&&h.zb===c-2?(q.zb=c-2,q.className=n.name,r[b]=
q):(Mc(r,b,p),r[b].Va[c-2]=q);vc([],m,t=>{t=hd(p,t,n,f,g);void 0===r[b].Va?(t.zb=c-2,r[b]=t):r[b].Va[c-2]=t;return[]});return[]})},qa:a=>uc(a,nd),G:(a,b,c)=>{b=R(b);uc(a,{name:b,fromWireType:d=>d,toWireType:(d,e)=>e,argPackAdvance:8,readValueFromPointer:od(b,c),$a:null})},w:(a,b,c,d,e,f)=>{var g=fd(b,c);a=R(a);a=jd(a);e=W(d,e);Nc(a,function(){ed(`Cannot call ${a} due to unbound types`,g)},b-1);vc([],g,l=>{Wc(a,hd(a,[l[0],null].concat(l.slice(1)),null,e,f),b-1);return[]})},m:(a,b,c,d,e)=>{b=R(b);-1===
e&&(e=4294967295);e=l=>l;if(0===d){var f=32-8*c;e=l=>l<<f>>>f}var g=b.includes("unsigned")?function(l,m){return m>>>0}:function(l,m){return m};uc(a,{name:b,fromWireType:e,toWireType:g,argPackAdvance:8,readValueFromPointer:pd(b,c,0!==d),$a:null})},g:(a,b,c)=>{function d(f){return new e(w.buffer,D[f+4>>2],D[f>>2])}var e=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array][b];c=R(c);uc(a,{name:c,fromWireType:d,argPackAdvance:8,readValueFromPointer:d},{Gc:!0})},
x:(a,b)=>{b=R(b);var c="std::string"===b;uc(a,{name:b,fromWireType:function(d){var e=D[d>>2],f=d+4;if(c)for(var g=f,l=0;l<=e;++l){var m=f+l;if(l==e||0==x[m]){g=g?G(x,g,m-g):"";if(void 0===n)var n=g;else n+=String.fromCharCode(0),n+=g;g=m+1}}else{n=Array(e);for(l=0;l<e;++l)n[l]=String.fromCharCode(x[f+l]);n=n.join("")}cd(d);return n},toWireType:function(d,e){e instanceof ArrayBuffer&&(e=new Uint8Array(e));var f="string"==typeof e;if(!(f||e instanceof Uint8Array||e instanceof Uint8ClampedArray||e instanceof
Int8Array))throw new S("Cannot pass non-string to std::string");var g=c&&f?fb(e):e.length;var l=Pd(4+g+1),m=l+4;D[l>>2]=g;if(c&&f)K(e,x,m,g+1);else if(f)for(f=0;f<g;++f){var n=e.charCodeAt(f);if(255<n)throw cd(m),new S("String has UTF-16 code units that do not fit in 8 bits");x[m+f]=n}else for(f=0;f<g;++f)x[m+f]=e[f];null!==d&&d.push(cd,l);return l},argPackAdvance:8,readValueFromPointer:pc,$a(d){cd(d)}})},s:(a,b,c)=>{c=R(c);if(2===b){var d=rd;var e=sd;var f=td;var g=l=>sa[l>>1]}else 4===b&&(d=ud,
e=vd,f=wd,g=l=>D[l>>2]);uc(a,{name:c,fromWireType:l=>{for(var m=D[l>>2],n,q=l+4,p=0;p<=m;++p){var r=l+4+p*b;if(p==m||0==g(r))q=d(q,r-q),void 0===n?n=q:(n+=String.fromCharCode(0),n+=q),q=r+b}cd(l);return n},toWireType:(l,m)=>{if("string"!=typeof m)throw new S(`Cannot pass non-string to C++ string type ${c}`);var n=f(m),q=Pd(4+n+b);D[q>>2]=n/b;e(m,q+4,n+b);null!==l&&l.push(cd,q);return q},argPackAdvance:8,readValueFromPointer:pc,$a(l){cd(l)}})},e:(a,b,c,d,e,f)=>{nc[a]={name:R(b),Ub:W(c,d),cb:W(e,f),
ec:[]}},c:(a,b,c,d,e,f,g,l,m,n)=>{nc[a].ec.push({Ac:R(b),Ec:c,rb:W(d,e),Dc:f,Vc:g,Uc:W(l,m),Wc:n})},S:(a,b)=>{b=R(b);uc(a,{md:!0,name:b,argPackAdvance:0,fromWireType:()=>{},toWireType:()=>{}})},fa:function(a){if(Ld.has(a)){var b=Ld.get(a),c=Ld;c.ib[a]=void 0;c.hc.push(a);0<b.readyState&&4>b.readyState&&b.abort()}},ca:()=>1,Q:()=>{throw Infinity;},j:(a,b,c)=>{a=X(a);b=xd(b,"emval::as");return yd(b,c,a)},p:(a,b,c,d)=>{a=zd[a];b=X(b);return a(null,b,c,d)},n:(a,b,c,d,e)=>{a=zd[a];b=X(b);c=Bd(c);return a(b,
b[c],d,e)},oa:md,E:(a,b)=>{a=X(a);b=X(b);return a==b},ka:a=>{if(0===a)return T(Cd());a=Bd(a);return T(Cd()[a])},k:(a,b,c)=>{var d=Ed(a,b),e=d.shift();a--;var f=Array(a);b=`methodCaller<(${d.map(g=>g.name).join(", ")}) => ${e.name}>`;return Dd(Lc(b,(g,l,m,n)=>{for(var q=0,p=0;p<a;++p)f[p]=d[p].readValueFromPointer(n+q),q+=d[p].argPackAdvance;g=1===c?Fd(l,f):l.apply(g,f);return yd(e,m,g)}))},r:(a,b)=>{a=X(a);b=X(b);return T(a[b])},F:a=>{9<a&&(ld[a+1]+=1)},la:(a,b)=>{a=X(a);b=X(b);return a instanceof
b},ma:()=>T([]),ja:a=>T(Bd(a)),pa:()=>T({}),na:a=>{var b=X(a);oc(b);md(a)},f:(a,b,c)=>{a=X(a);b=X(b);c=X(c);a[b]=c},i:(a,b)=>{a=xd(a,"_emval_take_value");a=a.readValueFromPointer(b);return T(a)},ia:a=>{a=X(a);return T(typeof a)},J:function(a,b,c){a=new Date(1E3*(b+2097152>>>0<4194305-!!a?(a>>>0)+4294967296*b:NaN));B[c>>2]=a.getSeconds();B[c+4>>2]=a.getMinutes();B[c+8>>2]=a.getHours();B[c+12>>2]=a.getDate();B[c+16>>2]=a.getMonth();B[c+20>>2]=a.getFullYear()-1900;B[c+24>>2]=a.getDay();B[c+28>>2]=(Gd(a.getFullYear())?
Hd:Id)[a.getMonth()]+a.getDate()-1|0;B[c+36>>2]=-(60*a.getTimezoneOffset());b=(new Date(a.getFullYear(),6,1)).getTimezoneOffset();var d=(new Date(a.getFullYear(),0,1)).getTimezoneOffset();B[c+32>>2]=(b!=d&&a.getTimezoneOffset()==Math.min(d,b))|0},K:function(a){var b=new Date(B[a+20>>2]+1900,B[a+16>>2],B[a+12>>2],B[a+8>>2],B[a+4>>2],B[a>>2],0),c=B[a+32>>2],d=b.getTimezoneOffset(),e=(new Date(b.getFullYear(),6,1)).getTimezoneOffset(),f=(new Date(b.getFullYear(),0,1)).getTimezoneOffset(),g=Math.min(f,
e);0>c?B[a+32>>2]=Number(e!=f&&g==d):0<c!=(g==d)&&(e=Math.max(f,e),b.setTime(b.getTime()+6E4*((0<c?g:e)-d)));B[a+24>>2]=b.getDay();B[a+28>>2]=(Gd(b.getFullYear())?Hd:Id)[b.getMonth()]+b.getDate()-1|0;B[a>>2]=b.getSeconds();B[a+4>>2]=b.getMinutes();B[a+8>>2]=b.getHours();B[a+12>>2]=b.getDate();B[a+16>>2]=b.getMonth();B[a+20>>2]=b.getYear();a=b.getTime();a=isNaN(a)?-1:a/1E3;de((E=a,1<=+Math.abs(E)?0<E?+Math.floor(E/4294967296)>>>0:~~+Math.ceil((E-+(~~E>>>0))/4294967296)>>>0:0));return a>>>0},H:function(a,
b,c,d,e,f,g){f=g+2097152>>>0<4194305-!!f?(f>>>0)+4294967296*g:NaN;try{var l=Ob(e);if(c&2){if(32768!==(l.node.mode&61440))throw new L(43);d&2||l.Na.Gb&&l.Na.Gb(l,x.slice(a,a+b),f,b,d)}}catch(m){if("undefined"==typeof Q||"ErrnoError"!==m.name)throw m;return-m.Xa}},V:(a,b,c,d)=>{var e=(new Date).getFullYear(),f=new Date(e,0,1),g=new Date(e,6,1);e=f.getTimezoneOffset();var l=g.getTimezoneOffset();D[a>>2]=60*Math.max(e,l);B[b>>2]=Number(e!=l);a=m=>m.toLocaleTimeString(void 0,{hour12:!1,timeZoneName:"short"}).split(" ")[1];
f=a(f);g=a(g);l<e?(K(f,x,c,17),K(g,x,d,17)):(K(f,x,d,17),K(g,x,c,17))},b:()=>{Ia("")},l:(a,b,c)=>{Jd.length=0;for(var d;d=x[b++];){var e=105!=d;e&=112!=d;c+=e&&c%8?4:0;Jd.push(112==d?D[c>>2]:105==d?B[c>>2]:ua[c>>3]);c+=e?8:4}return Qa[a](...Jd)},C:()=>Date.now(),W:()=>2147483648,u:()=>performance.now(),ha:()=>!ha,U:a=>{var b=x.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=Math,e=Math.max(a,b+2097152/c);a:{d=(d.min.call(d,2147483648,e+(65536-e%65536)%65536)-pa.buffer.byteLength+
65535)/65536;try{pa.grow(d);va();var f=1;break a}catch(g){}f=void 0}if(f)return!0}return!1},ga:function(a,b,c,d,e){function f(H){if(r)H();else if(!Ba&&!qa)try{if(H(),!(Ba||Ua||0<Nd))try{Sd(ra)}catch(ma){ma instanceof Ra||"unwind"==ma||ea(1,ma)}}catch(ma){ma instanceof Ra||"unwind"==ma||ea(1,ma)}}Nd+=1;var g=a+112,l=D[g+36>>2],m=D[g+40>>2],n=D[g+44>>2],q=D[g+48>>2],p=D[g+52>>2],r=!!(p&64),h=H=>{--Nd;f(()=>{l?U(l)(H):b?.(H)})},t=H=>{f(()=>{n?U(n)(H):d?.(H)})},u=H=>{--Nd;f(()=>{m?U(m)(H):c?.(H)})},A=
H=>{f(()=>{q?U(q)(H):e?.(H)})},J=H=>{Od(H,h,u,t,A)},I=(H,ma)=>{Td(H,ma.response,Sa=>{--Nd;f(()=>{l?U(l)(Sa):b?.(Sa)})},Sa=>{--Nd;f(()=>{l?U(l)(Sa):b?.(Sa)})})},z=H=>{Od(H,I,u,t,A)},N=kc(g+0),C=!!(p&16),V=!!(p&4);p=!!(p&32);if("EM_IDB_STORE"===N)J=D[g+84>>2],Td(a,x.slice(J,J+D[g+88>>2]),h,u);else if("EM_IDB_DELETE"===N)Vd(a,h,u);else if(C){if(p)return 0;Od(a,V?I:h,u,t,A)}else Ud(a,h,p?u:V?z:J);return a},X:(a,b)=>{var c=0;Yd().forEach((d,e)=>{var f=b+c;e=D[a+4*e>>2]=f;for(f=0;f<d.length;++f)w[e++]=
d.charCodeAt(f);w[e]=0;c+=d.length+1});return 0},Y:(a,b)=>{var c=Yd();D[a>>2]=c.length;var d=0;c.forEach(e=>d+=e.length+1);D[b>>2]=d;return 0},D:Sd,v:function(a){try{var b=Ob(a);bc(b);return 0}catch(c){if("undefined"==typeof Q||"ErrnoError"!==c.name)throw c;return c.Xa}},z:function(a,b,c,d){try{a:{var e=Ob(a);a=b;for(var f,g=b=0;g<c;g++){var l=D[a>>2],m=D[a+4>>2];a+=8;var n=e,q=f,p=w;if(0>m||0>q)throw new L(28);if(null===n.hb)throw new L(8);if(1===(n.flags&2097155))throw new L(8);if(O(n.node.mode))throw new L(31);
if(!n.Na.read)throw new L(28);var r="undefined"!=typeof q;if(!r)q=n.position;else if(!n.seekable)throw new L(70);var h=n.Na.read(n,p,l,m,q);r||(n.position+=h);var t=h;if(0>t){var u=-1;break a}b+=t;if(t<m)break;"undefined"!=typeof f&&(f+=t)}u=b}D[d>>2]=u;return 0}catch(A){if("undefined"==typeof Q||"ErrnoError"!==A.name)throw A;return A.Xa}},L:function(a,b,c,d,e){b=c+2097152>>>0<4194305-!!b?(b>>>0)+4294967296*c:NaN;try{if(isNaN(b))return 61;var f=Ob(a);cc(f,b,d);F=[f.position>>>0,(E=f.position,1<=+Math.abs(E)?
0<E?+Math.floor(E/4294967296)>>>0:~~+Math.ceil((E-+(~~E>>>0))/4294967296)>>>0:0)];B[e>>2]=F[0];B[e+4>>2]=F[1];f.Pb&&0===b&&0===d&&(f.Pb=null);return 0}catch(g){if("undefined"==typeof Q||"ErrnoError"!==g.name)throw g;return g.Xa}},t:function(a,b,c,d){try{a:{var e=Ob(a);a=b;for(var f,g=b=0;g<c;g++){var l=D[a>>2],m=D[a+4>>2];a+=8;var n=dc(e,w,l,m,f);if(0>n){var q=-1;break a}b+=n;"undefined"!=typeof f&&(f+=n)}q=b}D[d>>2]=q;return 0}catch(p){if("undefined"==typeof Q||"ErrnoError"!==p.name)throw p;return p.Xa}},
da:function(){var a=stackTrace(),b=fb(a)+1,c=Pd(b);K(a,x,c,b);return c},ra:function(){var a=self.navigator.userAgent,b=fb(a)+1,c=Pd(b);K(a,x,c,b);return c},R:(a,b)=>{bb(x.subarray(a,a+b));return 0},N:ee,y:fe,O:ge,P:he,a:pa,ea:ae,T:(a,b,c,d)=>ae(a,b,c,d)},Z=function(){function a(c){Z=c.exports;Yc=Z.wa;ya.unshift(Z.sa);Ha("wasm-instantiate");return Z}var b={a:ie};Ga("wasm-instantiate");if(k.instantiateWasm)try{return k.instantiateWasm(b,a)}catch(c){v(`Module.instantiateWasm callback failed with error: ${c}`),
ba(c)}Pa(b,function(c){a(c.instance)}).catch(ba);return{}}(),bd=a=>(bd=Z.ta)(a),cd=a=>(cd=Z.ua)(a),Pd=a=>(Pd=Z.va)(a),Rd=a=>(Rd=Z.xa)(a),Qd=()=>(Qd=Z.ya)(),nb=(a,b)=>(nb=Z.za)(a,b),je=(a,b)=>(je=Z.Aa)(a,b),de=a=>(de=Z.Ba)(a),ke=a=>(ke=Z.Ca)(a),le=()=>(le=Z.Da)();k.dynCall_viijii=(a,b,c,d,e,f,g)=>(k.dynCall_viijii=Z.Ea)(a,b,c,d,e,f,g);k.dynCall_ji=(a,b)=>(k.dynCall_ji=Z.Fa)(a,b);k.dynCall_jiji=(a,b,c,d,e)=>(k.dynCall_jiji=Z.Ga)(a,b,c,d,e);
k.dynCall_iiiiij=(a,b,c,d,e,f,g)=>(k.dynCall_iiiiij=Z.Ha)(a,b,c,d,e,f,g);k.dynCall_iiiiijj=(a,b,c,d,e,f,g,l,m)=>(k.dynCall_iiiiijj=Z.Ia)(a,b,c,d,e,f,g,l,m);k.dynCall_iiiiiijj=(a,b,c,d,e,f,g,l,m,n)=>(k.dynCall_iiiiiijj=Z.Ja)(a,b,c,d,e,f,g,l,m,n);k.__ZN2MB2NN28LinearDefragmentingAllocator10Allocation4nullE=1024;k.___start_em_js=332124;k.___stop_em_js=332997;function fe(a,b){var c=le();try{U(a)(b)}catch(d){ke(c);if(d!==d+0)throw d;je(1,0)}}
function he(a,b,c,d){var e=le();try{U(a)(b,c,d)}catch(f){ke(e);if(f!==f+0)throw f;je(1,0)}}function ge(a,b,c){var d=le();try{U(a)(b,c)}catch(e){ke(d);if(e!==e+0)throw e;je(1,0)}}function ee(a,b,c,d){var e=le();try{return U(a)(b,c,d)}catch(f){ke(e);if(f!==f+0)throw f;je(1,0)}}k.addRunDependency=Ga;k.removeRunDependency=Ha;k.FS_createPath=fc;k.FS_createLazyFile=jc;k.FS_createDevice=hc;k.FS_createPreloadedFile=yb;k.FS_createDataFile=xb;k.FS_unlink=Wb;var me;Fa=function ne(){me||oe();me||(Fa=ne)};
function oe(){function a(){if(!me&&(me=!0,k.calledRun=!0,!qa)){k.noFSInit||ec||(ec=!0,k.stdin=k.stdin,k.stdout=k.stdout,k.stderr=k.stderr,k.stdin?hc("/dev","stdin",k.stdin):Vb("/dev/tty","/dev/stdin"),k.stdout?hc("/dev","stdout",null,k.stdout):Vb("/dev/tty","/dev/stdout"),k.stderr?hc("/dev","stderr",null,k.stderr):Vb("/dev/tty1","/dev/stderr"),$b("/dev/stdin",0),$b("/dev/stdout",1),$b("/dev/stderr",1));Fb=!1;Ta(ya);aa(k);if(k.onRuntimeInitialized)k.onRuntimeInitialized();if(k.postRun)for("function"==
typeof k.postRun&&(k.postRun=[k.postRun]);k.postRun.length;){var b=k.postRun.shift();Aa.unshift(b)}Ta(Aa)}}if(!(0<Da)){if(k.preRun)for("function"==typeof k.preRun&&(k.preRun=[k.preRun]);k.preRun.length;)Ca();Ta(xa);0<Da||(k.setStatus?(k.setStatus("Running..."),setTimeout(function(){setTimeout(function(){k.setStatus("")},1);a()},1)):a())}}if(k.preInit)for("function"==typeof k.preInit&&(k.preInit=[k.preInit]);0<k.preInit.length;)k.preInit.pop()();oe();
if("object"==typeof window&&("undefined"==typeof ENVIRONMENT_IS_PTHREAD||!ENVIRONMENT_IS_PTHREAD)){var pe=()=>{var a=0,b=!1,c=m=>{var n=new XMLHttpRequest;n.open("POST","stdio.html",!1);n.send(m);try{window.close()}catch(q){}},d=m=>{var n=new XMLHttpRequest;++a;n.onreadystatechange=()=>{4==n.readyState&&0==--a&&b&&c("^exit^"+ra)};n.open("POST","stdio.html",!0);n.send(m)};if(-1!=document.URL.search("localhost")||-1!=document.URL.search(":6931/")){var e=1,f=na,g=v;za.unshift(()=>{0==a?c("^exit^"+ra):
b=!0});na=m=>{d("^out^"+e++ +"^"+encodeURIComponent(m));f(m)};v=m=>{d("^err^"+e++ +"^"+encodeURIComponent(m));g(m)};var l=()=>{try{d("^pageload^")}catch(m){setTimeout(l,50)}};l()}};"undefined"!=typeof document&&pe()};


  return readyPromise
}
);
})();
if (typeof exports === 'object' && typeof module === 'object')
  module.exports = BlinkIDWasmSDK;
else if (typeof define === 'function' && define['amd'])
  define([], () => BlinkIDWasmSDK);
