
var BlinkIDWasmSDK = (() => {
  var _scriptDir = typeof document != 'undefined' ? document.currentScript?.src : undefined;
  
  return (
function(moduleArg = {}) {

/*

 Copyright 2019 The Emscripten Authors
 SPDX-License-Identifier: MIT

 Copyright 2024 The Emscripten Authors
 SPDX-License-Identifier: MIT

 Copyright 2013 The Emscripten Authors
 SPDX-License-Identifier: MIT

 This file gets implicatly injected as a `--post-js` file when
 emcc is run with `--emrun`
*/
function h(){v.buffer!=aa.buffer&&ba();return aa}function w(){v.buffer!=aa.buffer&&ba();return ca}function x(){v.buffer!=aa.buffer&&ba();return da}function ea(){v.buffer!=aa.buffer&&ba();return fa}function A(){v.buffer!=aa.buffer&&ba();return ha}function B(){v.buffer!=aa.buffer&&ba();return ia}function ja(){v.buffer!=aa.buffer&&ba();return ka}var D=moduleArg,la,ma,readyPromise=new Promise((a,b)=>{la=a;ma=b});D.mc||(D.mc=0);D.mc++;
D.ENVIRONMENT_IS_PTHREAD||D.$ww||function(a){function b(m,n,q){var p=new XMLHttpRequest;p.open("GET",m,!0);p.responseType="arraybuffer";p.onprogress=function(r){var k=n;r.total&&(k=r.total);if(r.loaded){p.Uc?D.Kb[m].loaded=r.loaded:(p.Uc=!0,D.Kb||(D.Kb={}),D.Kb[m]={loaded:r.loaded,total:k});var t=k=r=0,u;for(u in D.Kb){var z=D.Kb[u];r+=z.total;k+=z.loaded;t++}r=Math.ceil(r*D.mc/t);D.setStatus&&D.setStatus(`Downloading data... (${k}/${r})`)}else!D.Kb&&D.setStatus&&D.setStatus("Downloading data...")};
p.onerror=function(){throw Error("NetworkError for: "+m);};p.onload=function(){if(200==p.status||304==p.status||206==p.status||0==p.status&&p.response)q(p.response);else throw Error(p.statusText+" : "+p.responseURL);};p.send(null)}function c(m){console.error("package error:",m)}function d(){function m(r,k,t){this.start=r;this.end=k;this.audio=t}function n(r){if(!r)throw"Loading data file failed."+Error().stack;if(r.constructor.name!==ArrayBuffer.name)throw"bad input to processPackageData"+Error().stack;
r=new Uint8Array(r);m.prototype.Zc=r;r=a.files;for(var k=0;k<r.length;++k)m.prototype.tc[r[k].filename].onload();D.removeRunDependency("datafile_/opt/jenkins/android-arm64-huawei-p30-pro/root/E0/sdk-blinkid-in-browser/resources/lightweight/advanced-threads/BlinkIDWasmSDK.data")}D.FS_createPath("/","microblink",!0,!0);m.prototype={tc:{},open:function(r,k){this.name=k;this.tc[k]=this;D.addRunDependency(`fp ${this.name}`)},send:function(){},onload:function(){this.finish(this.Zc.subarray(this.start,this.end))},
finish:function(r){D.FS_createDataFile(this.name,null,r,!0,!0,!0);D.removeRunDependency(`fp ${this.name}`);this.tc[this.name]=null}};for(var q=a.files,p=0;p<q.length;++p)(new m(q[p].start,q[p].end,q[p].audio||0)).open("GET",q[p].filename);D.addRunDependency("datafile_/opt/jenkins/android-arm64-huawei-p30-pro/root/E0/sdk-blinkid-in-browser/resources/lightweight/advanced-threads/BlinkIDWasmSDK.data");D.Kc||(D.Kc={});D.Kc["/opt/jenkins/android-arm64-huawei-p30-pro/root/E0/sdk-blinkid-in-browser/resources/lightweight/advanced-threads/BlinkIDWasmSDK.data"]=
{Ud:!1};l?(n(l),l=null):g=n}"object"===typeof window?window.encodeURIComponent(window.location.pathname.toString().substring(0,window.location.pathname.toString().lastIndexOf("/"))+"/"):"undefined"===typeof process&&"undefined"!==typeof location&&encodeURIComponent(location.pathname.toString().substring(0,location.pathname.toString().lastIndexOf("/"))+"/");"function"!==typeof D.locateFilePackage||D.locateFile||(D.locateFile=D.locateFilePackage,E("warning: you defined Module.locateFilePackage, that has been renamed to Module.locateFile (using your locateFilePackage for now)"));
var e=D.locateFile?D.locateFile("BlinkIDWasmSDK.data",""):"BlinkIDWasmSDK.data",f=a.remote_package_size,g=null,l=D.getPreloadedPackage?D.getPreloadedPackage(e,f):null;l||b(e,f,function(m){g?(g(m),g=null):l=m},c);D.calledRun?d():(D.preRun||(D.preRun=[]),D.preRun.push(d))}({files:[{filename:"/microblink/Model_07c7ab860e77ec2e92bb822f6d62424b8595a5beb4340f6b2f7f6a4cffa5d050.strop",start:0,end:120418},{filename:"/microblink/Model_2880751121560047e6dc571bc8ff4683aeb863886f7c0789234594ceb1e23577.strop",
start:120418,end:124356},{filename:"/microblink/Model_28a32f25173781f9315925a0b1aae79cbe30fcb5971e870d548c0b07f505fa74.strop",start:124356,end:1033542},{filename:"/microblink/Model_36d8e94f4cb46097bd6b7385f2aa91fcdee1a5fefeec59e56d1b9e82c94b00a7.strop",start:1033542,end:1403338},{filename:"/microblink/Model_473ac5f5e256623c0a6b282698c1f1b033b9fb5359e6aa142e9fb4a4022afe4e.strop",start:1403338,end:1410220},{filename:"/microblink/Model_7449c8658cb4f2272b20b3e1e59488558badfb94d78ed9bc37bdaaffe7400078.strop",
start:1410220,end:1994516},{filename:"/microblink/Model_8c7727da554fd257fa758787ca3d0f517b47f6c5ba791792f516da7dd210fde8.strop",start:1994516,end:3103584},{filename:"/microblink/Model_b452fd3cd4037080cfcb4c423dba5bc58c8ceafc28427fdf9c5778fb353f088e.strop",start:3103584,end:3110434},{filename:"/microblink/Model_cf1186bbf6553c03f45bb0918ec5039629b4e4460941a917199f3b8ee0b115be.strop",start:3110434,end:6388670},{filename:"/microblink/Model_d2bcaf18d17504513598e04f472c035b3d4f22d8653d5a79c05b4508a4b547b3.strop",
start:6388670,end:6822186},{filename:"/microblink/Model_dc2c0f42def7aab10489790c240770787f9ef5580a2c4695402237ee9f17d12f.strop",start:6822186,end:6957580},{filename:"/microblink/Model_e4f1f62f68ec44b71ecad3fb3f3b48fe3790beb5ab325611e17d63af06e9f644.strop",start:6957580,end:7014094},{filename:"/microblink/Model_ed586fd6ca47c8eebb513c4ffaaacc2c54e92162b145062d7022519fba0911de.strop",start:7014094,end:7727326},{filename:"/microblink/Model_f2874f5766b779c063dbe30467979163497dc4b29c43bab23d70c798ee32993a.strop",
start:7727326,end:7808832},{filename:"/microblink/Model_faf688599c7e261a2a7404730f69ed029115bb0d3e7a3657731d88e701720efe.strop",start:7808832,end:7825570},{filename:"/microblink/ccc_lookup_table.zzip",start:7825570,end:7846039}],remote_package_size:7846039});D.onAbort=function(a){E("Aborted with message: "+a);try{throw new WebAssembly.RuntimeError(a);}catch(b){E("Stacktrace: "+b.stack)}};
if("object"==typeof window){D.arguments=window.location.search.substr(1).trim().split("&");for(let a=0;a<D.arguments.length;++a)D.arguments[a]=decodeURI(D.arguments[a]);D.arguments[0]||(D.arguments=[])}var na=Object.assign({},D),oa="./this.program",pa=(a,b)=>{throw b;},qa="object"==typeof window,ra="function"==typeof importScripts,sa="object"==typeof process&&"object"==typeof process.Ld&&"string"==typeof process.Ld.node,F=D.ENVIRONMENT_IS_PTHREAD||!1,ta="";
function ua(a){return D.locateFile?D.locateFile(a,ta):ta+a}var va,wa,xa;
if(qa||ra)ra?ta=self.location.href:"undefined"!=typeof document&&document.currentScript&&(ta=document.currentScript.src),_scriptDir&&(ta=_scriptDir),ta=ta.startsWith("blob:")?"":ta.substr(0,ta.replace(/[?#].*/,"").lastIndexOf("/")+1),va=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},ra&&(xa=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),wa=(a,b,c)=>{var d=new XMLHttpRequest;d.open("GET",
a,!0);d.responseType="arraybuffer";d.onload=()=>{200==d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)};var ya=D.print||console.log.bind(console),E=D.printErr||console.error.bind(console);Object.assign(D,na);na=null;D.thisProgram&&(oa=D.thisProgram);D.quit&&(pa=D.quit);var za;D.wasmBinary&&(za=D.wasmBinary);var v,Aa,Ba=!1,Ca,aa,ca,da,fa,ha,ia,Da,ka;
function ba(){var a=v.buffer;D.HEAP8=aa=new Int8Array(a);D.HEAP16=da=new Int16Array(a);D.HEAPU8=ca=new Uint8Array(a);D.HEAPU16=fa=new Uint16Array(a);D.HEAP32=ha=new Int32Array(a);D.HEAPU32=ia=new Uint32Array(a);D.HEAPF32=Da=new Float32Array(a);D.HEAPF64=ka=new Float64Array(a)}var Ea=D.INITIAL_MEMORY||209715200;
if(F)v=D.wasmMemory;else if(D.wasmMemory)v=D.wasmMemory;else if(v=new WebAssembly.Memory({initial:Ea/65536,maximum:32768,shared:!0}),!(v.buffer instanceof SharedArrayBuffer))throw E("requested a shared WebAssembly.Memory but the returned buffer is not a SharedArrayBuffer, indicating that while the browser has SharedArrayBuffer it does not have WebAssembly threads support - you may need to set a flag"),sa&&E("(on node you may need: --experimental-wasm-threads --experimental-wasm-bulk-memory and/or recent version)"),
Error("bad memory");ba();Ea=v.buffer.byteLength;var Fa=[],Ga=[],Ha=[],Ia=[],Ja=!1;function Ka(){F||(D.noFSInit||La||(La=!0,D.stdin=D.stdin,D.stdout=D.stdout,D.stderr=D.stderr,D.stdin?Ma("/dev","stdin",D.stdin):Na("/dev/tty","/dev/stdin"),D.stdout?Ma("/dev","stdout",null,D.stdout):Na("/dev/tty","/dev/stdout"),D.stderr?Ma("/dev","stderr",null,D.stderr):Na("/dev/tty1","/dev/stderr"),Oa("/dev/stdin",0),Oa("/dev/stdout",1),Oa("/dev/stderr",1)),Pa=!1,Qa(Ga))}var Ra=0,Sa=null,Ta=null;
function Ua(){Ra++;D.monitorRunDependencies?.(Ra)}function Va(){Ra--;D.monitorRunDependencies?.(Ra);if(0==Ra&&(null!==Sa&&(clearInterval(Sa),Sa=null),Ta)){var a=Ta;Ta=null;a()}}function Wa(a){D.onAbort?.(a);a="Aborted("+a+")";E(a);Ba=!0;Ca=1;a=new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");ma(a);throw a;}var Xa=a=>a.startsWith("data:application/octet-stream;base64,"),Ya;Ya="BlinkIDWasmSDK.wasm";Xa(Ya)||(Ya=ua(Ya));
function Za(a){if(a==Ya&&za)return new Uint8Array(za);if(xa)return xa(a);throw"both async and sync fetching of the wasm failed";}function ab(a){return za||!qa&&!ra||"function"!=typeof fetch?Promise.resolve().then(()=>Za(a)):fetch(a,{credentials:"same-origin"}).then(b=>{if(!b.ok)throw`failed to load wasm binary file at '${a}'`;return b.arrayBuffer()}).catch(()=>Za(a))}
function bb(a,b,c){return ab(a).then(d=>WebAssembly.instantiate(d,b)).then(c,d=>{E(`failed to asynchronously prepare wasm: ${d}`);Wa(d)})}function cb(a,b){var c=Ya;return za||"function"!=typeof WebAssembly.instantiateStreaming||Xa(c)||"function"!=typeof fetch?bb(c,a,b):fetch(c,{credentials:"same-origin"}).then(d=>WebAssembly.instantiateStreaming(d,a).then(b,function(e){E(`wasm streaming compile failed: ${e}`);E("falling back to ArrayBuffer instantiation");return bb(c,a,b)}))}
var G,H,db={334537:a=>{a=I(a);throw Error("Failed to reconfigure RecognizerRunner due to following error: "+a);},334673:(a,b,c,d)=>{a=I(a);b=I(b);c=I(c);d=I(d);throw Error(a+b+c+d);},334889:(a,b)=>{a=I(a);b=I(b);throw Error(a+b);},334999:()=>{throw Error("Ping Proxy permission not found in license!",{cause:"PERMISSION_NOT_GRANTED"});},335102:a=>{throw Error(I(a));},335145:()=>{throw Error("Unable to perform that operation while recognizer is in use!");},335228:()=>{throw Error("Unable to perform that operation while recognizer is in use!");
},335311:()=>{throw Error("Unable to perform that operation while recognizer is in use!");},335394:(a,b)=>{throw Error(I(a),{cause:I(b)});},335468:(a,b)=>{throw Error(I(a),{cause:I(b)});},335542:(a,b)=>{throw Error(I(a),{cause:I(b)});}};function eb(a){this.name="ExitStatus";this.message=`Program terminated with exit(${a})`;this.status=a}
var fb=a=>{a.terminate();a.onmessage=()=>{}},hb=a=>{0==J.Db.length&&(gb(),J.Hc(J.Db[0]));var b=J.Db.pop();if(!b)return 6;J.Hb.push(b);J.wb[a.Gb]=b;b.Gb=a.Gb;b.postMessage({cmd:"run",start_routine:a.Ed,arg:a.Vc,pthread_ptr:a.Gb},a.Jd);return 0},N=0,kb=a=>{var b=ib();a=a();jb(b);return a},lb=(a,b)=>b+2097152>>>0<4194305-!!a?(a>>>0)+4294967296*b:NaN,O=(a,b,...c)=>kb(()=>{for(var d=c.length,e=mb(8*d),f=e>>3,g=0;g<c.length;g++){var l=c[g];ja()[f+g]=l}return nb(a,0,d,e,b)});
function ob(a){if(F)return O(0,1,a);Ca=a;pb||0<N||(J.Rc(),D.onExit?.(a),Ba=!0);pa(a,new eb(a))}var vb=a=>{Ca=a;if(F)throw qb(a),"unwind";if(!(pb||0<N||F)){rb();Qa(Ha);La=!1;sb(0);for(var b=0;b<tb.length;b++){var c=tb[b];c&&ub(c)}J.Rc();Ja=!0}ob(a)};function wb(){J.receiveObjectTransfer=J.yd;J.threadInitTLS=J.Sc;J.setExitStatus=J.Qc;pb=!1}function xb(){for(var a=navigator.hardwareConcurrency;a--;)gb();Fa.unshift(()=>{Ua("loading-workers");yb(()=>Va("loading-workers"))})}
function gb(){var a=ua("BlinkIDWasmSDK.worker.js");a=new Worker(a);J.Db.push(a)}function yb(a){F?a():Promise.all(J.Db.map(J.Hc)).then(a)}
var J={Db:[],Hb:[],Tc:[],wb:{},Qc:a=>Ca=a,Zd:["$terminateWorker"],Rc:()=>{for(var a of J.Hb)fb(a);for(a of J.Db)fb(a);J.Db=[];J.Hb=[];J.wb=[]},Oc:a=>{var b=a.Gb;delete J.wb[b];J.Db.push(a);J.Hb.splice(J.Hb.indexOf(a),1);a.Gb=0;zb(b)},yd(){},Sc(){J.Tc.forEach(a=>a())},Hc:a=>new Promise(b=>{a.onmessage=f=>{f=f.data;var g=f.cmd;if(f.targetThread&&f.targetThread!=Ab()){var l=J.wb[f.targetThread];l?l.postMessage(f,f.transferList):E(`Internal error! Worker sent a message "${g}" to target pthread ${f.targetThread}, but that thread no longer exists!`)}else if("checkMailbox"===
g)Bb();else if("spawnThread"===g)hb(f);else if("cleanupThread"===g)J.Oc(J.wb[f.thread]);else if("killThread"===g)f=f.thread,g=J.wb[f],delete J.wb[f],fb(g),zb(f),J.Hb.splice(J.Hb.indexOf(g),1),g.Gb=0;else if("cancelThread"===g)J.wb[f.thread].postMessage({cmd:"cancel"});else if("loaded"===g)a.loaded=!0,b(a);else if("alert"===g)alert(`Thread ${f.threadId}: ${f.text}`);else if("setimmediate"===f.target)a.postMessage(f);else if("callHandler"===g)D[f.handler](...f.args);else g&&E(`worker sent an unknown command ${g}`)};
a.onerror=f=>{E(`${"worker sent an error!"} ${f.filename}:${f.lineno}: ${f.message}`);throw f;};var c=[],d=["onExit","onAbort","print","printErr"],e;for(e of d)D.hasOwnProperty(e)&&c.push(e);a.postMessage({cmd:"load",handlers:c,urlOrBlob:D.mainScriptUrlOrBlob||_scriptDir,wasmMemory:v,wasmModule:Aa})})};D.PThread=J;var Qa=a=>{for(;0<a.length;)a.shift()(D)};D.establishStackSpace=()=>{var a=Ab(),b=B()[a+52>>2];a=B()[a+56>>2];Cb(b,b-a);jb(b)};function qb(a){if(F)return O(1,0,a);vb(a)}
var Db=[],Eb,P=a=>{var b=Db[a];b||(a>=Db.length&&(Db.length=a+1),Db[a]=b=Eb.get(a));return b};D.invokeEntryPoint=(a,b)=>{N=0;a=P(a)(b);pb||0<N?J.Qc(a):Fb(a)};var pb=D.noExitRuntime||!1;function Gb(a,b,c,d){return F?O(2,1,a,b,c,d):Hb(a,b,c,d)}
var Hb=(a,b,c,d)=>{if("undefined"==typeof SharedArrayBuffer)return E("Current environment does not support SharedArrayBuffer, pthreads are not available!"),6;var e=[];if(F&&0===e.length)return Gb(a,b,c,d);a={Ed:c,Gb:a,Vc:d,Jd:e};return F?(a.Sd="spawnThread",postMessage(a,e),0):hb(a)};function Ib(){var a=A()[+Jb>>2];Jb+=4;return a}
var Kb=(a,b)=>{for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a},Lb=a=>{var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=Kb(a.split("/").filter(d=>!!d),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a},Mb=a=>{var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&=b.substr(0,b.length-1);return a+b},Nb=a=>{if("/"===
a)return"/";a=Lb(a);a=a.replace(/\/$/,"");var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)},Ob=()=>{if("object"==typeof crypto&&"function"==typeof crypto.getRandomValues)return a=>(a.set(crypto.getRandomValues(new Uint8Array(a.byteLength))),a);Wa("initRandomDevice")},Pb=a=>(Pb=Ob())(a),Qb=(...a)=>{for(var b="",c=!1,d=a.length-1;-1<=d&&!c;d--){c=0<=d?a[d]:"/";if("string"!=typeof c)throw new TypeError("Arguments to path.resolve must be strings");if(!c)return"";b=c+"/"+b;c="/"===c.charAt(0)}b=Kb(b.split("/").filter(e=>
!!e),!c).join("/");return(c?"/":"")+b||"."},Rb="undefined"!=typeof TextDecoder?new TextDecoder("utf8"):void 0,Sb=(a,b,c)=>{var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.buffer&&Rb)return Rb.decode(a.buffer instanceof SharedArrayBuffer?a.slice(b,c):a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var f=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|f);else{var g=a[b++]&63;e=224==(e&240)?(e&15)<<12|f<<6|g:(e&7)<<18|f<<12|g<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,
d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d},Tb=[],Ub=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},Q=(a,b,c,d)=>{if(!(0<d))return 0;var e=c;d=c+d-1;for(var f=0;f<a.length;++f){var g=a.charCodeAt(f);if(55296<=g&&57343>=g){var l=a.charCodeAt(++f);g=65536+((g&1023)<<10)|l&1023}if(127>=g){if(c>=d)break;b[c++]=g}else{if(2047>=g){if(c+1>=d)break;b[c++]=192|g>>6}else{if(65535>=
g){if(c+2>=d)break;b[c++]=224|g>>12}else{if(c+3>=d)break;b[c++]=240|g>>18;b[c++]=128|g>>12&63}b[c++]=128|g>>6&63}b[c++]=128|g&63}}b[c]=0;return c-e};function Vb(a,b){var c=Array(Ub(a)+1);a=Q(a,c,0,c.length);b&&(c.length=a);return c}var Wb=[];function Xb(a,b){Wb[a]={input:[],ob:[],Ab:b};Yb(a,Zb)}
var Zb={open(a){var b=Wb[a.node.Tb];if(!b)throw new S(43);a.jb=b;a.seekable=!1},close(a){a.jb.Ab.$b(a.jb)},$b(a){a.jb.Ab.$b(a.jb)},read(a,b,c,d){if(!a.jb||!a.jb.Ab.Fc)throw new S(60);for(var e=0,f=0;f<d;f++){try{var g=a.jb.Ab.Fc(a.jb)}catch(l){throw new S(29);}if(void 0===g&&0===e)throw new S(6);if(null===g||void 0===g)break;e++;b[c+f]=g}e&&(a.node.timestamp=Date.now());return e},write(a,b,c,d){if(!a.jb||!a.jb.Ab.qc)throw new S(60);try{for(var e=0;e<d;e++)a.jb.Ab.qc(a.jb,b[c+e])}catch(f){throw new S(29);
}d&&(a.node.timestamp=Date.now());return e}},$b={Fc(){a:{if(!Tb.length){var a=null;"undefined"!=typeof window&&"function"==typeof window.prompt?(a=window.prompt("Input: "),null!==a&&(a+="\n")):"function"==typeof readline&&(a=readline(),null!==a&&(a+="\n"));if(!a){a=null;break a}Tb=Vb(a,!0)}a=Tb.shift()}return a},qc(a,b){null===b||10===b?(ya(Sb(a.ob,0)),a.ob=[]):0!=b&&a.ob.push(b)},$b(a){a.ob&&0<a.ob.length&&(ya(Sb(a.ob,0)),a.ob=[])},nd(){return{Pd:25856,Rd:5,Od:191,Qd:35387,Nd:[3,28,127,21,4,0,1,
0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]}},od(){return 0},pd(){return[24,80]}},ac={qc(a,b){null===b||10===b?(E(Sb(a.ob,0)),a.ob=[]):0!=b&&a.ob.push(b)},$b(a){a.ob&&0<a.ob.length&&(E(Sb(a.ob,0)),a.ob=[])}},cc=a=>{a=65536*Math.ceil(a/65536);var b=bc(65536,a);b?w().fill(0,b,b+a):b=0;return b};function dc(a,b){var c=a.eb?a.eb.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)>>>0),0!=c&&(b=Math.max(b,256)),c=a.eb,a.eb=new Uint8Array(b),0<a.kb&&a.eb.set(c.subarray(0,a.kb),0))}
var T={vb:null,zb(){return T.createNode(null,"/",16895,0)},createNode(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new S(63);T.vb||(T.vb={dir:{node:{ub:T.fb.ub,rb:T.fb.rb,Pb:T.fb.Pb,cc:T.fb.cc,Nc:T.fb.Nc,kc:T.fb.kc,Pc:T.fb.Pc,Mc:T.fb.Mc,hc:T.fb.hc},stream:{Fb:T.gb.Fb}},file:{node:{ub:T.fb.ub,rb:T.fb.rb},stream:{Fb:T.gb.Fb,read:T.gb.read,write:T.gb.write,Wb:T.gb.Wb,Qb:T.gb.Qb,dc:T.gb.dc}},link:{node:{ub:T.fb.ub,rb:T.fb.rb,Ub:T.fb.Ub},stream:{}},zc:{node:{ub:T.fb.ub,rb:T.fb.rb},stream:ec}});
c=fc(a,b,c,d);gc(c.mode)?(c.fb=T.vb.dir.node,c.gb=T.vb.dir.stream,c.eb={}):32768===(c.mode&61440)?(c.fb=T.vb.file.node,c.gb=T.vb.file.stream,c.kb=0,c.eb=null):40960===(c.mode&61440)?(c.fb=T.vb.link.node,c.gb=T.vb.link.stream):8192===(c.mode&61440)&&(c.fb=T.vb.zc.node,c.gb=T.vb.zc.stream);c.timestamp=Date.now();a&&(a.eb[b]=c,a.timestamp=c.timestamp);return c},Vd(a){return a.eb?a.eb.subarray?a.eb.subarray(0,a.kb):new Uint8Array(a.eb):new Uint8Array(0)},fb:{ub(a){var b={};b.cd=8192===(a.mode&61440)?
a.id:1;b.Gc=a.id;b.mode=a.mode;b.ud=1;b.uid=0;b.kd=0;b.Tb=a.Tb;b.size=gc(a.mode)?4096:32768===(a.mode&61440)?a.kb:40960===(a.mode&61440)?a.link.length:0;b.Wc=new Date(a.timestamp);b.td=new Date(a.timestamp);b.ad=new Date(a.timestamp);b.Xc=4096;b.Yc=Math.ceil(b.size/b.Xc);return b},rb(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);if(void 0!==b.size&&(b=b.size,a.kb!=b))if(0==b)a.eb=null,a.kb=0;else{var c=a.eb;a.eb=new Uint8Array(b);c&&a.eb.set(c.subarray(0,Math.min(b,
a.kb)));a.kb=b}},Pb(){throw hc[44];},cc(a,b,c,d){return T.createNode(a,b,c,d)},Nc(a,b,c){if(gc(a.mode)){try{var d=ic(b,c)}catch(f){}if(d)for(var e in d.eb)throw new S(55);}delete a.parent.eb[a.name];a.parent.timestamp=Date.now();a.name=c;b.eb[c]=a;b.timestamp=a.parent.timestamp;a.parent=b},kc(a,b){delete a.eb[b];a.timestamp=Date.now()},Pc(a,b){var c=ic(a,b),d;for(d in c.eb)throw new S(55);delete a.eb[b];a.timestamp=Date.now()},Mc(a){var b=[".",".."],c;for(c of Object.keys(a.eb))b.push(c);return b},
hc(a,b,c){a=T.createNode(a,b,41471,0);a.link=c;return a},Ub(a){if(40960!==(a.mode&61440))throw new S(28);return a.link}},gb:{read(a,b,c,d,e){var f=a.node.eb;if(e>=a.node.kb)return 0;a=Math.min(a.node.kb-e,d);if(8<a&&f.subarray)b.set(f.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=f[e+d];return a},write(a,b,c,d,e,f){b.buffer===h().buffer&&(f=!1);if(!d)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&(!a.eb||a.eb.subarray)){if(f)return a.eb=b.subarray(c,c+d),a.kb=d;if(0===a.kb&&0===e)return a.eb=
b.slice(c,c+d),a.kb=d;if(e+d<=a.kb)return a.eb.set(b.subarray(c,c+d),e),d}dc(a,e+d);if(a.eb.subarray&&b.subarray)a.eb.set(b.subarray(c,c+d),e);else for(f=0;f<d;f++)a.eb[e+f]=b[c+f];a.kb=Math.max(a.kb,e+d);return d},Fb(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.kb);if(0>b)throw new S(28);return b},Wb(a,b,c){dc(a.node,b+c);a.node.kb=Math.max(a.node.kb,b+c)},Qb(a,b,c,d,e){if(32768!==(a.node.mode&61440))throw new S(43);a=a.node.eb;if(e&2||a.buffer!==h().buffer){if(0<c||
c+b<a.length)a=a.subarray?a.subarray(c,c+b):Array.prototype.slice.call(a,c,c+b);c=!0;b=cc(b);if(!b)throw new S(48);h().set(a,b)}else c=!1,b=a.byteOffset;return{ib:b,Bb:c}},dc(a,b,c,d){T.gb.write(a,b,0,d,c,!1);return 0}}},jc=(a,b,c)=>{var d=`al ${a}`;wa(a,e=>{b(new Uint8Array(e));d&&Va(d)},()=>{if(c)c();else throw`Loading data file "${a}" failed.`;});d&&Ua(d)},kc=D.preloadPlugins||[],lc=(a,b,c,d)=>{"undefined"!=typeof Browser&&(F?wb():xb());var e=!1;kc.forEach(f=>{!e&&f.canHandle(b)&&(f.handle(a,b,
c,d),e=!0)});return e},nc=(a,b,c,d,e,f,g,l,m,n)=>{function q(k){function t(u){n?.();l||mc(a,b,u,d,e,m);f?.();Va(r)}lc(k,p,t,()=>{g?.();Va(r)})||t(k)}var p=b?Qb(Lb(a+"/"+b)):a,r=`cp ${p}`;Ua(r);"string"==typeof c?jc(c,q,g):q(c)},oc=(a,b)=>{var c=0;a&&(c|=365);b&&(c|=146);return c},pc=null,qc={},tb=[],rc=1,sc=null,Pa=!0,S=class{constructor(a){this.name="ErrnoError";this.nb=a}},hc={},tc=class{constructor(){this.fc={};this.node=null}get object(){return this.node}set object(a){this.node=a}get flags(){return this.fc.flags}set flags(a){this.fc.flags=
a}get position(){return this.fc.position}set position(a){this.fc.position=a}},uc=class{constructor(a,b,c,d){a||=this;this.parent=a;this.zb=a.zb;this.Rb=null;this.id=rc++;this.name=b;this.mode=c;this.fb={};this.gb={};this.Tb=d;this.ec=365;this.lc=146}get read(){return(this.mode&this.ec)===this.ec}set read(a){a?this.mode|=this.ec:this.mode&=~this.ec}get write(){return(this.mode&this.lc)===this.lc}set write(a){a?this.mode|=this.lc:this.mode&=~this.lc}get rd(){return gc(this.mode)}get qd(){return 8192===
(this.mode&61440)}};function vc(a,b={}){a=Qb(a);if(!a)return{path:"",node:null};b=Object.assign({Dc:!0,sc:0},b);if(8<b.sc)throw new S(32);a=a.split("/").filter(g=>!!g);for(var c=pc,d="/",e=0;e<a.length;e++){var f=e===a.length-1;if(f&&b.parent)break;c=ic(c,a[e]);d=Lb(d+"/"+a[e]);c.Rb&&(!f||f&&b.Dc)&&(c=c.Rb.root);if(!f||b.Zb)for(f=0;40960===(c.mode&61440);)if(c=wc(d),d=Qb(Mb(d),c),c=vc(d,{sc:b.sc+1}).node,40<f++)throw new S(32);}return{path:d,node:c}}
function xc(a){for(var b;;){if(a===a.parent)return a=a.zb.Jc,b?"/"!==a[a.length-1]?`${a}/${b}`:a+b:a;b=b?`${a.name}/${b}`:a.name;a=a.parent}}function yc(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%sc.length}function ic(a,b){var c=gc(a.mode)?(c=zc(a,"x"))?c:a.fb.Pb?0:2:54;if(c)throw new S(c);for(c=sc[yc(a.id,b)];c;c=c.Nb){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.fb.Pb(a,b)}
function fc(a,b,c,d){a=new uc(a,b,c,d);b=yc(a.parent.id,a.name);a.Nb=sc[b];return sc[b]=a}function gc(a){return 16384===(a&61440)}function Ac(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}function zc(a,b){if(Pa)return 0;if(!b.includes("r")||a.mode&292){if(b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73))return 2}else return 2;return 0}function Bc(a,b){try{return ic(a,b),20}catch(c){}return zc(a,"wx")}function Cc(a){a=tb[a];if(!a)throw new S(8);return a}
function Dc(a,b=-1){a=Object.assign(new tc,a);if(-1==b)a:{for(b=0;4096>=b;b++)if(!tb[b])break a;throw new S(33);}a.Cb=b;return tb[b]=a}function Ec(a,b=-1){a=Dc(a,b);a.gb?.Td?.(a);return a}var ec={open(a){a.gb=qc[a.node.Tb].gb;a.gb.open?.(a)},Fb(){throw new S(70);}};function Yb(a,b){qc[a]={gb:b}}
function Fc(a,b){var c="/"===b;if(c&&pc)throw new S(10);if(!c&&b){var d=vc(b,{Dc:!1});b=d.path;d=d.node;if(d.Rb)throw new S(10);if(!gc(d.mode))throw new S(54);}b={type:a,Yd:{},Jc:b,sd:[]};a=a.zb(b);a.zb=b;b.root=a;c?pc=a:d&&(d.Rb=b,d.zb&&d.zb.sd.push(b))}function Gc(a,b,c){var d=vc(a,{parent:!0}).node;a=Nb(a);if(!a||"."===a||".."===a)throw new S(28);var e=Bc(d,a);if(e)throw new S(e);if(!d.fb.cc)throw new S(63);return d.fb.cc(d,a,b,c)}function Hc(a){return Gc(a,16895,0)}
function Ic(a,b,c){"undefined"==typeof c&&(c=b,b=438);return Gc(a,b|8192,c)}function Na(a,b){if(!Qb(a))throw new S(44);var c=vc(b,{parent:!0}).node;if(!c)throw new S(44);b=Nb(b);var d=Bc(c,b);if(d)throw new S(d);if(!c.fb.hc)throw new S(63);c.fb.hc(c,b,a)}
function Jc(a){var b=vc(a,{parent:!0}).node;if(!b)throw new S(44);var c=Nb(a);a=ic(b,c);a:{try{var d=ic(b,c)}catch(f){d=f.nb;break a}var e=zc(b,"wx");d=e?e:gc(d.mode)?31:0}if(d)throw new S(d);if(!b.fb.kc)throw new S(63);if(a.Rb)throw new S(10);b.fb.kc(b,c);b=yc(a.parent.id,a.name);if(sc[b]===a)sc[b]=a.Nb;else for(b=sc[b];b;){if(b.Nb===a){b.Nb=a.Nb;break}b=b.Nb}}function wc(a){a=vc(a).node;if(!a)throw new S(44);if(!a.fb.Ub)throw new S(28);return Qb(xc(a.parent),a.fb.Ub(a))}
function Kc(a,b){a=vc(a,{Zb:!b}).node;if(!a)throw new S(44);if(!a.fb.ub)throw new S(63);return a.fb.ub(a)}function Lc(a){return Kc(a,!0)}function Mc(a,b){a="string"==typeof a?vc(a,{Zb:!0}).node:a;if(!a.fb.rb)throw new S(63);a.fb.rb(a,{mode:b&4095|a.mode&-4096,timestamp:Date.now()})}
function Oa(a,b,c){if(""===a)throw new S(44);if("string"==typeof b){var d={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090}[b];if("undefined"==typeof d)throw Error(`Unknown file open mode: ${b}`);b=d}c=b&64?("undefined"==typeof c?438:c)&4095|32768:0;if("object"==typeof a)var e=a;else{a=Lb(a);try{e=vc(a,{Zb:!(b&131072)}).node}catch(f){}}d=!1;if(b&64)if(e){if(b&128)throw new S(20);}else e=Gc(a,c,0),d=!0;if(!e)throw new S(44);8192===(e.mode&61440)&&(b&=-513);if(b&65536&&!gc(e.mode))throw new S(54);if(!d&&
(c=e?40960===(e.mode&61440)?32:gc(e.mode)&&("r"!==Ac(b)||b&512)?31:zc(e,Ac(b)):44))throw new S(c);if(b&512&&!d){c=e;c="string"==typeof c?vc(c,{Zb:!0}).node:c;if(!c.fb.rb)throw new S(63);if(gc(c.mode))throw new S(31);if(32768!==(c.mode&61440))throw new S(28);if(d=zc(c,"w"))throw new S(d);c.fb.rb(c,{size:0,timestamp:Date.now()})}b&=-131713;e=Dc({node:e,path:xc(e),flags:b,seekable:!0,position:0,gb:e.gb,Kd:[],error:!1});e.gb.open&&e.gb.open(e);!D.logReadFiles||b&1||(Nc||={},a in Nc||(Nc[a]=1));return e}
function ub(a){if(null===a.Cb)throw new S(8);a.nc&&(a.nc=null);try{a.gb.close&&a.gb.close(a)}catch(b){throw b;}finally{tb[a.Cb]=null}a.Cb=null}function Oc(a,b,c){if(null===a.Cb)throw new S(8);if(!a.seekable||!a.gb.Fb)throw new S(70);if(0!=c&&1!=c&&2!=c)throw new S(28);a.position=a.gb.Fb(a,b,c);a.Kd=[]}
function Pc(a,b,c,d,e,f){if(0>d||0>e)throw new S(28);if(null===a.Cb)throw new S(8);if(0===(a.flags&2097155))throw new S(8);if(gc(a.node.mode))throw new S(31);if(!a.gb.write)throw new S(28);a.seekable&&a.flags&1024&&Oc(a,0,2);var g="undefined"!=typeof e;if(!g)e=a.position;else if(!a.seekable)throw new S(70);b=a.gb.write(a,b,c,d,e,f);g||(a.position+=b);return b}var La;
function Qc(a,b){a="string"==typeof a?a:xc(a);for(b=b.split("/").reverse();b.length;){var c=b.pop();if(c){var d=Lb(a+"/"+c);try{Hc(d)}catch(e){}a=d}}return d}function Rc(a,b,c,d){a=Lb(("string"==typeof a?a:xc(a))+"/"+b);c=oc(c,d);return Gc(a,(void 0!==c?c:438)&4095|32768,0)}
function mc(a,b,c,d,e,f){var g=b;a&&(a="string"==typeof a?a:xc(a),g=b?Lb(a+"/"+b):a);a=oc(d,e);g=Gc(g,(void 0!==a?a:438)&4095|32768,0);if(c){if("string"==typeof c){b=Array(c.length);d=0;for(e=c.length;d<e;++d)b[d]=c.charCodeAt(d);c=b}Mc(g,a|146);b=Oa(g,577);Pc(b,c,0,c.length,0,f);ub(b);Mc(g,a)}}
function Ma(a,b,c,d){a=Lb(("string"==typeof a?a:xc(a))+"/"+b);b=oc(!!c,!!d);Ma.Ic||(Ma.Ic=64);var e=Ma.Ic++<<8|0;Yb(e,{open(f){f.seekable=!1},close(){d?.buffer?.length&&d(10)},read(f,g,l,m){for(var n=0,q=0;q<m;q++){try{var p=c()}catch(r){throw new S(29);}if(void 0===p&&0===n)throw new S(6);if(null===p||void 0===p)break;n++;g[l+q]=p}n&&(f.node.timestamp=Date.now());return n},write(f,g,l,m){for(var n=0;n<m;n++)try{d(g[l+n])}catch(q){throw new S(29);}m&&(f.node.timestamp=Date.now());return n}});return Ic(a,
b,e)}function Sc(a){if(!(a.qd||a.rd||a.link||a.eb)){if("undefined"!=typeof XMLHttpRequest)throw Error("Lazy loading should have been performed (contents set) in createLazyFile, but it was not. Lazy loading only works in web workers. Use --embed-file or --preload-file in emcc on the main thread.");if(va)try{a.eb=Vb(va(a.url),!0),a.kb=a.eb.length}catch(b){throw new S(29);}else throw Error("Cannot load without read() or XMLHttpRequest.");}}
function Tc(a,b,c,d,e){function f(p,r,k,t,u){p=p.node.eb;if(u>=p.length)return 0;t=Math.min(p.length-u,t);if(p.slice)for(var z=0;z<t;z++)r[k+z]=p[u+z];else for(z=0;z<t;z++)r[k+z]=p.get(u+z);return t}class g{constructor(){this.pc=!1;this.Yb=[];this.Ob=void 0;this.wc=this.xc=0}get(p){if(!(p>this.length-1||0>p)){var r=p%this.Ac;return this.Ob(p/this.Ac|0)[r]}}zd(p){this.Ob=p}yc(){var p=new XMLHttpRequest;p.open("HEAD",c,!1);p.send(null);if(!(200<=p.status&&300>p.status||304===p.status))throw Error("Couldn't load "+
c+". Status: "+p.status);var r=Number(p.getResponseHeader("Content-length")),k,t=(k=p.getResponseHeader("Accept-Ranges"))&&"bytes"===k;p=(k=p.getResponseHeader("Content-Encoding"))&&"gzip"===k;var u=1048576;t||(u=r);var z=this;z.zd(M=>{var L=M*u,y=(M+1)*u-1;y=Math.min(y,r-1);if("undefined"==typeof z.Yb[M]){var R=z.Yb;if(L>y)throw Error("invalid range ("+L+", "+y+") or no bytes requested!");if(y>r-1)throw Error("only "+r+" bytes available! programmer error!");var C=new XMLHttpRequest;C.open("GET",
c,!1);r!==u&&C.setRequestHeader("Range","bytes="+L+"-"+y);C.responseType="arraybuffer";C.overrideMimeType&&C.overrideMimeType("text/plain; charset=x-user-defined");C.send(null);if(!(200<=C.status&&300>C.status||304===C.status))throw Error("Couldn't load "+c+". Status: "+C.status);L=void 0!==C.response?new Uint8Array(C.response||[]):Vb(C.responseText||"",!0);R[M]=L}if("undefined"==typeof z.Yb[M])throw Error("doXHR failed!");return z.Yb[M]});if(p||!r)u=r=1,u=r=this.Ob(0).length,ya("LazyFiles on gzip forces download of the whole file when length is accessed");
this.xc=r;this.wc=u;this.pc=!0}get length(){this.pc||this.yc();return this.xc}get Ac(){this.pc||this.yc();return this.wc}}if("undefined"!=typeof XMLHttpRequest){if(!ra)throw"Cannot do synchronous binary XHRs outside webworkers in modern browsers. Use --embed-file or --preload-file in emcc";var l=new g;var m=void 0}else m=c,l=void 0;var n=Rc(a,b,d,e);l?n.eb=l:m&&(n.eb=null,n.url=m);Object.defineProperties(n,{kb:{get:function(){return this.eb.length}}});var q={};Object.keys(n.gb).forEach(p=>{var r=
n.gb[p];q[p]=(...k)=>{Sc(n);return r(...k)}});q.read=(p,r,k,t,u)=>{Sc(n);return f(p,r,k,t,u)};q.Qb=(p,r,k)=>{Sc(n);var t=cc(r);if(!t)throw new S(48);f(p,h(),t,r,k);return{ib:t,Bb:!0}};n.gb=q;return n}var U={},Nc,I=(a,b)=>a?Sb(w(),a,b):"";function Uc(a,b,c){if("/"===b.charAt(0))return b;a=-100===a?"/":Cc(a).path;if(0==b.length){if(!c)throw new S(44);return a}return Lb(a+"/"+b)}
function Vc(a,b,c){a=a(b);A()[c>>2]=a.cd;A()[c+4>>2]=a.mode;B()[c+8>>2]=a.ud;A()[c+12>>2]=a.uid;A()[c+16>>2]=a.kd;A()[c+20>>2]=a.Tb;H=[a.size>>>0,(G=a.size,1<=+Math.abs(G)?0<G?+Math.floor(G/4294967296)>>>0:~~+Math.ceil((G-+(~~G>>>0))/4294967296)>>>0:0)];A()[c+24>>2]=H[0];A()[c+28>>2]=H[1];A()[c+32>>2]=4096;A()[c+36>>2]=a.Yc;b=a.Wc.getTime();var d=a.td.getTime(),e=a.ad.getTime();H=[Math.floor(b/1E3)>>>0,(G=Math.floor(b/1E3),1<=+Math.abs(G)?0<G?+Math.floor(G/4294967296)>>>0:~~+Math.ceil((G-+(~~G>>>
0))/4294967296)>>>0:0)];A()[c+40>>2]=H[0];A()[c+44>>2]=H[1];B()[c+48>>2]=b%1E3*1E3;H=[Math.floor(d/1E3)>>>0,(G=Math.floor(d/1E3),1<=+Math.abs(G)?0<G?+Math.floor(G/4294967296)>>>0:~~+Math.ceil((G-+(~~G>>>0))/4294967296)>>>0:0)];A()[c+56>>2]=H[0];A()[c+60>>2]=H[1];B()[c+64>>2]=d%1E3*1E3;H=[Math.floor(e/1E3)>>>0,(G=Math.floor(e/1E3),1<=+Math.abs(G)?0<G?+Math.floor(G/4294967296)>>>0:~~+Math.ceil((G-+(~~G>>>0))/4294967296)>>>0:0)];A()[c+72>>2]=H[0];A()[c+76>>2]=H[1];B()[c+80>>2]=e%1E3*1E3;H=[a.Gc>>>0,
(G=a.Gc,1<=+Math.abs(G)?0<G?+Math.floor(G/4294967296)>>>0:~~+Math.ceil((G-+(~~G>>>0))/4294967296)>>>0:0)];A()[c+88>>2]=H[0];A()[c+92>>2]=H[1];return 0}var Jb=void 0;
function Wc(a,b,c){if(F)return O(3,1,a,b,c);Jb=c;try{var d=Cc(a);switch(b){case 0:var e=Ib();if(0>e)break;for(;tb[e];)e++;return Ec(d,e).Cb;case 1:case 2:return 0;case 3:return d.flags;case 4:return e=Ib(),d.flags|=e,0;case 12:return e=Ib(),x()[e+0>>1]=2,0;case 13:case 14:return 0}return-28}catch(f){if("undefined"==typeof U||"ErrnoError"!==f.name)throw f;return-f.nb}}
function Xc(a,b){if(F)return O(4,1,a,b);try{var c=Cc(a);return Vc(Kc,c.path,b)}catch(d){if("undefined"==typeof U||"ErrnoError"!==d.name)throw d;return-d.nb}}
function Yc(a,b,c){if(F)return O(5,1,a,b,c);Jb=c;try{var d=Cc(a);switch(b){case 21509:return d.jb?0:-59;case 21505:if(!d.jb)return-59;if(d.jb.Ab.nd){a=[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0];var e=Ib();A()[e>>2]=25856;A()[e+4>>2]=5;A()[e+8>>2]=191;A()[e+12>>2]=35387;for(var f=0;32>f;f++)h()[e+f+17]=a[f]||0}return 0;case 21510:case 21511:case 21512:return d.jb?0:-59;case 21506:case 21507:case 21508:if(!d.jb)return-59;if(d.jb.Ab.od)for(e=Ib(),A(),A(),A(),A(),a=[],
f=0;32>f;f++)a.push(h()[e+f+17]);return 0;case 21519:if(!d.jb)return-59;e=Ib();return A()[e>>2]=0;case 21520:return d.jb?-28:-59;case 21531:e=Ib();if(!d.gb.md)throw new S(59);return d.gb.md(d,b,e);case 21523:if(!d.jb)return-59;d.jb.Ab.pd&&(f=[24,80],e=Ib(),x()[e>>1]=f[0],x()[e+2>>1]=f[1]);return 0;case 21524:return d.jb?0:-59;case 21515:return d.jb?0:-59;default:return-28}}catch(g){if("undefined"==typeof U||"ErrnoError"!==g.name)throw g;return-g.nb}}
function Zc(a,b){if(F)return O(6,1,a,b);try{return a=I(a),Vc(Lc,a,b)}catch(c){if("undefined"==typeof U||"ErrnoError"!==c.name)throw c;return-c.nb}}function $c(a,b,c,d){if(F)return O(7,1,a,b,c,d);try{b=I(b);var e=d&256;b=Uc(a,b,d&4096);return Vc(e?Lc:Kc,b,c)}catch(f){if("undefined"==typeof U||"ErrnoError"!==f.name)throw f;return-f.nb}}
function ad(a,b,c,d){if(F)return O(8,1,a,b,c,d);Jb=d;try{b=I(b);b=Uc(a,b);var e=d?Ib():0;return Oa(b,c,e).Cb}catch(f){if("undefined"==typeof U||"ErrnoError"!==f.name)throw f;return-f.nb}}function bd(a,b){if(F)return O(9,1,a,b);try{return a=I(a),Vc(Kc,a,b)}catch(c){if("undefined"==typeof U||"ErrnoError"!==c.name)throw c;return-c.nb}}var cd={},dd=a=>{for(;a.length;){var b=a.pop();a.pop()(b)}};function ed(a){return this.fromWireType(B()[a>>2])}
var fd={},gd={},hd={},jd,ld=(a,b,c)=>{function d(l){l=c(l);if(l.length!==a.length)throw new jd("Mismatched type converter count");for(var m=0;m<a.length;++m)kd(a[m],l[m])}a.forEach(function(l){hd[l]=b});var e=Array(b.length),f=[],g=0;b.forEach((l,m)=>{gd.hasOwnProperty(l)?e[m]=gd[l]:(f.push(l),fd.hasOwnProperty(l)||(fd[l]=[]),fd[l].push(()=>{e[m]=gd[l];++g;g===f.length&&d(e)}))});0===f.length&&d(e)},md,W=a=>{for(var b="";w()[a];)b+=md[w()[a++]];return b},X;
function nd(a,b,c={}){var d=b.name;if(!a)throw new X(`type "${d}" must have a positive integer typeid pointer`);if(gd.hasOwnProperty(a)){if(c.ld)return;throw new X(`Cannot register type '${d}' twice`);}gd[a]=b;delete hd[a];fd.hasOwnProperty(a)&&(b=fd[a],delete fd[a],b.forEach(e=>e()))}function kd(a,b,c={}){if(!("argPackAdvance"in b))throw new TypeError("registerType registeredInstance requires argPackAdvance");return nd(a,b,c)}
var od=a=>{throw new X(a.cb.lb.hb.name+" instance already deleted");},pd=!1,qd=()=>{},rd=(a,b,c)=>{if(b===c)return a;if(void 0===c.qb)return null;a=rd(a,b,c.qb);return null===a?null:c.dd(a)},sd={},td=[],ud=()=>{for(;td.length;){var a=td.pop();a.cb.Lb=!1;a["delete"]()}},vd,wd={},xd=(a,b)=>{if(void 0===b)throw new X("ptr should not be undefined");for(;a.qb;)b=a.Vb(b),a=a.qb;return wd[b]},zd=(a,b)=>{if(!b.lb||!b.ib)throw new jd("makeClassHandle requires ptr and ptrType");if(!!b.sb!==!!b.mb)throw new jd("Both smartPtrType and smartPtr must be specified");
b.count={value:1};return yd(Object.create(a,{cb:{value:b,writable:!0}}))},yd=a=>{if("undefined"===typeof FinalizationRegistry)return yd=b=>b,a;pd=new FinalizationRegistry(b=>{b=b.cb;--b.count.value;0===b.count.value&&(b.mb?b.sb.xb(b.mb):b.lb.hb.xb(b.ib))});yd=b=>{var c=b.cb;c.mb&&pd.register(b,{cb:c},b);return b};qd=b=>{pd.unregister(b)};return yd(a)};function Ad(){}
var Bd=(a,b)=>Object.defineProperty(b,"name",{value:a}),Cd=(a,b,c)=>{if(void 0===a[b].pb){var d=a[b];a[b]=function(...e){if(!a[b].pb.hasOwnProperty(e.length))throw new X(`Function '${c}' called with an invalid number of arguments (${e.length}) - expects one of (${a[b].pb})!`);return a[b].pb[e.length].apply(this,e)};a[b].pb=[];a[b].pb[d.Xb]=d}},Dd=(a,b,c)=>{if(D.hasOwnProperty(a)){if(void 0===c||void 0!==D[a].pb&&void 0!==D[a].pb[c])throw new X(`Cannot register public name '${a}' twice`);Cd(D,a,a);
if(D.hasOwnProperty(c))throw new X(`Cannot register multiple overloads of a function with the same number of arguments (${c})!`);D[a].pb[c]=b}else D[a]=b,void 0!==c&&(D[a].Xd=c)},Ed=a=>{if(void 0===a)return"_unknown";a=a.replace(/[^a-zA-Z0-9_]/g,"$");var b=a.charCodeAt(0);return 48<=b&&57>=b?`_${a}`:a};function Fd(a,b,c,d,e,f,g,l){this.name=a;this.constructor=b;this.Mb=c;this.xb=d;this.qb=e;this.fd=f;this.Vb=g;this.dd=l;this.wd=[]}
var Gd=(a,b,c)=>{for(;b!==c;){if(!b.Vb)throw new X(`Expected null or instance of ${c.name}, got an instance of ${b.name}`);a=b.Vb(a);b=b.qb}return a};function Hd(a,b){if(null===b){if(this.oc)throw new X(`null is not a valid ${this.name}`);return 0}if(!b.cb)throw new X(`Cannot pass "${Id(b)}" as a ${this.name}`);if(!b.cb.ib)throw new X(`Cannot pass deleted object as a pointer of type ${this.name}`);return Gd(b.cb.ib,b.cb.lb.hb,this.hb)}
function Jd(a,b){if(null===b){if(this.oc)throw new X(`null is not a valid ${this.name}`);if(this.bc){var c=this.rc();null!==a&&a.push(this.xb,c);return c}return 0}if(!b||!b.cb)throw new X(`Cannot pass "${Id(b)}" as a ${this.name}`);if(!b.cb.ib)throw new X(`Cannot pass deleted object as a pointer of type ${this.name}`);if(!this.ac&&b.cb.lb.ac)throw new X(`Cannot convert argument of type ${b.cb.sb?b.cb.sb.name:b.cb.lb.name} to parameter type ${this.name}`);c=Gd(b.cb.ib,b.cb.lb.hb,this.hb);if(this.bc){if(void 0===
b.cb.mb)throw new X("Passing raw pointer to smart pointer is illegal");switch(this.Dd){case 0:if(b.cb.sb===this)c=b.cb.mb;else throw new X(`Cannot convert argument of type ${b.cb.sb?b.cb.sb.name:b.cb.lb.name} to parameter type ${this.name}`);break;case 1:c=b.cb.mb;break;case 2:if(b.cb.sb===this)c=b.cb.mb;else{var d=b.clone();c=this.xd(c,Kd(()=>d["delete"]()));null!==a&&a.push(this.xb,c)}break;default:throw new X("Unsupporting sharing policy");}}return c}
function Ld(a,b){if(null===b){if(this.oc)throw new X(`null is not a valid ${this.name}`);return 0}if(!b.cb)throw new X(`Cannot pass "${Id(b)}" as a ${this.name}`);if(!b.cb.ib)throw new X(`Cannot pass deleted object as a pointer of type ${this.name}`);if(b.cb.lb.ac)throw new X(`Cannot convert argument of type ${b.cb.lb.name} to parameter type ${this.name}`);return Gd(b.cb.ib,b.cb.lb.hb,this.hb)}
function Md(a,b,c,d,e,f,g,l,m,n,q){this.name=a;this.hb=b;this.oc=c;this.ac=d;this.bc=e;this.vd=f;this.Dd=g;this.Lc=l;this.rc=m;this.xd=n;this.xb=q;e||void 0!==b.qb?this.toWireType=Jd:(this.toWireType=d?Hd:Ld,this.tb=null)}
var Nd=(a,b,c)=>{if(!D.hasOwnProperty(a))throw new jd("Replacing nonexistent public symbol");void 0!==D[a].pb&&void 0!==c?D[a].pb[c]=b:(D[a]=b,D[a].Xb=c)},Od=(a,b,c=[])=>{a.includes("j")?(a=a.replace(/p/g,"i"),b=(0,D["dynCall_"+a])(b,...c)):b=P(b)(...c);return b},Pd=(a,b)=>(...c)=>Od(a,b,c),Qd=(a,b)=>{a=W(a);var c=a.includes("j")?Pd(a,b):P(b);if("function"!=typeof c)throw new X(`unknown function pointer with signature ${a}: ${b}`);return c},Rd,Ud=a=>{a=Sd(a);var b=W(a);Td(a);return b},Vd=(a,b)=>{function c(f){e[f]||
gd[f]||(hd[f]?hd[f].forEach(c):(d.push(f),e[f]=!0))}var d=[],e={};b.forEach(c);throw new Rd(`${a}: `+d.map(Ud).join([", "]));},Wd=(a,b)=>{for(var c=[],d=0;d<a;d++)c.push(B()[b+4*d>>2]);return c};function Xd(a){for(var b=1;b<a.length;++b)if(null!==a[b]&&void 0===a[b].tb)return!0;return!1}
function Yd(a,b,c,d,e){var f=b.length;if(2>f)throw new X("argTypes array size mismatch! Must at least get return value and 'this' types!");var g=null!==b[1]&&null!==c,l=Xd(b),m="void"!==b[0].name,n=f-2,q=Array(n),p=[],r=[];return Bd(a,function(...k){if(k.length!==n)throw new X(`function ${a} called with ${k.length} arguments, expected ${n}`);r.length=0;p.length=g?2:1;p[0]=e;if(g){var t=b[1].toWireType(r,this);p[1]=t}for(var u=0;u<n;++u)q[u]=b[u+2].toWireType(r,k[u]),p.push(q[u]);k=d(...p);if(l)dd(r);
else for(u=g?1:2;u<b.length;u++){var z=1===u?t:q[u-2];null!==b[u].tb&&b[u].tb(z)}t=m?b[0].fromWireType(k):void 0;return t})}
var Zd=a=>{a=a.trim();const b=a.indexOf("(");return-1!==b?a.substr(0,b):a},$d=[],ae=[],be=a=>{9<a&&0===--ae[a+1]&&(ae[a]=void 0,$d.push(a))},Y=a=>{if(!a)throw new X("Cannot use deleted val. handle = "+a);return ae[a]},Kd=a=>{switch(a){case void 0:return 2;case null:return 4;case !0:return 6;case !1:return 8;default:const b=$d.pop()||ae.length;ae[b]=a;ae[b+1]=1;return b}},ce={name:"emscripten::val",fromWireType:a=>{var b=Y(a);be(a);return b},toWireType:(a,b)=>Kd(b),argPackAdvance:8,readValueFromPointer:ed,
tb:null},Id=a=>{if(null===a)return"null";var b=typeof a;return"object"===b||"array"===b||"function"===b?a.toString():""+a},de=(a,b)=>{switch(b){case 4:return function(c){var d=this.fromWireType;v.buffer!=aa.buffer&&ba();return d.call(this,Da[c>>2])};case 8:return function(c){return this.fromWireType(ja()[c>>3])};default:throw new TypeError(`invalid float width (${b}): ${a}`);}},ee=(a,b,c)=>{switch(b){case 1:return c?d=>h()[d]:d=>w()[d];case 2:return c?d=>x()[d>>1]:d=>ea()[d>>1];case 4:return c?d=>
A()[d>>2]:d=>B()[d>>2];default:throw new TypeError(`invalid integer width (${b}): ${a}`);}},fe=(a,b)=>{Q(a,w(),b,17)},ge="undefined"!=typeof TextDecoder?new TextDecoder("utf-16le"):void 0,he=(a,b)=>{var c=a>>1;for(var d=c+b/2;!(c>=d)&&ea()[c];)++c;c<<=1;if(32<c-a&&ge)return ge.decode(w().slice(a,c));c="";for(d=0;!(d>=b/2);++d){var e=x()[a+2*d>>1];if(0==e)break;c+=String.fromCharCode(e)}return c},ie=(a,b,c)=>{c??=2147483647;if(2>c)return 0;c-=2;var d=b;c=c<2*a.length?c/2:a.length;for(var e=0;e<c;++e){var f=
a.charCodeAt(e);x()[b>>1]=f;b+=2}x()[b>>1]=0;return b-d},je=a=>2*a.length,ke=(a,b)=>{for(var c=0,d="";!(c>=b/4);){var e=A()[a+4*c>>2];if(0==e)break;++c;65536<=e?(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023)):d+=String.fromCharCode(e)}return d},le=(a,b,c)=>{c??=2147483647;if(4>c)return 0;var d=b;c=d+c-4;for(var e=0;e<a.length;++e){var f=a.charCodeAt(e);if(55296<=f&&57343>=f){var g=a.charCodeAt(++e);f=65536+((f&1023)<<10)|g&1023}A()[b>>2]=f;b+=4;if(b+4>c)break}A()[b>>2]=0;return b-d},me=
a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&++c;b+=4}return b},ne=a=>{if(!Ja&&!Ba)try{if(a(),!(Ja||pb||0<N))try{F?Fb(Ca):vb(Ca)}catch(b){b instanceof eb||"unwind"==b||pa(1,b)}}catch(b){b instanceof eb||"unwind"==b||pa(1,b)}},oe=a=>{"function"===typeof Atomics.Md&&(Atomics.Md(A(),a>>2,a).value.then(Bb),a+=128,Atomics.store(A(),a>>2,1))};D.__emscripten_thread_mailbox_await=oe;var Bb=()=>{var a=Ab();a&&(oe(a),ne(pe))};D.checkMailbox=Bb;
var qe=[],re=(a,b)=>{var c=gd[a];if(void 0===c)throw a=`${b} has unknown type ${Ud(a)}`,new X(a);return c},se=(a,b,c)=>{var d=[];a=a.toWireType(d,c);d.length&&(B()[b>>2]=Kd(d));return a},te=[],ue={},ve=a=>{var b=ue[a];return void 0===b?W(a):b},we=()=>{function a(b){b.$$$embind_global$$$=b;var c="object"==typeof $$$embind_global$$$&&b.$$$embind_global$$$==b;c||delete b.$$$embind_global$$$;return c}if("object"==typeof globalThis)return globalThis;if("object"==typeof $$$embind_global$$$)return $$$embind_global$$$;
"object"==typeof global&&a(global)?$$$embind_global$$$=global:"object"==typeof self&&a(self)&&($$$embind_global$$$=self);if("object"==typeof $$$embind_global$$$)return $$$embind_global$$$;throw Error("unable to get global object.");},xe=a=>{var b=te.length;te.push(a);return b},ye=(a,b)=>{for(var c=Array(a),d=0;d<a;++d)c[d]=re(B()[b+4*d>>2],"parameter "+d);return c},ze=Reflect.construct,Ae=a=>0===a%4&&(0!==a%100||0===a%400),Be=[0,31,60,91,121,152,182,213,244,274,305,335],Ce=[0,31,59,90,120,151,181,
212,243,273,304,334],De=[];class Ee{constructor(){this.Bb=[void 0];this.Ec=[]}get(a){return this.Bb[a]}has(a){return void 0!==this.Bb[a]}Wb(a){var b=this.Ec.pop()||this.Bb.length;this.Bb[b]=a;return b}}function Fe(a,b){try{var c=indexedDB.open("emscripten_filesystem",1)}catch(d){b(d);return}c.onupgradeneeded=d=>{d=d.target.result;d.objectStoreNames.contains("FILES")&&d.deleteObjectStore("FILES");d.createObjectStore("FILES")};c.onsuccess=d=>a(d.target.result);c.onerror=b}var Ge,He;
function Ie(a,b,c,d,e){function f(){var C=0,V=0;y.response&&M&&0===B()[a+12>>2]&&(V=y.response.byteLength);0<V&&(C=Je(V),w().set(new Uint8Array(y.response),C));B()[a+12>>2]=C;Ke(a+16,V);Ke(a+24,0);(C=y.response?y.response.byteLength:0)&&Ke(a+32,C);x()[a+40>>1]=y.readyState;x()[a+42>>1]=y.status;y.statusText&&(C=a+44,Q(y.statusText,w(),C,64))}var g=B()[a+8>>2];if(g){var l=I(g),m=a+112,n=I(m+0);n||="GET";var q=B()[m+56>>2],p=B()[m+68>>2],r=B()[m+72>>2];g=B()[m+76>>2];var k=B()[m+80>>2],t=B()[m+84>>
2],u=B()[m+88>>2],z=B()[m+52>>2],M=!!(z&1),L=!!(z&2);z=!!(z&64);p=p?I(p):void 0;r=r?I(r):void 0;var y=new XMLHttpRequest;y.withCredentials=!!w()[m+60];y.open(n,l,!z,p,r);z||(y.timeout=q);y.ae=l;y.responseType="arraybuffer";k&&(l=I(k),y.overrideMimeType(l));if(g)for(;;){m=B()[g>>2];if(!m)break;l=B()[g+4>>2];if(!l)break;g+=8;m=I(m);l=I(l);y.setRequestHeader(m,l)}var R=Ge.Wb(y);B()[a>>2]=R;g=t&&u?w().slice(t,t+u):null;y.onload=C=>{Ge.has(R)&&(f(),200<=y.status&&300>y.status?b?.(a,y,C):c?.(a,y,C))};y.onerror=
C=>{Ge.has(R)&&(f(),c?.(a,y,C))};y.ontimeout=C=>{Ge.has(R)&&c?.(a,y,C)};y.onprogress=C=>{if(Ge.has(R)){var V=M&&L&&y.response?y.response.byteLength:0,K=0;0<V&&M&&L&&(K=Je(V),w().set(new Uint8Array(y.response),K));B()[a+12>>2]=K;Ke(a+16,V);Ke(a+24,C.loaded-V);Ke(a+32,C.total);x()[a+40>>1]=y.readyState;3<=y.readyState&&0===y.status&&0<C.loaded&&(y.status=200);x()[a+42>>1]=y.status;y.statusText&&(V=a+44,Q(y.statusText,w(),V,64));d?.(a,y,C);K&&Td(K)}};y.onreadystatechange=C=>{Ge.has(R)?(x()[a+40>>1]=
y.readyState,2<=y.readyState&&(x()[a+42>>1]=y.status),e?.(a,y,C)):--N};try{y.send(g)}catch(C){c?.(a,y,C)}}else c(a,0,"no url specified!")}var Ke=(a,b)=>{B()[a>>2]=b;var c=B()[a>>2];B()[a+4>>2]=(b-c)/4294967296};
function Le(a,b,c,d){var e=He;if(e){var f=a+112;(f=B()[f+64>>2])||(f=B()[a+8>>2]);var g=I(f);try{var l=e.transaction(["FILES"],"readwrite").objectStore("FILES").put(b,g);l.onsuccess=()=>{x()[a+40>>1]=4;x()[a+42>>1]=200;var m=a+44;Q("OK",w(),m,64);c(a,0,g)};l.onerror=m=>{x()[a+40>>1]=4;x()[a+42>>1]=413;var n=a+44;Q("Payload Too Large",w(),n,64);d(a,0,m)}}catch(m){d(a,0,m)}}else d(a,0,"IndexedDB not available!")}
function Me(a,b,c){var d=He;if(d){var e=a+112;(e=B()[e+64>>2])||(e=B()[a+8>>2]);e=I(e);try{var f=d.transaction(["FILES"],"readonly").objectStore("FILES").get(e);f.onsuccess=g=>{if(g.target.result){g=g.target.result;var l=g.byteLength||g.length,m=Je(l);w().set(new Uint8Array(g),m);B()[a+12>>2]=m;Ke(a+16,l);Ke(a+24,0);Ke(a+32,l);x()[a+40>>1]=4;x()[a+42>>1]=200;l=a+44;Q("OK",w(),l,64);b(a,0,g)}else x()[a+40>>1]=4,x()[a+42>>1]=404,g=a+44,Q("Not Found",w(),g,64),c(a,0,"no data")};f.onerror=g=>{x()[a+40>>
1]=4;x()[a+42>>1]=404;var l=a+44;Q("Not Found",w(),l,64);c(a,0,g)}}catch(g){c(a,0,g)}}else c(a,0,"IndexedDB not available!")}
function Ne(a,b,c){var d=He;if(d){var e=a+112;(e=B()[e+64>>2])||(e=B()[a+8>>2]);e=I(e);try{var f=d.transaction(["FILES"],"readwrite").objectStore("FILES").delete(e);f.onsuccess=g=>{g=g.target.result;B()[a+12>>2]=0;Ke(a+16,0);Ke(a+24,0);Ke(a+32,0);x()[a+40>>1]=4;x()[a+42>>1]=200;var l=a+44;Q("OK",w(),l,64);b(a,0,g)};f.onerror=g=>{x()[a+40>>1]=4;x()[a+42>>1]=404;var l=a+44;Q("Not Found",w(),l,64);c(a,0,g)}}catch(g){c(a,0,g)}}else c(a,0,"IndexedDB not available!")}
var Oe={},Qe=()=>{if(!Pe){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"==typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:oa||"./this.program"},b;for(b in Oe)void 0===Oe[b]?delete a[b]:a[b]=Oe[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);Pe=c}return Pe},Pe;
function Re(a,b){if(F)return O(12,1,a,b);var c=0;Qe().forEach((d,e)=>{var f=b+c;e=B()[a+4*e>>2]=f;for(f=0;f<d.length;++f)h()[e++]=d.charCodeAt(f);h()[e]=0;c+=d.length+1});return 0}function Se(a,b){if(F)return O(13,1,a,b);var c=Qe();B()[a>>2]=c.length;var d=0;c.forEach(e=>d+=e.length+1);B()[b>>2]=d;return 0}function Te(a){if(F)return O(14,1,a);try{var b=Cc(a);ub(b);return 0}catch(c){if("undefined"==typeof U||"ErrnoError"!==c.name)throw c;return c.nb}}
function Ue(a,b,c,d){if(F)return O(15,1,a,b,c,d);try{a:{var e=Cc(a);a=b;for(var f,g=b=0;g<c;g++){var l=B()[a>>2],m=B()[a+4>>2];a+=8;var n=e,q=h(),p=f;if(0>m||0>p)throw new S(28);if(null===n.Cb)throw new S(8);if(1===(n.flags&2097155))throw new S(8);if(gc(n.node.mode))throw new S(31);if(!n.gb.read)throw new S(28);var r="undefined"!=typeof p;if(!r)p=n.position;else if(!n.seekable)throw new S(70);var k=n.gb.read(n,q,l,m,p);r||(n.position+=k);var t=k;if(0>t){var u=-1;break a}b+=t;if(t<m)break;"undefined"!=
typeof f&&(f+=t)}u=b}B()[d>>2]=u;return 0}catch(z){if("undefined"==typeof U||"ErrnoError"!==z.name)throw z;return z.nb}}
function Ve(a,b,c,d,e){if(F)return O(16,1,a,b,c,d,e);b=lb(b,c);try{if(isNaN(b))return 61;var f=Cc(a);Oc(f,b,d);H=[f.position>>>0,(G=f.position,1<=+Math.abs(G)?0<G?+Math.floor(G/4294967296)>>>0:~~+Math.ceil((G-+(~~G>>>0))/4294967296)>>>0:0)];A()[e>>2]=H[0];A()[e+4>>2]=H[1];f.nc&&0===b&&0===d&&(f.nc=null);return 0}catch(g){if("undefined"==typeof U||"ErrnoError"!==g.name)throw g;return g.nb}}
function We(a,b,c,d){if(F)return O(17,1,a,b,c,d);try{a:{var e=Cc(a);a=b;for(var f,g=b=0;g<c;g++){var l=B()[a>>2],m=B()[a+4>>2];a+=8;var n=Pc(e,h(),l,m,f);if(0>n){var q=-1;break a}b+=n;"undefined"!=typeof f&&(f+=n)}q=b}B()[d>>2]=q;return 0}catch(p){if("undefined"==typeof U||"ErrnoError"!==p.name)throw p;return p.nb}}
var Xe=[31,29,31,30,31,30,31,31,30,31,30,31],Ye=[31,28,31,30,31,30,31,31,30,31,30,31],Ze=(a,b)=>{h().set(a,b)},$e=(a,b,c,d)=>{function e(k,t,u){for(k="number"==typeof k?k.toString():k||"";k.length<t;)k=u[0]+k;return k}function f(k,t){return e(k,t,"0")}function g(k,t){function u(M){return 0>M?-1:0<M?1:0}var z;0===(z=u(k.getFullYear()-t.getFullYear()))&&0===(z=u(k.getMonth()-t.getMonth()))&&(z=u(k.getDate()-t.getDate()));return z}function l(k){switch(k.getDay()){case 0:return new Date(k.getFullYear()-
1,11,29);case 1:return k;case 2:return new Date(k.getFullYear(),0,3);case 3:return new Date(k.getFullYear(),0,2);case 4:return new Date(k.getFullYear(),0,1);case 5:return new Date(k.getFullYear()-1,11,31);case 6:return new Date(k.getFullYear()-1,11,30)}}function m(k){var t=k.Ib;for(k=new Date((new Date(k.Jb+1900,0,1)).getTime());0<t;){var u=k.getMonth(),z=(Ae(k.getFullYear())?Xe:Ye)[u];if(t>z-k.getDate())t-=z-k.getDate()+1,k.setDate(1),11>u?k.setMonth(u+1):(k.setMonth(0),k.setFullYear(k.getFullYear()+
1));else{k.setDate(k.getDate()+t);break}}u=new Date(k.getFullYear()+1,0,4);t=l(new Date(k.getFullYear(),0,4));u=l(u);return 0>=g(t,k)?0>=g(u,k)?k.getFullYear()+1:k.getFullYear():k.getFullYear()-1}var n=B()[d+40>>2];d={Hd:A()[d>>2],Gd:A()[d+4>>2],ic:A()[d+8>>2],uc:A()[d+12>>2],jc:A()[d+16>>2],Jb:A()[d+20>>2],yb:A()[d+24>>2],Ib:A()[d+28>>2],$d:A()[d+32>>2],Fd:A()[d+36>>2],Id:n?I(n):""};c=I(c);n={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S",
"%x":"%m/%d/%y","%X":"%H:%M:%S","%Ec":"%c","%EC":"%C","%Ex":"%m/%d/%y","%EX":"%H:%M:%S","%Ey":"%y","%EY":"%Y","%Od":"%d","%Oe":"%e","%OH":"%H","%OI":"%I","%Om":"%m","%OM":"%M","%OS":"%S","%Ou":"%u","%OU":"%U","%OV":"%V","%Ow":"%w","%OW":"%W","%Oy":"%y"};for(var q in n)c=c.replace(new RegExp(q,"g"),n[q]);var p="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),r="January February March April May June July August September October November December".split(" ");n={"%a":k=>p[k.yb].substring(0,
3),"%A":k=>p[k.yb],"%b":k=>r[k.jc].substring(0,3),"%B":k=>r[k.jc],"%C":k=>f((k.Jb+1900)/100|0,2),"%d":k=>f(k.uc,2),"%e":k=>e(k.uc,2," "),"%g":k=>m(k).toString().substring(2),"%G":m,"%H":k=>f(k.ic,2),"%I":k=>{k=k.ic;0==k?k=12:12<k&&(k-=12);return f(k,2)},"%j":k=>{for(var t=0,u=0;u<=k.jc-1;t+=(Ae(k.Jb+1900)?Xe:Ye)[u++]);return f(k.uc+t,3)},"%m":k=>f(k.jc+1,2),"%M":k=>f(k.Gd,2),"%n":()=>"\n","%p":k=>0<=k.ic&&12>k.ic?"AM":"PM","%S":k=>f(k.Hd,2),"%t":()=>"\t","%u":k=>k.yb||7,"%U":k=>f(Math.floor((k.Ib+
7-k.yb)/7),2),"%V":k=>{var t=Math.floor((k.Ib+7-(k.yb+6)%7)/7);2>=(k.yb+371-k.Ib-2)%7&&t++;if(t)53==t&&(u=(k.yb+371-k.Ib)%7,4==u||3==u&&Ae(k.Jb)||(t=1));else{t=52;var u=(k.yb+7-k.Ib-1)%7;(4==u||5==u&&Ae(k.Jb%400-1))&&t++}return f(t,2)},"%w":k=>k.yb,"%W":k=>f(Math.floor((k.Ib+7-(k.yb+6)%7)/7),2),"%y":k=>(k.Jb+1900).toString().substring(2),"%Y":k=>k.Jb+1900,"%z":k=>{k=k.Fd;var t=0<=k;k=Math.abs(k)/60;return(t?"+":"-")+String("0000"+(k/60*100+k%60)).slice(-4)},"%Z":k=>k.Id,"%%":()=>"%"};c=c.replace(/%%/g,
"\x00\x00");for(q in n)c.includes(q)&&(c=c.replace(new RegExp(q,"g"),n[q](d)));c=c.replace(/\0\0/g,"%");q=Vb(c,!1);if(q.length>b)return 0;Ze(q,a);return q.length-1};F?wb():xb();[44].forEach(a=>{hc[a]=new S(a);hc[a].stack="<generic error, no stack>"});sc=Array(4096);Fc(T,"/");Hc("/tmp");Hc("/home");Hc("/home/web_user");
(function(){Hc("/dev");Yb(259,{read:()=>0,write:(d,e,f,g)=>g});Ic("/dev/null",259);Xb(1280,$b);Xb(1536,ac);Ic("/dev/tty",1280);Ic("/dev/tty1",1536);var a=new Uint8Array(1024),b=0,c=()=>{0===b&&(b=Pb(a).byteLength);return a[--b]};Ma("/dev","random",c);Ma("/dev","urandom",c);Hc("/dev/shm");Hc("/dev/shm/tmp")})();
(function(){Hc("/proc");var a=Hc("/proc/self");Hc("/proc/self/fd");Fc({zb(){var b=fc(a,"fd",16895,73);b.fb={Pb(c,d){var e=Cc(+d);c={parent:null,zb:{Jc:"fake"},fb:{Ub:()=>e.path}};return c.parent=c}};return b}},"/proc/self/fd")})();D.FS_createPath=Qc;D.FS_createDataFile=mc;D.FS_createPreloadedFile=nc;D.FS_unlink=Jc;D.FS_createLazyFile=Tc;D.FS_createDevice=Ma;jd=D.InternalError=class extends Error{constructor(a){super(a);this.name="InternalError"}};for(var af=Array(256),bf=0;256>bf;++bf)af[bf]=String.fromCharCode(bf);
md=af;X=D.BindingError=class extends Error{constructor(a){super(a);this.name="BindingError"}};
Object.assign(Ad.prototype,{isAliasOf:function(a){if(!(this instanceof Ad&&a instanceof Ad))return!1;var b=this.cb.lb.hb,c=this.cb.ib;a.cb=a.cb;var d=a.cb.lb.hb;for(a=a.cb.ib;b.qb;)c=b.Vb(c),b=b.qb;for(;d.qb;)a=d.Vb(a),d=d.qb;return b===d&&c===a},clone:function(){this.cb.ib||od(this);if(this.cb.Sb)return this.cb.count.value+=1,this;var a=yd,b=Object,c=b.create,d=Object.getPrototypeOf(this),e=this.cb;a=a(c.call(b,d,{cb:{value:{count:e.count,Lb:e.Lb,Sb:e.Sb,ib:e.ib,lb:e.lb,mb:e.mb,sb:e.sb}}}));a.cb.count.value+=
1;a.cb.Lb=!1;return a},["delete"](){this.cb.ib||od(this);if(this.cb.Lb&&!this.cb.Sb)throw new X("Object already scheduled for deletion");qd(this);var a=this.cb;--a.count.value;0===a.count.value&&(a.mb?a.sb.xb(a.mb):a.lb.hb.xb(a.ib));this.cb.Sb||(this.cb.mb=void 0,this.cb.ib=void 0)},isDeleted:function(){return!this.cb.ib},deleteLater:function(){this.cb.ib||od(this);if(this.cb.Lb&&!this.cb.Sb)throw new X("Object already scheduled for deletion");td.push(this);1===td.length&&vd&&vd(ud);this.cb.Lb=!0;
return this}});D.getInheritedInstanceCount=()=>Object.keys(wd).length;D.getLiveInheritedInstances=()=>{var a=[],b;for(b in wd)wd.hasOwnProperty(b)&&a.push(wd[b]);return a};D.flushPendingDeletes=ud;D.setDelayFunction=a=>{vd=a;td.length&&vd&&vd(ud)};
Object.assign(Md.prototype,{gd(a){this.Lc&&(a=this.Lc(a));return a},Bc(a){this.xb?.(a)},argPackAdvance:8,readValueFromPointer:ed,fromWireType:function(a){function b(){return this.bc?zd(this.hb.Mb,{lb:this.vd,ib:c,sb:this,mb:a}):zd(this.hb.Mb,{lb:this,ib:a})}var c=this.gd(a);if(!c)return this.Bc(a),null;var d=xd(this.hb,c);if(void 0!==d){if(0===d.cb.count.value)return d.cb.ib=c,d.cb.mb=a,d.clone();d=d.clone();this.Bc(a);return d}d=this.hb.fd(c);d=sd[d];if(!d)return b.call(this);d=this.ac?d.$c:d.pointerType;
var e=rd(c,this.hb,d.hb);return null===e?b.call(this):this.bc?zd(d.hb.Mb,{lb:d,ib:e,sb:this,mb:a}):zd(d.hb.Mb,{lb:d,ib:e})}});Rd=D.UnboundTypeError=((a,b)=>{var c=Bd(b,function(d){this.name=b;this.message=d;d=Error(d).stack;void 0!==d&&(this.stack=this.toString()+"\n"+d.replace(/^Error(:[^\n]*)?\n/,""))});c.prototype=Object.create(a.prototype);c.prototype.constructor=c;c.prototype.toString=function(){return void 0===this.message?this.name:`${this.name}: ${this.message}`};return c})(Error,"UnboundTypeError");
ae.push(0,1,void 0,1,null,1,!0,1,!1,1);D.count_emval_handles=()=>ae.length/2-5-$d.length;Ge=new Ee;F||(Ua("library_fetch_init"),Fe(a=>{He=a;Va("library_fetch_init")},()=>{He=!1;Va("library_fetch_init")}));
var cf=[ob,qb,Gb,Wc,Xc,Yc,Zc,$c,ad,bd,function(a,b,c,d,e,f,g,l){if(F)return O(10,1,a,b,c,d,e,f,g,l);e=lb(e,f);try{if(isNaN(e))return 61;var m=Cc(d);if(0!==(b&2)&&0===(c&2)&&2!==(m.flags&2097155))throw new S(2);if(1===(m.flags&2097155))throw new S(2);if(!m.gb.Qb)throw new S(43);var n=m.gb.Qb(m,a,e,b,c);var q=n.ib;A()[g>>2]=n.Bb;B()[l>>2]=q;return 0}catch(p){if("undefined"==typeof U||"ErrnoError"!==p.name)throw p;return-p.nb}},function(a,b,c,d,e,f,g){if(F)return O(11,1,a,b,c,d,e,f,g);f=lb(f,g);try{var l=
Cc(e);if(c&2){if(32768!==(l.node.mode&61440))throw new S(43);if(!(d&2)){var m=w().slice(a,a+b);l.gb.dc&&l.gb.dc(l,m,f,b,d)}}}catch(n){if("undefined"==typeof U||"ErrnoError"!==n.name)throw n;return-n.nb}},Re,Se,Te,Ue,Ve,We],lf={ca:a=>{df(a,!ra,1,!qa,5242880,!1);J.Sc()},B:a=>{F?postMessage({cmd:"cleanupThread",thread:a}):J.Oc(J.wb[a])},$:Hb,E:Wc,ia:Xc,ja:Yc,ga:Zc,fa:$c,F:ad,ha:bd,d:a=>{var b=cd[a];delete cd[a];var c=b.rc,d=b.xb,e=b.Cc,f=e.map(g=>g.jd).concat(e.map(g=>g.Bd));ld([a],f,g=>{var l={};e.forEach((m,
n)=>{var q=g[n],p=m.Ob,r=m.hd,k=g[n+e.length],t=m.Ad,u=m.Cd;l[m.ed]={read:z=>q.fromWireType(p(r,z)),write:(z,M)=>{var L=[];t(u,z,k.toWireType(L,M));dd(L)}}});return[{name:b.name,fromWireType:m=>{var n={},q;for(q in l)n[q]=l[q].read(m);d(m);return n},toWireType:(m,n)=>{for(var q in l)if(!(q in n))throw new TypeError(`Missing field: "${q}"`);var p=c();for(q in l)l[q].write(p,n[q]);null!==m&&m.push(d,p);return p},argPackAdvance:8,readValueFromPointer:ed,tb:d}]})},P:()=>{},L:(a,b,c,d)=>{b=W(b);kd(a,{name:b,
fromWireType:function(e){return!!e},toWireType:function(e,f){return f?c:d},argPackAdvance:8,readValueFromPointer:function(e){return this.fromWireType(w()[e])},tb:null})},p:(a,b,c,d,e,f,g,l,m,n,q,p,r)=>{q=W(q);f=Qd(e,f);l&&=Qd(g,l);n&&=Qd(m,n);r=Qd(p,r);var k=Ed(q);Dd(k,function(){Vd(`Cannot construct ${q} due to unbound types`,[d])});ld([a,b,c],d?[d]:[],t=>{t=t[0];if(d){var u=t.hb;var z=u.Mb}else z=Ad.prototype;t=Bd(q,function(...R){if(Object.getPrototypeOf(this)!==M)throw new X("Use 'new' to construct "+
q);if(void 0===L.Eb)throw new X(q+" has no accessible constructor");var C=L.Eb[R.length];if(void 0===C)throw new X(`Tried to invoke ctor of ${q} with invalid number of parameters (${R.length}) - expected (${Object.keys(L.Eb).toString()}) parameters instead!`);return C.apply(this,R)});var M=Object.create(z,{constructor:{value:t}});t.prototype=M;var L=new Fd(q,t,M,r,u,f,l,n);if(L.qb){var y;(y=L.qb).vc??(y.vc=[]);L.qb.vc.push(L)}u=new Md(q,L,!0,!1,!1);y=new Md(q+"*",L,!1,!1,!1);z=new Md(q+" const*",
L,!1,!0,!1);sd[a]={pointerType:y,$c:z};Nd(k,t);return[u,y,z]})},r:(a,b,c,d,e,f)=>{var g=Wd(b,c);e=Qd(d,e);ld([],[a],l=>{l=l[0];var m=`constructor ${l.name}`;void 0===l.hb.Eb&&(l.hb.Eb=[]);if(void 0!==l.hb.Eb[b-1])throw new X(`Cannot register multiple constructors with identical number of parameters (${b-1}) for class '${l.name}'! Overload resolution is currently only performed using the parameter count, not actual type info!`);l.hb.Eb[b-1]=()=>{Vd(`Cannot construct ${l.name} due to unbound types`,
g)};ld([],g,n=>{n.splice(1,0,null);l.hb.Eb[b-1]=Yd(m,n,null,e,f);return[]});return[]})},h:(a,b,c,d,e,f,g,l)=>{var m=Wd(c,d);b=W(b);b=Zd(b);f=Qd(e,f);ld([],[a],n=>{function q(){Vd(`Cannot call ${p} due to unbound types`,m)}n=n[0];var p=`${n.name}.${b}`;b.startsWith("@@")&&(b=Symbol[b.substring(2)]);l&&n.hb.wd.push(b);var r=n.hb.Mb,k=r[b];void 0===k||void 0===k.pb&&k.className!==n.name&&k.Xb===c-2?(q.Xb=c-2,q.className=n.name,r[b]=q):(Cd(r,b,p),r[b].pb[c-2]=q);ld([],m,t=>{t=Yd(p,t,n,f,g);void 0===r[b].pb?
(t.Xb=c-2,r[b]=t):r[b].pb[c-2]=t;return[]});return[]})},Aa:a=>kd(a,ce),K:(a,b,c)=>{b=W(b);kd(a,{name:b,fromWireType:d=>d,toWireType:(d,e)=>e,argPackAdvance:8,readValueFromPointer:de(b,c),tb:null})},w:(a,b,c,d,e,f)=>{var g=Wd(b,c);a=W(a);a=Zd(a);e=Qd(d,e);Dd(a,function(){Vd(`Cannot call ${a} due to unbound types`,g)},b-1);ld([],g,l=>{Nd(a,Yd(a,[l[0],null].concat(l.slice(1)),null,e,f),b-1);return[]})},n:(a,b,c,d,e)=>{b=W(b);-1===e&&(e=4294967295);e=l=>l;if(0===d){var f=32-8*c;e=l=>l<<f>>>f}var g=b.includes("unsigned")?
function(l,m){return m>>>0}:function(l,m){return m};kd(a,{name:b,fromWireType:e,toWireType:g,argPackAdvance:8,readValueFromPointer:ee(b,c,0!==d),tb:null})},g:(a,b,c)=>{function d(f){var g=B()[f>>2];f=B()[f+4>>2];return new e(h().buffer,f,g)}var e=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array][b];c=W(c);kd(a,{name:c,fromWireType:d,argPackAdvance:8,readValueFromPointer:d},{ld:!0})},z:(a,b)=>{b=W(b);var c="std::string"===b;kd(a,{name:b,fromWireType:function(d){var e=
B()[d>>2],f=d+4;if(c)for(var g=f,l=0;l<=e;++l){var m=f+l;if(l==e||0==w()[m]){g=I(g,m-g);if(void 0===n)var n=g;else n+=String.fromCharCode(0),n+=g;g=m+1}}else{n=Array(e);for(l=0;l<e;++l)n[l]=String.fromCharCode(w()[f+l]);n=n.join("")}Td(d);return n},toWireType:function(d,e){e instanceof ArrayBuffer&&(e=new Uint8Array(e));var f="string"==typeof e;if(!(f||e instanceof Uint8Array||e instanceof Uint8ClampedArray||e instanceof Int8Array))throw new X("Cannot pass non-string to std::string");var g=c&&f?Ub(e):
e.length;var l=Je(4+g+1),m=l+4;B()[l>>2]=g;if(c&&f)g+=1,Q(e,w(),m,g);else if(f)for(f=0;f<g;++f){var n=e.charCodeAt(f);if(255<n)throw Td(m),new X("String has UTF-16 code units that do not fit in 8 bits");w()[m+f]=n}else for(f=0;f<g;++f)w()[m+f]=e[f];null!==d&&d.push(Td,l);return l},argPackAdvance:8,readValueFromPointer:ed,tb(d){Td(d)}})},x:(a,b,c)=>{c=W(c);if(2===b){var d=he;var e=ie;var f=je;var g=l=>ea()[l>>1]}else 4===b&&(d=ke,e=le,f=me,g=l=>B()[l>>2]);kd(a,{name:c,fromWireType:l=>{for(var m=B()[l>>
2],n,q=l+4,p=0;p<=m;++p){var r=l+4+p*b;if(p==m||0==g(r))q=d(q,r-q),void 0===n?n=q:(n+=String.fromCharCode(0),n+=q),q=r+b}Td(l);return n},toWireType:(l,m)=>{if("string"!=typeof m)throw new X(`Cannot pass non-string to C++ string type ${c}`);var n=f(m),q=Je(4+n+b);B()[q>>2]=n/b;e(m,q+4,n+b);null!==l&&l.push(Td,q);return q},argPackAdvance:8,readValueFromPointer:ed,tb(l){Td(l)}})},e:(a,b,c,d,e,f)=>{cd[a]={name:W(b),rc:Qd(c,d),xb:Qd(e,f),Cc:[]}},c:(a,b,c,d,e,f,g,l,m,n)=>{cd[a].Cc.push({ed:W(b),jd:c,Ob:Qd(d,
e),hd:f,Bd:g,Ad:Qd(l,m),Cd:n})},V:(a,b)=>{b=W(b);kd(a,{Wd:!0,name:b,argPackAdvance:0,fromWireType:()=>{},toWireType:()=>{}})},pa:function(a){if(Ge.has(a)){var b=Ge.get(a),c=Ge;c.Bb[a]=void 0;c.Ec.push(a);0<b.readyState&&4>b.readyState&&b.abort()}},ma:()=>1,Z:(a,b)=>{a==b?setTimeout(Bb):F?postMessage({targetThread:a,cmd:"checkMailbox"}):(a=J.wb[a])&&a.postMessage({cmd:"checkMailbox"})},aa:(a,b,c,d,e)=>{qe.length=d;e>>=3;for(var f=0;f<d;f++)qe[f]=ja()[e+f];a=b?db[b]:cf[a];J.bd=c;c=a(...qe);J.bd=0;return c},
ba:oe,la:()=>{},T:()=>{throw Infinity;},j:(a,b,c)=>{a=Y(a);b=re(b,"emval::as");return se(b,c,a)},q:(a,b,c,d)=>{a=te[a];b=Y(b);return a(null,b,c,d)},o:(a,b,c,d,e)=>{a=te[a];b=Y(b);c=ve(c);return a(b,b[c],d,e)},ya:be,I:(a,b)=>{a=Y(a);b=Y(b);return a==b},ta:a=>{if(0===a)return Kd(we());a=ve(a);return Kd(we()[a])},k:(a,b,c)=>{var d=ye(a,b),e=d.shift();a--;var f=Array(a);b=`methodCaller<(${d.map(g=>g.name).join(", ")}) => ${e.name}>`;return xe(Bd(b,(g,l,m,n)=>{for(var q=0,p=0;p<a;++p)f[p]=d[p].readValueFromPointer(n+
q),q+=d[p].argPackAdvance;g=1===c?ze(l,f):l.apply(g,f);return se(e,m,g)}))},s:(a,b)=>{a=Y(a);b=Y(b);return Kd(a[b])},J:a=>{9<a&&(ae[a+1]+=1)},ua:(a,b)=>{a=Y(a);b=Y(b);return a instanceof b},va:()=>Kd([]),sa:a=>Kd(ve(a)),za:()=>Kd({}),xa:a=>{var b=Y(a);dd(b);be(a)},f:(a,b,c)=>{a=Y(a);b=Y(b);c=Y(c);a[b]=c},i:(a,b)=>{a=re(a,"_emval_take_value");a=a.readValueFromPointer(b);return Kd(a)},ra:a=>{a=Y(a);return Kd(typeof a)},M:function(a,b,c){a=new Date(1E3*lb(a,b));A()[c>>2]=a.getSeconds();A()[c+4>>2]=a.getMinutes();
A()[c+8>>2]=a.getHours();A()[c+12>>2]=a.getDate();A()[c+16>>2]=a.getMonth();A()[c+20>>2]=a.getFullYear()-1900;A()[c+24>>2]=a.getDay();b=(Ae(a.getFullYear())?Be:Ce)[a.getMonth()]+a.getDate()-1|0;A()[c+28>>2]=b;A()[c+36>>2]=-(60*a.getTimezoneOffset());b=(new Date(a.getFullYear(),6,1)).getTimezoneOffset();var d=(new Date(a.getFullYear(),0,1)).getTimezoneOffset();a=(b!=d&&a.getTimezoneOffset()==Math.min(d,b))|0;A()[c+32>>2]=a},N:function(a){var b=new Date(A()[a+20>>2]+1900,A()[a+16>>2],A()[a+12>>2],A()[a+
8>>2],A()[a+4>>2],A()[a>>2],0),c=A()[a+32>>2],d=b.getTimezoneOffset(),e=(new Date(b.getFullYear(),6,1)).getTimezoneOffset(),f=(new Date(b.getFullYear(),0,1)).getTimezoneOffset(),g=Math.min(f,e);0>c?A()[a+32>>2]=Number(e!=f&&g==d):0<c!=(g==d)&&(e=Math.max(f,e),b.setTime(b.getTime()+6E4*((0<c?g:e)-d)));A()[a+24>>2]=b.getDay();c=(Ae(b.getFullYear())?Be:Ce)[b.getMonth()]+b.getDate()-1|0;A()[a+28>>2]=c;A()[a>>2]=b.getSeconds();A()[a+4>>2]=b.getMinutes();A()[a+8>>2]=b.getHours();A()[a+12>>2]=b.getDate();
A()[a+16>>2]=b.getMonth();A()[a+20>>2]=b.getYear();a=b.getTime();a=isNaN(a)?-1:a/1E3;ef((G=a,1<=+Math.abs(G)?0<G?+Math.floor(G/4294967296)>>>0:~~+Math.ceil((G-+(~~G>>>0))/4294967296)>>>0:0));return a>>>0},Y:(a,b,c,d)=>{var e=(new Date).getFullYear(),f=new Date(e,0,1),g=new Date(e,6,1);e=f.getTimezoneOffset();var l=g.getTimezoneOffset(),m=Math.max(e,l);B()[a>>2]=60*m;A()[b>>2]=Number(e!=l);a=n=>n.toLocaleTimeString(void 0,{hour12:!1,timeZoneName:"short"}).split(" ")[1];f=a(f);g=a(g);l<e?(fe(f,c),fe(g,
d)):(fe(f,d),fe(g,c))},b:()=>{Wa("")},y:function(){var a=D.allowedThreads;return a?a:navigator.hardwareConcurrency},l:(a,b,c)=>{De.length=0;for(var d;d=w()[b++];){var e=105!=d;e&=112!=d;c+=e&&c%8?4:0;De.push(112==d?B()[c>>2]:105==d?A()[c>>2]:ja()[c>>3]);c+=e?8:4}return db[a](...De)},C:()=>{},G:()=>Date.now(),ka:()=>{N+=1;throw"unwind";},_:()=>2147483648,m:()=>performance.timeOrigin+performance.now(),H:()=>"undefined"!=typeof SharedArrayBuffer,X:a=>{var b=w().length;a>>>=0;if(a<=b||2147483648<a)return!1;
for(var c=1;4>=c;c*=2){var d=Math,e=Math.max(a,b+2097152/c);a:{d=(d.min.call(d,2147483648,e+(65536-e%65536)%65536)-v.buffer.byteLength+65535)/65536;try{v.grow(d);ba();var f=1;break a}catch(g){}f=void 0}if(f)return!0}return!1},qa:function(a,b,c,d,e){function f(K){r?K():ne(K)}N+=1;var g=a+112,l=B()[g+36>>2],m=B()[g+40>>2],n=B()[g+44>>2],q=B()[g+48>>2],p=B()[g+52>>2],r=!!(p&64),k=K=>{--N;f(()=>{l?P(l)(K):b?.(K)})},t=K=>{f(()=>{n?P(n)(K):d?.(K)})},u=K=>{--N;f(()=>{m?P(m)(K):c?.(K)})},z=K=>{f(()=>{q?P(q)(K):
e?.(K)})},M=K=>{Ie(K,k,u,t,z)},L=(K,jf)=>{Le(K,jf.response,$a=>{--N;f(()=>{l?P(l)($a):b?.($a)})},$a=>{--N;f(()=>{l?P(l)($a):b?.($a)})})},y=K=>{Ie(K,L,u,t,z)},R=I(g+0),C=!!(p&16),V=!!(p&4);p=!!(p&32);if("EM_IDB_STORE"===R)M=B()[g+84>>2],g=B()[g+88>>2],Le(a,w().slice(M,M+g),k,u);else if("EM_IDB_DELETE"===R)Ne(a,k,u);else if(C){if(p)return 0;Ie(a,V?L:k,u,t,z)}else Me(a,k,p?u:V?y:M);return a},da:Re,ea:Se,v:vb,u:Te,D:Ue,O:Ve,t:We,na:function(){var a=stackTrace(),b=Ub(a)+1,c=Je(b);Q(a,w(),c,b);return c},
wa:function(){var a=self.navigator.userAgent,b=Ub(a)+1,c=Je(b);Q(a,w(),c,b);return c},U:(a,b)=>{Pb(w().subarray(a,a+b));return 0},Q:ff,A:gf,R:hf,S:kf,a:v||D.wasmMemory,oa:$e,W:(a,b,c,d)=>$e(a,b,c,d)},Z=function(){function a(c,d){Z=c.exports;J.Tc.push(Z.Ia);Eb=Z.Ka;Ga.unshift(Z.Ba);Aa=d;Va("wasm-instantiate");return Z}var b={a:lf};Ua("wasm-instantiate");if(D.instantiateWasm)try{return D.instantiateWasm(b,a)}catch(c){E(`Module.instantiateWasm callback failed with error: ${c}`),ma(c)}cb(b,function(c){a(c.instance,
c.module)}).catch(ma);return{}}(),Sd=a=>(Sd=Z.Ca)(a);D.__embind_initialize_bindings=()=>(D.__embind_initialize_bindings=Z.Da)();var Td=a=>(Td=Z.Ea)(a),Je=a=>(Je=Z.Fa)(a),Ab=D._pthread_self=()=>(Ab=D._pthread_self=Z.Ga)(),sb=a=>(sb=Z.Ha)(a);D.__emscripten_tls_init=()=>(D.__emscripten_tls_init=Z.Ia)();var bc=(a,b)=>(bc=Z.Ja)(a,b),rb=()=>(rb=Z.La)(),df=D.__emscripten_thread_init=(a,b,c,d,e,f)=>(df=D.__emscripten_thread_init=Z.Ma)(a,b,c,d,e,f);
D.__emscripten_thread_crashed=()=>(D.__emscripten_thread_crashed=Z.Na)();var nb=(a,b,c,d,e)=>(nb=Z.Oa)(a,b,c,d,e),zb=a=>(zb=Z.Pa)(a),Fb=D.__emscripten_thread_exit=a=>(Fb=D.__emscripten_thread_exit=Z.Qa)(a),pe=()=>(pe=Z.Ra)(),mf=(a,b)=>(mf=Z.Sa)(a,b),ef=a=>(ef=Z.Ta)(a),Cb=(a,b)=>(Cb=Z.Ua)(a,b),jb=a=>(jb=Z.Va)(a),mb=a=>(mb=Z.Wa)(a),ib=()=>(ib=Z.Xa)();D.dynCall_viijii=(a,b,c,d,e,f,g)=>(D.dynCall_viijii=Z.Ya)(a,b,c,d,e,f,g);D.dynCall_ji=(a,b)=>(D.dynCall_ji=Z.Za)(a,b);
D.dynCall_jiji=(a,b,c,d,e)=>(D.dynCall_jiji=Z._a)(a,b,c,d,e);D.dynCall_iiiiij=(a,b,c,d,e,f,g)=>(D.dynCall_iiiiij=Z.$a)(a,b,c,d,e,f,g);D.dynCall_iiiiijj=(a,b,c,d,e,f,g,l,m)=>(D.dynCall_iiiiijj=Z.ab)(a,b,c,d,e,f,g,l,m);D.dynCall_iiiiiijj=(a,b,c,d,e,f,g,l,m,n)=>(D.dynCall_iiiiiijj=Z.bb)(a,b,c,d,e,f,g,l,m,n);D.__ZN2MB2NN28LinearDefragmentingAllocator10Allocation4nullE=88624;D.___start_em_js=333544;D.___stop_em_js=334537;
function gf(a,b){var c=ib();try{P(a)(b)}catch(d){jb(c);if(d!==d+0)throw d;mf(1,0)}}function kf(a,b,c,d){var e=ib();try{P(a)(b,c,d)}catch(f){jb(e);if(f!==f+0)throw f;mf(1,0)}}function hf(a,b,c){var d=ib();try{P(a)(b,c)}catch(e){jb(d);if(e!==e+0)throw e;mf(1,0)}}function ff(a,b,c,d){var e=ib();try{return P(a)(b,c,d)}catch(f){jb(e);if(f!==f+0)throw f;mf(1,0)}}D.addRunDependency=Ua;D.removeRunDependency=Va;D.FS_createPath=Qc;D.FS_createLazyFile=Tc;D.FS_createDevice=Ma;D.wasmMemory=v;
D.keepRuntimeAlive=()=>pb||0<N;D.ExitStatus=eb;D.FS_createPreloadedFile=nc;D.FS_createDataFile=mc;D.FS_unlink=Jc;D.PThread=J;var nf;Ta=function of(){nf||pf();nf||(Ta=of)};
function pf(){function a(){if(!nf&&(nf=!0,D.calledRun=!0,!Ba)){Ka();la(D);if(D.onRuntimeInitialized)D.onRuntimeInitialized();if(!F){if(D.postRun)for("function"==typeof D.postRun&&(D.postRun=[D.postRun]);D.postRun.length;){var b=D.postRun.shift();Ia.unshift(b)}Qa(Ia)}}}if(!(0<Ra))if(F)la(D),Ka(),startWorker(D);else{if(D.preRun)for("function"==typeof D.preRun&&(D.preRun=[D.preRun]);D.preRun.length;)Fa.unshift(D.preRun.shift());Qa(Fa);0<Ra||(D.setStatus?(D.setStatus("Running..."),setTimeout(function(){setTimeout(function(){D.setStatus("")},
1);a()},1)):a())}}if(D.preInit)for("function"==typeof D.preInit&&(D.preInit=[D.preInit]);0<D.preInit.length;)D.preInit.pop()();pf();
if("object"==typeof window&&("undefined"==typeof F||!F)){var qf=()=>{var a=0,b=!1,c=m=>{var n=new XMLHttpRequest;n.open("POST","stdio.html",!1);n.send(m);try{window.close()}catch(q){}},d=m=>{var n=new XMLHttpRequest;++a;n.onreadystatechange=()=>{4==n.readyState&&0==--a&&b&&c("^exit^"+Ca)};n.open("POST","stdio.html",!0);n.send(m)};if(-1!=document.URL.search("localhost")||-1!=document.URL.search(":6931/")){var e=1,f=ya,g=E;Ha.unshift(()=>{0==a?c("^exit^"+Ca):b=!0});ya=m=>{d("^out^"+e++ +"^"+encodeURIComponent(m));
f(m)};E=m=>{d("^err^"+e++ +"^"+encodeURIComponent(m));g(m)};var l=()=>{try{d("^pageload^")}catch(m){setTimeout(l,50)}};l()}};"undefined"!=typeof document&&qf()};


  return readyPromise
}
);
})();
if (typeof exports === 'object' && typeof module === 'object')
  module.exports = BlinkIDWasmSDK;
else if (typeof define === 'function' && define['amd'])
  define([], () => BlinkIDWasmSDK);
