
var BlinkIDWasmSDK = (() => {
  var _scriptDir = typeof document !== 'undefined' && document.currentScript ? document.currentScript.src : undefined;
  
  return (
function(BlinkIDWasmSDK = {})  {

var h;h||(h=typeof BlinkIDWasmSDK !== 'undefined' ? BlinkIDWasmSDK : {});var aa,ba;h.ready=new Promise(function(a,b){aa=a;ba=b});h.Lb||(h.Lb=0);h.Lb++;
h.ENVIRONMENT_IS_PTHREAD||h.$ww||function(a){function b(m,n,r){var p=new XMLHttpRequest;p.open("GET",m,!0);p.responseType="arraybuffer";p.onprogress=function(q){var k=n;q.total&&(k=q.total);if(q.loaded){p.qc?h.lb[m].loaded=q.loaded:(p.qc=!0,h.lb||(h.lb={}),h.lb[m]={loaded:q.loaded,total:k});var t=k=q=0,x;for(x in h.lb){var z=h.lb[x];q+=z.total;k+=z.loaded;t++}q=Math.ceil(q*h.Lb/t);h.setStatus&&h.setStatus("Downloading data... ("+k+"/"+q+")")}else!h.lb&&h.setStatus&&h.setStatus("Downloading data...")};
p.onerror=function(){throw Error("NetworkError for: "+m);};p.onload=function(){if(200==p.status||304==p.status||206==p.status||0==p.status&&p.response)r(p.response);else throw Error(p.statusText+" : "+p.responseURL);};p.send(null)}function c(m){console.error("package error:",m)}function d(){function m(q,k,t){this.start=q;this.end=k;this.audio=t}function n(q){if(!q)throw"Loading data file failed."+Error().stack;if(q.constructor.name!==ArrayBuffer.name)throw"bad input to processPackageData"+Error().stack;
q=new Uint8Array(q);m.prototype.uc=q;q=a.files;for(var k=0;k<q.length;++k)m.prototype.Ub[q[k].filename].onload();h.removeRunDependency("datafile_/Users/ivan/Dev/core-webassembly-sdks.worktrees/blinkid-v6.3.2/SDKs/BlinkID/resources/lightweight-fixed/advanced/BlinkIDWasmSDK.data")}h.FS_createPath("/","microblink",!0,!0);m.prototype={Ub:{},open:function(q,k){this.name=k;this.Ub[k]=this;h.addRunDependency("fp "+this.name)},send:function(){},onload:function(){this.finish(this.uc.subarray(this.start,this.end))},
finish:function(q){h.FS_createDataFile(this.name,null,q,!0,!0,!0);h.removeRunDependency("fp "+this.name);this.Ub[this.name]=null}};for(var r=a.files,p=0;p<r.length;++p)(new m(r[p].start,r[p].end,r[p].audio||0)).open("GET",r[p].filename);h.addRunDependency("datafile_/Users/ivan/Dev/core-webassembly-sdks.worktrees/blinkid-v6.3.2/SDKs/BlinkID/resources/lightweight-fixed/advanced/BlinkIDWasmSDK.data");h.ic||(h.ic={});h.ic["/Users/ivan/Dev/core-webassembly-sdks.worktrees/blinkid-v6.3.2/SDKs/BlinkID/resources/lightweight-fixed/advanced/BlinkIDWasmSDK.data"]=
{kd:!1};l?(n(l),l=null):g=n}"object"===typeof window?window.encodeURIComponent(window.location.pathname.toString().substring(0,window.location.pathname.toString().lastIndexOf("/"))+"/"):"undefined"===typeof process&&"undefined"!==typeof location&&encodeURIComponent(location.pathname.toString().substring(0,location.pathname.toString().lastIndexOf("/"))+"/");"function"!==typeof h.locateFilePackage||h.locateFile||(h.locateFile=h.locateFilePackage,u("warning: you defined Module.locateFilePackage, that has been renamed to Module.locateFile (using your locateFilePackage for now)"));
var e=h.locateFile?h.locateFile("BlinkIDWasmSDK.data",""):"BlinkIDWasmSDK.data",f=a.remote_package_size,g=null,l=h.getPreloadedPackage?h.getPreloadedPackage(e,f):null;l||b(e,f,function(m){g?(g(m),g=null):l=m},c);h.calledRun?d():(h.preRun||(h.preRun=[]),h.preRun.push(d))}({files:[{filename:"/microblink/Model_0c0458bedf340ad5858a25dd463e63f57ddb42e69c3c5ff0c572a528356b020d.strop",start:0,end:120418},{filename:"/microblink/Model_1eab2e7966860966c3a26900cc5d5d8d072fec678c7e5af1489507419b5ff25b.strop",
start:120418,end:891236},{filename:"/microblink/Model_2880751121560047e6dc571bc8ff4683aeb863886f7c0789234594ceb1e23577.strop",start:891236,end:895174},{filename:"/microblink/Model_36d8e94f4cb46097bd6b7385f2aa91fcdee1a5fefeec59e56d1b9e82c94b00a7.strop",start:895174,end:1264970},{filename:"/microblink/Model_473ac5f5e256623c0a6b282698c1f1b033b9fb5359e6aa142e9fb4a4022afe4e.strop",start:1264970,end:1271852},{filename:"/microblink/Model_4cd5265c0ff4b156aef99f1a065de02ebd81cd59c7da18a3335ff08761e94679.strop",
start:1271852,end:2209176},{filename:"/microblink/Model_500f4403bf221021bb85c3e758d59f69841635787f6f4201a4ffe5e68733f8bb.strop",start:2209176,end:2792314},{filename:"/microblink/Model_9ea5cca9d0c69d5bcf7c5ae095eb03340e2d510261b50e0012e372f1bceb2640.strop",start:2792314,end:5587606},{filename:"/microblink/Model_b452fd3cd4037080cfcb4c423dba5bc58c8ceafc28427fdf9c5778fb353f088e.strop",start:5587606,end:5594456},{filename:"/microblink/Model_d2bcaf18d17504513598e04f472c035b3d4f22d8653d5a79c05b4508a4b547b3.strop",
start:5594456,end:6027972},{filename:"/microblink/Model_e4f1f62f68ec44b71ecad3fb3f3b48fe3790beb5ab325611e17d63af06e9f644.strop",start:6027972,end:6084486},{filename:"/microblink/Model_ed586fd6ca47c8eebb513c4ffaaacc2c54e92162b145062d7022519fba0911de.strop",start:6084486,end:6797718},{filename:"/microblink/Model_faf688599c7e261a2a7404730f69ed029115bb0d3e7a3657731d88e701720efe.strop",start:6797718,end:6814456},{filename:"/microblink/ccc_lookup_table.zzip",start:6814456,end:6834925},{filename:"/microblink/face_detector_model.zzip",
start:6834925,end:6931783}],remote_package_size:6931783});h.onAbort=function(a){u("Aborted with message: "+a);try{throw new WebAssembly.RuntimeError(a);}catch(b){u("Stacktrace: "+b.stack)}};var crypto={getRandomValues:function(a){for(var b=0;b<a.length;b++)a[b]=256*Math.random()|0}},ca=Object.assign({},h),da="./this.program",ea=(a,b)=>{throw b;},fa="object"==typeof window,ha="function"==typeof importScripts,ia="",ja,ka,la;
if(fa||ha)ha?ia=self.location.href:"undefined"!=typeof document&&document.currentScript&&(ia=document.currentScript.src),_scriptDir&&(ia=_scriptDir),ia=0!==ia.indexOf("blob:")?ia.substr(0,ia.replace(/[?#].*/,"").lastIndexOf("/")+1):"",ja=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},ha&&(la=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),ka=(a,b,c)=>{var d=new XMLHttpRequest;d.open("GET",
a,!0);d.responseType="arraybuffer";d.onload=()=>{200==d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)};var ma=h.print||console.log.bind(console),u=h.printErr||console.warn.bind(console);Object.assign(h,ca);ca=null;h.thisProgram&&(da=h.thisProgram);h.quit&&(ea=h.quit);var na;h.wasmBinary&&(na=h.wasmBinary);var noExitRuntime=h.noExitRuntime||!0;"object"!=typeof WebAssembly&&oa("no native wasm support detected");
var pa,qa=!1,ra="undefined"!=typeof TextDecoder?new TextDecoder("utf8"):void 0;
function sa(a,b,c){var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.buffer&&ra)return ra.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var f=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|f);else{var g=a[b++]&63;e=224==(e&240)?(e&15)<<12|f<<6|g:(e&7)<<18|f<<12|g<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d}function v(a,b){return a?sa(w,a,b):""}
function A(a,b,c,d){if(!(0<d))return 0;var e=c;d=c+d-1;for(var f=0;f<a.length;++f){var g=a.charCodeAt(f);if(55296<=g&&57343>=g){var l=a.charCodeAt(++f);g=65536+((g&1023)<<10)|l&1023}if(127>=g){if(c>=d)break;b[c++]=g}else{if(2047>=g){if(c+1>=d)break;b[c++]=192|g>>6}else{if(65535>=g){if(c+2>=d)break;b[c++]=224|g>>12}else{if(c+3>=d)break;b[c++]=240|g>>18;b[c++]=128|g>>12&63}b[c++]=128|g>>6&63}b[c++]=128|g&63}}b[c]=0;return c-e}
function ta(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b}var C,w,ua,D,E,I,va,wa;function xa(){var a=pa.buffer;h.HEAP8=C=new Int8Array(a);h.HEAP16=ua=new Int16Array(a);h.HEAP32=E=new Int32Array(a);h.HEAPU8=w=new Uint8Array(a);h.HEAPU16=D=new Uint16Array(a);h.HEAPU32=I=new Uint32Array(a);h.HEAPF32=va=new Float32Array(a);h.HEAPF64=wa=new Float64Array(a)}var ya,za=[],Aa=[],Ba=[];
function Ca(){var a=h.preRun.shift();za.unshift(a)}var Da=0,Ea=null,Fa=null;function Ga(){Da++;h.monitorRunDependencies&&h.monitorRunDependencies(Da)}function Ha(){Da--;h.monitorRunDependencies&&h.monitorRunDependencies(Da);if(0==Da&&(null!==Ea&&(clearInterval(Ea),Ea=null),Fa)){var a=Fa;Fa=null;a()}}function oa(a){if(h.onAbort)h.onAbort(a);a="Aborted("+a+")";u(a);qa=!0;a=new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");ba(a);throw a;}
function Ia(a){return a.startsWith("data:application/octet-stream;base64,")}var Ja;Ja="BlinkIDWasmSDK.wasm";if(!Ia(Ja)){var Ka=Ja;Ja=h.locateFile?h.locateFile(Ka,ia):ia+Ka}function La(a){try{if(a==Ja&&na)return new Uint8Array(na);if(la)return la(a);throw"both async and sync fetching of the wasm failed";}catch(b){oa(b)}}
function Ma(a){return na||!fa&&!ha||"function"!=typeof fetch?Promise.resolve().then(function(){return La(a)}):fetch(a,{credentials:"same-origin"}).then(function(b){if(!b.ok)throw"failed to load wasm binary file at '"+a+"'";return b.arrayBuffer()}).catch(function(){return La(a)})}function Na(a,b,c){return Ma(a).then(function(d){return WebAssembly.instantiate(d,b)}).then(function(d){return d}).then(c,function(d){u("failed to asynchronously prepare wasm: "+d);oa(d)})}
function Oa(a,b){var c=Ja;return na||"function"!=typeof WebAssembly.instantiateStreaming||Ia(c)||"function"!=typeof fetch?Na(c,a,b):fetch(c,{credentials:"same-origin"}).then(function(d){return WebAssembly.instantiateStreaming(d,a).then(b,function(e){u("wasm streaming compile failed: "+e);u("falling back to ArrayBuffer instantiation");return Na(c,a,b)})})}
var J,K,Pa={350108:a=>{a=v(a);throw Error("Failed to reconfigure RecognizerRunner due to following error: "+a);},350244:(a,b,c,d)=>{a=v(a);b=v(b);c=v(c);d=v(d);throw Error(a+b+c+d);},350460:(a,b)=>{a=v(a);b=v(b);throw Error(a+b);},350570:a=>{throw Error(v(a));},350613:()=>{throw Error("Unable to perform that operation while recognizer is in use!");},350696:()=>{throw Error("Unable to perform that operation while recognizer is in use!");},350779:()=>{throw Error("Unable to perform that operation while recognizer is in use!");
}};function Sa(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}function Ta(a){for(;0<a.length;)a.shift()(h)}function Ua(a){this.Oa=a-24;this.$c=function(b){I[this.Oa+4>>2]=b};this.Xc=function(b){I[this.Oa+8>>2]=b};this.Yc=function(){E[this.Oa>>2]=0};this.Wc=function(){C[this.Oa+12>>0]=0};this.Zc=function(){C[this.Oa+13>>0]=0};this.Hc=function(b,c){this.Vc();this.$c(b);this.Xc(c);this.Yc();this.Wc();this.Zc()};this.Vc=function(){I[this.Oa+16>>2]=0}}
var Va=0,Wa=(a,b)=>{for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a},L=a=>{var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=Wa(a.split("/").filter(d=>!!d),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a},Xa=a=>{var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,b.length-1));return a+b},Ya=
a=>{if("/"===a)return"/";a=L(a);a=a.replace(/\/$/,"");var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)};function Za(){if("object"==typeof crypto&&"function"==typeof crypto.getRandomValues){var a=new Uint8Array(1);return()=>{crypto.getRandomValues(a);return a[0]}}return()=>oa("randomDevice")}
function $a(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:"/";if("string"!=typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=Wa(a.split("/").filter(d=>!!d),!b).join("/");return(b?"/":"")+a||"."}function ab(a,b){var c=Array(ta(a)+1);a=A(a,c,0,c.length);b&&(c.length=a);return c}var bb=[];function cb(a,b){bb[a]={input:[],Ta:[],pb:b};db(a,eb)}
var eb={open:function(a){var b=bb[a.node.ub];if(!b)throw new M(43);a.Sa=b;a.seekable=!1},close:function(a){a.Sa.pb.Ab(a.Sa)},Ab:function(a){a.Sa.pb.Ab(a.Sa)},read:function(a,b,c,d){if(!a.Sa||!a.Sa.pb.ec)throw new M(60);for(var e=0,f=0;f<d;f++){try{var g=a.Sa.pb.ec(a.Sa)}catch(l){throw new M(29);}if(void 0===g&&0===e)throw new M(6);if(null===g||void 0===g)break;e++;b[c+f]=g}e&&(a.node.timestamp=Date.now());return e},write:function(a,b,c,d){if(!a.Sa||!a.Sa.pb.Qb)throw new M(60);try{for(var e=0;e<d;e++)a.Sa.pb.Qb(a.Sa,
b[c+e])}catch(f){throw new M(29);}d&&(a.node.timestamp=Date.now());return e}},fb={ec:function(a){if(!a.input.length){var b=null;"undefined"!=typeof window&&"function"==typeof window.prompt?(b=window.prompt("Input: "),null!==b&&(b+="\n")):"function"==typeof readline&&(b=readline(),null!==b&&(b+="\n"));if(!b)return null;a.input=ab(b,!0)}return a.input.shift()},Qb:function(a,b){null===b||10===b?(ma(sa(a.Ta,0)),a.Ta=[]):0!=b&&a.Ta.push(b)},Ab:function(a){a.Ta&&0<a.Ta.length&&(ma(sa(a.Ta,0)),a.Ta=[])}},
gb={Qb:function(a,b){null===b||10===b?(u(sa(a.Ta,0)),a.Ta=[]):0!=b&&a.Ta.push(b)},Ab:function(a){a.Ta&&0<a.Ta.length&&(u(sa(a.Ta,0)),a.Ta=[])}};function hb(a){a=65536*Math.ceil(a/65536);var b=ib(65536,a);b?(w.fill(0,b,b+a),a=b):a=0;return a}
var N={bb:null,eb:function(){return N.createNode(null,"/",16895,0)},createNode:function(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new M(63);N.bb||(N.bb={dir:{node:{ab:N.Ma.ab,Xa:N.Ma.Xa,qb:N.Ma.qb,Eb:N.Ma.Eb,mc:N.Ma.mc,Kb:N.Ma.Kb,nc:N.Ma.nc,lc:N.Ma.lc,Hb:N.Ma.Hb},stream:{ib:N.Na.ib}},file:{node:{ab:N.Ma.ab,Xa:N.Ma.Xa},stream:{ib:N.Na.ib,read:N.Na.read,write:N.Na.write,Wb:N.Na.Wb,rb:N.Na.rb,Fb:N.Na.Fb}},link:{node:{ab:N.Ma.ab,Xa:N.Ma.Xa,vb:N.Ma.vb},stream:{}},Zb:{node:{ab:N.Ma.ab,Xa:N.Ma.Xa},
stream:jb}});c=kb(a,b,c,d);16384===(c.mode&61440)?(c.Ma=N.bb.dir.node,c.Na=N.bb.dir.stream,c.La={}):32768===(c.mode&61440)?(c.Ma=N.bb.file.node,c.Na=N.bb.file.stream,c.Qa=0,c.La=null):40960===(c.mode&61440)?(c.Ma=N.bb.link.node,c.Na=N.bb.link.stream):8192===(c.mode&61440)&&(c.Ma=N.bb.Zb.node,c.Na=N.bb.Zb.stream);c.timestamp=Date.now();a&&(a.La[b]=c,a.timestamp=c.timestamp);return c},ld:function(a){return a.La?a.La.subarray?a.La.subarray(0,a.Qa):new Uint8Array(a.La):new Uint8Array(0)},bc:function(a,
b){var c=a.La?a.La.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)>>>0),0!=c&&(b=Math.max(b,256)),c=a.La,a.La=new Uint8Array(b),0<a.Qa&&a.La.set(c.subarray(0,a.Qa),0))},Sc:function(a,b){if(a.Qa!=b)if(0==b)a.La=null,a.Qa=0;else{var c=a.La;a.La=new Uint8Array(b);c&&a.La.set(c.subarray(0,Math.min(b,a.Qa)));a.Qa=b}},Ma:{ab:function(a){var b={};b.yc=8192===(a.mode&61440)?a.id:1;b.Nb=a.id;b.mode=a.mode;b.Oc=1;b.uid=0;b.Fc=0;b.ub=a.ub;b.size=16384===(a.mode&61440)?4096:32768===(a.mode&61440)?a.Qa:40960===
(a.mode&61440)?a.link.length:0;b.rc=new Date(a.timestamp);b.Nc=new Date(a.timestamp);b.wc=new Date(a.timestamp);b.sc=4096;b.tc=Math.ceil(b.size/b.sc);return b},Xa:function(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);void 0!==b.size&&N.Sc(a,b.size)},qb:function(){throw lb[44];},Eb:function(a,b,c,d){return N.createNode(a,b,c,d)},mc:function(a,b,c){if(16384===(a.mode&61440)){try{var d=mb(b,c)}catch(f){}if(d)for(var e in d.La)throw new M(55);}delete a.parent.La[a.name];
a.parent.timestamp=Date.now();a.name=c;b.La[c]=a;b.timestamp=a.parent.timestamp;a.parent=b},Kb:function(a,b){delete a.La[b];a.timestamp=Date.now()},nc:function(a,b){var c=mb(a,b),d;for(d in c.La)throw new M(55);delete a.La[b];a.timestamp=Date.now()},lc:function(a){var b=[".",".."],c;for(c in a.La)a.La.hasOwnProperty(c)&&b.push(c);return b},Hb:function(a,b,c){a=N.createNode(a,b,41471,0);a.link=c;return a},vb:function(a){if(40960!==(a.mode&61440))throw new M(28);return a.link}},Na:{read:function(a,
b,c,d,e){var f=a.node.La;if(e>=a.node.Qa)return 0;a=Math.min(a.node.Qa-e,d);if(8<a&&f.subarray)b.set(f.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=f[e+d];return a},write:function(a,b,c,d,e,f){b.buffer===C.buffer&&(f=!1);if(!d)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&(!a.La||a.La.subarray)){if(f)return a.La=b.subarray(c,c+d),a.Qa=d;if(0===a.Qa&&0===e)return a.La=b.slice(c,c+d),a.Qa=d;if(e+d<=a.Qa)return a.La.set(b.subarray(c,c+d),e),d}N.bc(a,e+d);if(a.La.subarray&&b.subarray)a.La.set(b.subarray(c,
c+d),e);else for(f=0;f<d;f++)a.La[e+f]=b[c+f];a.Qa=Math.max(a.Qa,e+d);return d},ib:function(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.Qa);if(0>b)throw new M(28);return b},Wb:function(a,b,c){N.bc(a.node,b+c);a.node.Qa=Math.max(a.node.Qa,b+c)},rb:function(a,b,c,d,e){if(32768!==(a.node.mode&61440))throw new M(43);a=a.node.La;if(e&2||a.buffer!==C.buffer){if(0<c||c+b<a.length)a=a.subarray?a.subarray(c,c+b):Array.prototype.slice.call(a,c,c+b);c=!0;b=hb(b);if(!b)throw new M(48);
C.set(a,b)}else c=!1,b=a.byteOffset;return{Oa:b,Xb:c}},Fb:function(a,b,c,d){N.Na.write(a,b,0,d,c,!1);return 0}}};function nb(a,b,c){var d="al "+a;ka(a,e=>{e||oa('Loading data file "'+a+'" failed (no arrayBuffer).');b(new Uint8Array(e));d&&Ha(d)},()=>{if(c)c();else throw'Loading data file "'+a+'" failed.';});d&&Ga(d)}
var ob=null,pb={},qb=[],rb=1,sb=null,tb=!0,M=null,lb={},vb=(a,b={})=>{a=$a(a);if(!a)return{path:"",node:null};b=Object.assign({dc:!0,Sb:0},b);if(8<b.Sb)throw new M(32);a=a.split("/").filter(g=>!!g);for(var c=ob,d="/",e=0;e<a.length;e++){var f=e===a.length-1;if(f&&b.parent)break;c=mb(c,a[e]);d=L(d+"/"+a[e]);c.sb&&(!f||f&&b.dc)&&(c=c.sb.root);if(!f||b.zb)for(f=0;40960===(c.mode&61440);)if(c=ub(d),d=$a(Xa(d),c),c=vb(d,{Sb:b.Sb+1}).node,40<f++)throw new M(32);}return{path:d,node:c}},wb=a=>{for(var b;;){if(a===
a.parent)return a=a.eb.hc,b?"/"!==a[a.length-1]?a+"/"+b:a+b:a;b=b?a.name+"/"+b:a.name;a=a.parent}},xb=(a,b)=>{for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%sb.length},mb=(a,b)=>{var c;if(c=(c=yb(a,"x"))?c:a.Ma.qb?0:2)throw new M(c,a);for(c=sb[xb(a.id,b)];c;c=c.ob){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.Ma.qb(a,b)},kb=(a,b,c,d)=>{a=new zb(a,b,c,d);b=xb(a.parent.id,a.name);a.ob=sb[b];return sb[b]=a},Ab={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090},Bb=
a=>{var b=["r","w","rw"][a&3];a&512&&(b+="w");return b},yb=(a,b)=>{if(tb)return 0;if(!b.includes("r")||a.mode&292){if(b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73))return 2}else return 2;return 0},Cb=(a,b)=>{try{return mb(a,b),20}catch(c){}return yb(a,"wx")},Db=(a=0)=>{for(;4096>=a;a++)if(!qb[a])return a;throw new M(33);},Fb=(a,b)=>{Eb||(Eb=function(){this.Gb={}},Eb.prototype={},Object.defineProperties(Eb.prototype,{object:{get:function(){return this.node},set:function(c){this.node=
c}},flags:{get:function(){return this.Gb.flags},set:function(c){this.Gb.flags=c}},position:{get:function(){return this.Gb.position},set:function(c){this.Gb.position=c}}}));a=Object.assign(new Eb,a);b=Db(b);a.gb=b;return qb[b]=a},jb={open:a=>{a.Na=pb[a.node.ub].Na;a.Na.open&&a.Na.open(a)},ib:()=>{throw new M(70);}},db=(a,b)=>{pb[a]={Na:b}},Gb=(a,b)=>{var c="/"===b,d=!b;if(c&&ob)throw new M(10);if(!c&&!d){var e=vb(b,{dc:!1});b=e.path;e=e.node;if(e.sb)throw new M(10);if(16384!==(e.mode&61440))throw new M(54);
}b={type:a,od:{},hc:b,Mc:[]};a=a.eb(b);a.eb=b;b.root=a;c?ob=a:e&&(e.sb=b,e.eb&&e.eb.Mc.push(b))},P=(a,b,c)=>{var d=vb(a,{parent:!0}).node;a=Ya(a);if(!a||"."===a||".."===a)throw new M(28);var e=Cb(d,a);if(e)throw new M(e);if(!d.Ma.Eb)throw new M(63);return d.Ma.Eb(d,a,b,c)},Hb=(a,b,c)=>{"undefined"==typeof c&&(c=b,b=438);return P(a,b|8192,c)},Ib=(a,b)=>{if(!$a(a))throw new M(44);var c=vb(b,{parent:!0}).node;if(!c)throw new M(44);b=Ya(b);var d=Cb(c,b);if(d)throw new M(d);if(!c.Ma.Hb)throw new M(63);
c.Ma.Hb(c,b,a)},Jb=a=>{var b=vb(a,{parent:!0}).node;if(!b)throw new M(44);var c=Ya(a);a=mb(b,c);a:{try{var d=mb(b,c)}catch(f){d=f.Va;break a}var e=yb(b,"wx");d=e?e:16384===(d.mode&61440)?31:0}if(d)throw new M(d);if(!b.Ma.Kb)throw new M(63);if(a.sb)throw new M(10);b.Ma.Kb(b,c);b=xb(a.parent.id,a.name);if(sb[b]===a)sb[b]=a.ob;else for(b=sb[b];b;){if(b.ob===a){b.ob=a.ob;break}b=b.ob}},ub=a=>{a=vb(a).node;if(!a)throw new M(44);if(!a.Ma.vb)throw new M(28);return $a(wb(a.parent),a.Ma.vb(a))},Kb=(a,b)=>
{a=vb(a,{zb:!b}).node;if(!a)throw new M(44);if(!a.Ma.ab)throw new M(63);return a.Ma.ab(a)},Lb=a=>Kb(a,!0),Mb=(a,b)=>{a="string"==typeof a?vb(a,{zb:!0}).node:a;if(!a.Ma.Xa)throw new M(63);a.Ma.Xa(a,{mode:b&4095|a.mode&-4096,timestamp:Date.now()})},Ob=(a,b,c)=>{if(""===a)throw new M(44);if("string"==typeof b){var d=Ab[b];if("undefined"==typeof d)throw Error("Unknown file open mode: "+b);b=d}c=b&64?("undefined"==typeof c?438:c)&4095|32768:0;if("object"==typeof a)var e=a;else{a=L(a);try{e=vb(a,{zb:!(b&
131072)}).node}catch(f){}}d=!1;if(b&64)if(e){if(b&128)throw new M(20);}else e=P(a,c,0),d=!0;if(!e)throw new M(44);8192===(e.mode&61440)&&(b&=-513);if(b&65536&&16384!==(e.mode&61440))throw new M(54);if(!d&&(c=e?40960===(e.mode&61440)?32:16384===(e.mode&61440)&&("r"!==Bb(b)||b&512)?31:yb(e,Bb(b)):44))throw new M(c);if(b&512&&!d){c=e;c="string"==typeof c?vb(c,{zb:!0}).node:c;if(!c.Ma.Xa)throw new M(63);if(16384===(c.mode&61440))throw new M(31);if(32768!==(c.mode&61440))throw new M(28);if(d=yb(c,"w"))throw new M(d);
c.Ma.Xa(c,{size:0,timestamp:Date.now()})}b&=-131713;e=Fb({node:e,path:wb(e),flags:b,seekable:!0,position:0,Na:e.Na,jd:[],error:!1});e.Na.open&&e.Na.open(e);!h.logReadFiles||b&1||(Nb||(Nb={}),a in Nb||(Nb[a]=1));return e},Pb=a=>{if(null===a.gb)throw new M(8);a.Mb&&(a.Mb=null);try{a.Na.close&&a.Na.close(a)}catch(b){throw b;}finally{qb[a.gb]=null}a.gb=null},Qb=(a,b,c)=>{if(null===a.gb)throw new M(8);if(!a.seekable||!a.Na.ib)throw new M(70);if(0!=c&&1!=c&&2!=c)throw new M(28);a.position=a.Na.ib(a,b,c);
a.jd=[]},Rb=(a,b,c,d,e,f)=>{if(0>d||0>e)throw new M(28);if(null===a.gb)throw new M(8);if(0===(a.flags&2097155))throw new M(8);if(16384===(a.node.mode&61440))throw new M(31);if(!a.Na.write)throw new M(28);a.seekable&&a.flags&1024&&Qb(a,0,2);var g="undefined"!=typeof e;if(!g)e=a.position;else if(!a.seekable)throw new M(70);b=a.Na.write(a,b,c,d,e,f);g||(a.position+=b);return b},Sb=()=>{M||(M=function(a,b){this.name="ErrnoError";this.node=b;this.Uc=function(c){this.Va=c};this.Uc(a);this.message="FS error"},
M.prototype=Error(),M.prototype.constructor=M,[44].forEach(a=>{lb[a]=new M(a);lb[a].stack="<generic error, no stack>"}))},Tb,Ub=(a,b)=>{var c=0;a&&(c|=365);b&&(c|=146);return c},Vb=(a,b)=>{a="string"==typeof a?a:wb(a);for(b=b.split("/").reverse();b.length;){var c=b.pop();if(c){var d=L(a+"/"+c);try{P(d,16895,0)}catch(e){}a=d}}return d},Wb=(a,b,c,d)=>{a=L(("string"==typeof a?a:wb(a))+"/"+b);c=Ub(c,d);return P(a,(void 0!==c?c:438)&4095|32768,0)},Xb=(a,b,c,d,e,f)=>{var g=b;a&&(a="string"==typeof a?a:
wb(a),g=b?L(a+"/"+b):a);a=Ub(d,e);g=P(g,(void 0!==a?a:438)&4095|32768,0);if(c){if("string"==typeof c){b=Array(c.length);d=0;for(e=c.length;d<e;++d)b[d]=c.charCodeAt(d);c=b}Mb(g,a|146);b=Ob(g,577);Rb(b,c,0,c.length,0,f);Pb(b);Mb(g,a)}return g},Yb=(a,b,c,d)=>{a=L(("string"==typeof a?a:wb(a))+"/"+b);b=Ub(!!c,!!d);Yb.fc||(Yb.fc=64);var e=Yb.fc++<<8|0;db(e,{open:f=>{f.seekable=!1},close:()=>{d&&d.buffer&&d.buffer.length&&d(10)},read:(f,g,l,m)=>{for(var n=0,r=0;r<m;r++){try{var p=c()}catch(q){throw new M(29);
}if(void 0===p&&0===n)throw new M(6);if(null===p||void 0===p)break;n++;g[l+r]=p}n&&(f.node.timestamp=Date.now());return n},write:(f,g,l,m)=>{for(var n=0;n<m;n++)try{d(g[l+n])}catch(r){throw new M(29);}m&&(f.node.timestamp=Date.now());return n}});return Hb(a,b,e)},Zb=a=>{if(!(a.Jc||a.Kc||a.link||a.La)){if("undefined"!=typeof XMLHttpRequest)throw Error("Lazy loading should have been performed (contents set) in createLazyFile, but it was not. Lazy loading only works in web workers. Use --embed-file or --preload-file in emcc on the main thread.");
if(ja)try{a.La=ab(ja(a.url),!0),a.Qa=a.La.length}catch(b){throw new M(29);}else throw Error("Cannot load without read() or XMLHttpRequest.");}},$b=(a,b,c,d,e)=>{function f(){this.Pb=!1;this.yb=[]}function g(p,q,k,t,x){p=p.node.La;if(x>=p.length)return 0;t=Math.min(p.length-x,t);if(p.slice)for(var z=0;z<t;z++)q[k+z]=p[x+z];else for(z=0;z<t;z++)q[k+z]=p.get(x+z);return t}f.prototype.get=function(p){if(!(p>this.length-1||0>p)){var q=p%this.$b;return this.Bb(p/this.$b|0)[q]}};f.prototype.Tc=function(p){this.Bb=
p};f.prototype.Yb=function(){var p=new XMLHttpRequest;p.open("HEAD",c,!1);p.send(null);if(!(200<=p.status&&300>p.status||304===p.status))throw Error("Couldn't load "+c+". Status: "+p.status);var q=Number(p.getResponseHeader("Content-length")),k,t=(k=p.getResponseHeader("Accept-Ranges"))&&"bytes"===k;p=(k=p.getResponseHeader("Content-Encoding"))&&"gzip"===k;var x=1048576;t||(x=q);var z=this;z.Tc(F=>{var G=F*x,y=(F+1)*x-1;y=Math.min(y,q-1);if("undefined"==typeof z.yb[F]){var O=z.yb;if(G>y)throw Error("invalid range ("+
G+", "+y+") or no bytes requested!");if(y>q-1)throw Error("only "+q+" bytes available! programmer error!");var B=new XMLHttpRequest;B.open("GET",c,!1);q!==x&&B.setRequestHeader("Range","bytes="+G+"-"+y);B.responseType="arraybuffer";B.overrideMimeType&&B.overrideMimeType("text/plain; charset=x-user-defined");B.send(null);if(!(200<=B.status&&300>B.status||304===B.status))throw Error("Couldn't load "+c+". Status: "+B.status);G=void 0!==B.response?new Uint8Array(B.response||[]):ab(B.responseText||"",
!0);O[F]=G}if("undefined"==typeof z.yb[F])throw Error("doXHR failed!");return z.yb[F]});if(p||!q)x=q=1,x=q=this.Bb(0).length,ma("LazyFiles on gzip forces download of the whole file when length is accessed");this.pc=q;this.oc=x;this.Pb=!0};if("undefined"!=typeof XMLHttpRequest){if(!ha)throw"Cannot do synchronous binary XHRs outside webworkers in modern browsers. Use --embed-file or --preload-file in emcc";var l=new f;Object.defineProperties(l,{length:{get:function(){this.Pb||this.Yb();return this.pc}},
$b:{get:function(){this.Pb||this.Yb();return this.oc}}});var m=void 0}else m=c,l=void 0;var n=Wb(a,b,d,e);l?n.La=l:m&&(n.La=null,n.url=m);Object.defineProperties(n,{Qa:{get:function(){return this.La.length}}});var r={};Object.keys(n.Na).forEach(p=>{var q=n.Na[p];r[p]=function(){Zb(n);return q.apply(null,arguments)}});r.read=(p,q,k,t,x)=>{Zb(n);return g(p,q,k,t,x)};r.rb=(p,q,k)=>{Zb(n);var t=hb(q);if(!t)throw new M(48);g(p,C,t,q,k);return{Oa:t,Xb:!0}};n.Na=r;return n},bc=(a,b,c,d,e,f,g,l,m,n)=>{function r(k){function t(x){n&&
n();l||Xb(a,b,x,d,e,m);f&&f();Ha(q)}ac.md(k,p,t,()=>{g&&g();Ha(q)})||t(k)}var p=b?$a(L(a+"/"+b)):a,q="cp "+p;Ga(q);"string"==typeof c?nb(c,k=>r(k),g):r(c)},Q={},Eb,Nb;function cc(a,b,c){if("/"===b.charAt(0))return b;a=-100===a?"/":dc(a).path;if(0==b.length){if(!c)throw new M(44);return a}return L(a+"/"+b)}
function ec(a,b,c){try{var d=a(b)}catch(f){if(f&&f.node&&L(b)!==L(wb(f.node)))return-54;throw f;}E[c>>2]=d.yc;E[c+8>>2]=d.Nb;E[c+12>>2]=d.mode;I[c+16>>2]=d.Oc;E[c+20>>2]=d.uid;E[c+24>>2]=d.Fc;E[c+28>>2]=d.ub;K=[d.size>>>0,(J=d.size,1<=+Math.abs(J)?0<J?(Math.min(+Math.floor(J/4294967296),4294967295)|0)>>>0:~~+Math.ceil((J-+(~~J>>>0))/4294967296)>>>0:0)];E[c+40>>2]=K[0];E[c+44>>2]=K[1];E[c+48>>2]=4096;E[c+52>>2]=d.tc;a=d.rc.getTime();b=d.Nc.getTime();var e=d.wc.getTime();K=[Math.floor(a/1E3)>>>0,(J=
Math.floor(a/1E3),1<=+Math.abs(J)?0<J?(Math.min(+Math.floor(J/4294967296),4294967295)|0)>>>0:~~+Math.ceil((J-+(~~J>>>0))/4294967296)>>>0:0)];E[c+56>>2]=K[0];E[c+60>>2]=K[1];I[c+64>>2]=a%1E3*1E3;K=[Math.floor(b/1E3)>>>0,(J=Math.floor(b/1E3),1<=+Math.abs(J)?0<J?(Math.min(+Math.floor(J/4294967296),4294967295)|0)>>>0:~~+Math.ceil((J-+(~~J>>>0))/4294967296)>>>0:0)];E[c+72>>2]=K[0];E[c+76>>2]=K[1];I[c+80>>2]=b%1E3*1E3;K=[Math.floor(e/1E3)>>>0,(J=Math.floor(e/1E3),1<=+Math.abs(J)?0<J?(Math.min(+Math.floor(J/
4294967296),4294967295)|0)>>>0:~~+Math.ceil((J-+(~~J>>>0))/4294967296)>>>0:0)];E[c+88>>2]=K[0];E[c+92>>2]=K[1];I[c+96>>2]=e%1E3*1E3;K=[d.Nb>>>0,(J=d.Nb,1<=+Math.abs(J)?0<J?(Math.min(+Math.floor(J/4294967296),4294967295)|0)>>>0:~~+Math.ceil((J-+(~~J>>>0))/4294967296)>>>0:0)];E[c+104>>2]=K[0];E[c+108>>2]=K[1];return 0}var fc=void 0;function gc(){fc+=4;return E[fc-4>>2]}function dc(a){a=qb[a];if(!a)throw new M(8);return a}var hc={};function ic(a){for(;a.length;){var b=a.pop();a.pop()(b)}}
function jc(a){return this.fromWireType(E[a>>2])}var kc={},lc={},mc={};function nc(a){if(void 0===a)return"_unknown";a=a.replace(/[^a-zA-Z0-9_]/g,"$");var b=a.charCodeAt(0);return 48<=b&&57>=b?"_"+a:a}function oc(a,b){a=nc(a);return{[a]:function(){return b.apply(this,arguments)}}[a]}
function pc(a){var b=Error,c=oc(a,function(d){this.name=a;this.message=d;d=Error(d).stack;void 0!==d&&(this.stack=this.toString()+"\n"+d.replace(/^Error(:[^\n]*)?\n/,""))});c.prototype=Object.create(b.prototype);c.prototype.constructor=c;c.prototype.toString=function(){return void 0===this.message?this.name:this.name+": "+this.message};return c}var qc=void 0;function rc(a){throw new qc(a);}
function sc(a,b,c){function d(l){l=c(l);l.length!==a.length&&rc("Mismatched type converter count");for(var m=0;m<a.length;++m)tc(a[m],l[m])}a.forEach(function(l){mc[l]=b});var e=Array(b.length),f=[],g=0;b.forEach((l,m)=>{lc.hasOwnProperty(l)?e[m]=lc[l]:(f.push(l),kc.hasOwnProperty(l)||(kc[l]=[]),kc[l].push(()=>{e[m]=lc[l];++g;g===f.length&&d(e)}))});0===f.length&&d(e)}
function uc(a){switch(a){case 1:return 0;case 2:return 1;case 4:return 2;case 8:return 3;default:throw new TypeError("Unknown type size: "+a);}}var vc=void 0;function R(a){for(var b="";w[a];)b+=vc[w[a++]];return b}var wc=void 0;function S(a){throw new wc(a);}
function tc(a,b,c={}){if(!("argPackAdvance"in b))throw new TypeError("registerType registeredInstance requires argPackAdvance");var d=b.name;a||S('type "'+d+'" must have a positive integer typeid pointer');if(lc.hasOwnProperty(a)){if(c.Gc)return;S("Cannot register type '"+d+"' twice")}lc[a]=b;delete mc[a];kc.hasOwnProperty(a)&&(b=kc[a],delete kc[a],b.forEach(e=>e()))}function xc(a){S(a.Ea.Ra.Pa.name+" instance already deleted")}var yc=!1;function zc(){}
function Ac(a){--a.count.value;0===a.count.value&&(a.Wa?a.Ya.fb(a.Wa):a.Ra.Pa.fb(a.Oa))}function Bc(a,b,c){if(b===c)return a;if(void 0===c.Za)return null;a=Bc(a,b,c.Za);return null===a?null:c.zc(a)}var Cc={},Dc=[];function Ec(){for(;Dc.length;){var a=Dc.pop();a.Ea.mb=!1;a["delete"]()}}var Fc=void 0,Gc={};function Hc(a,b){for(void 0===b&&S("ptr should not be undefined");a.Za;)b=a.wb(b),a=a.Za;return Gc[b]}
function Ic(a,b){b.Ra&&b.Oa||rc("makeClassHandle requires ptr and ptrType");!!b.Ya!==!!b.Wa&&rc("Both smartPtrType and smartPtr must be specified");b.count={value:1};return Jc(Object.create(a,{Ea:{value:b}}))}function Jc(a){if("undefined"===typeof FinalizationRegistry)return Jc=b=>b,a;yc=new FinalizationRegistry(b=>{Ac(b.Ea)});Jc=b=>{var c=b.Ea;c.Wa&&yc.register(b,{Ea:c},b);return b};zc=b=>{yc.unregister(b)};return Jc(a)}function Kc(){}
function Lc(a,b,c){if(void 0===a[b].Ua){var d=a[b];a[b]=function(){a[b].Ua.hasOwnProperty(arguments.length)||S("Function '"+c+"' called with an invalid number of arguments ("+arguments.length+") - expects one of ("+a[b].Ua+")!");return a[b].Ua[arguments.length].apply(this,arguments)};a[b].Ua=[];a[b].Ua[d.xb]=d}}
function Mc(a,b,c){h.hasOwnProperty(a)?((void 0===c||void 0!==h[a].Ua&&void 0!==h[a].Ua[c])&&S("Cannot register public name '"+a+"' twice"),Lc(h,a,a),h.hasOwnProperty(c)&&S("Cannot register multiple overloads of a function with the same number of arguments ("+c+")!"),h[a].Ua[c]=b):(h[a]=b,void 0!==c&&(h[a].nd=c))}function Nc(a,b,c,d,e,f,g,l){this.name=a;this.constructor=b;this.nb=c;this.fb=d;this.Za=e;this.Bc=f;this.wb=g;this.zc=l;this.Qc=[]}
function Oc(a,b,c){for(;b!==c;)b.wb||S("Expected null or instance of "+c.name+", got an instance of "+b.name),a=b.wb(a),b=b.Za;return a}function Pc(a,b){if(null===b)return this.Ob&&S("null is not a valid "+this.name),0;b.Ea||S('Cannot pass "'+Qc(b)+'" as a '+this.name);b.Ea.Oa||S("Cannot pass deleted object as a pointer of type "+this.name);return Oc(b.Ea.Oa,b.Ea.Ra.Pa,this.Pa)}
function Rc(a,b){if(null===b){this.Ob&&S("null is not a valid "+this.name);if(this.Db){var c=this.Rb();null!==a&&a.push(this.fb,c);return c}return 0}b.Ea||S('Cannot pass "'+Qc(b)+'" as a '+this.name);b.Ea.Oa||S("Cannot pass deleted object as a pointer of type "+this.name);!this.Cb&&b.Ea.Ra.Cb&&S("Cannot convert argument of type "+(b.Ea.Ya?b.Ea.Ya.name:b.Ea.Ra.name)+" to parameter type "+this.name);c=Oc(b.Ea.Oa,b.Ea.Ra.Pa,this.Pa);if(this.Db)switch(void 0===b.Ea.Wa&&S("Passing raw pointer to smart pointer is illegal"),
this.dd){case 0:b.Ea.Ya===this?c=b.Ea.Wa:S("Cannot convert argument of type "+(b.Ea.Ya?b.Ea.Ya.name:b.Ea.Ra.name)+" to parameter type "+this.name);break;case 1:c=b.Ea.Wa;break;case 2:if(b.Ea.Ya===this)c=b.Ea.Wa;else{var d=b.clone();c=this.Rc(c,T(function(){d["delete"]()}));null!==a&&a.push(this.fb,c)}break;default:S("Unsupporting sharing policy")}return c}
function Sc(a,b){if(null===b)return this.Ob&&S("null is not a valid "+this.name),0;b.Ea||S('Cannot pass "'+Qc(b)+'" as a '+this.name);b.Ea.Oa||S("Cannot pass deleted object as a pointer of type "+this.name);b.Ea.Ra.Cb&&S("Cannot convert argument of type "+b.Ea.Ra.name+" to parameter type "+this.name);return Oc(b.Ea.Oa,b.Ea.Ra.Pa,this.Pa)}
function Tc(a,b,c,d){this.name=a;this.Pa=b;this.Ob=c;this.Cb=d;this.Db=!1;this.fb=this.Rc=this.Rb=this.kc=this.dd=this.Pc=void 0;void 0!==b.Za?this.toWireType=Rc:(this.toWireType=d?Pc:Sc,this.$a=null)}function Uc(a,b,c){h.hasOwnProperty(a)||rc("Replacing nonexistant public symbol");void 0!==h[a].Ua&&void 0!==c?h[a].Ua[c]=b:(h[a]=b,h[a].xb=c)}var Vc=[];function U(a){var b=Vc[a];b||(a>=Vc.length&&(Vc.length=a+1),Vc[a]=b=ya.get(a));return b}
function Wc(a,b){var c=[];return function(){c.length=0;Object.assign(c,arguments);if(a.includes("j")){var d=h["dynCall_"+a];d=c&&c.length?d.apply(null,[b].concat(c)):d.call(null,b)}else d=U(b).apply(null,c);return d}}function V(a,b){a=R(a);var c=a.includes("j")?Wc(a,b):U(b);"function"!=typeof c&&S("unknown function pointer with signature "+a+": "+b);return c}var Xc=void 0;function Yc(a){a=Zc(a);var b=R(a);$c(a);return b}
function ad(a,b){function c(f){e[f]||lc[f]||(mc[f]?mc[f].forEach(c):(d.push(f),e[f]=!0))}var d=[],e={};b.forEach(c);throw new Xc(a+": "+d.map(Yc).join([", "]));}function bd(a,b){for(var c=[],d=0;d<a;d++)c.push(I[b+4*d>>2]);return c}
function cd(a,b,c,d,e){var f=b.length;2>f&&S("argTypes array size mismatch! Must at least get return value and 'this' types!");var g=null!==b[1]&&null!==c,l=!1;for(c=1;c<b.length;++c)if(null!==b[c]&&void 0===b[c].$a){l=!0;break}var m="void"!==b[0].name,n=f-2,r=Array(n),p=[],q=[];return function(){arguments.length!==n&&S("function "+a+" called with "+arguments.length+" arguments, expected "+n+" args!");q.length=0;p.length=g?2:1;p[0]=e;if(g){var k=b[1].toWireType(q,this);p[1]=k}for(var t=0;t<n;++t)r[t]=
b[t+2].toWireType(q,arguments[t]),p.push(r[t]);t=d.apply(null,p);if(l)ic(q);else for(var x=g?1:2;x<b.length;x++){var z=1===x?k:r[x-2];null!==b[x].$a&&b[x].$a(z)}k=m?b[0].fromWireType(t):void 0;return k}}var dd=[],W=[{},{value:void 0},{value:null},{value:!0},{value:!1}];function ed(a){4<a&&0===--W[a].Tb&&(W[a]=void 0,dd.push(a))}
var X=a=>{a||S("Cannot use deleted val. handle = "+a);return W[a].value},T=a=>{switch(a){case void 0:return 1;case null:return 2;case !0:return 3;case !1:return 4;default:var b=dd.length?dd.pop():W.length;W[b]={Tb:1,value:a};return b}};function Qc(a){if(null===a)return"null";var b=typeof a;return"object"===b||"array"===b||"function"===b?a.toString():""+a}
function fd(a,b){switch(b){case 2:return function(c){return this.fromWireType(va[c>>2])};case 3:return function(c){return this.fromWireType(wa[c>>3])};default:throw new TypeError("Unknown float type: "+a);}}
function gd(a,b,c){switch(b){case 0:return c?function(d){return C[d]}:function(d){return w[d]};case 1:return c?function(d){return ua[d>>1]}:function(d){return D[d>>1]};case 2:return c?function(d){return E[d>>2]}:function(d){return I[d>>2]};default:throw new TypeError("Unknown integer type: "+a);}}var hd="undefined"!=typeof TextDecoder?new TextDecoder("utf-16le"):void 0;
function jd(a,b){var c=a>>1;for(var d=c+b/2;!(c>=d)&&D[c];)++c;c<<=1;if(32<c-a&&hd)return hd.decode(w.subarray(a,c));c="";for(d=0;!(d>=b/2);++d){var e=ua[a+2*d>>1];if(0==e)break;c+=String.fromCharCode(e)}return c}function kd(a,b,c){void 0===c&&(c=2147483647);if(2>c)return 0;c-=2;var d=b;c=c<2*a.length?c/2:a.length;for(var e=0;e<c;++e)ua[b>>1]=a.charCodeAt(e),b+=2;ua[b>>1]=0;return b-d}function ld(a){return 2*a.length}
function md(a,b){for(var c=0,d="";!(c>=b/4);){var e=E[a+4*c>>2];if(0==e)break;++c;65536<=e?(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023)):d+=String.fromCharCode(e)}return d}function nd(a,b,c){void 0===c&&(c=2147483647);if(4>c)return 0;var d=b;c=d+c-4;for(var e=0;e<a.length;++e){var f=a.charCodeAt(e);if(55296<=f&&57343>=f){var g=a.charCodeAt(++e);f=65536+((f&1023)<<10)|g&1023}E[b>>2]=f;b+=4;if(b+4>c)break}E[b>>2]=0;return b-d}
function od(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&++c;b+=4}return b}function pd(a,b){var c=lc[a];void 0===c&&S(b+" has unknown type "+Yc(a));return c}function qd(a,b){for(var c=Array(a),d=0;d<a;++d)c[d]=pd(I[b+4*d>>2],"parameter "+d);return c}var rd={};function sd(a){var b=rd[a];return void 0===b?R(a):b}var td=[];
function ud(){function a(b){b.$$$embind_global$$$=b;var c="object"==typeof $$$embind_global$$$&&b.$$$embind_global$$$==b;c||delete b.$$$embind_global$$$;return c}if("object"==typeof globalThis)return globalThis;if("object"==typeof $$$embind_global$$$)return $$$embind_global$$$;"object"==typeof global&&a(global)?$$$embind_global$$$=global:"object"==typeof self&&a(self)&&($$$embind_global$$$=self);if("object"==typeof $$$embind_global$$$)return $$$embind_global$$$;throw Error("unable to get global object.");
}function vd(a){var b=td.length;td.push(a);return b}var wd=[];function xd(a){var b=Array(a+1);return function(c,d,e){b[0]=c;for(var f=0;f<a;++f){var g=pd(I[d+4*f>>2],"parameter "+f);b[f+1]=g.readValueFromPointer(e);e+=g.argPackAdvance}c=new (c.bind.apply(c,b));return T(c)}}var yd={};function zd(a){return 0===a%4&&(0!==a%100||0===a%400)}var Ad=[0,31,60,91,121,152,182,213,244,274,305,335],Bd=[0,31,59,90,120,151,181,212,243,273,304,334];
function Cd(a){return(zd(a.getFullYear())?Ad:Bd)[a.getMonth()]+a.getDate()-1}function Dd(a){var b=ta(a)+1,c=Ed(b);c&&A(a,C,c,b);return c}var Fd=[],Gd={};function Z(a,b){I[a>>2]=b;I[a+4>>2]=b/4294967296|0}var Hd;
function Id(a,b,c,d,e){function f(){var B=0,Y=0;y.response&&F&&0===I[a+12>>2]&&(Y=y.response.byteLength);0<Y&&(B=Ed(Y),w.set(new Uint8Array(y.response),B));I[a+12>>2]=B;Z(a+16,Y);Z(a+24,0);(B=y.response?y.response.byteLength:0)&&Z(a+32,B);D[a+40>>1]=y.readyState;D[a+42>>1]=y.status;y.statusText&&A(y.statusText,w,a+44,64)}var g=I[a+8>>2];if(g){var l=v(g),m=a+112,n=v(m);n||(n="GET");var r=I[m+52>>2],p=I[m+56>>2],q=!!I[m+60>>2],k=I[m+68>>2],t=I[m+72>>2];g=I[m+76>>2];var x=I[m+80>>2],z=I[m+84>>2];m=I[m+
88>>2];var F=!!(r&1),G=!!(r&2);r=!!(r&64);k=k?v(k):void 0;t=t?v(t):void 0;var y=new XMLHttpRequest;y.withCredentials=q;y.open(n,l,!r,k,t);r||(y.timeout=p);y.qd=l;y.responseType="arraybuffer";x&&(l=v(x),y.overrideMimeType(l));if(g)for(;;){n=I[g>>2];if(!n)break;l=I[g+4>>2];if(!l)break;g+=8;n=v(n);l=v(l);y.setRequestHeader(n,l)}var O=I[a+0>>2];Gd[O]=y;g=z&&m?w.slice(z,z+m):null;y.onload=B=>{O in Gd&&(f(),200<=y.status&&300>y.status?b&&b(a,y,B):c&&c(a,y,B))};y.onerror=B=>{O in Gd&&(f(),c&&c(a,y,B))};
y.ontimeout=B=>{O in Gd&&c&&c(a,y,B)};y.onprogress=B=>{if(O in Gd){var Y=F&&G&&y.response?y.response.byteLength:0,H=0;0<Y&&F&&G&&(H=Ed(Y),w.set(new Uint8Array(y.response),H));I[a+12>>2]=H;Z(a+16,Y);Z(a+24,B.loaded-Y);Z(a+32,B.total);D[a+40>>1]=y.readyState;3<=y.readyState&&0===y.status&&0<B.loaded&&(y.status=200);D[a+42>>1]=y.status;y.statusText&&A(y.statusText,w,a+44,64);d&&d(a,y,B);H&&$c(H)}};y.onreadystatechange=B=>{O in Gd&&(D[a+40>>1]=y.readyState,2<=y.readyState&&(D[a+42>>1]=y.status),e&&e(a,
y,B))};try{y.send(g)}catch(B){c&&c(a,y,B)}}else c(a,0,"no url specified!")}function Jd(a,b,c,d){var e=Hd;if(e){var f=I[a+112+64>>2];f||(f=I[a+8>>2]);var g=v(f);try{var l=e.transaction(["FILES"],"readwrite").objectStore("FILES").put(b,g);l.onsuccess=()=>{D[a+40>>1]=4;D[a+42>>1]=200;A("OK",w,a+44,64);c(a,0,g)};l.onerror=m=>{D[a+40>>1]=4;D[a+42>>1]=413;A("Payload Too Large",w,a+44,64);d(a,0,m)}}catch(m){d(a,0,m)}}else d(a,0,"IndexedDB not available!")}
function Kd(a,b,c){var d=Hd;if(d){var e=I[a+112+64>>2];e||(e=I[a+8>>2]);e=v(e);try{var f=d.transaction(["FILES"],"readonly").objectStore("FILES").get(e);f.onsuccess=g=>{if(g.target.result){g=g.target.result;var l=g.byteLength||g.length,m=Ed(l);w.set(new Uint8Array(g),m);I[a+12>>2]=m;Z(a+16,l);Z(a+24,0);Z(a+32,l);D[a+40>>1]=4;D[a+42>>1]=200;A("OK",w,a+44,64);b(a,0,g)}else D[a+40>>1]=4,D[a+42>>1]=404,A("Not Found",w,a+44,64),c(a,0,"no data")};f.onerror=g=>{D[a+40>>1]=4;D[a+42>>1]=404;A("Not Found",
w,a+44,64);c(a,0,g)}}catch(g){c(a,0,g)}}else c(a,0,"IndexedDB not available!")}
function Ld(a,b,c){var d=Hd;if(d){var e=I[a+112+64>>2];e||(e=I[a+8>>2]);e=v(e);try{var f=d.transaction(["FILES"],"readwrite").objectStore("FILES").delete(e);f.onsuccess=g=>{g=g.target.result;I[a+12>>2]=0;Z(a+16,0);Z(a+24,0);Z(a+32,0);D[a+40>>1]=4;D[a+42>>1]=200;A("OK",w,a+44,64);b(a,0,g)};f.onerror=g=>{D[a+40>>1]=4;D[a+42>>1]=404;A("Not Found",w,a+44,64);c(a,0,g)}}catch(g){c(a,0,g)}}else c(a,0,"IndexedDB not available!")}var Md={};
function Nd(){if(!Od){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"==typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:da||"./this.program"},b;for(b in Md)void 0===Md[b]?delete a[b]:a[b]=Md[b];var c=[];for(b in a)c.push(b+"="+a[b]);Od=c}return Od}var Od;function Pd(a,b){Pd.jc||(Pd.jc=Za());for(var c=0;c<b;c++)C[a+c>>0]=Pd.jc();return 0}
var Qd=[31,29,31,30,31,30,31,31,30,31,30,31],Rd=[31,28,31,30,31,30,31,31,30,31,30,31];
function Sd(a,b,c,d){function e(k,t,x){for(k="number"==typeof k?k.toString():k||"";k.length<t;)k=x[0]+k;return k}function f(k,t){return e(k,t,"0")}function g(k,t){function x(F){return 0>F?-1:0<F?1:0}var z;0===(z=x(k.getFullYear()-t.getFullYear()))&&0===(z=x(k.getMonth()-t.getMonth()))&&(z=x(k.getDate()-t.getDate()));return z}function l(k){switch(k.getDay()){case 0:return new Date(k.getFullYear()-1,11,29);case 1:return k;case 2:return new Date(k.getFullYear(),0,3);case 3:return new Date(k.getFullYear(),
0,2);case 4:return new Date(k.getFullYear(),0,1);case 5:return new Date(k.getFullYear()-1,11,31);case 6:return new Date(k.getFullYear()-1,11,30)}}function m(k){var t=k.jb;for(k=new Date((new Date(k.kb+1900,0,1)).getTime());0<t;){var x=k.getMonth(),z=(zd(k.getFullYear())?Qd:Rd)[x];if(t>z-k.getDate())t-=z-k.getDate()+1,k.setDate(1),11>x?k.setMonth(x+1):(k.setMonth(0),k.setFullYear(k.getFullYear()+1));else{k.setDate(k.getDate()+t);break}}x=new Date(k.getFullYear()+1,0,4);t=l(new Date(k.getFullYear(),
0,4));x=l(x);return 0>=g(t,k)?0>=g(x,k)?k.getFullYear()+1:k.getFullYear():k.getFullYear()-1}var n=E[d+40>>2];d={gd:E[d>>2],fd:E[d+4>>2],Ib:E[d+8>>2],Vb:E[d+12>>2],Jb:E[d+16>>2],kb:E[d+20>>2],cb:E[d+24>>2],jb:E[d+28>>2],pd:E[d+32>>2],ed:E[d+36>>2],hd:n?v(n):""};c=v(c);n={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S","%x":"%m/%d/%y","%X":"%H:%M:%S","%Ec":"%c","%EC":"%C","%Ex":"%m/%d/%y","%EX":"%H:%M:%S","%Ey":"%y","%EY":"%Y","%Od":"%d",
"%Oe":"%e","%OH":"%H","%OI":"%I","%Om":"%m","%OM":"%M","%OS":"%S","%Ou":"%u","%OU":"%U","%OV":"%V","%Ow":"%w","%OW":"%W","%Oy":"%y"};for(var r in n)c=c.replace(new RegExp(r,"g"),n[r]);var p="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),q="January February March April May June July August September October November December".split(" ");n={"%a":function(k){return p[k.cb].substring(0,3)},"%A":function(k){return p[k.cb]},"%b":function(k){return q[k.Jb].substring(0,3)},"%B":function(k){return q[k.Jb]},
"%C":function(k){return f((k.kb+1900)/100|0,2)},"%d":function(k){return f(k.Vb,2)},"%e":function(k){return e(k.Vb,2," ")},"%g":function(k){return m(k).toString().substring(2)},"%G":function(k){return m(k)},"%H":function(k){return f(k.Ib,2)},"%I":function(k){k=k.Ib;0==k?k=12:12<k&&(k-=12);return f(k,2)},"%j":function(k){for(var t=0,x=0;x<=k.Jb-1;t+=(zd(k.kb+1900)?Qd:Rd)[x++]);return f(k.Vb+t,3)},"%m":function(k){return f(k.Jb+1,2)},"%M":function(k){return f(k.fd,2)},"%n":function(){return"\n"},"%p":function(k){return 0<=
k.Ib&&12>k.Ib?"AM":"PM"},"%S":function(k){return f(k.gd,2)},"%t":function(){return"\t"},"%u":function(k){return k.cb||7},"%U":function(k){return f(Math.floor((k.jb+7-k.cb)/7),2)},"%V":function(k){var t=Math.floor((k.jb+7-(k.cb+6)%7)/7);2>=(k.cb+371-k.jb-2)%7&&t++;if(t)53==t&&(x=(k.cb+371-k.jb)%7,4==x||3==x&&zd(k.kb)||(t=1));else{t=52;var x=(k.cb+7-k.jb-1)%7;(4==x||5==x&&zd(k.kb%400-1))&&t++}return f(t,2)},"%w":function(k){return k.cb},"%W":function(k){return f(Math.floor((k.jb+7-(k.cb+6)%7)/7),2)},
"%y":function(k){return(k.kb+1900).toString().substring(2)},"%Y":function(k){return k.kb+1900},"%z":function(k){k=k.ed;var t=0<=k;k=Math.abs(k)/60;return(t?"+":"-")+String("0000"+(k/60*100+k%60)).slice(-4)},"%Z":function(k){return k.hd},"%%":function(){return"%"}};c=c.replace(/%%/g,"\x00\x00");for(r in n)c.includes(r)&&(c=c.replace(new RegExp(r,"g"),n[r](d)));c=c.replace(/\0\0/g,"%");r=ab(c,!1);if(r.length>b)return 0;C.set(r,a);return r.length-1}
function zb(a,b,c,d){a||(a=this);this.parent=a;this.eb=a.eb;this.sb=null;this.id=rb++;this.name=b;this.mode=c;this.Ma={};this.Na={};this.ub=d}Object.defineProperties(zb.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}},Kc:{get:function(){return 16384===(this.mode&61440)}},Jc:{get:function(){return 8192===(this.mode&61440)}}});Sb();
sb=Array(4096);Gb(N,"/");P("/tmp",16895,0);P("/home",16895,0);P("/home/web_user",16895,0);(()=>{P("/dev",16895,0);db(259,{read:()=>0,write:(b,c,d,e)=>e});Hb("/dev/null",259);cb(1280,fb);cb(1536,gb);Hb("/dev/tty",1280);Hb("/dev/tty1",1536);var a=Za();Yb("/dev","random",a);Yb("/dev","urandom",a);P("/dev/shm",16895,0);P("/dev/shm/tmp",16895,0)})();
(()=>{P("/proc",16895,0);var a=P("/proc/self",16895,0);P("/proc/self/fd",16895,0);Gb({eb:()=>{var b=kb(a,"fd",16895,73);b.Ma={qb:(c,d)=>{var e=qb[+d];if(!e)throw new M(8);c={parent:null,eb:{hc:"fake"},Ma:{vb:()=>e.path}};return c.parent=c}};return b}},"/proc/self/fd")})();var ac;h.FS_createPath=Vb;h.FS_createDataFile=Xb;h.FS_createPreloadedFile=bc;h.FS_unlink=Jb;h.FS_createLazyFile=$b;h.FS_createDevice=Yb;qc=h.InternalError=pc("InternalError");for(var Td=Array(256),Ud=0;256>Ud;++Ud)Td[Ud]=String.fromCharCode(Ud);
vc=Td;wc=h.BindingError=pc("BindingError");Kc.prototype.isAliasOf=function(a){if(!(this instanceof Kc&&a instanceof Kc))return!1;var b=this.Ea.Ra.Pa,c=this.Ea.Oa,d=a.Ea.Ra.Pa;for(a=a.Ea.Oa;b.Za;)c=b.wb(c),b=b.Za;for(;d.Za;)a=d.wb(a),d=d.Za;return b===d&&c===a};
Kc.prototype.clone=function(){this.Ea.Oa||xc(this);if(this.Ea.tb)return this.Ea.count.value+=1,this;var a=Jc,b=Object,c=b.create,d=Object.getPrototypeOf(this),e=this.Ea;a=a(c.call(b,d,{Ea:{value:{count:e.count,mb:e.mb,tb:e.tb,Oa:e.Oa,Ra:e.Ra,Wa:e.Wa,Ya:e.Ya}}}));a.Ea.count.value+=1;a.Ea.mb=!1;return a};Kc.prototype["delete"]=function(){this.Ea.Oa||xc(this);this.Ea.mb&&!this.Ea.tb&&S("Object already scheduled for deletion");zc(this);Ac(this.Ea);this.Ea.tb||(this.Ea.Wa=void 0,this.Ea.Oa=void 0)};
Kc.prototype.isDeleted=function(){return!this.Ea.Oa};Kc.prototype.deleteLater=function(){this.Ea.Oa||xc(this);this.Ea.mb&&!this.Ea.tb&&S("Object already scheduled for deletion");Dc.push(this);1===Dc.length&&Fc&&Fc(Ec);this.Ea.mb=!0;return this};h.getInheritedInstanceCount=function(){return Object.keys(Gc).length};h.getLiveInheritedInstances=function(){var a=[],b;for(b in Gc)Gc.hasOwnProperty(b)&&a.push(Gc[b]);return a};h.flushPendingDeletes=Ec;h.setDelayFunction=function(a){Fc=a;Dc.length&&Fc&&Fc(Ec)};
Tc.prototype.Cc=function(a){this.kc&&(a=this.kc(a));return a};Tc.prototype.ac=function(a){this.fb&&this.fb(a)};Tc.prototype.argPackAdvance=8;Tc.prototype.readValueFromPointer=jc;Tc.prototype.deleteObject=function(a){if(null!==a)a["delete"]()};
Tc.prototype.fromWireType=function(a){function b(){return this.Db?Ic(this.Pa.nb,{Ra:this.Pc,Oa:c,Ya:this,Wa:a}):Ic(this.Pa.nb,{Ra:this,Oa:a})}var c=this.Cc(a);if(!c)return this.ac(a),null;var d=Hc(this.Pa,c);if(void 0!==d){if(0===d.Ea.count.value)return d.Ea.Oa=c,d.Ea.Wa=a,d.clone();d=d.clone();this.ac(a);return d}d=this.Pa.Bc(c);d=Cc[d];if(!d)return b.call(this);d=this.Cb?d.vc:d.pointerType;var e=Bc(c,this.Pa,d.Pa);return null===e?b.call(this):this.Db?Ic(d.Pa.nb,{Ra:d,Oa:e,Ya:this,Wa:a}):Ic(d.Pa.nb,
{Ra:d,Oa:e})};Xc=h.UnboundTypeError=pc("UnboundTypeError");h.count_emval_handles=function(){for(var a=0,b=5;b<W.length;++b)void 0!==W[b]&&++a;return a};h.get_first_emval=function(){for(var a=5;a<W.length;++a)if(void 0!==W[a])return W[a];return null};Ga("library_fetch_init");
(function(a,b){try{var c=indexedDB.open("emscripten_filesystem",1)}catch(d){b(d);return}c.onupgradeneeded=d=>{d=d.target.result;d.objectStoreNames.contains("FILES")&&d.deleteObjectStore("FILES");d.createObjectStore("FILES")};c.onsuccess=d=>a(d.target.result);c.onerror=d=>b(d)})(a=>{Hd=a;Ha("library_fetch_init")},()=>{Hd=!1;Ha("library_fetch_init")});
var Zd={ra:function(a,b,c){(new Ua(a)).Hc(b,c);Va++;throw a;},F:function(a,b,c){fc=c;try{var d=dc(a);switch(b){case 0:var e=gc();return 0>e?-28:Fb(d,e).gb;case 1:case 2:return 0;case 3:return d.flags;case 4:return e=gc(),d.flags|=e,0;case 5:return e=gc(),ua[e+0>>1]=2,0;case 6:case 7:return 0;case 16:case 8:return-28;case 9:return-1;default:return-28}}catch(f){if("undefined"==typeof Q||"ErrnoError"!==f.name)throw f;return-f.Va}},ca:function(a,b){try{var c=dc(a);return ec(Kb,c.path,b)}catch(d){if("undefined"==
typeof Q||"ErrnoError"!==d.name)throw d;return-d.Va}},da:function(a,b,c){fc=c;try{var d=dc(a);switch(b){case 21509:case 21505:return d.Sa?0:-59;case 21510:case 21511:case 21512:case 21506:case 21507:case 21508:return d.Sa?0:-59;case 21519:if(!d.Sa)return-59;var e=gc();return E[e>>2]=0;case 21520:return d.Sa?-28:-59;case 21531:a=e=gc();if(!d.Na.Ic)throw new M(59);return d.Na.Ic(d,b,a);case 21523:return d.Sa?0:-59;case 21524:return d.Sa?0:-59;default:return-28}}catch(f){if("undefined"==typeof Q||"ErrnoError"!==
f.name)throw f;return-f.Va}},aa:function(a,b,c,d){try{b=v(b);var e=d&256;b=cc(a,b,d&4096);return ec(e?Lb:Kb,b,c)}catch(f){if("undefined"==typeof Q||"ErrnoError"!==f.name)throw f;return-f.Va}},G:function(a,b,c,d){fc=d;try{b=v(b);b=cc(a,b);var e=d?gc():0;return Ob(b,c,e).gb}catch(f){if("undefined"==typeof Q||"ErrnoError"!==f.name)throw f;return-f.Va}},ba:function(a,b){try{return a=v(a),ec(Kb,a,b)}catch(c){if("undefined"==typeof Q||"ErrnoError"!==c.name)throw c;return-c.Va}},d:function(a){var b=hc[a];
delete hc[a];var c=b.Rb,d=b.fb,e=b.cc,f=e.map(g=>g.Ec).concat(e.map(g=>g.bd));sc([a],f,g=>{var l={};e.forEach((m,n)=>{var r=g[n],p=m.Bb,q=m.Dc,k=g[n+e.length],t=m.ad,x=m.cd;l[m.Ac]={read:z=>r.fromWireType(p(q,z)),write:(z,F)=>{var G=[];t(x,z,k.toWireType(G,F));ic(G)}}});return[{name:b.name,fromWireType:function(m){var n={},r;for(r in l)n[r]=l[r].read(m);d(m);return n},toWireType:function(m,n){for(var r in l)if(!(r in n))throw new TypeError('Missing field:  "'+r+'"');var p=c();for(r in l)l[r].write(p,
n[r]);null!==m&&m.push(d,p);return p},argPackAdvance:8,readValueFromPointer:jc,$a:d}]})},P:function(){},ka:function(a,b,c,d,e){var f=uc(c);b=R(b);tc(a,{name:b,fromWireType:function(g){return!!g},toWireType:function(g,l){return l?d:e},argPackAdvance:8,readValueFromPointer:function(g){if(1===c)var l=C;else if(2===c)l=ua;else if(4===c)l=E;else throw new TypeError("Unknown boolean type size: "+b);return this.fromWireType(l[g>>f])},$a:null})},r:function(a,b,c,d,e,f,g,l,m,n,r,p,q){r=R(r);f=V(e,f);l&&(l=
V(g,l));n&&(n=V(m,n));q=V(p,q);var k=nc(r);Mc(k,function(){ad("Cannot construct "+r+" due to unbound types",[d])});sc([a,b,c],d?[d]:[],function(t){t=t[0];if(d){var x=t.Pa;var z=x.nb}else z=Kc.prototype;t=oc(k,function(){if(Object.getPrototypeOf(this)!==F)throw new wc("Use 'new' to construct "+r);if(void 0===G.hb)throw new wc(r+" has no accessible constructor");var O=G.hb[arguments.length];if(void 0===O)throw new wc("Tried to invoke ctor of "+r+" with invalid number of parameters ("+arguments.length+
") - expected ("+Object.keys(G.hb).toString()+") parameters instead!");return O.apply(this,arguments)});var F=Object.create(z,{constructor:{value:t}});t.prototype=F;var G=new Nc(r,t,F,q,x,f,l,n);x=new Tc(r,G,!0,!1);z=new Tc(r+"*",G,!1,!1);var y=new Tc(r+" const*",G,!1,!0);Cc[a]={pointerType:z,vc:y};Uc(k,t);return[x,z,y]})},u:function(a,b,c,d,e,f){0<b||oa();var g=bd(b,c);e=V(d,e);sc([],[a],function(l){l=l[0];var m="constructor "+l.name;void 0===l.Pa.hb&&(l.Pa.hb=[]);if(void 0!==l.Pa.hb[b-1])throw new wc("Cannot register multiple constructors with identical number of parameters ("+
(b-1)+") for class '"+l.name+"'! Overload resolution is currently only performed using the parameter count, not actual type info!");l.Pa.hb[b-1]=()=>{ad("Cannot construct "+l.name+" due to unbound types",g)};sc([],g,function(n){n.splice(1,0,null);l.Pa.hb[b-1]=cd(m,n,null,e,f);return[]});return[]})},i:function(a,b,c,d,e,f,g,l){var m=bd(c,d);b=R(b);f=V(e,f);sc([],[a],function(n){function r(){ad("Cannot call "+p+" due to unbound types",m)}n=n[0];var p=n.name+"."+b;b.startsWith("@@")&&(b=Symbol[b.substring(2)]);
l&&n.Pa.Qc.push(b);var q=n.Pa.nb,k=q[b];void 0===k||void 0===k.Ua&&k.className!==n.name&&k.xb===c-2?(r.xb=c-2,r.className=n.name,q[b]=r):(Lc(q,b,p),q[b].Ua[c-2]=r);sc([],m,function(t){t=cd(p,t,n,f,g);void 0===q[b].Ua?(t.xb=c-2,q[b]=t):q[b].Ua[c-2]=t;return[]});return[]})},ja:function(a,b){b=R(b);tc(a,{name:b,fromWireType:function(c){var d=X(c);ed(c);return d},toWireType:function(c,d){return T(d)},argPackAdvance:8,readValueFromPointer:jc,$a:null})},I:function(a,b,c){c=uc(c);b=R(b);tc(a,{name:b,fromWireType:function(d){return d},
toWireType:function(d,e){return e},argPackAdvance:8,readValueFromPointer:fd(b,c),$a:null})},A:function(a,b,c,d,e,f){var g=bd(b,c);a=R(a);e=V(d,e);Mc(a,function(){ad("Cannot call "+a+" due to unbound types",g)},b-1);sc([],g,function(l){Uc(a,cd(a,[l[0],null].concat(l.slice(1)),null,e,f),b-1);return[]})},o:function(a,b,c,d,e){b=R(b);-1===e&&(e=4294967295);e=uc(c);var f=l=>l;if(0===d){var g=32-8*c;f=l=>l<<g>>>g}c=b.includes("unsigned")?function(l,m){return m>>>0}:function(l,m){return m};tc(a,{name:b,
fromWireType:f,toWireType:c,argPackAdvance:8,readValueFromPointer:gd(b,e,0!==d),$a:null})},h:function(a,b,c){function d(f){f>>=2;var g=I;return new e(g.buffer,g[f+1],g[f])}var e=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array][b];c=R(c);tc(a,{name:c,fromWireType:d,argPackAdvance:8,readValueFromPointer:d},{Gc:!0})},J:function(a,b){b=R(b);var c="std::string"===b;tc(a,{name:b,fromWireType:function(d){var e=I[d>>2],f=d+4;if(c)for(var g=f,l=0;l<=e;++l){var m=
f+l;if(l==e||0==w[m]){g=v(g,m-g);if(void 0===n)var n=g;else n+=String.fromCharCode(0),n+=g;g=m+1}}else{n=Array(e);for(l=0;l<e;++l)n[l]=String.fromCharCode(w[f+l]);n=n.join("")}$c(d);return n},toWireType:function(d,e){e instanceof ArrayBuffer&&(e=new Uint8Array(e));var f="string"==typeof e;f||e instanceof Uint8Array||e instanceof Uint8ClampedArray||e instanceof Int8Array||S("Cannot pass non-string to std::string");var g=c&&f?ta(e):e.length;var l=Ed(4+g+1),m=l+4;I[l>>2]=g;if(c&&f)A(e,w,m,g+1);else if(f)for(f=
0;f<g;++f){var n=e.charCodeAt(f);255<n&&($c(m),S("String has UTF-16 code units that do not fit in 8 bits"));w[m+f]=n}else for(f=0;f<g;++f)w[m+f]=e[f];null!==d&&d.push($c,l);return l},argPackAdvance:8,readValueFromPointer:jc,$a:function(d){$c(d)}})},z:function(a,b,c){c=R(c);if(2===b){var d=jd;var e=kd;var f=ld;var g=()=>D;var l=1}else 4===b&&(d=md,e=nd,f=od,g=()=>I,l=2);tc(a,{name:c,fromWireType:function(m){for(var n=I[m>>2],r=g(),p,q=m+4,k=0;k<=n;++k){var t=m+4+k*b;if(k==n||0==r[t>>l])q=d(q,t-q),
void 0===p?p=q:(p+=String.fromCharCode(0),p+=q),q=t+b}$c(m);return p},toWireType:function(m,n){"string"!=typeof n&&S("Cannot pass non-string to C++ string type "+c);var r=f(n),p=Ed(4+r+b);I[p>>2]=r>>l;e(n,p+4,r+b);null!==m&&m.push($c,p);return p},argPackAdvance:8,readValueFromPointer:jc,$a:function(m){$c(m)}})},e:function(a,b,c,d,e,f){hc[a]={name:R(b),Rb:V(c,d),fb:V(e,f),cc:[]}},b:function(a,b,c,d,e,f,g,l,m,n){hc[a].cc.push({Ac:R(b),Ec:c,Bb:V(d,e),Dc:f,bd:g,ad:V(l,m),cd:n})},la:function(a,b){b=R(b);
tc(a,{Lc:!0,name:b,argPackAdvance:0,fromWireType:function(){},toWireType:function(){}})},ma:function(a){var b=Gd[a];b&&(delete Gd[a],0<b.readyState&&4>b.readyState&&b.abort())},fa:function(){return!0},T:function(){throw Infinity;},m:function(a,b,c){a=X(a);b=pd(b,"emval::as");var d=[],e=T(d);I[c>>2]=e;return b.toWireType(d,a)},L:function(a,b,c,d){a=X(a);c=qd(b,c);for(var e=Array(b),f=0;f<b;++f){var g=c[f];e[f]=g.readValueFromPointer(d);d+=g.argPackAdvance}a=a.apply(void 0,e);return T(a)},q:function(a,
b,c,d){a=td[a];b=X(b);c=sd(c);a(b,c,null,d)},c:ed,M:function(a,b){a=X(a);b=X(b);return a==b},s:function(a){if(0===a)return T(ud());a=sd(a);return T(ud()[a])},t:function(a,b){var c=qd(a,b),d=c[0];b=d.name+"_$"+c.slice(1).map(function(g){return g.name}).join("_")+"$";var e=wd[b];if(void 0!==e)return e;var f=Array(a-1);e=vd((g,l,m,n)=>{for(var r=0,p=0;p<a-1;++p)f[p]=c[p+1].readValueFromPointer(n+r),r+=c[p+1].argPackAdvance;g=g[l].apply(g,f);for(p=0;p<a-1;++p)c[p+1].xc&&c[p+1].xc(f[p]);if(!d.Lc)return d.toWireType(m,
g)});return wd[b]=e},B:function(a,b){a=X(a);b=X(b);return T(a[b])},v:function(a){4<a&&(W[a].Tb+=1)},sa:function(a,b){a=X(a);b=X(b);return a instanceof b},w:function(a,b,c,d){a=X(a);var e=yd[b];e||(e=xd(b),yd[b]=e);return e(a,c,d)},k:function(){return T([])},f:function(a){return T(sd(a))},n:function(){return T({})},l:function(a){var b=X(a);ic(b);ed(a)},g:function(a,b,c){a=X(a);b=X(b);c=X(c);a[b]=c},j:function(a,b){a=pd(a,"_emval_take_value");a=a.readValueFromPointer(b);return T(a)},N:function(a){a=
X(a);return T(typeof a)},ga:function(a,b){a=new Date(1E3*(I[a>>2]+4294967296*E[a+4>>2]));E[b>>2]=a.getSeconds();E[b+4>>2]=a.getMinutes();E[b+8>>2]=a.getHours();E[b+12>>2]=a.getDate();E[b+16>>2]=a.getMonth();E[b+20>>2]=a.getFullYear()-1900;E[b+24>>2]=a.getDay();E[b+28>>2]=Cd(a)|0;E[b+36>>2]=-(60*a.getTimezoneOffset());var c=(new Date(a.getFullYear(),6,1)).getTimezoneOffset(),d=(new Date(a.getFullYear(),0,1)).getTimezoneOffset();E[b+32>>2]=(c!=d&&a.getTimezoneOffset()==Math.min(d,c))|0},ha:function(a){var b=
new Date(E[a+20>>2]+1900,E[a+16>>2],E[a+12>>2],E[a+8>>2],E[a+4>>2],E[a>>2],0),c=E[a+32>>2],d=b.getTimezoneOffset(),e=(new Date(b.getFullYear(),6,1)).getTimezoneOffset(),f=(new Date(b.getFullYear(),0,1)).getTimezoneOffset(),g=Math.min(f,e);0>c?E[a+32>>2]=Number(e!=f&&g==d):0<c!=(g==d)&&(e=Math.max(f,e),b.setTime(b.getTime()+6E4*((0<c?g:e)-d)));E[a+24>>2]=b.getDay();E[a+28>>2]=Cd(b)|0;E[a>>2]=b.getSeconds();E[a+4>>2]=b.getMinutes();E[a+8>>2]=b.getHours();E[a+12>>2]=b.getDate();E[a+16>>2]=b.getMonth();
E[a+20>>2]=b.getYear();return b.getTime()/1E3|0},Y:function(a,b,c,d,e,f,g){try{var l=dc(d);if(0!==(b&2)&&0===(c&2)&&2!==(l.flags&2097155))throw new M(2);if(1===(l.flags&2097155))throw new M(2);if(!l.Na.rb)throw new M(43);var m=l.Na.rb(l,a,e,b,c);var n=m.Oa;E[f>>2]=m.Xb;I[g>>2]=n;return 0}catch(r){if("undefined"==typeof Q||"ErrnoError"!==r.name)throw r;return-r.Va}},Z:function(a,b,c,d,e,f){try{var g=dc(e);if(c&2){if(32768!==(g.node.mode&61440))throw new M(43);d&2||g.Na.Fb&&g.Na.Fb(g,w.slice(a,a+b),
f,b,d)}}catch(l){if("undefined"==typeof Q||"ErrnoError"!==l.name)throw l;return-l.Va}},ia:function(a,b,c){function d(m){return(m=m.toTimeString().match(/\(([A-Za-z ]+)\)$/))?m[1]:"GMT"}var e=(new Date).getFullYear(),f=new Date(e,0,1),g=new Date(e,6,1);e=f.getTimezoneOffset();var l=g.getTimezoneOffset();I[a>>2]=60*Math.max(e,l);E[b>>2]=Number(e!=l);a=d(f);b=d(g);a=Dd(a);b=Dd(b);l<e?(I[c>>2]=a,I[c+4>>2]=b):(I[c>>2]=b,I[c+4>>2]=a)},a:function(){oa("")},p:function(a,b,c){Fd.length=0;var d;for(c>>=2;d=
w[b++];)c+=105!=d&c,Fd.push(105==d?E[c]:wa[c++>>1]),++c;return Pa[a].apply(null,Fd)},H:function(){return Date.now()},X:function(){return 2147483648},x:()=>performance.now(),oa:function(){return!ha},ea:function(a,b,c){w.copyWithin(a,b,b+c)},W:function(a){var b=w.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=Math,e=d.min;var f=Math.max(a,b+16777216/c);f+=(65536-f%65536)%65536;a:{var g=pa.buffer;try{pa.grow(e.call(d,2147483648,f)-g.byteLength+65535>>>16);xa();var l=1;break a}catch(m){}l=
void 0}if(l)return!0}return!1},na:function(a,b,c,d,e){function f(H){if(z)H();else if(!qa)try{H()}catch(Qa){Qa instanceof Sa||"unwind"==Qa||ea(1,Qa)}}var g=a+112,l=v(g),m=I[g+36>>2],n=I[g+40>>2],r=I[g+44>>2],p=I[g+48>>2],q=I[g+52>>2],k=!!(q&4),t=!!(q&32),x=!!(q&16),z=!!(q&64),F=H=>{f(()=>{m?U(m)(H):b&&b(H)})},G=H=>{f(()=>{r?U(r)(H):d&&d(H)})},y=H=>{f(()=>{n?U(n)(H):c&&c(H)})},O=H=>{f(()=>{p?U(p)(H):e&&e(H)})};q=H=>{Id(H,F,y,G,O)};var B=(H,Qa)=>{Jd(H,Qa.response,Ra=>{f(()=>{m?U(m)(Ra):b&&b(Ra)})},Ra=>
{f(()=>{m?U(m)(Ra):b&&b(Ra)})})},Y=H=>{Id(H,B,y,G,O)};if("EM_IDB_STORE"===l)l=I[g+84>>2],Jd(a,w.slice(l,l+I[g+88>>2]),F,y);else if("EM_IDB_DELETE"===l)Ld(a,F,y);else if(x){if(t)return 0;Id(a,k?B:F,y,G,O)}else Kd(a,F,t?y:k?Y:q);return a},_:function(a,b){var c=0;Nd().forEach(function(d,e){var f=b+c;e=I[a+4*e>>2]=f;for(f=0;f<d.length;++f)C[e++>>0]=d.charCodeAt(f);C[e>>0]=0;c+=d.length+1});return 0},$:function(a,b){var c=Nd();I[a>>2]=c.length;var d=0;c.forEach(function(e){d+=e.length+1});I[b>>2]=d;return 0},
K:function(a){if(!noExitRuntime){if(h.onExit)h.onExit(a);qa=!0}ea(a,new Sa(a))},y:function(a){try{var b=dc(a);Pb(b);return 0}catch(c){if("undefined"==typeof Q||"ErrnoError"!==c.name)throw c;return c.Va}},E:function(a,b,c,d){try{a:{var e=dc(a);a=b;for(var f,g=b=0;g<c;g++){var l=I[a>>2],m=I[a+4>>2];a+=8;var n=e,r=l,p=m,q=f,k=C;if(0>p||0>q)throw new M(28);if(null===n.gb)throw new M(8);if(1===(n.flags&2097155))throw new M(8);if(16384===(n.node.mode&61440))throw new M(31);if(!n.Na.read)throw new M(28);
var t="undefined"!=typeof q;if(!t)q=n.position;else if(!n.seekable)throw new M(70);var x=n.Na.read(n,k,r,p,q);t||(n.position+=x);var z=x;if(0>z){var F=-1;break a}b+=z;if(z<m)break;"undefined"!==typeof f&&(f+=z)}F=b}I[d>>2]=F;return 0}catch(G){if("undefined"==typeof Q||"ErrnoError"!==G.name)throw G;return G.Va}},O:function(a,b,c,d,e){try{b=c+2097152>>>0<4194305-!!b?(b>>>0)+4294967296*c:NaN;if(isNaN(b))return 61;var f=dc(a);Qb(f,b,d);K=[f.position>>>0,(J=f.position,1<=+Math.abs(J)?0<J?(Math.min(+Math.floor(J/
4294967296),4294967295)|0)>>>0:~~+Math.ceil((J-+(~~J>>>0))/4294967296)>>>0:0)];E[e>>2]=K[0];E[e+4>>2]=K[1];f.Mb&&0===b&&0===d&&(f.Mb=null);return 0}catch(g){if("undefined"==typeof Q||"ErrnoError"!==g.name)throw g;return g.Va}},D:function(a,b,c,d){try{a:{var e=dc(a);a=b;for(var f,g=b=0;g<c;g++){var l=I[a>>2],m=I[a+4>>2];a+=8;var n=Rb(e,C,l,m,f);if(0>n){var r=-1;break a}b+=n;"undefined"!==typeof f&&(f+=n)}r=b}I[d>>2]=r;return 0}catch(p){if("undefined"==typeof Q||"ErrnoError"!==p.name)throw p;return p.Va}},
pa:function(){var a=stackTrace(),b=ta(a)+1,c=Ed(b);A(a,w,c,b);return c},U:Pd,Q:Vd,C:Wd,R:Xd,S:Yd,qa:Sd,V:function(a,b,c,d){return Sd(a,b,c,d)}};(function(){function a(c){c=c.exports;h.asm=c;pa=h.asm.ta;xa();ya=h.asm.xa;Aa.unshift(h.asm.ua);Ha("wasm-instantiate");return c}var b={a:Zd};Ga("wasm-instantiate");if(h.instantiateWasm)try{return h.instantiateWasm(b,a)}catch(c){u("Module.instantiateWasm callback failed with error: "+c),ba(c)}Oa(b,function(c){a(c.instance)}).catch(ba);return{}})();
function Ed(){return(Ed=h.asm.va).apply(null,arguments)}function $c(){return($c=h.asm.wa).apply(null,arguments)}var Zc=h.___getTypeName=function(){return(Zc=h.___getTypeName=h.asm.ya).apply(null,arguments)};h.__embind_initialize_bindings=function(){return(h.__embind_initialize_bindings=h.asm.za).apply(null,arguments)};function ib(){return(ib=h.asm.Aa).apply(null,arguments)}function $d(){return($d=h.asm.Ba).apply(null,arguments)}function ae(){return(ae=h.asm.Ca).apply(null,arguments)}
function be(){return(be=h.asm.Da).apply(null,arguments)}h.dynCall_ji=function(){return(h.dynCall_ji=h.asm.Fa).apply(null,arguments)};h.dynCall_jiji=function(){return(h.dynCall_jiji=h.asm.Ga).apply(null,arguments)};h.dynCall_viijii=function(){return(h.dynCall_viijii=h.asm.Ha).apply(null,arguments)};h.dynCall_iiiiij=function(){return(h.dynCall_iiiiij=h.asm.Ia).apply(null,arguments)};h.dynCall_iiiiijj=function(){return(h.dynCall_iiiiijj=h.asm.Ja).apply(null,arguments)};
h.dynCall_iiiiiijj=function(){return(h.dynCall_iiiiiijj=h.asm.Ka).apply(null,arguments)};h.__ZN2MB2NN28LinearDefragmentingAllocator10Allocation4nullE=1024;h.___start_em_js=350862;h.___stop_em_js=351735;function Wd(a,b){var c=ae();try{U(a)(b)}catch(d){be(c);if(d!==d+0)throw d;$d(1,0)}}function Yd(a,b,c,d){var e=ae();try{U(a)(b,c,d)}catch(f){be(e);if(f!==f+0)throw f;$d(1,0)}}function Xd(a,b,c){var d=ae();try{U(a)(b,c)}catch(e){be(d);if(e!==e+0)throw e;$d(1,0)}}
function Vd(a,b,c,d){var e=ae();try{return U(a)(b,c,d)}catch(f){be(e);if(f!==f+0)throw f;$d(1,0)}}h.addRunDependency=Ga;h.removeRunDependency=Ha;h.FS_createPath=Vb;h.FS_createDataFile=Xb;h.FS_createPreloadedFile=bc;h.FS_createLazyFile=$b;h.FS_createDevice=Yb;h.FS_unlink=Jb;var ce;Fa=function de(){ce||ee();ce||(Fa=de)};
function ee(){function a(){if(!ce&&(ce=!0,h.calledRun=!0,!qa)){h.noFSInit||Tb||(Tb=!0,Sb(),h.stdin=h.stdin,h.stdout=h.stdout,h.stderr=h.stderr,h.stdin?Yb("/dev","stdin",h.stdin):Ib("/dev/tty","/dev/stdin"),h.stdout?Yb("/dev","stdout",null,h.stdout):Ib("/dev/tty","/dev/stdout"),h.stderr?Yb("/dev","stderr",null,h.stderr):Ib("/dev/tty1","/dev/stderr"),Ob("/dev/stdin",0),Ob("/dev/stdout",1),Ob("/dev/stderr",1));tb=!1;Ta(Aa);aa(h);if(h.onRuntimeInitialized)h.onRuntimeInitialized();if(h.postRun)for("function"==
typeof h.postRun&&(h.postRun=[h.postRun]);h.postRun.length;){var b=h.postRun.shift();Ba.unshift(b)}Ta(Ba)}}if(!(0<Da)){if(h.preRun)for("function"==typeof h.preRun&&(h.preRun=[h.preRun]);h.preRun.length;)Ca();Ta(za);0<Da||(h.setStatus?(h.setStatus("Running..."),setTimeout(function(){setTimeout(function(){h.setStatus("")},1);a()},1)):a())}}if(h.preInit)for("function"==typeof h.preInit&&(h.preInit=[h.preInit]);0<h.preInit.length;)h.preInit.pop()();ee();


  return BlinkIDWasmSDK.ready
}

);
})();
if (typeof exports === 'object' && typeof module === 'object')
  module.exports = BlinkIDWasmSDK;
else if (typeof define === 'function' && define['amd'])
  define([], function() { return BlinkIDWasmSDK; });
else if (typeof exports === 'object')
  exports["BlinkIDWasmSDK"] = BlinkIDWasmSDK;
