
var BlinkIDWasmSDK = (function() {
  var _scriptDir = typeof document !== 'undefined' && document.currentScript ? document.currentScript.src : undefined;
  
  return (
function(BlinkIDWasmSDK) {
  BlinkIDWasmSDK = BlinkIDWasmSDK || {};


function g(){n.buffer!=t&&aa(n.buffer);return ba}function x(){n.buffer!=t&&aa(n.buffer);return ca}function ea(){n.buffer!=t&&aa(n.buffer);return fa}function y(){n.buffer!=t&&aa(n.buffer);return ha}function A(){n.buffer!=t&&aa(n.buffer);return ia}function C(){n.buffer!=t&&aa(n.buffer);return ja}function ka(){n.buffer!=t&&aa(n.buffer);return la}var E;E||(E=typeof BlinkIDWasmSDK !== 'undefined' ? BlinkIDWasmSDK : {});var ma,na;E.ready=new Promise(function(a,b){ma=a;na=b});E.Vc||(E.Vc=0);E.Vc++;
(function(a){function b(m,q,p){var r=new XMLHttpRequest;r.open("GET",m,!0);r.responseType="arraybuffer";r.onprogress=function(u){var k=q;u.total&&(k=u.total);if(u.loaded){r.Hd?E.ic[m].loaded=u.loaded:(r.Hd=!0,E.ic||(E.ic={}),E.ic[m]={loaded:u.loaded,total:k});var v=k=u=0,z;for(z in E.ic){var B=E.ic[z];u+=B.total;k+=B.loaded;v++}u=Math.ceil(u*E.Vc/v);E.setStatus&&E.setStatus("Downloading data... ("+k+"/"+u+")")}else!E.ic&&E.setStatus&&E.setStatus("Downloading data...")};r.onerror=function(){throw Error("NetworkError for: "+
m);};r.onload=function(){if(200==r.status||304==r.status||206==r.status||0==r.status&&r.response)p(r.response);else throw Error(r.statusText+" : "+r.responseURL);};r.send(null)}function c(m){console.error("package error:",m)}function d(){function m(u,k,v){this.start=u;this.end=k;this.audio=v}function q(u){if(!u)throw"Loading data file failed."+Error().stack;if(!(u instanceof ArrayBuffer))throw"bad input to processPackageData"+Error().stack;u=new Uint8Array(u);m.prototype.Md=u;u=a.files;for(var k=
0;k<u.length;++k)m.prototype.fd[u[k].filename].onload();E.removeRunDependency("datafile_../../resources/advanced-threads/BlinkIDWasmSDK.data")}E.FS_createPath("/","microblink",!0,!0);m.prototype={fd:{},open:function(u,k){this.name=k;this.fd[k]=this;E.addRunDependency("fp "+this.name)},send:function(){},onload:function(){this.finish(this.Md.subarray(this.start,this.end))},finish:function(u){E.FS_createDataFile(this.name,null,u,!0,!0,!0);E.removeRunDependency("fp "+this.name);this.fd[this.name]=null}};
for(var p=a.files,r=0;r<p.length;++r)(new m(p[r].start,p[r].end,p[r].audio)).open("GET",p[r].filename);E.addRunDependency("datafile_../../resources/advanced-threads/BlinkIDWasmSDK.data");E.yd||(E.yd={});E.yd["../../resources/advanced-threads/BlinkIDWasmSDK.data"]={Ze:!1};l?(q(l),l=null):h=q}if("object"===typeof window)window.encodeURIComponent(window.location.pathname.toString().substring(0,window.location.pathname.toString().lastIndexOf("/"))+"/");else if("undefined"!==typeof location)encodeURIComponent(location.pathname.toString().substring(0,
location.pathname.toString().lastIndexOf("/"))+"/");else throw"using preloaded data can only be done on a web page or in a web worker";"function"!==typeof E.locateFilePackage||E.locateFile||(E.locateFile=E.locateFilePackage,F("warning: you defined Module.locateFilePackage, that has been renamed to Module.locateFile (using your locateFilePackage for now)"));var e=E.locateFile?E.locateFile("BlinkIDWasmSDK.data",""):"BlinkIDWasmSDK.data",f=a.remote_package_size,h=null,l=E.getPreloadedPackage?E.getPreloadedPackage(e,
f):null;l||b(e,f,function(m){h?(h(m),h=null):l=m},c);E.calledRun?d():(E.preRun||(E.preRun=[]),E.preRun.push(d))})({files:[{filename:"/microblink/BlinkID_BlurClassifier_general_6.2.0.strop",start:0,end:4418,audio:0},{filename:"/microblink/BlinkID_Detector_general_6.6.0.strop",start:4418,end:293394,audio:0},{filename:"/microblink/BlinkID_RotationClassifier_general_6.2.0.strop",start:293394,end:350356,audio:0},{filename:"/microblink/face_detector_model.zzip",start:350356,end:447214,audio:0},{filename:"/microblink/ccc_lookup_table.zzip",
start:447214,end:467683,audio:0},{filename:"/microblink/BlinkID_Analyzer_general_6.5.0.strop",start:467683,end:485477,audio:0},{filename:"/microblink/BlinkID_MonochromeClassifier_general_6.0.0.strop",start:485477,end:492967,audio:0},{filename:"/microblink/BlinkID_Segmentator_general_6.14.0.strop",start:492967,end:2274783,audio:0},{filename:"/microblink/BlinkID_Ocr_general_6.13.0.strop",start:2274783,end:2586091,audio:0},{filename:"/microblink/BlinkID_Classifier_general_6.14.0.strop",start:2586091,
end:3030189,audio:0},{filename:"/microblink/BlinkID_MoireClassifier_malaysia_6.0.0.strop",start:3030189,end:3037423,audio:0},{filename:"/microblink/BlinkID_Ocr_mrz_6.4.0.strop",start:3037423,end:3407791,audio:0}],remote_package_size:3407791,package_uuid:"6c9047dc-763f-4891-bd5f-4770aa836939"});var crypto={getRandomValues:function(a){for(var b=0;b<a.length;b++)a[b]=256*Math.random()|0}},oa;oa=E.allowedThreads&&0<E.allowedThreads?E.allowedThreads-1:navigator.hardwareConcurrency-1;var pa=0,qa;
0<oa&&(E.threadWorkersReadyPromise=new Promise(function(a){qa=a}));E.preRun||(E.preRun=[]);E.preRun.push(function(a){function b(){pa++;pa==oa&&qa()}var c=a.PThread.ad;a.PThread.ad=function(d){c(d,b)}});var sa={},ta;for(ta in E)E.hasOwnProperty(ta)&&(sa[ta]=E[ta]);var ua="./this.program";function va(a,b){throw b;}var wa=!1,xa=!1,ya=!1;wa="object"===typeof window;xa="function"===typeof importScripts;ya="object"===typeof process&&"object"===typeof process.Se&&"string"===typeof process.Se.node;
var G=E.ENVIRONMENT_IS_PTHREAD||!1;G&&(t=E.buffer);var za="";function Aa(a){return E.locateFile?E.locateFile(a,za):za+a}var Ba,Ca;
if(wa||xa)xa?za=self.location.href:"undefined"!==typeof document&&document.currentScript&&(za=document.currentScript.src),_scriptDir&&(za=_scriptDir),za=0!==za.indexOf("blob:")?za.substr(0,za.lastIndexOf("/")+1):"",Ba=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},xa&&(Ca=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});
var Da=E.print||console.log.bind(console),F=E.printErr||console.warn.bind(console);for(ta in sa)sa.hasOwnProperty(ta)&&(E[ta]=sa[ta]);sa=null;E.thisProgram&&(ua=E.thisProgram);E.quit&&(va=E.quit);var Ea,Fa=0,Ga;E.wasmBinary&&(Ga=E.wasmBinary);var noExitRuntime=E.noExitRuntime||!0;"object"!==typeof WebAssembly&&H("no native wasm support detected");var n,Ha,Ia=!1,Ja;function Ka(a,b){a||H("Assertion failed: "+b)}
function La(a,b,c){c=b+c;for(var d="";!(b>=c);){var e=a[b++];if(!e)break;if(e&128){var f=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|f);else{var h=a[b++]&63;e=224==(e&240)?(e&15)<<12|f<<6|h:(e&7)<<18|f<<12|h<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d}function K(a,b){return a?La(x(),a,b):""}
function Ma(a,b,c,d){if(!(0<d))return 0;var e=c;d=c+d-1;for(var f=0;f<a.length;++f){var h=a.charCodeAt(f);if(55296<=h&&57343>=h){var l=a.charCodeAt(++f);h=65536+((h&1023)<<10)|l&1023}if(127>=h){if(c>=d)break;b[c++]=h}else{if(2047>=h){if(c+1>=d)break;b[c++]=192|h>>6}else{if(65535>=h){if(c+2>=d)break;b[c++]=224|h>>12}else{if(c+3>=d)break;b[c++]=240|h>>18;b[c++]=128|h>>12&63}b[c++]=128|h>>6&63}b[c++]=128|h&63}}b[c]=0;return c-e}function Na(a,b,c){Ma(a,x(),b,c)}
function Oa(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:b+4}return b}function Pa(a,b){for(var c="",d=0;!(d>=b/2);++d){var e=ea()[a+2*d>>1];if(0==e)break;c+=String.fromCharCode(e)}return c}function Qa(a,b,c){void 0===c&&(c=2147483647);if(2>c)return 0;c-=2;var d=b;c=c<2*a.length?c/2:a.length;for(var e=0;e<c;++e){var f=a.charCodeAt(e);ea()[b>>1]=f;b+=2}ea()[b>>1]=0;return b-d}
function Ra(a){return 2*a.length}function Sa(a,b){for(var c=0,d="";!(c>=b/4);){var e=A()[a+4*c>>2];if(0==e)break;++c;65536<=e?(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023)):d+=String.fromCharCode(e)}return d}function Ta(a,b,c){void 0===c&&(c=2147483647);if(4>c)return 0;var d=b;c=d+c-4;for(var e=0;e<a.length;++e){var f=a.charCodeAt(e);if(55296<=f&&57343>=f){var h=a.charCodeAt(++e);f=65536+((f&1023)<<10)|h&1023}A()[b>>2]=f;b+=4;if(b+4>c)break}A()[b>>2]=0;return b-d}
function Ua(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&++c;b+=4}return b}function Va(a){var b=Oa(a)+1,c=L(b);c&&Ma(a,g(),c,b);return c}function Wa(a,b){g().set(a,b)}var t,ba,ca,fa,ha,ia,ja,Xa,la;function aa(a){t=a;E.HEAP8=ba=new Int8Array(a);E.HEAP16=fa=new Int16Array(a);E.HEAP32=ia=new Int32Array(a);E.HEAPU8=ca=new Uint8Array(a);E.HEAPU16=ha=new Uint16Array(a);E.HEAPU32=ja=new Uint32Array(a);E.HEAPF32=Xa=new Float32Array(a);E.HEAPF64=la=new Float64Array(a)}
var Ya=E.INITIAL_MEMORY||209715200;
if(G)n=E.wasmMemory,t=E.buffer;else if(E.wasmMemory)n=E.wasmMemory;else if(n=new WebAssembly.Memory({initial:Ya/65536,maximum:12800,shared:!0}),!(n.buffer instanceof SharedArrayBuffer))throw F("requested a shared WebAssembly.Memory but the returned buffer is not a SharedArrayBuffer, indicating that while the browser has SharedArrayBuffer it does not have WebAssembly threads support - you may need to set a flag"),ya&&console.log("(on node you may need: --experimental-wasm-threads --experimental-wasm-bulk-memory and also use a recent version)"),Error("bad memory");
n&&(t=n.buffer);Ya=t.byteLength;aa(t);var M,Za=[],$a=[],ab=[],bb=[];function cb(){G||(E.noFSInit||db||(db=!0,eb(),E.stdin=E.stdin,E.stdout=E.stdout,E.stderr=E.stderr,E.stdin?fb("/dev","stdin",E.stdin):gb("/dev/tty","/dev/stdin"),E.stdout?fb("/dev","stdout",null,E.stdout):gb("/dev/tty","/dev/stdout"),E.stderr?fb("/dev","stderr",null,E.stderr):gb("/dev/tty1","/dev/stderr"),hb("/dev/stdin",0),hb("/dev/stdout",1),hb("/dev/stderr",1)),ib($a))}function jb(){var a=E.preRun.shift();Za.unshift(a)}
var kb=0,lb=null,mb=null;function nb(){Ka(!G,"addRunDependency cannot be used in a pthread worker");kb++;E.monitorRunDependencies&&E.monitorRunDependencies(kb)}function ob(){kb--;E.monitorRunDependencies&&E.monitorRunDependencies(kb);if(0==kb&&(null!==lb&&(clearInterval(lb),lb=null),mb)){var a=mb;mb=null;a()}}E.preloadedImages={};E.preloadedAudios={};
function H(a){if(E.onAbort)E.onAbort(a);G&&console.error("Pthread aborting at "+Error().stack);a+="";F(a);Ia=!0;Ja=1;a=new WebAssembly.RuntimeError("abort("+a+"). Build with -s ASSERTIONS=1 for more info.");na(a);throw a;}function pb(){var a=qb;return String.prototype.startsWith?a.startsWith("data:application/octet-stream;base64,"):0===a.indexOf("data:application/octet-stream;base64,")}var qb="BlinkIDWasmSDK.wasm";pb()||(qb=Aa(qb));
function rb(){var a=qb;try{if(a==qb&&Ga)return new Uint8Array(Ga);if(Ca)return Ca(a);throw"both async and sync fetching of the wasm failed";}catch(b){H(b)}}function sb(){return Ga||!wa&&!xa||"function"!==typeof fetch?Promise.resolve().then(function(){return rb()}):fetch(qb,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+qb+"'";return a.arrayBuffer()}).catch(function(){return rb()})}
var N,tb,vb={223986:function(a,b){a=K(a);b=K(b);throw Error(a+b);},224096:function(a,b,c,d){a=K(a);b=K(b);c=K(c);d=K(d);throw Error(a+b+c+d);},224312:function(a){a=K(a);throw Error("Failed to reconfigure RecognizerRunner due to following error: "+a);},224448:function(a,b){a=K(a);b=K(b);console.log(a+b)},224546:function(a){throw Error(K(a));},224589:function(){throw"Canceled!";},224607:function(a,b){setTimeout(function(){ub(a,b)},0)},224686:function(){throw Error("Unable to perform that operation while recognizer is in use!");
},224769:function(){throw Error("Unable to perform that operation while recognizer is in use!");},224852:function(){throw Error("Unable to perform that operation while recognizer is in use!");}};function ib(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b(E);else{var c=b.$e;"number"===typeof c?void 0===b.qc?M.get(c)():M.get(c)(b.qc):c(void 0===b.qc?null:b.qc)}}}
function wb(a,b){if(0>=a||a>g().length||a&1||0>b)return-28;if(0==b)return 0;2147483647<=b&&(b=Infinity);var c=Atomics.load(A(),xb>>2),d=0;if(c==a&&Atomics.compareExchange(A(),xb>>2,c,0)==c&&(--b,d=1,0>=b))return 1;a=Atomics.notify(A(),a>>2,b);if(0<=a)return a+d;throw"Atomics.notify returned an unexpected value "+a;}E._emscripten_futex_wake=wb;
function yb(a){if(G)throw"Internal Error! cleanupThread() can only ever be called from main application thread!";if(!a)throw"Internal Error! Null pthread_ptr in cleanupThread!";var b=O.Zb[a];b&&(A()[a+12>>2]=0,O.Lc(b.worker))}
var O={dc:[],cc:[],gd:[],cf:function(){},ce:function(){for(var a=L(228),b=0;57>b;++b)C()[a/4+b]=0;A()[a+12>>2]=a;b=a+152;A()[b>>2]=b;var c=L(512);for(b=0;128>b;++b)C()[c/4+b]=0;Atomics.store(C(),a+100>>2,c);Atomics.store(C(),a+40>>2,a);zb(a,!xa,1);Ab(a)},de:function(){O.receiveObjectTransfer=O.se;O.threadInit=O.Le;O.threadCancel=O.Ke;O.threadExit=O.Ed;O.setExitStatus=O.ye},Zb:{},Oc:[],ue:function(){for(;0<O.Oc.length;)O.Oc.pop()();G&&Bb()&&Cb()},Dd:function(a,b){Atomics.store(C(),a+56>>2,1);Atomics.store(C(),
a+60>>2,0);O.ue();Atomics.store(C(),a+4>>2,b);Atomics.store(C(),a+0>>2,1);wb(a+0,2147483647);zb(0,0,0)},ye:function(a){Ja=a},Ed:function(a){var b=Bb();b&&(O.Dd(b,a),G&&postMessage({cmd:"exit"}))},Ke:function(){O.Dd(Bb(),-1);postMessage({cmd:"cancelDone"})},Je:function(){for(var a in O.Zb){var b=O.Zb[a];b&&b.worker&&O.Lc(b.worker)}O.Zb={};for(a=0;a<O.dc.length;++a){var c=O.dc[a];c.terminate()}O.dc=[];for(a=0;a<O.cc.length;++a)c=O.cc[a],b=c.Sb,O.Wc(b),c.terminate();O.cc=[]},Wc:function(a){if(a){if(a.$b){var b=
A()[a.$b+100>>2];A()[a.$b+100>>2]=0;P(b);P(a.$b)}a.$b=0;a.Uc&&a.hc&&P(a.hc);a.hc=0;a.worker&&(a.worker.Sb=null)}},Lc:function(a){O.ve(function(){delete O.Zb[a.Sb.$b];O.dc.push(a);O.cc.splice(O.cc.indexOf(a),1);O.Wc(a.Sb);a.Sb=void 0})},ve:function(a){A()[Db>>2]=0;try{a()}finally{A()[Db>>2]=1}},se:function(){},Le:function(){for(var a in O.gd)O.gd[a]()},ad:function(a,b){a.onmessage=function(c){var d=c.data,e=d.cmd;a.Sb&&(O.Qd=a.Sb.$b);if(d.targetThread&&d.targetThread!=Bb()){var f=O.Zb[d.kf];f?f.worker.postMessage(c.data,
d.transferList):console.error('Internal error! Worker sent a message "'+e+'" to target pthread '+d.targetThread+", but that thread no longer exists!")}else if("processQueuedMainThreadWork"===e)Eb();else if("spawnThread"===e)Fb(c.data);else if("cleanupThread"===e)yb(d.thread);else if("killThread"===e){c=d.thread;if(G)throw"Internal Error! killThread() can only ever be called from main application thread!";if(!c)throw"Internal Error! Null pthread_ptr in killThread!";A()[c+12>>2]=0;c=O.Zb[c];c.worker.terminate();
O.Wc(c);O.cc.splice(O.cc.indexOf(c.worker),1);c.worker.Sb=void 0}else if("cancelThread"===e){c=d.thread;if(G)throw"Internal Error! cancelThread() can only ever be called from main application thread!";if(!c)throw"Internal Error! Null pthread_ptr in cancelThread!";O.Zb[c].worker.postMessage({cmd:"cancel"})}else if("loaded"===e)a.loaded=!0,b&&b(a),a.vc&&(a.vc(),delete a.vc);else if("print"===e)Da("Thread "+d.threadId+": "+d.text);else if("printErr"===e)F("Thread "+d.threadId+": "+d.text);else if("alert"===
e)alert("Thread "+d.threadId+": "+d.text);else if("exit"===e)a.Sb&&Atomics.load(C(),a.Sb.$b+64>>2)&&O.Lc(a);else if("exitProcess"===e)try{Gb(d.returnCode)}catch(h){if(h instanceof Hb)return;throw h;}else"cancelDone"===e?O.Lc(a):"objectTransfer"!==e&&("setimmediate"===c.data.target?a.postMessage(c.data):F("worker sent an unknown command "+e));O.Qd=void 0};a.onerror=function(c){F("pthread sent an error! "+c.filename+":"+c.lineno+": "+c.message)};a.postMessage({cmd:"load",urlOrBlob:E.mainScriptUrlOrBlob||
_scriptDir,wasmMemory:n,wasmModule:Ha})},Id:function(){var a=Aa("BlinkIDWasmSDK.worker.js");O.dc.push(new Worker(a))},Wd:function(){0==O.dc.length&&(O.Id(),O.ad(O.dc[0]));return O.dc.pop()},Ue:function(a){for(a=performance.now()+a;performance.now()<a;);}};E.establishStackSpace=function(a,b){Ib(a,b);Q(a)};E.invokeEntryPoint=function(a,b){return M.get(a)(b)};var Jb=0;function Kb(){return noExitRuntime||0<Jb}E.keepRuntimeAlive=Kb;var Lb;
Lb=G?function(){return performance.now()-E.__performance_now_clock_drift}:function(){return performance.now()};function Mb(a,b){if(0===a)a=Date.now();else if(1===a||4===a)a=Lb();else return-1;A()[b>>2]=a/1E3|0;A()[b+4>>2]=a%1E3*1E6|0;return 0}function Nb(a,b){O.Oc.push(function(){M.get(a)(b)})}
function Ob(a){this.Hb=a-16;this.De=function(b){A()[this.Hb+8>>2]=b};this.Ae=function(b){A()[this.Hb+0>>2]=b};this.Be=function(){A()[this.Hb+4>>2]=0};this.ze=function(){var b=0;g()[this.Hb+12>>0]=b};this.Ce=function(){var b=0;g()[this.Hb+13>>0]=b};this.ud=function(b,c){this.De(b);this.Ae(c);this.Be();this.ze();this.Ce()}}var Pb=0;
function Qb(){function a(h){return(h=h.toTimeString().match(/\(([A-Za-z ]+)\)$/))?h[1]:"GMT"}if(G)return R(2,1);if(!Qb.Nd){Qb.Nd=!0;var b=(new Date).getFullYear(),c=new Date(b,0,1),d=new Date(b,6,1);b=c.getTimezoneOffset();var e=d.getTimezoneOffset(),f=Math.max(b,e);A()[Rb()>>2]=60*f;A()[Sb()>>2]=Number(b!=e);c=a(c);d=a(d);c=Va(c);d=Va(d);e<b?(A()[Tb()>>2]=c,A()[Tb()+4>>2]=d):(A()[Tb()>>2]=d,A()[Tb()+4>>2]=c)}}
function Ub(a,b){for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a}function Vb(a){var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=Ub(a.split("/").filter(function(d){return!!d}),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a}
function Wb(a){var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,b.length-1));return a+b}function Xb(a){if("/"===a)return"/";a=Vb(a);a=a.replace(/\/$/,"");var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)}
function Yb(){if("object"===typeof crypto&&"function"===typeof crypto.getRandomValues){var a=new Uint8Array(1);return function(){crypto.getRandomValues(a);return a[0]}}return function(){H("randomDevice")}}
function Zb(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:"/";if("string"!==typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=Ub(a.split("/").filter(function(d){return!!d}),!b).join("/");return(b?"/":"")+a||"."}var $b=[];function ac(a,b){$b[a]={input:[],Nb:[],nc:b};bc(a,cc)}
var cc={open:function(a){var b=$b[a.node.tc];if(!b)throw new S(43);a.Kb=b;a.seekable=!1},close:function(a){a.Kb.nc.flush(a.Kb)},flush:function(a){a.Kb.nc.flush(a.Kb)},read:function(a,b,c,d){if(!a.Kb||!a.Kb.nc.td)throw new S(60);for(var e=0,f=0;f<d;f++){try{var h=a.Kb.nc.td(a.Kb)}catch(l){throw new S(29);}if(void 0===h&&0===e)throw new S(6);if(null===h||void 0===h)break;e++;b[c+f]=h}e&&(a.node.timestamp=Date.now());return e},write:function(a,b,c,d){if(!a.Kb||!a.Kb.nc.bd)throw new S(60);try{for(var e=
0;e<d;e++)a.Kb.nc.bd(a.Kb,b[c+e])}catch(f){throw new S(29);}d&&(a.node.timestamp=Date.now());return e}},ec={td:function(a){if(!a.input.length){var b=null;"undefined"!=typeof window&&"function"==typeof window.prompt?(b=window.prompt("Input: "),null!==b&&(b+="\n")):"function"==typeof readline&&(b=readline(),null!==b&&(b+="\n"));if(!b)return null;a.input=dc(b,!0)}return a.input.shift()},bd:function(a,b){null===b||10===b?(Da(La(a.Nb,0)),a.Nb=[]):0!=b&&a.Nb.push(b)},flush:function(a){a.Nb&&0<a.Nb.length&&
(Da(La(a.Nb,0)),a.Nb=[])}},fc={bd:function(a,b){null===b||10===b?(F(La(a.Nb,0)),a.Nb=[]):0!=b&&a.Nb.push(b)},flush:function(a){a.Nb&&0<a.Nb.length&&(F(La(a.Nb,0)),a.Nb=[])}},T={Yb:null,ac:function(){return T.createNode(null,"/",16895,0)},createNode:function(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new S(63);T.Yb||(T.Yb={dir:{node:{Xb:T.Eb.Xb,Qb:T.Eb.Qb,rc:T.Eb.rc,Hc:T.Eb.Hc,Cd:T.Eb.Cd,Sc:T.Eb.Sc,Mc:T.Eb.Mc,Bd:T.Eb.Bd,Nc:T.Eb.Nc},stream:{fc:T.Gb.fc}},file:{node:{Xb:T.Eb.Xb,Qb:T.Eb.Qb},
stream:{fc:T.Gb.fc,read:T.Gb.read,write:T.Gb.write,hd:T.Gb.hd,Ic:T.Gb.Ic,Jc:T.Gb.Jc}},link:{node:{Xb:T.Eb.Xb,Qb:T.Eb.Qb,uc:T.Eb.uc},stream:{}},kd:{node:{Xb:T.Eb.Xb,Qb:T.Eb.Qb},stream:gc}});c=hc(a,b,c,d);ic(c.mode)?(c.Eb=T.Yb.dir.node,c.Gb=T.Yb.dir.stream,c.Fb={}):32768===(c.mode&61440)?(c.Eb=T.Yb.file.node,c.Gb=T.Yb.file.stream,c.Jb=0,c.Fb=null):40960===(c.mode&61440)?(c.Eb=T.Yb.link.node,c.Gb=T.Yb.link.stream):8192===(c.mode&61440)&&(c.Eb=T.Yb.kd.node,c.Gb=T.Yb.kd.stream);c.timestamp=Date.now();
a&&(a.Fb[b]=c,a.timestamp=c.timestamp);return c},af:function(a){return a.Fb?a.Fb.subarray?a.Fb.subarray(0,a.Jb):new Uint8Array(a.Fb):new Uint8Array(0)},pd:function(a,b){var c=a.Fb?a.Fb.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)>>>0),0!=c&&(b=Math.max(b,256)),c=a.Fb,a.Fb=new Uint8Array(b),0<a.Jb&&a.Fb.set(c.subarray(0,a.Jb),0))},te:function(a,b){if(a.Jb!=b)if(0==b)a.Fb=null,a.Jb=0;else{var c=a.Fb;a.Fb=new Uint8Array(b);c&&a.Fb.set(c.subarray(0,Math.min(b,a.Jb)));a.Jb=b}},Eb:{Xb:function(a){var b=
{};b.Rd=8192===(a.mode&61440)?a.id:1;b.Yc=a.id;b.mode=a.mode;b.ne=1;b.uid=0;b.$d=0;b.tc=a.tc;b.size=ic(a.mode)?4096:32768===(a.mode&61440)?a.Jb:40960===(a.mode&61440)?a.link.length:0;b.Jd=new Date(a.timestamp);b.me=new Date(a.timestamp);b.Pd=new Date(a.timestamp);b.Kd=4096;b.Ld=Math.ceil(b.size/b.Kd);return b},Qb:function(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);void 0!==b.size&&T.te(a,b.size)},rc:function(){throw jc[44];},Hc:function(a,b,c,d){return T.createNode(a,
b,c,d)},Cd:function(a,b,c){if(ic(a.mode)){try{var d=kc(b,c)}catch(f){}if(d)for(var e in d.Fb)throw new S(55);}delete a.parent.Fb[a.name];a.parent.timestamp=Date.now();a.name=c;b.Fb[c]=a;b.timestamp=a.parent.timestamp;a.parent=b},Sc:function(a,b){delete a.Fb[b];a.timestamp=Date.now()},Mc:function(a,b){var c=kc(a,b),d;for(d in c.Fb)throw new S(55);delete a.Fb[b];a.timestamp=Date.now()},Bd:function(a){var b=[".",".."],c;for(c in a.Fb)a.Fb.hasOwnProperty(c)&&b.push(c);return b},Nc:function(a,b,c){a=T.createNode(a,
b,41471,0);a.link=c;return a},uc:function(a){if(40960!==(a.mode&61440))throw new S(28);return a.link}},Gb:{read:function(a,b,c,d,e){var f=a.node.Fb;if(e>=a.node.Jb)return 0;a=Math.min(a.node.Jb-e,d);if(8<a&&f.subarray)b.set(f.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=f[e+d];return a},write:function(a,b,c,d,e,f){b.buffer===g().buffer&&(f=!1);if(!d)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&(!a.Fb||a.Fb.subarray)){if(f)return a.Fb=b.subarray(c,c+d),a.Jb=d;if(0===a.Jb&&0===e)return a.Fb=
b.slice(c,c+d),a.Jb=d;if(e+d<=a.Jb)return a.Fb.set(b.subarray(c,c+d),e),d}T.pd(a,e+d);if(a.Fb.subarray&&b.subarray)a.Fb.set(b.subarray(c,c+d),e);else for(f=0;f<d;f++)a.Fb[e+f]=b[c+f];a.Jb=Math.max(a.Jb,e+d);return d},fc:function(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.Jb);if(0>b)throw new S(28);return b},hd:function(a,b,c){T.pd(a.node,b+c);a.node.Jb=Math.max(a.node.Jb,b+c)},Ic:function(a,b,c,d,e,f){if(0!==b)throw new S(28);if(32768!==(a.node.mode&61440))throw new S(43);
a=a.node.Fb;if(f&2||a.buffer!==t){if(0<d||d+c<a.length)a=a.subarray?a.subarray(d,d+c):Array.prototype.slice.call(a,d,d+c);d=!0;f=16384*Math.ceil(c/16384);for(b=L(f);c<f;)g()[b+c++]=0;c=b;if(!c)throw new S(48);g().set(a,c)}else d=!1,c=a.byteOffset;return{Hb:c,Tc:d}},Jc:function(a,b,c,d,e){if(32768!==(a.node.mode&61440))throw new S(43);if(e&2)return 0;T.Gb.write(a,b,0,d,c,!1);return 0}}},lc=null,mc={},nc=[],oc=1,pc=null,qc=!0,rc={},S=null,jc={};
function sc(a,b){a=Zb("/",a);b=b||{};if(!a)return{path:"",node:null};var c={rd:!0,dd:0},d;for(d in c)void 0===b[d]&&(b[d]=c[d]);if(8<b.dd)throw new S(32);a=Ub(a.split("/").filter(function(h){return!!h}),!1);var e=lc;c="/";for(d=0;d<a.length;d++){var f=d===a.length-1;if(f&&b.parent)break;e=kc(e,a[d]);c=Vb(c+"/"+a[d]);e.lc&&(!f||f&&b.rd)&&(e=e.lc.root);if(!f||b.Dc)for(f=0;40960===(e.mode&61440);)if(e=tc(c),c=Zb(Wb(c),e),e=sc(c,{dd:b.dd}).node,40<f++)throw new S(32);}return{path:c,node:e}}
function uc(a){for(var b;;){if(a===a.parent)return a=a.ac.wd,b?"/"!==a[a.length-1]?a+"/"+b:a+b:a;b=b?a.name+"/"+b:a.name;a=a.parent}}function vc(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%pc.length}function wc(a){var b=vc(a.parent.id,a.name);if(pc[b]===a)pc[b]=a.mc;else for(b=pc[b];b;){if(b.mc===a){b.mc=a.mc;break}b=b.mc}}
function kc(a,b){var c;if(c=(c=xc(a,"x"))?c:a.Eb.rc?0:2)throw new S(c,a);for(c=pc[vc(a.id,b)];c;c=c.mc){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.Eb.rc(a,b)}function hc(a,b,c,d){a=new yc(a,b,c,d);b=vc(a.parent.id,a.name);a.mc=pc[b];return pc[b]=a}function ic(a){return 16384===(a&61440)}var zc={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090};function Ac(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}
function xc(a,b){if(qc)return 0;if(-1===b.indexOf("r")||a.mode&292){if(-1!==b.indexOf("w")&&!(a.mode&146)||-1!==b.indexOf("x")&&!(a.mode&73))return 2}else return 2;return 0}function Bc(a,b){try{return kc(a,b),20}catch(c){}return xc(a,"wx")}function Cc(a,b,c){try{var d=kc(a,b)}catch(e){return e.Mb}if(a=xc(a,"wx"))return a;if(c){if(!ic(d.mode))return 54;if(d===d.parent||"/"===uc(d))return 10}else if(ic(d.mode))return 31;return 0}
function Dc(a){var b=4096;for(a=a||0;a<=b;a++)if(!nc[a])return a;throw new S(33);}function Ec(a,b){Fc||(Fc=function(){},Fc.prototype={object:{get:function(){return this.node},set:function(e){this.node=e}}});var c=new Fc,d;for(d in a)c[d]=a[d];a=c;b=Dc(b);a.Wb=b;return nc[b]=a}var gc={open:function(a){a.Gb=mc[a.node.tc].Gb;a.Gb.open&&a.Gb.open(a)},fc:function(){throw new S(70);}};function bc(a,b){mc[a]={Gb:b}}
function Gc(a,b){var c="/"===b,d=!b;if(c&&lc)throw new S(10);if(!c&&!d){var e=sc(b,{rd:!1});b=e.path;e=e.node;if(e.lc)throw new S(10);if(!ic(e.mode))throw new S(54);}b={type:a,gf:{},wd:b,le:[]};a=a.ac(b);a.ac=b;b.root=a;c?lc=a:e&&(e.lc=b,e.ac&&e.ac.le.push(b))}function Hc(a,b,c){var d=sc(a,{parent:!0}).node;a=Xb(a);if(!a||"."===a||".."===a)throw new S(28);var e=Bc(d,a);if(e)throw new S(e);if(!d.Eb.Hc)throw new S(63);return d.Eb.Hc(d,a,b,c)}function Ic(a){return Hc(a,16895,0)}
function Jc(a,b,c){"undefined"===typeof c&&(c=b,b=438);return Hc(a,b|8192,c)}function gb(a,b){if(!Zb(a))throw new S(44);var c=sc(b,{parent:!0}).node;if(!c)throw new S(44);b=Xb(b);var d=Bc(c,b);if(d)throw new S(d);if(!c.Eb.Nc)throw new S(63);c.Eb.Nc(c,b,a)}
function Kc(a){var b=sc(a,{parent:!0}).node,c=Xb(a),d=kc(b,c),e=Cc(b,c,!1);if(e)throw new S(e);if(!b.Eb.Sc)throw new S(63);if(d.lc)throw new S(10);try{rc.willDeletePath&&rc.willDeletePath(a)}catch(f){F("FS.trackingDelegate['willDeletePath']('"+a+"') threw an exception: "+f.message)}b.Eb.Sc(b,c);wc(d);try{if(rc.onDeletePath)rc.onDeletePath(a)}catch(f){F("FS.trackingDelegate['onDeletePath']('"+a+"') threw an exception: "+f.message)}}
function tc(a){a=sc(a).node;if(!a)throw new S(44);if(!a.Eb.uc)throw new S(28);return Zb(uc(a.parent),a.Eb.uc(a))}function Lc(a,b){a="string"===typeof a?sc(a,{Dc:!0}).node:a;if(!a.Eb.Qb)throw new S(63);a.Eb.Qb(a,{mode:b&4095|a.mode&-4096,timestamp:Date.now()})}
function hb(a,b,c,d){if(""===a)throw new S(44);if("string"===typeof b){var e=zc[b];if("undefined"===typeof e)throw Error("Unknown file open mode: "+b);b=e}c=b&64?("undefined"===typeof c?438:c)&4095|32768:0;if("object"===typeof a)var f=a;else{a=Vb(a);try{f=sc(a,{Dc:!(b&131072)}).node}catch(h){}}e=!1;if(b&64)if(f){if(b&128)throw new S(20);}else f=Hc(a,c,0),e=!0;if(!f)throw new S(44);8192===(f.mode&61440)&&(b&=-513);if(b&65536&&!ic(f.mode))throw new S(54);if(!e&&(c=f?40960===(f.mode&61440)?32:ic(f.mode)&&
("r"!==Ac(b)||b&512)?31:xc(f,Ac(b)):44))throw new S(c);if(b&512){c=f;c="string"===typeof c?sc(c,{Dc:!0}).node:c;if(!c.Eb.Qb)throw new S(63);if(ic(c.mode))throw new S(31);if(32768!==(c.mode&61440))throw new S(28);if(e=xc(c,"w"))throw new S(e);c.Eb.Qb(c,{size:0,timestamp:Date.now()})}b&=-131713;d=Ec({node:f,path:uc(f),flags:b,seekable:!0,position:0,Gb:f.Gb,Re:[],error:!1},d);d.Gb.open&&d.Gb.open(d);!E.logReadFiles||b&1||(Mc||(Mc={}),a in Mc||(Mc[a]=1,F("FS.trackingDelegate error on read file: "+a)));
try{rc.onOpenFile&&(f=0,1!==(b&2097155)&&(f|=1),0!==(b&2097155)&&(f|=2),rc.onOpenFile(a,f))}catch(h){F("FS.trackingDelegate['onOpenFile']('"+a+"', flags) threw an exception: "+h.message)}return d}function Nc(a){if(null===a.Wb)throw new S(8);a.Xc&&(a.Xc=null);try{a.Gb.close&&a.Gb.close(a)}catch(b){throw b;}finally{nc[a.Wb]=null}a.Wb=null}function Oc(a,b,c){if(null===a.Wb)throw new S(8);if(!a.seekable||!a.Gb.fc)throw new S(70);if(0!=c&&1!=c&&2!=c)throw new S(28);a.position=a.Gb.fc(a,b,c);a.Re=[]}
function Pc(a,b,c,d,e,f){if(0>d||0>e)throw new S(28);if(null===a.Wb)throw new S(8);if(0===(a.flags&2097155))throw new S(8);if(ic(a.node.mode))throw new S(31);if(!a.Gb.write)throw new S(28);a.seekable&&a.flags&1024&&Oc(a,0,2);var h="undefined"!==typeof e;if(!h)e=a.position;else if(!a.seekable)throw new S(70);b=a.Gb.write(a,b,c,d,e,f);h||(a.position+=b);try{if(a.path&&rc.onWriteToFile)rc.onWriteToFile(a.path)}catch(l){F("FS.trackingDelegate['onWriteToFile']('"+a.path+"') threw an exception: "+l.message)}return b}
function eb(){S||(S=function(a,b){this.node=b;this.xe=function(c){this.Mb=c};this.xe(a);this.message="FS error"},S.prototype=Error(),S.prototype.constructor=S,[44].forEach(function(a){jc[a]=new S(a);jc[a].stack="<generic error, no stack>"}))}var db;function Qc(a,b){var c=0;a&&(c|=365);b&&(c|=146);return c}function Rc(a,b){a="string"===typeof a?a:uc(a);for(b=b.split("/").reverse();b.length;){var c=b.pop();if(c){var d=Vb(a+"/"+c);try{Ic(d)}catch(e){}a=d}}return d}
function Sc(a,b,c,d){a=Vb(("string"===typeof a?a:uc(a))+"/"+b);c=Qc(c,d);return Hc(a,(void 0!==c?c:438)&4095|32768,0)}function Tc(a,b,c,d,e,f){a=b?Vb(("string"===typeof a?a:uc(a))+"/"+b):a;d=Qc(d,e);e=Hc(a,(void 0!==d?d:438)&4095|32768,0);if(c){if("string"===typeof c){a=Array(c.length);b=0;for(var h=c.length;b<h;++b)a[b]=c.charCodeAt(b);c=a}Lc(e,d|146);a=hb(e,577);Pc(a,c,0,c.length,0,f);Nc(a);Lc(e,d)}return e}
function fb(a,b,c,d){a=Vb(("string"===typeof a?a:uc(a))+"/"+b);b=Qc(!!c,!!d);fb.vd||(fb.vd=64);var e=fb.vd++<<8|0;bc(e,{open:function(f){f.seekable=!1},close:function(){d&&d.buffer&&d.buffer.length&&d(10)},read:function(f,h,l,m){for(var q=0,p=0;p<m;p++){try{var r=c()}catch(u){throw new S(29);}if(void 0===r&&0===q)throw new S(6);if(null===r||void 0===r)break;q++;h[l+p]=r}q&&(f.node.timestamp=Date.now());return q},write:function(f,h,l,m){for(var q=0;q<m;q++)try{d(h[l+q])}catch(p){throw new S(29);}m&&
(f.node.timestamp=Date.now());return q}});return Jc(a,b,e)}function Uc(a){if(!(a.fe||a.ge||a.link||a.Fb)){if("undefined"!==typeof XMLHttpRequest)throw Error("Lazy loading should have been performed (contents set) in createLazyFile, but it was not. Lazy loading only works in web workers. Use --embed-file or --preload-file in emcc on the main thread.");if(Ba)try{a.Fb=dc(Ba(a.url),!0),a.Jb=a.Fb.length}catch(b){throw new S(29);}else throw Error("Cannot load without read() or XMLHttpRequest.");}}
function Vc(a,b,c,d,e){function f(){this.$c=!1;this.Cc=[]}f.prototype.get=function(p){if(!(p>this.length-1||0>p)){var r=p%this.ld;return this.Ec(p/this.ld|0)[r]}};f.prototype.we=function(p){this.Ec=p};f.prototype.jd=function(){var p=new XMLHttpRequest;p.open("HEAD",c,!1);p.send(null);if(!(200<=p.status&&300>p.status||304===p.status))throw Error("Couldn't load "+c+". Status: "+p.status);var r=Number(p.getResponseHeader("Content-length")),u,k=(u=p.getResponseHeader("Accept-Ranges"))&&"bytes"===u;p=
(u=p.getResponseHeader("Content-Encoding"))&&"gzip"===u;var v=1048576;k||(v=r);var z=this;z.we(function(B){var I=B*v,J=(B+1)*v-1;J=Math.min(J,r-1);if("undefined"===typeof z.Cc[B]){var ra=z.Cc;if(I>J)throw Error("invalid range ("+I+", "+J+") or no bytes requested!");if(J>r-1)throw Error("only "+r+" bytes available! programmer error!");var w=new XMLHttpRequest;w.open("GET",c,!1);r!==v&&w.setRequestHeader("Range","bytes="+I+"-"+J);"undefined"!=typeof Uint8Array&&(w.responseType="arraybuffer");w.overrideMimeType&&
w.overrideMimeType("text/plain; charset=x-user-defined");w.send(null);if(!(200<=w.status&&300>w.status||304===w.status))throw Error("Couldn't load "+c+". Status: "+w.status);I=void 0!==w.response?new Uint8Array(w.response||[]):dc(w.responseText||"",!0);ra[B]=I}if("undefined"===typeof z.Cc[B])throw Error("doXHR failed!");return z.Cc[B]});if(p||!r)v=r=1,v=r=this.Ec(0).length,Da("LazyFiles on gzip forces download of the whole file when length is accessed");this.Gd=r;this.Fd=v;this.$c=!0};if("undefined"!==
typeof XMLHttpRequest){if(!xa)throw"Cannot do synchronous binary XHRs outside webworkers in modern browsers. Use --embed-file or --preload-file in emcc";var h=new f;Object.defineProperties(h,{length:{get:function(){this.$c||this.jd();return this.Gd}},ld:{get:function(){this.$c||this.jd();return this.Fd}}});var l=void 0}else l=c,h=void 0;var m=Sc(a,b,d,e);h?m.Fb=h:l&&(m.Fb=null,m.url=l);Object.defineProperties(m,{Jb:{get:function(){return this.Fb.length}}});var q={};Object.keys(m.Gb).forEach(function(p){var r=
m.Gb[p];q[p]=function(){Uc(m);return r.apply(null,arguments)}});q.read=function(p,r,u,k,v){Uc(m);p=p.node.Fb;if(v>=p.length)return 0;k=Math.min(p.length-v,k);if(p.slice)for(var z=0;z<k;z++)r[u+z]=p[v+z];else for(z=0;z<k;z++)r[u+z]=p.get(v+z);return k};m.Gb=q;return m}
function Wc(a,b,c,d,e,f,h,l,m,q){function p(k){function v(B){q&&q();l||Tc(a,b,B,d,e,m);f&&f();ob(u)}var z=!1;E.preloadPlugins.forEach(function(B){!z&&B.canHandle(r)&&(B.handle(k,r,v,function(){h&&h();ob(u)}),z=!0)});z||v(k)}Xc.ud();var r=b?Zb(Vb(a+"/"+b)):a,u="cp "+r;nb(u);"string"==typeof c?Xc.Te(c,function(k){p(k)},h):p(c)}var U={},Fc,Mc,Yc={};
function Zc(a,b){try{var c=sc(a,{Dc:!0}).node;if(!c)throw new S(44);if(!c.Eb.Xb)throw new S(63);var d=c.Eb.Xb(c)}catch(e){if(e&&e.node&&Vb(a)!==Vb(uc(e.node)))return-54;throw e;}A()[b>>2]=d.Rd;A()[b+4>>2]=0;A()[b+8>>2]=d.Yc;A()[b+12>>2]=d.mode;A()[b+16>>2]=d.ne;A()[b+20>>2]=d.uid;A()[b+24>>2]=d.$d;A()[b+28>>2]=d.tc;A()[b+32>>2]=0;tb=[d.size>>>0,(N=d.size,1<=+Math.abs(N)?0<N?(Math.min(+Math.floor(N/4294967296),4294967295)|0)>>>0:~~+Math.ceil((N-+(~~N>>>0))/4294967296)>>>0:0)];A()[b+40>>2]=tb[0];A()[b+
44>>2]=tb[1];A()[b+48>>2]=4096;A()[b+52>>2]=d.Ld;A()[b+56>>2]=d.Jd.getTime()/1E3|0;A()[b+60>>2]=0;A()[b+64>>2]=d.me.getTime()/1E3|0;A()[b+68>>2]=0;A()[b+72>>2]=d.Pd.getTime()/1E3|0;A()[b+76>>2]=0;tb=[d.Yc>>>0,(N=d.Yc,1<=+Math.abs(N)?0<N?(Math.min(+Math.floor(N/4294967296),4294967295)|0)>>>0:~~+Math.ceil((N-+(~~N>>>0))/4294967296)>>>0:0)];A()[b+80>>2]=tb[0];A()[b+84>>2]=tb[1];return 0}var $c=void 0;function ad(){$c+=4;return A()[$c-4>>2]}function bd(a){a=nc[a];if(!a)throw new S(8);return a}
function cd(a,b,c){if(G)return R(3,1,a,b,c);$c=c;try{var d=bd(a);switch(b){case 0:var e=ad();return 0>e?-28:hb(d.path,d.flags,0,e).Wb;case 1:case 2:return 0;case 3:return d.flags;case 4:return e=ad(),d.flags|=e,0;case 12:return e=ad(),ea()[e+0>>1]=2,0;case 13:case 14:return 0;case 16:case 8:return-28;case 9:return-1;default:return-28}}catch(f){return"undefined"!==typeof U&&f instanceof S||H(f),-f.Mb}}
function dd(a,b){if(G)return R(4,1,a,b);try{var c=bd(a);return Zc(c.path,b)}catch(d){return"undefined"!==typeof U&&d instanceof S||H(d),-d.Mb}}
function ed(a,b,c){if(G)return R(5,1,a,b,c);$c=c;try{var d=bd(a);switch(b){case 21509:case 21505:return d.Kb?0:-59;case 21510:case 21511:case 21512:case 21506:case 21507:case 21508:return d.Kb?0:-59;case 21519:if(!d.Kb)return-59;var e=ad();return A()[e>>2]=0;case 21520:return d.Kb?-28:-59;case 21531:a=e=ad();if(!d.Gb.ee)throw new S(59);return d.Gb.ee(d,b,a);case 21523:return d.Kb?0:-59;case 21524:return d.Kb?0:-59;default:H("bad ioctl syscall "+b)}}catch(f){return"undefined"!==typeof U&&f instanceof
S||H(f),-f.Mb}}
function fd(a,b,c,d,e,f){if(G)return R(6,1,a,b,c,d,e,f);try{a:{f<<=12;var h=!1;if(0!==(d&16)&&0!==a%16384)var l=-28;else{if(0!==(d&32)){var m=gd(16384,b);if(!m){l=-48;break a}hd(m,0,b);h=!0}else{var q=nc[e];if(!q){l=-8;break a}var p=f;if(0!==(c&2)&&0===(d&2)&&2!==(q.flags&2097155))throw new S(2);if(1===(q.flags&2097155))throw new S(2);if(!q.Gb.Ic)throw new S(43);var r=q.Gb.Ic(q,a,b,p,c,d);m=r.Hb;h=r.Tc}Yc[m]={ke:m,ie:b,Tc:h,Wb:e,pe:c,flags:d,offset:f};l=m}}return l}catch(u){return"undefined"!==typeof U&&
u instanceof S||H(u),-u.Mb}}function id(a,b){if(G)return R(7,1,a,b);try{if(-1===(a|0)||0===b)var c=-28;else{var d=Yc[a];if(d&&b===d.ie){var e=nc[d.Wb];if(e&&d.pe&2){var f=d.flags,h=d.offset,l=x().slice(a,a+b);e&&e.Gb.Jc&&e.Gb.Jc(e,l,h,b,f)}Yc[a]=null;d.Tc&&P(d.ke)}c=0}return c}catch(m){return"undefined"!==typeof U&&m instanceof S||H(m),-m.Mb}}
function jd(a,b,c){if(G)return R(8,1,a,b,c);$c=c;try{var d=K(a),e=c?ad():0;return hb(d,b,e).Wb}catch(f){return"undefined"!==typeof U&&f instanceof S||H(f),-f.Mb}}
function kd(a){if(G)return R(9,1,a);try{a=K(a);var b=sc(a,{parent:!0}).node,c=Xb(a),d=kc(b,c),e=Cc(b,c,!0);if(e)throw new S(e);if(!b.Eb.Mc)throw new S(63);if(d.lc)throw new S(10);try{rc.willDeletePath&&rc.willDeletePath(a)}catch(f){F("FS.trackingDelegate['willDeletePath']('"+a+"') threw an exception: "+f.message)}b.Eb.Mc(b,c);wc(d);try{if(rc.onDeletePath)rc.onDeletePath(a)}catch(f){F("FS.trackingDelegate['onDeletePath']('"+a+"') threw an exception: "+f.message)}return 0}catch(f){return"undefined"!==
typeof U&&f instanceof S||H(f),-f.Mb}}function ld(a,b){if(G)return R(10,1,a,b);try{return a=K(a),Zc(a,b)}catch(c){return"undefined"!==typeof U&&c instanceof S||H(c),-c.Mb}}function md(a){if(G)return R(11,1,a);try{return a=K(a),Kc(a),0}catch(b){return"undefined"!==typeof U&&b instanceof S||H(b),-b.Mb}}var nd={};function od(a){for(;a.length;){var b=a.pop();a.pop()(b)}}function pd(a){return this.fromWireType(C()[a>>2])}var qd={},rd={},sd={};
function td(a){if(void 0===a)return"_unknown";a=a.replace(/[^a-zA-Z0-9_]/g,"$");var b=a.charCodeAt(0);return 48<=b&&57>=b?"_"+a:a}function ud(a,b){a=td(a);return(new Function("body","return function "+a+'() {\n    "use strict";    return body.apply(this, arguments);\n};\n'))(b)}
function vd(a){var b=Error,c=ud(a,function(d){this.name=a;this.message=d;d=Error(d).stack;void 0!==d&&(this.stack=this.toString()+"\n"+d.replace(/^Error(:[^\n]*)?\n/,""))});c.prototype=Object.create(b.prototype);c.prototype.constructor=c;c.prototype.toString=function(){return void 0===this.message?this.name:this.name+": "+this.message};return c}var wd=void 0;function xd(a){throw new wd(a);}
function yd(a,b,c){function d(l){l=c(l);l.length!==a.length&&xd("Mismatched type converter count");for(var m=0;m<a.length;++m)zd(a[m],l[m])}a.forEach(function(l){sd[l]=b});var e=Array(b.length),f=[],h=0;b.forEach(function(l,m){rd.hasOwnProperty(l)?e[m]=rd[l]:(f.push(l),qd.hasOwnProperty(l)||(qd[l]=[]),qd[l].push(function(){e[m]=rd[l];++h;h===f.length&&d(e)}))});0===f.length&&d(e)}
function Ad(a){switch(a){case 1:return 0;case 2:return 1;case 4:return 2;case 8:return 3;default:throw new TypeError("Unknown type size: "+a);}}var Bd=void 0;function V(a){for(var b="";x()[a];)b+=Bd[x()[a++]];return b}var Cd=void 0;function X(a){throw new Cd(a);}
function zd(a,b,c){c=c||{};if(!("argPackAdvance"in b))throw new TypeError("registerType registeredInstance requires argPackAdvance");var d=b.name;a||X('type "'+d+'" must have a positive integer typeid pointer');if(rd.hasOwnProperty(a)){if(c.ae)return;X("Cannot register type '"+d+"' twice")}rd[a]=b;delete sd[a];qd.hasOwnProperty(a)&&(b=qd[a],delete qd[a],b.forEach(function(e){e()}))}function Dd(a){X(a.Db.Lb.Ib.name+" instance already deleted")}var Ed=!1;function Fd(){}
function Gd(a){--a.count.value;0===a.count.value&&(a.Rb?a.Tb.bc(a.Rb):a.Lb.Ib.bc(a.Hb))}function Hd(a){if("undefined"===typeof FinalizationGroup)return Hd=function(b){return b},a;Ed=new FinalizationGroup(function(b){for(var c=b.next();!c.done;c=b.next())c=c.value,c.Hb?Gd(c):console.warn("object already deleted: "+c.Hb)});Hd=function(b){Ed.register(b,b.Db,b.Db);return b};Fd=function(b){Ed.unregister(b.Db)};return Hd(a)}var Id=void 0,Jd=[];
function Kd(){for(;Jd.length;){var a=Jd.pop();a.Db.jc=!1;a["delete"]()}}function Ld(){}var Md={};function Nd(a,b,c){if(void 0===a[b].Ob){var d=a[b];a[b]=function(){a[b].Ob.hasOwnProperty(arguments.length)||X("Function '"+c+"' called with an invalid number of arguments ("+arguments.length+") - expects one of ("+a[b].Ob+")!");return a[b].Ob[arguments.length].apply(this,arguments)};a[b].Ob=[];a[b].Ob[d.Ac]=d}}
function Od(a,b,c){E.hasOwnProperty(a)?((void 0===c||void 0!==E[a].Ob&&void 0!==E[a].Ob[c])&&X("Cannot register public name '"+a+"' twice"),Nd(E,a,a),E.hasOwnProperty(c)&&X("Cannot register multiple overloads of a function with the same number of arguments ("+c+")!"),E[a].Ob[c]=b):(E[a]=b,void 0!==c&&(E[a].ff=c))}function Pd(a,b,c,d,e,f,h,l){this.name=a;this.constructor=b;this.kc=c;this.bc=d;this.Ub=e;this.Vd=f;this.xc=h;this.Sd=l;this.qe=[]}
function Qd(a,b,c){for(;b!==c;)b.xc||X("Expected null or instance of "+c.name+", got an instance of "+b.name),a=b.xc(a),b=b.Ub;return a}function Rd(a,b){if(null===b)return this.Zc&&X("null is not a valid "+this.name),0;b.Db||X('Cannot pass "'+Sd(b)+'" as a '+this.name);b.Db.Hb||X("Cannot pass deleted object as a pointer of type "+this.name);return Qd(b.Db.Hb,b.Db.Lb.Ib,this.Ib)}
function Td(a,b){if(null===b){this.Zc&&X("null is not a valid "+this.name);if(this.Gc){var c=this.cd();null!==a&&a.push(this.bc,c);return c}return 0}b.Db||X('Cannot pass "'+Sd(b)+'" as a '+this.name);b.Db.Hb||X("Cannot pass deleted object as a pointer of type "+this.name);!this.Fc&&b.Db.Lb.Fc&&X("Cannot convert argument of type "+(b.Db.Tb?b.Db.Tb.name:b.Db.Lb.name)+" to parameter type "+this.name);c=Qd(b.Db.Hb,b.Db.Lb.Ib,this.Ib);if(this.Gc)switch(void 0===b.Db.Rb&&X("Passing raw pointer to smart pointer is illegal"),
this.He){case 0:b.Db.Tb===this?c=b.Db.Rb:X("Cannot convert argument of type "+(b.Db.Tb?b.Db.Tb.name:b.Db.Lb.name)+" to parameter type "+this.name);break;case 1:c=b.Db.Rb;break;case 2:if(b.Db.Tb===this)c=b.Db.Rb;else{var d=b.clone();c=this.re(c,Y(function(){d["delete"]()}));null!==a&&a.push(this.bc,c)}break;default:X("Unsupporting sharing policy")}return c}
function Ud(a,b){if(null===b)return this.Zc&&X("null is not a valid "+this.name),0;b.Db||X('Cannot pass "'+Sd(b)+'" as a '+this.name);b.Db.Hb||X("Cannot pass deleted object as a pointer of type "+this.name);b.Db.Lb.Fc&&X("Cannot convert argument of type "+b.Db.Lb.name+" to parameter type "+this.name);return Qd(b.Db.Hb,b.Db.Lb.Ib,this.Ib)}function Vd(a,b,c){if(b===c)return a;if(void 0===c.Ub)return null;a=Vd(a,b,c.Ub);return null===a?null:c.Sd(a)}var Wd={};
function Xd(a,b){for(void 0===b&&X("ptr should not be undefined");a.Ub;)b=a.xc(b),a=a.Ub;return Wd[b]}function Yd(a,b){b.Lb&&b.Hb||xd("makeClassHandle requires ptr and ptrType");!!b.Tb!==!!b.Rb&&xd("Both smartPtrType and smartPtr must be specified");b.count={value:1};return Hd(Object.create(a,{Db:{value:b}}))}
function Zd(a,b,c,d){this.name=a;this.Ib=b;this.Zc=c;this.Fc=d;this.Gc=!1;this.bc=this.re=this.cd=this.Ad=this.He=this.oe=void 0;void 0!==b.Ub?this.toWireType=Td:(this.toWireType=d?Rd:Ud,this.Vb=null)}function $d(a,b,c){E.hasOwnProperty(a)||xd("Replacing nonexistant public symbol");void 0!==E[a].Ob&&void 0!==c?E[a].Ob[c]=b:(E[a]=b,E[a].Ac=c)}
function ae(a,b){var c=[];return function(){c.length=arguments.length;for(var d=0;d<arguments.length;d++)c[d]=arguments[d];-1!=a.indexOf("j")?(d=E["dynCall_"+a],d=c&&c.length?d.apply(null,[b].concat(c)):d.call(null,b)):d=M.get(b).apply(null,c);return d}}function be(a,b){a=V(a);var c=-1!=a.indexOf("j")?ae(a,b):M.get(b);"function"!==typeof c&&X("unknown function pointer with signature "+a+": "+b);return c}var ce=void 0;function de(a){a=ee(a);var b=V(a);P(a);return b}
function fe(a,b){function c(f){e[f]||rd[f]||(sd[f]?sd[f].forEach(c):(d.push(f),e[f]=!0))}var d=[],e={};b.forEach(c);throw new ce(a+": "+d.map(de).join([", "]));}function ge(a,b){for(var c=[],d=0;d<a;d++)c.push(A()[(b>>2)+d]);return c}
function he(a){var b=Function;if(!(b instanceof Function))throw new TypeError("new_ called with constructor type "+typeof b+" which is not a function");var c=ud(b.name||"unknownFunctionName",function(){});c.prototype=b.prototype;c=new c;a=b.apply(c,a);return a instanceof Object?a:c}
function ie(a,b,c,d,e){var f=b.length;2>f&&X("argTypes array size mismatch! Must at least get return value and 'this' types!");var h=null!==b[1]&&null!==c,l=!1;for(c=1;c<b.length;++c)if(null!==b[c]&&void 0===b[c].Vb){l=!0;break}var m="void"!==b[0].name,q="",p="";for(c=0;c<f-2;++c)q+=(0!==c?", ":"")+"arg"+c,p+=(0!==c?", ":"")+"arg"+c+"Wired";a="return function "+td(a)+"("+q+") {\nif (arguments.length !== "+(f-2)+") {\nthrowBindingError('function "+a+" called with ' + arguments.length + ' arguments, expected "+
(f-2)+" args!');\n}\n";l&&(a+="var destructors = [];\n");var r=l?"destructors":"null";q="throwBindingError invoker fn runDestructors retType classParam".split(" ");d=[X,d,e,od,b[0],b[1]];h&&(a+="var thisWired = classParam.toWireType("+r+", this);\n");for(c=0;c<f-2;++c)a+="var arg"+c+"Wired = argType"+c+".toWireType("+r+", arg"+c+"); // "+b[c+2].name+"\n",q.push("argType"+c),d.push(b[c+2]);h&&(p="thisWired"+(0<p.length?", ":"")+p);a+=(m?"var rv = ":"")+"invoker(fn"+(0<p.length?", ":"")+p+");\n";if(l)a+=
"runDestructors(destructors);\n";else for(c=h?1:2;c<b.length;++c)f=1===c?"thisWired":"arg"+(c-2)+"Wired",null!==b[c].Vb&&(a+=f+"_dtor("+f+"); // "+b[c].name+"\n",q.push(f+"_dtor"),d.push(b[c].Vb));m&&(a+="var ret = retType.fromWireType(rv);\nreturn ret;\n");q.push(a+"}\n");return he(q).apply(null,d)}var je=[],Z=[{},{value:void 0},{value:null},{value:!0},{value:!1}];function ke(a){4<a&&0===--Z[a].ed&&(Z[a]=void 0,je.push(a))}
function Y(a){switch(a){case void 0:return 1;case null:return 2;case !0:return 3;case !1:return 4;default:var b=je.length?je.pop():Z.length;Z[b]={ed:1,value:a};return b}}function Sd(a){if(null===a)return"null";var b=typeof a;return"object"===b||"array"===b||"function"===b?a.toString():""+a}
function le(a,b){switch(b){case 2:return function(c){var d=this.fromWireType;n.buffer!=t&&aa(n.buffer);return d.call(this,Xa[c>>2])};case 3:return function(c){return this.fromWireType(ka()[c>>3])};default:throw new TypeError("Unknown float type: "+a);}}
function me(a,b,c){switch(b){case 0:return c?function(d){return g()[d]}:function(d){return x()[d]};case 1:return c?function(d){return ea()[d>>1]}:function(d){return y()[d>>1]};case 2:return c?function(d){return A()[d>>2]}:function(d){return C()[d>>2]};default:throw new TypeError("Unknown integer type: "+a);}}function ne(a){a||X("Cannot use deleted val. handle = "+a);return Z[a].value}function oe(a,b){var c=rd[a];void 0===c&&X(b+" has unknown type "+de(a));return c}
function pe(a,b){for(var c=Array(a),d=0;d<a;++d)c[d]=oe(A()[(b>>2)+d],"parameter "+d);return c}var qe={};function re(a){var b=qe[a];return void 0===b?V(a):b}var se=[];function te(){return"object"===typeof globalThis?globalThis:Function("return this")()}function ue(a){var b=se.length;se.push(a);return b}var ve={},we=[];
function xe(){xa||(Ea||(Ea={}),Ea["Blocking on the main thread is very dangerous, see https://emscripten.org/docs/porting/pthreads.html#blocking-on-the-main-browser-thread"]||(Ea["Blocking on the main thread is very dangerous, see https://emscripten.org/docs/porting/pthreads.html#blocking-on-the-main-browser-thread"]=1,F("Blocking on the main thread is very dangerous, see https://emscripten.org/docs/porting/pthreads.html#blocking-on-the-main-browser-thread")))}
function ye(a,b,c){if(0>=a||a>g().length||a&1)return-28;if(wa){if(Atomics.load(A(),a>>2)!=b)return-6;var d=performance.now();c=d+c;for(Atomics.exchange(A(),xb>>2,a);;){d=performance.now();if(d>c)return Atomics.exchange(A(),xb>>2,0),-73;d=Atomics.exchange(A(),xb>>2,0);if(0==d)break;Eb();if(Atomics.load(A(),a>>2)!=b)return-6;Atomics.exchange(A(),xb>>2,a)}return 0}a=Atomics.wait(A(),a>>2,b,c);if("timed-out"===a)return-73;if("not-equal"===a)return-6;if("ok"===a)return 0;throw"Atomics.wait returned an unexpected value "+
a;}function R(a,b){for(var c=arguments.length-2,d=ze(),e=Ae(8*c),f=e>>3,h=0;h<c;h++){var l=arguments[2+h];ka()[f+h]=l}c=Be(a,c,e,b);Q(d);return c}var Ce=[],De=[0,"undefined"!==typeof document?document:0,"undefined"!==typeof window?window:0];function Ee(a){a=2<a?K(a):a;return De[a]||("undefined"!==typeof document?document.querySelector(a):void 0)}
function Fe(a,b,c){var d=Ee(a);if(!d)return-4;d.Bc&&(A()[d.Bc>>2]=b,A()[d.Bc+4>>2]=c);if(d.xd||!d.We)d.xd&&(d=d.xd),a=!1,d.zc&&d.zc.yc&&(a=d.zc.yc.getParameter(2978),a=0===a[0]&&0===a[1]&&a[2]===d.width&&a[3]===d.height),d.width=b,d.height=c,a&&d.zc.yc.viewport(0,0,b,c);else{if(d.Bc){d=A()[d.Bc+8>>2];a=a?K(a):"";var e=ze(),f=Ae(12),h=0;if(a){h=Oa(a)+1;var l=L(h);Na(a,l,h);h=l}A()[f>>2]=h;A()[f+4>>2]=b;A()[f+8>>2]=c;Ge(0,d,657457152,0,h,f);Q(e);return 1}return-4}return 0}
function He(a,b,c){return G?R(12,1,a,b,c):Fe(a,b,c)}var Ie=[];function Je(a,b){C()[a>>2]=b;C()[a+4>>2]=b/4294967296|0}function Ke(a,b){try{var c=indexedDB.open("emscripten_filesystem",1)}catch(d){b(d);return}c.onupgradeneeded=function(d){d=d.target.result;d.objectStoreNames.contains("FILES")&&d.deleteObjectStore("FILES");d.createObjectStore("FILES")};c.onsuccess=function(d){a(d.target.result)};c.onerror=function(d){b(d)}}var Le;
function Me(a,b,c,d,e){function f(D){var da=0,W=0;D&&(W=w.response?w.response.byteLength:0,da=L(W),x().set(new Uint8Array(w.response),da));C()[a+12>>2]=da;Je(a+16,W)}var h=C()[a+8>>2];if(h){var l=K(h),m=a+112,q=K(m);q||(q="GET");C();var p=C()[m+52>>2],r=C()[m+56>>2],u=!!C()[m+60>>2];C();var k=C()[m+68>>2],v=C()[m+72>>2],z=C()[m+76>>2],B=C()[m+80>>2];h=C()[m+84>>2];m=C()[m+88>>2];var I=!!(p&1),J=!!(p&2);p=!!(p&64);k=k?K(k):void 0;v=v?K(v):void 0;var ra=B?K(B):void 0,w=new XMLHttpRequest;w.withCredentials=
u;w.open(q,l,!p,k,v);p||(w.timeout=r);w.mf=l;w.responseType="arraybuffer";B&&w.overrideMimeType(ra);if(z)for(;;){q=C()[z>>2];if(!q)break;l=C()[z+4>>2];if(!l)break;z+=8;q=K(q);l=K(l);w.setRequestHeader(q,l)}Ie.push(w);z=Ie.length;C()[a+0>>2]=z;h=h&&m?x().slice(h,h+m):null;w.onload=function(D){f(I&&!J);var da=w.response?w.response.byteLength:0;Je(a+24,0);da&&Je(a+32,da);y()[a+40>>1]=w.readyState;y()[a+42>>1]=w.status;w.statusText&&Na(w.statusText,a+44,64);200<=w.status&&300>w.status?b&&b(a,w,D):c&&
c(a,w,D)};w.onerror=function(D){f(I);var da=w.status;Je(a+24,0);Je(a+32,w.response?w.response.byteLength:0);y()[a+40>>1]=w.readyState;y()[a+42>>1]=da;c&&c(a,w,D)};w.ontimeout=function(D){c&&c(a,w,D)};w.onprogress=function(D){var da=I&&J&&w.response?w.response.byteLength:0,W=0;I&&J&&(W=L(da),x().set(new Uint8Array(w.response),W));C()[a+12>>2]=W;Je(a+16,da);Je(a+24,D.loaded-da);Je(a+32,D.total);y()[a+40>>1]=w.readyState;3<=w.readyState&&0===w.status&&0<D.loaded&&(w.status=200);y()[a+42>>1]=w.status;
w.statusText&&Na(w.statusText,a+44,64);d&&d(a,w,D);W&&P(W)};w.onreadystatechange=function(D){y()[a+40>>1]=w.readyState;2<=w.readyState&&(y()[a+42>>1]=w.status);e&&e(a,w,D)};try{w.send(h)}catch(D){c&&c(a,w,D)}}else c(a,0,"no url specified!")}
function Ne(a){try{a()}catch(b){if(b instanceof Hb)return;if("unwind"!==b)throw b&&"object"===typeof b&&b.stack&&F("exception thrown: "+[b,b.stack]),b;}if(G&&!Kb())try{if(G)throw a=Ja,G?O.Ed(a):Gb(a),ya&&process.Ye(a),"unwind";Gb(Ja)}catch(b){if(!(b instanceof Hb))throw b;}}
function Oe(a,b,c,d){var e=Le;if(e){var f=a+112;(f=C()[f+64>>2])||(f=C()[a+8>>2]);var h=K(f);try{var l=e.transaction(["FILES"],"readwrite").objectStore("FILES").put(b,h);l.onsuccess=function(){y()[a+40>>1]=4;y()[a+42>>1]=200;Na("OK",a+44,64);c(a,0,h)};l.onerror=function(m){y()[a+40>>1]=4;y()[a+42>>1]=413;Na("Payload Too Large",a+44,64);d(a,0,m)}}catch(m){d(a,0,m)}}else d(a,0,"IndexedDB not available!")}
function Pe(a,b,c){var d=Le;if(d){var e=a+112;(e=C()[e+64>>2])||(e=C()[a+8>>2]);e=K(e);try{var f=d.transaction(["FILES"],"readonly").objectStore("FILES").get(e);f.onsuccess=function(h){if(h.target.result){h=h.target.result;var l=h.byteLength||h.length,m=L(l);x().set(new Uint8Array(h),m);C()[a+12>>2]=m;Je(a+16,l);Je(a+24,0);Je(a+32,l);y()[a+40>>1]=4;y()[a+42>>1]=200;Na("OK",a+44,64);b(a,0,h)}else y()[a+40>>1]=4,y()[a+42>>1]=404,Na("Not Found",a+44,64),c(a,0,"no data")};f.onerror=function(h){y()[a+
40>>1]=4;y()[a+42>>1]=404;Na("Not Found",a+44,64);c(a,0,h)}}catch(h){c(a,0,h)}}else c(a,0,"IndexedDB not available!")}
function Qe(a,b,c){var d=Le;if(d){var e=a+112;(e=C()[e+64>>2])||(e=C()[a+8>>2]);e=K(e);try{var f=d.transaction(["FILES"],"readwrite").objectStore("FILES").delete(e);f.onsuccess=function(h){h=h.target.result;C()[a+12>>2]=0;Je(a+16,0);Je(a+24,0);Je(a+32,0);y()[a+40>>1]=4;y()[a+42>>1]=200;Na("OK",a+44,64);b(a,0,h)};f.onerror=function(h){y()[a+40>>1]=4;y()[a+42>>1]=404;Na("Not Found",a+44,64);c(a,0,h)}}catch(h){c(a,0,h)}}else c(a,0,"IndexedDB not available!")}
function Re(a){var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=function(c,d){b.vertexAttribDivisorANGLE(c,d)},a.drawArraysInstanced=function(c,d,e,f){b.drawArraysInstancedANGLE(c,d,e,f)},a.drawElementsInstanced=function(c,d,e,f,h){b.drawElementsInstancedANGLE(c,d,e,f,h)})}
function Se(a){var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=function(){return b.createVertexArrayOES()},a.deleteVertexArray=function(c){b.deleteVertexArrayOES(c)},a.bindVertexArray=function(c){b.bindVertexArrayOES(c)},a.isVertexArray=function(c){return b.isVertexArrayOES(c)})}function Te(a){var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=function(c,d){b.drawBuffersWEBGL(c,d)})}
function Ue(a,b){a.sd||(a.sd=a.getContext,a.getContext=function(d,e){e=a.sd(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null});var c=a.getContext("webgl",b);return c?Ve(c,b):0}function Ve(a,b){var c=L(8);A()[c+4>>2]=Bb();var d={bf:c,attributes:b,version:b.je,yc:a};a.canvas&&(a.canvas.zc=d);("undefined"===typeof b.od||b.od)&&We(d);return c}
function We(a){a||(a=Xe);if(!a.be){a.be=!0;var b=a.yc;Re(b);Se(b);Te(b);b.Xe=b.getExtension("EXT_disjoint_timer_query");b.ef=b.getExtension("WEBGL_multi_draw");(b.getSupportedExtensions()||[]).forEach(function(c){0>c.indexOf("lose_context")&&0>c.indexOf("debug")&&b.getExtension(c)})}}var Xe,Ye=["default","low-power","high-performance"],Ze={};
function $e(){if(!af){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"===typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:ua||"./this.program"},b;for(b in Ze)a[b]=Ze[b];var c=[];for(b in a)c.push(b+"="+a[b]);af=c}return af}var af;
function bf(a,b){if(G)return R(13,1,a,b);try{var c=0;$e().forEach(function(d,e){var f=b+c;e=A()[a+4*e>>2]=f;for(f=0;f<d.length;++f)g()[e++>>0]=d.charCodeAt(f);g()[e>>0]=0;c+=d.length+1});return 0}catch(d){return"undefined"!==typeof U&&d instanceof S||H(d),d.Mb}}function cf(a,b){if(G)return R(14,1,a,b);try{var c=$e();A()[a>>2]=c.length;var d=0;c.forEach(function(e){d+=e.length+1});A()[b>>2]=d;return 0}catch(e){return"undefined"!==typeof U&&e instanceof S||H(e),e.Mb}}
function df(a){if(G)return R(15,1,a);try{var b=bd(a);Nc(b);return 0}catch(c){return"undefined"!==typeof U&&c instanceof S||H(c),c.Mb}}function ef(a,b){if(G)return R(16,1,a,b);try{var c=bd(a),d=c.Kb?2:ic(c.mode)?3:40960===(c.mode&61440)?7:4;g()[b>>0]=d;return 0}catch(e){return"undefined"!==typeof U&&e instanceof S||H(e),e.Mb}}
function ff(a,b,c,d){if(G)return R(17,1,a,b,c,d);try{a:{for(var e=bd(a),f=a=0;f<c;f++){var h=A()[b+8*f>>2],l=A()[b+(8*f+4)>>2],m=e,q=g(),p=h,r=l,u=void 0;if(0>r||0>u)throw new S(28);if(null===m.Wb)throw new S(8);if(1===(m.flags&2097155))throw new S(8);if(ic(m.node.mode))throw new S(31);if(!m.Gb.read)throw new S(28);var k="undefined"!==typeof u;if(!k)u=m.position;else if(!m.seekable)throw new S(70);var v=m.Gb.read(m,q,p,r,u);k||(m.position+=v);var z=v;if(0>z){var B=-1;break a}a+=z;if(z<l)break}B=a}A()[d>>
2]=B;return 0}catch(I){return"undefined"!==typeof U&&I instanceof S||H(I),I.Mb}}
function gf(a,b,c,d,e){if(G)return R(18,1,a,b,c,d,e);try{var f=bd(a);a=4294967296*c+(b>>>0);if(-9007199254740992>=a||9007199254740992<=a)return-61;Oc(f,a,d);tb=[f.position>>>0,(N=f.position,1<=+Math.abs(N)?0<N?(Math.min(+Math.floor(N/4294967296),4294967295)|0)>>>0:~~+Math.ceil((N-+(~~N>>>0))/4294967296)>>>0:0)];A()[e>>2]=tb[0];A()[e+4>>2]=tb[1];f.Xc&&0===a&&0===d&&(f.Xc=null);return 0}catch(h){return"undefined"!==typeof U&&h instanceof S||H(h),h.Mb}}
function hf(a,b,c,d){if(G)return R(19,1,a,b,c,d);try{a:{for(var e=bd(a),f=a=0;f<c;f++){var h=A()[b+8*f>>2],l=A()[b+(8*f+4)>>2],m=Pc(e,g(),h,l,void 0);if(0>m){var q=-1;break a}a+=m}q=a}A()[d>>2]=q;return 0}catch(p){return"undefined"!==typeof U&&p instanceof S||H(p),p.Mb}}function jf(a,b){jf.zd||(jf.zd=Yb());for(var c=0;c<b;c++)g()[a+c>>0]=jf.zd();return 0}
function Fb(a){if(G)throw"Internal Error! spawnThread() can only ever be called from main application thread!";var b=O.Wd();if(!b)return 6;if(void 0!==b.Sb)throw"Internal error!";if(!a.Kc)throw"Internal error, no pthread ptr!";O.cc.push(b);for(var c=L(512),d=0;128>d;++d)A()[c+4*d>>2]=0;var e=a.hc+a.oc;d=O.Zb[a.Kc]={worker:b,hc:a.hc,oc:a.oc,Uc:a.Uc,$b:a.Kc};var f=d.$b>>2;Atomics.store(C(),f+16,a.nd);Atomics.store(C(),f+25,c);Atomics.store(C(),f+10,d.$b);Atomics.store(C(),f+20,a.oc);Atomics.store(C(),
f+19,e);Atomics.store(C(),f+26,a.oc);Atomics.store(C(),f+28,e);Atomics.store(C(),f+29,a.nd);c=kf()+40;Atomics.store(C(),f+43,c);b.Sb=d;var h={cmd:"run",start_routine:a.Ie,arg:a.qc,threadInfoStruct:a.Kc,stackBase:a.hc,stackSize:a.oc};b.vc=function(){h.time=performance.now();b.postMessage(h,a.Qe)};b.loaded&&(b.vc(),delete b.vc);return 0}
function lf(a,b){if(!a)return F("pthread_join attempted on a null thread pointer!"),71;if(G&&Bb()==a)return F("PThread "+a+" is attempting to join to itself!"),16;if(!G&&mf()==a)return F("Main thread "+a+" is attempting to join to itself!"),16;if(A()[a+12>>2]!==a)return F("pthread_join attempted on thread "+a+", which does not point to a valid thread, or does not exist anymore!"),71;if(Atomics.load(C(),a+64>>2))return F("Attempted to join thread "+a+", which was already detached!"),28;for(xe();;){var c=
Atomics.load(C(),a+0>>2);if(1==c)return c=Atomics.load(C(),a+4>>2),b&&(A()[b>>2]=c),Atomics.store(C(),a+64>>2,1),G?postMessage({cmd:"cleanupThread",thread:a}):yb(a),0;if(G){var d=Bb();if(d&&!Atomics.load(C(),d+56>>2)&&2==Atomics.load(C(),d+0>>2))throw"Canceled!";}G||Eb();ye(a+0,c,G?100:1)}}function nf(a){return 0===a%4&&(0!==a%100||0===a%400)}function of(a,b){for(var c=0,d=0;d<=b;c+=a[d++]);return c}var pf=[31,29,31,30,31,30,31,31,30,31,30,31],qf=[31,28,31,30,31,30,31,31,30,31,30,31];
function rf(a,b){for(a=new Date(a.getTime());0<b;){var c=a.getMonth(),d=(nf(a.getFullYear())?pf:qf)[c];if(b>d-a.getDate())b-=d-a.getDate()+1,a.setDate(1),11>c?a.setMonth(c+1):(a.setMonth(0),a.setFullYear(a.getFullYear()+1));else{a.setDate(a.getDate()+b);break}}return a}
function sf(a,b,c,d){function e(k,v,z){for(k="number"===typeof k?k.toString():k||"";k.length<v;)k=z[0]+k;return k}function f(k,v){return e(k,v,"0")}function h(k,v){function z(I){return 0>I?-1:0<I?1:0}var B;0===(B=z(k.getFullYear()-v.getFullYear()))&&0===(B=z(k.getMonth()-v.getMonth()))&&(B=z(k.getDate()-v.getDate()));return B}function l(k){switch(k.getDay()){case 0:return new Date(k.getFullYear()-1,11,29);case 1:return k;case 2:return new Date(k.getFullYear(),0,3);case 3:return new Date(k.getFullYear(),
0,2);case 4:return new Date(k.getFullYear(),0,1);case 5:return new Date(k.getFullYear()-1,11,31);case 6:return new Date(k.getFullYear()-1,11,30)}}function m(k){k=rf(new Date(k.Pb+1900,0,1),k.Rc);var v=new Date(k.getFullYear()+1,0,4),z=l(new Date(k.getFullYear(),0,4));v=l(v);return 0>=h(z,k)?0>=h(v,k)?k.getFullYear()+1:k.getFullYear():k.getFullYear()-1}var q=A()[d+40>>2];d={Oe:A()[d>>2],Ne:A()[d+4>>2],Pc:A()[d+8>>2],wc:A()[d+12>>2],pc:A()[d+16>>2],Pb:A()[d+20>>2],Qc:A()[d+24>>2],Rc:A()[d+28>>2],lf:A()[d+
32>>2],Me:A()[d+36>>2],Pe:q?K(q):""};c=K(c);q={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S","%x":"%m/%d/%y","%X":"%H:%M:%S","%Ec":"%c","%EC":"%C","%Ex":"%m/%d/%y","%EX":"%H:%M:%S","%Ey":"%y","%EY":"%Y","%Od":"%d","%Oe":"%e","%OH":"%H","%OI":"%I","%Om":"%m","%OM":"%M","%OS":"%S","%Ou":"%u","%OU":"%U","%OV":"%V","%Ow":"%w","%OW":"%W","%Oy":"%y"};for(var p in q)c=c.replace(new RegExp(p,"g"),q[p]);var r="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),
u="January February March April May June July August September October November December".split(" ");q={"%a":function(k){return r[k.Qc].substring(0,3)},"%A":function(k){return r[k.Qc]},"%b":function(k){return u[k.pc].substring(0,3)},"%B":function(k){return u[k.pc]},"%C":function(k){return f((k.Pb+1900)/100|0,2)},"%d":function(k){return f(k.wc,2)},"%e":function(k){return e(k.wc,2," ")},"%g":function(k){return m(k).toString().substring(2)},"%G":function(k){return m(k)},"%H":function(k){return f(k.Pc,
2)},"%I":function(k){k=k.Pc;0==k?k=12:12<k&&(k-=12);return f(k,2)},"%j":function(k){return f(k.wc+of(nf(k.Pb+1900)?pf:qf,k.pc-1),3)},"%m":function(k){return f(k.pc+1,2)},"%M":function(k){return f(k.Ne,2)},"%n":function(){return"\n"},"%p":function(k){return 0<=k.Pc&&12>k.Pc?"AM":"PM"},"%S":function(k){return f(k.Oe,2)},"%t":function(){return"\t"},"%u":function(k){return k.Qc||7},"%U":function(k){var v=new Date(k.Pb+1900,0,1),z=0===v.getDay()?v:rf(v,7-v.getDay());k=new Date(k.Pb+1900,k.pc,k.wc);return 0>
h(z,k)?f(Math.ceil((31-z.getDate()+(of(nf(k.getFullYear())?pf:qf,k.getMonth()-1)-31)+k.getDate())/7),2):0===h(z,v)?"01":"00"},"%V":function(k){var v=new Date(k.Pb+1901,0,4),z=l(new Date(k.Pb+1900,0,4));v=l(v);var B=rf(new Date(k.Pb+1900,0,1),k.Rc);return 0>h(B,z)?"53":0>=h(v,B)?"01":f(Math.ceil((z.getFullYear()<k.Pb+1900?k.Rc+32-z.getDate():k.Rc+1-z.getDate())/7),2)},"%w":function(k){return k.Qc},"%W":function(k){var v=new Date(k.Pb,0,1),z=1===v.getDay()?v:rf(v,0===v.getDay()?1:7-v.getDay()+1);k=
new Date(k.Pb+1900,k.pc,k.wc);return 0>h(z,k)?f(Math.ceil((31-z.getDate()+(of(nf(k.getFullYear())?pf:qf,k.getMonth()-1)-31)+k.getDate())/7),2):0===h(z,v)?"01":"00"},"%y":function(k){return(k.Pb+1900).toString().substring(2)},"%Y":function(k){return k.Pb+1900},"%z":function(k){k=k.Me;var v=0<=k;k=Math.abs(k)/60;return(v?"+":"-")+String("0000"+(k/60*100+k%60)).slice(-4)},"%Z":function(k){return k.Pe},"%%":function(){return"%"}};for(p in q)0<=c.indexOf(p)&&(c=c.replace(new RegExp(p,"g"),q[p](d)));p=
dc(c,!1);if(p.length>b)return 0;Wa(p,a);return p.length-1}function yc(a,b,c,d){a||(a=this);this.parent=a;this.ac=a.ac;this.lc=null;this.id=oc++;this.name=b;this.mode=c;this.Eb={};this.Gb={};this.tc=d}
Object.defineProperties(yc.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}},ge:{get:function(){return ic(this.mode)}},fe:{get:function(){return 8192===(this.mode&61440)}}});eb();pc=Array(4096);Gc(T,"/");Ic("/tmp");Ic("/home");Ic("/home/web_user");
(function(){Ic("/dev");bc(259,{read:function(){return 0},write:function(b,c,d,e){return e}});Jc("/dev/null",259);ac(1280,ec);ac(1536,fc);Jc("/dev/tty",1280);Jc("/dev/tty1",1536);var a=Yb();fb("/dev","random",a);fb("/dev","urandom",a);Ic("/dev/shm");Ic("/dev/shm/tmp")})();
(function(){Ic("/proc");var a=Ic("/proc/self");Ic("/proc/self/fd");Gc({ac:function(){var b=hc(a,"fd",16895,73);b.Eb={rc:function(c,d){var e=nc[+d];if(!e)throw new S(8);c={parent:null,ac:{wd:"fake"},Eb:{uc:function(){return e.path}}};return c.parent=c}};return b}},"/proc/self/fd")})();var Xc;E.FS_createPath=Rc;E.FS_createDataFile=Tc;E.FS_createPreloadedFile=Wc;E.FS_createLazyFile=Vc;E.FS_createDevice=fb;E.FS_unlink=Kc;wd=E.InternalError=vd("InternalError");
for(var tf=Array(256),uf=0;256>uf;++uf)tf[uf]=String.fromCharCode(uf);Bd=tf;Cd=E.BindingError=vd("BindingError");Ld.prototype.isAliasOf=function(a){if(!(this instanceof Ld&&a instanceof Ld))return!1;var b=this.Db.Lb.Ib,c=this.Db.Hb,d=a.Db.Lb.Ib;for(a=a.Db.Hb;b.Ub;)c=b.xc(c),b=b.Ub;for(;d.Ub;)a=d.xc(a),d=d.Ub;return b===d&&c===a};
Ld.prototype.clone=function(){this.Db.Hb||Dd(this);if(this.Db.sc)return this.Db.count.value+=1,this;var a=Hd,b=Object,c=b.create,d=Object.getPrototypeOf(this),e=this.Db;a=a(c.call(b,d,{Db:{value:{count:e.count,jc:e.jc,sc:e.sc,Hb:e.Hb,Lb:e.Lb,Rb:e.Rb,Tb:e.Tb}}}));a.Db.count.value+=1;a.Db.jc=!1;return a};Ld.prototype["delete"]=function(){this.Db.Hb||Dd(this);this.Db.jc&&!this.Db.sc&&X("Object already scheduled for deletion");Fd(this);Gd(this.Db);this.Db.sc||(this.Db.Rb=void 0,this.Db.Hb=void 0)};
Ld.prototype.isDeleted=function(){return!this.Db.Hb};Ld.prototype.deleteLater=function(){this.Db.Hb||Dd(this);this.Db.jc&&!this.Db.sc&&X("Object already scheduled for deletion");Jd.push(this);1===Jd.length&&Id&&Id(Kd);this.Db.jc=!0;return this};Zd.prototype.Xd=function(a){this.Ad&&(a=this.Ad(a));return a};Zd.prototype.md=function(a){this.bc&&this.bc(a)};Zd.prototype.argPackAdvance=8;Zd.prototype.readValueFromPointer=pd;Zd.prototype.deleteObject=function(a){if(null!==a)a["delete"]()};
Zd.prototype.fromWireType=function(a){function b(){return this.Gc?Yd(this.Ib.kc,{Lb:this.oe,Hb:c,Tb:this,Rb:a}):Yd(this.Ib.kc,{Lb:this,Hb:a})}var c=this.Xd(a);if(!c)return this.md(a),null;var d=Xd(this.Ib,c);if(void 0!==d){if(0===d.Db.count.value)return d.Db.Hb=c,d.Db.Rb=a,d.clone();d=d.clone();this.md(a);return d}d=this.Ib.Vd(c);d=Md[d];if(!d)return b.call(this);d=this.Fc?d.Od:d.pointerType;var e=Vd(c,this.Ib,d.Ib);return null===e?b.call(this):this.Gc?Yd(d.Ib.kc,{Lb:d,Hb:e,Tb:this,Rb:a}):Yd(d.Ib.kc,
{Lb:d,Hb:e})};E.getInheritedInstanceCount=function(){return Object.keys(Wd).length};E.getLiveInheritedInstances=function(){var a=[],b;for(b in Wd)Wd.hasOwnProperty(b)&&a.push(Wd[b]);return a};E.flushPendingDeletes=Kd;E.setDelayFunction=function(a){Id=a;Jd.length&&Id&&Id(Kd)};ce=E.UnboundTypeError=vd("UnboundTypeError");E.count_emval_handles=function(){for(var a=0,b=5;b<Z.length;++b)void 0!==Z[b]&&++a;return a};E.get_first_emval=function(){for(var a=5;a<Z.length;++a)if(void 0!==Z[a])return Z[a];return null};
G||(Ke(function(a){Le=a;ob("library_fetch_init")},function(){Le=!1;ob("library_fetch_init")}),"undefined"!==typeof ENVIRONMENT_IS_FETCH_WORKER&&ENVIRONMENT_IS_FETCH_WORKER||nb("library_fetch_init"));var vf=[null,function(a,b){if(G)return R(1,1,a,b)},Qb,cd,dd,ed,fd,id,jd,kd,ld,md,He,bf,cf,df,ef,ff,gf,hf];function dc(a,b){var c=Array(Oa(a)+1);a=Ma(a,c,0,c.length);b&&(c.length=a);return c}
var Jf={r:function(a,b,c,d){H("Assertion failed: "+K(a)+", at: "+[b?K(b):"unknown filename",c,d?K(d):"unknown function"])},wa:function(a,b){return Mb(a,b)},H:function(a){return L(a+16)+16},Ja:function(a,b){return Nb(a,b)},G:function(a,b,c){(new Ob(a)).ud(b,c);Pb++;throw a;},va:function(a,b){Qb();a=new Date(1E3*A()[a>>2]);A()[b>>2]=a.getSeconds();A()[b+4>>2]=a.getMinutes();A()[b+8>>2]=a.getHours();A()[b+12>>2]=a.getDate();A()[b+16>>2]=a.getMonth();A()[b+20>>2]=a.getFullYear()-1900;A()[b+24>>2]=a.getDay();
var c=new Date(a.getFullYear(),0,1),d=(a.getTime()-c.getTime())/864E5|0;A()[b+28>>2]=d;A()[b+36>>2]=-(60*a.getTimezoneOffset());d=(new Date(a.getFullYear(),6,1)).getTimezoneOffset();c=c.getTimezoneOffset();a=(d!=c&&a.getTimezoneOffset()==Math.min(c,d))|0;A()[b+32>>2]=a;a=A()[Tb()+(a?4:0)>>2];A()[b+40>>2]=a;return b},V:cd,ya:dd,Ca:ed,za:fd,Aa:function(){return 0},Ba:id,E:jd,Da:kd,xa:ld,W:md,g:function(a){var b=nd[a];delete nd[a];var c=b.cd,d=b.bc,e=b.qd,f=e.map(function(h){return h.Zd}).concat(e.map(function(h){return h.Fe}));
yd([a],f,function(h){var l={};e.forEach(function(m,q){var p=h[q],r=m.Ec,u=m.Yd,k=h[q+e.length],v=m.Ee,z=m.Ge;l[m.Ud]={read:function(B){return p.fromWireType(r(u,B))},write:function(B,I){var J=[];v(z,B,k.toWireType(J,I));od(J)}}});return[{name:b.name,fromWireType:function(m){var q={},p;for(p in l)q[p]=l[p].read(m);d(m);return q},toWireType:function(m,q){for(var p in l)if(!(p in q))throw new TypeError('Missing field:  "'+p+'"');var r=c();for(p in l)l[p].write(r,q[p]);null!==m&&m.push(d,r);return r},
argPackAdvance:8,readValueFromPointer:pd,Vb:d}]})},Ha:function(a,b,c,d,e){var f=Ad(c);b=V(b);zd(a,{name:b,fromWireType:function(h){return!!h},toWireType:function(h,l){return l?d:e},argPackAdvance:8,readValueFromPointer:function(h){if(1===c)var l=g();else if(2===c)l=ea();else if(4===c)l=A();else throw new TypeError("Unknown boolean type size: "+b);return this.fromWireType(l[h>>f])},Vb:null})},x:function(a,b,c,d,e,f,h,l,m,q,p,r,u){p=V(p);f=be(e,f);l&&(l=be(h,l));q&&(q=be(m,q));u=be(r,u);var k=td(p);
Od(k,function(){fe("Cannot construct "+p+" due to unbound types",[d])});yd([a,b,c],d?[d]:[],function(v){v=v[0];if(d){var z=v.Ib;var B=z.kc}else B=Ld.prototype;v=ud(k,function(){if(Object.getPrototypeOf(this)!==I)throw new Cd("Use 'new' to construct "+p);if(void 0===J.ec)throw new Cd(p+" has no accessible constructor");var w=J.ec[arguments.length];if(void 0===w)throw new Cd("Tried to invoke ctor of "+p+" with invalid number of parameters ("+arguments.length+") - expected ("+Object.keys(J.ec).toString()+
") parameters instead!");return w.apply(this,arguments)});var I=Object.create(B,{constructor:{value:v}});v.prototype=I;var J=new Pd(p,v,I,u,z,f,l,q);z=new Zd(p,J,!0,!1);B=new Zd(p+"*",J,!1,!1);var ra=new Zd(p+" const*",J,!1,!0);Md[a]={pointerType:B,Od:ra};$d(k,v);return[z,B,ra]})},A:function(a,b,c,d,e,f){Ka(0<b);var h=ge(b,c);e=be(d,e);var l=[f],m=[];yd([],[a],function(q){q=q[0];var p="constructor "+q.name;void 0===q.Ib.ec&&(q.Ib.ec=[]);if(void 0!==q.Ib.ec[b-1])throw new Cd("Cannot register multiple constructors with identical number of parameters ("+
(b-1)+") for class '"+q.name+"'! Overload resolution is currently only performed using the parameter count, not actual type info!");q.Ib.ec[b-1]=function(){fe("Cannot construct "+q.name+" due to unbound types",h)};yd([],h,function(r){q.Ib.ec[b-1]=function(){arguments.length!==b-1&&X(p+" called with "+arguments.length+" arguments, expected "+(b-1));m.length=0;l.length=b;for(var u=1;u<b;++u)l[u]=r[u].toWireType(m,arguments[u-1]);u=e.apply(null,l);od(m);return r[0].fromWireType(u)};return[]});return[]})},
j:function(a,b,c,d,e,f,h,l){var m=ge(c,d);b=V(b);f=be(e,f);yd([],[a],function(q){function p(){fe("Cannot call "+r+" due to unbound types",m)}q=q[0];var r=q.name+"."+b;l&&q.Ib.qe.push(b);var u=q.Ib.kc,k=u[b];void 0===k||void 0===k.Ob&&k.className!==q.name&&k.Ac===c-2?(p.Ac=c-2,p.className=q.name,u[b]=p):(Nd(u,b,r),u[b].Ob[c-2]=p);yd([],m,function(v){v=ie(r,v,q,f,h);void 0===u[b].Ob?(v.Ac=c-2,u[b]=v):u[b].Ob[c-2]=v;return[]});return[]})},Ga:function(a,b){b=V(b);zd(a,{name:b,fromWireType:function(c){var d=
Z[c].value;ke(c);return d},toWireType:function(c,d){return Y(d)},argPackAdvance:8,readValueFromPointer:pd,Vb:null})},X:function(a,b,c){c=Ad(c);b=V(b);zd(a,{name:b,fromWireType:function(d){return d},toWireType:function(d,e){if("number"!==typeof e&&"boolean"!==typeof e)throw new TypeError('Cannot convert "'+Sd(e)+'" to '+this.name);return e},argPackAdvance:8,readValueFromPointer:le(b,c),Vb:null})},K:function(a,b,c,d,e,f){var h=ge(b,c);a=V(a);e=be(d,e);Od(a,function(){fe("Cannot call "+a+" due to unbound types",
h)},b-1);yd([],h,function(l){$d(a,ie(a,[l[0],null].concat(l.slice(1)),null,e,f),b-1);return[]})},n:function(a,b,c,d,e){function f(q){return q}b=V(b);-1===e&&(e=4294967295);var h=Ad(c);if(0===d){var l=32-8*c;f=function(q){return q<<l>>>l}}var m=-1!=b.indexOf("unsigned");zd(a,{name:b,fromWireType:f,toWireType:function(q,p){if("number"!==typeof p&&"boolean"!==typeof p)throw new TypeError('Cannot convert "'+Sd(p)+'" to '+this.name);if(p<d||p>e)throw new TypeError('Passing a number "'+Sd(p)+'" from JS side to C/C++ side to an argument of type "'+
b+'", which is outside the valid range ['+d+", "+e+"]!");return m?p>>>0:p|0},argPackAdvance:8,readValueFromPointer:me(b,h,0!==d),Vb:null})},l:function(a,b,c){function d(f){f>>=2;var h=C();return new e(t,h[f+1],h[f])}var e=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array][b];c=V(c);zd(a,{name:c,fromWireType:d,argPackAdvance:8,readValueFromPointer:d},{ae:!0})},Y:function(a,b){b=V(b);var c="std::string"===b;zd(a,{name:b,fromWireType:function(d){var e=C()[d>>
2];if(c)for(var f=d+4,h=0;h<=e;++h){var l=d+4+h;if(h==e||0==x()[l]){f=K(f,l-f);if(void 0===m)var m=f;else m+=String.fromCharCode(0),m+=f;f=l+1}}else{m=Array(e);for(h=0;h<e;++h)m[h]=String.fromCharCode(x()[d+4+h]);m=m.join("")}P(d);return m},toWireType:function(d,e){e instanceof ArrayBuffer&&(e=new Uint8Array(e));var f="string"===typeof e;f||e instanceof Uint8Array||e instanceof Uint8ClampedArray||e instanceof Int8Array||X("Cannot pass non-string to std::string");var h=(c&&f?function(){return Oa(e)}:
function(){return e.length})(),l=L(4+h+1);C()[l>>2]=h;if(c&&f)Na(e,l+4,h+1);else if(f)for(f=0;f<h;++f){var m=e.charCodeAt(f);255<m&&(P(l),X("String has UTF-16 code units that do not fit in 8 bits"));x()[l+4+f]=m}else for(f=0;f<h;++f)x()[l+4+f]=e[f];null!==d&&d.push(P,l);return l},argPackAdvance:8,readValueFromPointer:pd,Vb:function(d){P(d)}})},F:function(a,b,c){c=V(c);if(2===b){var d=Pa;var e=Qa;var f=Ra;var h=function(){return y()};var l=1}else 4===b&&(d=Sa,e=Ta,f=Ua,h=function(){return C()},l=2);
zd(a,{name:c,fromWireType:function(m){for(var q=C()[m>>2],p=h(),r,u=m+4,k=0;k<=q;++k){var v=m+4+k*b;if(k==q||0==p[v>>l])u=d(u,v-u),void 0===r?r=u:(r+=String.fromCharCode(0),r+=u),u=v+b}P(m);return r},toWireType:function(m,q){"string"!==typeof q&&X("Cannot pass non-string to C++ string type "+c);var p=f(q),r=L(4+p+b);C()[r>>2]=p>>l;e(q,r+4,p+b);null!==m&&m.push(P,r);return r},argPackAdvance:8,readValueFromPointer:pd,Vb:function(m){P(m)}})},h:function(a,b,c,d,e,f){nd[a]={name:V(b),cd:be(c,d),bc:be(e,
f),qd:[]}},d:function(a,b,c,d,e,f,h,l,m,q){nd[a].qd.push({Ud:V(b),Zd:c,Ec:be(d,e),Yd:f,Fe:h,Ee:be(l,m),Ge:q})},Ia:function(a,b){b=V(b);zd(a,{he:!0,name:b,argPackAdvance:0,fromWireType:function(){},toWireType:function(){}})},Ea:function(a){delete Ie[a-1]},oa:function(a,b){if(a==b)postMessage({cmd:"processQueuedMainThreadWork"});else if(G)postMessage({targetThread:a,cmd:"processThreadQueue"});else{a=(a=O.Zb[a])&&a.worker;if(!a)return;a.postMessage({cmd:"processThreadQueue"})}return 1},t:function(a,
b,c){a=ne(a);b=oe(b,"emval::as");var d=[],e=Y(d);A()[c>>2]=e;return b.toWireType(d,a)},aa:function(a,b,c,d){a=ne(a);c=pe(b,c);for(var e=Array(b),f=0;f<b;++f){var h=c[f];e[f]=h.readValueFromPointer(d);d+=h.argPackAdvance}a=a.apply(void 0,e);return Y(a)},z:function(a,b,c,d){a=se[a];b=ne(b);c=re(c);a(b,c,null,d)},Q:ke,Ra:function(a,b){a=ne(a);b=ne(b);return a==b},Pa:function(a){if(0===a)return Y(te());a=re(a);return Y(te()[a])},y:function(a,b){b=pe(a,b);for(var c=b[0],d=c.name+"_$"+b.slice(1).map(function(q){return q.name}).join("_")+
"$",e=["retType"],f=[c],h="",l=0;l<a-1;++l)h+=(0!==l?", ":"")+"arg"+l,e.push("argType"+l),f.push(b[1+l]);d="return function "+td("methodCaller_"+d)+"(handle, name, destructors, args) {\n";var m=0;for(l=0;l<a-1;++l)d+="    var arg"+l+" = argType"+l+".readValueFromPointer(args"+(m?"+"+m:"")+");\n",m+=b[l+1].argPackAdvance;d+="    var rv = handle[name]("+h+");\n";for(l=0;l<a-1;++l)b[l+1].deleteObject&&(d+="    argType"+l+".deleteObject(arg"+l+");\n");c.he||(d+="    return retType.toWireType(destructors, rv);\n");
e.push(d+"};\n");a=he(e).apply(null,f);return ue(a)},Oa:function(a){a=re(a);return Y(E[a])},u:function(a,b){a=ne(a);b=ne(b);return Y(a[b])},ba:function(a){4<a&&(Z[a].ed+=1)},Qa:function(a,b){a=ne(a);b=ne(b);return a instanceof b},J:function(a,b,c,d){a=ne(a);var e=ve[b];if(!e){e="";for(var f=0;f<b;++f)e+=(0!==f?", ":"")+"arg"+f;var h="return function emval_allocator_"+b+"(constructor, argTypes, args) {\n";for(f=0;f<b;++f)h+="var argType"+f+" = requireRegisteredType(Module['HEAP32'][(argTypes >>> 2) + "+
f+'], "parameter '+f+'");\nvar arg'+f+" = argType"+f+".readValueFromPointer(args);\nargs += argType"+f+"['argPackAdvance'];\n";e=(new Function("requireRegisteredType","Module","__emval_register",h+("var obj = new constructor("+e+");\nreturn __emval_register(obj);\n}\n")))(oe,E,Y);ve[b]=e}return e(a,c,d)},fa:function(){return Y([])},Ua:function(a){return Y(re(a))},Na:function(){return Y({})},Ta:function(a){od(Z[a].value);ke(a)},p:function(a,b,c){a=ne(a);b=ne(b);c=ne(c);a[b]=c},o:function(a,b){a=oe(a,
"_emval_take_value");a=a.readValueFromPointer(b);return Y(a)},Sa:function(a){a=ne(a);return Y(typeof a)},s:function(){H()},D:function(){var a=E.allowedThreads;return a?a:navigator.hardwareConcurrency},P:Mb,m:function(a,b,c){we.length=0;var d;for(c>>=2;d=x()[b++];)(d=105>d)&&c&1&&c++,we.push(d?ka()[c++>>1]:A()[c]),++c;return vb[a].apply(null,we)},ra:xe,S:function(){},w:ye,v:wb,B:Lb,L:function(){return"undefined"!==typeof SharedArrayBuffer},e:function(a,b){wf(a,b||1);throw"longjmp";},ha:function(a,
b,c){x().copyWithin(a,b,b+c)},la:function(a,b,c){Ce.length=b;c>>=3;for(var d=0;d<b;d++)Ce[d]=ka()[c+d];return(0>a?vb[-a-1]:vf[a]).apply(null,Ce)},ia:function(a){var b=x().length;a>>>=0;if(a<=b||838860800<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);d=Math.max(a,d);0<d%65536&&(d+=65536-d%65536);a:{try{n.grow(Math.min(838860800,d)-t.byteLength+65535>>>16);aa(n.buffer);var e=1;break a}catch(f){}e=void 0}if(e)return!0}return!1},ma:function(a,b,c){return Ee(a)?Fe(a,b,c):
He(a,b,c)},R:function(){},Fa:function(a,b,c,d,e){function f(D){Me(D,h,q,p,m)}function h(D,da){Oe(D,da.response,function(W){--Jb;Ne(function(){v?M.get(v)(W):b&&b(W)})},function(W){--Jb;Ne(function(){v?M.get(v)(W):b&&b(W)})})}function l(D){Me(D,r,q,p,m)}function m(D){Ne(function(){I?M.get(I)(D):e&&e(D)})}function q(D){--Jb;Ne(function(){z?M.get(z)(D):c&&c(D)})}function p(D){Ne(function(){B?M.get(B)(D):d&&d(D)})}function r(D){--Jb;Ne(function(){v?M.get(v)(D):b&&b(D)})}Jb+=1;var u=a+112,k=K(u),v=C()[u+
36>>2],z=C()[u+40>>2],B=C()[u+44>>2],I=C()[u+48>>2],J=C()[u+52>>2],ra=!!(J&4),w=!!(J&32);J=!!(J&16);if("EM_IDB_STORE"===k)k=C()[u+84>>2],Oe(a,x().slice(k,k+C()[u+88>>2]),r,q);else if("EM_IDB_DELETE"===k)Qe(a,r,q);else if(J){if(w)return 0;Me(a,ra?h:r,q,p,m)}else Pe(a,r,w?q:ra?f:l);return a},na:function(a,b){b>>=2;var c=A()[b+6];b={alpha:!!A()[b+0],depth:!!A()[b+1],stencil:!!A()[b+2],antialias:!!A()[b+3],premultipliedAlpha:!!A()[b+4],preserveDrawingBuffer:!!A()[b+5],powerPreference:Ye[c],failIfMajorPerformanceCaveat:!!A()[b+
7],je:A()[b+8],df:A()[b+9],od:A()[b+10],Td:A()[b+11],hf:A()[b+12],jf:A()[b+13]};a=Ee(a);return!a||b.Td?0:Ue(a,b)},ta:bf,ua:cf,I:function(a){Gb(a)},C:df,sa:ef,U:ff,Va:gf,T:hf,b:function(){return Fa|0},Ma:function(){var a=self.navigator.userAgent,b=Oa(a)+1,c=L(b);Na(a,c,b);return c},ja:jf,ga:function(){O.ce()},M:xf,k:yf,q:zf,N:Af,ea:Bf,f:Cf,i:Df,O:Ef,da:Ff,ca:Gf,Wa:Hf,a:n||E.wasmMemory,La:function(a){Qb();var b=new Date(A()[a+20>>2]+1900,A()[a+16>>2],A()[a+12>>2],A()[a+8>>2],A()[a+4>>2],A()[a>>2],0),
c=A()[a+32>>2],d=b.getTimezoneOffset(),e=new Date(b.getFullYear(),0,1),f=(new Date(b.getFullYear(),6,1)).getTimezoneOffset(),h=e.getTimezoneOffset(),l=Math.min(h,f);0>c?A()[a+32>>2]=Number(f!=h&&l==d):0<c!=(l==d)&&(f=Math.max(h,f),b.setTime(b.getTime()+6E4*((0<c?l:f)-d)));A()[a+24>>2]=b.getDay();c=(b.getTime()-e.getTime())/864E5|0;A()[a+28>>2]=c;A()[a>>2]=b.getSeconds();A()[a+4>>2]=b.getMinutes();A()[a+8>>2]=b.getHours();A()[a+12>>2]=b.getDate();A()[a+16>>2]=b.getMonth();return b.getTime()/1E3|0},
pa:function(a){var b=O.Oc.pop();a&&b()},qa:Nb,Z:function(a,b,c,d){if("undefined"===typeof SharedArrayBuffer)return F("Current environment does not support SharedArrayBuffer, pthreads are not available!"),6;if(!a)return F("pthread_create called with a null thread pointer!"),28;var e=[];if(G&&0===e.length)return If(687865856,a,b,c,d);var f=0,h=0;if(b&&-1!=b){var l=A()[b>>2];l+=81920;f=A()[b+8>>2];h=0!==A()[b+12>>2]}else l=2097152;(b=0==f)?f=gd(16,l):(f-=l,Ka(0<f));for(var m=L(228),q=0;57>q;++q)C()[(m>>
2)+q]=0;A()[a>>2]=m;A()[m+12>>2]=m;a=m+152;A()[a>>2]=a;c={hc:f,oc:l,Uc:b,nd:h,Ie:c,Kc:m,qc:d,Qe:e};return G?(c.Ve="spawnThread",postMessage(c,e),0):Fb(c)},Ka:function(a,b){return lf(a,b)},c:function(a){Fa=a|0},_:sf,ka:function(a,b,c,d){return sf(a,b,c,d)},$:function(a){var b=Date.now()/1E3|0;a&&(A()[a>>2]=b);return b}};
(function(){function a(e,f){E.asm=e.exports;M=E.asm.ab;$a.unshift(E.asm.Xa);O.gd.push(E.asm.$a);Ha=f;G||ob("wasm-instantiate")}function b(e){a(e.instance,e.module)}function c(e){return sb().then(function(f){return WebAssembly.instantiate(f,d)}).then(e,function(f){F("failed to asynchronously prepare wasm: "+f);H(f)})}var d={a:Jf};G||nb("wasm-instantiate");if(E.instantiateWasm)try{return E.instantiateWasm(d,a)}catch(e){return F("Module.instantiateWasm callback failed with error: "+e),!1}(function(){return Ga||
"function"!==typeof WebAssembly.instantiateStreaming||pb()||"function"!==typeof fetch?c(b):fetch(qb,{credentials:"same-origin"}).then(function(e){return WebAssembly.instantiateStreaming(e,d).then(b,function(f){F("wasm streaming compile failed: "+f);F("falling back to ArrayBuffer instantiation");return c(b)})})})().catch(na);return{}})();E.___wasm_call_ctors=function(){return(E.___wasm_call_ctors=E.asm.Xa).apply(null,arguments)};
var P=E._free=function(){return(P=E._free=E.asm.Ya).apply(null,arguments)},L=E._malloc=function(){return(L=E._malloc=E.asm.Za).apply(null,arguments)},Bb=E._pthread_self=function(){return(Bb=E._pthread_self=E.asm._a).apply(null,arguments)};E._emscripten_tls_init=function(){return(E._emscripten_tls_init=E.asm.$a).apply(null,arguments)};var ee=E.___getTypeName=function(){return(ee=E.___getTypeName=E.asm.bb).apply(null,arguments)};
E.___embind_register_native_and_builtin_types=function(){return(E.___embind_register_native_and_builtin_types=E.asm.cb).apply(null,arguments)};
var hd=E._memset=function(){return(hd=E._memset=E.asm.db).apply(null,arguments)},kf=E._emscripten_get_global_libc=function(){return(kf=E._emscripten_get_global_libc=E.asm.eb).apply(null,arguments)},Tb=E.__get_tzname=function(){return(Tb=E.__get_tzname=E.asm.fb).apply(null,arguments)},Sb=E.__get_daylight=function(){return(Sb=E.__get_daylight=E.asm.gb).apply(null,arguments)},Rb=E.__get_timezone=function(){return(Rb=E.__get_timezone=E.asm.hb).apply(null,arguments)},mf=E._emscripten_main_browser_thread_id=
function(){return(mf=E._emscripten_main_browser_thread_id=E.asm.ib).apply(null,arguments)},Cb=E.___pthread_tsd_run_dtors=function(){return(Cb=E.___pthread_tsd_run_dtors=E.asm.jb).apply(null,arguments)},Eb=E._emscripten_main_thread_process_queued_calls=function(){return(Eb=E._emscripten_main_thread_process_queued_calls=E.asm.kb).apply(null,arguments)};E._emscripten_current_thread_process_queued_calls=function(){return(E._emscripten_current_thread_process_queued_calls=E.asm.lb).apply(null,arguments)};
var Ab=E._emscripten_register_main_browser_thread_id=function(){return(Ab=E._emscripten_register_main_browser_thread_id=E.asm.mb).apply(null,arguments)},ub=E.__emscripten_do_dispatch_to_thread=function(){return(ub=E.__emscripten_do_dispatch_to_thread=E.asm.nb).apply(null,arguments)},If=E._emscripten_sync_run_in_main_thread_4=function(){return(If=E._emscripten_sync_run_in_main_thread_4=E.asm.ob).apply(null,arguments)},Be=E._emscripten_run_in_main_runtime_thread_js=function(){return(Be=E._emscripten_run_in_main_runtime_thread_js=
E.asm.pb).apply(null,arguments)},Ge=E.__emscripten_call_on_thread=function(){return(Ge=E.__emscripten_call_on_thread=E.asm.qb).apply(null,arguments)},zb=E.__emscripten_thread_init=function(){return(zb=E.__emscripten_thread_init=E.asm.rb).apply(null,arguments)},ze=E.stackSave=function(){return(ze=E.stackSave=E.asm.sb).apply(null,arguments)},Q=E.stackRestore=function(){return(Q=E.stackRestore=E.asm.tb).apply(null,arguments)},Ae=E.stackAlloc=function(){return(Ae=E.stackAlloc=E.asm.ub).apply(null,arguments)},
Ib=E._emscripten_stack_set_limits=function(){return(Ib=E._emscripten_stack_set_limits=E.asm.vb).apply(null,arguments)},wf=E._setThrew=function(){return(wf=E._setThrew=E.asm.wb).apply(null,arguments)},gd=E._memalign=function(){return(gd=E._memalign=E.asm.xb).apply(null,arguments)};E.dynCall_jiji=function(){return(E.dynCall_jiji=E.asm.yb).apply(null,arguments)};E.dynCall_viijii=function(){return(E.dynCall_viijii=E.asm.zb).apply(null,arguments)};
E.dynCall_iiiiiijj=function(){return(E.dynCall_iiiiiijj=E.asm.Ab).apply(null,arguments)};E.dynCall_iiiiij=function(){return(E.dynCall_iiiiij=E.asm.Bb).apply(null,arguments)};E.dynCall_iiiiijj=function(){return(E.dynCall_iiiiijj=E.asm.Cb).apply(null,arguments)};var Db=E.__emscripten_allow_main_runtime_queued_calls=223460,xb=E.__emscripten_main_thread_futex=821624;function Cf(a,b){var c=ze();try{M.get(a)(b)}catch(d){Q(c);if(d!==d+0&&"longjmp"!==d)throw d;wf(1,0)}}
function yf(a,b){var c=ze();try{return M.get(a)(b)}catch(d){Q(c);if(d!==d+0&&"longjmp"!==d)throw d;wf(1,0)}}function Df(a,b,c){var d=ze();try{M.get(a)(b,c)}catch(e){Q(d);if(e!==e+0&&"longjmp"!==e)throw e;wf(1,0)}}function zf(a,b,c){var d=ze();try{return M.get(a)(b,c)}catch(e){Q(d);if(e!==e+0&&"longjmp"!==e)throw e;wf(1,0)}}function Ef(a,b,c,d){var e=ze();try{M.get(a)(b,c,d)}catch(f){Q(e);if(f!==f+0&&"longjmp"!==f)throw f;wf(1,0)}}
function Bf(a,b,c,d,e){var f=ze();try{return M.get(a)(b,c,d,e)}catch(h){Q(f);if(h!==h+0&&"longjmp"!==h)throw h;wf(1,0)}}function Af(a,b,c,d){var e=ze();try{return M.get(a)(b,c,d)}catch(f){Q(e);if(f!==f+0&&"longjmp"!==f)throw f;wf(1,0)}}function Ff(a,b,c,d,e){var f=ze();try{M.get(a)(b,c,d,e)}catch(h){Q(f);if(h!==h+0&&"longjmp"!==h)throw h;wf(1,0)}}function xf(a){var b=ze();try{return M.get(a)()}catch(c){Q(b);if(c!==c+0&&"longjmp"!==c)throw c;wf(1,0)}}
function Gf(a,b,c,d,e,f,h){var l=ze();try{M.get(a)(b,c,d,e,f,h)}catch(m){Q(l);if(m!==m+0&&"longjmp"!==m)throw m;wf(1,0)}}function Hf(a,b,c,d,e,f,h,l,m,q){var p=ze();try{M.get(a)(b,c,d,e,f,h,l,m,q)}catch(r){Q(p);if(r!==r+0&&"longjmp"!==r)throw r;wf(1,0)}}E.addRunDependency=nb;E.removeRunDependency=ob;E.FS_createPath=Rc;E.FS_createDataFile=Tc;E.FS_createPreloadedFile=Wc;E.FS_createLazyFile=Vc;E.FS_createDevice=fb;E.FS_unlink=Kc;E.PThread=O;E.PThread=O;E.wasmMemory=n;E.ExitStatus=Hb;var Kf;
function Hb(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}mb=function Lf(){Kf||Mf();Kf||(mb=Lf)};
function Mf(){function a(){if(!Kf&&(Kf=!0,E.calledRun=!0,!Ia)){cb();G||(qc=!1,ib(ab));ma(E);if(E.onRuntimeInitialized)E.onRuntimeInitialized();if(!G){if(E.postRun)for("function"==typeof E.postRun&&(E.postRun=[E.postRun]);E.postRun.length;){var b=E.postRun.shift();bb.unshift(b)}ib(bb)}}}if(!(0<kb))if(G)ma(E),cb(),postMessage({cmd:"loaded"});else{if(!G){if(E.preRun)for("function"==typeof E.preRun&&(E.preRun=[E.preRun]);E.preRun.length;)jb();ib(Za)}0<kb||(E.setStatus?(E.setStatus("Running..."),setTimeout(function(){setTimeout(function(){E.setStatus("")},
1);a()},1)):a())}}E.run=Mf;function Gb(a){Ja=a;if(G)throw postMessage({cmd:"exitProcess",returnCode:a}),new Hb(a);if(!Kb()){O.Je();if(E.onExit)E.onExit(a);Ia=!0}va(a,new Hb(a))}if(E.preInit)for("function"==typeof E.preInit&&(E.preInit=[E.preInit]);0<E.preInit.length;)E.preInit.pop()();G&&(noExitRuntime=!1,O.de());Mf();


  return BlinkIDWasmSDK.ready
}
);
})();
if (typeof exports === 'object' && typeof module === 'object')
  module.exports = BlinkIDWasmSDK;
else if (typeof define === 'function' && define['amd'])
  define([], function() { return BlinkIDWasmSDK; });
else if (typeof exports === 'object')
  exports["BlinkIDWasmSDK"] = BlinkIDWasmSDK;
