
var BlinkIDWasmSDK = (function() {
  var _scriptDir = typeof document !== 'undefined' && document.currentScript ? document.currentScript.src : undefined;
  
  return (
function(BlinkIDWasmSDK) {
  BlinkIDWasmSDK = BlinkIDWasmSDK || {};


function g(){n.buffer!=t&&aa(n.buffer);return ba}function x(){n.buffer!=t&&aa(n.buffer);return ca}function da(){n.buffer!=t&&aa(n.buffer);return ea}function y(){n.buffer!=t&&aa(n.buffer);return fa}function A(){n.buffer!=t&&aa(n.buffer);return ha}function C(){n.buffer!=t&&aa(n.buffer);return ia}function ja(){n.buffer!=t&&aa(n.buffer);return ka}var D;D||(D=typeof BlinkIDWasmSDK !== 'undefined' ? BlinkIDWasmSDK : {});var la,ma;D.ready=new Promise(function(a,b){la=a;ma=b});D.Jc||(D.Jc=0);D.Jc++;
(function(a){function b(m,q,p){var r=new XMLHttpRequest;r.open("GET",m,!0);r.responseType="arraybuffer";r.onprogress=function(u){var k=q;u.total&&(k=u.total);if(u.loaded){r.vd?D.Xb[m].loaded=u.loaded:(r.vd=!0,D.Xb||(D.Xb={}),D.Xb[m]={loaded:u.loaded,total:k});var v=k=u=0,z;for(z in D.Xb){var B=D.Xb[z];u+=B.total;k+=B.loaded;v++}u=Math.ceil(u*D.Jc/v);D.setStatus&&D.setStatus("Downloading data... ("+k+"/"+u+")")}else!D.Xb&&D.setStatus&&D.setStatus("Downloading data...")};r.onerror=function(){throw Error("NetworkError for: "+
m);};r.onload=function(){if(200==r.status||304==r.status||206==r.status||0==r.status&&r.response)p(r.response);else throw Error(r.statusText+" : "+r.responseURL);};r.send(null)}function c(m){console.error("package error:",m)}function d(){function m(u,k,v){this.start=u;this.end=k;this.audio=v}function q(u){if(!u)throw"Loading data file failed."+Error().stack;if(!(u instanceof ArrayBuffer))throw"bad input to processPackageData"+Error().stack;u=new Uint8Array(u);m.prototype.Ad=u;u=a.files;for(var k=
0;k<u.length;++k)m.prototype.Uc[u[k].filename].onload();D.removeRunDependency("datafile_../../resources/advanced-threads/BlinkIDWasmSDK.data")}D.FS_createPath("/","microblink",!0,!0);m.prototype={Uc:{},open:function(u,k){this.name=k;this.Uc[k]=this;D.addRunDependency("fp "+this.name)},send:function(){},onload:function(){this.finish(this.Ad.subarray(this.start,this.end))},finish:function(u){D.FS_createDataFile(this.name,null,u,!0,!0,!0);D.removeRunDependency("fp "+this.name);this.Uc[this.name]=null}};
for(var p=a.files,r=0;r<p.length;++r)(new m(p[r].start,p[r].end,p[r].audio)).open("GET",p[r].filename);D.addRunDependency("datafile_../../resources/advanced-threads/BlinkIDWasmSDK.data");D.ld||(D.ld={});D.ld["../../resources/advanced-threads/BlinkIDWasmSDK.data"]={Ie:!1};l?(q(l),l=null):h=q}if("object"===typeof window)window.encodeURIComponent(window.location.pathname.toString().substring(0,window.location.pathname.toString().lastIndexOf("/"))+"/");else if("undefined"!==typeof location)encodeURIComponent(location.pathname.toString().substring(0,
location.pathname.toString().lastIndexOf("/"))+"/");else throw"using preloaded data can only be done on a web page or in a web worker";"function"!==typeof D.locateFilePackage||D.locateFile||(D.locateFile=D.locateFilePackage,E("warning: you defined Module.locateFilePackage, that has been renamed to Module.locateFile (using your locateFilePackage for now)"));var e=D.locateFile?D.locateFile("BlinkIDWasmSDK.data",""):"BlinkIDWasmSDK.data",f=a.remote_package_size,h=null,l=D.getPreloadedPackage?D.getPreloadedPackage(e,
f):null;l||b(e,f,function(m){h?(h(m),h=null):l=m},c);D.calledRun?d():(D.preRun||(D.preRun=[]),D.preRun.push(d))})({files:[{filename:"/microblink/BlinkID_Detector_general_6.7.0.strop",start:0,end:288208,audio:0},{filename:"/microblink/BlinkID_BlurClassifier_general_6.2.0.strop",start:288208,end:292146,audio:0},{filename:"/microblink/BlinkID_Ocr_general_6.14.0.strop",start:292146,end:808286,audio:0},{filename:"/microblink/BlinkID_RotationClassifier_general_6.2.0.strop",start:808286,end:864800,audio:0},
{filename:"/microblink/BlinkID_Segmentator_general_6.15.0.strop",start:864800,end:2793784,audio:0},{filename:"/microblink/face_detector_model.zzip",start:2793784,end:2890642,audio:0},{filename:"/microblink/ccc_lookup_table.zzip",start:2890642,end:2911111,audio:0},{filename:"/microblink/BlinkID_MonochromeClassifier_general_6.0.0.strop",start:2911111,end:2917929,audio:0},{filename:"/microblink/BlinkID_Classifier_general_6.15.0.strop",start:2917929,end:3446859,audio:0},{filename:"/microblink/BlinkID_MoireClassifier_malaysia_6.0.0.strop",
start:3446859,end:3453741,audio:0},{filename:"/microblink/BlinkID_Ocr_mrz_6.4.0.strop",start:3453741,end:3823533,audio:0},{filename:"/microblink/BlinkID_Analyzer_general_6.6.0.strop",start:3823533,end:3840271,audio:0}],remote_package_size:3840271,package_uuid:"9a4fa844-9da0-43e0-af7b-4186a33f2aa5"});var crypto={getRandomValues:function(a){for(var b=0;b<a.length;b++)a[b]=256*Math.random()|0}},oa;oa=D.allowedThreads&&0<D.allowedThreads?D.allowedThreads-1:navigator.hardwareConcurrency-1;var pa=0,qa;
0<oa&&(D.threadWorkersReadyPromise=new Promise(function(a){qa=a}));D.preRun||(D.preRun=[]);D.preRun.push(function(a){function b(){pa++;pa==oa&&qa()}var c=a.PThread.Pc;a.PThread.Pc=function(d){c(d,b)}});var ra={},sa;for(sa in D)D.hasOwnProperty(sa)&&(ra[sa]=D[sa]);var ta="./this.program";function ua(a,b){throw b;}var va=!1,wa=!1,xa=!1;va="object"===typeof window;wa="function"===typeof importScripts;xa="object"===typeof process&&"object"===typeof process.Be&&"string"===typeof process.Be.node;
var F=D.ENVIRONMENT_IS_PTHREAD||!1,ya="";function za(a){return D.locateFile?D.locateFile(a,ya):ya+a}var Aa,Ba;
if(va||wa)wa?ya=self.location.href:"undefined"!==typeof document&&document.currentScript&&(ya=document.currentScript.src),_scriptDir&&(ya=_scriptDir),ya=0!==ya.indexOf("blob:")?ya.substr(0,ya.lastIndexOf("/")+1):"",Aa=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},wa&&(Ba=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});
var Ca=D.print||console.log.bind(console),E=D.printErr||console.warn.bind(console);for(sa in ra)ra.hasOwnProperty(sa)&&(D[sa]=ra[sa]);ra=null;D.thisProgram&&(ta=D.thisProgram);D.quit&&(ua=D.quit);var Da,Ea=0,Fa;D.wasmBinary&&(Fa=D.wasmBinary);var noExitRuntime=D.noExitRuntime||!0;"object"!==typeof WebAssembly&&H("no native wasm support detected");var n,Ga,Ha=!1,Ia;function Ja(a,b){a||H("Assertion failed: "+b)}
function Ka(a,b,c){c=b+c;for(var d="";!(b>=c);){var e=a[b++];if(!e)break;if(e&128){var f=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|f);else{var h=a[b++]&63;e=224==(e&240)?(e&15)<<12|f<<6|h:(e&7)<<18|f<<12|h<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d}function K(a,b){return a?Ka(x(),a,b):""}
function La(a,b,c,d){if(!(0<d))return 0;var e=c;d=c+d-1;for(var f=0;f<a.length;++f){var h=a.charCodeAt(f);if(55296<=h&&57343>=h){var l=a.charCodeAt(++f);h=65536+((h&1023)<<10)|l&1023}if(127>=h){if(c>=d)break;b[c++]=h}else{if(2047>=h){if(c+1>=d)break;b[c++]=192|h>>6}else{if(65535>=h){if(c+2>=d)break;b[c++]=224|h>>12}else{if(c+3>=d)break;b[c++]=240|h>>18;b[c++]=128|h>>12&63}b[c++]=128|h>>6&63}b[c++]=128|h&63}}b[c]=0;return c-e}function Ma(a,b,c){La(a,x(),b,c)}
function Na(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:b+4}return b}function Oa(a,b){for(var c="",d=0;!(d>=b/2);++d){var e=da()[a+2*d>>1];if(0==e)break;c+=String.fromCharCode(e)}return c}function Pa(a,b,c){void 0===c&&(c=2147483647);if(2>c)return 0;c-=2;var d=b;c=c<2*a.length?c/2:a.length;for(var e=0;e<c;++e){var f=a.charCodeAt(e);da()[b>>1]=f;b+=2}da()[b>>1]=0;return b-d}
function Qa(a){return 2*a.length}function Ra(a,b){for(var c=0,d="";!(c>=b/4);){var e=A()[a+4*c>>2];if(0==e)break;++c;65536<=e?(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023)):d+=String.fromCharCode(e)}return d}function Sa(a,b,c){void 0===c&&(c=2147483647);if(4>c)return 0;var d=b;c=d+c-4;for(var e=0;e<a.length;++e){var f=a.charCodeAt(e);if(55296<=f&&57343>=f){var h=a.charCodeAt(++e);f=65536+((f&1023)<<10)|h&1023}A()[b>>2]=f;b+=4;if(b+4>c)break}A()[b>>2]=0;return b-d}
function Ta(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&++c;b+=4}return b}function Ua(a){var b=Na(a)+1,c=L(b);c&&La(a,g(),c,b);return c}function Va(a,b){g().set(a,b)}var t,ba,ca,ea,fa,ha,ia,Wa,ka;F&&(t=D.buffer);
function aa(a){t=a;D.HEAP8=ba=new Int8Array(a);D.HEAP16=ea=new Int16Array(a);D.HEAP32=ha=new Int32Array(a);D.HEAPU8=ca=new Uint8Array(a);D.HEAPU16=fa=new Uint16Array(a);D.HEAPU32=ia=new Uint32Array(a);D.HEAPF32=Wa=new Float32Array(a);D.HEAPF64=ka=new Float64Array(a)}var Xa=D.INITIAL_MEMORY||209715200;
if(F)n=D.wasmMemory,t=D.buffer;else if(D.wasmMemory)n=D.wasmMemory;else if(n=new WebAssembly.Memory({initial:Xa/65536,maximum:12800,shared:!0}),!(n.buffer instanceof SharedArrayBuffer))throw E("requested a shared WebAssembly.Memory but the returned buffer is not a SharedArrayBuffer, indicating that while the browser has SharedArrayBuffer it does not have WebAssembly threads support - you may need to set a flag"),xa&&console.log("(on node you may need: --experimental-wasm-threads --experimental-wasm-bulk-memory and also use a recent version)"),
Error("bad memory");n&&(t=n.buffer);Xa=t.byteLength;aa(t);var O,Ya=[],Za=[],$a=[];function ab(){F||(D.noFSInit||bb||(bb=!0,cb(),D.stdin=D.stdin,D.stdout=D.stdout,D.stderr=D.stderr,D.stdin?db("/dev","stdin",D.stdin):eb("/dev/tty","/dev/stdin"),D.stdout?db("/dev","stdout",null,D.stdout):eb("/dev/tty","/dev/stdout"),D.stderr?db("/dev","stderr",null,D.stderr):eb("/dev/tty1","/dev/stderr"),fb("/dev/stdin",0),fb("/dev/stdout",1),fb("/dev/stderr",1)),gb(Za))}
function hb(){var a=D.preRun.shift();Ya.unshift(a)}var jb=0,kb=null,lb=null;function mb(){Ja(!F,"addRunDependency cannot be used in a pthread worker");jb++;D.monitorRunDependencies&&D.monitorRunDependencies(jb)}function nb(){jb--;D.monitorRunDependencies&&D.monitorRunDependencies(jb);if(0==jb&&(null!==kb&&(clearInterval(kb),kb=null),lb)){var a=lb;lb=null;a()}}D.preloadedImages={};D.preloadedAudios={};
function H(a){if(D.onAbort)D.onAbort(a);F&&console.error("Pthread aborting at "+Error().stack);a+="";E(a);Ha=!0;Ia=1;a=new WebAssembly.RuntimeError("abort("+a+"). Build with -s ASSERTIONS=1 for more info.");ma(a);throw a;}function ob(){return pb.startsWith("data:application/octet-stream;base64,")}var pb="BlinkIDWasmSDK.wasm";ob()||(pb=za(pb));
function qb(){var a=pb;try{if(a==pb&&Fa)return new Uint8Array(Fa);if(Ba)return Ba(a);throw"both async and sync fetching of the wasm failed";}catch(b){H(b)}}function rb(){return Fa||!va&&!wa||"function"!==typeof fetch?Promise.resolve().then(function(){return qb()}):fetch(pb,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+pb+"'";return a.arrayBuffer()}).catch(function(){return qb()})}
var P,sb,ub={302322:function(a){a=K(a);throw Error("Failed to reconfigure RecognizerRunner due to following error: "+a);},302458:function(a,b,c,d){a=K(a);b=K(b);c=K(c);d=K(d);throw Error(a+b+c+d);},302674:function(a,b){a=K(a);b=K(b);throw Error(a+b);},302784:function(a,b){a=K(a);b=K(b);console.log(a+b)},302882:function(a){throw Error(K(a));},302925:function(){throw"Canceled!";},302943:function(a,b){setTimeout(function(){tb(a,b)},0)},303022:function(){throw Error("Unable to perform that operation while recognizer is in use!");
},303105:function(){throw Error("Unable to perform that operation while recognizer is in use!");},303188:function(){throw Error("Unable to perform that operation while recognizer is in use!");}};function gb(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b(D);else{var c=b.Je;"number"===typeof c?void 0===b.dc?O.get(c)():O.get(c)(b.dc):c(void 0===b.dc?null:b.dc)}}}
function vb(a,b){if(0>=a||a>g().length||a&1||0>b)return-28;if(0==b)return 0;2147483647<=b&&(b=Infinity);var c=Atomics.load(A(),wb>>2),d=0;if(c==a&&Atomics.compareExchange(A(),wb>>2,c,0)==c&&(--b,d=1,0>=b))return 1;a=Atomics.notify(A(),a>>2,b);if(0<=a)return a+d;throw"Atomics.notify returned an unexpected value "+a;}D._emscripten_futex_wake=vb;
function xb(a){if(F)throw"Internal Error! cleanupThread() can only ever be called from main application thread!";if(!a)throw"Internal Error! Null pthread_ptr in cleanupThread!";var b=Q.Ob[a];b&&(A()[a+12>>2]=0,Q.Ac(b.worker))}
var Q={Tb:[],Sb:[],Vc:[],Ne:function(){},Rd:function(){for(var a=L(228),b=0;57>b;++b)C()[a/4+b]=0;A()[a+12>>2]=a;b=a+152;A()[b>>2]=b;var c=L(512);for(b=0;128>b;++b)C()[c/4+b]=0;Atomics.store(C(),a+100>>2,c);Atomics.store(C(),a+40>>2,a);yb(a,!wa,1);zb(a)},Sd:function(){Q.receiveObjectTransfer=Q.ge;Q.threadInit=Q.ue;Q.threadCancel=Q.te;Q.threadExit=Q.sd;Q.setExitStatus=Q.me},Ob:{},Cc:[],ie:function(){for(;0<Q.Cc.length;)Q.Cc.pop()();F&&Ab()&&Bb()},rd:function(a,b){Atomics.store(C(),a+56>>2,1);Atomics.store(C(),
a+60>>2,0);Q.ie();Atomics.store(C(),a+4>>2,b);Atomics.store(C(),a+0>>2,1);vb(a+0,2147483647);yb(0,0,0)},me:function(a){Ia=a},sd:function(a){var b=Ab();b&&(Q.rd(b,a),F&&postMessage({cmd:"exit"}))},te:function(){Q.rd(Ab(),-1);postMessage({cmd:"cancelDone"})},se:function(){for(var a in Q.Ob){var b=Q.Ob[a];b&&b.worker&&Q.Ac(b.worker)}Q.Ob={};for(a=0;a<Q.Tb.length;++a){var c=Q.Tb[a];c.terminate()}Q.Tb=[];for(a=0;a<Q.Sb.length;++a)c=Q.Sb[a],b=c.Hb,Q.Kc(b),c.terminate();Q.Sb=[]},Kc:function(a){if(a){if(a.Pb){var b=
A()[a.Pb+100>>2];A()[a.Pb+100>>2]=0;R(b);R(a.Pb)}a.Pb=0;a.Ic&&a.Wb&&R(a.Wb);a.Wb=0;a.worker&&(a.worker.Hb=null)}},Ac:function(a){Q.je(function(){delete Q.Ob[a.Hb.Pb];Q.Tb.push(a);Q.Sb.splice(Q.Sb.indexOf(a),1);Q.Kc(a.Hb);a.Hb=void 0})},je:function(a){A()[Cb>>2]=0;try{a()}finally{A()[Cb>>2]=1}},ge:function(){},ue:function(){for(var a in Q.Vc)Q.Vc[a]()},Pc:function(a,b){a.onmessage=function(c){var d=c.data,e=d.cmd;a.Hb&&(Q.Ed=a.Hb.Pb);if(d.targetThread&&d.targetThread!=Ab()){var f=Q.Ob[d.Ue];f?f.worker.postMessage(c.data,
d.transferList):console.error('Internal error! Worker sent a message "'+e+'" to target pthread '+d.targetThread+", but that thread no longer exists!")}else if("processQueuedMainThreadWork"===e)Db();else if("spawnThread"===e)Eb(c.data);else if("cleanupThread"===e)xb(d.thread);else if("killThread"===e){c=d.thread;if(F)throw"Internal Error! killThread() can only ever be called from main application thread!";if(!c)throw"Internal Error! Null pthread_ptr in killThread!";A()[c+12>>2]=0;c=Q.Ob[c];c.worker.terminate();
Q.Kc(c);Q.Sb.splice(Q.Sb.indexOf(c.worker),1);c.worker.Hb=void 0}else if("cancelThread"===e){c=d.thread;if(F)throw"Internal Error! cancelThread() can only ever be called from main application thread!";if(!c)throw"Internal Error! Null pthread_ptr in cancelThread!";Q.Ob[c].worker.postMessage({cmd:"cancel"})}else if("loaded"===e)a.loaded=!0,b&&b(a),a.kc&&(a.kc(),delete a.kc);else if("print"===e)Ca("Thread "+d.threadId+": "+d.text);else if("printErr"===e)E("Thread "+d.threadId+": "+d.text);else if("alert"===
e)alert("Thread "+d.threadId+": "+d.text);else if("exit"===e)a.Hb&&Atomics.load(C(),a.Hb.Pb+64>>2)&&Q.Ac(a);else if("exitProcess"===e)try{Fb(d.returnCode)}catch(h){if(h instanceof Gb)return;throw h;}else"cancelDone"===e?Q.Ac(a):"objectTransfer"!==e&&("setimmediate"===c.data.target?a.postMessage(c.data):E("worker sent an unknown command "+e));Q.Ed=void 0};a.onerror=function(c){E("pthread sent an error! "+c.filename+":"+c.lineno+": "+c.message)};a.postMessage({cmd:"load",urlOrBlob:D.mainScriptUrlOrBlob||
_scriptDir,wasmMemory:n,wasmModule:Ga})},wd:function(){var a=za("BlinkIDWasmSDK.worker.js");Q.Tb.push(new Worker(a))},Kd:function(){0==Q.Tb.length&&(Q.wd(),Q.Pc(Q.Tb[0]));return Q.Tb.pop()},De:function(a){for(a=performance.now()+a;performance.now()<a;);}};D.establishStackSpace=function(a,b){Hb(a,b);Ib(a)};D.invokeEntryPoint=function(a,b){return O.get(a)(b)};var Jb=0;function Kb(){return noExitRuntime||0<Jb}D.keepRuntimeAlive=Kb;var Lb;
Lb=F?function(){return performance.now()-D.__performance_now_clock_drift}:function(){return performance.now()};function Mb(a,b){Q.Cc.push(function(){O.get(a)(b)})}
function Nb(){function a(h){return(h=h.toTimeString().match(/\(([A-Za-z ]+)\)$/))?h[1]:"GMT"}if(F)return S(2,1);if(!Nb.Bd){Nb.Bd=!0;var b=(new Date).getFullYear(),c=new Date(b,0,1),d=new Date(b,6,1);b=c.getTimezoneOffset();var e=d.getTimezoneOffset(),f=Math.max(b,e);A()[Ob()>>2]=60*f;A()[Pb()>>2]=Number(b!=e);c=a(c);d=a(d);c=Ua(c);d=Ua(d);e<b?(A()[Qb()>>2]=c,A()[Qb()+4>>2]=d):(A()[Qb()>>2]=d,A()[Qb()+4>>2]=c)}}
function Rb(a,b){for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a}function Sb(a){var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=Rb(a.split("/").filter(function(d){return!!d}),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a}
function Tb(a){var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,b.length-1));return a+b}function Ub(a){if("/"===a)return"/";a=Sb(a);a=a.replace(/\/$/,"");var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)}
function Vb(){if("object"===typeof crypto&&"function"===typeof crypto.getRandomValues){var a=new Uint8Array(1);return function(){crypto.getRandomValues(a);return a[0]}}return function(){H("randomDevice")}}
function Wb(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:"/";if("string"!==typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=Rb(a.split("/").filter(function(d){return!!d}),!b).join("/");return(b?"/":"")+a||"."}var Xb=[];function Yb(a,b){Xb[a]={input:[],Cb:[],ac:b};Zb(a,$b)}
var $b={open:function(a){var b=Xb[a.node.ic];if(!b)throw new T(43);a.zb=b;a.seekable=!1},close:function(a){a.zb.ac.flush(a.zb)},flush:function(a){a.zb.ac.flush(a.zb)},read:function(a,b,c,d){if(!a.zb||!a.zb.ac.gd)throw new T(60);for(var e=0,f=0;f<d;f++){try{var h=a.zb.ac.gd(a.zb)}catch(l){throw new T(29);}if(void 0===h&&0===e)throw new T(6);if(null===h||void 0===h)break;e++;b[c+f]=h}e&&(a.node.timestamp=Date.now());return e},write:function(a,b,c,d){if(!a.zb||!a.zb.ac.Qc)throw new T(60);try{for(var e=
0;e<d;e++)a.zb.ac.Qc(a.zb,b[c+e])}catch(f){throw new T(29);}d&&(a.node.timestamp=Date.now());return e}},bc={gd:function(a){if(!a.input.length){var b=null;"undefined"!=typeof window&&"function"==typeof window.prompt?(b=window.prompt("Input: "),null!==b&&(b+="\n")):"function"==typeof readline&&(b=readline(),null!==b&&(b+="\n"));if(!b)return null;a.input=ac(b,!0)}return a.input.shift()},Qc:function(a,b){null===b||10===b?(Ca(Ka(a.Cb,0)),a.Cb=[]):0!=b&&a.Cb.push(b)},flush:function(a){a.Cb&&0<a.Cb.length&&
(Ca(Ka(a.Cb,0)),a.Cb=[])}},cc={Qc:function(a,b){null===b||10===b?(E(Ka(a.Cb,0)),a.Cb=[]):0!=b&&a.Cb.push(b)},flush:function(a){a.Cb&&0<a.Cb.length&&(E(Ka(a.Cb,0)),a.Cb=[])}},U={Nb:null,Qb:function(){return U.createNode(null,"/",16895,0)},createNode:function(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new T(63);U.Nb||(U.Nb={dir:{node:{Mb:U.ub.Mb,Fb:U.ub.Fb,ec:U.ub.ec,wc:U.ub.wc,pd:U.ub.pd,Gc:U.ub.Gc,qd:U.ub.qd,od:U.ub.od,Bc:U.ub.Bc},stream:{Vb:U.vb.Vb}},file:{node:{Mb:U.ub.Mb,Fb:U.ub.Fb},
stream:{Vb:U.vb.Vb,read:U.vb.read,write:U.vb.write,Wc:U.vb.Wc,xc:U.vb.xc,yc:U.vb.yc}},link:{node:{Mb:U.ub.Mb,Fb:U.ub.Fb,jc:U.ub.jc},stream:{}},Yc:{node:{Mb:U.ub.Mb,Fb:U.ub.Fb},stream:dc}});c=ec(a,b,c,d);fc(c.mode)?(c.ub=U.Nb.dir.node,c.vb=U.Nb.dir.stream,c.tb={}):32768===(c.mode&61440)?(c.ub=U.Nb.file.node,c.vb=U.Nb.file.stream,c.yb=0,c.tb=null):40960===(c.mode&61440)?(c.ub=U.Nb.link.node,c.vb=U.Nb.link.stream):8192===(c.mode&61440)&&(c.ub=U.Nb.Yc.node,c.vb=U.Nb.Yc.stream);c.timestamp=Date.now();
a&&(a.tb[b]=c,a.timestamp=c.timestamp);return c},Ke:function(a){return a.tb?a.tb.subarray?a.tb.subarray(0,a.yb):new Uint8Array(a.tb):new Uint8Array(0)},cd:function(a,b){var c=a.tb?a.tb.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)>>>0),0!=c&&(b=Math.max(b,256)),c=a.tb,a.tb=new Uint8Array(b),0<a.yb&&a.tb.set(c.subarray(0,a.yb),0))},he:function(a,b){if(a.yb!=b)if(0==b)a.tb=null,a.yb=0;else{var c=a.tb;a.tb=new Uint8Array(b);c&&a.tb.set(c.subarray(0,Math.min(b,a.yb)));a.yb=b}},ub:{Mb:function(a){var b=
{};b.Fd=8192===(a.mode&61440)?a.id:1;b.Mc=a.id;b.mode=a.mode;b.be=1;b.uid=0;b.Od=0;b.ic=a.ic;b.size=fc(a.mode)?4096:32768===(a.mode&61440)?a.yb:40960===(a.mode&61440)?a.link.length:0;b.xd=new Date(a.timestamp);b.ae=new Date(a.timestamp);b.Dd=new Date(a.timestamp);b.yd=4096;b.zd=Math.ceil(b.size/b.yd);return b},Fb:function(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);void 0!==b.size&&U.he(a,b.size)},ec:function(){throw gc[44];},wc:function(a,b,c,d){return U.createNode(a,
b,c,d)},pd:function(a,b,c){if(fc(a.mode)){try{var d=hc(b,c)}catch(f){}if(d)for(var e in d.tb)throw new T(55);}delete a.parent.tb[a.name];a.parent.timestamp=Date.now();a.name=c;b.tb[c]=a;b.timestamp=a.parent.timestamp;a.parent=b},Gc:function(a,b){delete a.tb[b];a.timestamp=Date.now()},qd:function(a,b){var c=hc(a,b),d;for(d in c.tb)throw new T(55);delete a.tb[b];a.timestamp=Date.now()},od:function(a){var b=[".",".."],c;for(c in a.tb)a.tb.hasOwnProperty(c)&&b.push(c);return b},Bc:function(a,b,c){a=U.createNode(a,
b,41471,0);a.link=c;return a},jc:function(a){if(40960!==(a.mode&61440))throw new T(28);return a.link}},vb:{read:function(a,b,c,d,e){var f=a.node.tb;if(e>=a.node.yb)return 0;a=Math.min(a.node.yb-e,d);if(8<a&&f.subarray)b.set(f.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=f[e+d];return a},write:function(a,b,c,d,e,f){b.buffer===g().buffer&&(f=!1);if(!d)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&(!a.tb||a.tb.subarray)){if(f)return a.tb=b.subarray(c,c+d),a.yb=d;if(0===a.yb&&0===e)return a.tb=
b.slice(c,c+d),a.yb=d;if(e+d<=a.yb)return a.tb.set(b.subarray(c,c+d),e),d}U.cd(a,e+d);if(a.tb.subarray&&b.subarray)a.tb.set(b.subarray(c,c+d),e);else for(f=0;f<d;f++)a.tb[e+f]=b[c+f];a.yb=Math.max(a.yb,e+d);return d},Vb:function(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.yb);if(0>b)throw new T(28);return b},Wc:function(a,b,c){U.cd(a.node,b+c);a.node.yb=Math.max(a.node.yb,b+c)},xc:function(a,b,c,d,e,f){if(0!==b)throw new T(28);if(32768!==(a.node.mode&61440))throw new T(43);
a=a.node.tb;if(f&2||a.buffer!==t){if(0<d||d+c<a.length)a=a.subarray?a.subarray(d,d+c):Array.prototype.slice.call(a,d,d+c);d=!0;f=65536*Math.ceil(c/65536);for(b=L(f);c<f;)g()[b+c++]=0;c=b;if(!c)throw new T(48);g().set(a,c)}else d=!1,c=a.byteOffset;return{xb:c,Hc:d}},yc:function(a,b,c,d,e){if(32768!==(a.node.mode&61440))throw new T(43);if(e&2)return 0;U.vb.write(a,b,0,d,c,!1);return 0}}},ic=null,jc={},kc=[],lc=1,mc=null,nc={},T=null,gc={};
function oc(a,b){a=Wb("/",a);b=b||{};if(!a)return{path:"",node:null};var c={ed:!0,Sc:0},d;for(d in c)void 0===b[d]&&(b[d]=c[d]);if(8<b.Sc)throw new T(32);a=Rb(a.split("/").filter(function(h){return!!h}),!1);var e=ic;c="/";for(d=0;d<a.length;d++){var f=d===a.length-1;if(f&&b.parent)break;e=hc(e,a[d]);c=Sb(c+"/"+a[d]);e.fc&&(!f||f&&b.ed)&&(e=e.fc.root);if(!f||b.sc)for(f=0;40960===(e.mode&61440);)if(e=pc(c),c=Wb(Tb(c),e),e=oc(c,{Sc:b.Sc}).node,40<f++)throw new T(32);}return{path:c,node:e}}
function qc(a){for(var b;;){if(a===a.parent)return a=a.Qb.jd,b?"/"!==a[a.length-1]?a+"/"+b:a+b:a;b=b?a.name+"/"+b:a.name;a=a.parent}}function rc(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%mc.length}function hc(a,b){var c;if(c=a.ub.ec?0:2)throw new T(c,a);for(c=mc[rc(a.id,b)];c;c=c.$b){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.ub.ec(a,b)}function ec(a,b,c,d){a=new sc(a,b,c,d);b=rc(a.parent.id,a.name);a.$b=mc[b];return mc[b]=a}
function fc(a){return 16384===(a&61440)}var tc={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090};function uc(a,b){try{return hc(a,b),20}catch(c){}return 0}function vc(a){var b=4096;for(a=a||0;a<=b;a++)if(!kc[a])return a;throw new T(33);}function wc(a,b){xc||(xc=function(){},xc.prototype={object:{get:function(){return this.node},set:function(e){this.node=e}}});var c=new xc,d;for(d in a)c[d]=a[d];a=c;b=vc(b);a.Lb=b;return kc[b]=a}
var dc={open:function(a){a.vb=jc[a.node.ic].vb;a.vb.open&&a.vb.open(a)},Vb:function(){throw new T(70);}};function Zb(a,b){jc[a]={vb:b}}function yc(a,b){var c="/"===b,d=!b;if(c&&ic)throw new T(10);if(!c&&!d){var e=oc(b,{ed:!1});b=e.path;e=e.node;if(e.fc)throw new T(10);if(!fc(e.mode))throw new T(54);}b={type:a,Re:{},jd:b,$d:[]};a=a.Qb(b);a.Qb=b;b.root=a;c?ic=a:e&&(e.fc=b,e.Qb&&e.Qb.$d.push(b))}
function zc(a,b,c){var d=oc(a,{parent:!0}).node;a=Ub(a);if(!a||"."===a||".."===a)throw new T(28);var e=uc(d,a);if(e)throw new T(e);if(!d.ub.wc)throw new T(63);return d.ub.wc(d,a,b,c)}function Ac(a){return zc(a,16895,0)}function Bc(a,b,c){"undefined"===typeof c&&(c=b,b=438);return zc(a,b|8192,c)}function eb(a,b){if(!Wb(a))throw new T(44);var c=oc(b,{parent:!0}).node;if(!c)throw new T(44);b=Ub(b);var d=uc(c,b);if(d)throw new T(d);if(!c.ub.Bc)throw new T(63);c.ub.Bc(c,b,a)}
function Cc(a){var b=oc(a,{parent:!0}).node,c=Ub(a),d=hc(b,c);a:{try{var e=hc(b,c)}catch(f){e=f.Bb;break a}e=fc(e.mode)?31:0}if(e)throw new T(e);if(!b.ub.Gc)throw new T(63);if(d.fc)throw new T(10);try{nc.willDeletePath&&nc.willDeletePath(a)}catch(f){E("FS.trackingDelegate['willDeletePath']('"+a+"') threw an exception: "+f.message)}b.ub.Gc(b,c);b=rc(d.parent.id,d.name);if(mc[b]===d)mc[b]=d.$b;else for(b=mc[b];b;){if(b.$b===d){b.$b=d.$b;break}b=b.$b}try{if(nc.onDeletePath)nc.onDeletePath(a)}catch(f){E("FS.trackingDelegate['onDeletePath']('"+
a+"') threw an exception: "+f.message)}}function pc(a){a=oc(a).node;if(!a)throw new T(44);if(!a.ub.jc)throw new T(28);return Wb(qc(a.parent),a.ub.jc(a))}function Dc(a,b){a="string"===typeof a?oc(a,{sc:!0}).node:a;if(!a.ub.Fb)throw new T(63);a.ub.Fb(a,{mode:b&4095|a.mode&-4096,timestamp:Date.now()})}
function fb(a,b,c,d){if(""===a)throw new T(44);if("string"===typeof b){var e=tc[b];if("undefined"===typeof e)throw Error("Unknown file open mode: "+b);b=e}c=b&64?("undefined"===typeof c?438:c)&4095|32768:0;if("object"===typeof a)var f=a;else{a=Sb(a);try{f=oc(a,{sc:!(b&131072)}).node}catch(h){}}e=!1;if(b&64)if(f){if(b&128)throw new T(20);}else f=zc(a,c,0),e=!0;if(!f)throw new T(44);8192===(f.mode&61440)&&(b&=-513);if(b&65536&&!fc(f.mode))throw new T(54);if(!e){if(f)if(40960===(f.mode&61440))c=32;else{if(c=
fc(f.mode))c=["r","w","rw"][b&3],b&512&&(c+="w"),c="r"!==c||b&512;c=c?31:0}else c=44;if(c)throw new T(c);}if(b&512){c=f;c="string"===typeof c?oc(c,{sc:!0}).node:c;if(!c.ub.Fb)throw new T(63);if(fc(c.mode))throw new T(31);if(32768!==(c.mode&61440))throw new T(28);c.ub.Fb(c,{size:0,timestamp:Date.now()})}b&=-131713;d=wc({node:f,path:qc(f),flags:b,seekable:!0,position:0,vb:f.vb,Ae:[],error:!1},d);d.vb.open&&d.vb.open(d);!D.logReadFiles||b&1||(Ec||(Ec={}),a in Ec||(Ec[a]=1,E("FS.trackingDelegate error on read file: "+
a)));try{nc.onOpenFile&&(f=0,1!==(b&2097155)&&(f|=1),0!==(b&2097155)&&(f|=2),nc.onOpenFile(a,f))}catch(h){E("FS.trackingDelegate['onOpenFile']('"+a+"', flags) threw an exception: "+h.message)}return d}function Fc(a){if(null===a.Lb)throw new T(8);a.Lc&&(a.Lc=null);try{a.vb.close&&a.vb.close(a)}catch(b){throw b;}finally{kc[a.Lb]=null}a.Lb=null}
function Gc(a,b,c){if(null===a.Lb)throw new T(8);if(!a.seekable||!a.vb.Vb)throw new T(70);if(0!=c&&1!=c&&2!=c)throw new T(28);a.position=a.vb.Vb(a,b,c);a.Ae=[]}
function Hc(a,b,c,d,e,f){if(0>d||0>e)throw new T(28);if(null===a.Lb)throw new T(8);if(0===(a.flags&2097155))throw new T(8);if(fc(a.node.mode))throw new T(31);if(!a.vb.write)throw new T(28);a.seekable&&a.flags&1024&&Gc(a,0,2);var h="undefined"!==typeof e;if(!h)e=a.position;else if(!a.seekable)throw new T(70);b=a.vb.write(a,b,c,d,e,f);h||(a.position+=b);try{if(a.path&&nc.onWriteToFile)nc.onWriteToFile(a.path)}catch(l){E("FS.trackingDelegate['onWriteToFile']('"+a.path+"') threw an exception: "+l.message)}return b}
function cb(){T||(T=function(a,b){this.node=b;this.le=function(c){this.Bb=c};this.le(a);this.message="FS error"},T.prototype=Error(),T.prototype.constructor=T,[44].forEach(function(a){gc[a]=new T(a);gc[a].stack="<generic error, no stack>"}))}var bb;function Ic(a,b){var c=0;a&&(c|=365);b&&(c|=146);return c}function Jc(a,b){a="string"===typeof a?a:qc(a);for(b=b.split("/").reverse();b.length;){var c=b.pop();if(c){var d=Sb(a+"/"+c);try{Ac(d)}catch(e){}a=d}}return d}
function Kc(a,b,c,d){a=Sb(("string"===typeof a?a:qc(a))+"/"+b);c=Ic(c,d);return zc(a,(void 0!==c?c:438)&4095|32768,0)}function Lc(a,b,c,d,e,f){a=b?Sb(("string"===typeof a?a:qc(a))+"/"+b):a;d=Ic(d,e);e=zc(a,(void 0!==d?d:438)&4095|32768,0);if(c){if("string"===typeof c){a=Array(c.length);b=0;for(var h=c.length;b<h;++b)a[b]=c.charCodeAt(b);c=a}Dc(e,d|146);a=fb(e,577);Hc(a,c,0,c.length,0,f);Fc(a);Dc(e,d)}return e}
function db(a,b,c,d){a=Sb(("string"===typeof a?a:qc(a))+"/"+b);b=Ic(!!c,!!d);db.hd||(db.hd=64);var e=db.hd++<<8|0;Zb(e,{open:function(f){f.seekable=!1},close:function(){d&&d.buffer&&d.buffer.length&&d(10)},read:function(f,h,l,m){for(var q=0,p=0;p<m;p++){try{var r=c()}catch(u){throw new T(29);}if(void 0===r&&0===q)throw new T(6);if(null===r||void 0===r)break;q++;h[l+p]=r}q&&(f.node.timestamp=Date.now());return q},write:function(f,h,l,m){for(var q=0;q<m;q++)try{d(h[l+q])}catch(p){throw new T(29);}m&&
(f.node.timestamp=Date.now());return q}});return Bc(a,b,e)}function Mc(a){if(!(a.Ud||a.Vd||a.link||a.tb)){if("undefined"!==typeof XMLHttpRequest)throw Error("Lazy loading should have been performed (contents set) in createLazyFile, but it was not. Lazy loading only works in web workers. Use --embed-file or --preload-file in emcc on the main thread.");if(Aa)try{a.tb=ac(Aa(a.url),!0),a.yb=a.tb.length}catch(b){throw new T(29);}else throw Error("Cannot load without read() or XMLHttpRequest.");}}
function Nc(a,b,c,d,e){function f(){this.Oc=!1;this.rc=[]}f.prototype.get=function(p){if(!(p>this.length-1||0>p)){var r=p%this.Zc;return this.tc(p/this.Zc|0)[r]}};f.prototype.ke=function(p){this.tc=p};f.prototype.Xc=function(){var p=new XMLHttpRequest;p.open("HEAD",c,!1);p.send(null);if(!(200<=p.status&&300>p.status||304===p.status))throw Error("Couldn't load "+c+". Status: "+p.status);var r=Number(p.getResponseHeader("Content-length")),u,k=(u=p.getResponseHeader("Accept-Ranges"))&&"bytes"===u;p=
(u=p.getResponseHeader("Content-Encoding"))&&"gzip"===u;var v=1048576;k||(v=r);var z=this;z.ke(function(B){var I=B*v,J=(B+1)*v-1;J=Math.min(J,r-1);if("undefined"===typeof z.rc[B]){var na=z.rc;if(I>J)throw Error("invalid range ("+I+", "+J+") or no bytes requested!");if(J>r-1)throw Error("only "+r+" bytes available! programmer error!");var w=new XMLHttpRequest;w.open("GET",c,!1);r!==v&&w.setRequestHeader("Range","bytes="+I+"-"+J);"undefined"!=typeof Uint8Array&&(w.responseType="arraybuffer");w.overrideMimeType&&
w.overrideMimeType("text/plain; charset=x-user-defined");w.send(null);if(!(200<=w.status&&300>w.status||304===w.status))throw Error("Couldn't load "+c+". Status: "+w.status);I=void 0!==w.response?new Uint8Array(w.response||[]):ac(w.responseText||"",!0);na[B]=I}if("undefined"===typeof z.rc[B])throw Error("doXHR failed!");return z.rc[B]});if(p||!r)v=r=1,v=r=this.tc(0).length,Ca("LazyFiles on gzip forces download of the whole file when length is accessed");this.ud=r;this.td=v;this.Oc=!0};if("undefined"!==
typeof XMLHttpRequest){if(!wa)throw"Cannot do synchronous binary XHRs outside webworkers in modern browsers. Use --embed-file or --preload-file in emcc";var h=new f;Object.defineProperties(h,{length:{get:function(){this.Oc||this.Xc();return this.ud}},Zc:{get:function(){this.Oc||this.Xc();return this.td}}});var l=void 0}else l=c,h=void 0;var m=Kc(a,b,d,e);h?m.tb=h:l&&(m.tb=null,m.url=l);Object.defineProperties(m,{yb:{get:function(){return this.tb.length}}});var q={};Object.keys(m.vb).forEach(function(p){var r=
m.vb[p];q[p]=function(){Mc(m);return r.apply(null,arguments)}});q.read=function(p,r,u,k,v){Mc(m);p=p.node.tb;if(v>=p.length)return 0;k=Math.min(p.length-v,k);if(p.slice)for(var z=0;z<k;z++)r[u+z]=p[v+z];else for(z=0;z<k;z++)r[u+z]=p.get(v+z);return k};m.vb=q;return m}
function Oc(a,b,c,d,e,f,h,l,m,q){function p(k){function v(B){q&&q();l||Lc(a,b,B,d,e,m);f&&f();nb(u)}var z=!1;D.preloadPlugins.forEach(function(B){!z&&B.canHandle(r)&&(B.handle(k,r,v,function(){h&&h();nb(u)}),z=!0)});z||v(k)}Pc.Me();var r=b?Wb(Sb(a+"/"+b)):a,u="cp "+r;mb(u);"string"==typeof c?Pc.Ce(c,function(k){p(k)},h):p(c)}var V={},xc,Ec,Qc={};
function Rc(a,b){try{var c=oc(a,{sc:!0}).node;if(!c)throw new T(44);if(!c.ub.Mb)throw new T(63);var d=c.ub.Mb(c)}catch(e){if(e&&e.node&&Sb(a)!==Sb(qc(e.node)))return-54;throw e;}A()[b>>2]=d.Fd;A()[b+4>>2]=0;A()[b+8>>2]=d.Mc;A()[b+12>>2]=d.mode;A()[b+16>>2]=d.be;A()[b+20>>2]=d.uid;A()[b+24>>2]=d.Od;A()[b+28>>2]=d.ic;A()[b+32>>2]=0;sb=[d.size>>>0,(P=d.size,1<=+Math.abs(P)?0<P?(Math.min(+Math.floor(P/4294967296),4294967295)|0)>>>0:~~+Math.ceil((P-+(~~P>>>0))/4294967296)>>>0:0)];A()[b+40>>2]=sb[0];A()[b+
44>>2]=sb[1];A()[b+48>>2]=4096;A()[b+52>>2]=d.zd;A()[b+56>>2]=d.xd.getTime()/1E3|0;A()[b+60>>2]=0;A()[b+64>>2]=d.ae.getTime()/1E3|0;A()[b+68>>2]=0;A()[b+72>>2]=d.Dd.getTime()/1E3|0;A()[b+76>>2]=0;sb=[d.Mc>>>0,(P=d.Mc,1<=+Math.abs(P)?0<P?(Math.min(+Math.floor(P/4294967296),4294967295)|0)>>>0:~~+Math.ceil((P-+(~~P>>>0))/4294967296)>>>0:0)];A()[b+80>>2]=sb[0];A()[b+84>>2]=sb[1];return 0}var Sc=void 0;function Tc(){Sc+=4;return A()[Sc-4>>2]}function Uc(a){a=kc[a];if(!a)throw new T(8);return a}
function Vc(a,b,c){if(F)return S(3,1,a,b,c);Sc=c;try{var d=Uc(a);switch(b){case 0:var e=Tc();return 0>e?-28:fb(d.path,d.flags,0,e).Lb;case 1:case 2:return 0;case 3:return d.flags;case 4:return e=Tc(),d.flags|=e,0;case 12:return e=Tc(),da()[e+0>>1]=2,0;case 13:case 14:return 0;case 16:case 8:return-28;case 9:return-1;default:return-28}}catch(f){return"undefined"!==typeof V&&f instanceof T||H(f),-f.Bb}}
function Wc(a,b){if(F)return S(4,1,a,b);try{var c=Uc(a);return Rc(c.path,b)}catch(d){return"undefined"!==typeof V&&d instanceof T||H(d),-d.Bb}}
function Xc(a,b,c){if(F)return S(5,1,a,b,c);Sc=c;try{var d=Uc(a);switch(b){case 21509:case 21505:return d.zb?0:-59;case 21510:case 21511:case 21512:case 21506:case 21507:case 21508:return d.zb?0:-59;case 21519:if(!d.zb)return-59;var e=Tc();return A()[e>>2]=0;case 21520:return d.zb?-28:-59;case 21531:a=e=Tc();if(!d.vb.Td)throw new T(59);return d.vb.Td(d,b,a);case 21523:return d.zb?0:-59;case 21524:return d.zb?0:-59;default:H("bad ioctl syscall "+b)}}catch(f){return"undefined"!==typeof V&&f instanceof
T||H(f),-f.Bb}}
function Yc(a,b,c,d,e,f){if(F)return S(6,1,a,b,c,d,e,f);try{a:{f<<=12;var h=!1;if(0!==(d&16)&&0!==a%65536)var l=-28;else{if(0!==(d&32)){var m=Zc(65536,b);if(!m){l=-48;break a}$c(m,0,b);h=!0}else{var q=kc[e];if(!q){l=-8;break a}var p=f;if(0!==(c&2)&&0===(d&2)&&2!==(q.flags&2097155))throw new T(2);if(1===(q.flags&2097155))throw new T(2);if(!q.vb.xc)throw new T(43);var r=q.vb.xc(q,a,b,p,c,d);m=r.xb;h=r.Hc}Qc[m]={Zd:m,Xd:b,Hc:h,Lb:e,de:c,flags:d,offset:f};l=m}}return l}catch(u){return"undefined"!==typeof V&&
u instanceof T||H(u),-u.Bb}}function ad(a,b){if(F)return S(7,1,a,b);try{if(-1===(a|0)||0===b)var c=-28;else{var d=Qc[a];if(d&&b===d.Xd){var e=kc[d.Lb];if(e&&d.de&2){var f=d.flags,h=d.offset,l=x().slice(a,a+b);e&&e.vb.yc&&e.vb.yc(e,l,h,b,f)}Qc[a]=null;d.Hc&&R(d.Zd)}c=0}return c}catch(m){return"undefined"!==typeof V&&m instanceof T||H(m),-m.Bb}}
function bd(a,b,c){if(F)return S(8,1,a,b,c);Sc=c;try{var d=K(a),e=c?Tc():0;return fb(d,b,e).Lb}catch(f){return"undefined"!==typeof V&&f instanceof T||H(f),-f.Bb}}function cd(a,b){if(F)return S(9,1,a,b);try{return a=K(a),Rc(a,b)}catch(c){return"undefined"!==typeof V&&c instanceof T||H(c),-c.Bb}}var dd={};function ed(a){for(;a.length;){var b=a.pop();a.pop()(b)}}function fd(a){return this.fromWireType(C()[a>>2])}var gd={},hd={},jd={};
function kd(a){if(void 0===a)return"_unknown";a=a.replace(/[^a-zA-Z0-9_]/g,"$");var b=a.charCodeAt(0);return 48<=b&&57>=b?"_"+a:a}function ld(a,b){a=kd(a);return(new Function("body","return function "+a+'() {\n    "use strict";    return body.apply(this, arguments);\n};\n'))(b)}
function md(a){var b=Error,c=ld(a,function(d){this.name=a;this.message=d;d=Error(d).stack;void 0!==d&&(this.stack=this.toString()+"\n"+d.replace(/^Error(:[^\n]*)?\n/,""))});c.prototype=Object.create(b.prototype);c.prototype.constructor=c;c.prototype.toString=function(){return void 0===this.message?this.name:this.name+": "+this.message};return c}var nd=void 0;function od(a){throw new nd(a);}
function pd(a,b,c){function d(l){l=c(l);l.length!==a.length&&od("Mismatched type converter count");for(var m=0;m<a.length;++m)qd(a[m],l[m])}a.forEach(function(l){jd[l]=b});var e=Array(b.length),f=[],h=0;b.forEach(function(l,m){hd.hasOwnProperty(l)?e[m]=hd[l]:(f.push(l),gd.hasOwnProperty(l)||(gd[l]=[]),gd[l].push(function(){e[m]=hd[l];++h;h===f.length&&d(e)}))});0===f.length&&d(e)}
function rd(a){switch(a){case 1:return 0;case 2:return 1;case 4:return 2;case 8:return 3;default:throw new TypeError("Unknown type size: "+a);}}var sd=void 0;function W(a){for(var b="";x()[a];)b+=sd[x()[a++]];return b}var td=void 0;function X(a){throw new td(a);}
function qd(a,b,c){c=c||{};if(!("argPackAdvance"in b))throw new TypeError("registerType registeredInstance requires argPackAdvance");var d=b.name;a||X('type "'+d+'" must have a positive integer typeid pointer');if(hd.hasOwnProperty(a)){if(c.Pd)return;X("Cannot register type '"+d+"' twice")}hd[a]=b;delete jd[a];gd.hasOwnProperty(a)&&(b=gd[a],delete gd[a],b.forEach(function(e){e()}))}function ud(a){X(a.sb.Ab.wb.name+" instance already deleted")}var vd=!1;function wd(){}
function xd(a){--a.count.value;0===a.count.value&&(a.Gb?a.Ib.Rb(a.Gb):a.Ab.wb.Rb(a.xb))}function yd(a){if("undefined"===typeof FinalizationGroup)return yd=function(b){return b},a;vd=new FinalizationGroup(function(b){for(var c=b.next();!c.done;c=b.next())c=c.value,c.xb?xd(c):console.warn("object already deleted: "+c.xb)});yd=function(b){vd.register(b,b.sb,b.sb);return b};wd=function(b){vd.unregister(b.sb)};return yd(a)}var zd=void 0,Ad=[];
function Bd(){for(;Ad.length;){var a=Ad.pop();a.sb.Yb=!1;a["delete"]()}}function Cd(){}var Dd={};function Ed(a,b,c){if(void 0===a[b].Db){var d=a[b];a[b]=function(){a[b].Db.hasOwnProperty(arguments.length)||X("Function '"+c+"' called with an invalid number of arguments ("+arguments.length+") - expects one of ("+a[b].Db+")!");return a[b].Db[arguments.length].apply(this,arguments)};a[b].Db=[];a[b].Db[d.pc]=d}}
function Fd(a,b,c){D.hasOwnProperty(a)?((void 0===c||void 0!==D[a].Db&&void 0!==D[a].Db[c])&&X("Cannot register public name '"+a+"' twice"),Ed(D,a,a),D.hasOwnProperty(c)&&X("Cannot register multiple overloads of a function with the same number of arguments ("+c+")!"),D[a].Db[c]=b):(D[a]=b,void 0!==c&&(D[a].Qe=c))}function Gd(a,b,c,d,e,f,h,l){this.name=a;this.constructor=b;this.Zb=c;this.Rb=d;this.Jb=e;this.Jd=f;this.mc=h;this.Gd=l;this.ee=[]}
function Hd(a,b,c){for(;b!==c;)b.mc||X("Expected null or instance of "+c.name+", got an instance of "+b.name),a=b.mc(a),b=b.Jb;return a}function Id(a,b){if(null===b)return this.Nc&&X("null is not a valid "+this.name),0;b.sb||X('Cannot pass "'+Jd(b)+'" as a '+this.name);b.sb.xb||X("Cannot pass deleted object as a pointer of type "+this.name);return Hd(b.sb.xb,b.sb.Ab.wb,this.wb)}
function Kd(a,b){if(null===b){this.Nc&&X("null is not a valid "+this.name);if(this.vc){var c=this.Rc();null!==a&&a.push(this.Rb,c);return c}return 0}b.sb||X('Cannot pass "'+Jd(b)+'" as a '+this.name);b.sb.xb||X("Cannot pass deleted object as a pointer of type "+this.name);!this.uc&&b.sb.Ab.uc&&X("Cannot convert argument of type "+(b.sb.Ib?b.sb.Ib.name:b.sb.Ab.name)+" to parameter type "+this.name);c=Hd(b.sb.xb,b.sb.Ab.wb,this.wb);if(this.vc)switch(void 0===b.sb.Gb&&X("Passing raw pointer to smart pointer is illegal"),
this.qe){case 0:b.sb.Ib===this?c=b.sb.Gb:X("Cannot convert argument of type "+(b.sb.Ib?b.sb.Ib.name:b.sb.Ab.name)+" to parameter type "+this.name);break;case 1:c=b.sb.Gb;break;case 2:if(b.sb.Ib===this)c=b.sb.Gb;else{var d=b.clone();c=this.fe(c,Y(function(){d["delete"]()}));null!==a&&a.push(this.Rb,c)}break;default:X("Unsupporting sharing policy")}return c}
function Ld(a,b){if(null===b)return this.Nc&&X("null is not a valid "+this.name),0;b.sb||X('Cannot pass "'+Jd(b)+'" as a '+this.name);b.sb.xb||X("Cannot pass deleted object as a pointer of type "+this.name);b.sb.Ab.uc&&X("Cannot convert argument of type "+b.sb.Ab.name+" to parameter type "+this.name);return Hd(b.sb.xb,b.sb.Ab.wb,this.wb)}function Md(a,b,c){if(b===c)return a;if(void 0===c.Jb)return null;a=Md(a,b,c.Jb);return null===a?null:c.Gd(a)}var Nd={};
function Od(a,b){for(void 0===b&&X("ptr should not be undefined");a.Jb;)b=a.mc(b),a=a.Jb;return Nd[b]}function Pd(a,b){b.Ab&&b.xb||od("makeClassHandle requires ptr and ptrType");!!b.Ib!==!!b.Gb&&od("Both smartPtrType and smartPtr must be specified");b.count={value:1};return yd(Object.create(a,{sb:{value:b}}))}
function Qd(a,b,c,d){this.name=a;this.wb=b;this.Nc=c;this.uc=d;this.vc=!1;this.Rb=this.fe=this.Rc=this.nd=this.qe=this.ce=void 0;void 0!==b.Jb?this.toWireType=Kd:(this.toWireType=d?Id:Ld,this.Kb=null)}function Rd(a,b,c){D.hasOwnProperty(a)||od("Replacing nonexistant public symbol");void 0!==D[a].Db&&void 0!==c?D[a].Db[c]=b:(D[a]=b,D[a].pc=c)}
function Sd(a,b){var c=[];return function(){c.length=arguments.length;for(var d=0;d<arguments.length;d++)c[d]=arguments[d];a.includes("j")?(d=D["dynCall_"+a],d=c&&c.length?d.apply(null,[b].concat(c)):d.call(null,b)):d=O.get(b).apply(null,c);return d}}function Td(a,b){a=W(a);var c=a.includes("j")?Sd(a,b):O.get(b);"function"!==typeof c&&X("unknown function pointer with signature "+a+": "+b);return c}var Ud=void 0;function Vd(a){a=Wd(a);var b=W(a);R(a);return b}
function Xd(a,b){function c(f){e[f]||hd[f]||(jd[f]?jd[f].forEach(c):(d.push(f),e[f]=!0))}var d=[],e={};b.forEach(c);throw new Ud(a+": "+d.map(Vd).join([", "]));}function Yd(a,b){for(var c=[],d=0;d<a;d++)c.push(A()[(b>>2)+d]);return c}
function Zd(a){var b=Function;if(!(b instanceof Function))throw new TypeError("new_ called with constructor type "+typeof b+" which is not a function");var c=ld(b.name||"unknownFunctionName",function(){});c.prototype=b.prototype;c=new c;a=b.apply(c,a);return a instanceof Object?a:c}
function $d(a,b,c,d,e){var f=b.length;2>f&&X("argTypes array size mismatch! Must at least get return value and 'this' types!");var h=null!==b[1]&&null!==c,l=!1;for(c=1;c<b.length;++c)if(null!==b[c]&&void 0===b[c].Kb){l=!0;break}var m="void"!==b[0].name,q="",p="";for(c=0;c<f-2;++c)q+=(0!==c?", ":"")+"arg"+c,p+=(0!==c?", ":"")+"arg"+c+"Wired";a="return function "+kd(a)+"("+q+") {\nif (arguments.length !== "+(f-2)+") {\nthrowBindingError('function "+a+" called with ' + arguments.length + ' arguments, expected "+
(f-2)+" args!');\n}\n";l&&(a+="var destructors = [];\n");var r=l?"destructors":"null";q="throwBindingError invoker fn runDestructors retType classParam".split(" ");d=[X,d,e,ed,b[0],b[1]];h&&(a+="var thisWired = classParam.toWireType("+r+", this);\n");for(c=0;c<f-2;++c)a+="var arg"+c+"Wired = argType"+c+".toWireType("+r+", arg"+c+"); // "+b[c+2].name+"\n",q.push("argType"+c),d.push(b[c+2]);h&&(p="thisWired"+(0<p.length?", ":"")+p);a+=(m?"var rv = ":"")+"invoker(fn"+(0<p.length?", ":"")+p+");\n";if(l)a+=
"runDestructors(destructors);\n";else for(c=h?1:2;c<b.length;++c)f=1===c?"thisWired":"arg"+(c-2)+"Wired",null!==b[c].Kb&&(a+=f+"_dtor("+f+"); // "+b[c].name+"\n",q.push(f+"_dtor"),d.push(b[c].Kb));m&&(a+="var ret = retType.fromWireType(rv);\nreturn ret;\n");q.push(a+"}\n");return Zd(q).apply(null,d)}var ae=[],Z=[{},{value:void 0},{value:null},{value:!0},{value:!1}];function be(a){4<a&&0===--Z[a].Tc&&(Z[a]=void 0,ae.push(a))}
function Y(a){switch(a){case void 0:return 1;case null:return 2;case !0:return 3;case !1:return 4;default:var b=ae.length?ae.pop():Z.length;Z[b]={Tc:1,value:a};return b}}function Jd(a){if(null===a)return"null";var b=typeof a;return"object"===b||"array"===b||"function"===b?a.toString():""+a}
function ce(a,b){switch(b){case 2:return function(c){var d=this.fromWireType;n.buffer!=t&&aa(n.buffer);return d.call(this,Wa[c>>2])};case 3:return function(c){return this.fromWireType(ja()[c>>3])};default:throw new TypeError("Unknown float type: "+a);}}
function de(a,b,c){switch(b){case 0:return c?function(d){return g()[d]}:function(d){return x()[d]};case 1:return c?function(d){return da()[d>>1]}:function(d){return y()[d>>1]};case 2:return c?function(d){return A()[d>>2]}:function(d){return C()[d>>2]};default:throw new TypeError("Unknown integer type: "+a);}}function ee(a){a||X("Cannot use deleted val. handle = "+a);return Z[a].value}function fe(a,b){var c=hd[a];void 0===c&&X(b+" has unknown type "+Vd(a));return c}
function ge(a,b){for(var c=Array(a),d=0;d<a;++d)c[d]=fe(A()[(b>>2)+d],"parameter "+d);return c}var he={};function ie(a){var b=he[a];return void 0===b?W(a):b}var je=[];function ke(){return"object"===typeof globalThis?globalThis:Function("return this")()}function le(a){var b=je.length;je.push(a);return b}var me={},ne=[];
function oe(){wa||(Da||(Da={}),Da["Blocking on the main thread is very dangerous, see https://emscripten.org/docs/porting/pthreads.html#blocking-on-the-main-browser-thread"]||(Da["Blocking on the main thread is very dangerous, see https://emscripten.org/docs/porting/pthreads.html#blocking-on-the-main-browser-thread"]=1,E("Blocking on the main thread is very dangerous, see https://emscripten.org/docs/porting/pthreads.html#blocking-on-the-main-browser-thread")))}
function pe(a,b,c){if(0>=a||a>g().length||a&1)return-28;if(va){if(Atomics.load(A(),a>>2)!=b)return-6;var d=performance.now();c=d+c;for(Atomics.exchange(A(),wb>>2,a);;){d=performance.now();if(d>c)return Atomics.exchange(A(),wb>>2,0),-73;d=Atomics.exchange(A(),wb>>2,0);if(0==d)break;Db();if(Atomics.load(A(),a>>2)!=b)return-6;Atomics.exchange(A(),wb>>2,a)}return 0}a=Atomics.wait(A(),a>>2,b,c);if("timed-out"===a)return-73;if("not-equal"===a)return-6;if("ok"===a)return 0;throw"Atomics.wait returned an unexpected value "+
a;}function S(a,b){for(var c=arguments.length-2,d=qe(),e=re(8*c),f=e>>3,h=0;h<c;h++){var l=arguments[2+h];ja()[f+h]=l}c=se(a,c,e,b);Ib(d);return c}var te=[],ue=[0,"undefined"!==typeof document?document:0,"undefined"!==typeof window?window:0];function ve(a){a=2<a?K(a):a;return ue[a]||("undefined"!==typeof document?document.querySelector(a):void 0)}
function we(a,b,c){var d=ve(a);if(!d)return-4;d.qc&&(A()[d.qc>>2]=b,A()[d.qc+4>>2]=c);if(d.kd||!d.Fe)d.kd&&(d=d.kd),a=!1,d.oc&&d.oc.nc&&(a=d.oc.nc.getParameter(2978),a=0===a[0]&&0===a[1]&&a[2]===d.width&&a[3]===d.height),d.width=b,d.height=c,a&&d.oc.nc.viewport(0,0,b,c);else{if(d.qc){d=A()[d.qc+8>>2];a=a?K(a):"";var e=qe(),f=re(12),h=0;if(a){h=Na(a)+1;var l=L(h);Ma(a,l,h);h=l}A()[f>>2]=h;A()[f+4>>2]=b;A()[f+8>>2]=c;xe(0,d,657457152,0,h,f);Ib(e);return 1}return-4}return 0}
function ye(a,b,c){return F?S(10,1,a,b,c):we(a,b,c)}var ze=[];function Ae(a,b){C()[a>>2]=b;C()[a+4>>2]=b/4294967296|0}function Be(a,b){try{var c=indexedDB.open("emscripten_filesystem",1)}catch(d){b(d);return}c.onupgradeneeded=function(d){d=d.target.result;d.objectStoreNames.contains("FILES")&&d.deleteObjectStore("FILES");d.createObjectStore("FILES")};c.onsuccess=function(d){a(d.target.result)};c.onerror=function(d){b(d)}}var Ce;
function De(a,b,c,d,e){function f(M){var N=0,G=0;M&&(G=w.response?w.response.byteLength:0,N=L(G),x().set(new Uint8Array(w.response),N));C()[a+12>>2]=N;Ae(a+16,G)}var h=C()[a+8>>2];if(h){var l=K(h),m=a+112,q=K(m);q||(q="GET");C();var p=C()[m+52>>2],r=C()[m+56>>2],u=!!C()[m+60>>2];C();var k=C()[m+68>>2],v=C()[m+72>>2],z=C()[m+76>>2],B=C()[m+80>>2];h=C()[m+84>>2];m=C()[m+88>>2];var I=!!(p&1),J=!!(p&2);p=!!(p&64);k=k?K(k):void 0;v=v?K(v):void 0;var na=B?K(B):void 0,w=new XMLHttpRequest;w.withCredentials=
u;w.open(q,l,!p,k,v);p||(w.timeout=r);w.We=l;w.responseType="arraybuffer";B&&w.overrideMimeType(na);if(z)for(;;){q=C()[z>>2];if(!q)break;l=C()[z+4>>2];if(!l)break;z+=8;q=K(q);l=K(l);w.setRequestHeader(q,l)}ze.push(w);z=ze.length;C()[a+0>>2]=z;h=h&&m?x().slice(h,h+m):null;w.onload=function(M){f(I&&!J);var N=w.response?w.response.byteLength:0;Ae(a+24,0);N&&Ae(a+32,N);y()[a+40>>1]=w.readyState;y()[a+42>>1]=w.status;w.statusText&&Ma(w.statusText,a+44,64);200<=w.status&&300>w.status?b&&b(a,w,M):c&&c(a,
w,M)};w.onerror=function(M){f(I);var N=w.status;Ae(a+24,0);Ae(a+32,w.response?w.response.byteLength:0);y()[a+40>>1]=w.readyState;y()[a+42>>1]=N;c&&c(a,w,M)};w.ontimeout=function(M){c&&c(a,w,M)};w.onprogress=function(M){var N=I&&J&&w.response?w.response.byteLength:0,G=0;I&&J&&(G=L(N),x().set(new Uint8Array(w.response),G));C()[a+12>>2]=G;Ae(a+16,N);Ae(a+24,M.loaded-N);Ae(a+32,M.total);y()[a+40>>1]=w.readyState;3<=w.readyState&&0===w.status&&0<M.loaded&&(w.status=200);y()[a+42>>1]=w.status;w.statusText&&
Ma(w.statusText,a+44,64);d&&d(a,w,M);G&&R(G)};w.onreadystatechange=function(M){y()[a+40>>1]=w.readyState;2<=w.readyState&&(y()[a+42>>1]=w.status);e&&e(a,w,M)};try{w.send(h)}catch(M){c&&c(a,w,M)}}else c(a,0,"no url specified!")}
function Ee(a,b){if(!Ha)if(b)a();else{try{a()}catch(c){if(c instanceof Gb)return;if("unwind"!==c)throw c&&"object"===typeof c&&c.stack&&E("exception thrown: "+[c,c.stack]),c;}if(F&&!Kb())try{if(F)throw a=Ia,F?Q.sd(a):Fb(a),xa&&process.He(a),"unwind";Fb(Ia)}catch(c){if(!(c instanceof Gb))throw c;}}}
function Fe(a,b,c,d){var e=Ce;if(e){var f=a+112;(f=C()[f+64>>2])||(f=C()[a+8>>2]);var h=K(f);try{var l=e.transaction(["FILES"],"readwrite").objectStore("FILES").put(b,h);l.onsuccess=function(){y()[a+40>>1]=4;y()[a+42>>1]=200;Ma("OK",a+44,64);c(a,0,h)};l.onerror=function(m){y()[a+40>>1]=4;y()[a+42>>1]=413;Ma("Payload Too Large",a+44,64);d(a,0,m)}}catch(m){d(a,0,m)}}else d(a,0,"IndexedDB not available!")}
function Ge(a,b,c){var d=Ce;if(d){var e=a+112;(e=C()[e+64>>2])||(e=C()[a+8>>2]);e=K(e);try{var f=d.transaction(["FILES"],"readonly").objectStore("FILES").get(e);f.onsuccess=function(h){if(h.target.result){h=h.target.result;var l=h.byteLength||h.length,m=L(l);x().set(new Uint8Array(h),m);C()[a+12>>2]=m;Ae(a+16,l);Ae(a+24,0);Ae(a+32,l);y()[a+40>>1]=4;y()[a+42>>1]=200;Ma("OK",a+44,64);b(a,0,h)}else y()[a+40>>1]=4,y()[a+42>>1]=404,Ma("Not Found",a+44,64),c(a,0,"no data")};f.onerror=function(h){y()[a+
40>>1]=4;y()[a+42>>1]=404;Ma("Not Found",a+44,64);c(a,0,h)}}catch(h){c(a,0,h)}}else c(a,0,"IndexedDB not available!")}
function He(a,b,c){var d=Ce;if(d){var e=a+112;(e=C()[e+64>>2])||(e=C()[a+8>>2]);e=K(e);try{var f=d.transaction(["FILES"],"readwrite").objectStore("FILES").delete(e);f.onsuccess=function(h){h=h.target.result;C()[a+12>>2]=0;Ae(a+16,0);Ae(a+24,0);Ae(a+32,0);y()[a+40>>1]=4;y()[a+42>>1]=200;Ma("OK",a+44,64);b(a,0,h)};f.onerror=function(h){y()[a+40>>1]=4;y()[a+42>>1]=404;Ma("Not Found",a+44,64);c(a,0,h)}}catch(h){c(a,0,h)}}else c(a,0,"IndexedDB not available!")}
function Ie(a){var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=function(c,d){b.vertexAttribDivisorANGLE(c,d)},a.drawArraysInstanced=function(c,d,e,f){b.drawArraysInstancedANGLE(c,d,e,f)},a.drawElementsInstanced=function(c,d,e,f,h){b.drawElementsInstancedANGLE(c,d,e,f,h)})}
function Je(a){var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=function(){return b.createVertexArrayOES()},a.deleteVertexArray=function(c){b.deleteVertexArrayOES(c)},a.bindVertexArray=function(c){b.bindVertexArrayOES(c)},a.isVertexArray=function(c){return b.isVertexArrayOES(c)})}function Ke(a){var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=function(c,d){b.drawBuffersWEBGL(c,d)})}
function Le(a,b){a.fd||(a.fd=a.getContext,a.getContext=function(d,e){e=a.fd(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null});var c=a.getContext("webgl",b);return c?Me(c,b):0}function Me(a,b){var c=L(8);A()[c+4>>2]=Ab();var d={Le:c,attributes:b,version:b.Yd,nc:a};a.canvas&&(a.canvas.oc=d);("undefined"===typeof b.bd||b.bd)&&Ne(d);return c}
function Ne(a){a||(a=Oe);if(!a.Qd){a.Qd=!0;var b=a.nc;Ie(b);Je(b);Ke(b);b.Ge=b.getExtension("EXT_disjoint_timer_query");b.Pe=b.getExtension("WEBGL_multi_draw");(b.getSupportedExtensions()||[]).forEach(function(c){c.includes("lose_context")||c.includes("debug")||b.getExtension(c)})}}var Oe,Pe=["default","low-power","high-performance"],Qe={};
function Re(){if(!Se){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"===typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:ta||"./this.program"},b;for(b in Qe)a[b]=Qe[b];var c=[];for(b in a)c.push(b+"="+a[b]);Se=c}return Se}var Se;
function Te(a,b){if(F)return S(11,1,a,b);try{var c=0;Re().forEach(function(d,e){var f=b+c;e=A()[a+4*e>>2]=f;for(f=0;f<d.length;++f)g()[e++>>0]=d.charCodeAt(f);g()[e>>0]=0;c+=d.length+1});return 0}catch(d){return"undefined"!==typeof V&&d instanceof T||H(d),d.Bb}}function Ue(a,b){if(F)return S(12,1,a,b);try{var c=Re();A()[a>>2]=c.length;var d=0;c.forEach(function(e){d+=e.length+1});A()[b>>2]=d;return 0}catch(e){return"undefined"!==typeof V&&e instanceof T||H(e),e.Bb}}
function Ve(a){if(F)return S(13,1,a);try{var b=Uc(a);Fc(b);return 0}catch(c){return"undefined"!==typeof V&&c instanceof T||H(c),c.Bb}}function We(a,b){if(F)return S(14,1,a,b);try{var c=Uc(a),d=c.zb?2:fc(c.mode)?3:40960===(c.mode&61440)?7:4;g()[b>>0]=d;return 0}catch(e){return"undefined"!==typeof V&&e instanceof T||H(e),e.Bb}}
function Xe(a,b,c,d){if(F)return S(15,1,a,b,c,d);try{a:{for(var e=Uc(a),f=a=0;f<c;f++){var h=A()[b+8*f>>2],l=A()[b+(8*f+4)>>2],m=e,q=g(),p=h,r=l,u=void 0;if(0>r||0>u)throw new T(28);if(null===m.Lb)throw new T(8);if(1===(m.flags&2097155))throw new T(8);if(fc(m.node.mode))throw new T(31);if(!m.vb.read)throw new T(28);var k="undefined"!==typeof u;if(!k)u=m.position;else if(!m.seekable)throw new T(70);var v=m.vb.read(m,q,p,r,u);k||(m.position+=v);var z=v;if(0>z){var B=-1;break a}a+=z;if(z<l)break}B=a}A()[d>>
2]=B;return 0}catch(I){return"undefined"!==typeof V&&I instanceof T||H(I),I.Bb}}
function Ye(a,b,c,d,e){if(F)return S(16,1,a,b,c,d,e);try{var f=Uc(a);a=4294967296*c+(b>>>0);if(-9007199254740992>=a||9007199254740992<=a)return-61;Gc(f,a,d);sb=[f.position>>>0,(P=f.position,1<=+Math.abs(P)?0<P?(Math.min(+Math.floor(P/4294967296),4294967295)|0)>>>0:~~+Math.ceil((P-+(~~P>>>0))/4294967296)>>>0:0)];A()[e>>2]=sb[0];A()[e+4>>2]=sb[1];f.Lc&&0===a&&0===d&&(f.Lc=null);return 0}catch(h){return"undefined"!==typeof V&&h instanceof T||H(h),h.Bb}}
function Ze(a,b,c,d){if(F)return S(17,1,a,b,c,d);try{a:{for(var e=Uc(a),f=a=0;f<c;f++){var h=A()[b+8*f>>2],l=A()[b+(8*f+4)>>2],m=Hc(e,g(),h,l,void 0);if(0>m){var q=-1;break a}a+=m}q=a}A()[d>>2]=q;return 0}catch(p){return"undefined"!==typeof V&&p instanceof T||H(p),p.Bb}}function $e(a,b){$e.md||($e.md=Vb());for(var c=0;c<b;c++)g()[a+c>>0]=$e.md();return 0}
function Eb(a){if(F)throw"Internal Error! spawnThread() can only ever be called from main application thread!";var b=Q.Kd();if(!b)return 6;if(void 0!==b.Hb)throw"Internal error!";if(!a.zc)throw"Internal error, no pthread ptr!";Q.Sb.push(b);for(var c=L(512),d=0;128>d;++d)A()[c+4*d>>2]=0;var e=a.Wb+a.bc;d=Q.Ob[a.zc]={worker:b,Wb:a.Wb,bc:a.bc,Ic:a.Ic,Pb:a.zc};var f=d.Pb>>2;Atomics.store(C(),f+16,a.ad);Atomics.store(C(),f+25,c);Atomics.store(C(),f+10,d.Pb);Atomics.store(C(),f+20,a.bc);Atomics.store(C(),
f+19,e);Atomics.store(C(),f+26,a.bc);Atomics.store(C(),f+28,e);Atomics.store(C(),f+29,a.ad);c=af()+40;Atomics.store(C(),f+43,c);b.Hb=d;var h={cmd:"run",start_routine:a.re,arg:a.dc,threadInfoStruct:a.zc,stackBase:a.Wb,stackSize:a.bc};b.kc=function(){h.time=performance.now();b.postMessage(h,a.ze)};b.loaded&&(b.kc(),delete b.kc);return 0}
function bf(a,b){if(!a)return E("pthread_join attempted on a null thread pointer!"),71;if(F&&Ab()==a)return E("PThread "+a+" is attempting to join to itself!"),16;if(!F&&cf()==a)return E("Main thread "+a+" is attempting to join to itself!"),16;if(A()[a+12>>2]!==a)return E("pthread_join attempted on thread "+a+", which does not point to a valid thread, or does not exist anymore!"),71;if(Atomics.load(C(),a+64>>2))return E("Attempted to join thread "+a+", which was already detached!"),28;for(oe();;){var c=
Atomics.load(C(),a+0>>2);if(1==c)return c=Atomics.load(C(),a+4>>2),b&&(A()[b>>2]=c),Atomics.store(C(),a+64>>2,1),F?postMessage({cmd:"cleanupThread",thread:a}):xb(a),0;if(F){var d=Ab();if(d&&!Atomics.load(C(),d+56>>2)&&2==Atomics.load(C(),d+0>>2))throw"Canceled!";}F||Db();pe(a+0,c,F?100:1)}}function df(a){return 0===a%4&&(0!==a%100||0===a%400)}function ef(a,b){for(var c=0,d=0;d<=b;c+=a[d++]);return c}var ff=[31,29,31,30,31,30,31,31,30,31,30,31],gf=[31,28,31,30,31,30,31,31,30,31,30,31];
function hf(a,b){for(a=new Date(a.getTime());0<b;){var c=a.getMonth(),d=(df(a.getFullYear())?ff:gf)[c];if(b>d-a.getDate())b-=d-a.getDate()+1,a.setDate(1),11>c?a.setMonth(c+1):(a.setMonth(0),a.setFullYear(a.getFullYear()+1));else{a.setDate(a.getDate()+b);break}}return a}
function jf(a,b,c,d){function e(k,v,z){for(k="number"===typeof k?k.toString():k||"";k.length<v;)k=z[0]+k;return k}function f(k,v){return e(k,v,"0")}function h(k,v){function z(I){return 0>I?-1:0<I?1:0}var B;0===(B=z(k.getFullYear()-v.getFullYear()))&&0===(B=z(k.getMonth()-v.getMonth()))&&(B=z(k.getDate()-v.getDate()));return B}function l(k){switch(k.getDay()){case 0:return new Date(k.getFullYear()-1,11,29);case 1:return k;case 2:return new Date(k.getFullYear(),0,3);case 3:return new Date(k.getFullYear(),
0,2);case 4:return new Date(k.getFullYear(),0,1);case 5:return new Date(k.getFullYear()-1,11,31);case 6:return new Date(k.getFullYear()-1,11,30)}}function m(k){k=hf(new Date(k.Eb+1900,0,1),k.Fc);var v=new Date(k.getFullYear()+1,0,4),z=l(new Date(k.getFullYear(),0,4));v=l(v);return 0>=h(z,k)?0>=h(v,k)?k.getFullYear()+1:k.getFullYear():k.getFullYear()-1}var q=A()[d+40>>2];d={xe:A()[d>>2],we:A()[d+4>>2],Dc:A()[d+8>>2],lc:A()[d+12>>2],cc:A()[d+16>>2],Eb:A()[d+20>>2],Ec:A()[d+24>>2],Fc:A()[d+28>>2],Ve:A()[d+
32>>2],ve:A()[d+36>>2],ye:q?K(q):""};c=K(c);q={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S","%x":"%m/%d/%y","%X":"%H:%M:%S","%Ec":"%c","%EC":"%C","%Ex":"%m/%d/%y","%EX":"%H:%M:%S","%Ey":"%y","%EY":"%Y","%Od":"%d","%Oe":"%e","%OH":"%H","%OI":"%I","%Om":"%m","%OM":"%M","%OS":"%S","%Ou":"%u","%OU":"%U","%OV":"%V","%Ow":"%w","%OW":"%W","%Oy":"%y"};for(var p in q)c=c.replace(new RegExp(p,"g"),q[p]);var r="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),
u="January February March April May June July August September October November December".split(" ");q={"%a":function(k){return r[k.Ec].substring(0,3)},"%A":function(k){return r[k.Ec]},"%b":function(k){return u[k.cc].substring(0,3)},"%B":function(k){return u[k.cc]},"%C":function(k){return f((k.Eb+1900)/100|0,2)},"%d":function(k){return f(k.lc,2)},"%e":function(k){return e(k.lc,2," ")},"%g":function(k){return m(k).toString().substring(2)},"%G":function(k){return m(k)},"%H":function(k){return f(k.Dc,
2)},"%I":function(k){k=k.Dc;0==k?k=12:12<k&&(k-=12);return f(k,2)},"%j":function(k){return f(k.lc+ef(df(k.Eb+1900)?ff:gf,k.cc-1),3)},"%m":function(k){return f(k.cc+1,2)},"%M":function(k){return f(k.we,2)},"%n":function(){return"\n"},"%p":function(k){return 0<=k.Dc&&12>k.Dc?"AM":"PM"},"%S":function(k){return f(k.xe,2)},"%t":function(){return"\t"},"%u":function(k){return k.Ec||7},"%U":function(k){var v=new Date(k.Eb+1900,0,1),z=0===v.getDay()?v:hf(v,7-v.getDay());k=new Date(k.Eb+1900,k.cc,k.lc);return 0>
h(z,k)?f(Math.ceil((31-z.getDate()+(ef(df(k.getFullYear())?ff:gf,k.getMonth()-1)-31)+k.getDate())/7),2):0===h(z,v)?"01":"00"},"%V":function(k){var v=new Date(k.Eb+1901,0,4),z=l(new Date(k.Eb+1900,0,4));v=l(v);var B=hf(new Date(k.Eb+1900,0,1),k.Fc);return 0>h(B,z)?"53":0>=h(v,B)?"01":f(Math.ceil((z.getFullYear()<k.Eb+1900?k.Fc+32-z.getDate():k.Fc+1-z.getDate())/7),2)},"%w":function(k){return k.Ec},"%W":function(k){var v=new Date(k.Eb,0,1),z=1===v.getDay()?v:hf(v,0===v.getDay()?1:7-v.getDay()+1);k=
new Date(k.Eb+1900,k.cc,k.lc);return 0>h(z,k)?f(Math.ceil((31-z.getDate()+(ef(df(k.getFullYear())?ff:gf,k.getMonth()-1)-31)+k.getDate())/7),2):0===h(z,v)?"01":"00"},"%y":function(k){return(k.Eb+1900).toString().substring(2)},"%Y":function(k){return k.Eb+1900},"%z":function(k){k=k.ve;var v=0<=k;k=Math.abs(k)/60;return(v?"+":"-")+String("0000"+(k/60*100+k%60)).slice(-4)},"%Z":function(k){return k.ye},"%%":function(){return"%"}};for(p in q)c.includes(p)&&(c=c.replace(new RegExp(p,"g"),q[p](d)));p=ac(c,
!1);if(p.length>b)return 0;Va(p,a);return p.length-1}function sc(a,b,c,d){a||(a=this);this.parent=a;this.Qb=a.Qb;this.fc=null;this.id=lc++;this.name=b;this.mode=c;this.ub={};this.vb={};this.ic=d}
Object.defineProperties(sc.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}},Vd:{get:function(){return fc(this.mode)}},Ud:{get:function(){return 8192===(this.mode&61440)}}});cb();mc=Array(4096);yc(U,"/");Ac("/tmp");Ac("/home");Ac("/home/web_user");
(function(){Ac("/dev");Zb(259,{read:function(){return 0},write:function(b,c,d,e){return e}});Bc("/dev/null",259);Yb(1280,bc);Yb(1536,cc);Bc("/dev/tty",1280);Bc("/dev/tty1",1536);var a=Vb();db("/dev","random",a);db("/dev","urandom",a);Ac("/dev/shm");Ac("/dev/shm/tmp")})();
(function(){Ac("/proc");var a=Ac("/proc/self");Ac("/proc/self/fd");yc({Qb:function(){var b=ec(a,"fd",16895,73);b.ub={ec:function(c,d){var e=kc[+d];if(!e)throw new T(8);c={parent:null,Qb:{jd:"fake"},ub:{jc:function(){return e.path}}};return c.parent=c}};return b}},"/proc/self/fd")})();var Pc;D.FS_createPath=Jc;D.FS_createDataFile=Lc;D.FS_createPreloadedFile=Oc;D.FS_createLazyFile=Nc;D.FS_createDevice=db;D.FS_unlink=Cc;nd=D.InternalError=md("InternalError");
for(var kf=Array(256),lf=0;256>lf;++lf)kf[lf]=String.fromCharCode(lf);sd=kf;td=D.BindingError=md("BindingError");Cd.prototype.isAliasOf=function(a){if(!(this instanceof Cd&&a instanceof Cd))return!1;var b=this.sb.Ab.wb,c=this.sb.xb,d=a.sb.Ab.wb;for(a=a.sb.xb;b.Jb;)c=b.mc(c),b=b.Jb;for(;d.Jb;)a=d.mc(a),d=d.Jb;return b===d&&c===a};
Cd.prototype.clone=function(){this.sb.xb||ud(this);if(this.sb.hc)return this.sb.count.value+=1,this;var a=yd,b=Object,c=b.create,d=Object.getPrototypeOf(this),e=this.sb;a=a(c.call(b,d,{sb:{value:{count:e.count,Yb:e.Yb,hc:e.hc,xb:e.xb,Ab:e.Ab,Gb:e.Gb,Ib:e.Ib}}}));a.sb.count.value+=1;a.sb.Yb=!1;return a};Cd.prototype["delete"]=function(){this.sb.xb||ud(this);this.sb.Yb&&!this.sb.hc&&X("Object already scheduled for deletion");wd(this);xd(this.sb);this.sb.hc||(this.sb.Gb=void 0,this.sb.xb=void 0)};
Cd.prototype.isDeleted=function(){return!this.sb.xb};Cd.prototype.deleteLater=function(){this.sb.xb||ud(this);this.sb.Yb&&!this.sb.hc&&X("Object already scheduled for deletion");Ad.push(this);1===Ad.length&&zd&&zd(Bd);this.sb.Yb=!0;return this};Qd.prototype.Ld=function(a){this.nd&&(a=this.nd(a));return a};Qd.prototype.$c=function(a){this.Rb&&this.Rb(a)};Qd.prototype.argPackAdvance=8;Qd.prototype.readValueFromPointer=fd;Qd.prototype.deleteObject=function(a){if(null!==a)a["delete"]()};
Qd.prototype.fromWireType=function(a){function b(){return this.vc?Pd(this.wb.Zb,{Ab:this.ce,xb:c,Ib:this,Gb:a}):Pd(this.wb.Zb,{Ab:this,xb:a})}var c=this.Ld(a);if(!c)return this.$c(a),null;var d=Od(this.wb,c);if(void 0!==d){if(0===d.sb.count.value)return d.sb.xb=c,d.sb.Gb=a,d.clone();d=d.clone();this.$c(a);return d}d=this.wb.Jd(c);d=Dd[d];if(!d)return b.call(this);d=this.uc?d.Cd:d.pointerType;var e=Md(c,this.wb,d.wb);return null===e?b.call(this):this.vc?Pd(d.wb.Zb,{Ab:d,xb:e,Ib:this,Gb:a}):Pd(d.wb.Zb,
{Ab:d,xb:e})};D.getInheritedInstanceCount=function(){return Object.keys(Nd).length};D.getLiveInheritedInstances=function(){var a=[],b;for(b in Nd)Nd.hasOwnProperty(b)&&a.push(Nd[b]);return a};D.flushPendingDeletes=Bd;D.setDelayFunction=function(a){zd=a;Ad.length&&zd&&zd(Bd)};Ud=D.UnboundTypeError=md("UnboundTypeError");D.count_emval_handles=function(){for(var a=0,b=5;b<Z.length;++b)void 0!==Z[b]&&++a;return a};D.get_first_emval=function(){for(var a=5;a<Z.length;++a)if(void 0!==Z[a])return Z[a];return null};
F||(Be(function(a){Ce=a;nb("library_fetch_init")},function(){Ce=!1;nb("library_fetch_init")}),"undefined"!==typeof ENVIRONMENT_IS_FETCH_WORKER&&ENVIRONMENT_IS_FETCH_WORKER||mb("library_fetch_init"));var mf=[null,function(a,b){if(F)return S(1,1,a,b)},Nb,Vc,Wc,Xc,Yc,ad,bd,cd,ye,Te,Ue,Ve,We,Xe,Ye,Ze];function ac(a,b){var c=Array(Na(a)+1);a=La(a,c,0,c.length);b&&(c.length=a);return c}
var tf={n:function(a,b,c,d){H("Assertion failed: "+K(a)+", at: "+[b?K(b):"unknown filename",c,d?K(d):"unknown function"])},za:function(a,b){return Mb(a,b)},ia:function(a,b){Nb();a=new Date(1E3*A()[a>>2]);A()[b>>2]=a.getSeconds();A()[b+4>>2]=a.getMinutes();A()[b+8>>2]=a.getHours();A()[b+12>>2]=a.getDate();A()[b+16>>2]=a.getMonth();A()[b+20>>2]=a.getFullYear()-1900;A()[b+24>>2]=a.getDay();var c=new Date(a.getFullYear(),0,1),d=(a.getTime()-c.getTime())/864E5|0;A()[b+28>>2]=d;A()[b+36>>2]=-(60*a.getTimezoneOffset());
d=(new Date(a.getFullYear(),6,1)).getTimezoneOffset();c=c.getTimezoneOffset();a=(d!=c&&a.getTimezoneOffset()==Math.min(c,d))|0;A()[b+32>>2]=a;a=A()[Qb()+(a?4:0)>>2];A()[b+40>>2]=a;return b},P:Vc,pa:Wc,ta:Xc,qa:Yc,ra:function(){return 0},sa:ad,Q:bd,oa:cd,c:function(a){var b=dd[a];delete dd[a];var c=b.Rc,d=b.Rb,e=b.dd,f=e.map(function(h){return h.Nd}).concat(e.map(function(h){return h.oe}));pd([a],f,function(h){var l={};e.forEach(function(m,q){var p=h[q],r=m.tc,u=m.Md,k=h[q+e.length],v=m.ne,z=m.pe;
l[m.Id]={read:function(B){return p.fromWireType(r(u,B))},write:function(B,I){var J=[];v(z,B,k.toWireType(J,I));ed(J)}}});return[{name:b.name,fromWireType:function(m){var q={},p;for(p in l)q[p]=l[p].read(m);d(m);return q},toWireType:function(m,q){for(var p in l)if(!(p in q))throw new TypeError('Missing field:  "'+p+'"');var r=c();for(p in l)l[p].write(r,q[p]);null!==m&&m.push(d,r);return r},argPackAdvance:8,readValueFromPointer:fd,Kb:d}]})},_:function(){},xa:function(a,b,c,d,e){var f=rd(c);b=W(b);
qd(a,{name:b,fromWireType:function(h){return!!h},toWireType:function(h,l){return l?d:e},argPackAdvance:8,readValueFromPointer:function(h){if(1===c)var l=g();else if(2===c)l=da();else if(4===c)l=A();else throw new TypeError("Unknown boolean type size: "+b);return this.fromWireType(l[h>>f])},Kb:null})},u:function(a,b,c,d,e,f,h,l,m,q,p,r,u){p=W(p);f=Td(e,f);l&&(l=Td(h,l));q&&(q=Td(m,q));u=Td(r,u);var k=kd(p);Fd(k,function(){Xd("Cannot construct "+p+" due to unbound types",[d])});pd([a,b,c],d?[d]:[],
function(v){v=v[0];if(d){var z=v.wb;var B=z.Zb}else B=Cd.prototype;v=ld(k,function(){if(Object.getPrototypeOf(this)!==I)throw new td("Use 'new' to construct "+p);if(void 0===J.Ub)throw new td(p+" has no accessible constructor");var w=J.Ub[arguments.length];if(void 0===w)throw new td("Tried to invoke ctor of "+p+" with invalid number of parameters ("+arguments.length+") - expected ("+Object.keys(J.Ub).toString()+") parameters instead!");return w.apply(this,arguments)});var I=Object.create(B,{constructor:{value:v}});
v.prototype=I;var J=new Gd(p,v,I,u,z,f,l,q);z=new Qd(p,J,!0,!1);B=new Qd(p+"*",J,!1,!1);var na=new Qd(p+" const*",J,!1,!0);Dd[a]={pointerType:B,Cd:na};Rd(k,v);return[z,B,na]})},v:function(a,b,c,d,e,f){Ja(0<b);var h=Yd(b,c);e=Td(d,e);var l=[f],m=[];pd([],[a],function(q){q=q[0];var p="constructor "+q.name;void 0===q.wb.Ub&&(q.wb.Ub=[]);if(void 0!==q.wb.Ub[b-1])throw new td("Cannot register multiple constructors with identical number of parameters ("+(b-1)+") for class '"+q.name+"'! Overload resolution is currently only performed using the parameter count, not actual type info!");
q.wb.Ub[b-1]=function(){Xd("Cannot construct "+q.name+" due to unbound types",h)};pd([],h,function(r){q.wb.Ub[b-1]=function(){arguments.length!==b-1&&X(p+" called with "+arguments.length+" arguments, expected "+(b-1));m.length=0;l.length=b;for(var u=1;u<b;++u)l[u]=r[u].toWireType(m,arguments[u-1]);u=e.apply(null,l);ed(m);return r[0].fromWireType(u)};return[]});return[]})},f:function(a,b,c,d,e,f,h,l){var m=Yd(c,d);b=W(b);f=Td(e,f);pd([],[a],function(q){function p(){Xd("Cannot call "+r+" due to unbound types",
m)}q=q[0];var r=q.name+"."+b;b.startsWith("@@")&&(b=Symbol[b.substring(2)]);l&&q.wb.ee.push(b);var u=q.wb.Zb,k=u[b];void 0===k||void 0===k.Db&&k.className!==q.name&&k.pc===c-2?(p.pc=c-2,p.className=q.name,u[b]=p):(Ed(u,b,r),u[b].Db[c-2]=p);pd([],m,function(v){v=$d(r,v,q,f,h);void 0===u[b].Db?(v.pc=c-2,u[b]=v):u[b].Db[c-2]=v;return[]});return[]})},wa:function(a,b){b=W(b);qd(a,{name:b,fromWireType:function(c){var d=Z[c].value;be(c);return d},toWireType:function(c,d){return Y(d)},argPackAdvance:8,readValueFromPointer:fd,
Kb:null})},R:function(a,b,c){c=rd(c);b=W(b);qd(a,{name:b,fromWireType:function(d){return d},toWireType:function(d,e){if("number"!==typeof e&&"boolean"!==typeof e)throw new TypeError('Cannot convert "'+Jd(e)+'" to '+this.name);return e},argPackAdvance:8,readValueFromPointer:ce(b,c),Kb:null})},C:function(a,b,c,d,e,f){var h=Yd(b,c);a=W(a);e=Td(d,e);Fd(a,function(){Xd("Cannot call "+a+" due to unbound types",h)},b-1);pd([],h,function(l){Rd(a,$d(a,[l[0],null].concat(l.slice(1)),null,e,f),b-1);return[]})},
j:function(a,b,c,d,e){function f(q){return q}b=W(b);-1===e&&(e=4294967295);var h=rd(c);if(0===d){var l=32-8*c;f=function(q){return q<<l>>>l}}var m=b.includes("unsigned");qd(a,{name:b,fromWireType:f,toWireType:function(q,p){if("number"!==typeof p&&"boolean"!==typeof p)throw new TypeError('Cannot convert "'+Jd(p)+'" to '+this.name);if(p<d||p>e)throw new TypeError('Passing a number "'+Jd(p)+'" from JS side to C/C++ side to an argument of type "'+b+'", which is outside the valid range ['+d+", "+e+"]!");
return m?p>>>0:p|0},argPackAdvance:8,readValueFromPointer:de(b,h,0!==d),Kb:null})},h:function(a,b,c){function d(f){f>>=2;var h=C();return new e(t,h[f+1],h[f])}var e=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array][b];c=W(c);qd(a,{name:c,fromWireType:d,argPackAdvance:8,readValueFromPointer:d},{Pd:!0})},S:function(a,b){b=W(b);var c="std::string"===b;qd(a,{name:b,fromWireType:function(d){var e=C()[d>>2];if(c)for(var f=d+4,h=0;h<=e;++h){var l=d+4+h;if(h==
e||0==x()[l]){f=K(f,l-f);if(void 0===m)var m=f;else m+=String.fromCharCode(0),m+=f;f=l+1}}else{m=Array(e);for(h=0;h<e;++h)m[h]=String.fromCharCode(x()[d+4+h]);m=m.join("")}R(d);return m},toWireType:function(d,e){e instanceof ArrayBuffer&&(e=new Uint8Array(e));var f="string"===typeof e;f||e instanceof Uint8Array||e instanceof Uint8ClampedArray||e instanceof Int8Array||X("Cannot pass non-string to std::string");var h=(c&&f?function(){return Na(e)}:function(){return e.length})(),l=L(4+h+1);C()[l>>2]=
h;if(c&&f)Ma(e,l+4,h+1);else if(f)for(f=0;f<h;++f){var m=e.charCodeAt(f);255<m&&(R(l),X("String has UTF-16 code units that do not fit in 8 bits"));x()[l+4+f]=m}else for(f=0;f<h;++f)x()[l+4+f]=e[f];null!==d&&d.push(R,l);return l},argPackAdvance:8,readValueFromPointer:fd,Kb:function(d){R(d)}})},z:function(a,b,c){c=W(c);if(2===b){var d=Oa;var e=Pa;var f=Qa;var h=function(){return y()};var l=1}else 4===b&&(d=Ra,e=Sa,f=Ta,h=function(){return C()},l=2);qd(a,{name:c,fromWireType:function(m){for(var q=C()[m>>
2],p=h(),r,u=m+4,k=0;k<=q;++k){var v=m+4+k*b;if(k==q||0==p[v>>l])u=d(u,v-u),void 0===r?r=u:(r+=String.fromCharCode(0),r+=u),u=v+b}R(m);return r},toWireType:function(m,q){"string"!==typeof q&&X("Cannot pass non-string to C++ string type "+c);var p=f(q),r=L(4+p+b);C()[r>>2]=p>>l;e(q,r+4,p+b);null!==m&&m.push(R,r);return r},argPackAdvance:8,readValueFromPointer:fd,Kb:function(m){R(m)}})},d:function(a,b,c,d,e,f){dd[a]={name:W(b),Rc:Td(c,d),Rb:Td(e,f),dd:[]}},b:function(a,b,c,d,e,f,h,l,m,q){dd[a].dd.push({Id:W(b),
Nd:c,tc:Td(d,e),Md:f,oe:h,ne:Td(l,m),pe:q})},ya:function(a,b){b=W(b);qd(a,{Wd:!0,name:b,argPackAdvance:0,fromWireType:function(){},toWireType:function(){}})},ua:function(a){delete ze[a-1]},na:function(a,b){if(a==b)postMessage({cmd:"processQueuedMainThreadWork"});else if(F)postMessage({targetThread:a,cmd:"processThreadQueue"});else{a=(a=Q.Ob[a])&&a.worker;if(!a)return;a.postMessage({cmd:"processThreadQueue"})}return 1},k:function(a,b,c){a=ee(a);b=fe(b,"emval::as");var d=[],e=Y(d);A()[c>>2]=e;return b.toWireType(d,
a)},W:function(a,b,c,d){a=ee(a);c=ge(b,c);for(var e=Array(b),f=0;f<b;++f){var h=c[f];e[f]=h.readValueFromPointer(d);d+=h.argPackAdvance}a=a.apply(void 0,e);return Y(a)},t:function(a,b,c,d){a=je[a];b=ee(b);c=ie(c);a(b,c,null,d)},H:be,Ha:function(a,b){a=ee(a);b=ee(b);return a==b},Fa:function(a){if(0===a)return Y(ke());a=ie(a);return Y(ke()[a])},s:function(a,b){b=ge(a,b);for(var c=b[0],d=c.name+"_$"+b.slice(1).map(function(q){return q.name}).join("_")+"$",e=["retType"],f=[c],h="",l=0;l<a-1;++l)h+=(0!==
l?", ":"")+"arg"+l,e.push("argType"+l),f.push(b[1+l]);d="return function "+kd("methodCaller_"+d)+"(handle, name, destructors, args) {\n";var m=0;for(l=0;l<a-1;++l)d+="    var arg"+l+" = argType"+l+".readValueFromPointer(args"+(m?"+"+m:"")+");\n",m+=b[l+1].argPackAdvance;d+="    var rv = handle[name]("+h+");\n";for(l=0;l<a-1;++l)b[l+1].deleteObject&&(d+="    argType"+l+".deleteObject(arg"+l+");\n");c.Wd||(d+="    return retType.toWireType(destructors, rv);\n");e.push(d+"};\n");a=Zd(e).apply(null,f);
return le(a)},Da:function(a){a=ie(a);return Y(D[a])},p:function(a,b){a=ee(a);b=ee(b);return Y(a[b])},X:function(a){4<a&&(Z[a].Tc+=1)},Ga:function(a,b){a=ee(a);b=ee(b);return a instanceof b},B:function(a,b,c,d){a=ee(a);var e=me[b];if(!e){e="";for(var f=0;f<b;++f)e+=(0!==f?", ":"")+"arg"+f;var h="return function emval_allocator_"+b+"(constructor, argTypes, args) {\n";for(f=0;f<b;++f)h+="var argType"+f+" = requireRegisteredType(Module['HEAP32'][(argTypes >>> 2) + "+f+'], "parameter '+f+'");\nvar arg'+
f+" = argType"+f+".readValueFromPointer(args);\nargs += argType"+f+"['argPackAdvance'];\n";e=(new Function("requireRegisteredType","Module","__emval_register",h+("var obj = new constructor("+e+");\nreturn __emval_register(obj);\n}\n")))(fe,D,Y);me[b]=e}return e(a,c,d)},Y:function(){return Y([])},Ka:function(a){return Y(ie(a))},Ea:function(){return Y({})},Ja:function(a){ed(Z[a].value);be(a)},m:function(a,b,c){a=ee(a);b=ee(b);c=ee(c);a[b]=c},l:function(a,b){a=fe(a,"_emval_take_value");a=a.readValueFromPointer(b);
return Y(a)},Ia:function(a){a=ee(a);return Y(typeof a)},o:function(){H()},w:function(){var a=D.allowedThreads;return a?a:navigator.hardwareConcurrency},I:function(a,b){if(0===a)a=Date.now();else if(1===a||4===a)a=Lb();else return-1;A()[b>>2]=a/1E3|0;A()[b+4>>2]=a%1E3*1E6|0;return 0},i:function(a,b,c){ne.length=0;var d;for(c>>=2;d=x()[b++];)(d=105>d)&&c&1&&c++,ne.push(d?ja()[c++>>1]:A()[c]),++c;return ub[a].apply(null,ne)},ja:oe,M:function(){},r:pe,q:vb,x:Lb,D:function(){return"undefined"!==typeof SharedArrayBuffer},
G:function(a,b){nf(a,b||1);throw"longjmp";},ba:function(a,b,c){x().copyWithin(a,b,b+c)},ka:function(a,b,c){te.length=b;c>>=3;for(var d=0;d<b;d++)te[d]=ja()[c+d];return(0>a?ub[-a-1]:mf[a]).apply(null,te)},ca:function(a){var b=x().length;a>>>=0;if(a<=b||838860800<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);d=Math.max(a,d);0<d%65536&&(d+=65536-d%65536);a:{try{n.grow(Math.min(838860800,d)-t.byteLength+65535>>>16);aa(n.buffer);var e=1;break a}catch(f){}e=void 0}if(e)return!0}return!1},
la:function(a,b,c){return ve(a)?we(a,b,c):ye(a,b,c)},L:function(){},va:function(a,b,c,d,e){function f(G){De(G,h,q,p,m)}function h(G,rf){Fe(G,rf.response,function(ib){--Jb;Ee(function(){v?O.get(v)(ib):b&&b(ib)},N)},function(ib){--Jb;Ee(function(){v?O.get(v)(ib):b&&b(ib)},N)})}function l(G){De(G,r,q,p,m)}function m(G){Ee(function(){I?O.get(I)(G):e&&e(G)},N)}function q(G){--Jb;Ee(function(){z?O.get(z)(G):c&&c(G)},N)}function p(G){Ee(function(){B?O.get(B)(G):d&&d(G)},N)}function r(G){--Jb;Ee(function(){v?
O.get(v)(G):b&&b(G)},N)}Jb+=1;var u=a+112,k=K(u),v=C()[u+36>>2],z=C()[u+40>>2],B=C()[u+44>>2],I=C()[u+48>>2],J=C()[u+52>>2],na=!!(J&4),w=!!(J&32),M=!!(J&16),N=!!(J&64);if("EM_IDB_STORE"===k)k=C()[u+84>>2],Fe(a,x().slice(k,k+C()[u+88>>2]),r,q);else if("EM_IDB_DELETE"===k)He(a,r,q);else if(M){if(w)return 0;De(a,na?h:r,q,p,m)}else Ge(a,r,w?q:na?f:l);return a},ma:function(a,b){b>>=2;var c=A()[b+6];b={alpha:!!A()[b+0],depth:!!A()[b+1],stencil:!!A()[b+2],antialias:!!A()[b+3],premultipliedAlpha:!!A()[b+
4],preserveDrawingBuffer:!!A()[b+5],powerPreference:Pe[c],failIfMajorPerformanceCaveat:!!A()[b+7],Yd:A()[b+8],Oe:A()[b+9],bd:A()[b+10],Hd:A()[b+11],Se:A()[b+12],Te:A()[b+13]};a=ve(a);return!a||b.Hd?0:Le(a,b)},ga:Te,ha:Ue,A:function(a){Fb(a)},y:Ve,fa:We,O:Xe,Z:Ye,N:Ze,g:function(){return Ea},Ca:function(){var a=self.navigator.userAgent,b=Na(a)+1,c=L(b);Ma(a,c,b);return c},da:$e,aa:function(){Q.Rd()},$:of,F:pf,E:qf,a:n||D.wasmMemory,Ba:function(a){Nb();var b=new Date(A()[a+20>>2]+1900,A()[a+16>>2],
A()[a+12>>2],A()[a+8>>2],A()[a+4>>2],A()[a>>2],0),c=A()[a+32>>2],d=b.getTimezoneOffset(),e=new Date(b.getFullYear(),0,1),f=(new Date(b.getFullYear(),6,1)).getTimezoneOffset(),h=e.getTimezoneOffset(),l=Math.min(h,f);0>c?A()[a+32>>2]=Number(f!=h&&l==d):0<c!=(l==d)&&(f=Math.max(h,f),b.setTime(b.getTime()+6E4*((0<c?l:f)-d)));A()[a+24>>2]=b.getDay();c=(b.getTime()-e.getTime())/864E5|0;A()[a+28>>2]=c;A()[a>>2]=b.getSeconds();A()[a+4>>2]=b.getMinutes();A()[a+8>>2]=b.getHours();A()[a+12>>2]=b.getDate();A()[a+
16>>2]=b.getMonth();return b.getTime()/1E3|0},J:function(a){var b=Q.Cc.pop();a&&b()},K:Mb,T:function(a,b,c,d){if("undefined"===typeof SharedArrayBuffer)return E("Current environment does not support SharedArrayBuffer, pthreads are not available!"),6;if(!a)return E("pthread_create called with a null thread pointer!"),28;var e=[];if(F&&0===e.length)return sf(687865856,a,b,c,d);var f=0,h=0;if(b&&-1!=b){var l=A()[b>>2];l+=81920;f=A()[b+8>>2];h=0!==A()[b+12>>2]}else l=2097152;(b=0==f)?f=Zc(16,l):(f-=l,
Ja(0<f));for(var m=L(228),q=0;57>q;++q)C()[(m>>2)+q]=0;A()[a>>2]=m;A()[m+12>>2]=m;a=m+152;A()[a>>2]=a;c={Wb:f,bc:l,Ic:b,ad:h,re:c,zc:m,dc:d,ze:e};return F?(c.Ee="spawnThread",postMessage(c,e),0):Eb(c)},Aa:function(a,b){return bf(a,b)},e:function(a){Ea=a},U:jf,ea:function(a,b,c,d){return jf(a,b,c,d)},V:function(a){var b=Date.now()/1E3|0;a&&(A()[a>>2]=b);return b}};
(function(){function a(e,f){D.asm=e.exports;O=D.asm.Qa;Za.unshift(D.asm.La);Q.Vc.push(D.asm.Pa);Ga=f;F||nb("wasm-instantiate")}function b(e){a(e.instance,e.module)}function c(e){return rb().then(function(f){return WebAssembly.instantiate(f,d)}).then(e,function(f){E("failed to asynchronously prepare wasm: "+f);H(f)})}var d={a:tf};F||mb("wasm-instantiate");if(D.instantiateWasm)try{return D.instantiateWasm(d,a)}catch(e){return E("Module.instantiateWasm callback failed with error: "+e),!1}(function(){return Fa||
"function"!==typeof WebAssembly.instantiateStreaming||ob()||"function"!==typeof fetch?c(b):fetch(pb,{credentials:"same-origin"}).then(function(e){return WebAssembly.instantiateStreaming(e,d).then(b,function(f){E("wasm streaming compile failed: "+f);E("falling back to ArrayBuffer instantiation");return c(b)})})})().catch(ma);return{}})();D.___wasm_call_ctors=function(){return(D.___wasm_call_ctors=D.asm.La).apply(null,arguments)};
var R=D._free=function(){return(R=D._free=D.asm.Ma).apply(null,arguments)},L=D._malloc=function(){return(L=D._malloc=D.asm.Na).apply(null,arguments)},Ab=D._pthread_self=function(){return(Ab=D._pthread_self=D.asm.Oa).apply(null,arguments)};D._emscripten_tls_init=function(){return(D._emscripten_tls_init=D.asm.Pa).apply(null,arguments)};var Wd=D.___getTypeName=function(){return(Wd=D.___getTypeName=D.asm.Ra).apply(null,arguments)};
D.___embind_register_native_and_builtin_types=function(){return(D.___embind_register_native_and_builtin_types=D.asm.Sa).apply(null,arguments)};D._emscripten_current_thread_process_queued_calls=function(){return(D._emscripten_current_thread_process_queued_calls=D.asm.Ta).apply(null,arguments)};
var zb=D._emscripten_register_main_browser_thread_id=function(){return(zb=D._emscripten_register_main_browser_thread_id=D.asm.Ua).apply(null,arguments)},cf=D._emscripten_main_browser_thread_id=function(){return(cf=D._emscripten_main_browser_thread_id=D.asm.Va).apply(null,arguments)},tb=D.__emscripten_do_dispatch_to_thread=function(){return(tb=D.__emscripten_do_dispatch_to_thread=D.asm.Wa).apply(null,arguments)},sf=D._emscripten_sync_run_in_main_thread_4=function(){return(sf=D._emscripten_sync_run_in_main_thread_4=
D.asm.Xa).apply(null,arguments)},Db=D._emscripten_main_thread_process_queued_calls=function(){return(Db=D._emscripten_main_thread_process_queued_calls=D.asm.Ya).apply(null,arguments)},se=D._emscripten_run_in_main_runtime_thread_js=function(){return(se=D._emscripten_run_in_main_runtime_thread_js=D.asm.Za).apply(null,arguments)},xe=D.__emscripten_call_on_thread=function(){return(xe=D.__emscripten_call_on_thread=D.asm._a).apply(null,arguments)},yb=D.__emscripten_thread_init=function(){return(yb=D.__emscripten_thread_init=
D.asm.$a).apply(null,arguments)},$c=D._memset=function(){return($c=D._memset=D.asm.ab).apply(null,arguments)},Bb=D.___pthread_tsd_run_dtors=function(){return(Bb=D.___pthread_tsd_run_dtors=D.asm.bb).apply(null,arguments)},af=D._emscripten_get_global_libc=function(){return(af=D._emscripten_get_global_libc=D.asm.cb).apply(null,arguments)},Qb=D.__get_tzname=function(){return(Qb=D.__get_tzname=D.asm.db).apply(null,arguments)},Pb=D.__get_daylight=function(){return(Pb=D.__get_daylight=D.asm.eb).apply(null,
arguments)},Ob=D.__get_timezone=function(){return(Ob=D.__get_timezone=D.asm.fb).apply(null,arguments)},qe=D.stackSave=function(){return(qe=D.stackSave=D.asm.gb).apply(null,arguments)},Ib=D.stackRestore=function(){return(Ib=D.stackRestore=D.asm.hb).apply(null,arguments)},re=D.stackAlloc=function(){return(re=D.stackAlloc=D.asm.ib).apply(null,arguments)},Hb=D._emscripten_stack_set_limits=function(){return(Hb=D._emscripten_stack_set_limits=D.asm.jb).apply(null,arguments)},nf=D._setThrew=function(){return(nf=
D._setThrew=D.asm.kb).apply(null,arguments)},Zc=D._memalign=function(){return(Zc=D._memalign=D.asm.lb).apply(null,arguments)};D.dynCall_jiji=function(){return(D.dynCall_jiji=D.asm.mb).apply(null,arguments)};D.dynCall_ji=function(){return(D.dynCall_ji=D.asm.nb).apply(null,arguments)};D.dynCall_viijii=function(){return(D.dynCall_viijii=D.asm.ob).apply(null,arguments)};D.dynCall_iiiiij=function(){return(D.dynCall_iiiiij=D.asm.pb).apply(null,arguments)};
D.dynCall_iiiiijj=function(){return(D.dynCall_iiiiijj=D.asm.qb).apply(null,arguments)};D.dynCall_iiiiiijj=function(){return(D.dynCall_iiiiiijj=D.asm.rb).apply(null,arguments)};var Cb=D.__emscripten_allow_main_runtime_queued_calls=301796,wb=D.__emscripten_main_thread_futex=962768;function pf(a,b){var c=qe();try{O.get(a)(b)}catch(d){Ib(c);if(d!==d+0&&"longjmp"!==d)throw d;nf(1,0)}}function qf(a,b,c){var d=qe();try{O.get(a)(b,c)}catch(e){Ib(d);if(e!==e+0&&"longjmp"!==e)throw e;nf(1,0)}}
function of(a,b,c,d){var e=qe();try{return O.get(a)(b,c,d)}catch(f){Ib(e);if(f!==f+0&&"longjmp"!==f)throw f;nf(1,0)}}D.addRunDependency=mb;D.removeRunDependency=nb;D.FS_createPath=Jc;D.FS_createDataFile=Lc;D.FS_createPreloadedFile=Oc;D.FS_createLazyFile=Nc;D.FS_createDevice=db;D.FS_unlink=Cc;D.PThread=Q;D.PThread=Q;D.wasmMemory=n;D.ExitStatus=Gb;var uf;function Gb(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}lb=function vf(){uf||wf();uf||(lb=vf)};
function wf(){function a(){if(!uf&&(uf=!0,D.calledRun=!0,!Ha)){ab();la(D);if(D.onRuntimeInitialized)D.onRuntimeInitialized();if(!F){if(D.postRun)for("function"==typeof D.postRun&&(D.postRun=[D.postRun]);D.postRun.length;){var b=D.postRun.shift();$a.unshift(b)}gb($a)}}}if(!(0<jb))if(F)la(D),ab(),postMessage({cmd:"loaded"});else{if(!F){if(D.preRun)for("function"==typeof D.preRun&&(D.preRun=[D.preRun]);D.preRun.length;)hb();gb(Ya)}0<jb||(D.setStatus?(D.setStatus("Running..."),setTimeout(function(){setTimeout(function(){D.setStatus("")},
1);a()},1)):a())}}D.run=wf;function Fb(a){Ia=a;if(F)throw postMessage({cmd:"exitProcess",returnCode:a}),new Gb(a);if(!Kb()){Q.se();if(D.onExit)D.onExit(a);Ha=!0}ua(a,new Gb(a))}if(D.preInit)for("function"==typeof D.preInit&&(D.preInit=[D.preInit]);0<D.preInit.length;)D.preInit.pop()();F&&(noExitRuntime=!1,Q.Sd());wf();


  return BlinkIDWasmSDK.ready
}
);
})();
if (typeof exports === 'object' && typeof module === 'object')
  module.exports = BlinkIDWasmSDK;
else if (typeof define === 'function' && define['amd'])
  define([], function() { return BlinkIDWasmSDK; });
else if (typeof exports === 'object')
  exports["BlinkIDWasmSDK"] = BlinkIDWasmSDK;
