
var BlinkIDWasmSDK = (() => {
  var _scriptDir = typeof document !== 'undefined' && document.currentScript ? document.currentScript.src : undefined;
  
  return (
function(BlinkIDWasmSDK) {
  BlinkIDWasmSDK = BlinkIDWasmSDK || {};


function g(){n.buffer!=r&&aa(n.buffer);return ba}function y(){n.buffer!=r&&aa(n.buffer);return ca}function da(){n.buffer!=r&&aa(n.buffer);return ea}function z(){n.buffer!=r&&aa(n.buffer);return fa}function B(){n.buffer!=r&&aa(n.buffer);return ha}function C(){n.buffer!=r&&aa(n.buffer);return ia}function ja(){n.buffer!=r&&aa(n.buffer);return ka}var D;D||(D=typeof BlinkIDWasmSDK !== 'undefined' ? BlinkIDWasmSDK : {});var la=Object.assign,na,oa;D.ready=new Promise(function(a,b){na=a;oa=b});
D.uc||(D.uc=0);D.uc++;
D.ENVIRONMENT_IS_PTHREAD||function(a){function b(m,q,p){var t=new XMLHttpRequest;t.open("GET",m,!0);t.responseType="arraybuffer";t.onprogress=function(v){var k=q;v.total&&(k=v.total);if(v.loaded){t.gd?D.Lb[m].loaded=v.loaded:(t.gd=!0,D.Lb||(D.Lb={}),D.Lb[m]={loaded:v.loaded,total:k});var u=k=v=0,x;for(x in D.Lb){var A=D.Lb[x];v+=A.total;k+=A.loaded;u++}v=Math.ceil(v*D.uc/u);D.setStatus&&D.setStatus("Downloading data... ("+k+"/"+v+")")}else!D.Lb&&D.setStatus&&D.setStatus("Downloading data...")};t.onerror=
function(){throw Error("NetworkError for: "+m);};t.onload=function(){if(200==t.status||304==t.status||206==t.status||0==t.status&&t.response)p(t.response);else throw Error(t.statusText+" : "+t.responseURL);};t.send(null)}function c(m){console.error("package error:",m)}function d(){function m(v,k,u){this.start=v;this.end=k;this.audio=u}function q(v){if(!v)throw"Loading data file failed."+Error().stack;if(!(v instanceof ArrayBuffer))throw"bad input to processPackageData"+Error().stack;v=new Uint8Array(v);
m.prototype.md=v;v=a.files;for(var k=0;k<v.length;++k)m.prototype.Fc[v[k].filename].onload();D.removeRunDependency("datafile_../../resources/advanced-threads/BlinkIDWasmSDK.data")}D.FS_createPath("/","microblink",!0,!0);m.prototype={Fc:{},open:function(v,k){this.name=k;this.Fc[k]=this;D.addRunDependency("fp "+this.name)},send:function(){},onload:function(){this.finish(this.md.subarray(this.start,this.end))},finish:function(v){D.FS_createDataFile(this.name,null,v,!0,!0,!0);D.removeRunDependency("fp "+
this.name);this.Fc[this.name]=null}};for(var p=a.files,t=0;t<p.length;++t)(new m(p[t].start,p[t].end,p[t].audio||0)).open("GET",p[t].filename);D.addRunDependency("datafile_../../resources/advanced-threads/BlinkIDWasmSDK.data");D.Xc||(D.Xc={});D.Xc["../../resources/advanced-threads/BlinkIDWasmSDK.data"]={le:!1};l?(q(l),l=null):h=q}"object"===typeof window?window.encodeURIComponent(window.location.pathname.toString().substring(0,window.location.pathname.toString().lastIndexOf("/"))+"/"):"undefined"===
typeof process&&"undefined"!==typeof location&&encodeURIComponent(location.pathname.toString().substring(0,location.pathname.toString().lastIndexOf("/"))+"/");"function"!==typeof D.locateFilePackage||D.locateFile||(D.locateFile=D.locateFilePackage,E("warning: you defined Module.locateFilePackage, that has been renamed to Module.locateFile (using your locateFilePackage for now)"));var e=D.locateFile?D.locateFile("BlinkIDWasmSDK.data",""):"BlinkIDWasmSDK.data",f=a.remote_package_size,h=null,l=D.getPreloadedPackage?
D.getPreloadedPackage(e,f):null;l||b(e,f,function(m){h?(h(m),h=null):l=m},c);D.calledRun?d():(D.preRun||(D.preRun=[]),D.preRun.push(d))}({files:[{filename:"/microblink/Model_a5858807e9d6b351bdbe37cbb4f373b6b9dca41776e0f60a8457be92550632ed.strop",start:0,end:1999160},{filename:"/microblink/Model_2d419402bfe12530fb79cb71e911ddf977986ad414c8870fcedd54378167d1af.strop",start:1999160,end:2213256},{filename:"/microblink/Model_82ae7b860c6b4cb8249534e0004901bc46dee18fd3adbe535809abeefbf4fd88.strop",start:2213256,
end:6931572},{filename:"/microblink/Model_e4f1f62f68ec44b71ecad3fb3f3b48fe3790beb5ab325611e17d63af06e9f644.strop",start:6931572,end:6988086},{filename:"/microblink/Model_36d8e94f4cb46097bd6b7385f2aa91fcdee1a5fefeec59e56d1b9e82c94b00a7.strop",start:6988086,end:7357878},{filename:"/microblink/face_detector_model.zzip",start:7357878,end:7454736},{filename:"/microblink/Model_faf688599c7e261a2a7404730f69ed029115bb0d3e7a3657731d88e701720efe.strop",start:7454736,end:7471474},{filename:"/microblink/ccc_lookup_table.zzip",
start:7471474,end:7491943},{filename:"/microblink/Model_8322bc53f683fdb17f42124244cf6469a82e1c00ec8c43c5d7939ae25ee8c006.strop",start:7491943,end:8011545},{filename:"/microblink/Model_2880751121560047e6dc571bc8ff4683aeb863886f7c0789234594ceb1e23577.strop",start:8011545,end:8015483},{filename:"/microblink/Model_d647a73c5ff6581d591761cdfe03eff14a830e302c92782c1d683291bea047d6.strop",start:8015483,end:8685053},{filename:"/microblink/Model_473ac5f5e256623c0a6b282698c1f1b033b9fb5359e6aa142e9fb4a4022afe4e.strop",
start:8685053,end:8691935},{filename:"/microblink/Model_b452fd3cd4037080cfcb4c423dba5bc58c8ceafc28427fdf9c5778fb353f088e.strop",start:8691935,end:8698753},{filename:"/microblink/Model_840bd7ad76dab96d6ebae4afab54c9608ffe35d9f35a92e46a45924d04fee981.strop",start:8698753,end:9411985}],remote_package_size:9411985,package_uuid:"5997a12f-b20f-41ab-bdc7-5054d03f2b6d"});var crypto={getRandomValues:function(a){for(var b=0;b<a.length;b++)a[b]=256*Math.random()|0}},pa;
pa=D.allowedThreads&&0<D.allowedThreads?D.allowedThreads-1:navigator.hardwareConcurrency-1;var qa=0,ra;0<pa&&(D.threadWorkersReadyPromise=new Promise(function(a){ra=a}));D.preRun||(D.preRun=[]);D.preRun.push(function(a){function b(){qa++;qa==pa&&ra()}var c=a.PThread.zc;a.PThread.zc=function(d){c(d,b)}});
var sa=la({},D),ta="./this.program",ua=(a,b)=>{throw b;},va="object"===typeof window,wa="function"===typeof importScripts,xa="object"===typeof process&&"object"===typeof process.he&&"string"===typeof process.he.node,F=D.ENVIRONMENT_IS_PTHREAD||!1,ya="";function za(a){return D.locateFile?D.locateFile(a,ya):ya+a}var Aa,Ba,Ca;
if(va||wa)wa?ya=self.location.href:"undefined"!==typeof document&&document.currentScript&&(ya=document.currentScript.src),_scriptDir&&(ya=_scriptDir),ya=0!==ya.indexOf("blob:")?ya.substr(0,ya.replace(/[?#].*/,"").lastIndexOf("/")+1):"",Aa=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},wa&&(Ca=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),Ba=function(a,b,c){var d=new XMLHttpRequest;
d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=function(){200==d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)};var Da=D.print||console.log.bind(console),E=D.printErr||console.warn.bind(console);la(D,sa);sa=null;D.thisProgram&&(ta=D.thisProgram);D.quit&&(ua=D.quit);var Ea,Fa=0,Ga;D.wasmBinary&&(Ga=D.wasmBinary);var noExitRuntime=D.noExitRuntime||!0;"object"!==typeof WebAssembly&&Ha("no native wasm support detected");var n,Ia,Ja=!1,Ka;
function La(a){var b=new TextDecoder(a);this.decode=c=>{c.buffer instanceof SharedArrayBuffer&&(c=new Uint8Array(c));return b.decode.call(b,c)}}var Ma="undefined"!==typeof TextDecoder?new La("utf8"):void 0;
function Na(a,b,c){var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.subarray&&Ma)return Ma.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var f=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|f);else{var h=a[b++]&63;e=224==(e&240)?(e&15)<<12|f<<6|h:(e&7)<<18|f<<12|h<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d}function I(a,b){return a?Na(y(),a,b):""}
function Oa(a,b,c,d){if(!(0<d))return 0;var e=c;d=c+d-1;for(var f=0;f<a.length;++f){var h=a.charCodeAt(f);if(55296<=h&&57343>=h){var l=a.charCodeAt(++f);h=65536+((h&1023)<<10)|l&1023}if(127>=h){if(c>=d)break;b[c++]=h}else{if(2047>=h){if(c+1>=d)break;b[c++]=192|h>>6}else{if(65535>=h){if(c+2>=d)break;b[c++]=224|h>>12}else{if(c+3>=d)break;b[c++]=240|h>>18;b[c++]=128|h>>12&63}b[c++]=128|h>>6&63}b[c++]=128|h&63}}b[c]=0;return c-e}function K(a,b,c){Oa(a,y(),b,c)}
function Pa(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:b+4}return b}var Qa="undefined"!==typeof TextDecoder?new La("utf-16le"):void 0;function Ra(a,b){var c=a>>1;for(var d=c+b/2;!(c>=d)&&z()[c];)++c;c<<=1;if(32<c-a&&Qa)return Qa.decode(y().subarray(a,c));c="";for(d=0;!(d>=b/2);++d){var e=da()[a+2*d>>1];if(0==e)break;c+=String.fromCharCode(e)}return c}
function Sa(a,b,c){void 0===c&&(c=2147483647);if(2>c)return 0;c-=2;var d=b;c=c<2*a.length?c/2:a.length;for(var e=0;e<c;++e){var f=a.charCodeAt(e);da()[b>>1]=f;b+=2}da()[b>>1]=0;return b-d}function Ta(a){return 2*a.length}function Ua(a,b){for(var c=0,d="";!(c>=b/4);){var e=B()[a+4*c>>2];if(0==e)break;++c;65536<=e?(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023)):d+=String.fromCharCode(e)}return d}
function Va(a,b,c){void 0===c&&(c=2147483647);if(4>c)return 0;var d=b;c=d+c-4;for(var e=0;e<a.length;++e){var f=a.charCodeAt(e);if(55296<=f&&57343>=f){var h=a.charCodeAt(++e);f=65536+((f&1023)<<10)|h&1023}B()[b>>2]=f;b+=4;if(b+4>c)break}B()[b>>2]=0;return b-d}function Wa(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&++c;b+=4}return b}function Xa(a){var b=Pa(a)+1,c=Ya(b);c&&Oa(a,g(),c,b);return c}function Za(a,b){g().set(a,b)}var r,ba,ca,ea,fa,ha,ia,$a,ka;F&&(r=D.buffer);
function aa(a){r=a;D.HEAP8=ba=new Int8Array(a);D.HEAP16=ea=new Int16Array(a);D.HEAP32=ha=new Int32Array(a);D.HEAPU8=ca=new Uint8Array(a);D.HEAPU16=fa=new Uint16Array(a);D.HEAPU32=ia=new Uint32Array(a);D.HEAPF32=$a=new Float32Array(a);D.HEAPF64=ka=new Float64Array(a)}var bb=D.INITIAL_MEMORY||209715200;
if(F)n=D.wasmMemory,r=D.buffer;else if(D.wasmMemory)n=D.wasmMemory;else if(n=new WebAssembly.Memory({initial:bb/65536,maximum:12800,shared:!0}),!(n.buffer instanceof SharedArrayBuffer))throw E("requested a shared WebAssembly.Memory but the returned buffer is not a SharedArrayBuffer, indicating that while the browser has SharedArrayBuffer it does not have WebAssembly threads support - you may need to set a flag"),xa&&console.log("(on node you may need: --experimental-wasm-threads --experimental-wasm-bulk-memory and also use a recent version)"),
Error("bad memory");n&&(r=n.buffer);bb=r.byteLength;aa(r);var cb,db=[],eb=[],fb=[],gb=!1,hb=0;function ib(){return noExitRuntime||0<hb}
function jb(){F||(D.noFSInit||kb||(kb=!0,lb(),D.stdin=D.stdin,D.stdout=D.stdout,D.stderr=D.stderr,D.stdin?mb("/dev","stdin",D.stdin):nb("/dev/tty","/dev/stdin"),D.stdout?mb("/dev","stdout",null,D.stdout):nb("/dev/tty","/dev/stdout"),D.stderr?mb("/dev","stderr",null,D.stderr):nb("/dev/tty1","/dev/stderr"),ob("/dev/stdin",0),ob("/dev/stdout",1),ob("/dev/stderr",1)),pb=!1,qb(eb))}function rb(){var a=D.preRun.shift();db.unshift(a)}var sb=0,tb=null,ub=null;
function vb(){sb++;D.monitorRunDependencies&&D.monitorRunDependencies(sb)}function wb(){sb--;D.monitorRunDependencies&&D.monitorRunDependencies(sb);if(0==sb&&(null!==tb&&(clearInterval(tb),tb=null),ub)){var a=ub;ub=null;a()}}D.preloadedImages={};D.preloadedAudios={};function Ha(a){if(F)postMessage({cmd:"onAbort",arg:a});else if(D.onAbort)D.onAbort(a);a="Aborted("+a+")";E(a);Ja=!0;Ka=1;a=new WebAssembly.RuntimeError(a+". Build with -s ASSERTIONS=1 for more info.");oa(a);throw a;}
function xb(){return yb.startsWith("data:application/octet-stream;base64,")}var yb;yb="BlinkIDWasmSDK.wasm";xb()||(yb=za(yb));function zb(){var a=yb;try{if(a==yb&&Ga)return new Uint8Array(Ga);if(Ca)return Ca(a);throw"both async and sync fetching of the wasm failed";}catch(b){Ha(b)}}
function Ab(){return Ga||!va&&!wa||"function"!==typeof fetch?Promise.resolve().then(function(){return zb()}):fetch(yb,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+yb+"'";return a.arrayBuffer()}).catch(function(){return zb()})}
var N,Bb,Cb={381937:function(a){a=I(a);throw Error("Failed to reconfigure RecognizerRunner due to following error: "+a);},382073:function(a,b,c,d){a=I(a);b=I(b);c=I(c);d=I(d);throw Error(a+b+c+d);},382289:function(a,b){a=I(a);b=I(b);throw Error(a+b);},382399:function(a,b){a=I(a);b=I(b);console.log(a+b)},382497:function(a){throw Error(I(a));},382540:function(){throw Error("Unable to perform that operation while recognizer is in use!");},382623:function(){throw Error("Unable to perform that operation while recognizer is in use!");
},382706:function(){throw Error("Unable to perform that operation while recognizer is in use!");}};function qb(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b(D);else{var c=b.me;"number"===typeof c?void 0===b.Sb?O(c)():O(c)(b.Sb):c(void 0===b.Sb?null:b.Sb)}}}function Db(a){var b=Eb();a=a();Fb(b);return a}function Gb(a){var b=P.Fb[a];b&&(B()[a>>2]=0,P.Gc(b.worker))}function Hb(a){a instanceof Ib||"unwind"==a||ua(1,a)}
var P={Ib:[],Zb:[],Ic:[],qe:function(){},Cd:function(){P.receiveObjectTransfer=P.Rd;P.threadInit=P.dd;P.setExitStatus=P.Wd},Fb:{},Wd:function(a){Ka=a},cd:function(){for(var a in P.Fb){var b=P.Fb[a];b&&b.worker&&P.Gc(b.worker)}for(a=0;a<P.Ib.length;++a)P.Ib[a].terminate();P.Ib=[]},Gc:function(a){P.Td(function(){delete P.Fb[a.Qb.Hc];P.Ib.push(a);P.Zb.splice(P.Zb.indexOf(a),1);Jb(a.Qb.Hc);a.Qb=void 0})},Td:function(a){B()[Kb>>2]=0;try{a()}finally{B()[Kb>>2]=1}},Rd:function(){},dd:function(){for(var a in P.Ic)P.Ic[a]()},
zc:function(a,b){a.onmessage=function(c){c=c.data;var d=c.cmd;a.Qb&&(P.pd=a.Qb.Hc);if(c.targetThread&&c.targetThread!=Lb()){var e=P.Fb[c.xe];e?e.worker.postMessage(c,c.transferList):E('Internal error! Worker sent a message "'+d+'" to target pthread '+c.targetThread+", but that thread no longer exists!")}else if("processQueuedMainThreadWork"===d)Mb();else if("spawnThread"===d)Nb(c);else if("cleanupThread"===d)Gb(c.thread);else if("killThread"===d)c=c.thread,B()[c>>2]=0,d=P.Fb[c],delete P.Fb[c],d.worker.terminate(),
Jb(c),P.Zb.splice(P.Zb.indexOf(d.worker),1),d.worker.Qb=void 0;else if("cancelThread"===d)P.Fb[c.thread].worker.postMessage({cmd:"cancel"});else if("loaded"===d)a.loaded=!0,b&&b(a),a.Yb&&(a.Yb(),delete a.Yb);else if("print"===d)Da("Thread "+c.threadId+": "+c.text);else if("printErr"===d)E("Thread "+c.threadId+": "+c.text);else if("alert"===d)alert("Thread "+c.threadId+": "+c.text);else if("detachedExit"===d)P.Gc(a);else if("setimmediate"===c.target)a.postMessage(c);else if("onAbort"===d){if(D.onAbort)D.onAbort(c.arg)}else E("worker sent an unknown command "+
d);P.pd=void 0};a.onerror=function(c){E("worker sent an error! "+c.filename+":"+c.lineno+": "+c.message);throw c;};a.postMessage({cmd:"load",urlOrBlob:D.mainScriptUrlOrBlob||_scriptDir,wasmMemory:n,wasmModule:Ia})},hd:function(){var a=za("BlinkIDWasmSDK.worker.js");P.Ib.push(new Worker(a))},vd:function(){0==P.Ib.length&&(P.hd(),P.zc(P.Ib[0]));return P.Ib.pop()}};D.establishStackSpace=function(){var a=Lb(),b=B()[a+44>>2];a=B()[a+48>>2];Ob(b,b-a);Fb(b)};
function Pb(a){if(F)return Q(1,0,a);try{Qb(a)}catch(b){Hb(b)}}var Rb=[];function O(a){var b=Rb[a];b||(a>=Rb.length&&(Rb.length=a+1),Rb[a]=b=cb.get(a));return b}D.invokeEntryPoint=function(a,b){return O(a)(b)};var Sb;Sb=F?()=>performance.now()-D.__performance_now_clock_drift:()=>performance.now();
function Tb(){function a(h){return(h=h.toTimeString().match(/\(([A-Za-z ]+)\)$/))?h[1]:"GMT"}if(F)return Q(2,1);var b=(new Date).getFullYear(),c=new Date(b,0,1),d=new Date(b,6,1);b=c.getTimezoneOffset();var e=d.getTimezoneOffset(),f=Math.max(b,e);B()[Ub()>>2]=60*f;B()[Vb()>>2]=Number(b!=e);c=a(c);d=a(d);c=Xa(c);d=Xa(d);e<b?(B()[Wb()>>2]=c,B()[Wb()+4>>2]=d):(B()[Wb()>>2]=d,B()[Wb()+4>>2]=c)}var Xb;
function Nb(a){var b=P.vd();if(!b)return 6;P.Zb.push(b);var c=P.Fb[a.Ac]={worker:b,Hc:a.Ac};b.Qb=c;var d={cmd:"run",start_routine:a.ae,arg:a.Sb,threadInfoStruct:a.Ac};b.Yb=function(){d.time=performance.now();b.postMessage(d,a.fe)};b.loaded&&(b.Yb(),delete b.Yb);return 0}function Yb(a,b){for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a}
function Zb(a){var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=Yb(a.split("/").filter(function(d){return!!d}),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a}function $b(a){var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,b.length-1));return a+b}function ac(a){if("/"===a)return"/";a=Zb(a);a=a.replace(/\/$/,"");var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)}
function bc(){if("object"===typeof crypto&&"function"===typeof crypto.getRandomValues){var a=new Uint8Array(1);return function(){crypto.getRandomValues(a);return a[0]}}return function(){Ha("randomDevice")}}
function cc(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:"/";if("string"!==typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=Yb(a.split("/").filter(function(d){return!!d}),!b).join("/");return(b?"/":"")+a||"."}var dc=[];function ec(a,b){dc[a]={input:[],ub:[],Pb:b};fc(a,gc)}
var gc={open:function(a){var b=dc[a.node.Wb];if(!b)throw new R(43);a.sb=b;a.seekable=!1},close:function(a){a.sb.Pb.flush(a.sb)},flush:function(a){a.sb.Pb.flush(a.sb)},read:function(a,b,c,d){if(!a.sb||!a.sb.Pb.Tc)throw new R(60);for(var e=0,f=0;f<d;f++){try{var h=a.sb.Pb.Tc(a.sb)}catch(l){throw new R(29);}if(void 0===h&&0===e)throw new R(6);if(null===h||void 0===h)break;e++;b[c+f]=h}e&&(a.node.timestamp=Date.now());return e},write:function(a,b,c,d){if(!a.sb||!a.sb.Pb.Bc)throw new R(60);try{for(var e=
0;e<d;e++)a.sb.Pb.Bc(a.sb,b[c+e])}catch(f){throw new R(29);}d&&(a.node.timestamp=Date.now());return e}},ic={Tc:function(a){if(!a.input.length){var b=null;"undefined"!=typeof window&&"function"==typeof window.prompt?(b=window.prompt("Input: "),null!==b&&(b+="\n")):"function"==typeof readline&&(b=readline(),null!==b&&(b+="\n"));if(!b)return null;a.input=hc(b,!0)}return a.input.shift()},Bc:function(a,b){null===b||10===b?(Da(Na(a.ub,0)),a.ub=[]):0!=b&&a.ub.push(b)},flush:function(a){a.ub&&0<a.ub.length&&
(Da(Na(a.ub,0)),a.ub=[])}},jc={Bc:function(a,b){null===b||10===b?(E(Na(a.ub,0)),a.ub=[]):0!=b&&a.ub.push(b)},flush:function(a){a.ub&&0<a.ub.length&&(E(Na(a.ub,0)),a.ub=[])}};function kc(a){a=65536*Math.ceil(a/65536);var b=lc(65536,a);if(!b)return 0;y().fill(0,b,b+a);return b}
var S={Eb:null,Gb:function(){return S.createNode(null,"/",16895,0)},createNode:function(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new R(63);S.Eb||(S.Eb={dir:{node:{Db:S.lb.Db,xb:S.lb.xb,Tb:S.lb.Tb,lc:S.lb.lc,ad:S.lb.ad,sc:S.lb.sc,bd:S.lb.bd,$c:S.lb.$c,oc:S.lb.oc},stream:{Kb:S.nb.Kb}},file:{node:{Db:S.lb.Db,xb:S.lb.xb},stream:{Kb:S.nb.Kb,read:S.nb.read,write:S.nb.write,Jc:S.nb.Jc,mc:S.nb.mc,nc:S.nb.nc}},link:{node:{Db:S.lb.Db,xb:S.lb.xb,Xb:S.lb.Xb},stream:{}},Lc:{node:{Db:S.lb.Db,xb:S.lb.xb},
stream:mc}});c=nc(a,b,c,d);16384===(c.mode&61440)?(c.lb=S.Eb.dir.node,c.nb=S.Eb.dir.stream,c.mb={}):32768===(c.mode&61440)?(c.lb=S.Eb.file.node,c.nb=S.Eb.file.stream,c.qb=0,c.mb=null):40960===(c.mode&61440)?(c.lb=S.Eb.link.node,c.nb=S.Eb.link.stream):8192===(c.mode&61440)&&(c.lb=S.Eb.Lc.node,c.nb=S.Eb.Lc.stream);c.timestamp=Date.now();a&&(a.mb[b]=c,a.timestamp=c.timestamp);return c},ne:function(a){return a.mb?a.mb.subarray?a.mb.subarray(0,a.qb):new Uint8Array(a.mb):new Uint8Array(0)},Pc:function(a,
b){var c=a.mb?a.mb.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)>>>0),0!=c&&(b=Math.max(b,256)),c=a.mb,a.mb=new Uint8Array(b),0<a.qb&&a.mb.set(c.subarray(0,a.qb),0))},Sd:function(a,b){if(a.qb!=b)if(0==b)a.mb=null,a.qb=0;else{var c=a.mb;a.mb=new Uint8Array(b);c&&a.mb.set(c.subarray(0,Math.min(b,a.qb)));a.qb=b}},lb:{Db:function(a){var b={};b.qd=8192===(a.mode&61440)?a.id:1;b.wc=a.id;b.mode=a.mode;b.Md=1;b.uid=0;b.zd=0;b.Wb=a.Wb;b.size=16384===(a.mode&61440)?4096:32768===(a.mode&61440)?a.qb:40960===
(a.mode&61440)?a.link.length:0;b.jd=new Date(a.timestamp);b.Ld=new Date(a.timestamp);b.od=new Date(a.timestamp);b.kd=4096;b.ld=Math.ceil(b.size/b.kd);return b},xb:function(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);void 0!==b.size&&S.Sd(a,b.size)},Tb:function(){throw oc[44];},lc:function(a,b,c,d){return S.createNode(a,b,c,d)},ad:function(a,b,c){if(16384===(a.mode&61440)){try{var d=pc(b,c)}catch(f){}if(d)for(var e in d.mb)throw new R(55);}delete a.parent.mb[a.name];
a.parent.timestamp=Date.now();a.name=c;b.mb[c]=a;b.timestamp=a.parent.timestamp;a.parent=b},sc:function(a,b){delete a.mb[b];a.timestamp=Date.now()},bd:function(a,b){var c=pc(a,b),d;for(d in c.mb)throw new R(55);delete a.mb[b];a.timestamp=Date.now()},$c:function(a){var b=[".",".."],c;for(c in a.mb)a.mb.hasOwnProperty(c)&&b.push(c);return b},oc:function(a,b,c){a=S.createNode(a,b,41471,0);a.link=c;return a},Xb:function(a){if(40960!==(a.mode&61440))throw new R(28);return a.link}},nb:{read:function(a,
b,c,d,e){var f=a.node.mb;if(e>=a.node.qb)return 0;a=Math.min(a.node.qb-e,d);if(8<a&&f.subarray)b.set(f.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=f[e+d];return a},write:function(a,b,c,d,e,f){b.buffer===g().buffer&&(f=!1);if(!d)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&(!a.mb||a.mb.subarray)){if(f)return a.mb=b.subarray(c,c+d),a.qb=d;if(0===a.qb&&0===e)return a.mb=b.slice(c,c+d),a.qb=d;if(e+d<=a.qb)return a.mb.set(b.subarray(c,c+d),e),d}S.Pc(a,e+d);if(a.mb.subarray&&b.subarray)a.mb.set(b.subarray(c,
c+d),e);else for(f=0;f<d;f++)a.mb[e+f]=b[c+f];a.qb=Math.max(a.qb,e+d);return d},Kb:function(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.qb);if(0>b)throw new R(28);return b},Jc:function(a,b,c){S.Pc(a.node,b+c);a.node.qb=Math.max(a.node.qb,b+c)},mc:function(a,b,c,d,e,f){if(0!==b)throw new R(28);if(32768!==(a.node.mode&61440))throw new R(43);a=a.node.mb;if(f&2||a.buffer!==r){if(0<d||d+c<a.length)a=a.subarray?a.subarray(d,d+c):Array.prototype.slice.call(a,d,d+c);d=!0;c=kc(c);
if(!c)throw new R(48);g().set(a,c)}else d=!1,c=a.byteOffset;return{pb:c,tc:d}},nc:function(a,b,c,d,e){if(32768!==(a.node.mode&61440))throw new R(43);if(e&2)return 0;S.nb.write(a,b,0,d,c,!1);return 0}}};function qc(a,b,c){var d="al "+a;Ba(a,function(e){e||Ha('Loading data file "'+a+'" failed (no arrayBuffer).');b(new Uint8Array(e));d&&wb(d)},function(){if(c)c();else throw'Loading data file "'+a+'" failed.';});d&&vb(d)}var rc=null,sc={},tc=[],uc=1,vc=null,pb=!0,R=null,oc={};
function wc(a,b){a=cc("/",a);b=b||{};if(!a)return{path:"",node:null};var c={Rc:!0,Dc:0},d;for(d in c)void 0===b[d]&&(b[d]=c[d]);if(8<b.Dc)throw new R(32);a=Yb(a.split("/").filter(function(h){return!!h}),!1);var e=rc;c="/";for(d=0;d<a.length;d++){var f=d===a.length-1;if(f&&b.parent)break;e=pc(e,a[d]);c=Zb(c+"/"+a[d]);e.Ub&&(!f||f&&b.Rc)&&(e=e.Ub.root);if(!f||b.hc)for(f=0;40960===(e.mode&61440);)if(e=xc(c),c=cc($b(c),e),e=wc(c,{Dc:b.Dc}).node,40<f++)throw new R(32);}return{path:c,node:e}}
function yc(a){for(var b;;){if(a===a.parent)return a=a.Gb.Vc,b?"/"!==a[a.length-1]?a+"/"+b:a+b:a;b=b?a.name+"/"+b:a.name;a=a.parent}}function zc(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%vc.length}function pc(a,b){var c;if(c=(c=Ac(a,"x"))?c:a.lb.Tb?0:2)throw new R(c,a);for(c=vc[zc(a.id,b)];c;c=c.Ob){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.lb.Tb(a,b)}
function nc(a,b,c,d){a=new Bc(a,b,c,d);b=zc(a.parent.id,a.name);a.Ob=vc[b];return vc[b]=a}var Cc={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090};function Dc(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}function Ac(a,b){if(pb)return 0;if(!b.includes("r")||a.mode&292){if(b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73))return 2}else return 2;return 0}function Ec(a,b){try{return pc(a,b),20}catch(c){}return Ac(a,"wx")}
function Fc(a){var b=4096;for(a=a||0;a<=b;a++)if(!tc[a])return a;throw new R(33);}function Gc(a,b){Hc||(Hc=function(){},Hc.prototype={object:{get:function(){return this.node},set:function(e){this.node=e}}});var c=new Hc,d;for(d in a)c[d]=a[d];a=c;b=Fc(b);a.Cb=b;return tc[b]=a}var mc={open:function(a){a.nb=sc[a.node.Wb].nb;a.nb.open&&a.nb.open(a)},Kb:function(){throw new R(70);}};function fc(a,b){sc[a]={nb:b}}
function Ic(a,b){var c="/"===b,d=!b;if(c&&rc)throw new R(10);if(!c&&!d){var e=wc(b,{Rc:!1});b=e.path;e=e.node;if(e.Ub)throw new R(10);if(16384!==(e.mode&61440))throw new R(54);}b={type:a,ue:{},Vc:b,Kd:[]};a=a.Gb(b);a.Gb=b;b.root=a;c?rc=a:e&&(e.Ub=b,e.Gb&&e.Gb.Kd.push(b))}function Jc(a,b,c){var d=wc(a,{parent:!0}).node;a=ac(a);if(!a||"."===a||".."===a)throw new R(28);var e=Ec(d,a);if(e)throw new R(e);if(!d.lb.lc)throw new R(63);return d.lb.lc(d,a,b,c)}function Kc(a){return Jc(a,16895,0)}
function Lc(a,b,c){"undefined"===typeof c&&(c=b,b=438);return Jc(a,b|8192,c)}function nb(a,b){if(!cc(a))throw new R(44);var c=wc(b,{parent:!0}).node;if(!c)throw new R(44);b=ac(b);var d=Ec(c,b);if(d)throw new R(d);if(!c.lb.oc)throw new R(63);c.lb.oc(c,b,a)}
function Mc(a){var b=wc(a,{parent:!0}).node;if(!b)throw new R(44);var c=ac(a);a=pc(b,c);a:{try{var d=pc(b,c)}catch(f){d=f.tb;break a}var e=Ac(b,"wx");d=e?e:16384===(d.mode&61440)?31:0}if(d)throw new R(d);if(!b.lb.sc)throw new R(63);if(a.Ub)throw new R(10);b.lb.sc(b,c);b=zc(a.parent.id,a.name);if(vc[b]===a)vc[b]=a.Ob;else for(b=vc[b];b;){if(b.Ob===a){b.Ob=a.Ob;break}b=b.Ob}}function xc(a){a=wc(a).node;if(!a)throw new R(44);if(!a.lb.Xb)throw new R(28);return cc(yc(a.parent),a.lb.Xb(a))}
function Nc(a,b){a=wc(a,{hc:!b}).node;if(!a)throw new R(44);if(!a.lb.Db)throw new R(63);return a.lb.Db(a)}function Oc(a){return Nc(a,!0)}function Pc(a,b){a="string"===typeof a?wc(a,{hc:!0}).node:a;if(!a.lb.xb)throw new R(63);a.lb.xb(a,{mode:b&4095|a.mode&-4096,timestamp:Date.now()})}
function ob(a,b,c,d){if(""===a)throw new R(44);if("string"===typeof b){var e=Cc[b];if("undefined"===typeof e)throw Error("Unknown file open mode: "+b);b=e}c=b&64?("undefined"===typeof c?438:c)&4095|32768:0;if("object"===typeof a)var f=a;else{a=Zb(a);try{f=wc(a,{hc:!(b&131072)}).node}catch(h){}}e=!1;if(b&64)if(f){if(b&128)throw new R(20);}else f=Jc(a,c,0),e=!0;if(!f)throw new R(44);8192===(f.mode&61440)&&(b&=-513);if(b&65536&&16384!==(f.mode&61440))throw new R(54);if(!e&&(c=f?40960===(f.mode&61440)?
32:16384===(f.mode&61440)&&("r"!==Dc(b)||b&512)?31:Ac(f,Dc(b)):44))throw new R(c);if(b&512){c=f;c="string"===typeof c?wc(c,{hc:!0}).node:c;if(!c.lb.xb)throw new R(63);if(16384===(c.mode&61440))throw new R(31);if(32768!==(c.mode&61440))throw new R(28);if(e=Ac(c,"w"))throw new R(e);c.lb.xb(c,{size:0,timestamp:Date.now()})}b&=-131713;d=Gc({node:f,path:yc(f),id:f.id,flags:b,mode:f.mode,seekable:!0,position:0,nb:f.nb,lb:f.lb,ge:[],error:!1},d);d.nb.open&&d.nb.open(d);!D.logReadFiles||b&1||(Qc||(Qc={}),
a in Qc||(Qc[a]=1));return d}function Rc(a){if(null===a.Cb)throw new R(8);a.vc&&(a.vc=null);try{a.nb.close&&a.nb.close(a)}catch(b){throw b;}finally{tc[a.Cb]=null}a.Cb=null}function Sc(a,b,c){if(null===a.Cb)throw new R(8);if(!a.seekable||!a.nb.Kb)throw new R(70);if(0!=c&&1!=c&&2!=c)throw new R(28);a.position=a.nb.Kb(a,b,c);a.ge=[]}
function Tc(a,b,c,d,e,f){if(0>d||0>e)throw new R(28);if(null===a.Cb)throw new R(8);if(0===(a.flags&2097155))throw new R(8);if(16384===(a.node.mode&61440))throw new R(31);if(!a.nb.write)throw new R(28);a.seekable&&a.flags&1024&&Sc(a,0,2);var h="undefined"!==typeof e;if(!h)e=a.position;else if(!a.seekable)throw new R(70);b=a.nb.write(a,b,c,d,e,f);h||(a.position+=b);return b}
function lb(){R||(R=function(a,b){this.node=b;this.Vd=function(c){this.tb=c};this.Vd(a);this.message="FS error"},R.prototype=Error(),R.prototype.constructor=R,[44].forEach(function(a){oc[a]=new R(a);oc[a].stack="<generic error, no stack>"}))}var kb;function Uc(a,b){var c=0;a&&(c|=365);b&&(c|=146);return c}function Vc(a,b){a="string"===typeof a?a:yc(a);for(b=b.split("/").reverse();b.length;){var c=b.pop();if(c){var d=Zb(a+"/"+c);try{Kc(d)}catch(e){}a=d}}return d}
function Wc(a,b,c,d){a=Zb(("string"===typeof a?a:yc(a))+"/"+b);c=Uc(c,d);return Jc(a,(void 0!==c?c:438)&4095|32768,0)}function Xc(a,b,c,d,e,f){a=b?Zb(("string"===typeof a?a:yc(a))+"/"+b):a;d=Uc(d,e);e=Jc(a,(void 0!==d?d:438)&4095|32768,0);if(c){if("string"===typeof c){a=Array(c.length);b=0;for(var h=c.length;b<h;++b)a[b]=c.charCodeAt(b);c=a}Pc(e,d|146);a=ob(e,577);Tc(a,c,0,c.length,0,f);Rc(a);Pc(e,d)}return e}
function mb(a,b,c,d){a=Zb(("string"===typeof a?a:yc(a))+"/"+b);b=Uc(!!c,!!d);mb.Uc||(mb.Uc=64);var e=mb.Uc++<<8|0;fc(e,{open:function(f){f.seekable=!1},close:function(){d&&d.buffer&&d.buffer.length&&d(10)},read:function(f,h,l,m){for(var q=0,p=0;p<m;p++){try{var t=c()}catch(v){throw new R(29);}if(void 0===t&&0===q)throw new R(6);if(null===t||void 0===t)break;q++;h[l+p]=t}q&&(f.node.timestamp=Date.now());return q},write:function(f,h,l,m){for(var q=0;q<m;q++)try{d(h[l+q])}catch(p){throw new R(29);}m&&
(f.node.timestamp=Date.now());return q}});return Lc(a,b,e)}function Yc(a){if(!(a.Ed||a.Fd||a.link||a.mb)){if("undefined"!==typeof XMLHttpRequest)throw Error("Lazy loading should have been performed (contents set) in createLazyFile, but it was not. Lazy loading only works in web workers. Use --embed-file or --preload-file in emcc on the main thread.");if(Aa)try{a.mb=hc(Aa(a.url),!0),a.qb=a.mb.length}catch(b){throw new R(29);}else throw Error("Cannot load without read() or XMLHttpRequest.");}}
function Zc(a,b,c,d,e){function f(){this.yc=!1;this.fc=[]}f.prototype.get=function(p){if(!(p>this.length-1||0>p)){var t=p%this.Mc;return this.ic(p/this.Mc|0)[t]}};f.prototype.Ud=function(p){this.ic=p};f.prototype.Kc=function(){var p=new XMLHttpRequest;p.open("HEAD",c,!1);p.send(null);if(!(200<=p.status&&300>p.status||304===p.status))throw Error("Couldn't load "+c+". Status: "+p.status);var t=Number(p.getResponseHeader("Content-length")),v,k=(v=p.getResponseHeader("Accept-Ranges"))&&"bytes"===v;p=
(v=p.getResponseHeader("Content-Encoding"))&&"gzip"===v;var u=1048576;k||(u=t);var x=this;x.Ud(function(A){var H=A*u,J=(A+1)*u-1;J=Math.min(J,t-1);if("undefined"===typeof x.fc[A]){var ma=x.fc;if(H>J)throw Error("invalid range ("+H+", "+J+") or no bytes requested!");if(J>t-1)throw Error("only "+t+" bytes available! programmer error!");var w=new XMLHttpRequest;w.open("GET",c,!1);t!==u&&w.setRequestHeader("Range","bytes="+H+"-"+J);"undefined"!=typeof Uint8Array&&(w.responseType="arraybuffer");w.overrideMimeType&&
w.overrideMimeType("text/plain; charset=x-user-defined");w.send(null);if(!(200<=w.status&&300>w.status||304===w.status))throw Error("Couldn't load "+c+". Status: "+w.status);H=void 0!==w.response?new Uint8Array(w.response||[]):hc(w.responseText||"",!0);ma[A]=H}if("undefined"===typeof x.fc[A])throw Error("doXHR failed!");return x.fc[A]});if(p||!t)u=t=1,u=t=this.ic(0).length,Da("LazyFiles on gzip forces download of the whole file when length is accessed");this.fd=t;this.ed=u;this.yc=!0};if("undefined"!==
typeof XMLHttpRequest){if(!wa)throw"Cannot do synchronous binary XHRs outside webworkers in modern browsers. Use --embed-file or --preload-file in emcc";var h=new f;Object.defineProperties(h,{length:{get:function(){this.yc||this.Kc();return this.fd}},Mc:{get:function(){this.yc||this.Kc();return this.ed}}});var l=void 0}else l=c,h=void 0;var m=Wc(a,b,d,e);h?m.mb=h:l&&(m.mb=null,m.url=l);Object.defineProperties(m,{qb:{get:function(){return this.mb.length}}});var q={};Object.keys(m.nb).forEach(function(p){var t=
m.nb[p];q[p]=function(){Yc(m);return t.apply(null,arguments)}});q.read=function(p,t,v,k,u){Yc(m);p=p.node.mb;if(u>=p.length)return 0;k=Math.min(p.length-u,k);if(p.slice)for(var x=0;x<k;x++)t[v+x]=p[u+x];else for(x=0;x<k;x++)t[v+x]=p.get(u+x);return k};m.nb=q;return m}
function $c(a,b,c,d,e,f,h,l,m,q){function p(k){function u(A){q&&q();l||Xc(a,b,A,d,e,m);f&&f();wb(v)}var x=!1;D.preloadPlugins.forEach(function(A){!x&&A.canHandle(t)&&(A.handle(k,t,u,function(){h&&h();wb(v)}),x=!0)});x||u(k)}ad.pe();var t=b?cc(Zb(a+"/"+b)):a,v="cp "+t;vb(v);"string"==typeof c?qc(c,function(k){p(k)},h):p(c)}var T={},Hc,Qc,bd={};
function cd(a,b,c){try{var d=a(b)}catch(e){if(e&&e.node&&Zb(b)!==Zb(yc(e.node)))return-54;throw e;}B()[c>>2]=d.qd;B()[c+4>>2]=0;B()[c+8>>2]=d.wc;B()[c+12>>2]=d.mode;B()[c+16>>2]=d.Md;B()[c+20>>2]=d.uid;B()[c+24>>2]=d.zd;B()[c+28>>2]=d.Wb;B()[c+32>>2]=0;Bb=[d.size>>>0,(N=d.size,1<=+Math.abs(N)?0<N?(Math.min(+Math.floor(N/4294967296),4294967295)|0)>>>0:~~+Math.ceil((N-+(~~N>>>0))/4294967296)>>>0:0)];B()[c+40>>2]=Bb[0];B()[c+44>>2]=Bb[1];B()[c+48>>2]=4096;B()[c+52>>2]=d.ld;B()[c+56>>2]=d.jd.getTime()/
1E3|0;B()[c+60>>2]=0;B()[c+64>>2]=d.Ld.getTime()/1E3|0;B()[c+68>>2]=0;B()[c+72>>2]=d.od.getTime()/1E3|0;B()[c+76>>2]=0;Bb=[d.wc>>>0,(N=d.wc,1<=+Math.abs(N)?0<N?(Math.min(+Math.floor(N/4294967296),4294967295)|0)>>>0:~~+Math.ceil((N-+(~~N>>>0))/4294967296)>>>0:0)];B()[c+80>>2]=Bb[0];B()[c+84>>2]=Bb[1];return 0}var dd=void 0;function ed(){dd+=4;return B()[dd-4>>2]}function fd(a){a=tc[a];if(!a)throw new R(8);return a}
function gd(a,b,c){if(F)return Q(3,1,a,b,c);dd=c;try{var d=fd(a);switch(b){case 0:var e=ed();return 0>e?-28:ob(d.path,d.flags,0,e).Cb;case 1:case 2:return 0;case 3:return d.flags;case 4:return e=ed(),d.flags|=e,0;case 5:return e=ed(),da()[e+0>>1]=2,0;case 6:case 7:return 0;case 16:case 8:return-28;case 9:return-1;default:return-28}}catch(f){if("undefined"===typeof T||!(f instanceof R))throw f;return-f.tb}}
function hd(a,b){if(F)return Q(4,1,a,b);try{var c=fd(a);return cd(Nc,c.path,b)}catch(d){if("undefined"===typeof T||!(d instanceof R))throw d;return-d.tb}}function jd(a,b,c,d){if(F)return Q(5,1,a,b,c,d);try{b=I(b);var e=d&256;d&=4096;var f=b;if("/"===f[0])b=f;else{if(-100===a)var h="/";else{var l=tc[a];if(!l)throw new R(8);h=l.path}if(0==f.length){if(!d)throw new R(44);b=h}else b=Zb(h+"/"+f)}return cd(e?Oc:Nc,b,c)}catch(m){if("undefined"===typeof T||!(m instanceof R))throw m;return-m.tb}}
function kd(a,b,c){if(F)return Q(6,1,a,b,c);dd=c;try{var d=fd(a);switch(b){case 21509:case 21505:return d.sb?0:-59;case 21510:case 21511:case 21512:case 21506:case 21507:case 21508:return d.sb?0:-59;case 21519:if(!d.sb)return-59;var e=ed();return B()[e>>2]=0;case 21520:return d.sb?-28:-59;case 21531:a=e=ed();if(!d.nb.Dd)throw new R(59);return d.nb.Dd(d,b,a);case 21523:return d.sb?0:-59;case 21524:return d.sb?0:-59;default:Ha("bad ioctl syscall "+b)}}catch(f){if("undefined"===typeof T||!(f instanceof
R))throw f;return-f.tb}}
function ld(a,b,c,d,e,f){if(F)return Q(8,1,a,b,c,d,e,f);try{a:{f<<=12;var h=!1;if(0!==(d&16)&&0!==a%65536)var l=-28;else{if(0!==(d&32)){var m=kc(b);if(!m){l=-48;break a}h=!0}else{var q=tc[e];if(!q){l=-8;break a}var p=f;if(0!==(c&2)&&0===(d&2)&&2!==(q.flags&2097155))throw new R(2);if(1===(q.flags&2097155))throw new R(2);if(!q.nb.mc)throw new R(43);var t=q.nb.mc(q,a,b,p,c,d);m=t.pb;h=t.tc}bd[m]={Jd:m,Hd:b,tc:h,Cb:e,Od:c,flags:d,offset:f};l=m}}return l}catch(v){if("undefined"===typeof T||!(v instanceof
R))throw v;return-v.tb}}function md(a,b){if(F)return Q(9,1,a,b);try{var c=bd[a];if(0!==b&&c){if(b===c.Hd){var d=tc[c.Cb];if(d&&c.Od&2){var e=c.flags,f=c.offset,h=y().slice(a,a+b);d&&d.nb.nc&&d.nb.nc(d,h,f,b,e)}bd[a]=null;c.tc&&nd(c.Jd)}var l=0}else l=-28;return l}catch(m){if("undefined"===typeof T||!(m instanceof R))throw m;return-m.tb}}
function od(a,b,c){if(F)return Q(10,1,a,b,c);dd=c;try{var d=I(a),e=c?ed():0;return ob(d,b,e).Cb}catch(f){if("undefined"===typeof T||!(f instanceof R))throw f;return-f.tb}}function pd(a,b){if(F)return Q(11,1,a,b);try{return a=I(a),cd(Nc,a,b)}catch(c){if("undefined"===typeof T||!(c instanceof R))throw c;return-c.tb}}var qd={};function rd(a){for(;a.length;){var b=a.pop();a.pop()(b)}}function sd(a){return this.fromWireType(C()[a>>2])}var td={},ud={},vd={};
function wd(a){if(void 0===a)return"_unknown";a=a.replace(/[^a-zA-Z0-9_]/g,"$");var b=a.charCodeAt(0);return 48<=b&&57>=b?"_"+a:a}function xd(a,b){a=wd(a);return(new Function("body","return function "+a+'() {\n    "use strict";    return body.apply(this, arguments);\n};\n'))(b)}
function yd(a){var b=Error,c=xd(a,function(d){this.name=a;this.message=d;d=Error(d).stack;void 0!==d&&(this.stack=this.toString()+"\n"+d.replace(/^Error(:[^\n]*)?\n/,""))});c.prototype=Object.create(b.prototype);c.prototype.constructor=c;c.prototype.toString=function(){return void 0===this.message?this.name:this.name+": "+this.message};return c}var zd=void 0;function Ad(a){throw new zd(a);}
function Bd(a,b,c){function d(l){l=c(l);l.length!==a.length&&Ad("Mismatched type converter count");for(var m=0;m<a.length;++m)Cd(a[m],l[m])}a.forEach(function(l){vd[l]=b});var e=Array(b.length),f=[],h=0;b.forEach(function(l,m){ud.hasOwnProperty(l)?e[m]=ud[l]:(f.push(l),td.hasOwnProperty(l)||(td[l]=[]),td[l].push(function(){e[m]=ud[l];++h;h===f.length&&d(e)}))});0===f.length&&d(e)}
function Dd(a){switch(a){case 1:return 0;case 2:return 1;case 4:return 2;case 8:return 3;default:throw new TypeError("Unknown type size: "+a);}}var Ed=void 0;function U(a){for(var b="";y()[a];)b+=Ed[y()[a++]];return b}var Fd=void 0;function V(a){throw new Fd(a);}
function Cd(a,b,c){c=c||{};if(!("argPackAdvance"in b))throw new TypeError("registerType registeredInstance requires argPackAdvance");var d=b.name;a||V('type "'+d+'" must have a positive integer typeid pointer');if(ud.hasOwnProperty(a)){if(c.Ad)return;V("Cannot register type '"+d+"' twice")}ud[a]=b;delete vd[a];td.hasOwnProperty(a)&&(b=td[a],delete td[a],b.forEach(function(e){e()}))}function Gd(a){V(a.kb.rb.ob.name+" instance already deleted")}var Hd=!1;function Id(){}
function Jd(a){--a.count.value;0===a.count.value&&(a.yb?a.zb.Hb(a.yb):a.rb.ob.Hb(a.pb))}function Kd(a){if("undefined"===typeof FinalizationGroup)return Kd=function(b){return b},a;Hd=new FinalizationGroup(function(b){for(var c=b.next();!c.done;c=b.next())c=c.value,c.pb?Jd(c):console.warn("object already deleted: "+c.pb)});Kd=function(b){Hd.register(b,b.kb,b.kb);return b};Id=function(b){Hd.unregister(b.kb)};return Kd(a)}var Ld=void 0,Md=[];
function Nd(){for(;Md.length;){var a=Md.pop();a.kb.Mb=!1;a["delete"]()}}function Od(){}var Pd={};function Qd(a,b,c){if(void 0===a[b].vb){var d=a[b];a[b]=function(){a[b].vb.hasOwnProperty(arguments.length)||V("Function '"+c+"' called with an invalid number of arguments ("+arguments.length+") - expects one of ("+a[b].vb+")!");return a[b].vb[arguments.length].apply(this,arguments)};a[b].vb=[];a[b].vb[d.dc]=d}}
function Rd(a,b,c){D.hasOwnProperty(a)?((void 0===c||void 0!==D[a].vb&&void 0!==D[a].vb[c])&&V("Cannot register public name '"+a+"' twice"),Qd(D,a,a),D.hasOwnProperty(c)&&V("Cannot register multiple overloads of a function with the same number of arguments ("+c+")!"),D[a].vb[c]=b):(D[a]=b,void 0!==c&&(D[a].te=c))}function Sd(a,b,c,d,e,f,h,l){this.name=a;this.constructor=b;this.Nb=c;this.Hb=d;this.Ab=e;this.ud=f;this.ac=h;this.rd=l;this.Pd=[]}
function Td(a,b,c){for(;b!==c;)b.ac||V("Expected null or instance of "+c.name+", got an instance of "+b.name),a=b.ac(a),b=b.Ab;return a}function Ud(a,b){if(null===b)return this.xc&&V("null is not a valid "+this.name),0;b.kb||V('Cannot pass "'+Vd(b)+'" as a '+this.name);b.kb.pb||V("Cannot pass deleted object as a pointer of type "+this.name);return Td(b.kb.pb,b.kb.rb.ob,this.ob)}
function Wd(a,b){if(null===b){this.xc&&V("null is not a valid "+this.name);if(this.kc){var c=this.Cc();null!==a&&a.push(this.Hb,c);return c}return 0}b.kb||V('Cannot pass "'+Vd(b)+'" as a '+this.name);b.kb.pb||V("Cannot pass deleted object as a pointer of type "+this.name);!this.jc&&b.kb.rb.jc&&V("Cannot convert argument of type "+(b.kb.zb?b.kb.zb.name:b.kb.rb.name)+" to parameter type "+this.name);c=Td(b.kb.pb,b.kb.rb.ob,this.ob);if(this.kc)switch(void 0===b.kb.yb&&V("Passing raw pointer to smart pointer is illegal"),
this.$d){case 0:b.kb.zb===this?c=b.kb.yb:V("Cannot convert argument of type "+(b.kb.zb?b.kb.zb.name:b.kb.rb.name)+" to parameter type "+this.name);break;case 1:c=b.kb.yb;break;case 2:if(b.kb.zb===this)c=b.kb.yb;else{var d=b.clone();c=this.Qd(c,W(function(){d["delete"]()}));null!==a&&a.push(this.Hb,c)}break;default:V("Unsupporting sharing policy")}return c}
function Xd(a,b){if(null===b)return this.xc&&V("null is not a valid "+this.name),0;b.kb||V('Cannot pass "'+Vd(b)+'" as a '+this.name);b.kb.pb||V("Cannot pass deleted object as a pointer of type "+this.name);b.kb.rb.jc&&V("Cannot convert argument of type "+b.kb.rb.name+" to parameter type "+this.name);return Td(b.kb.pb,b.kb.rb.ob,this.ob)}function Yd(a,b,c){if(b===c)return a;if(void 0===c.Ab)return null;a=Yd(a,b,c.Ab);return null===a?null:c.rd(a)}var Zd={};
function $d(a,b){for(void 0===b&&V("ptr should not be undefined");a.Ab;)b=a.ac(b),a=a.Ab;return Zd[b]}function ae(a,b){b.rb&&b.pb||Ad("makeClassHandle requires ptr and ptrType");!!b.zb!==!!b.yb&&Ad("Both smartPtrType and smartPtr must be specified");b.count={value:1};return Kd(Object.create(a,{kb:{value:b}}))}
function be(a,b,c,d){this.name=a;this.ob=b;this.xc=c;this.jc=d;this.kc=!1;this.Hb=this.Qd=this.Cc=this.Zc=this.$d=this.Nd=void 0;void 0!==b.Ab?this.toWireType=Wd:(this.toWireType=d?Ud:Xd,this.Bb=null)}function ce(a,b,c){D.hasOwnProperty(a)||Ad("Replacing nonexistant public symbol");void 0!==D[a].vb&&void 0!==c?D[a].vb[c]=b:(D[a]=b,D[a].dc=c)}
function de(a,b){var c=[];return function(){c.length=arguments.length;for(var d=0;d<arguments.length;d++)c[d]=arguments[d];a.includes("j")?(d=D["dynCall_"+a],d=c&&c.length?d.apply(null,[b].concat(c)):d.call(null,b)):d=O(b).apply(null,c);return d}}function ee(a,b){a=U(a);var c=a.includes("j")?de(a,b):O(b);"function"!==typeof c&&V("unknown function pointer with signature "+a+": "+b);return c}var fe=void 0;function ge(a){a=he(a);var b=U(a);nd(a);return b}
function ie(a,b){function c(f){e[f]||ud[f]||(vd[f]?vd[f].forEach(c):(d.push(f),e[f]=!0))}var d=[],e={};b.forEach(c);throw new fe(a+": "+d.map(ge).join([", "]));}function je(a,b){for(var c=[],d=0;d<a;d++)c.push(B()[(b>>2)+d]);return c}
function ke(a){var b=Function;if(!(b instanceof Function))throw new TypeError("new_ called with constructor type "+typeof b+" which is not a function");var c=xd(b.name||"unknownFunctionName",function(){});c.prototype=b.prototype;c=new c;a=b.apply(c,a);return a instanceof Object?a:c}
function le(a,b,c,d,e){var f=b.length;2>f&&V("argTypes array size mismatch! Must at least get return value and 'this' types!");var h=null!==b[1]&&null!==c,l=!1;for(c=1;c<b.length;++c)if(null!==b[c]&&void 0===b[c].Bb){l=!0;break}var m="void"!==b[0].name,q="",p="";for(c=0;c<f-2;++c)q+=(0!==c?", ":"")+"arg"+c,p+=(0!==c?", ":"")+"arg"+c+"Wired";a="return function "+wd(a)+"("+q+") {\nif (arguments.length !== "+(f-2)+") {\nthrowBindingError('function "+a+" called with ' + arguments.length + ' arguments, expected "+
(f-2)+" args!');\n}\n";l&&(a+="var destructors = [];\n");var t=l?"destructors":"null";q="throwBindingError invoker fn runDestructors retType classParam".split(" ");d=[V,d,e,rd,b[0],b[1]];h&&(a+="var thisWired = classParam.toWireType("+t+", this);\n");for(c=0;c<f-2;++c)a+="var arg"+c+"Wired = argType"+c+".toWireType("+t+", arg"+c+"); // "+b[c+2].name+"\n",q.push("argType"+c),d.push(b[c+2]);h&&(p="thisWired"+(0<p.length?", ":"")+p);a+=(m?"var rv = ":"")+"invoker(fn"+(0<p.length?", ":"")+p+");\n";if(l)a+=
"runDestructors(destructors);\n";else for(c=h?1:2;c<b.length;++c)f=1===c?"thisWired":"arg"+(c-2)+"Wired",null!==b[c].Bb&&(a+=f+"_dtor("+f+"); // "+b[c].name+"\n",q.push(f+"_dtor"),d.push(b[c].Bb));m&&(a+="var ret = retType.fromWireType(rv);\nreturn ret;\n");q.push(a+"}\n");return ke(q).apply(null,d)}var me=[],X=[{},{value:void 0},{value:null},{value:!0},{value:!1}];function ne(a){4<a&&0===--X[a].Ec&&(X[a]=void 0,me.push(a))}
function Y(a){a||V("Cannot use deleted val. handle = "+a);return X[a].value}function W(a){switch(a){case void 0:return 1;case null:return 2;case !0:return 3;case !1:return 4;default:var b=me.length?me.pop():X.length;X[b]={Ec:1,value:a};return b}}function Vd(a){if(null===a)return"null";var b=typeof a;return"object"===b||"array"===b||"function"===b?a.toString():""+a}
function oe(a,b){switch(b){case 2:return function(c){var d=this.fromWireType;n.buffer!=r&&aa(n.buffer);return d.call(this,$a[c>>2])};case 3:return function(c){return this.fromWireType(ja()[c>>3])};default:throw new TypeError("Unknown float type: "+a);}}
function pe(a,b,c){switch(b){case 0:return c?function(d){return g()[d]}:function(d){return y()[d]};case 1:return c?function(d){return da()[d>>1]}:function(d){return z()[d>>1]};case 2:return c?function(d){return B()[d>>2]}:function(d){return C()[d>>2]};default:throw new TypeError("Unknown integer type: "+a);}}function qe(a,b){var c=ud[a];void 0===c&&V(b+" has unknown type "+ge(a));return c}function re(a,b){for(var c=Array(a),d=0;d<a;++d)c[d]=qe(B()[(b>>2)+d],"parameter "+d);return c}var se={};
function te(a){var b=se[a];return void 0===b?U(a):b}var ue=[];function ve(){return"object"===typeof globalThis?globalThis:Function("return this")()}function we(a){var b=ue.length;ue.push(a);return b}var xe=[],ye={},ze=[];function Q(a,b){var c=arguments.length-2,d=arguments;return Db(function(){for(var e=Ae(8*c),f=e>>3,h=0;h<c;h++){var l=d[2+h];ja()[f+h]=l}return Be(a,c,e,b)})}var Ce=[];
function De(a,b,c,d){Db(function(){var e=Ae(12),f=0;if(b){f=Pa(b)+1;var h=Ya(f);K(b,h,f);f=h}B()[e>>2]=f;B()[e+4>>2]=c;B()[e+8>>2]=d;Ee(a,657457152,0,f,e)})}var Fe=[0,"undefined"!==typeof document?document:0,"undefined"!==typeof window?window:0];function Ge(a){a=2<a?I(a):a;return Fe[a]||("undefined"!==typeof document?document.querySelector(a):void 0)}
function He(a,b,c){var d=Ge(a);if(!d)return-4;d.ec&&(B()[d.ec>>2]=b,B()[d.ec+4>>2]=c);if(d.Wc||!d.je)d.Wc&&(d=d.Wc),a=!1,d.cc&&d.cc.bc&&(a=d.cc.bc.getParameter(2978),a=0===a[0]&&0===a[1]&&a[2]===d.width&&a[3]===d.height),d.width=b,d.height=c,a&&d.cc.bc.viewport(0,0,b,c);else return d.ec?(d=B()[d.ec+8>>2],a=a?I(a):"",De(d,a,b,c),1):-4;return 0}function Ie(a,b,c){return F?Q(12,1,a,b,c):He(a,b,c)}var Je=[];function Z(a,b){C()[a>>2]=b;C()[a+4>>2]=b/4294967296|0}
function Ke(a,b){try{var c=indexedDB.open("emscripten_filesystem",1)}catch(d){b(d);return}c.onupgradeneeded=function(d){d=d.target.result;d.objectStoreNames.contains("FILES")&&d.deleteObjectStore("FILES");d.createObjectStore("FILES")};c.onsuccess=function(d){a(d.target.result)};c.onerror=function(d){b(d)}}var Le;
function Me(a,b,c,d,e){function f(L){var M=0,G=0;L&&(G=w.response?w.response.byteLength:0,M=Ya(G),y().set(new Uint8Array(w.response),M));C()[a+12>>2]=M;Z(a+16,G)}var h=C()[a+8>>2];if(h){var l=I(h),m=a+112,q=I(m);q||(q="GET");C();var p=C()[m+52>>2],t=C()[m+56>>2],v=!!C()[m+60>>2];C();var k=C()[m+68>>2],u=C()[m+72>>2],x=C()[m+76>>2],A=C()[m+80>>2];h=C()[m+84>>2];m=C()[m+88>>2];var H=!!(p&1),J=!!(p&2);p=!!(p&64);k=k?I(k):void 0;u=u?I(u):void 0;var ma=A?I(A):void 0,w=new XMLHttpRequest;w.withCredentials=
v;w.open(q,l,!p,k,u);p||(w.timeout=t);w.ze=l;w.responseType="arraybuffer";A&&w.overrideMimeType(ma);if(x)for(;;){q=C()[x>>2];if(!q)break;l=C()[x+4>>2];if(!l)break;x+=8;q=I(q);l=I(l);w.setRequestHeader(q,l)}Je.push(w);x=Je.length;C()[a+0>>2]=x;h=h&&m?y().slice(h,h+m):null;w.onload=function(L){f(H&&!J);var M=w.response?w.response.byteLength:0;Z(a+24,0);M&&Z(a+32,M);z()[a+40>>1]=w.readyState;z()[a+42>>1]=w.status;w.statusText&&K(w.statusText,a+44,64);200<=w.status&&300>w.status?b&&b(a,w,L):c&&c(a,w,
L)};w.onerror=function(L){f(H);var M=w.status;Z(a+24,0);Z(a+32,w.response?w.response.byteLength:0);z()[a+40>>1]=w.readyState;z()[a+42>>1]=M;c&&c(a,w,L)};w.ontimeout=function(L){c&&c(a,w,L)};w.onprogress=function(L){var M=H&&J&&w.response?w.response.byteLength:0,G=0;H&&J&&(G=Ya(M),y().set(new Uint8Array(w.response),G));C()[a+12>>2]=G;Z(a+16,M);Z(a+24,L.loaded-M);Z(a+32,L.total);z()[a+40>>1]=w.readyState;3<=w.readyState&&0===w.status&&0<L.loaded&&(w.status=200);z()[a+42>>1]=w.status;w.statusText&&K(w.statusText,
a+44,64);d&&d(a,w,L);G&&nd(G)};w.onreadystatechange=function(L){z()[a+40>>1]=w.readyState;2<=w.readyState&&(z()[a+42>>1]=w.status);e&&e(a,w,L)};try{w.send(h)}catch(L){c&&c(a,w,L)}}else c(a,0,"no url specified!")}function Ne(a,b){if(!gb&&!Ja)if(b)a();else try{if(a(),F&&!ib())try{F?Oe(Ka):Qb(Ka)}catch(c){Hb(c)}}catch(c){Hb(c)}}
function Pe(a,b,c,d){var e=Le;if(e){var f=a+112;(f=C()[f+64>>2])||(f=C()[a+8>>2]);var h=I(f);try{var l=e.transaction(["FILES"],"readwrite").objectStore("FILES").put(b,h);l.onsuccess=function(){z()[a+40>>1]=4;z()[a+42>>1]=200;K("OK",a+44,64);c(a,0,h)};l.onerror=function(m){z()[a+40>>1]=4;z()[a+42>>1]=413;K("Payload Too Large",a+44,64);d(a,0,m)}}catch(m){d(a,0,m)}}else d(a,0,"IndexedDB not available!")}
function Qe(a,b,c){var d=Le;if(d){var e=a+112;(e=C()[e+64>>2])||(e=C()[a+8>>2]);e=I(e);try{var f=d.transaction(["FILES"],"readonly").objectStore("FILES").get(e);f.onsuccess=function(h){if(h.target.result){h=h.target.result;var l=h.byteLength||h.length,m=Ya(l);y().set(new Uint8Array(h),m);C()[a+12>>2]=m;Z(a+16,l);Z(a+24,0);Z(a+32,l);z()[a+40>>1]=4;z()[a+42>>1]=200;K("OK",a+44,64);b(a,0,h)}else z()[a+40>>1]=4,z()[a+42>>1]=404,K("Not Found",a+44,64),c(a,0,"no data")};f.onerror=function(h){z()[a+40>>
1]=4;z()[a+42>>1]=404;K("Not Found",a+44,64);c(a,0,h)}}catch(h){c(a,0,h)}}else c(a,0,"IndexedDB not available!")}
function Re(a,b,c){var d=Le;if(d){var e=a+112;(e=C()[e+64>>2])||(e=C()[a+8>>2]);e=I(e);try{var f=d.transaction(["FILES"],"readwrite").objectStore("FILES").delete(e);f.onsuccess=function(h){h=h.target.result;C()[a+12>>2]=0;Z(a+16,0);Z(a+24,0);Z(a+32,0);z()[a+40>>1]=4;z()[a+42>>1]=200;K("OK",a+44,64);b(a,0,h)};f.onerror=function(h){z()[a+40>>1]=4;z()[a+42>>1]=404;K("Not Found",a+44,64);c(a,0,h)}}catch(h){c(a,0,h)}}else c(a,0,"IndexedDB not available!")}
function Se(a){var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=function(c,d){b.vertexAttribDivisorANGLE(c,d)},a.drawArraysInstanced=function(c,d,e,f){b.drawArraysInstancedANGLE(c,d,e,f)},a.drawElementsInstanced=function(c,d,e,f,h){b.drawElementsInstancedANGLE(c,d,e,f,h)})}
function Te(a){var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=function(){return b.createVertexArrayOES()},a.deleteVertexArray=function(c){b.deleteVertexArrayOES(c)},a.bindVertexArray=function(c){b.bindVertexArrayOES(c)},a.isVertexArray=function(c){return b.isVertexArrayOES(c)})}function Ue(a){var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=function(c,d){b.drawBuffersWEBGL(c,d)})}
function Ve(a,b){a.Sc||(a.Sc=a.getContext,a.getContext=function(d,e){e=a.Sc(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null});var c=a.getContext("webgl",b);return c?We(c,b):0}function We(a,b){var c=Ya(8);B()[c+4>>2]=Lb();var d={oe:c,attributes:b,version:b.Id,bc:a};a.canvas&&(a.canvas.cc=d);("undefined"===typeof b.Oc||b.Oc)&&Xe(d);return c}
function Xe(a){a||(a=Ye);if(!a.Bd){a.Bd=!0;var b=a.bc;Se(b);Te(b);Ue(b);b.ke=b.getExtension("EXT_disjoint_timer_query");b.se=b.getExtension("WEBGL_multi_draw");(b.getSupportedExtensions()||[]).forEach(function(c){c.includes("lose_context")||c.includes("debug")||b.getExtension(c)})}}var Ye,Ze=["default","low-power","high-performance"],$e={};
function af(){if(!bf){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"===typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:ta||"./this.program"},b;for(b in $e)void 0===$e[b]?delete a[b]:a[b]=$e[b];var c=[];for(b in a)c.push(b+"="+a[b]);bf=c}return bf}var bf;
function cf(a,b){if(F)return Q(13,1,a,b);var c=0;af().forEach(function(d,e){var f=b+c;e=B()[a+4*e>>2]=f;for(f=0;f<d.length;++f)g()[e++>>0]=d.charCodeAt(f);g()[e>>0]=0;c+=d.length+1});return 0}function df(a,b){if(F)return Q(14,1,a,b);var c=af();B()[a>>2]=c.length;var d=0;c.forEach(function(e){d+=e.length+1});B()[b>>2]=d;return 0}function ef(a){if(F)return Q(15,1,a);try{var b=fd(a);Rc(b);return 0}catch(c){if("undefined"===typeof T||!(c instanceof R))throw c;return c.tb}}
function ff(a,b,c,d){if(F)return Q(16,1,a,b,c,d);try{a:{for(var e=fd(a),f=a=0;f<c;f++){var h=B()[b+8*f>>2],l=B()[b+(8*f+4)>>2],m=e,q=g(),p=h,t=l,v=void 0;if(0>t||0>v)throw new R(28);if(null===m.Cb)throw new R(8);if(1===(m.flags&2097155))throw new R(8);if(16384===(m.node.mode&61440))throw new R(31);if(!m.nb.read)throw new R(28);var k="undefined"!==typeof v;if(!k)v=m.position;else if(!m.seekable)throw new R(70);var u=m.nb.read(m,q,p,t,v);k||(m.position+=u);var x=u;if(0>x){var A=-1;break a}a+=x;if(x<
l)break}A=a}B()[d>>2]=A;return 0}catch(H){if("undefined"===typeof T||!(H instanceof R))throw H;return H.tb}}
function gf(a,b,c,d,e){if(F)return Q(17,1,a,b,c,d,e);try{var f=fd(a);a=4294967296*c+(b>>>0);if(-9007199254740992>=a||9007199254740992<=a)return-61;Sc(f,a,d);Bb=[f.position>>>0,(N=f.position,1<=+Math.abs(N)?0<N?(Math.min(+Math.floor(N/4294967296),4294967295)|0)>>>0:~~+Math.ceil((N-+(~~N>>>0))/4294967296)>>>0:0)];B()[e>>2]=Bb[0];B()[e+4>>2]=Bb[1];f.vc&&0===a&&0===d&&(f.vc=null);return 0}catch(h){if("undefined"===typeof T||!(h instanceof R))throw h;return h.tb}}
function hf(a,b,c,d){if(F)return Q(18,1,a,b,c,d);try{a:{for(var e=fd(a),f=a=0;f<c;f++){var h=B()[b+8*f>>2],l=B()[b+(8*f+4)>>2],m=Tc(e,g(),h,l,void 0);if(0>m){var q=-1;break a}a+=m}q=a}B()[d>>2]=q;return 0}catch(p){if("undefined"===typeof T||!(p instanceof R))throw p;return p.tb}}function jf(a,b){jf.Yc||(jf.Yc=bc());for(var c=0;c<b;c++)g()[a+c>>0]=jf.Yc();return 0}function kf(a){return 0===a%4&&(0!==a%100||0===a%400)}function lf(a,b){for(var c=0,d=0;d<=b;c+=a[d++]);return c}
var mf=[31,29,31,30,31,30,31,31,30,31,30,31],nf=[31,28,31,30,31,30,31,31,30,31,30,31];function of(a,b){for(a=new Date(a.getTime());0<b;){var c=a.getMonth(),d=(kf(a.getFullYear())?mf:nf)[c];if(b>d-a.getDate())b-=d-a.getDate()+1,a.setDate(1),11>c?a.setMonth(c+1):(a.setMonth(0),a.setFullYear(a.getFullYear()+1));else{a.setDate(a.getDate()+b);break}}return a}
function pf(a,b,c,d){function e(k,u,x){for(k="number"===typeof k?k.toString():k||"";k.length<u;)k=x[0]+k;return k}function f(k,u){return e(k,u,"0")}function h(k,u){function x(H){return 0>H?-1:0<H?1:0}var A;0===(A=x(k.getFullYear()-u.getFullYear()))&&0===(A=x(k.getMonth()-u.getMonth()))&&(A=x(k.getDate()-u.getDate()));return A}function l(k){switch(k.getDay()){case 0:return new Date(k.getFullYear()-1,11,29);case 1:return k;case 2:return new Date(k.getFullYear(),0,3);case 3:return new Date(k.getFullYear(),
0,2);case 4:return new Date(k.getFullYear(),0,1);case 5:return new Date(k.getFullYear()-1,11,31);case 6:return new Date(k.getFullYear()-1,11,30)}}function m(k){k=of(new Date(k.wb+1900,0,1),k.rc);var u=new Date(k.getFullYear()+1,0,4),x=l(new Date(k.getFullYear(),0,4));u=l(u);return 0>=h(x,k)?0>=h(u,k)?k.getFullYear()+1:k.getFullYear():k.getFullYear()-1}var q=B()[d+40>>2];d={de:B()[d>>2],ce:B()[d+4>>2],pc:B()[d+8>>2],$b:B()[d+12>>2],Rb:B()[d+16>>2],wb:B()[d+20>>2],qc:B()[d+24>>2],rc:B()[d+28>>2],ye:B()[d+
32>>2],be:B()[d+36>>2],ee:q?I(q):""};c=I(c);q={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S","%x":"%m/%d/%y","%X":"%H:%M:%S","%Ec":"%c","%EC":"%C","%Ex":"%m/%d/%y","%EX":"%H:%M:%S","%Ey":"%y","%EY":"%Y","%Od":"%d","%Oe":"%e","%OH":"%H","%OI":"%I","%Om":"%m","%OM":"%M","%OS":"%S","%Ou":"%u","%OU":"%U","%OV":"%V","%Ow":"%w","%OW":"%W","%Oy":"%y"};for(var p in q)c=c.replace(new RegExp(p,"g"),q[p]);var t="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),
v="January February March April May June July August September October November December".split(" ");q={"%a":function(k){return t[k.qc].substring(0,3)},"%A":function(k){return t[k.qc]},"%b":function(k){return v[k.Rb].substring(0,3)},"%B":function(k){return v[k.Rb]},"%C":function(k){return f((k.wb+1900)/100|0,2)},"%d":function(k){return f(k.$b,2)},"%e":function(k){return e(k.$b,2," ")},"%g":function(k){return m(k).toString().substring(2)},"%G":function(k){return m(k)},"%H":function(k){return f(k.pc,
2)},"%I":function(k){k=k.pc;0==k?k=12:12<k&&(k-=12);return f(k,2)},"%j":function(k){return f(k.$b+lf(kf(k.wb+1900)?mf:nf,k.Rb-1),3)},"%m":function(k){return f(k.Rb+1,2)},"%M":function(k){return f(k.ce,2)},"%n":function(){return"\n"},"%p":function(k){return 0<=k.pc&&12>k.pc?"AM":"PM"},"%S":function(k){return f(k.de,2)},"%t":function(){return"\t"},"%u":function(k){return k.qc||7},"%U":function(k){var u=new Date(k.wb+1900,0,1),x=0===u.getDay()?u:of(u,7-u.getDay());k=new Date(k.wb+1900,k.Rb,k.$b);return 0>
h(x,k)?f(Math.ceil((31-x.getDate()+(lf(kf(k.getFullYear())?mf:nf,k.getMonth()-1)-31)+k.getDate())/7),2):0===h(x,u)?"01":"00"},"%V":function(k){var u=new Date(k.wb+1901,0,4),x=l(new Date(k.wb+1900,0,4));u=l(u);var A=of(new Date(k.wb+1900,0,1),k.rc);return 0>h(A,x)?"53":0>=h(u,A)?"01":f(Math.ceil((x.getFullYear()<k.wb+1900?k.rc+32-x.getDate():k.rc+1-x.getDate())/7),2)},"%w":function(k){return k.qc},"%W":function(k){var u=new Date(k.wb,0,1),x=1===u.getDay()?u:of(u,0===u.getDay()?1:7-u.getDay()+1);k=
new Date(k.wb+1900,k.Rb,k.$b);return 0>h(x,k)?f(Math.ceil((31-x.getDate()+(lf(kf(k.getFullYear())?mf:nf,k.getMonth()-1)-31)+k.getDate())/7),2):0===h(x,u)?"01":"00"},"%y":function(k){return(k.wb+1900).toString().substring(2)},"%Y":function(k){return k.wb+1900},"%z":function(k){k=k.be;var u=0<=k;k=Math.abs(k)/60;return(u?"+":"-")+String("0000"+(k/60*100+k%60)).slice(-4)},"%Z":function(k){return k.ee},"%%":function(){return"%"}};for(p in q)c.includes(p)&&(c=c.replace(new RegExp(p,"g"),q[p](d)));p=hc(c,
!1);if(p.length>b)return 0;Za(p,a);return p.length-1}function Bc(a,b,c,d){a||(a=this);this.parent=a;this.Gb=a.Gb;this.Ub=null;this.id=uc++;this.name=b;this.mode=c;this.lb={};this.nb={};this.Wb=d}
Object.defineProperties(Bc.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}},Fd:{get:function(){return 16384===(this.mode&61440)}},Ed:{get:function(){return 8192===(this.mode&61440)}}});lb();vc=Array(4096);Ic(S,"/");Kc("/tmp");Kc("/home");Kc("/home/web_user");
(function(){Kc("/dev");fc(259,{read:function(){return 0},write:function(b,c,d,e){return e}});Lc("/dev/null",259);ec(1280,ic);ec(1536,jc);Lc("/dev/tty",1280);Lc("/dev/tty1",1536);var a=bc();mb("/dev","random",a);mb("/dev","urandom",a);Kc("/dev/shm");Kc("/dev/shm/tmp")})();
(function(){Kc("/proc");var a=Kc("/proc/self");Kc("/proc/self/fd");Ic({Gb:function(){var b=nc(a,"fd",16895,73);b.lb={Tb:function(c,d){var e=tc[+d];if(!e)throw new R(8);c={parent:null,Gb:{Vc:"fake"},lb:{Xb:function(){return e.path}}};return c.parent=c}};return b}},"/proc/self/fd")})();var ad;D.FS_createPath=Vc;D.FS_createDataFile=Xc;D.FS_createPreloadedFile=$c;D.FS_createLazyFile=Zc;D.FS_createDevice=mb;D.FS_unlink=Mc;zd=D.InternalError=yd("InternalError");
for(var qf=Array(256),rf=0;256>rf;++rf)qf[rf]=String.fromCharCode(rf);Ed=qf;Fd=D.BindingError=yd("BindingError");Od.prototype.isAliasOf=function(a){if(!(this instanceof Od&&a instanceof Od))return!1;var b=this.kb.rb.ob,c=this.kb.pb,d=a.kb.rb.ob;for(a=a.kb.pb;b.Ab;)c=b.ac(c),b=b.Ab;for(;d.Ab;)a=d.ac(a),d=d.Ab;return b===d&&c===a};
Od.prototype.clone=function(){this.kb.pb||Gd(this);if(this.kb.Vb)return this.kb.count.value+=1,this;var a=Kd,b=Object,c=b.create,d=Object.getPrototypeOf(this),e=this.kb;a=a(c.call(b,d,{kb:{value:{count:e.count,Mb:e.Mb,Vb:e.Vb,pb:e.pb,rb:e.rb,yb:e.yb,zb:e.zb}}}));a.kb.count.value+=1;a.kb.Mb=!1;return a};Od.prototype["delete"]=function(){this.kb.pb||Gd(this);this.kb.Mb&&!this.kb.Vb&&V("Object already scheduled for deletion");Id(this);Jd(this.kb);this.kb.Vb||(this.kb.yb=void 0,this.kb.pb=void 0)};
Od.prototype.isDeleted=function(){return!this.kb.pb};Od.prototype.deleteLater=function(){this.kb.pb||Gd(this);this.kb.Mb&&!this.kb.Vb&&V("Object already scheduled for deletion");Md.push(this);1===Md.length&&Ld&&Ld(Nd);this.kb.Mb=!0;return this};be.prototype.wd=function(a){this.Zc&&(a=this.Zc(a));return a};be.prototype.Nc=function(a){this.Hb&&this.Hb(a)};be.prototype.argPackAdvance=8;be.prototype.readValueFromPointer=sd;be.prototype.deleteObject=function(a){if(null!==a)a["delete"]()};
be.prototype.fromWireType=function(a){function b(){return this.kc?ae(this.ob.Nb,{rb:this.Nd,pb:c,zb:this,yb:a}):ae(this.ob.Nb,{rb:this,pb:a})}var c=this.wd(a);if(!c)return this.Nc(a),null;var d=$d(this.ob,c);if(void 0!==d){if(0===d.kb.count.value)return d.kb.pb=c,d.kb.yb=a,d.clone();d=d.clone();this.Nc(a);return d}d=this.ob.ud(c);d=Pd[d];if(!d)return b.call(this);d=this.jc?d.nd:d.pointerType;var e=Yd(c,this.ob,d.ob);return null===e?b.call(this):this.kc?ae(d.ob.Nb,{rb:d,pb:e,zb:this,yb:a}):ae(d.ob.Nb,
{rb:d,pb:e})};D.getInheritedInstanceCount=function(){return Object.keys(Zd).length};D.getLiveInheritedInstances=function(){var a=[],b;for(b in Zd)Zd.hasOwnProperty(b)&&a.push(Zd[b]);return a};D.flushPendingDeletes=Nd;D.setDelayFunction=function(a){Ld=a;Md.length&&Ld&&Ld(Nd)};fe=D.UnboundTypeError=yd("UnboundTypeError");D.count_emval_handles=function(){for(var a=0,b=5;b<X.length;++b)void 0!==X[b]&&++a;return a};D.get_first_emval=function(){for(var a=5;a<X.length;++a)if(void 0!==X[a])return X[a];return null};
F||(Ke(function(a){Le=a;wb("library_fetch_init")},function(){Le=!1;wb("library_fetch_init")}),"undefined"!==typeof ENVIRONMENT_IS_FETCH_WORKER&&ENVIRONMENT_IS_FETCH_WORKER||vb("library_fetch_init"));var sf=[null,Pb,Tb,gd,hd,jd,kd,function(a,b){if(F)return Q(7,1,a,b);try{return a=I(a),cd(Oc,a,b)}catch(c){if("undefined"===typeof T||!(c instanceof R))throw c;return-c.tb}},ld,md,od,pd,Ie,cf,df,ef,ff,gf,hf];function hc(a,b){var c=Array(Pa(a)+1);a=Oa(a,c,0,c.length);b&&(c.length=a);return c}
var Bf={ea:function(a){tf(a,!wa,1,!va);P.dd()},_:function(a){F?postMessage({cmd:"cleanupThread",thread:a}):Gb(a)},ja:function(a,b){Xb||(Xb=!0,Tb());a=new Date(1E3*B()[a>>2]);B()[b>>2]=a.getSeconds();B()[b+4>>2]=a.getMinutes();B()[b+8>>2]=a.getHours();B()[b+12>>2]=a.getDate();B()[b+16>>2]=a.getMonth();B()[b+20>>2]=a.getFullYear()-1900;B()[b+24>>2]=a.getDay();var c=new Date(a.getFullYear(),0,1),d=(a.getTime()-c.getTime())/864E5|0;B()[b+28>>2]=d;B()[b+36>>2]=-(60*a.getTimezoneOffset());d=(new Date(a.getFullYear(),
6,1)).getTimezoneOffset();c=c.getTimezoneOffset();a=(d!=c&&a.getTimezoneOffset()==Math.min(c,d))|0;B()[b+32>>2]=a;a=B()[Wb()+(a?4:0)>>2];B()[b+40>>2]=a;return b},E:function(a,b,c,d){if("undefined"===typeof SharedArrayBuffer)return E("Current environment does not support SharedArrayBuffer, pthreads are not available!"),6;var e=[];if(F&&0===e.length)return uf(687865856,a,b,c,d);a={ae:c,Ac:a,Sb:d,fe:e};return F?(a.ie="spawnThread",postMessage(a,e),0):Nb(a)},aa:function(){postMessage({cmd:"detachedExit"})},
G:gd,oa:hd,ma:jd,pa:kd,ia:ld,ha:md,H:od,na:pd,c:function(a){var b=qd[a];delete qd[a];var c=b.Cc,d=b.Hb,e=b.Qc,f=e.map(function(h){return h.yd}).concat(e.map(function(h){return h.Yd}));Bd([a],f,function(h){var l={};e.forEach(function(m,q){var p=h[q],t=m.ic,v=m.xd,k=h[q+e.length],u=m.Xd,x=m.Zd;l[m.td]={read:function(A){return p.fromWireType(t(v,A))},write:function(A,H){var J=[];u(x,A,k.toWireType(J,H));rd(J)}}});return[{name:b.name,fromWireType:function(m){var q={},p;for(p in l)q[p]=l[p].read(m);d(m);
return q},toWireType:function(m,q){for(var p in l)if(!(p in q))throw new TypeError('Missing field:  "'+p+'"');var t=c();for(p in l)l[p].write(t,q[p]);null!==m&&m.push(d,t);return t},argPackAdvance:8,readValueFromPointer:sd,Bb:d}]})},P:function(){},sa:function(a,b,c,d,e){var f=Dd(c);b=U(b);Cd(a,{name:b,fromWireType:function(h){return!!h},toWireType:function(h,l){return l?d:e},argPackAdvance:8,readValueFromPointer:function(h){if(1===c)var l=g();else if(2===c)l=da();else if(4===c)l=B();else throw new TypeError("Unknown boolean type size: "+
b);return this.fromWireType(l[h>>f])},Bb:null})},r:function(a,b,c,d,e,f,h,l,m,q,p,t,v){p=U(p);f=ee(e,f);l&&(l=ee(h,l));q&&(q=ee(m,q));v=ee(t,v);var k=wd(p);Rd(k,function(){ie("Cannot construct "+p+" due to unbound types",[d])});Bd([a,b,c],d?[d]:[],function(u){u=u[0];if(d){var x=u.ob;var A=x.Nb}else A=Od.prototype;u=xd(k,function(){if(Object.getPrototypeOf(this)!==H)throw new Fd("Use 'new' to construct "+p);if(void 0===J.Jb)throw new Fd(p+" has no accessible constructor");var w=J.Jb[arguments.length];
if(void 0===w)throw new Fd("Tried to invoke ctor of "+p+" with invalid number of parameters ("+arguments.length+") - expected ("+Object.keys(J.Jb).toString()+") parameters instead!");return w.apply(this,arguments)});var H=Object.create(A,{constructor:{value:u}});u.prototype=H;var J=new Sd(p,u,H,v,x,f,l,q);x=new be(p,J,!0,!1);A=new be(p+"*",J,!1,!1);var ma=new be(p+" const*",J,!1,!0);Pd[a]={pointerType:A,nd:ma};ce(k,u);return[x,A,ma]})},s:function(a,b,c,d,e,f){0<b||Ha(void 0);var h=je(b,c);e=ee(d,
e);Bd([],[a],function(l){l=l[0];var m="constructor "+l.name;void 0===l.ob.Jb&&(l.ob.Jb=[]);if(void 0!==l.ob.Jb[b-1])throw new Fd("Cannot register multiple constructors with identical number of parameters ("+(b-1)+") for class '"+l.name+"'! Overload resolution is currently only performed using the parameter count, not actual type info!");l.ob.Jb[b-1]=function(){ie("Cannot construct "+l.name+" due to unbound types",h)};Bd([],h,function(q){q.splice(1,0,null);l.ob.Jb[b-1]=le(m,q,null,e,f);return[]});
return[]})},f:function(a,b,c,d,e,f,h,l){var m=je(c,d);b=U(b);f=ee(e,f);Bd([],[a],function(q){function p(){ie("Cannot call "+t+" due to unbound types",m)}q=q[0];var t=q.name+"."+b;b.startsWith("@@")&&(b=Symbol[b.substring(2)]);l&&q.ob.Pd.push(b);var v=q.ob.Nb,k=v[b];void 0===k||void 0===k.vb&&k.className!==q.name&&k.dc===c-2?(p.dc=c-2,p.className=q.name,v[b]=p):(Qd(v,b,t),v[b].vb[c-2]=p);Bd([],m,function(u){u=le(t,u,q,f,h);void 0===v[b].vb?(u.dc=c-2,v[b]=u):v[b].vb[c-2]=u;return[]});return[]})},ra:function(a,
b){b=U(b);Cd(a,{name:b,fromWireType:function(c){var d=Y(c);ne(c);return d},toWireType:function(c,d){return W(d)},argPackAdvance:8,readValueFromPointer:sd,Bb:null})},I:function(a,b,c){c=Dd(c);b=U(b);Cd(a,{name:b,fromWireType:function(d){return d},toWireType:function(d,e){return e},argPackAdvance:8,readValueFromPointer:oe(b,c),Bb:null})},A:function(a,b,c,d,e,f){var h=je(b,c);a=U(a);e=ee(d,e);Rd(a,function(){ie("Cannot call "+a+" due to unbound types",h)},b-1);Bd([],h,function(l){ce(a,le(a,[l[0],null].concat(l.slice(1)),
null,e,f),b-1);return[]})},k:function(a,b,c,d,e){function f(l){return l}b=U(b);-1===e&&(e=4294967295);e=Dd(c);if(0===d){var h=32-8*c;f=function(l){return l<<h>>>h}}c=b.includes("unsigned")?function(l,m){return m>>>0}:function(l,m){return m};Cd(a,{name:b,fromWireType:f,toWireType:c,argPackAdvance:8,readValueFromPointer:pe(b,e,0!==d),Bb:null})},e:function(a,b,c){function d(f){f>>=2;var h=C();return new e(r,h[f+1],h[f])}var e=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,
Float64Array][b];c=U(c);Cd(a,{name:c,fromWireType:d,argPackAdvance:8,readValueFromPointer:d},{Ad:!0})},J:function(a,b){b=U(b);var c="std::string"===b;Cd(a,{name:b,fromWireType:function(d){var e=C()[d>>2];if(c)for(var f=d+4,h=0;h<=e;++h){var l=d+4+h;if(h==e||0==y()[l]){f=I(f,l-f);if(void 0===m)var m=f;else m+=String.fromCharCode(0),m+=f;f=l+1}}else{m=Array(e);for(h=0;h<e;++h)m[h]=String.fromCharCode(y()[d+4+h]);m=m.join("")}nd(d);return m},toWireType:function(d,e){e instanceof ArrayBuffer&&(e=new Uint8Array(e));
var f="string"===typeof e;f||e instanceof Uint8Array||e instanceof Uint8ClampedArray||e instanceof Int8Array||V("Cannot pass non-string to std::string");var h=(c&&f?function(){return Pa(e)}:function(){return e.length})(),l=Ya(4+h+1);C()[l>>2]=h;if(c&&f)K(e,l+4,h+1);else if(f)for(f=0;f<h;++f){var m=e.charCodeAt(f);255<m&&(nd(l),V("String has UTF-16 code units that do not fit in 8 bits"));y()[l+4+f]=m}else for(f=0;f<h;++f)y()[l+4+f]=e[f];null!==d&&d.push(nd,l);return l},argPackAdvance:8,readValueFromPointer:sd,
Bb:function(d){nd(d)}})},x:function(a,b,c){c=U(c);if(2===b){var d=Ra;var e=Sa;var f=Ta;var h=function(){return z()};var l=1}else 4===b&&(d=Ua,e=Va,f=Wa,h=function(){return C()},l=2);Cd(a,{name:c,fromWireType:function(m){for(var q=C()[m>>2],p=h(),t,v=m+4,k=0;k<=q;++k){var u=m+4+k*b;if(k==q||0==p[u>>l])v=d(v,u-v),void 0===t?t=v:(t+=String.fromCharCode(0),t+=v),v=u+b}nd(m);return t},toWireType:function(m,q){"string"!==typeof q&&V("Cannot pass non-string to C++ string type "+c);var p=f(q),t=Ya(4+p+b);
C()[t>>2]=p>>l;e(q,t+4,p+b);null!==m&&m.push(nd,t);return t},argPackAdvance:8,readValueFromPointer:sd,Bb:function(m){nd(m)}})},d:function(a,b,c,d,e,f){qd[a]={name:U(b),Cc:ee(c,d),Hb:ee(e,f),Qc:[]}},b:function(a,b,c,d,e,f,h,l,m,q){qd[a].Qc.push({td:U(b),yd:c,ic:ee(d,e),xd:f,Yd:h,Xd:ee(l,m),Zd:q})},ta:function(a,b){b=U(b);Cd(a,{Gd:!0,name:b,argPackAdvance:0,fromWireType:function(){},toWireType:function(){}})},ga:function(){return 2097152},ua:function(a){delete Je[a-1]},qa:function(a,b,c){var d=performance.now();
c=d+c;for(Atomics.exchange(B(),vf>>2,a);;){d=performance.now();if(d>c)return Atomics.exchange(B(),vf>>2,0),-73;d=Atomics.exchange(B(),vf>>2,0);if(0==d)break;Mb();if(Atomics.load(B(),a>>2)!=b)return-6;Atomics.exchange(B(),vf>>2,a)}return 0},fa:function(a,b){if(a==b)postMessage({cmd:"processQueuedMainThreadWork"});else if(F)postMessage({targetThread:a,cmd:"processThreadQueue"});else{a=(a=P.Fb[a])&&a.worker;if(!a)return;a.postMessage({cmd:"processThreadQueue"})}return 1},U:function(){throw"longjmp";
},l:function(a,b,c){a=Y(a);b=qe(b,"emval::as");var d=[],e=W(d);B()[c>>2]=e;return b.toWireType(d,a)},Ca:function(a,b,c,d){a=Y(a);c=re(b,c);for(var e=Array(b),f=0;f<b;++f){var h=c[f];e[f]=h.readValueFromPointer(d);d+=h.argPackAdvance}a=a.apply(void 0,e);return W(a)},q:function(a,b,c,d){a=ue[a];b=Y(b);c=te(c);a(b,c,null,d)},D:ne,Da:function(a,b){a=Y(a);b=Y(b);return a==b},za:function(a){if(0===a)return W(ve());a=te(a);return W(ve()[a])},p:function(a,b){var c=re(a,b),d=c[0];b=d.name+"_$"+c.slice(1).map(function(p){return p.name}).join("_")+
"$";var e=xe[b];if(void 0!==e)return e;e=["retType"];for(var f=[d],h="",l=0;l<a-1;++l)h+=(0!==l?", ":"")+"arg"+l,e.push("argType"+l),f.push(c[1+l]);var m="return function "+wd("methodCaller_"+b)+"(handle, name, destructors, args) {\n",q=0;for(l=0;l<a-1;++l)m+="    var arg"+l+" = argType"+l+".readValueFromPointer(args"+(q?"+"+q:"")+");\n",q+=c[l+1].argPackAdvance;m+="    var rv = handle[name]("+h+");\n";for(l=0;l<a-1;++l)c[l+1].deleteObject&&(m+="    argType"+l+".deleteObject(arg"+l+");\n");d.Gd||
(m+="    return retType.toWireType(destructors, rv);\n");e.push(m+"};\n");a=ke(e).apply(null,f);e=we(a);return xe[b]=e},o:function(a,b){a=Y(a);b=Y(b);return W(a[b])},L:function(a){4<a&&(X[a].Ec+=1)},Aa:function(a,b){a=Y(a);b=Y(b);return a instanceof b},z:function(a,b,c,d){a=Y(a);var e=ye[b];if(!e){e="";for(var f=0;f<b;++f)e+=(0!==f?", ":"")+"arg"+f;var h="return function emval_allocator_"+b+"(constructor, argTypes, args) {\n";for(f=0;f<b;++f)h+="var argType"+f+" = requireRegisteredType(Module['HEAP32'][(argTypes >>> 2) + "+
f+'], "parameter '+f+'");\nvar arg'+f+" = argType"+f+".readValueFromPointer(args);\nargs += argType"+f+"['argPackAdvance'];\n";e=(new Function("requireRegisteredType","Module","valueToHandle",h+("var obj = new constructor("+e+");\nreturn valueToHandle(obj);\n}\n")))(qe,D,W);ye[b]=e}return e(a,c,d)},T:function(){return W([])},Ga:function(a){return W(te(a))},N:function(){return W({})},Fa:function(a){var b=Y(a);rd(b);ne(a)},h:function(a,b,c){a=Y(a);b=Y(b);c=Y(c);a[b]=c},j:function(a,b){a=qe(a,"_emval_take_value");
a=a.readValueFromPointer(b);return W(a)},Ea:function(a){a=Y(a);return W(typeof a)},m:function(){Ha("")},M:function(){var a=D.allowedThreads;return a?a:navigator.hardwareConcurrency},y:function(a,b){if(0===a)a=Date.now();else if(1===a||4===a)a=Sb();else return-1;B()[b>>2]=a/1E3|0;B()[b+4>>2]=a%1E3*1E6|0;return 0},n:function(a,b,c){ze.length=0;var d;for(c>>=2;d=y()[b++];)(d=105>d)&&c&1&&c++,ze.push(d?ja()[c++>>1]:B()[c]),++c;return Cb[a].apply(null,ze)},C:function(){wa||(Ea||(Ea={}),Ea["Blocking on the main thread is very dangerous, see https://emscripten.org/docs/porting/pthreads.html#blocking-on-the-main-browser-thread"]||
(Ea["Blocking on the main thread is very dangerous, see https://emscripten.org/docs/porting/pthreads.html#blocking-on-the-main-browser-thread"]=1,E("Blocking on the main thread is very dangerous, see https://emscripten.org/docs/porting/pthreads.html#blocking-on-the-main-browser-thread")))},Z:function(){return 838860800},t:Sb,wa:function(){return"undefined"!==typeof SharedArrayBuffer},V:function(a,b,c){y().copyWithin(a,b,b+c)},ba:function(a,b,c){Ce.length=b;c>>=3;for(var d=0;d<b;d++)Ce[d]=ja()[c+d];
return(0>a?Cb[-a-1]:sf[a]).apply(null,Ce)},W:function(a){var b=y().length;a>>>=0;if(a<=b||838860800<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);d=Math.max(a,d);0<d%65536&&(d+=65536-d%65536);a:{try{n.grow(Math.min(838860800,d)-r.byteLength+65535>>>16);aa(n.buffer);var e=1;break a}catch(f){}e=void 0}if(e)return!0}return!1},ca:function(a,b,c){return Ge(a)?He(a,b,c):Ie(a,b,c)},va:function(a,b,c,d,e){function f(G){Me(G,h,q,p,m)}function h(G,zf){Pe(G,zf.response,function(ab){--hb;
Ne(function(){u?O(u)(ab):b&&b(ab)},M)},function(ab){--hb;Ne(function(){u?O(u)(ab):b&&b(ab)},M)})}function l(G){Me(G,t,q,p,m)}function m(G){Ne(function(){H?O(H)(G):e&&e(G)},M)}function q(G){--hb;Ne(function(){x?O(x)(G):c&&c(G)},M)}function p(G){Ne(function(){A?O(A)(G):d&&d(G)},M)}function t(G){--hb;Ne(function(){u?O(u)(G):b&&b(G)},M)}hb+=1;var v=a+112,k=I(v),u=C()[v+36>>2],x=C()[v+40>>2],A=C()[v+44>>2],H=C()[v+48>>2],J=C()[v+52>>2],ma=!!(J&4),w=!!(J&32),L=!!(J&16),M=!!(J&64);if("EM_IDB_STORE"===k)k=
C()[v+84>>2],Pe(a,y().slice(k,k+C()[v+88>>2]),t,q);else if("EM_IDB_DELETE"===k)Re(a,t,q);else if(L){if(w)return 0;Me(a,ma?h:t,q,p,m)}else Qe(a,t,w?q:ma?f:l);return a},$:function(){throw"unwind";},da:function(a,b){b>>=2;var c=B()[b+6];b={alpha:!!B()[b+0],depth:!!B()[b+1],stencil:!!B()[b+2],antialias:!!B()[b+3],premultipliedAlpha:!!B()[b+4],preserveDrawingBuffer:!!B()[b+5],powerPreference:Ze[c],failIfMajorPerformanceCaveat:!!B()[b+7],Id:B()[b+8],re:B()[b+9],Oc:B()[b+10],sd:B()[b+11],ve:B()[b+12],we:B()[b+
13]};a=Ge(a);return!a||b.sd?0:Ve(a,b)},ka:cf,la:df,u:function(a){Qb(a)},w:ef,F:ff,O:gf,v:hf,i:function(){return Fa},Ba:function(){var a=self.navigator.userAgent,b=Pa(a)+1,c=Ya(b);K(a,c,b);return c},X:jf,Q:wf,B:xf,R:yf,S:Af,a:n||D.wasmMemory,xa:function(a){Xb||(Xb=!0,Tb());var b=new Date(B()[a+20>>2]+1900,B()[a+16>>2],B()[a+12>>2],B()[a+8>>2],B()[a+4>>2],B()[a>>2],0),c=B()[a+32>>2],d=b.getTimezoneOffset(),e=new Date(b.getFullYear(),0,1),f=(new Date(b.getFullYear(),6,1)).getTimezoneOffset(),h=e.getTimezoneOffset(),
l=Math.min(h,f);0>c?B()[a+32>>2]=Number(f!=h&&l==d):0<c!=(l==d)&&(f=Math.max(h,f),b.setTime(b.getTime()+6E4*((0<c?l:f)-d)));B()[a+24>>2]=b.getDay();c=(b.getTime()-e.getTime())/864E5|0;B()[a+28>>2]=c;B()[a>>2]=b.getSeconds();B()[a+4>>2]=b.getMinutes();B()[a+8>>2]=b.getHours();B()[a+12>>2]=b.getDate();B()[a+16>>2]=b.getMonth();return b.getTime()/1E3|0},g:function(a){Fa=a},K:pf,Y:function(a,b,c,d){return pf(a,b,c,d)},ya:function(a){var b=Date.now()/1E3|0;a&&(B()[a>>2]=b);return b}};
(function(){function a(e,f){D.asm=e.exports;P.Ic.push(D.asm.La);cb=D.asm.db;eb.unshift(D.asm.Ha);Ia=f;F||wb("wasm-instantiate")}function b(e){a(e.instance,e.module)}function c(e){return Ab().then(function(f){return WebAssembly.instantiate(f,d)}).then(function(f){return f}).then(e,function(f){E("failed to asynchronously prepare wasm: "+f);Ha(f)})}var d={a:Bf};F||vb("wasm-instantiate");if(D.instantiateWasm)try{return D.instantiateWasm(d,a)}catch(e){return E("Module.instantiateWasm callback failed with error: "+
e),!1}(function(){return Ga||"function"!==typeof WebAssembly.instantiateStreaming||xb()||"function"!==typeof fetch?c(b):fetch(yb,{credentials:"same-origin"}).then(function(e){return WebAssembly.instantiateStreaming(e,d).then(b,function(f){E("wasm streaming compile failed: "+f);E("falling back to ArrayBuffer instantiation");return c(b)})})})().catch(oa);return{}})();D.___wasm_call_ctors=function(){return(D.___wasm_call_ctors=D.asm.Ha).apply(null,arguments)};
var nd=D._free=function(){return(nd=D._free=D.asm.Ia).apply(null,arguments)},Ya=D._malloc=function(){return(Ya=D._malloc=D.asm.Ja).apply(null,arguments)},Lb=D._pthread_self=function(){return(Lb=D._pthread_self=D.asm.Ka).apply(null,arguments)};D._emscripten_tls_init=function(){return(D._emscripten_tls_init=D.asm.La).apply(null,arguments)};var he=D.___getTypeName=function(){return(he=D.___getTypeName=D.asm.Ma).apply(null,arguments)};
D.___embind_register_native_and_builtin_types=function(){return(D.___embind_register_native_and_builtin_types=D.asm.Na).apply(null,arguments)};
var tf=D.__emscripten_thread_init=function(){return(tf=D.__emscripten_thread_init=D.asm.Oa).apply(null,arguments)},Wb=D.__get_tzname=function(){return(Wb=D.__get_tzname=D.asm.Pa).apply(null,arguments)},Vb=D.__get_daylight=function(){return(Vb=D.__get_daylight=D.asm.Qa).apply(null,arguments)},Ub=D.__get_timezone=function(){return(Ub=D.__get_timezone=D.asm.Ra).apply(null,arguments)};
D._emscripten_current_thread_process_queued_calls=function(){return(D._emscripten_current_thread_process_queued_calls=D.asm.Sa).apply(null,arguments)};
var uf=D._emscripten_sync_run_in_main_thread_4=function(){return(uf=D._emscripten_sync_run_in_main_thread_4=D.asm.Ta).apply(null,arguments)},Mb=D._emscripten_main_thread_process_queued_calls=function(){return(Mb=D._emscripten_main_thread_process_queued_calls=D.asm.Ua).apply(null,arguments)},Be=D._emscripten_run_in_main_runtime_thread_js=function(){return(Be=D._emscripten_run_in_main_runtime_thread_js=D.asm.Va).apply(null,arguments)},Ee=D._emscripten_dispatch_to_thread_=function(){return(Ee=D._emscripten_dispatch_to_thread_=
D.asm.Wa).apply(null,arguments)},Jb=D.__emscripten_thread_free_data=function(){return(Jb=D.__emscripten_thread_free_data=D.asm.Xa).apply(null,arguments)},Oe=D.__emscripten_thread_exit=function(){return(Oe=D.__emscripten_thread_exit=D.asm.Ya).apply(null,arguments)},lc=D._memalign=function(){return(lc=D._memalign=D.asm.Za).apply(null,arguments)},Cf=D._setThrew=function(){return(Cf=D._setThrew=D.asm._a).apply(null,arguments)},Ob=D._emscripten_stack_set_limits=function(){return(Ob=D._emscripten_stack_set_limits=
D.asm.$a).apply(null,arguments)},Eb=D.stackSave=function(){return(Eb=D.stackSave=D.asm.ab).apply(null,arguments)},Fb=D.stackRestore=function(){return(Fb=D.stackRestore=D.asm.bb).apply(null,arguments)},Ae=D.stackAlloc=function(){return(Ae=D.stackAlloc=D.asm.cb).apply(null,arguments)};D.dynCall_ji=function(){return(D.dynCall_ji=D.asm.eb).apply(null,arguments)};D.dynCall_jiji=function(){return(D.dynCall_jiji=D.asm.fb).apply(null,arguments)};
D.dynCall_viijii=function(){return(D.dynCall_viijii=D.asm.gb).apply(null,arguments)};D.dynCall_iiiiij=function(){return(D.dynCall_iiiiij=D.asm.hb).apply(null,arguments)};D.dynCall_iiiiijj=function(){return(D.dynCall_iiiiijj=D.asm.ib).apply(null,arguments)};D.dynCall_iiiiiijj=function(){return(D.dynCall_iiiiiijj=D.asm.jb).apply(null,arguments)};var vf=D.__emscripten_main_thread_futex=1043848,Kb=D.__emscripten_allow_main_runtime_queued_calls=381140;
function xf(a,b){var c=Eb();try{O(a)(b)}catch(d){Fb(c);if(d!==d+0&&"longjmp"!==d)throw d;Cf(1,0)}}function Af(a,b,c,d){var e=Eb();try{O(a)(b,c,d)}catch(f){Fb(e);if(f!==f+0&&"longjmp"!==f)throw f;Cf(1,0)}}function yf(a,b,c){var d=Eb();try{O(a)(b,c)}catch(e){Fb(d);if(e!==e+0&&"longjmp"!==e)throw e;Cf(1,0)}}function wf(a,b,c,d){var e=Eb();try{return O(a)(b,c,d)}catch(f){Fb(e);if(f!==f+0&&"longjmp"!==f)throw f;Cf(1,0)}}D.addRunDependency=vb;D.removeRunDependency=wb;D.FS_createPath=Vc;
D.FS_createDataFile=Xc;D.FS_createPreloadedFile=$c;D.FS_createLazyFile=Zc;D.FS_createDevice=mb;D.FS_unlink=Mc;D.keepRuntimeAlive=ib;D.PThread=P;D.PThread=P;D.wasmMemory=n;D.ExitStatus=Ib;var Df;function Ib(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}ub=function Ef(){Df||Ff();Df||(ub=Ef)};
function Ff(){function a(){if(!Df&&(Df=!0,D.calledRun=!0,!Ja)){jb();na(D);if(D.onRuntimeInitialized)D.onRuntimeInitialized();if(!F){if(D.postRun)for("function"==typeof D.postRun&&(D.postRun=[D.postRun]);D.postRun.length;){var b=D.postRun.shift();fb.unshift(b)}qb(fb)}}}if(!(0<sb))if(F)na(D),jb(),postMessage({cmd:"loaded"});else{if(D.preRun)for("function"==typeof D.preRun&&(D.preRun=[D.preRun]);D.preRun.length;)rb();qb(db);0<sb||(D.setStatus?(D.setStatus("Running..."),setTimeout(function(){setTimeout(function(){D.setStatus("")},
1);a()},1)):a())}}D.run=Ff;function Qb(a){Ka=a;if(F)throw Pb(a),"unwind";ib()||F||(P.cd(),gb=!0);Ka=a;if(!ib()){P.cd();if(D.onExit)D.onExit(a);Ja=!0}ua(a,new Ib(a))}if(D.preInit)for("function"==typeof D.preInit&&(D.preInit=[D.preInit]);0<D.preInit.length;)D.preInit.pop()();F&&(noExitRuntime=!1,P.Cd());Ff();


  return BlinkIDWasmSDK.ready
}
);
})();
if (typeof exports === 'object' && typeof module === 'object')
  module.exports = BlinkIDWasmSDK;
else if (typeof define === 'function' && define['amd'])
  define([], function() { return BlinkIDWasmSDK; });
else if (typeof exports === 'object')
  exports["BlinkIDWasmSDK"] = BlinkIDWasmSDK;
