
var BlinkIDWasmSDK = (() => {
  var _scriptDir = typeof document !== 'undefined' && document.currentScript ? document.currentScript.src : undefined;
  
  return (
function(BlinkIDWasmSDK) {
  BlinkIDWasmSDK = BlinkIDWasmSDK || {};


var g;g||(g=typeof BlinkIDWasmSDK !== 'undefined' ? BlinkIDWasmSDK : {});var aa,ba;g.ready=new Promise(function(a,b){aa=a;ba=b});g.Lb||(g.Lb=0);g.Lb++;
g.ENVIRONMENT_IS_PTHREAD||function(a){function b(m,p,n){var r=new XMLHttpRequest;r.open("GET",m,!0);r.responseType="arraybuffer";r.onprogress=function(v){var l=p;v.total&&(l=v.total);if(v.loaded){r.pc?g.mb[m].loaded=v.loaded:(r.pc=!0,g.mb||(g.mb={}),g.mb[m]={loaded:v.loaded,total:l});var u=l=v=0,w;for(w in g.mb){var y=g.mb[w];v+=y.total;l+=y.loaded;u++}v=Math.ceil(v*g.Lb/u);g.setStatus&&g.setStatus("Downloading data... ("+l+"/"+v+")")}else!g.mb&&g.setStatus&&g.setStatus("Downloading data...")};r.onerror=
function(){throw Error("NetworkError for: "+m);};r.onload=function(){if(200==r.status||304==r.status||206==r.status||0==r.status&&r.response)n(r.response);else throw Error(r.statusText+" : "+r.responseURL);};r.send(null)}function c(m){console.error("package error:",m)}function d(){function m(v,l,u){this.start=v;this.end=l;this.audio=u}function p(v){if(!v)throw"Loading data file failed."+Error().stack;if(!(v instanceof ArrayBuffer))throw"bad input to processPackageData"+Error().stack;v=new Uint8Array(v);
m.prototype.uc=v;v=a.files;for(var l=0;l<v.length;++l)m.prototype.Ub[v[l].filename].onload();g.removeRunDependency("datafile_../../resources/advanced/BlinkIDWasmSDK.data")}g.FS_createPath("/","microblink",!0,!0);m.prototype={Ub:{},open:function(v,l){this.name=l;this.Ub[l]=this;g.addRunDependency("fp "+this.name)},send:function(){},onload:function(){this.finish(this.uc.subarray(this.start,this.end))},finish:function(v){g.FS_createDataFile(this.name,null,v,!0,!0,!0);g.removeRunDependency("fp "+this.name);
this.Ub[this.name]=null}};for(var n=a.files,r=0;r<n.length;++r)(new m(n[r].start,n[r].end,n[r].audio||0)).open("GET",n[r].filename);g.addRunDependency("datafile_../../resources/advanced/BlinkIDWasmSDK.data");g.hc||(g.hc={});g.hc["../../resources/advanced/BlinkIDWasmSDK.data"]={cd:!1};k?(p(k),k=null):h=p}"object"===typeof window?window.encodeURIComponent(window.location.pathname.toString().substring(0,window.location.pathname.toString().lastIndexOf("/"))+"/"):"undefined"===typeof process&&"undefined"!==
typeof location&&encodeURIComponent(location.pathname.toString().substring(0,location.pathname.toString().lastIndexOf("/"))+"/");"function"!==typeof g.locateFilePackage||g.locateFile||(g.locateFile=g.locateFilePackage,ca("warning: you defined Module.locateFilePackage, that has been renamed to Module.locateFile (using your locateFilePackage for now)"));var e=g.locateFile?g.locateFile("BlinkIDWasmSDK.data",""):"BlinkIDWasmSDK.data",f=a.remote_package_size,h=null,k=g.getPreloadedPackage?g.getPreloadedPackage(e,
f):null;k||b(e,f,function(m){h?(h(m),h=null):k=m},c);g.calledRun?d():(g.preRun||(g.preRun=[]),g.preRun.push(d))}({files:[{filename:"/microblink/Model_2d419402bfe12530fb79cb71e911ddf977986ad414c8870fcedd54378167d1af.strop",start:0,end:214096},{filename:"/microblink/Model_82ae7b860c6b4cb8249534e0004901bc46dee18fd3adbe535809abeefbf4fd88.strop",start:214096,end:4932412},{filename:"/microblink/Model_ed586fd6ca47c8eebb513c4ffaaacc2c54e92162b145062d7022519fba0911de.strop",start:4932412,end:5645644},{filename:"/microblink/Model_e4f1f62f68ec44b71ecad3fb3f3b48fe3790beb5ab325611e17d63af06e9f644.strop",
start:5645644,end:5702158},{filename:"/microblink/Model_26abb1accd3147801c9070f367d68903d55fee884a3870d78f7053360da50e30.strop",start:5702158,end:7771622},{filename:"/microblink/Model_36d8e94f4cb46097bd6b7385f2aa91fcdee1a5fefeec59e56d1b9e82c94b00a7.strop",start:7771622,end:8141414},{filename:"/microblink/face_detector_model.zzip",start:8141414,end:8238272},{filename:"/microblink/Model_faf688599c7e261a2a7404730f69ed029115bb0d3e7a3657731d88e701720efe.strop",start:8238272,end:8255010},{filename:"/microblink/ccc_lookup_table.zzip",
start:8255010,end:8275479},{filename:"/microblink/Model_9728a773c1b4698cf671cb4a5babc846265c5f7ab0fe34b27cb15c6c50d2881b.strop",start:8275479,end:8973049},{filename:"/microblink/Model_8322bc53f683fdb17f42124244cf6469a82e1c00ec8c43c5d7939ae25ee8c006.strop",start:8973049,end:9492651},{filename:"/microblink/Model_2880751121560047e6dc571bc8ff4683aeb863886f7c0789234594ceb1e23577.strop",start:9492651,end:9496589},{filename:"/microblink/Model_473ac5f5e256623c0a6b282698c1f1b033b9fb5359e6aa142e9fb4a4022afe4e.strop",
start:9496589,end:9503471},{filename:"/microblink/Model_b452fd3cd4037080cfcb4c423dba5bc58c8ceafc28427fdf9c5778fb353f088e.strop",start:9503471,end:9510289}],remote_package_size:9510289,package_uuid:"5242f77c-8493-4049-9278-96111cb782b0"});var crypto={getRandomValues:function(a){for(var b=0;b<a.length;b++)a[b]=256*Math.random()|0}},da=Object.assign({},g),ea="./this.program",fa=(a,b)=>{throw b;},ha="object"==typeof window,ia="function"==typeof importScripts,ja="",ka,la,ma;
if(ha||ia)ia?ja=self.location.href:"undefined"!=typeof document&&document.currentScript&&(ja=document.currentScript.src),_scriptDir&&(ja=_scriptDir),ja=0!==ja.indexOf("blob:")?ja.substr(0,ja.replace(/[?#].*/,"").lastIndexOf("/")+1):"",ka=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},ia&&(ma=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),la=(a,b,c)=>{var d=new XMLHttpRequest;d.open("GET",
a,!0);d.responseType="arraybuffer";d.onload=()=>{200==d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)};var na=g.print||console.log.bind(console),ca=g.printErr||console.warn.bind(console);Object.assign(g,da);da=null;g.thisProgram&&(ea=g.thisProgram);g.quit&&(fa=g.quit);var oa=0,pa;g.wasmBinary&&(pa=g.wasmBinary);var noExitRuntime=g.noExitRuntime||!0;"object"!=typeof WebAssembly&&qa("no native wasm support detected");
var ra,sa=!1,ta="undefined"!=typeof TextDecoder?new TextDecoder("utf8"):void 0;
function ua(a,b,c){var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.buffer&&ta)return ta.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var f=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|f);else{var h=a[b++]&63;e=224==(e&240)?(e&15)<<12|f<<6|h:(e&7)<<18|f<<12|h<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d}function q(a,b){return a?ua(t,a,b):""}
function z(a,b,c,d){if(!(0<d))return 0;var e=c;d=c+d-1;for(var f=0;f<a.length;++f){var h=a.charCodeAt(f);if(55296<=h&&57343>=h){var k=a.charCodeAt(++f);h=65536+((h&1023)<<10)|k&1023}if(127>=h){if(c>=d)break;b[c++]=h}else{if(2047>=h){if(c+1>=d)break;b[c++]=192|h>>6}else{if(65535>=h){if(c+2>=d)break;b[c++]=224|h>>12}else{if(c+3>=d)break;b[c++]=240|h>>18;b[c++]=128|h>>12&63}b[c++]=128|h>>6&63}b[c++]=128|h&63}}b[c]=0;return c-e}
function va(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:b+4}return b}var wa="undefined"!=typeof TextDecoder?new TextDecoder("utf-16le"):void 0;function xa(a,b){var c=a>>1;for(var d=c+b/2;!(c>=d)&&A[c];)++c;c<<=1;if(32<c-a&&wa)return wa.decode(t.subarray(a,c));c="";for(d=0;!(d>=b/2);++d){var e=ya[a+2*d>>1];if(0==e)break;c+=String.fromCharCode(e)}return c}
function za(a,b,c){void 0===c&&(c=2147483647);if(2>c)return 0;c-=2;var d=b;c=c<2*a.length?c/2:a.length;for(var e=0;e<c;++e)ya[b>>1]=a.charCodeAt(e),b+=2;ya[b>>1]=0;return b-d}function Aa(a){return 2*a.length}function Ba(a,b){for(var c=0,d="";!(c>=b/4);){var e=C[a+4*c>>2];if(0==e)break;++c;65536<=e?(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023)):d+=String.fromCharCode(e)}return d}
function Ca(a,b,c){void 0===c&&(c=2147483647);if(4>c)return 0;var d=b;c=d+c-4;for(var e=0;e<a.length;++e){var f=a.charCodeAt(e);if(55296<=f&&57343>=f){var h=a.charCodeAt(++e);f=65536+((f&1023)<<10)|h&1023}C[b>>2]=f;b+=4;if(b+4>c)break}C[b>>2]=0;return b-d}function Da(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&++c;b+=4}return b}function Ea(a){var b=va(a)+1,c=Fa(b);c&&z(a,D,c,b);return c}var Ga,D,t,ya,A,C,E,Ha,Ia;
function Ja(){var a=ra.buffer;Ga=a;g.HEAP8=D=new Int8Array(a);g.HEAP16=ya=new Int16Array(a);g.HEAP32=C=new Int32Array(a);g.HEAPU8=t=new Uint8Array(a);g.HEAPU16=A=new Uint16Array(a);g.HEAPU32=E=new Uint32Array(a);g.HEAPF32=Ha=new Float32Array(a);g.HEAPF64=Ia=new Float64Array(a)}var Ka,La=[],Ma=[],Oa=[];function Pa(){var a=g.preRun.shift();La.unshift(a)}var Qa=0,Ra=null,Sa=null;function Ta(){Qa++;g.monitorRunDependencies&&g.monitorRunDependencies(Qa)}
function Ua(){Qa--;g.monitorRunDependencies&&g.monitorRunDependencies(Qa);if(0==Qa&&(null!==Ra&&(clearInterval(Ra),Ra=null),Sa)){var a=Sa;Sa=null;a()}}g.preloadedImages={};g.preloadedAudios={};function qa(a){if(g.onAbort)g.onAbort(a);a="Aborted("+a+")";ca(a);sa=!0;a=new WebAssembly.RuntimeError(a+". Build with -s ASSERTIONS=1 for more info.");ba(a);throw a;}function Va(){return Wa.startsWith("data:application/octet-stream;base64,")}var Wa;Wa="BlinkIDWasmSDK.wasm";
if(!Va()){var Xa=Wa;Wa=g.locateFile?g.locateFile(Xa,ja):ja+Xa}function Ya(){var a=Wa;try{if(a==Wa&&pa)return new Uint8Array(pa);if(ma)return ma(a);throw"both async and sync fetching of the wasm failed";}catch(b){qa(b)}}function Za(){return pa||!ha&&!ia||"function"!=typeof fetch?Promise.resolve().then(function(){return Ya()}):fetch(Wa,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+Wa+"'";return a.arrayBuffer()}).catch(function(){return Ya()})}
var H,$a,ab={383961:function(a){a=q(a);throw Error("Failed to reconfigure RecognizerRunner due to following error: "+a);},384097:function(a,b,c,d){a=q(a);b=q(b);c=q(c);d=q(d);throw Error(a+b+c+d);},384313:function(a,b){a=q(a);b=q(b);throw Error(a+b);},384423:function(a,b){a=q(a);b=q(b);console.log(a+b)},384521:function(a){throw Error(q(a));},384564:function(){throw Error("Unable to perform that operation while recognizer is in use!");},384647:function(){throw Error("Unable to perform that operation while recognizer is in use!");
},384730:function(){throw Error("Unable to perform that operation while recognizer is in use!");}};function bb(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b(g);else{var c=b.dd;"number"==typeof c?void 0===b.Kb?J(c)():J(c)(b.Kb):c(void 0===b.Kb?null:b.Kb)}}}var cb=[];function J(a){var b=cb[a];b||(a>=cb.length&&(cb.length=a+1),cb[a]=b=Ka.get(a));return b}
function db(a,b){for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a}function K(a){var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=db(a.split("/").filter(function(d){return!!d}),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a}
function eb(a){var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,b.length-1));return a+b}function fb(a){if("/"===a)return"/";a=K(a);a=a.replace(/\/$/,"");var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)}function gb(){if("object"==typeof crypto&&"function"==typeof crypto.getRandomValues){var a=new Uint8Array(1);return function(){crypto.getRandomValues(a);return a[0]}}return function(){qa("randomDevice")}}
function hb(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:"/";if("string"!=typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=db(a.split("/").filter(function(d){return!!d}),!b).join("/");return(b?"/":"")+a||"."}var ib=[];function jb(a,b){ib[a]={input:[],Ua:[],qb:b};kb(a,lb)}
var lb={open:function(a){var b=ib[a.node.ub];if(!b)throw new L(43);a.Ta=b;a.seekable=!1},close:function(a){a.Ta.qb.flush(a.Ta)},flush:function(a){a.Ta.qb.flush(a.Ta)},read:function(a,b,c,d){if(!a.Ta||!a.Ta.qb.dc)throw new L(60);for(var e=0,f=0;f<d;f++){try{var h=a.Ta.qb.dc(a.Ta)}catch(k){throw new L(29);}if(void 0===h&&0===e)throw new L(6);if(null===h||void 0===h)break;e++;b[c+f]=h}e&&(a.node.timestamp=Date.now());return e},write:function(a,b,c,d){if(!a.Ta||!a.Ta.qb.Qb)throw new L(60);try{for(var e=
0;e<d;e++)a.Ta.qb.Qb(a.Ta,b[c+e])}catch(f){throw new L(29);}d&&(a.node.timestamp=Date.now());return e}},nb={dc:function(a){if(!a.input.length){var b=null;"undefined"!=typeof window&&"function"==typeof window.prompt?(b=window.prompt("Input: "),null!==b&&(b+="\n")):"function"==typeof readline&&(b=readline(),null!==b&&(b+="\n"));if(!b)return null;a.input=mb(b,!0)}return a.input.shift()},Qb:function(a,b){null===b||10===b?(na(ua(a.Ua,0)),a.Ua=[]):0!=b&&a.Ua.push(b)},flush:function(a){a.Ua&&0<a.Ua.length&&
(na(ua(a.Ua,0)),a.Ua=[])}},ob={Qb:function(a,b){null===b||10===b?(ca(ua(a.Ua,0)),a.Ua=[]):0!=b&&a.Ua.push(b)},flush:function(a){a.Ua&&0<a.Ua.length&&(ca(ua(a.Ua,0)),a.Ua=[])}},M={cb:null,fb:function(){return M.createNode(null,"/",16895,0)},createNode:function(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new L(63);M.cb||(M.cb={dir:{node:{bb:M.Na.bb,Ya:M.Na.Ya,rb:M.Na.rb,Db:M.Na.Db,lc:M.Na.lc,Jb:M.Na.Jb,mc:M.Na.mc,kc:M.Na.kc,Gb:M.Na.Gb},stream:{jb:M.Oa.jb}},file:{node:{bb:M.Na.bb,Ya:M.Na.Ya},
stream:{jb:M.Oa.jb,read:M.Oa.read,write:M.Oa.write,Wb:M.Oa.Wb,Eb:M.Oa.Eb,Fb:M.Oa.Fb}},link:{node:{bb:M.Na.bb,Ya:M.Na.Ya,vb:M.Na.vb},stream:{}},Yb:{node:{bb:M.Na.bb,Ya:M.Na.Ya},stream:pb}});c=qb(a,b,c,d);16384===(c.mode&61440)?(c.Na=M.cb.dir.node,c.Oa=M.cb.dir.stream,c.Ma={}):32768===(c.mode&61440)?(c.Na=M.cb.file.node,c.Oa=M.cb.file.stream,c.Ra=0,c.Ma=null):40960===(c.mode&61440)?(c.Na=M.cb.link.node,c.Oa=M.cb.link.stream):8192===(c.mode&61440)&&(c.Na=M.cb.Yb.node,c.Oa=M.cb.Yb.stream);c.timestamp=
Date.now();a&&(a.Ma[b]=c,a.timestamp=c.timestamp);return c},ed:function(a){return a.Ma?a.Ma.subarray?a.Ma.subarray(0,a.Ra):new Uint8Array(a.Ma):new Uint8Array(0)},ac:function(a,b){var c=a.Ma?a.Ma.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)>>>0),0!=c&&(b=Math.max(b,256)),c=a.Ma,a.Ma=new Uint8Array(b),0<a.Ra&&a.Ma.set(c.subarray(0,a.Ra),0))},Rc:function(a,b){if(a.Ra!=b)if(0==b)a.Ma=null,a.Ra=0;else{var c=a.Ma;a.Ma=new Uint8Array(b);c&&a.Ma.set(c.subarray(0,Math.min(b,a.Ra)));a.Ra=b}},Na:{bb:function(a){var b=
{};b.yc=8192===(a.mode&61440)?a.id:1;b.Nb=a.id;b.mode=a.mode;b.Nc=1;b.uid=0;b.Fc=0;b.ub=a.ub;b.size=16384===(a.mode&61440)?4096:32768===(a.mode&61440)?a.Ra:40960===(a.mode&61440)?a.link.length:0;b.rc=new Date(a.timestamp);b.Mc=new Date(a.timestamp);b.xc=new Date(a.timestamp);b.sc=4096;b.tc=Math.ceil(b.size/b.sc);return b},Ya:function(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);void 0!==b.size&&M.Rc(a,b.size)},rb:function(){throw rb[44];},Db:function(a,b,c,
d){return M.createNode(a,b,c,d)},lc:function(a,b,c){if(16384===(a.mode&61440)){try{var d=sb(b,c)}catch(f){}if(d)for(var e in d.Ma)throw new L(55);}delete a.parent.Ma[a.name];a.parent.timestamp=Date.now();a.name=c;b.Ma[c]=a;b.timestamp=a.parent.timestamp;a.parent=b},Jb:function(a,b){delete a.Ma[b];a.timestamp=Date.now()},mc:function(a,b){var c=sb(a,b),d;for(d in c.Ma)throw new L(55);delete a.Ma[b];a.timestamp=Date.now()},kc:function(a){var b=[".",".."],c;for(c in a.Ma)a.Ma.hasOwnProperty(c)&&b.push(c);
return b},Gb:function(a,b,c){a=M.createNode(a,b,41471,0);a.link=c;return a},vb:function(a){if(40960!==(a.mode&61440))throw new L(28);return a.link}},Oa:{read:function(a,b,c,d,e){var f=a.node.Ma;if(e>=a.node.Ra)return 0;a=Math.min(a.node.Ra-e,d);if(8<a&&f.subarray)b.set(f.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=f[e+d];return a},write:function(a,b,c,d,e,f){b.buffer===D.buffer&&(f=!1);if(!d)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&(!a.Ma||a.Ma.subarray)){if(f)return a.Ma=b.subarray(c,
c+d),a.Ra=d;if(0===a.Ra&&0===e)return a.Ma=b.slice(c,c+d),a.Ra=d;if(e+d<=a.Ra)return a.Ma.set(b.subarray(c,c+d),e),d}M.ac(a,e+d);if(a.Ma.subarray&&b.subarray)a.Ma.set(b.subarray(c,c+d),e);else for(f=0;f<d;f++)a.Ma[e+f]=b[c+f];a.Ra=Math.max(a.Ra,e+d);return d},jb:function(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.Ra);if(0>b)throw new L(28);return b},Wb:function(a,b,c){M.ac(a.node,b+c);a.node.Ra=Math.max(a.node.Ra,b+c)},Eb:function(a,b,c,d,e,f){if(0!==b)throw new L(28);
if(32768!==(a.node.mode&61440))throw new L(43);a=a.node.Ma;if(f&2||a.buffer!==Ga){if(0<d||d+c<a.length)a=a.subarray?a.subarray(d,d+c):Array.prototype.slice.call(a,d,d+c);d=!0;c=65536*Math.ceil(c/65536);(f=tb(65536,c))?(t.fill(0,f,f+c),c=f):c=0;if(!c)throw new L(48);D.set(a,c)}else d=!1,c=a.byteOffset;return{Qa:c,qc:d}},Fb:function(a,b,c,d,e){if(32768!==(a.node.mode&61440))throw new L(43);if(e&2)return 0;M.Oa.write(a,b,0,d,c,!1);return 0}}};
function ub(a,b,c){var d="al "+a;la(a,function(e){e||qa('Loading data file "'+a+'" failed (no arrayBuffer).');b(new Uint8Array(e));d&&Ua(d)},function(){if(c)c();else throw'Loading data file "'+a+'" failed.';});d&&Ta(d)}
var vb=null,wb={},xb=[],yb=1,zb=null,Ab=!0,L=null,rb={},N=(a,b={})=>{a=hb("/",a);if(!a)return{path:"",node:null};b=Object.assign({cc:!0,Sb:0},b);if(8<b.Sb)throw new L(32);a=db(a.split("/").filter(h=>!!h),!1);for(var c=vb,d="/",e=0;e<a.length;e++){var f=e===a.length-1;if(f&&b.parent)break;c=sb(c,a[e]);d=K(d+"/"+a[e]);c.sb&&(!f||f&&b.cc)&&(c=c.sb.root);if(!f||b.zb)for(f=0;40960===(c.mode&61440);)if(c=Bb(d),d=hb(eb(d),c),c=N(d,{Sb:b.Sb+1}).node,40<f++)throw new L(32);}return{path:d,node:c}},Cb=a=>{for(var b;;){if(a===
a.parent)return a=a.fb.fc,b?"/"!==a[a.length-1]?a+"/"+b:a+b:a;b=b?a.name+"/"+b:a.name;a=a.parent}},Db=(a,b)=>{for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%zb.length},sb=(a,b)=>{var c;if(c=(c=Eb(a,"x"))?c:a.Na.rb?0:2)throw new L(c,a);for(c=zb[Db(a.id,b)];c;c=c.pb){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.Na.rb(a,b)},qb=(a,b,c,d)=>{a=new Fb(a,b,c,d);b=Db(a.parent.id,a.name);a.pb=zb[b];return zb[b]=a},Gb={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090},Hb=
a=>{var b=["r","w","rw"][a&3];a&512&&(b+="w");return b},Eb=(a,b)=>{if(Ab)return 0;if(!b.includes("r")||a.mode&292){if(b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73))return 2}else return 2;return 0},Ib=(a,b)=>{try{return sb(a,b),20}catch(c){}return Eb(a,"wx")},Jb=(a=0,b=4096)=>{for(;a<=b;a++)if(!xb[a])return a;throw new L(33);},Lb=(a,b)=>{Kb||(Kb=function(){},Kb.prototype={object:{get:function(){return this.node},set:function(c){this.node=c}}});a=Object.assign(new Kb,a);b=Jb(b,void 0);
a.hb=b;return xb[b]=a},pb={open:a=>{a.Oa=wb[a.node.ub].Oa;a.Oa.open&&a.Oa.open(a)},jb:()=>{throw new L(70);}},kb=(a,b)=>{wb[a]={Oa:b}},Mb=(a,b)=>{var c="/"===b,d=!b;if(c&&vb)throw new L(10);if(!c&&!d){var e=N(b,{cc:!1});b=e.path;e=e.node;if(e.sb)throw new L(10);if(16384!==(e.mode&61440))throw new L(54);}b={type:a,hd:{},fc:b,Lc:[]};a=a.fb(b);a.fb=b;b.root=a;c?vb=a:e&&(e.sb=b,e.fb&&e.fb.Lc.push(b))},O=(a,b,c)=>{var d=N(a,{parent:!0}).node;a=fb(a);if(!a||"."===a||".."===a)throw new L(28);var e=Ib(d,
a);if(e)throw new L(e);if(!d.Na.Db)throw new L(63);return d.Na.Db(d,a,b,c)},Nb=(a,b,c)=>{"undefined"==typeof c&&(c=b,b=438);return O(a,b|8192,c)},Ob=(a,b)=>{if(!hb(a))throw new L(44);var c=N(b,{parent:!0}).node;if(!c)throw new L(44);b=fb(b);var d=Ib(c,b);if(d)throw new L(d);if(!c.Na.Gb)throw new L(63);c.Na.Gb(c,b,a)},Pb=a=>{var b=N(a,{parent:!0}).node;if(!b)throw new L(44);var c=fb(a);a=sb(b,c);a:{try{var d=sb(b,c)}catch(f){d=f.Wa;break a}var e=Eb(b,"wx");d=e?e:16384===(d.mode&61440)?31:0}if(d)throw new L(d);
if(!b.Na.Jb)throw new L(63);if(a.sb)throw new L(10);b.Na.Jb(b,c);b=Db(a.parent.id,a.name);if(zb[b]===a)zb[b]=a.pb;else for(b=zb[b];b;){if(b.pb===a){b.pb=a.pb;break}b=b.pb}},Bb=a=>{a=N(a).node;if(!a)throw new L(44);if(!a.Na.vb)throw new L(28);return hb(Cb(a.parent),a.Na.vb(a))},Qb=(a,b)=>{a=N(a,{zb:!b}).node;if(!a)throw new L(44);if(!a.Na.bb)throw new L(63);return a.Na.bb(a)},Rb=a=>Qb(a,!0),Sb=(a,b)=>{a="string"==typeof a?N(a,{zb:!0}).node:a;if(!a.Na.Ya)throw new L(63);a.Na.Ya(a,{mode:b&4095|a.mode&
-4096,timestamp:Date.now()})},Ub=(a,b,c,d)=>{if(""===a)throw new L(44);if("string"==typeof b){var e=Gb[b];if("undefined"==typeof e)throw Error("Unknown file open mode: "+b);b=e}c=b&64?("undefined"==typeof c?438:c)&4095|32768:0;if("object"==typeof a)var f=a;else{a=K(a);try{f=N(a,{zb:!(b&131072)}).node}catch(h){}}e=!1;if(b&64)if(f){if(b&128)throw new L(20);}else f=O(a,c,0),e=!0;if(!f)throw new L(44);8192===(f.mode&61440)&&(b&=-513);if(b&65536&&16384!==(f.mode&61440))throw new L(54);if(!e&&(c=f?40960===
(f.mode&61440)?32:16384===(f.mode&61440)&&("r"!==Hb(b)||b&512)?31:Eb(f,Hb(b)):44))throw new L(c);if(b&512){c=f;c="string"==typeof c?N(c,{zb:!0}).node:c;if(!c.Na.Ya)throw new L(63);if(16384===(c.mode&61440))throw new L(31);if(32768!==(c.mode&61440))throw new L(28);if(e=Eb(c,"w"))throw new L(e);c.Na.Ya(c,{size:0,timestamp:Date.now()})}b&=-131713;d=Lb({node:f,path:Cb(f),flags:b,seekable:!0,position:0,Oa:f.Oa,bd:[],error:!1},d);d.Oa.open&&d.Oa.open(d);!g.logReadFiles||b&1||(Tb||(Tb={}),a in Tb||(Tb[a]=
1));return d},Vb=a=>{if(null===a.hb)throw new L(8);a.Mb&&(a.Mb=null);try{a.Oa.close&&a.Oa.close(a)}catch(b){throw b;}finally{xb[a.hb]=null}a.hb=null},Wb=(a,b,c)=>{if(null===a.hb)throw new L(8);if(!a.seekable||!a.Oa.jb)throw new L(70);if(0!=c&&1!=c&&2!=c)throw new L(28);a.position=a.Oa.jb(a,b,c);a.bd=[]},Xb=(a,b,c,d,e,f)=>{if(0>d||0>e)throw new L(28);if(null===a.hb)throw new L(8);if(0===(a.flags&2097155))throw new L(8);if(16384===(a.node.mode&61440))throw new L(31);if(!a.Oa.write)throw new L(28);a.seekable&&
a.flags&1024&&Wb(a,0,2);var h="undefined"!=typeof e;if(!h)e=a.position;else if(!a.seekable)throw new L(70);b=a.Oa.write(a,b,c,d,e,f);h||(a.position+=b);return b},Yb=()=>{L||(L=function(a,b){this.node=b;this.Tc=function(c){this.Wa=c};this.Tc(a);this.message="FS error"},L.prototype=Error(),L.prototype.constructor=L,[44].forEach(a=>{rb[a]=new L(a);rb[a].stack="<generic error, no stack>"}))},Zb,$b=(a,b)=>{var c=0;a&&(c|=365);b&&(c|=146);return c},ac=(a,b)=>{a="string"==typeof a?a:Cb(a);for(b=b.split("/").reverse();b.length;){var c=
b.pop();if(c){var d=K(a+"/"+c);try{O(d,16895,0)}catch(e){}a=d}}return d},bc=(a,b,c,d)=>{a=K(("string"==typeof a?a:Cb(a))+"/"+b);c=$b(c,d);return O(a,(void 0!==c?c:438)&4095|32768,0)},cc=(a,b,c,d,e,f)=>{var h=b;a&&(a="string"==typeof a?a:Cb(a),h=b?K(a+"/"+b):a);a=$b(d,e);h=O(h,(void 0!==a?a:438)&4095|32768,0);if(c){if("string"==typeof c){b=Array(c.length);d=0;for(e=c.length;d<e;++d)b[d]=c.charCodeAt(d);c=b}Sb(h,a|146);b=Ub(h,577);Xb(b,c,0,c.length,0,f);Vb(b);Sb(h,a)}return h},Q=(a,b,c,d)=>{a=K(("string"==
typeof a?a:Cb(a))+"/"+b);b=$b(!!c,!!d);Q.ec||(Q.ec=64);var e=Q.ec++<<8|0;kb(e,{open:f=>{f.seekable=!1},close:()=>{d&&d.buffer&&d.buffer.length&&d(10)},read:(f,h,k,m)=>{for(var p=0,n=0;n<m;n++){try{var r=c()}catch(v){throw new L(29);}if(void 0===r&&0===p)throw new L(6);if(null===r||void 0===r)break;p++;h[k+n]=r}p&&(f.node.timestamp=Date.now());return p},write:(f,h,k,m)=>{for(var p=0;p<m;p++)try{d(h[k+p])}catch(n){throw new L(29);}m&&(f.node.timestamp=Date.now());return p}});return Nb(a,b,e)},dc=a=>
{if(!(a.Ic||a.Jc||a.link||a.Ma)){if("undefined"!=typeof XMLHttpRequest)throw Error("Lazy loading should have been performed (contents set) in createLazyFile, but it was not. Lazy loading only works in web workers. Use --embed-file or --preload-file in emcc on the main thread.");if(ka)try{a.Ma=mb(ka(a.url),!0),a.Ra=a.Ma.length}catch(b){throw new L(29);}else throw Error("Cannot load without read() or XMLHttpRequest.");}},ec=(a,b,c,d,e)=>{function f(){this.Pb=!1;this.yb=[]}f.prototype.get=function(n){if(!(n>
this.length-1||0>n)){var r=n%this.Zb;return this.Ab(n/this.Zb|0)[r]}};f.prototype.Sc=function(n){this.Ab=n};f.prototype.Xb=function(){var n=new XMLHttpRequest;n.open("HEAD",c,!1);n.send(null);if(!(200<=n.status&&300>n.status||304===n.status))throw Error("Couldn't load "+c+". Status: "+n.status);var r=Number(n.getResponseHeader("Content-length")),v,l=(v=n.getResponseHeader("Accept-Ranges"))&&"bytes"===v;n=(v=n.getResponseHeader("Content-Encoding"))&&"gzip"===v;var u=1048576;l||(u=r);var w=this;w.Sc(y=>
{var I=y*u,F=(y+1)*u-1;F=Math.min(F,r-1);if("undefined"==typeof w.yb[y]){var x=w.yb;if(I>F)throw Error("invalid range ("+I+", "+F+") or no bytes requested!");if(F>r-1)throw Error("only "+r+" bytes available! programmer error!");var B=new XMLHttpRequest;B.open("GET",c,!1);r!==u&&B.setRequestHeader("Range","bytes="+I+"-"+F);B.responseType="arraybuffer";B.overrideMimeType&&B.overrideMimeType("text/plain; charset=x-user-defined");B.send(null);if(!(200<=B.status&&300>B.status||304===B.status))throw Error("Couldn't load "+
c+". Status: "+B.status);I=void 0!==B.response?new Uint8Array(B.response||[]):mb(B.responseText||"",!0);x[y]=I}if("undefined"==typeof w.yb[y])throw Error("doXHR failed!");return w.yb[y]});if(n||!r)u=r=1,u=r=this.Ab(0).length,na("LazyFiles on gzip forces download of the whole file when length is accessed");this.oc=r;this.nc=u;this.Pb=!0};if("undefined"!=typeof XMLHttpRequest){if(!ia)throw"Cannot do synchronous binary XHRs outside webworkers in modern browsers. Use --embed-file or --preload-file in emcc";
var h=new f;Object.defineProperties(h,{length:{get:function(){this.Pb||this.Xb();return this.oc}},Zb:{get:function(){this.Pb||this.Xb();return this.nc}}});var k=void 0}else k=c,h=void 0;var m=bc(a,b,d,e);h?m.Ma=h:k&&(m.Ma=null,m.url=k);Object.defineProperties(m,{Ra:{get:function(){return this.Ma.length}}});var p={};Object.keys(m.Oa).forEach(n=>{var r=m.Oa[n];p[n]=function(){dc(m);return r.apply(null,arguments)}});p.read=(n,r,v,l,u)=>{dc(m);n=n.node.Ma;if(u>=n.length)return 0;l=Math.min(n.length-u,
l);if(n.slice)for(var w=0;w<l;w++)r[v+w]=n[u+w];else for(w=0;w<l;w++)r[v+w]=n.get(u+w);return l};m.Oa=p;return m},gc=(a,b,c,d,e,f,h,k,m,p)=>{function n(l){function u(w){p&&p();k||cc(a,b,w,d,e,m);f&&f();Ua(v)}fc.fd(l,r,u,()=>{h&&h();Ua(v)})||u(l)}var r=b?hb(K(a+"/"+b)):a,v="cp "+r;Ta(v);"string"==typeof c?ub(c,l=>n(l),h):n(c)},R={},Kb,Tb;
function hc(a,b,c){if("/"===b[0])return b;if(-100===a)a="/";else{a=xb[a];if(!a)throw new L(8);a=a.path}if(0==b.length){if(!c)throw new L(44);return a}return K(a+"/"+b)}
function ic(a,b,c){try{var d=a(b)}catch(e){if(e&&e.node&&K(b)!==K(Cb(e.node)))return-54;throw e;}C[c>>2]=d.yc;C[c+4>>2]=0;C[c+8>>2]=d.Nb;C[c+12>>2]=d.mode;C[c+16>>2]=d.Nc;C[c+20>>2]=d.uid;C[c+24>>2]=d.Fc;C[c+28>>2]=d.ub;C[c+32>>2]=0;$a=[d.size>>>0,(H=d.size,1<=+Math.abs(H)?0<H?(Math.min(+Math.floor(H/4294967296),4294967295)|0)>>>0:~~+Math.ceil((H-+(~~H>>>0))/4294967296)>>>0:0)];C[c+40>>2]=$a[0];C[c+44>>2]=$a[1];C[c+48>>2]=4096;C[c+52>>2]=d.tc;C[c+56>>2]=d.rc.getTime()/1E3|0;C[c+60>>2]=0;C[c+64>>2]=
d.Mc.getTime()/1E3|0;C[c+68>>2]=0;C[c+72>>2]=d.xc.getTime()/1E3|0;C[c+76>>2]=0;$a=[d.Nb>>>0,(H=d.Nb,1<=+Math.abs(H)?0<H?(Math.min(+Math.floor(H/4294967296),4294967295)|0)>>>0:~~+Math.ceil((H-+(~~H>>>0))/4294967296)>>>0:0)];C[c+80>>2]=$a[0];C[c+84>>2]=$a[1];return 0}var jc=void 0;function kc(){jc+=4;return C[jc-4>>2]}function lc(a){a=xb[a];if(!a)throw new L(8);return a}var mc={};function nc(a){for(;a.length;){var b=a.pop();a.pop()(b)}}function oc(a){return this.fromWireType(E[a>>2])}
var pc={},qc={},rc={};function sc(a){if(void 0===a)return"_unknown";a=a.replace(/[^a-zA-Z0-9_]/g,"$");var b=a.charCodeAt(0);return 48<=b&&57>=b?"_"+a:a}function tc(a,b){a=sc(a);return(new Function("body","return function "+a+'() {\n    "use strict";    return body.apply(this, arguments);\n};\n'))(b)}
function uc(a){var b=Error,c=tc(a,function(d){this.name=a;this.message=d;d=Error(d).stack;void 0!==d&&(this.stack=this.toString()+"\n"+d.replace(/^Error(:[^\n]*)?\n/,""))});c.prototype=Object.create(b.prototype);c.prototype.constructor=c;c.prototype.toString=function(){return void 0===this.message?this.name:this.name+": "+this.message};return c}var vc=void 0;function wc(a){throw new vc(a);}
function xc(a,b,c){function d(k){k=c(k);k.length!==a.length&&wc("Mismatched type converter count");for(var m=0;m<a.length;++m)yc(a[m],k[m])}a.forEach(function(k){rc[k]=b});var e=Array(b.length),f=[],h=0;b.forEach((k,m)=>{qc.hasOwnProperty(k)?e[m]=qc[k]:(f.push(k),pc.hasOwnProperty(k)||(pc[k]=[]),pc[k].push(()=>{e[m]=qc[k];++h;h===f.length&&d(e)}))});0===f.length&&d(e)}
function zc(a){switch(a){case 1:return 0;case 2:return 1;case 4:return 2;case 8:return 3;default:throw new TypeError("Unknown type size: "+a);}}var Ac=void 0;function S(a){for(var b="";t[a];)b+=Ac[t[a++]];return b}var Bc=void 0;function T(a){throw new Bc(a);}
function yc(a,b,c={}){if(!("argPackAdvance"in b))throw new TypeError("registerType registeredInstance requires argPackAdvance");var d=b.name;a||T('type "'+d+'" must have a positive integer typeid pointer');if(qc.hasOwnProperty(a)){if(c.Gc)return;T("Cannot register type '"+d+"' twice")}qc[a]=b;delete rc[a];pc.hasOwnProperty(a)&&(b=pc[a],delete pc[a],b.forEach(e=>e()))}function Cc(a){T(a.La.Sa.Pa.name+" instance already deleted")}var Dc=!1;function Ec(){}
function Fc(a){--a.count.value;0===a.count.value&&(a.Xa?a.Za.gb(a.Xa):a.Sa.Pa.gb(a.Qa))}function Gc(a,b,c){if(b===c)return a;if(void 0===c.$a)return null;a=Gc(a,b,c.$a);return null===a?null:c.zc(a)}var Hc={},Ic=[];function Jc(){for(;Ic.length;){var a=Ic.pop();a.La.nb=!1;a["delete"]()}}var Kc=void 0,Lc={};function Mc(a,b){for(void 0===b&&T("ptr should not be undefined");a.$a;)b=a.wb(b),a=a.$a;return Lc[b]}
function Nc(a,b){b.Sa&&b.Qa||wc("makeClassHandle requires ptr and ptrType");!!b.Za!==!!b.Xa&&wc("Both smartPtrType and smartPtr must be specified");b.count={value:1};return Oc(Object.create(a,{La:{value:b}}))}function Oc(a){if("undefined"===typeof FinalizationRegistry)return Oc=b=>b,a;Dc=new FinalizationRegistry(b=>{Fc(b.La)});Oc=b=>{var c=b.La;c.Xa&&Dc.register(b,{La:c},b);return b};Ec=b=>{Dc.unregister(b)};return Oc(a)}function Pc(){}
function Qc(a,b,c){if(void 0===a[b].Va){var d=a[b];a[b]=function(){a[b].Va.hasOwnProperty(arguments.length)||T("Function '"+c+"' called with an invalid number of arguments ("+arguments.length+") - expects one of ("+a[b].Va+")!");return a[b].Va[arguments.length].apply(this,arguments)};a[b].Va=[];a[b].Va[d.xb]=d}}
function Rc(a,b,c){g.hasOwnProperty(a)?((void 0===c||void 0!==g[a].Va&&void 0!==g[a].Va[c])&&T("Cannot register public name '"+a+"' twice"),Qc(g,a,a),g.hasOwnProperty(c)&&T("Cannot register multiple overloads of a function with the same number of arguments ("+c+")!"),g[a].Va[c]=b):(g[a]=b,void 0!==c&&(g[a].gd=c))}function Sc(a,b,c,d,e,f,h,k){this.name=a;this.constructor=b;this.ob=c;this.gb=d;this.$a=e;this.Bc=f;this.wb=h;this.zc=k;this.Pc=[]}
function Tc(a,b,c){for(;b!==c;)b.wb||T("Expected null or instance of "+c.name+", got an instance of "+b.name),a=b.wb(a),b=b.$a;return a}function Uc(a,b){if(null===b)return this.Ob&&T("null is not a valid "+this.name),0;b.La||T('Cannot pass "'+Vc(b)+'" as a '+this.name);b.La.Qa||T("Cannot pass deleted object as a pointer of type "+this.name);return Tc(b.La.Qa,b.La.Sa.Pa,this.Pa)}
function Wc(a,b){if(null===b){this.Ob&&T("null is not a valid "+this.name);if(this.Cb){var c=this.Rb();null!==a&&a.push(this.gb,c);return c}return 0}b.La||T('Cannot pass "'+Vc(b)+'" as a '+this.name);b.La.Qa||T("Cannot pass deleted object as a pointer of type "+this.name);!this.Bb&&b.La.Sa.Bb&&T("Cannot convert argument of type "+(b.La.Za?b.La.Za.name:b.La.Sa.name)+" to parameter type "+this.name);c=Tc(b.La.Qa,b.La.Sa.Pa,this.Pa);if(this.Cb)switch(void 0===b.La.Xa&&T("Passing raw pointer to smart pointer is illegal"),
this.Xc){case 0:b.La.Za===this?c=b.La.Xa:T("Cannot convert argument of type "+(b.La.Za?b.La.Za.name:b.La.Sa.name)+" to parameter type "+this.name);break;case 1:c=b.La.Xa;break;case 2:if(b.La.Za===this)c=b.La.Xa;else{var d=b.clone();c=this.Qc(c,U(function(){d["delete"]()}));null!==a&&a.push(this.gb,c)}break;default:T("Unsupporting sharing policy")}return c}
function Xc(a,b){if(null===b)return this.Ob&&T("null is not a valid "+this.name),0;b.La||T('Cannot pass "'+Vc(b)+'" as a '+this.name);b.La.Qa||T("Cannot pass deleted object as a pointer of type "+this.name);b.La.Sa.Bb&&T("Cannot convert argument of type "+b.La.Sa.name+" to parameter type "+this.name);return Tc(b.La.Qa,b.La.Sa.Pa,this.Pa)}
function Yc(a,b,c,d){this.name=a;this.Pa=b;this.Ob=c;this.Bb=d;this.Cb=!1;this.gb=this.Qc=this.Rb=this.jc=this.Xc=this.Oc=void 0;void 0!==b.$a?this.toWireType=Wc:(this.toWireType=d?Uc:Xc,this.ab=null)}function Zc(a,b,c){g.hasOwnProperty(a)||wc("Replacing nonexistant public symbol");void 0!==g[a].Va&&void 0!==c?g[a].Va[c]=b:(g[a]=b,g[a].xb=c)}
function $c(a,b){var c=[];return function(){c.length=0;Object.assign(c,arguments);if(a.includes("j")){var d=g["dynCall_"+a];d=c&&c.length?d.apply(null,[b].concat(c)):d.call(null,b)}else d=J(b).apply(null,c);return d}}function V(a,b){a=S(a);var c=a.includes("j")?$c(a,b):J(b);"function"!=typeof c&&T("unknown function pointer with signature "+a+": "+b);return c}var ad=void 0;function bd(a){a=cd(a);var b=S(a);W(a);return b}
function dd(a,b){function c(f){e[f]||qc[f]||(rc[f]?rc[f].forEach(c):(d.push(f),e[f]=!0))}var d=[],e={};b.forEach(c);throw new ad(a+": "+d.map(bd).join([", "]));}function ed(a,b){for(var c=[],d=0;d<a;d++)c.push(C[(b>>2)+d]);return c}
function fd(a){var b=Function;if(!(b instanceof Function))throw new TypeError("new_ called with constructor type "+typeof b+" which is not a function");var c=tc(b.name||"unknownFunctionName",function(){});c.prototype=b.prototype;c=new c;a=b.apply(c,a);return a instanceof Object?a:c}
function gd(a,b,c,d,e){var f=b.length;2>f&&T("argTypes array size mismatch! Must at least get return value and 'this' types!");var h=null!==b[1]&&null!==c,k=!1;for(c=1;c<b.length;++c)if(null!==b[c]&&void 0===b[c].ab){k=!0;break}var m="void"!==b[0].name,p="",n="";for(c=0;c<f-2;++c)p+=(0!==c?", ":"")+"arg"+c,n+=(0!==c?", ":"")+"arg"+c+"Wired";a="return function "+sc(a)+"("+p+") {\nif (arguments.length !== "+(f-2)+") {\nthrowBindingError('function "+a+" called with ' + arguments.length + ' arguments, expected "+
(f-2)+" args!');\n}\n";k&&(a+="var destructors = [];\n");var r=k?"destructors":"null";p="throwBindingError invoker fn runDestructors retType classParam".split(" ");d=[T,d,e,nc,b[0],b[1]];h&&(a+="var thisWired = classParam.toWireType("+r+", this);\n");for(c=0;c<f-2;++c)a+="var arg"+c+"Wired = argType"+c+".toWireType("+r+", arg"+c+"); // "+b[c+2].name+"\n",p.push("argType"+c),d.push(b[c+2]);h&&(n="thisWired"+(0<n.length?", ":"")+n);a+=(m?"var rv = ":"")+"invoker(fn"+(0<n.length?", ":"")+n+");\n";if(k)a+=
"runDestructors(destructors);\n";else for(c=h?1:2;c<b.length;++c)f=1===c?"thisWired":"arg"+(c-2)+"Wired",null!==b[c].ab&&(a+=f+"_dtor("+f+"); // "+b[c].name+"\n",p.push(f+"_dtor"),d.push(b[c].ab));m&&(a+="var ret = retType.fromWireType(rv);\nreturn ret;\n");p.push(a+"}\n");return fd(p).apply(null,d)}var hd=[],X=[{},{value:void 0},{value:null},{value:!0},{value:!1}];function jd(a){4<a&&0===--X[a].Tb&&(X[a]=void 0,hd.push(a))}
var Y=a=>{a||T("Cannot use deleted val. handle = "+a);return X[a].value},U=a=>{switch(a){case void 0:return 1;case null:return 2;case !0:return 3;case !1:return 4;default:var b=hd.length?hd.pop():X.length;X[b]={Tb:1,value:a};return b}};function Vc(a){if(null===a)return"null";var b=typeof a;return"object"===b||"array"===b||"function"===b?a.toString():""+a}
function kd(a,b){switch(b){case 2:return function(c){return this.fromWireType(Ha[c>>2])};case 3:return function(c){return this.fromWireType(Ia[c>>3])};default:throw new TypeError("Unknown float type: "+a);}}
function ld(a,b,c){switch(b){case 0:return c?function(d){return D[d]}:function(d){return t[d]};case 1:return c?function(d){return ya[d>>1]}:function(d){return A[d>>1]};case 2:return c?function(d){return C[d>>2]}:function(d){return E[d>>2]};default:throw new TypeError("Unknown integer type: "+a);}}function md(a,b){var c=qc[a];void 0===c&&T(b+" has unknown type "+bd(a));return c}function nd(a,b){for(var c=Array(a),d=0;d<a;++d)c[d]=md(C[(b>>2)+d],"parameter "+d);return c}var od={};
function pd(a){var b=od[a];return void 0===b?S(a):b}var qd=[];function rd(){return"object"==typeof globalThis?globalThis:Function("return this")()}function sd(a){var b=qd.length;qd.push(a);return b}var td=[],ud={};
function vd(a,b,c){function d(m){return(m=m.toTimeString().match(/\(([A-Za-z ]+)\)$/))?m[1]:"GMT"}var e=(new Date).getFullYear(),f=new Date(e,0,1),h=new Date(e,6,1);e=f.getTimezoneOffset();var k=h.getTimezoneOffset();C[a>>2]=60*Math.max(e,k);C[b>>2]=Number(e!=k);a=d(f);b=d(h);a=Ea(a);b=Ea(b);k<e?(C[c>>2]=a,C[c+4>>2]=b):(C[c>>2]=b,C[c+4>>2]=a)}function wd(a,b,c){wd.vc||(wd.vc=!0,vd(a,b,c))}var xd=[],yd=[];function Z(a,b){E[a>>2]=b;E[a+4>>2]=b/4294967296|0}var zd;
function Ad(a,b,c,d,e){function f(B){var P=0,G=0;B&&(G=x.response?x.response.byteLength:0,P=Fa(G),t.set(new Uint8Array(x.response),P));E[a+12>>2]=P;Z(a+16,G)}var h=E[a+8>>2];if(h){var k=q(h),m=a+112,p=q(m);p||(p="GET");var n=E[m+52>>2],r=E[m+56>>2],v=!!E[m+60>>2],l=E[m+68>>2],u=E[m+72>>2];h=E[m+76>>2];var w=E[m+80>>2],y=E[m+84>>2];m=E[m+88>>2];var I=!!(n&1),F=!!(n&2);n=!!(n&64);l=l?q(l):void 0;u=u?q(u):void 0;var x=new XMLHttpRequest;x.withCredentials=v;x.open(p,k,!n,l,u);n||(x.timeout=r);x.kd=k;
x.responseType="arraybuffer";w&&(k=q(w),x.overrideMimeType(k));if(h)for(;;){p=E[h>>2];if(!p)break;k=E[h+4>>2];if(!k)break;h+=8;p=q(p);k=q(k);x.setRequestHeader(p,k)}yd.push(x);E[a+0>>2]=yd.length;h=y&&m?t.slice(y,y+m):null;x.onload=B=>{f(I&&!F);var P=x.response?x.response.byteLength:0;Z(a+24,0);P&&Z(a+32,P);A[a+40>>1]=x.readyState;A[a+42>>1]=x.status;x.statusText&&z(x.statusText,t,a+44,64);200<=x.status&&300>x.status?b&&b(a,x,B):c&&c(a,x,B)};x.onerror=B=>{f(I);var P=x.status;Z(a+24,0);Z(a+32,x.response?
x.response.byteLength:0);A[a+40>>1]=x.readyState;A[a+42>>1]=P;c&&c(a,x,B)};x.ontimeout=B=>{c&&c(a,x,B)};x.onprogress=B=>{var P=I&&F&&x.response?x.response.byteLength:0,G=0;I&&F&&(G=Fa(P),t.set(new Uint8Array(x.response),G));E[a+12>>2]=G;Z(a+16,P);Z(a+24,B.loaded-P);Z(a+32,B.total);A[a+40>>1]=x.readyState;3<=x.readyState&&0===x.status&&0<B.loaded&&(x.status=200);A[a+42>>1]=x.status;x.statusText&&z(x.statusText,t,a+44,64);d&&d(a,x,B);G&&W(G)};x.onreadystatechange=B=>{A[a+40>>1]=x.readyState;2<=x.readyState&&
(A[a+42>>1]=x.status);e&&e(a,x,B)};try{x.send(h)}catch(B){c&&c(a,x,B)}}else c(a,0,"no url specified!")}function Bd(a,b){if(!sa)if(b)a();else try{a()}catch(c){c instanceof Cd||"unwind"==c||fa(1,c)}}
function Dd(a,b,c,d){var e=zd;if(e){var f=E[a+112+64>>2];f||(f=E[a+8>>2]);var h=q(f);try{var k=e.transaction(["FILES"],"readwrite").objectStore("FILES").put(b,h);k.onsuccess=()=>{A[a+40>>1]=4;A[a+42>>1]=200;z("OK",t,a+44,64);c(a,0,h)};k.onerror=m=>{A[a+40>>1]=4;A[a+42>>1]=413;z("Payload Too Large",t,a+44,64);d(a,0,m)}}catch(m){d(a,0,m)}}else d(a,0,"IndexedDB not available!")}
function Ed(a,b,c){var d=zd;if(d){var e=E[a+112+64>>2];e||(e=E[a+8>>2]);e=q(e);try{var f=d.transaction(["FILES"],"readonly").objectStore("FILES").get(e);f.onsuccess=h=>{if(h.target.result){h=h.target.result;var k=h.byteLength||h.length,m=Fa(k);t.set(new Uint8Array(h),m);E[a+12>>2]=m;Z(a+16,k);Z(a+24,0);Z(a+32,k);A[a+40>>1]=4;A[a+42>>1]=200;z("OK",t,a+44,64);b(a,0,h)}else A[a+40>>1]=4,A[a+42>>1]=404,z("Not Found",t,a+44,64),c(a,0,"no data")};f.onerror=h=>{A[a+40>>1]=4;A[a+42>>1]=404;z("Not Found",
t,a+44,64);c(a,0,h)}}catch(h){c(a,0,h)}}else c(a,0,"IndexedDB not available!")}
function Fd(a,b,c){var d=zd;if(d){var e=E[a+112+64>>2];e||(e=E[a+8>>2]);e=q(e);try{var f=d.transaction(["FILES"],"readwrite").objectStore("FILES").delete(e);f.onsuccess=h=>{h=h.target.result;E[a+12>>2]=0;Z(a+16,0);Z(a+24,0);Z(a+32,0);A[a+40>>1]=4;A[a+42>>1]=200;z("OK",t,a+44,64);b(a,0,h)};f.onerror=h=>{A[a+40>>1]=4;A[a+42>>1]=404;z("Not Found",t,a+44,64);c(a,0,h)}}catch(h){c(a,0,h)}}else c(a,0,"IndexedDB not available!")}var Gd={};
function Hd(){if(!Id){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"==typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:ea||"./this.program"},b;for(b in Gd)void 0===Gd[b]?delete a[b]:a[b]=Gd[b];var c=[];for(b in a)c.push(b+"="+a[b]);Id=c}return Id}var Id;function Jd(a,b){Jd.ic||(Jd.ic=gb());for(var c=0;c<b;c++)D[a+c>>0]=Jd.ic();return 0}function Kd(a){return 0===a%4&&(0!==a%100||0===a%400)}
var Ld=[31,29,31,30,31,30,31,31,30,31,30,31],Md=[31,28,31,30,31,30,31,31,30,31,30,31];
function Nd(a,b,c,d){function e(l,u,w){for(l="number"==typeof l?l.toString():l||"";l.length<u;)l=w[0]+l;return l}function f(l,u){return e(l,u,"0")}function h(l,u){function w(I){return 0>I?-1:0<I?1:0}var y;0===(y=w(l.getFullYear()-u.getFullYear()))&&0===(y=w(l.getMonth()-u.getMonth()))&&(y=w(l.getDate()-u.getDate()));return y}function k(l){switch(l.getDay()){case 0:return new Date(l.getFullYear()-1,11,29);case 1:return l;case 2:return new Date(l.getFullYear(),0,3);case 3:return new Date(l.getFullYear(),
0,2);case 4:return new Date(l.getFullYear(),0,1);case 5:return new Date(l.getFullYear()-1,11,31);case 6:return new Date(l.getFullYear()-1,11,30)}}function m(l){var u=l.kb;for(l=new Date((new Date(l.lb+1900,0,1)).getTime());0<u;){var w=l.getMonth(),y=(Kd(l.getFullYear())?Ld:Md)[w];if(u>y-l.getDate())u-=y-l.getDate()+1,l.setDate(1),11>w?l.setMonth(w+1):(l.setMonth(0),l.setFullYear(l.getFullYear()+1));else{l.setDate(l.getDate()+u);break}}w=new Date(l.getFullYear()+1,0,4);u=k(new Date(l.getFullYear(),
0,4));w=k(w);return 0>=h(u,l)?0>=h(w,l)?l.getFullYear()+1:l.getFullYear():l.getFullYear()-1}var p=C[d+40>>2];d={$c:C[d>>2],Zc:C[d+4>>2],Hb:C[d+8>>2],Vb:C[d+12>>2],Ib:C[d+16>>2],lb:C[d+20>>2],eb:C[d+24>>2],kb:C[d+28>>2],jd:C[d+32>>2],Yc:C[d+36>>2],ad:p?q(p):""};c=q(c);p={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S","%x":"%m/%d/%y","%X":"%H:%M:%S","%Ec":"%c","%EC":"%C","%Ex":"%m/%d/%y","%EX":"%H:%M:%S","%Ey":"%y","%EY":"%Y","%Od":"%d",
"%Oe":"%e","%OH":"%H","%OI":"%I","%Om":"%m","%OM":"%M","%OS":"%S","%Ou":"%u","%OU":"%U","%OV":"%V","%Ow":"%w","%OW":"%W","%Oy":"%y"};for(var n in p)c=c.replace(new RegExp(n,"g"),p[n]);var r="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),v="January February March April May June July August September October November December".split(" ");p={"%a":function(l){return r[l.eb].substring(0,3)},"%A":function(l){return r[l.eb]},"%b":function(l){return v[l.Ib].substring(0,3)},"%B":function(l){return v[l.Ib]},
"%C":function(l){return f((l.lb+1900)/100|0,2)},"%d":function(l){return f(l.Vb,2)},"%e":function(l){return e(l.Vb,2," ")},"%g":function(l){return m(l).toString().substring(2)},"%G":function(l){return m(l)},"%H":function(l){return f(l.Hb,2)},"%I":function(l){l=l.Hb;0==l?l=12:12<l&&(l-=12);return f(l,2)},"%j":function(l){for(var u=0,w=0;w<=l.Ib-1;u+=(Kd(l.lb+1900)?Ld:Md)[w++]);return f(l.Vb+u,3)},"%m":function(l){return f(l.Ib+1,2)},"%M":function(l){return f(l.Zc,2)},"%n":function(){return"\n"},"%p":function(l){return 0<=
l.Hb&&12>l.Hb?"AM":"PM"},"%S":function(l){return f(l.$c,2)},"%t":function(){return"\t"},"%u":function(l){return l.eb||7},"%U":function(l){return f(Math.floor((l.kb+7-l.eb)/7),2)},"%V":function(l){var u=Math.floor((l.kb+7-(l.eb+6)%7)/7);2>=(l.eb+371-l.kb-2)%7&&u++;if(u)53==u&&(w=(l.eb+371-l.kb)%7,4==w||3==w&&Kd(l.lb)||(u=1));else{u=52;var w=(l.eb+7-l.kb-1)%7;(4==w||5==w&&Kd(l.lb%400-1))&&u++}return f(u,2)},"%w":function(l){return l.eb},"%W":function(l){return f(Math.floor((l.kb+7-(l.eb+6)%7)/7),2)},
"%y":function(l){return(l.lb+1900).toString().substring(2)},"%Y":function(l){return l.lb+1900},"%z":function(l){l=l.Yc;var u=0<=l;l=Math.abs(l)/60;return(u?"+":"-")+String("0000"+(l/60*100+l%60)).slice(-4)},"%Z":function(l){return l.ad},"%%":function(){return"%"}};c=c.replace(/%%/g,"\x00\x00");for(n in p)c.includes(n)&&(c=c.replace(new RegExp(n,"g"),p[n](d)));c=c.replace(/\0\0/g,"%");n=mb(c,!1);if(n.length>b)return 0;D.set(n,a);return n.length-1}
function Fb(a,b,c,d){a||(a=this);this.parent=a;this.fb=a.fb;this.sb=null;this.id=yb++;this.name=b;this.mode=c;this.Na={};this.Oa={};this.ub=d}Object.defineProperties(Fb.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}},Jc:{get:function(){return 16384===(this.mode&61440)}},Ic:{get:function(){return 8192===(this.mode&61440)}}});Yb();
zb=Array(4096);Mb(M,"/");O("/tmp",16895,0);O("/home",16895,0);O("/home/web_user",16895,0);(()=>{O("/dev",16895,0);kb(259,{read:()=>0,write:(b,c,d,e)=>e});Nb("/dev/null",259);jb(1280,nb);jb(1536,ob);Nb("/dev/tty",1280);Nb("/dev/tty1",1536);var a=gb();Q("/dev","random",a);Q("/dev","urandom",a);O("/dev/shm",16895,0);O("/dev/shm/tmp",16895,0)})();
(()=>{O("/proc",16895,0);var a=O("/proc/self",16895,0);O("/proc/self/fd",16895,0);Mb({fb:()=>{var b=qb(a,"fd",16895,73);b.Na={rb:(c,d)=>{var e=xb[+d];if(!e)throw new L(8);c={parent:null,fb:{fc:"fake"},Na:{vb:()=>e.path}};return c.parent=c}};return b}},"/proc/self/fd")})();var fc;g.FS_createPath=ac;g.FS_createDataFile=cc;g.FS_createPreloadedFile=gc;g.FS_createLazyFile=ec;g.FS_createDevice=Q;g.FS_unlink=Pb;vc=g.InternalError=uc("InternalError");for(var Od=Array(256),Pd=0;256>Pd;++Pd)Od[Pd]=String.fromCharCode(Pd);
Ac=Od;Bc=g.BindingError=uc("BindingError");Pc.prototype.isAliasOf=function(a){if(!(this instanceof Pc&&a instanceof Pc))return!1;var b=this.La.Sa.Pa,c=this.La.Qa,d=a.La.Sa.Pa;for(a=a.La.Qa;b.$a;)c=b.wb(c),b=b.$a;for(;d.$a;)a=d.wb(a),d=d.$a;return b===d&&c===a};
Pc.prototype.clone=function(){this.La.Qa||Cc(this);if(this.La.tb)return this.La.count.value+=1,this;var a=Oc,b=Object,c=b.create,d=Object.getPrototypeOf(this),e=this.La;a=a(c.call(b,d,{La:{value:{count:e.count,nb:e.nb,tb:e.tb,Qa:e.Qa,Sa:e.Sa,Xa:e.Xa,Za:e.Za}}}));a.La.count.value+=1;a.La.nb=!1;return a};Pc.prototype["delete"]=function(){this.La.Qa||Cc(this);this.La.nb&&!this.La.tb&&T("Object already scheduled for deletion");Ec(this);Fc(this.La);this.La.tb||(this.La.Xa=void 0,this.La.Qa=void 0)};
Pc.prototype.isDeleted=function(){return!this.La.Qa};Pc.prototype.deleteLater=function(){this.La.Qa||Cc(this);this.La.nb&&!this.La.tb&&T("Object already scheduled for deletion");Ic.push(this);1===Ic.length&&Kc&&Kc(Jc);this.La.nb=!0;return this};g.getInheritedInstanceCount=function(){return Object.keys(Lc).length};g.getLiveInheritedInstances=function(){var a=[],b;for(b in Lc)Lc.hasOwnProperty(b)&&a.push(Lc[b]);return a};g.flushPendingDeletes=Jc;g.setDelayFunction=function(a){Kc=a;Ic.length&&Kc&&Kc(Jc)};
Yc.prototype.Cc=function(a){this.jc&&(a=this.jc(a));return a};Yc.prototype.$b=function(a){this.gb&&this.gb(a)};Yc.prototype.argPackAdvance=8;Yc.prototype.readValueFromPointer=oc;Yc.prototype.deleteObject=function(a){if(null!==a)a["delete"]()};
Yc.prototype.fromWireType=function(a){function b(){return this.Cb?Nc(this.Pa.ob,{Sa:this.Oc,Qa:c,Za:this,Xa:a}):Nc(this.Pa.ob,{Sa:this,Qa:a})}var c=this.Cc(a);if(!c)return this.$b(a),null;var d=Mc(this.Pa,c);if(void 0!==d){if(0===d.La.count.value)return d.La.Qa=c,d.La.Xa=a,d.clone();d=d.clone();this.$b(a);return d}d=this.Pa.Bc(c);d=Hc[d];if(!d)return b.call(this);d=this.Bb?d.wc:d.pointerType;var e=Gc(c,this.Pa,d.Pa);return null===e?b.call(this):this.Cb?Nc(d.Pa.ob,{Sa:d,Qa:e,Za:this,Xa:a}):Nc(d.Pa.ob,
{Sa:d,Qa:e})};ad=g.UnboundTypeError=uc("UnboundTypeError");g.count_emval_handles=function(){for(var a=0,b=5;b<X.length;++b)void 0!==X[b]&&++a;return a};g.get_first_emval=function(){for(var a=5;a<X.length;++a)if(void 0!==X[a])return X[a];return null};
(function(a,b){try{var c=indexedDB.open("emscripten_filesystem",1)}catch(d){b(d);return}c.onupgradeneeded=d=>{d=d.target.result;d.objectStoreNames.contains("FILES")&&d.deleteObjectStore("FILES");d.createObjectStore("FILES")};c.onsuccess=d=>a(d.target.result);c.onerror=d=>b(d)})(a=>{zd=a;Ua("library_fetch_init")},()=>{zd=!1;Ua("library_fetch_init")});"undefined"!=typeof ENVIRONMENT_IS_FETCH_WORKER&&ENVIRONMENT_IS_FETCH_WORKER||Ta("library_fetch_init");
function mb(a,b){var c=Array(va(a)+1);a=z(a,c,0,c.length);b&&(c.length=a);return c}
var Ud={B:function(a,b,c){jc=c;try{var d=lc(a);switch(b){case 0:var e=kc();return 0>e?-28:Ub(d.path,d.flags,0,e).hb;case 1:case 2:return 0;case 3:return d.flags;case 4:return e=kc(),d.flags|=e,0;case 5:return e=kc(),ya[e+0>>1]=2,0;case 6:case 7:return 0;case 16:case 8:return-28;case 9:return-1;default:return-28}}catch(f){if("undefined"==typeof R||!(f instanceof L))throw f;return-f.Wa}},_:function(a,b){try{var c=lc(a);return ic(Qb,c.path,b)}catch(d){if("undefined"==typeof R||!(d instanceof L))throw d;
return-d.Wa}},$:function(a,b,c){jc=c;try{var d=lc(a);switch(b){case 21509:case 21505:return d.Ta?0:-59;case 21510:case 21511:case 21512:case 21506:case 21507:case 21508:return d.Ta?0:-59;case 21519:if(!d.Ta)return-59;var e=kc();return C[e>>2]=0;case 21520:return d.Ta?-28:-59;case 21531:a=e=kc();if(!d.Oa.Hc)throw new L(59);return d.Oa.Hc(d,b,a);case 21523:return d.Ta?0:-59;case 21524:return d.Ta?0:-59;default:qa("bad ioctl syscall "+b)}}catch(f){if("undefined"==typeof R||!(f instanceof L))throw f;
return-f.Wa}},Y:function(a,b,c,d){try{b=q(b);var e=d&256;b=hc(a,b,d&4096);return ic(e?Rb:Qb,b,c)}catch(f){if("undefined"==typeof R||!(f instanceof L))throw f;return-f.Wa}},C:function(a,b,c,d){jc=d;try{b=q(b);b=hc(a,b);var e=d?kc():0;return Ub(b,c,e).hb}catch(f){if("undefined"==typeof R||!(f instanceof L))throw f;return-f.Wa}},Z:function(a,b){try{return a=q(a),ic(Qb,a,b)}catch(c){if("undefined"==typeof R||!(c instanceof L))throw c;return-c.Wa}},b:function(a){var b=mc[a];delete mc[a];var c=b.Rb,d=b.gb,
e=b.bc,f=e.map(h=>h.Ec).concat(e.map(h=>h.Vc));xc([a],f,h=>{var k={};e.forEach((m,p)=>{var n=h[p],r=m.Ab,v=m.Dc,l=h[p+e.length],u=m.Uc,w=m.Wc;k[m.Ac]={read:y=>n.fromWireType(r(v,y)),write:(y,I)=>{var F=[];u(w,y,l.toWireType(F,I));nc(F)}}});return[{name:b.name,fromWireType:function(m){var p={},n;for(n in k)p[n]=k[n].read(m);d(m);return p},toWireType:function(m,p){for(var n in k)if(!(n in p))throw new TypeError('Missing field:  "'+n+'"');var r=c();for(n in k)k[n].write(r,p[n]);null!==m&&m.push(d,r);
return r},argPackAdvance:8,readValueFromPointer:oc,ab:d}]})},K:function(){},ha:function(a,b,c,d,e){var f=zc(c);b=S(b);yc(a,{name:b,fromWireType:function(h){return!!h},toWireType:function(h,k){return k?d:e},argPackAdvance:8,readValueFromPointer:function(h){if(1===c)var k=D;else if(2===c)k=ya;else if(4===c)k=C;else throw new TypeError("Unknown boolean type size: "+b);return this.fromWireType(k[h>>f])},ab:null})},q:function(a,b,c,d,e,f,h,k,m,p,n,r,v){n=S(n);f=V(e,f);k&&(k=V(h,k));p&&(p=V(m,p));v=V(r,
v);var l=sc(n);Rc(l,function(){dd("Cannot construct "+n+" due to unbound types",[d])});xc([a,b,c],d?[d]:[],function(u){u=u[0];if(d){var w=u.Pa;var y=w.ob}else y=Pc.prototype;u=tc(l,function(){if(Object.getPrototypeOf(this)!==I)throw new Bc("Use 'new' to construct "+n);if(void 0===F.ib)throw new Bc(n+" has no accessible constructor");var B=F.ib[arguments.length];if(void 0===B)throw new Bc("Tried to invoke ctor of "+n+" with invalid number of parameters ("+arguments.length+") - expected ("+Object.keys(F.ib).toString()+
") parameters instead!");return B.apply(this,arguments)});var I=Object.create(y,{constructor:{value:u}});u.prototype=I;var F=new Sc(n,u,I,v,w,f,k,p);w=new Yc(n,F,!0,!1);y=new Yc(n+"*",F,!1,!1);var x=new Yc(n+" const*",F,!1,!0);Hc[a]={pointerType:y,wc:x};Zc(l,u);return[w,y,x]})},r:function(a,b,c,d,e,f){0<b||qa(void 0);var h=ed(b,c);e=V(d,e);xc([],[a],function(k){k=k[0];var m="constructor "+k.name;void 0===k.Pa.ib&&(k.Pa.ib=[]);if(void 0!==k.Pa.ib[b-1])throw new Bc("Cannot register multiple constructors with identical number of parameters ("+
(b-1)+") for class '"+k.name+"'! Overload resolution is currently only performed using the parameter count, not actual type info!");k.Pa.ib[b-1]=()=>{dd("Cannot construct "+k.name+" due to unbound types",h)};xc([],h,function(p){p.splice(1,0,null);k.Pa.ib[b-1]=gd(m,p,null,e,f);return[]});return[]})},e:function(a,b,c,d,e,f,h,k){var m=ed(c,d);b=S(b);f=V(e,f);xc([],[a],function(p){function n(){dd("Cannot call "+r+" due to unbound types",m)}p=p[0];var r=p.name+"."+b;b.startsWith("@@")&&(b=Symbol[b.substring(2)]);
k&&p.Pa.Pc.push(b);var v=p.Pa.ob,l=v[b];void 0===l||void 0===l.Va&&l.className!==p.name&&l.xb===c-2?(n.xb=c-2,n.className=p.name,v[b]=n):(Qc(v,b,r),v[b].Va[c-2]=n);xc([],m,function(u){u=gd(r,u,p,f,h);void 0===v[b].Va?(u.xb=c-2,v[b]=u):v[b].Va[c-2]=u;return[]});return[]})},ga:function(a,b){b=S(b);yc(a,{name:b,fromWireType:function(c){var d=Y(c);jd(c);return d},toWireType:function(c,d){return U(d)},argPackAdvance:8,readValueFromPointer:oc,ab:null})},E:function(a,b,c){c=zc(c);b=S(b);yc(a,{name:b,fromWireType:function(d){return d},
toWireType:function(d,e){return e},argPackAdvance:8,readValueFromPointer:kd(b,c),ab:null})},x:function(a,b,c,d,e,f){var h=ed(b,c);a=S(a);e=V(d,e);Rc(a,function(){dd("Cannot call "+a+" due to unbound types",h)},b-1);xc([],h,function(k){Zc(a,gd(a,[k[0],null].concat(k.slice(1)),null,e,f),b-1);return[]})},j:function(a,b,c,d,e){b=S(b);-1===e&&(e=4294967295);e=zc(c);var f=k=>k;if(0===d){var h=32-8*c;f=k=>k<<h>>>h}c=b.includes("unsigned")?function(k,m){return m>>>0}:function(k,m){return m};yc(a,{name:b,
fromWireType:f,toWireType:c,argPackAdvance:8,readValueFromPointer:ld(b,e,0!==d),ab:null})},d:function(a,b,c){function d(f){f>>=2;var h=E;return new e(Ga,h[f+1],h[f])}var e=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array][b];c=S(c);yc(a,{name:c,fromWireType:d,argPackAdvance:8,readValueFromPointer:d},{Gc:!0})},F:function(a,b){b=S(b);var c="std::string"===b;yc(a,{name:b,fromWireType:function(d){var e=E[d>>2];if(c)for(var f=d+4,h=0;h<=e;++h){var k=d+4+h;if(h==
e||0==t[k]){f=q(f,k-f);if(void 0===m)var m=f;else m+=String.fromCharCode(0),m+=f;f=k+1}}else{m=Array(e);for(h=0;h<e;++h)m[h]=String.fromCharCode(t[d+4+h]);m=m.join("")}W(d);return m},toWireType:function(d,e){e instanceof ArrayBuffer&&(e=new Uint8Array(e));var f="string"==typeof e;f||e instanceof Uint8Array||e instanceof Uint8ClampedArray||e instanceof Int8Array||T("Cannot pass non-string to std::string");var h=(c&&f?()=>va(e):()=>e.length)(),k=Fa(4+h+1);E[k>>2]=h;if(c&&f)z(e,t,k+4,h+1);else if(f)for(f=
0;f<h;++f){var m=e.charCodeAt(f);255<m&&(W(k),T("String has UTF-16 code units that do not fit in 8 bits"));t[k+4+f]=m}else for(f=0;f<h;++f)t[k+4+f]=e[f];null!==d&&d.push(W,k);return k},argPackAdvance:8,readValueFromPointer:oc,ab:function(d){W(d)}})},u:function(a,b,c){c=S(c);if(2===b){var d=xa;var e=za;var f=Aa;var h=()=>A;var k=1}else 4===b&&(d=Ba,e=Ca,f=Da,h=()=>E,k=2);yc(a,{name:c,fromWireType:function(m){for(var p=E[m>>2],n=h(),r,v=m+4,l=0;l<=p;++l){var u=m+4+l*b;if(l==p||0==n[u>>k])v=d(v,u-v),
void 0===r?r=v:(r+=String.fromCharCode(0),r+=v),v=u+b}W(m);return r},toWireType:function(m,p){"string"!=typeof p&&T("Cannot pass non-string to C++ string type "+c);var n=f(p),r=Fa(4+n+b);E[r>>2]=n>>k;e(p,r+4,n+b);null!==m&&m.push(W,r);return r},argPackAdvance:8,readValueFromPointer:oc,ab:function(m){W(m)}})},c:function(a,b,c,d,e,f){mc[a]={name:S(b),Rb:V(c,d),gb:V(e,f),bc:[]}},a:function(a,b,c,d,e,f,h,k,m,p){mc[a].bc.push({Ac:S(b),Ec:c,Ab:V(d,e),Dc:f,Vc:h,Uc:V(k,m),Wc:p})},ia:function(a,b){b=S(b);
yc(a,{Kc:!0,name:b,argPackAdvance:0,fromWireType:function(){},toWireType:function(){}})},D:function(){return Date.now()},ja:function(a){delete yd[a-1]},ca:function(){return!0},P:function(){throw Infinity;},k:function(a,b,c){a=Y(a);b=md(b,"emval::as");var d=[],e=U(d);C[c>>2]=e;return b.toWireType(d,a)},oa:function(a,b,c,d){a=Y(a);c=nd(b,c);for(var e=Array(b),f=0;f<b;++f){var h=c[f];e[f]=h.readValueFromPointer(d);d+=h.argPackAdvance}a=a.apply(void 0,e);return U(a)},p:function(a,b,c,d){a=qd[a];b=Y(b);
c=pd(c);a(b,c,null,d)},z:jd,pa:function(a,b){a=Y(a);b=Y(b);return a==b},ma:function(a){if(0===a)return U(rd());a=pd(a);return U(rd()[a])},o:function(a,b){var c=nd(a,b),d=c[0];b=d.name+"_$"+c.slice(1).map(function(n){return n.name}).join("_")+"$";var e=td[b];if(void 0!==e)return e;e=["retType"];for(var f=[d],h="",k=0;k<a-1;++k)h+=(0!==k?", ":"")+"arg"+k,e.push("argType"+k),f.push(c[1+k]);var m="return function "+sc("methodCaller_"+b)+"(handle, name, destructors, args) {\n",p=0;for(k=0;k<a-1;++k)m+=
"    var arg"+k+" = argType"+k+".readValueFromPointer(args"+(p?"+"+p:"")+");\n",p+=c[k+1].argPackAdvance;m+="    var rv = handle[name]("+h+");\n";for(k=0;k<a-1;++k)c[k+1].deleteObject&&(m+="    argType"+k+".deleteObject(arg"+k+");\n");d.Kc||(m+="    return retType.toWireType(destructors, rv);\n");e.push(m+"};\n");a=fd(e).apply(null,f);e=sd(a);return td[b]=e},n:function(a,b){a=Y(a);b=Y(b);return U(a[b])},H:function(a){4<a&&(X[a].Tb+=1)},na:function(a,b){a=Y(a);b=Y(b);return a instanceof b},w:function(a,
b,c,d){a=Y(a);var e=ud[b];if(!e){e="";for(var f=0;f<b;++f)e+=(0!==f?", ":"")+"arg"+f;var h="return function emval_allocator_"+b+"(constructor, argTypes, args) {\n";for(f=0;f<b;++f)h+="var argType"+f+" = requireRegisteredType(Module['HEAP32'][(argTypes >>> 2) + "+f+'], "parameter '+f+'");\nvar arg'+f+" = argType"+f+".readValueFromPointer(args);\nargs += argType"+f+"['argPackAdvance'];\n";e=(new Function("requireRegisteredType","Module","valueToHandle",h+("var obj = new constructor("+e+");\nreturn valueToHandle(obj);\n}\n")))(md,
g,U);ud[b]=e}return e(a,c,d)},N:function(){return U([])},sa:function(a){return U(pd(a))},I:function(){return U({})},ra:function(a){var b=Y(a);nc(b);jd(a)},f:function(a,b,c){a=Y(a);b=Y(b);c=Y(c);a[b]=c},i:function(a,b){a=md(a,"_emval_take_value");a=a.readValueFromPointer(b);return U(a)},qa:function(a){a=Y(a);return U(typeof a)},da:function(a,b){a=new Date(1E3*C[a>>2]);C[b>>2]=a.getSeconds();C[b+4>>2]=a.getMinutes();C[b+8>>2]=a.getHours();C[b+12>>2]=a.getDate();C[b+16>>2]=a.getMonth();C[b+20>>2]=a.getFullYear()-
1900;C[b+24>>2]=a.getDay();var c=new Date(a.getFullYear(),0,1);C[b+28>>2]=(a.getTime()-c.getTime())/864E5|0;C[b+36>>2]=-(60*a.getTimezoneOffset());var d=(new Date(a.getFullYear(),6,1)).getTimezoneOffset();c=c.getTimezoneOffset();C[b+32>>2]=(d!=c&&a.getTimezoneOffset()==Math.min(c,d))|0},ea:function(a){var b=new Date(C[a+20>>2]+1900,C[a+16>>2],C[a+12>>2],C[a+8>>2],C[a+4>>2],C[a>>2],0),c=C[a+32>>2],d=b.getTimezoneOffset(),e=new Date(b.getFullYear(),0,1),f=(new Date(b.getFullYear(),6,1)).getTimezoneOffset(),
h=e.getTimezoneOffset(),k=Math.min(h,f);0>c?C[a+32>>2]=Number(f!=h&&k==d):0<c!=(k==d)&&(f=Math.max(h,f),b.setTime(b.getTime()+6E4*((0<c?k:f)-d)));C[a+24>>2]=b.getDay();C[a+28>>2]=(b.getTime()-e.getTime())/864E5|0;C[a>>2]=b.getSeconds();C[a+4>>2]=b.getMinutes();C[a+8>>2]=b.getHours();C[a+12>>2]=b.getDate();C[a+16>>2]=b.getMonth();return b.getTime()/1E3|0},U:function(a,b,c,d,e,f,h){try{var k=xb[e];if(!k)return-8;if(0!==(c&2)&&0===(d&2)&&2!==(k.flags&2097155))throw new L(2);if(1===(k.flags&2097155))throw new L(2);
if(!k.Oa.Eb)throw new L(43);var m=k.Oa.Eb(k,a,b,f,c,d);var p=m.Qa;C[h>>2]=m.qc;return p}catch(n){if("undefined"==typeof R||!(n instanceof L))throw n;return-n.Wa}},V:function(a,b,c,d,e,f){try{var h=xb[e];h&&c&2&&h&&h.Oa.Fb&&h.Oa.Fb(h,t.slice(a,a+b),f,b,d)}catch(k){if("undefined"==typeof R||!(k instanceof L))throw k;return-k.Wa}},fa:wd,l:function(){qa("")},m:function(a,b,c){xd.length=0;var d;for(c>>=2;d=t[b++];)(d=105>d)&&c&1&&c++,xd.push(d?Ia[c++>>1]:C[c]),++c;return ab[a].apply(null,xd)},T:function(){return 2147483648},
ba:()=>performance.now(),la:function(){return!ia},aa:function(a,b,c){t.copyWithin(a,b,b+c)},S:function(a){var b=t.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);var e=Math;d=Math.max(a,d);e=e.min.call(e,2147483648,d+(65536-d%65536)%65536);a:{try{ra.grow(e-Ga.byteLength+65535>>>16);Ja();var f=1;break a}catch(h){}f=void 0}if(f)return!0}return!1},ka:function(a,b,c,d,e){var f=a+112,h=q(f),k=E[f+36>>2],m=E[f+40>>2],p=E[f+44>>2],n=E[f+48>>2],r=E[f+
52>>2],v=!!(r&4),l=!!(r&32),u=!!(r&16),w=!!(r&64),y=G=>{Bd(()=>{k?J(k)(G):b&&b(G)},w)},I=G=>{Bd(()=>{p?J(p)(G):d&&d(G)},w)},F=G=>{Bd(()=>{m?J(m)(G):c&&c(G)},w)},x=G=>{Bd(()=>{n?J(n)(G):e&&e(G)},w)};r=G=>{Ad(G,y,F,I,x)};var B=(G,Vd)=>{Dd(G,Vd.response,Na=>{Bd(()=>{k?J(k)(Na):b&&b(Na)},w)},Na=>{Bd(()=>{k?J(k)(Na):b&&b(Na)},w)})},P=G=>{Ad(G,B,F,I,x)};if("EM_IDB_STORE"===h)h=E[f+84>>2],Dd(a,t.slice(h,h+E[f+88>>2]),y,F);else if("EM_IDB_DELETE"===h)Fd(a,y,F);else if(u){if(l)return 0;Ad(a,v?B:y,F,I,x)}else Ed(a,
y,l?F:v?P:r);return a},W:function(a,b){var c=0;Hd().forEach(function(d,e){var f=b+c;e=C[a+4*e>>2]=f;for(f=0;f<d.length;++f)D[e++>>0]=d.charCodeAt(f);D[e>>0]=0;c+=d.length+1});return 0},X:function(a,b){var c=Hd();C[a>>2]=c.length;var d=0;c.forEach(function(e){d+=e.length+1});C[b>>2]=d;return 0},v:function(a){if(!noExitRuntime){if(g.onExit)g.onExit(a);sa=!0}fa(a,new Cd(a))},t:function(a){try{var b=lc(a);Vb(b);return 0}catch(c){if("undefined"==typeof R||!(c instanceof L))throw c;return c.Wa}},A:function(a,
b,c,d){try{a:{for(var e=lc(a),f=a=0;f<c;f++){var h=C[b+(8*f+4)>>2],k=e,m=C[b+8*f>>2],p=h,n=void 0,r=D;if(0>p||0>n)throw new L(28);if(null===k.hb)throw new L(8);if(1===(k.flags&2097155))throw new L(8);if(16384===(k.node.mode&61440))throw new L(31);if(!k.Oa.read)throw new L(28);var v="undefined"!=typeof n;if(!v)n=k.position;else if(!k.seekable)throw new L(70);var l=k.Oa.read(k,r,m,p,n);v||(k.position+=l);var u=l;if(0>u){var w=-1;break a}a+=u;if(u<h)break}w=a}C[d>>2]=w;return 0}catch(y){if("undefined"==
typeof R||!(y instanceof L))throw y;return y.Wa}},J:function(a,b,c,d,e){try{var f=lc(a);a=4294967296*c+(b>>>0);if(-9007199254740992>=a||9007199254740992<=a)return-61;Wb(f,a,d);$a=[f.position>>>0,(H=f.position,1<=+Math.abs(H)?0<H?(Math.min(+Math.floor(H/4294967296),4294967295)|0)>>>0:~~+Math.ceil((H-+(~~H>>>0))/4294967296)>>>0:0)];C[e>>2]=$a[0];C[e+4>>2]=$a[1];f.Mb&&0===a&&0===d&&(f.Mb=null);return 0}catch(h){if("undefined"==typeof R||!(h instanceof L))throw h;return h.Wa}},s:function(a,b,c,d){try{a:{for(var e=
lc(a),f=a=0;f<c;f++){var h=Xb(e,D,C[b+8*f>>2],C[b+(8*f+4)>>2],void 0);if(0>h){var k=-1;break a}a+=h}k=a}C[d>>2]=k;return 0}catch(m){if("undefined"==typeof R||!(m instanceof L))throw m;return m.Wa}},h:function(){return oa},ta:function(){var a=self.navigator.userAgent,b=va(a)+1,c=Fa(b);z(a,t,c,b);return c},Q:Jd,L:Qd,y:Rd,M:Sd,O:Td,g:function(a){oa=a},G:Nd,R:function(a,b,c,d){return Nd(a,b,c,d)}};
(function(){function a(e){g.asm=e.exports;ra=g.asm.ua;Ja();Ka=g.asm.Aa;Ma.unshift(g.asm.va);Ua("wasm-instantiate")}function b(e){a(e.instance)}function c(e){return Za().then(function(f){return WebAssembly.instantiate(f,d)}).then(function(f){return f}).then(e,function(f){ca("failed to asynchronously prepare wasm: "+f);qa(f)})}var d={a:Ud};Ta("wasm-instantiate");if(g.instantiateWasm)try{return g.instantiateWasm(d,a)}catch(e){return ca("Module.instantiateWasm callback failed with error: "+e),!1}(function(){return pa||
"function"!=typeof WebAssembly.instantiateStreaming||Va()||"function"!=typeof fetch?c(b):fetch(Wa,{credentials:"same-origin"}).then(function(e){return WebAssembly.instantiateStreaming(e,d).then(b,function(f){ca("wasm streaming compile failed: "+f);ca("falling back to ArrayBuffer instantiation");return c(b)})})})().catch(ba);return{}})();g.___wasm_call_ctors=function(){return(g.___wasm_call_ctors=g.asm.va).apply(null,arguments)};
var W=g._free=function(){return(W=g._free=g.asm.wa).apply(null,arguments)},Fa=g._malloc=function(){return(Fa=g._malloc=g.asm.xa).apply(null,arguments)},cd=g.___getTypeName=function(){return(cd=g.___getTypeName=g.asm.ya).apply(null,arguments)};g.___embind_register_native_and_builtin_types=function(){return(g.___embind_register_native_and_builtin_types=g.asm.za).apply(null,arguments)};
var tb=g._emscripten_builtin_memalign=function(){return(tb=g._emscripten_builtin_memalign=g.asm.Ba).apply(null,arguments)},Wd=g._setThrew=function(){return(Wd=g._setThrew=g.asm.Ca).apply(null,arguments)},Xd=g.stackSave=function(){return(Xd=g.stackSave=g.asm.Da).apply(null,arguments)},Yd=g.stackRestore=function(){return(Yd=g.stackRestore=g.asm.Ea).apply(null,arguments)};g.dynCall_ji=function(){return(g.dynCall_ji=g.asm.Fa).apply(null,arguments)};
g.dynCall_jiji=function(){return(g.dynCall_jiji=g.asm.Ga).apply(null,arguments)};g.dynCall_viijii=function(){return(g.dynCall_viijii=g.asm.Ha).apply(null,arguments)};g.dynCall_iiiiij=function(){return(g.dynCall_iiiiij=g.asm.Ia).apply(null,arguments)};g.dynCall_iiiiijj=function(){return(g.dynCall_iiiiijj=g.asm.Ja).apply(null,arguments)};g.dynCall_iiiiiijj=function(){return(g.dynCall_iiiiiijj=g.asm.Ka).apply(null,arguments)};
function Rd(a,b){var c=Xd();try{J(a)(b)}catch(d){Yd(c);if(d!==d+0)throw d;Wd(1,0)}}function Td(a,b,c,d){var e=Xd();try{J(a)(b,c,d)}catch(f){Yd(e);if(f!==f+0)throw f;Wd(1,0)}}function Sd(a,b,c){var d=Xd();try{J(a)(b,c)}catch(e){Yd(d);if(e!==e+0)throw e;Wd(1,0)}}function Qd(a,b,c,d){var e=Xd();try{return J(a)(b,c,d)}catch(f){Yd(e);if(f!==f+0)throw f;Wd(1,0)}}g.addRunDependency=Ta;g.removeRunDependency=Ua;g.FS_createPath=ac;g.FS_createDataFile=cc;g.FS_createPreloadedFile=gc;g.FS_createLazyFile=ec;
g.FS_createDevice=Q;g.FS_unlink=Pb;var Zd;function Cd(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}Sa=function $d(){Zd||ae();Zd||(Sa=$d)};
function ae(){function a(){if(!Zd&&(Zd=!0,g.calledRun=!0,!sa)){g.noFSInit||Zb||(Zb=!0,Yb(),g.stdin=g.stdin,g.stdout=g.stdout,g.stderr=g.stderr,g.stdin?Q("/dev","stdin",g.stdin):Ob("/dev/tty","/dev/stdin"),g.stdout?Q("/dev","stdout",null,g.stdout):Ob("/dev/tty","/dev/stdout"),g.stderr?Q("/dev","stderr",null,g.stderr):Ob("/dev/tty1","/dev/stderr"),Ub("/dev/stdin",0),Ub("/dev/stdout",1),Ub("/dev/stderr",1));Ab=!1;bb(Ma);aa(g);if(g.onRuntimeInitialized)g.onRuntimeInitialized();if(g.postRun)for("function"==
typeof g.postRun&&(g.postRun=[g.postRun]);g.postRun.length;){var b=g.postRun.shift();Oa.unshift(b)}bb(Oa)}}if(!(0<Qa)){if(g.preRun)for("function"==typeof g.preRun&&(g.preRun=[g.preRun]);g.preRun.length;)Pa();bb(La);0<Qa||(g.setStatus?(g.setStatus("Running..."),setTimeout(function(){setTimeout(function(){g.setStatus("")},1);a()},1)):a())}}g.run=ae;if(g.preInit)for("function"==typeof g.preInit&&(g.preInit=[g.preInit]);0<g.preInit.length;)g.preInit.pop()();ae();


  return BlinkIDWasmSDK.ready
}
);
})();
if (typeof exports === 'object' && typeof module === 'object')
  module.exports = BlinkIDWasmSDK;
else if (typeof define === 'function' && define['amd'])
  define([], function() { return BlinkIDWasmSDK; });
else if (typeof exports === 'object')
  exports["BlinkIDWasmSDK"] = BlinkIDWasmSDK;
