
var BlinkIDWasmSDK = (() => {
  var _scriptDir = typeof document !== 'undefined' && document.currentScript ? document.currentScript.src : undefined;
  
  return (
function(config) {
  var BlinkIDWasmSDK = config || {};


var g;g||(g=typeof BlinkIDWasmSDK !== 'undefined' ? BlinkIDWasmSDK : {});var aa,ba;g.ready=new Promise(function(a,b){aa=a;ba=b});g.Mb||(g.Mb=0);g.Mb++;
g.ENVIRONMENT_IS_PTHREAD||function(a){function b(m,n,t){var p=new XMLHttpRequest;p.open("GET",m,!0);p.responseType="arraybuffer";p.onprogress=function(q){var k=n;q.total&&(k=q.total);if(q.loaded){p.rc?g.mb[m].loaded=q.loaded:(p.rc=!0,g.mb||(g.mb={}),g.mb[m]={loaded:q.loaded,total:k});var u=k=q=0,x;for(x in g.mb){var z=g.mb[x];q+=z.total;k+=z.loaded;u++}q=Math.ceil(q*g.Mb/u);g.setStatus&&g.setStatus("Downloading data... ("+k+"/"+q+")")}else!g.mb&&g.setStatus&&g.setStatus("Downloading data...")};p.onerror=
function(){throw Error("NetworkError for: "+m);};p.onload=function(){if(200==p.status||304==p.status||206==p.status||0==p.status&&p.response)t(p.response);else throw Error(p.statusText+" : "+p.responseURL);};p.send(null)}function c(m){console.error("package error:",m)}function d(){function m(q,k,u){this.start=q;this.end=k;this.audio=u}function n(q){if(!q)throw"Loading data file failed."+Error().stack;if(q.constructor.name!==ArrayBuffer.name)throw"bad input to processPackageData"+Error().stack;q=new Uint8Array(q);
m.prototype.vc=q;q=a.files;for(var k=0;k<q.length;++k)m.prototype.Vb[q[k].filename].onload();g.removeRunDependency("datafile_/opt/jenkins/jenkinsData/E4/core-webassembly-sdks/SDKs/BlinkID/resources/basic/BlinkIDWasmSDK.data")}g.FS_createPath("/","microblink",!0,!0);m.prototype={Vb:{},open:function(q,k){this.name=k;this.Vb[k]=this;g.addRunDependency("fp "+this.name)},send:function(){},onload:function(){this.finish(this.vc.subarray(this.start,this.end))},finish:function(q){g.FS_createDataFile(this.name,
null,q,!0,!0,!0);g.removeRunDependency("fp "+this.name);this.Vb[this.name]=null}};for(var t=a.files,p=0;p<t.length;++p)(new m(t[p].start,t[p].end,t[p].audio||0)).open("GET",t[p].filename);g.addRunDependency("datafile_/opt/jenkins/jenkinsData/E4/core-webassembly-sdks/SDKs/BlinkID/resources/basic/BlinkIDWasmSDK.data");g.jc||(g.jc={});g.jc["/opt/jenkins/jenkinsData/E4/core-webassembly-sdks/SDKs/BlinkID/resources/basic/BlinkIDWasmSDK.data"]={ld:!1};l?(n(l),l=null):h=n}"object"===typeof window?window.encodeURIComponent(window.location.pathname.toString().substring(0,
window.location.pathname.toString().lastIndexOf("/"))+"/"):"undefined"===typeof process&&"undefined"!==typeof location&&encodeURIComponent(location.pathname.toString().substring(0,location.pathname.toString().lastIndexOf("/"))+"/");"function"!==typeof g.locateFilePackage||g.locateFile||(g.locateFile=g.locateFilePackage,r("warning: you defined Module.locateFilePackage, that has been renamed to Module.locateFile (using your locateFilePackage for now)"));var e=g.locateFile?g.locateFile("BlinkIDWasmSDK.data",
""):"BlinkIDWasmSDK.data",f=a.remote_package_size,h=null,l=g.getPreloadedPackage?g.getPreloadedPackage(e,f):null;l||b(e,f,function(m){h?(h(m),h=null):l=m},c);g.calledRun?d():(g.preRun||(g.preRun=[]),g.preRun.push(d))}({files:[{filename:"/microblink/Model_19d332fd742e2cc1f4d925a61caceb93ee3b225b3bad0c3966df7d1e3c9f6e0b.strop",start:0,end:430042},{filename:"/microblink/Model_2880751121560047e6dc571bc8ff4683aeb863886f7c0789234594ceb1e23577.strop",start:430042,end:433980},{filename:"/microblink/Model_36d8e94f4cb46097bd6b7385f2aa91fcdee1a5fefeec59e56d1b9e82c94b00a7.strop",
start:433980,end:803808},{filename:"/microblink/Model_473ac5f5e256623c0a6b282698c1f1b033b9fb5359e6aa142e9fb4a4022afe4e.strop",start:803808,end:810690},{filename:"/microblink/Model_500f4403bf221021bb85c3e758d59f69841635787f6f4201a4ffe5e68733f8bb.strop",start:810690,end:1393828},{filename:"/microblink/Model_5b6ea9ea320cf60db51d28292a50330f5915638e7bdcc0c7c2dc6d6c3e3d9655.strop",start:1393828,end:2135910},{filename:"/microblink/Model_82ae7b860c6b4cb8249534e0004901bc46dee18fd3adbe535809abeefbf4fd88.strop",
start:2135910,end:6854226},{filename:"/microblink/Model_8326c5065a6d8451d6d004db73babf4a4a9f502c68643a14934cc098d04bf44f.strop",start:6854226,end:7271330},{filename:"/microblink/Model_b452fd3cd4037080cfcb4c423dba5bc58c8ceafc28427fdf9c5778fb353f088e.strop",start:7271330,end:7278180},{filename:"/microblink/Model_e4f1f62f68ec44b71ecad3fb3f3b48fe3790beb5ab325611e17d63af06e9f644.strop",start:7278180,end:7334694},{filename:"/microblink/Model_ed586fd6ca47c8eebb513c4ffaaacc2c54e92162b145062d7022519fba0911de.strop",
start:7334694,end:8047926},{filename:"/microblink/Model_f7f2ce138860672abe85ef788b82633f674cde6b121a6017be15f41f2451017a.strop",start:8047926,end:10494450},{filename:"/microblink/Model_faf688599c7e261a2a7404730f69ed029115bb0d3e7a3657731d88e701720efe.strop",start:10494450,end:10511188},{filename:"/microblink/ccc_lookup_table.zzip",start:10511188,end:10531657},{filename:"/microblink/face_detector_model.zzip",start:10531657,end:10628515}],remote_package_size:10628515});
g.onAbort=function(a){r("Aborted with message: "+a);try{throw new WebAssembly.RuntimeError(a);}catch(b){r("Stacktrace: "+b.stack)}};var crypto={getRandomValues:function(a){for(var b=0;b<a.length;b++)a[b]=256*Math.random()|0}},ca=Object.assign({},g),da="./this.program",ea=(a,b)=>{throw b;},fa="object"==typeof window,ha="function"==typeof importScripts,ia="",ja,ka,la;
if(fa||ha)ha?ia=self.location.href:"undefined"!=typeof document&&document.currentScript&&(ia=document.currentScript.src),_scriptDir&&(ia=_scriptDir),ia=0!==ia.indexOf("blob:")?ia.substr(0,ia.replace(/[?#].*/,"").lastIndexOf("/")+1):"",ja=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},ha&&(la=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),ka=(a,b,c)=>{var d=new XMLHttpRequest;d.open("GET",
a,!0);d.responseType="arraybuffer";d.onload=()=>{200==d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)};var ma=g.print||console.log.bind(console),r=g.printErr||console.warn.bind(console);Object.assign(g,ca);ca=null;g.thisProgram&&(da=g.thisProgram);g.quit&&(ea=g.quit);var na;g.wasmBinary&&(na=g.wasmBinary);var noExitRuntime=g.noExitRuntime||!0;"object"!=typeof WebAssembly&&oa("no native wasm support detected");
var pa,qa=!1,ra="undefined"!=typeof TextDecoder?new TextDecoder("utf8"):void 0;
function sa(a,b,c){var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.buffer&&ra)return ra.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var f=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|f);else{var h=a[b++]&63;e=224==(e&240)?(e&15)<<12|f<<6|h:(e&7)<<18|f<<12|h<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d}function v(a,b){return a?sa(w,a,b):""}
function A(a,b,c,d){if(!(0<d))return 0;var e=c;d=c+d-1;for(var f=0;f<a.length;++f){var h=a.charCodeAt(f);if(55296<=h&&57343>=h){var l=a.charCodeAt(++f);h=65536+((h&1023)<<10)|l&1023}if(127>=h){if(c>=d)break;b[c++]=h}else{if(2047>=h){if(c+1>=d)break;b[c++]=192|h>>6}else{if(65535>=h){if(c+2>=d)break;b[c++]=224|h>>12}else{if(c+3>=d)break;b[c++]=240|h>>18;b[c++]=128|h>>12&63}b[c++]=128|h>>6&63}b[c++]=128|h&63}}b[c]=0;return c-e}
function ta(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b}var C,w,ua,D,E,G,va,wa;function xa(){var a=pa.buffer;g.HEAP8=C=new Int8Array(a);g.HEAP16=ua=new Int16Array(a);g.HEAP32=E=new Int32Array(a);g.HEAPU8=w=new Uint8Array(a);g.HEAPU16=D=new Uint16Array(a);g.HEAPU32=G=new Uint32Array(a);g.HEAPF32=va=new Float32Array(a);g.HEAPF64=wa=new Float64Array(a)}var ya,za=[],Aa=[],Ba=[];
function Ca(){var a=g.preRun.shift();za.unshift(a)}var Da=0,Ea=null,Fa=null;function Ga(){Da++;g.monitorRunDependencies&&g.monitorRunDependencies(Da)}function Ha(){Da--;g.monitorRunDependencies&&g.monitorRunDependencies(Da);if(0==Da&&(null!==Ea&&(clearInterval(Ea),Ea=null),Fa)){var a=Fa;Fa=null;a()}}function oa(a){if(g.onAbort)g.onAbort(a);a="Aborted("+a+")";r(a);qa=!0;a=new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");ba(a);throw a;}
function Ia(){return Ja.startsWith("data:application/octet-stream;base64,")}var Ja;Ja="BlinkIDWasmSDK.wasm";if(!Ia()){var Ka=Ja;Ja=g.locateFile?g.locateFile(Ka,ia):ia+Ka}function La(){var a=Ja;try{if(a==Ja&&na)return new Uint8Array(na);if(la)return la(a);throw"both async and sync fetching of the wasm failed";}catch(b){oa(b)}}
function Ma(){return na||!fa&&!ha||"function"!=typeof fetch?Promise.resolve().then(function(){return La()}):fetch(Ja,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+Ja+"'";return a.arrayBuffer()}).catch(function(){return La()})}
var J,K,Na={456492:a=>{a=v(a);throw Error("Failed to reconfigure RecognizerRunner due to following error: "+a);},456628:(a,b,c,d)=>{a=v(a);b=v(b);c=v(c);d=v(d);throw Error(a+b+c+d);},456844:(a,b)=>{a=v(a);b=v(b);throw Error(a+b);},456954:(a,b)=>{a=v(a);b=v(b);console.log(a+b)},457052:a=>{throw Error(v(a));},457095:()=>{throw Error("Unable to perform that operation while recognizer is in use!");},457178:()=>{throw Error("Unable to perform that operation while recognizer is in use!");},457261:()=>{throw Error("Unable to perform that operation while recognizer is in use!");
}};function Oa(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}function Pa(a){for(;0<a.length;)a.shift()(g)}function Sa(a){this.Pa=a-24;this.ad=function(b){G[this.Pa+4>>2]=b};this.Yc=function(b){G[this.Pa+8>>2]=b};this.Zc=function(){E[this.Pa>>2]=0};this.Xc=function(){C[this.Pa+12>>0]=0};this.$c=function(){C[this.Pa+13>>0]=0};this.Ic=function(b,c){this.Wc();this.ad(b);this.Yc(c);this.Zc();this.Xc();this.$c()};this.Wc=function(){G[this.Pa+16>>2]=0}}
var Ta=0,Ua=(a,b)=>{for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a},L=a=>{var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=Ua(a.split("/").filter(d=>!!d),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a},Va=a=>{var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,b.length-1));return a+b},Wa=
a=>{if("/"===a)return"/";a=L(a);a=a.replace(/\/$/,"");var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)};function Xa(){if("object"==typeof crypto&&"function"==typeof crypto.getRandomValues){var a=new Uint8Array(1);return()=>{crypto.getRandomValues(a);return a[0]}}return()=>oa("randomDevice")}
function Ya(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:"/";if("string"!=typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=Ua(a.split("/").filter(d=>!!d),!b).join("/");return(b?"/":"")+a||"."}function Za(a,b){var c=Array(ta(a)+1);a=A(a,c,0,c.length);b&&(c.length=a);return c}var $a=[];function ab(a,b){$a[a]={input:[],Ua:[],qb:b};bb(a,cb)}
var cb={open:function(a){var b=$a[a.node.vb];if(!b)throw new M(43);a.Ta=b;a.seekable=!1},close:function(a){a.Ta.qb.Bb(a.Ta)},Bb:function(a){a.Ta.qb.Bb(a.Ta)},read:function(a,b,c,d){if(!a.Ta||!a.Ta.qb.fc)throw new M(60);for(var e=0,f=0;f<d;f++){try{var h=a.Ta.qb.fc(a.Ta)}catch(l){throw new M(29);}if(void 0===h&&0===e)throw new M(6);if(null===h||void 0===h)break;e++;b[c+f]=h}e&&(a.node.timestamp=Date.now());return e},write:function(a,b,c,d){if(!a.Ta||!a.Ta.qb.Rb)throw new M(60);try{for(var e=0;e<d;e++)a.Ta.qb.Rb(a.Ta,
b[c+e])}catch(f){throw new M(29);}d&&(a.node.timestamp=Date.now());return e}},db={fc:function(a){if(!a.input.length){var b=null;"undefined"!=typeof window&&"function"==typeof window.prompt?(b=window.prompt("Input: "),null!==b&&(b+="\n")):"function"==typeof readline&&(b=readline(),null!==b&&(b+="\n"));if(!b)return null;a.input=Za(b,!0)}return a.input.shift()},Rb:function(a,b){null===b||10===b?(ma(sa(a.Ua,0)),a.Ua=[]):0!=b&&a.Ua.push(b)},Bb:function(a){a.Ua&&0<a.Ua.length&&(ma(sa(a.Ua,0)),a.Ua=[])}},
eb={Rb:function(a,b){null===b||10===b?(r(sa(a.Ua,0)),a.Ua=[]):0!=b&&a.Ua.push(b)},Bb:function(a){a.Ua&&0<a.Ua.length&&(r(sa(a.Ua,0)),a.Ua=[])}};function fb(a){a=65536*Math.ceil(a/65536);var b=gb(65536,a);b?(w.fill(0,b,b+a),a=b):a=0;return a}
var N={cb:null,fb:function(){return N.createNode(null,"/",16895,0)},createNode:function(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new M(63);N.cb||(N.cb={dir:{node:{bb:N.Na.bb,Ya:N.Na.Ya,rb:N.Na.rb,Fb:N.Na.Fb,nc:N.Na.nc,Lb:N.Na.Lb,oc:N.Na.oc,mc:N.Na.mc,Ib:N.Na.Ib},stream:{jb:N.Oa.jb}},file:{node:{bb:N.Na.bb,Ya:N.Na.Ya},stream:{jb:N.Oa.jb,read:N.Oa.read,write:N.Oa.write,Xb:N.Oa.Xb,sb:N.Oa.sb,Gb:N.Oa.Gb}},link:{node:{bb:N.Na.bb,Ya:N.Na.Ya,wb:N.Na.wb},stream:{}},$b:{node:{bb:N.Na.bb,Ya:N.Na.Ya},
stream:hb}});c=ib(a,b,c,d);16384===(c.mode&61440)?(c.Na=N.cb.dir.node,c.Oa=N.cb.dir.stream,c.Ma={}):32768===(c.mode&61440)?(c.Na=N.cb.file.node,c.Oa=N.cb.file.stream,c.Ra=0,c.Ma=null):40960===(c.mode&61440)?(c.Na=N.cb.link.node,c.Oa=N.cb.link.stream):8192===(c.mode&61440)&&(c.Na=N.cb.$b.node,c.Oa=N.cb.$b.stream);c.timestamp=Date.now();a&&(a.Ma[b]=c,a.timestamp=c.timestamp);return c},md:function(a){return a.Ma?a.Ma.subarray?a.Ma.subarray(0,a.Ra):new Uint8Array(a.Ma):new Uint8Array(0)},cc:function(a,
b){var c=a.Ma?a.Ma.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)>>>0),0!=c&&(b=Math.max(b,256)),c=a.Ma,a.Ma=new Uint8Array(b),0<a.Ra&&a.Ma.set(c.subarray(0,a.Ra),0))},Tc:function(a,b){if(a.Ra!=b)if(0==b)a.Ma=null,a.Ra=0;else{var c=a.Ma;a.Ma=new Uint8Array(b);c&&a.Ma.set(c.subarray(0,Math.min(b,a.Ra)));a.Ra=b}},Na:{bb:function(a){var b={};b.zc=8192===(a.mode&61440)?a.id:1;b.Ob=a.id;b.mode=a.mode;b.Pc=1;b.uid=0;b.Gc=0;b.vb=a.vb;b.size=16384===(a.mode&61440)?4096:32768===(a.mode&61440)?a.Ra:40960===
(a.mode&61440)?a.link.length:0;b.sc=new Date(a.timestamp);b.Oc=new Date(a.timestamp);b.xc=new Date(a.timestamp);b.tc=4096;b.uc=Math.ceil(b.size/b.tc);return b},Ya:function(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);void 0!==b.size&&N.Tc(a,b.size)},rb:function(){throw jb[44];},Fb:function(a,b,c,d){return N.createNode(a,b,c,d)},nc:function(a,b,c){if(16384===(a.mode&61440)){try{var d=kb(b,c)}catch(f){}if(d)for(var e in d.Ma)throw new M(55);}delete a.parent.Ma[a.name];
a.parent.timestamp=Date.now();a.name=c;b.Ma[c]=a;b.timestamp=a.parent.timestamp;a.parent=b},Lb:function(a,b){delete a.Ma[b];a.timestamp=Date.now()},oc:function(a,b){var c=kb(a,b),d;for(d in c.Ma)throw new M(55);delete a.Ma[b];a.timestamp=Date.now()},mc:function(a){var b=[".",".."],c;for(c in a.Ma)a.Ma.hasOwnProperty(c)&&b.push(c);return b},Ib:function(a,b,c){a=N.createNode(a,b,41471,0);a.link=c;return a},wb:function(a){if(40960!==(a.mode&61440))throw new M(28);return a.link}},Oa:{read:function(a,
b,c,d,e){var f=a.node.Ma;if(e>=a.node.Ra)return 0;a=Math.min(a.node.Ra-e,d);if(8<a&&f.subarray)b.set(f.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=f[e+d];return a},write:function(a,b,c,d,e,f){b.buffer===C.buffer&&(f=!1);if(!d)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&(!a.Ma||a.Ma.subarray)){if(f)return a.Ma=b.subarray(c,c+d),a.Ra=d;if(0===a.Ra&&0===e)return a.Ma=b.slice(c,c+d),a.Ra=d;if(e+d<=a.Ra)return a.Ma.set(b.subarray(c,c+d),e),d}N.cc(a,e+d);if(a.Ma.subarray&&b.subarray)a.Ma.set(b.subarray(c,
c+d),e);else for(f=0;f<d;f++)a.Ma[e+f]=b[c+f];a.Ra=Math.max(a.Ra,e+d);return d},jb:function(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.Ra);if(0>b)throw new M(28);return b},Xb:function(a,b,c){N.cc(a.node,b+c);a.node.Ra=Math.max(a.node.Ra,b+c)},sb:function(a,b,c,d,e){if(32768!==(a.node.mode&61440))throw new M(43);a=a.node.Ma;if(e&2||a.buffer!==C.buffer){if(0<c||c+b<a.length)a=a.subarray?a.subarray(c,c+b):Array.prototype.slice.call(a,c,c+b);c=!0;b=fb(b);if(!b)throw new M(48);
C.set(a,b)}else c=!1,b=a.byteOffset;return{Pa:b,Yb:c}},Gb:function(a,b,c,d){N.Oa.write(a,b,0,d,c,!1);return 0}}};function lb(a,b,c){var d="al "+a;ka(a,e=>{e||oa('Loading data file "'+a+'" failed (no arrayBuffer).');b(new Uint8Array(e));d&&Ha(d)},()=>{if(c)c();else throw'Loading data file "'+a+'" failed.';});d&&Ga(d)}
var mb=null,nb={},ob=[],pb=1,qb=null,rb=!0,M=null,jb={},tb=(a,b={})=>{a=Ya(a);if(!a)return{path:"",node:null};b=Object.assign({ec:!0,Tb:0},b);if(8<b.Tb)throw new M(32);a=a.split("/").filter(h=>!!h);for(var c=mb,d="/",e=0;e<a.length;e++){var f=e===a.length-1;if(f&&b.parent)break;c=kb(c,a[e]);d=L(d+"/"+a[e]);c.tb&&(!f||f&&b.ec)&&(c=c.tb.root);if(!f||b.Ab)for(f=0;40960===(c.mode&61440);)if(c=sb(d),d=Ya(Va(d),c),c=tb(d,{Tb:b.Tb+1}).node,40<f++)throw new M(32);}return{path:d,node:c}},ub=a=>{for(var b;;){if(a===
a.parent)return a=a.fb.ic,b?"/"!==a[a.length-1]?a+"/"+b:a+b:a;b=b?a.name+"/"+b:a.name;a=a.parent}},vb=(a,b)=>{for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%qb.length},kb=(a,b)=>{var c;if(c=(c=wb(a,"x"))?c:a.Na.rb?0:2)throw new M(c,a);for(c=qb[vb(a.id,b)];c;c=c.pb){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.Na.rb(a,b)},ib=(a,b,c,d)=>{a=new xb(a,b,c,d);b=vb(a.parent.id,a.name);a.pb=qb[b];return qb[b]=a},yb={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090},zb=
a=>{var b=["r","w","rw"][a&3];a&512&&(b+="w");return b},wb=(a,b)=>{if(rb)return 0;if(!b.includes("r")||a.mode&292){if(b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73))return 2}else return 2;return 0},Ab=(a,b)=>{try{return kb(a,b),20}catch(c){}return wb(a,"wx")},Bb=(a=0)=>{for(;4096>=a;a++)if(!ob[a])return a;throw new M(33);},Db=(a,b)=>{Cb||(Cb=function(){this.Hb={}},Cb.prototype={},Object.defineProperties(Cb.prototype,{object:{get:function(){return this.node},set:function(c){this.node=
c}},flags:{get:function(){return this.Hb.flags},set:function(c){this.Hb.flags=c}},position:{get:function(){return this.Hb.position},set:function(c){this.Hb.position=c}}}));a=Object.assign(new Cb,a);b=Bb(b);a.hb=b;return ob[b]=a},hb={open:a=>{a.Oa=nb[a.node.vb].Oa;a.Oa.open&&a.Oa.open(a)},jb:()=>{throw new M(70);}},bb=(a,b)=>{nb[a]={Oa:b}},Eb=(a,b)=>{var c="/"===b,d=!b;if(c&&mb)throw new M(10);if(!c&&!d){var e=tb(b,{ec:!1});b=e.path;e=e.node;if(e.tb)throw new M(10);if(16384!==(e.mode&61440))throw new M(54);
}b={type:a,pd:{},ic:b,Nc:[]};a=a.fb(b);a.fb=b;b.root=a;c?mb=a:e&&(e.tb=b,e.fb&&e.fb.Nc.push(b))},P=(a,b,c)=>{var d=tb(a,{parent:!0}).node;a=Wa(a);if(!a||"."===a||".."===a)throw new M(28);var e=Ab(d,a);if(e)throw new M(e);if(!d.Na.Fb)throw new M(63);return d.Na.Fb(d,a,b,c)},Fb=(a,b,c)=>{"undefined"==typeof c&&(c=b,b=438);return P(a,b|8192,c)},Gb=(a,b)=>{if(!Ya(a))throw new M(44);var c=tb(b,{parent:!0}).node;if(!c)throw new M(44);b=Wa(b);var d=Ab(c,b);if(d)throw new M(d);if(!c.Na.Ib)throw new M(63);
c.Na.Ib(c,b,a)},Hb=a=>{var b=tb(a,{parent:!0}).node;if(!b)throw new M(44);var c=Wa(a);a=kb(b,c);a:{try{var d=kb(b,c)}catch(f){d=f.Wa;break a}var e=wb(b,"wx");d=e?e:16384===(d.mode&61440)?31:0}if(d)throw new M(d);if(!b.Na.Lb)throw new M(63);if(a.tb)throw new M(10);b.Na.Lb(b,c);b=vb(a.parent.id,a.name);if(qb[b]===a)qb[b]=a.pb;else for(b=qb[b];b;){if(b.pb===a){b.pb=a.pb;break}b=b.pb}},sb=a=>{a=tb(a).node;if(!a)throw new M(44);if(!a.Na.wb)throw new M(28);return Ya(ub(a.parent),a.Na.wb(a))},Ib=(a,b)=>
{a=tb(a,{Ab:!b}).node;if(!a)throw new M(44);if(!a.Na.bb)throw new M(63);return a.Na.bb(a)},Jb=a=>Ib(a,!0),Kb=(a,b)=>{a="string"==typeof a?tb(a,{Ab:!0}).node:a;if(!a.Na.Ya)throw new M(63);a.Na.Ya(a,{mode:b&4095|a.mode&-4096,timestamp:Date.now()})},Mb=(a,b,c)=>{if(""===a)throw new M(44);if("string"==typeof b){var d=yb[b];if("undefined"==typeof d)throw Error("Unknown file open mode: "+b);b=d}c=b&64?("undefined"==typeof c?438:c)&4095|32768:0;if("object"==typeof a)var e=a;else{a=L(a);try{e=tb(a,{Ab:!(b&
131072)}).node}catch(f){}}d=!1;if(b&64)if(e){if(b&128)throw new M(20);}else e=P(a,c,0),d=!0;if(!e)throw new M(44);8192===(e.mode&61440)&&(b&=-513);if(b&65536&&16384!==(e.mode&61440))throw new M(54);if(!d&&(c=e?40960===(e.mode&61440)?32:16384===(e.mode&61440)&&("r"!==zb(b)||b&512)?31:wb(e,zb(b)):44))throw new M(c);if(b&512&&!d){c=e;c="string"==typeof c?tb(c,{Ab:!0}).node:c;if(!c.Na.Ya)throw new M(63);if(16384===(c.mode&61440))throw new M(31);if(32768!==(c.mode&61440))throw new M(28);if(d=wb(c,"w"))throw new M(d);
c.Na.Ya(c,{size:0,timestamp:Date.now()})}b&=-131713;e=Db({node:e,path:ub(e),flags:b,seekable:!0,position:0,Oa:e.Oa,kd:[],error:!1});e.Oa.open&&e.Oa.open(e);!g.logReadFiles||b&1||(Lb||(Lb={}),a in Lb||(Lb[a]=1));return e},Nb=a=>{if(null===a.hb)throw new M(8);a.Nb&&(a.Nb=null);try{a.Oa.close&&a.Oa.close(a)}catch(b){throw b;}finally{ob[a.hb]=null}a.hb=null},Ob=(a,b,c)=>{if(null===a.hb)throw new M(8);if(!a.seekable||!a.Oa.jb)throw new M(70);if(0!=c&&1!=c&&2!=c)throw new M(28);a.position=a.Oa.jb(a,b,c);
a.kd=[]},Pb=(a,b,c,d,e,f)=>{if(0>d||0>e)throw new M(28);if(null===a.hb)throw new M(8);if(0===(a.flags&2097155))throw new M(8);if(16384===(a.node.mode&61440))throw new M(31);if(!a.Oa.write)throw new M(28);a.seekable&&a.flags&1024&&Ob(a,0,2);var h="undefined"!=typeof e;if(!h)e=a.position;else if(!a.seekable)throw new M(70);b=a.Oa.write(a,b,c,d,e,f);h||(a.position+=b);return b},Qb=()=>{M||(M=function(a,b){this.node=b;this.Vc=function(c){this.Wa=c};this.Vc(a);this.message="FS error"},M.prototype=Error(),
M.prototype.constructor=M,[44].forEach(a=>{jb[a]=new M(a);jb[a].stack="<generic error, no stack>"}))},Rb,Sb=(a,b)=>{var c=0;a&&(c|=365);b&&(c|=146);return c},Tb=(a,b)=>{a="string"==typeof a?a:ub(a);for(b=b.split("/").reverse();b.length;){var c=b.pop();if(c){var d=L(a+"/"+c);try{P(d,16895,0)}catch(e){}a=d}}return d},Ub=(a,b,c,d)=>{a=L(("string"==typeof a?a:ub(a))+"/"+b);c=Sb(c,d);return P(a,(void 0!==c?c:438)&4095|32768,0)},Vb=(a,b,c,d,e,f)=>{var h=b;a&&(a="string"==typeof a?a:ub(a),h=b?L(a+"/"+b):
a);a=Sb(d,e);h=P(h,(void 0!==a?a:438)&4095|32768,0);if(c){if("string"==typeof c){b=Array(c.length);d=0;for(e=c.length;d<e;++d)b[d]=c.charCodeAt(d);c=b}Kb(h,a|146);b=Mb(h,577);Pb(b,c,0,c.length,0,f);Nb(b);Kb(h,a)}return h},Wb=(a,b,c,d)=>{a=L(("string"==typeof a?a:ub(a))+"/"+b);b=Sb(!!c,!!d);Wb.hc||(Wb.hc=64);var e=Wb.hc++<<8|0;bb(e,{open:f=>{f.seekable=!1},close:()=>{d&&d.buffer&&d.buffer.length&&d(10)},read:(f,h,l,m)=>{for(var n=0,t=0;t<m;t++){try{var p=c()}catch(q){throw new M(29);}if(void 0===p&&
0===n)throw new M(6);if(null===p||void 0===p)break;n++;h[l+t]=p}n&&(f.node.timestamp=Date.now());return n},write:(f,h,l,m)=>{for(var n=0;n<m;n++)try{d(h[l+n])}catch(t){throw new M(29);}m&&(f.node.timestamp=Date.now());return n}});return Fb(a,b,e)},Xb=a=>{if(!(a.Kc||a.Lc||a.link||a.Ma)){if("undefined"!=typeof XMLHttpRequest)throw Error("Lazy loading should have been performed (contents set) in createLazyFile, but it was not. Lazy loading only works in web workers. Use --embed-file or --preload-file in emcc on the main thread.");
if(ja)try{a.Ma=Za(ja(a.url),!0),a.Ra=a.Ma.length}catch(b){throw new M(29);}else throw Error("Cannot load without read() or XMLHttpRequest.");}},Yb=(a,b,c,d,e)=>{function f(){this.Qb=!1;this.zb=[]}function h(p,q,k,u,x){p=p.node.Ma;if(x>=p.length)return 0;u=Math.min(p.length-x,u);if(p.slice)for(var z=0;z<u;z++)q[k+z]=p[x+z];else for(z=0;z<u;z++)q[k+z]=p.get(x+z);return u}f.prototype.get=function(p){if(!(p>this.length-1||0>p)){var q=p%this.ac;return this.Cb(p/this.ac|0)[q]}};f.prototype.Uc=function(p){this.Cb=
p};f.prototype.Zb=function(){var p=new XMLHttpRequest;p.open("HEAD",c,!1);p.send(null);if(!(200<=p.status&&300>p.status||304===p.status))throw Error("Couldn't load "+c+". Status: "+p.status);var q=Number(p.getResponseHeader("Content-length")),k,u=(k=p.getResponseHeader("Accept-Ranges"))&&"bytes"===k;p=(k=p.getResponseHeader("Content-Encoding"))&&"gzip"===k;var x=1048576;u||(x=q);var z=this;z.Uc(F=>{var H=F*x,y=(F+1)*x-1;y=Math.min(y,q-1);if("undefined"==typeof z.zb[F]){var O=z.zb;if(H>y)throw Error("invalid range ("+
H+", "+y+") or no bytes requested!");if(y>q-1)throw Error("only "+q+" bytes available! programmer error!");var B=new XMLHttpRequest;B.open("GET",c,!1);q!==x&&B.setRequestHeader("Range","bytes="+H+"-"+y);B.responseType="arraybuffer";B.overrideMimeType&&B.overrideMimeType("text/plain; charset=x-user-defined");B.send(null);if(!(200<=B.status&&300>B.status||304===B.status))throw Error("Couldn't load "+c+". Status: "+B.status);H=void 0!==B.response?new Uint8Array(B.response||[]):Za(B.responseText||"",
!0);O[F]=H}if("undefined"==typeof z.zb[F])throw Error("doXHR failed!");return z.zb[F]});if(p||!q)x=q=1,x=q=this.Cb(0).length,ma("LazyFiles on gzip forces download of the whole file when length is accessed");this.qc=q;this.pc=x;this.Qb=!0};if("undefined"!=typeof XMLHttpRequest){if(!ha)throw"Cannot do synchronous binary XHRs outside webworkers in modern browsers. Use --embed-file or --preload-file in emcc";var l=new f;Object.defineProperties(l,{length:{get:function(){this.Qb||this.Zb();return this.qc}},
ac:{get:function(){this.Qb||this.Zb();return this.pc}}});var m=void 0}else m=c,l=void 0;var n=Ub(a,b,d,e);l?n.Ma=l:m&&(n.Ma=null,n.url=m);Object.defineProperties(n,{Ra:{get:function(){return this.Ma.length}}});var t={};Object.keys(n.Oa).forEach(p=>{var q=n.Oa[p];t[p]=function(){Xb(n);return q.apply(null,arguments)}});t.read=(p,q,k,u,x)=>{Xb(n);return h(p,q,k,u,x)};t.sb=(p,q,k)=>{Xb(n);var u=fb(q);if(!u)throw new M(48);h(p,C,u,q,k);return{Pa:u,Yb:!0}};n.Oa=t;return n},$b=(a,b,c,d,e,f,h,l,m,n)=>{function t(k){function u(x){n&&
n();l||Vb(a,b,x,d,e,m);f&&f();Ha(q)}Zb.nd(k,p,u,()=>{h&&h();Ha(q)})||u(k)}var p=b?Ya(L(a+"/"+b)):a,q="cp "+p;Ga(q);"string"==typeof c?lb(c,k=>t(k),h):t(c)},Q={},Cb,Lb;function ac(a,b,c){if("/"===b.charAt(0))return b;a=-100===a?"/":bc(a).path;if(0==b.length){if(!c)throw new M(44);return a}return L(a+"/"+b)}
function cc(a,b,c){try{var d=a(b)}catch(f){if(f&&f.node&&L(b)!==L(ub(f.node)))return-54;throw f;}E[c>>2]=d.zc;E[c+8>>2]=d.Ob;E[c+12>>2]=d.mode;G[c+16>>2]=d.Pc;E[c+20>>2]=d.uid;E[c+24>>2]=d.Gc;E[c+28>>2]=d.vb;K=[d.size>>>0,(J=d.size,1<=+Math.abs(J)?0<J?(Math.min(+Math.floor(J/4294967296),4294967295)|0)>>>0:~~+Math.ceil((J-+(~~J>>>0))/4294967296)>>>0:0)];E[c+40>>2]=K[0];E[c+44>>2]=K[1];E[c+48>>2]=4096;E[c+52>>2]=d.uc;a=d.sc.getTime();b=d.Oc.getTime();var e=d.xc.getTime();K=[Math.floor(a/1E3)>>>0,(J=
Math.floor(a/1E3),1<=+Math.abs(J)?0<J?(Math.min(+Math.floor(J/4294967296),4294967295)|0)>>>0:~~+Math.ceil((J-+(~~J>>>0))/4294967296)>>>0:0)];E[c+56>>2]=K[0];E[c+60>>2]=K[1];G[c+64>>2]=a%1E3*1E3;K=[Math.floor(b/1E3)>>>0,(J=Math.floor(b/1E3),1<=+Math.abs(J)?0<J?(Math.min(+Math.floor(J/4294967296),4294967295)|0)>>>0:~~+Math.ceil((J-+(~~J>>>0))/4294967296)>>>0:0)];E[c+72>>2]=K[0];E[c+76>>2]=K[1];G[c+80>>2]=b%1E3*1E3;K=[Math.floor(e/1E3)>>>0,(J=Math.floor(e/1E3),1<=+Math.abs(J)?0<J?(Math.min(+Math.floor(J/
4294967296),4294967295)|0)>>>0:~~+Math.ceil((J-+(~~J>>>0))/4294967296)>>>0:0)];E[c+88>>2]=K[0];E[c+92>>2]=K[1];G[c+96>>2]=e%1E3*1E3;K=[d.Ob>>>0,(J=d.Ob,1<=+Math.abs(J)?0<J?(Math.min(+Math.floor(J/4294967296),4294967295)|0)>>>0:~~+Math.ceil((J-+(~~J>>>0))/4294967296)>>>0:0)];E[c+104>>2]=K[0];E[c+108>>2]=K[1];return 0}var dc=void 0;function ec(){dc+=4;return E[dc-4>>2]}function bc(a){a=ob[a];if(!a)throw new M(8);return a}var fc={};function gc(a){for(;a.length;){var b=a.pop();a.pop()(b)}}
function hc(a){return this.fromWireType(E[a>>2])}var ic={},jc={},kc={};function lc(a){if(void 0===a)return"_unknown";a=a.replace(/[^a-zA-Z0-9_]/g,"$");var b=a.charCodeAt(0);return 48<=b&&57>=b?"_"+a:a}function mc(a,b){a=lc(a);return function(){return b.apply(this,arguments)}}
function nc(a){var b=Error,c=mc(a,function(d){this.name=a;this.message=d;d=Error(d).stack;void 0!==d&&(this.stack=this.toString()+"\n"+d.replace(/^Error(:[^\n]*)?\n/,""))});c.prototype=Object.create(b.prototype);c.prototype.constructor=c;c.prototype.toString=function(){return void 0===this.message?this.name:this.name+": "+this.message};return c}var oc=void 0;function pc(a){throw new oc(a);}
function qc(a,b,c){function d(l){l=c(l);l.length!==a.length&&pc("Mismatched type converter count");for(var m=0;m<a.length;++m)rc(a[m],l[m])}a.forEach(function(l){kc[l]=b});var e=Array(b.length),f=[],h=0;b.forEach((l,m)=>{jc.hasOwnProperty(l)?e[m]=jc[l]:(f.push(l),ic.hasOwnProperty(l)||(ic[l]=[]),ic[l].push(()=>{e[m]=jc[l];++h;h===f.length&&d(e)}))});0===f.length&&d(e)}
function sc(a){switch(a){case 1:return 0;case 2:return 1;case 4:return 2;case 8:return 3;default:throw new TypeError("Unknown type size: "+a);}}var tc=void 0;function R(a){for(var b="";w[a];)b+=tc[w[a++]];return b}var uc=void 0;function S(a){throw new uc(a);}
function rc(a,b,c={}){if(!("argPackAdvance"in b))throw new TypeError("registerType registeredInstance requires argPackAdvance");var d=b.name;a||S('type "'+d+'" must have a positive integer typeid pointer');if(jc.hasOwnProperty(a)){if(c.Hc)return;S("Cannot register type '"+d+"' twice")}jc[a]=b;delete kc[a];ic.hasOwnProperty(a)&&(b=ic[a],delete ic[a],b.forEach(e=>e()))}function vc(a){S(a.La.Sa.Qa.name+" instance already deleted")}var wc=!1;function xc(){}
function yc(a){--a.count.value;0===a.count.value&&(a.Xa?a.Za.gb(a.Xa):a.Sa.Qa.gb(a.Pa))}function zc(a,b,c){if(b===c)return a;if(void 0===c.$a)return null;a=zc(a,b,c.$a);return null===a?null:c.Ac(a)}var Ac={},Bc=[];function Cc(){for(;Bc.length;){var a=Bc.pop();a.La.nb=!1;a["delete"]()}}var Dc=void 0,Ec={};function Fc(a,b){for(void 0===b&&S("ptr should not be undefined");a.$a;)b=a.xb(b),a=a.$a;return Ec[b]}
function Gc(a,b){b.Sa&&b.Pa||pc("makeClassHandle requires ptr and ptrType");!!b.Za!==!!b.Xa&&pc("Both smartPtrType and smartPtr must be specified");b.count={value:1};return Hc(Object.create(a,{La:{value:b}}))}function Hc(a){if("undefined"===typeof FinalizationRegistry)return Hc=b=>b,a;wc=new FinalizationRegistry(b=>{yc(b.La)});Hc=b=>{var c=b.La;c.Xa&&wc.register(b,{La:c},b);return b};xc=b=>{wc.unregister(b)};return Hc(a)}function Ic(){}
function Jc(a,b,c){if(void 0===a[b].Va){var d=a[b];a[b]=function(){a[b].Va.hasOwnProperty(arguments.length)||S("Function '"+c+"' called with an invalid number of arguments ("+arguments.length+") - expects one of ("+a[b].Va+")!");return a[b].Va[arguments.length].apply(this,arguments)};a[b].Va=[];a[b].Va[d.yb]=d}}
function Kc(a,b,c){g.hasOwnProperty(a)?((void 0===c||void 0!==g[a].Va&&void 0!==g[a].Va[c])&&S("Cannot register public name '"+a+"' twice"),Jc(g,a,a),g.hasOwnProperty(c)&&S("Cannot register multiple overloads of a function with the same number of arguments ("+c+")!"),g[a].Va[c]=b):(g[a]=b,void 0!==c&&(g[a].od=c))}function Lc(a,b,c,d,e,f,h,l){this.name=a;this.constructor=b;this.ob=c;this.gb=d;this.$a=e;this.Cc=f;this.xb=h;this.Ac=l;this.Rc=[]}
function Mc(a,b,c){for(;b!==c;)b.xb||S("Expected null or instance of "+c.name+", got an instance of "+b.name),a=b.xb(a),b=b.$a;return a}function Nc(a,b){if(null===b)return this.Pb&&S("null is not a valid "+this.name),0;b.La||S('Cannot pass "'+Oc(b)+'" as a '+this.name);b.La.Pa||S("Cannot pass deleted object as a pointer of type "+this.name);return Mc(b.La.Pa,b.La.Sa.Qa,this.Qa)}
function Pc(a,b){if(null===b){this.Pb&&S("null is not a valid "+this.name);if(this.Eb){var c=this.Sb();null!==a&&a.push(this.gb,c);return c}return 0}b.La||S('Cannot pass "'+Oc(b)+'" as a '+this.name);b.La.Pa||S("Cannot pass deleted object as a pointer of type "+this.name);!this.Db&&b.La.Sa.Db&&S("Cannot convert argument of type "+(b.La.Za?b.La.Za.name:b.La.Sa.name)+" to parameter type "+this.name);c=Mc(b.La.Pa,b.La.Sa.Qa,this.Qa);if(this.Eb)switch(void 0===b.La.Xa&&S("Passing raw pointer to smart pointer is illegal"),
this.ed){case 0:b.La.Za===this?c=b.La.Xa:S("Cannot convert argument of type "+(b.La.Za?b.La.Za.name:b.La.Sa.name)+" to parameter type "+this.name);break;case 1:c=b.La.Xa;break;case 2:if(b.La.Za===this)c=b.La.Xa;else{var d=b.clone();c=this.Sc(c,T(function(){d["delete"]()}));null!==a&&a.push(this.gb,c)}break;default:S("Unsupporting sharing policy")}return c}
function Qc(a,b){if(null===b)return this.Pb&&S("null is not a valid "+this.name),0;b.La||S('Cannot pass "'+Oc(b)+'" as a '+this.name);b.La.Pa||S("Cannot pass deleted object as a pointer of type "+this.name);b.La.Sa.Db&&S("Cannot convert argument of type "+b.La.Sa.name+" to parameter type "+this.name);return Mc(b.La.Pa,b.La.Sa.Qa,this.Qa)}
function Rc(a,b,c,d){this.name=a;this.Qa=b;this.Pb=c;this.Db=d;this.Eb=!1;this.gb=this.Sc=this.Sb=this.lc=this.ed=this.Qc=void 0;void 0!==b.$a?this.toWireType=Pc:(this.toWireType=d?Nc:Qc,this.ab=null)}function Sc(a,b,c){g.hasOwnProperty(a)||pc("Replacing nonexistant public symbol");void 0!==g[a].Va&&void 0!==c?g[a].Va[c]=b:(g[a]=b,g[a].yb=c)}var Tc=[];function U(a){var b=Tc[a];b||(a>=Tc.length&&(Tc.length=a+1),Tc[a]=b=ya.get(a));return b}
function Uc(a,b){var c=[];return function(){c.length=0;Object.assign(c,arguments);if(a.includes("j")){var d=g["dynCall_"+a];d=c&&c.length?d.apply(null,[b].concat(c)):d.call(null,b)}else d=U(b).apply(null,c);return d}}function V(a,b){a=R(a);var c=a.includes("j")?Uc(a,b):U(b);"function"!=typeof c&&S("unknown function pointer with signature "+a+": "+b);return c}var Vc=void 0;function Wc(a){a=Xc(a);var b=R(a);Yc(a);return b}
function Zc(a,b){function c(f){e[f]||jc[f]||(kc[f]?kc[f].forEach(c):(d.push(f),e[f]=!0))}var d=[],e={};b.forEach(c);throw new Vc(a+": "+d.map(Wc).join([", "]));}function $c(a,b){for(var c=[],d=0;d<a;d++)c.push(G[b+4*d>>2]);return c}
function ad(a,b,c,d,e){var f=b.length;2>f&&S("argTypes array size mismatch! Must at least get return value and 'this' types!");var h=null!==b[1]&&null!==c,l=!1;for(c=1;c<b.length;++c)if(null!==b[c]&&void 0===b[c].ab){l=!0;break}var m="void"!==b[0].name,n=f-2,t=Array(n),p=[],q=[];return function(){arguments.length!==n&&S("function "+a+" called with "+arguments.length+" arguments, expected "+n+" args!");q.length=0;p.length=h?2:1;p[0]=e;if(h){var k=b[1].toWireType(q,this);p[1]=k}for(var u=0;u<n;++u)t[u]=
b[u+2].toWireType(q,arguments[u]),p.push(t[u]);u=d.apply(null,p);if(l)gc(q);else for(var x=h?1:2;x<b.length;x++){var z=1===x?k:t[x-2];null!==b[x].ab&&b[x].ab(z)}k=m?b[0].fromWireType(u):void 0;return k}}var bd=[],W=[{},{value:void 0},{value:null},{value:!0},{value:!1}];function cd(a){4<a&&0===--W[a].Ub&&(W[a]=void 0,bd.push(a))}
var X=a=>{a||S("Cannot use deleted val. handle = "+a);return W[a].value},T=a=>{switch(a){case void 0:return 1;case null:return 2;case !0:return 3;case !1:return 4;default:var b=bd.length?bd.pop():W.length;W[b]={Ub:1,value:a};return b}};function Oc(a){if(null===a)return"null";var b=typeof a;return"object"===b||"array"===b||"function"===b?a.toString():""+a}
function dd(a,b){switch(b){case 2:return function(c){return this.fromWireType(va[c>>2])};case 3:return function(c){return this.fromWireType(wa[c>>3])};default:throw new TypeError("Unknown float type: "+a);}}
function ed(a,b,c){switch(b){case 0:return c?function(d){return C[d]}:function(d){return w[d]};case 1:return c?function(d){return ua[d>>1]}:function(d){return D[d>>1]};case 2:return c?function(d){return E[d>>2]}:function(d){return G[d>>2]};default:throw new TypeError("Unknown integer type: "+a);}}var fd="undefined"!=typeof TextDecoder?new TextDecoder("utf-16le"):void 0;
function gd(a,b){var c=a>>1;for(var d=c+b/2;!(c>=d)&&D[c];)++c;c<<=1;if(32<c-a&&fd)return fd.decode(w.subarray(a,c));c="";for(d=0;!(d>=b/2);++d){var e=ua[a+2*d>>1];if(0==e)break;c+=String.fromCharCode(e)}return c}function hd(a,b,c){void 0===c&&(c=2147483647);if(2>c)return 0;c-=2;var d=b;c=c<2*a.length?c/2:a.length;for(var e=0;e<c;++e)ua[b>>1]=a.charCodeAt(e),b+=2;ua[b>>1]=0;return b-d}function jd(a){return 2*a.length}
function kd(a,b){for(var c=0,d="";!(c>=b/4);){var e=E[a+4*c>>2];if(0==e)break;++c;65536<=e?(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023)):d+=String.fromCharCode(e)}return d}function ld(a,b,c){void 0===c&&(c=2147483647);if(4>c)return 0;var d=b;c=d+c-4;for(var e=0;e<a.length;++e){var f=a.charCodeAt(e);if(55296<=f&&57343>=f){var h=a.charCodeAt(++e);f=65536+((f&1023)<<10)|h&1023}E[b>>2]=f;b+=4;if(b+4>c)break}E[b>>2]=0;return b-d}
function md(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&++c;b+=4}return b}function nd(a,b){var c=jc[a];void 0===c&&S(b+" has unknown type "+Wc(a));return c}function od(a,b){for(var c=Array(a),d=0;d<a;++d)c[d]=nd(G[b+4*d>>2],"parameter "+d);return c}var pd={};function qd(a){var b=pd[a];return void 0===b?R(a):b}var rd=[];
function sd(){function a(b){b.$$$embind_global$$$=b;var c="object"==typeof $$$embind_global$$$&&b.$$$embind_global$$$==b;c||delete b.$$$embind_global$$$;return c}if("object"==typeof globalThis)return globalThis;if("object"==typeof $$$embind_global$$$)return $$$embind_global$$$;"object"==typeof global&&a(global)?$$$embind_global$$$=global:"object"==typeof self&&a(self)&&($$$embind_global$$$=self);if("object"==typeof $$$embind_global$$$)return $$$embind_global$$$;throw Error("unable to get global object.");
}function td(a){var b=rd.length;rd.push(a);return b}var ud=[];function vd(a){var b=Array(a+1);return function(c,d,e){b[0]=c;for(var f=0;f<a;++f){var h=nd(G[d+4*f>>2],"parameter "+f);b[f+1]=h.readValueFromPointer(e);e+=h.argPackAdvance}c=new (c.bind.apply(c,b));return T(c)}}var wd={};function xd(a){return 0===a%4&&(0!==a%100||0===a%400)}var yd=[0,31,60,91,121,152,182,213,244,274,305,335],zd=[0,31,59,90,120,151,181,212,243,273,304,334];
function Ad(a){return(xd(a.getFullYear())?yd:zd)[a.getMonth()]+a.getDate()-1}function Bd(a){var b=ta(a)+1,c=Cd(b);c&&A(a,C,c,b);return c}var Dd=[],Ed={};function Z(a,b){G[a>>2]=b;G[a+4>>2]=b/4294967296|0}var Fd;
function Gd(a,b,c,d,e){function f(){var B=0,Y=0;y.response&&F&&0===G[a+12>>2]&&(Y=y.response.byteLength);0<Y&&(B=Cd(Y),w.set(new Uint8Array(y.response),B));G[a+12>>2]=B;Z(a+16,Y);Z(a+24,0);(B=y.response?y.response.byteLength:0)&&Z(a+32,B);D[a+40>>1]=y.readyState;D[a+42>>1]=y.status;y.statusText&&A(y.statusText,w,a+44,64)}var h=G[a+8>>2];if(h){var l=v(h),m=a+112,n=v(m);n||(n="GET");var t=G[m+52>>2],p=G[m+56>>2],q=!!G[m+60>>2],k=G[m+68>>2],u=G[m+72>>2];h=G[m+76>>2];var x=G[m+80>>2],z=G[m+84>>2];m=G[m+
88>>2];var F=!!(t&1),H=!!(t&2);t=!!(t&64);k=k?v(k):void 0;u=u?v(u):void 0;var y=new XMLHttpRequest;y.withCredentials=q;y.open(n,l,!t,k,u);t||(y.timeout=p);y.rd=l;y.responseType="arraybuffer";x&&(l=v(x),y.overrideMimeType(l));if(h)for(;;){n=G[h>>2];if(!n)break;l=G[h+4>>2];if(!l)break;h+=8;n=v(n);l=v(l);y.setRequestHeader(n,l)}var O=G[a+0>>2];Ed[O]=y;h=z&&m?w.slice(z,z+m):null;y.onload=B=>{O in Ed&&(f(),200<=y.status&&300>y.status?b&&b(a,y,B):c&&c(a,y,B))};y.onerror=B=>{O in Ed&&(f(),c&&c(a,y,B))};
y.ontimeout=B=>{O in Ed&&c&&c(a,y,B)};y.onprogress=B=>{if(O in Ed){var Y=F&&H&&y.response?y.response.byteLength:0,I=0;0<Y&&F&&H&&(I=Cd(Y),w.set(new Uint8Array(y.response),I));G[a+12>>2]=I;Z(a+16,Y);Z(a+24,B.loaded-Y);Z(a+32,B.total);D[a+40>>1]=y.readyState;3<=y.readyState&&0===y.status&&0<B.loaded&&(y.status=200);D[a+42>>1]=y.status;y.statusText&&A(y.statusText,w,a+44,64);d&&d(a,y,B);I&&Yc(I)}};y.onreadystatechange=B=>{O in Ed&&(D[a+40>>1]=y.readyState,2<=y.readyState&&(D[a+42>>1]=y.status),e&&e(a,
y,B))};try{y.send(h)}catch(B){c&&c(a,y,B)}}else c(a,0,"no url specified!")}function Hd(a,b,c,d){var e=Fd;if(e){var f=G[a+112+64>>2];f||(f=G[a+8>>2]);var h=v(f);try{var l=e.transaction(["FILES"],"readwrite").objectStore("FILES").put(b,h);l.onsuccess=()=>{D[a+40>>1]=4;D[a+42>>1]=200;A("OK",w,a+44,64);c(a,0,h)};l.onerror=m=>{D[a+40>>1]=4;D[a+42>>1]=413;A("Payload Too Large",w,a+44,64);d(a,0,m)}}catch(m){d(a,0,m)}}else d(a,0,"IndexedDB not available!")}
function Id(a,b,c){var d=Fd;if(d){var e=G[a+112+64>>2];e||(e=G[a+8>>2]);e=v(e);try{var f=d.transaction(["FILES"],"readonly").objectStore("FILES").get(e);f.onsuccess=h=>{if(h.target.result){h=h.target.result;var l=h.byteLength||h.length,m=Cd(l);w.set(new Uint8Array(h),m);G[a+12>>2]=m;Z(a+16,l);Z(a+24,0);Z(a+32,l);D[a+40>>1]=4;D[a+42>>1]=200;A("OK",w,a+44,64);b(a,0,h)}else D[a+40>>1]=4,D[a+42>>1]=404,A("Not Found",w,a+44,64),c(a,0,"no data")};f.onerror=h=>{D[a+40>>1]=4;D[a+42>>1]=404;A("Not Found",
w,a+44,64);c(a,0,h)}}catch(h){c(a,0,h)}}else c(a,0,"IndexedDB not available!")}
function Jd(a,b,c){var d=Fd;if(d){var e=G[a+112+64>>2];e||(e=G[a+8>>2]);e=v(e);try{var f=d.transaction(["FILES"],"readwrite").objectStore("FILES").delete(e);f.onsuccess=h=>{h=h.target.result;G[a+12>>2]=0;Z(a+16,0);Z(a+24,0);Z(a+32,0);D[a+40>>1]=4;D[a+42>>1]=200;A("OK",w,a+44,64);b(a,0,h)};f.onerror=h=>{D[a+40>>1]=4;D[a+42>>1]=404;A("Not Found",w,a+44,64);c(a,0,h)}}catch(h){c(a,0,h)}}else c(a,0,"IndexedDB not available!")}var Kd={};
function Ld(){if(!Md){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"==typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:da||"./this.program"},b;for(b in Kd)void 0===Kd[b]?delete a[b]:a[b]=Kd[b];var c=[];for(b in a)c.push(b+"="+a[b]);Md=c}return Md}var Md;function Nd(a,b){Nd.kc||(Nd.kc=Xa());for(var c=0;c<b;c++)C[a+c>>0]=Nd.kc();return 0}
var Od=[31,29,31,30,31,30,31,31,30,31,30,31],Pd=[31,28,31,30,31,30,31,31,30,31,30,31];
function Qd(a,b,c,d){function e(k,u,x){for(k="number"==typeof k?k.toString():k||"";k.length<u;)k=x[0]+k;return k}function f(k,u){return e(k,u,"0")}function h(k,u){function x(F){return 0>F?-1:0<F?1:0}var z;0===(z=x(k.getFullYear()-u.getFullYear()))&&0===(z=x(k.getMonth()-u.getMonth()))&&(z=x(k.getDate()-u.getDate()));return z}function l(k){switch(k.getDay()){case 0:return new Date(k.getFullYear()-1,11,29);case 1:return k;case 2:return new Date(k.getFullYear(),0,3);case 3:return new Date(k.getFullYear(),
0,2);case 4:return new Date(k.getFullYear(),0,1);case 5:return new Date(k.getFullYear()-1,11,31);case 6:return new Date(k.getFullYear()-1,11,30)}}function m(k){var u=k.kb;for(k=new Date((new Date(k.lb+1900,0,1)).getTime());0<u;){var x=k.getMonth(),z=(xd(k.getFullYear())?Od:Pd)[x];if(u>z-k.getDate())u-=z-k.getDate()+1,k.setDate(1),11>x?k.setMonth(x+1):(k.setMonth(0),k.setFullYear(k.getFullYear()+1));else{k.setDate(k.getDate()+u);break}}x=new Date(k.getFullYear()+1,0,4);u=l(new Date(k.getFullYear(),
0,4));x=l(x);return 0>=h(u,k)?0>=h(x,k)?k.getFullYear()+1:k.getFullYear():k.getFullYear()-1}var n=E[d+40>>2];d={hd:E[d>>2],gd:E[d+4>>2],Jb:E[d+8>>2],Wb:E[d+12>>2],Kb:E[d+16>>2],lb:E[d+20>>2],eb:E[d+24>>2],kb:E[d+28>>2],qd:E[d+32>>2],fd:E[d+36>>2],jd:n?v(n):""};c=v(c);n={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S","%x":"%m/%d/%y","%X":"%H:%M:%S","%Ec":"%c","%EC":"%C","%Ex":"%m/%d/%y","%EX":"%H:%M:%S","%Ey":"%y","%EY":"%Y","%Od":"%d",
"%Oe":"%e","%OH":"%H","%OI":"%I","%Om":"%m","%OM":"%M","%OS":"%S","%Ou":"%u","%OU":"%U","%OV":"%V","%Ow":"%w","%OW":"%W","%Oy":"%y"};for(var t in n)c=c.replace(new RegExp(t,"g"),n[t]);var p="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),q="January February March April May June July August September October November December".split(" ");n={"%a":function(k){return p[k.eb].substring(0,3)},"%A":function(k){return p[k.eb]},"%b":function(k){return q[k.Kb].substring(0,3)},"%B":function(k){return q[k.Kb]},
"%C":function(k){return f((k.lb+1900)/100|0,2)},"%d":function(k){return f(k.Wb,2)},"%e":function(k){return e(k.Wb,2," ")},"%g":function(k){return m(k).toString().substring(2)},"%G":function(k){return m(k)},"%H":function(k){return f(k.Jb,2)},"%I":function(k){k=k.Jb;0==k?k=12:12<k&&(k-=12);return f(k,2)},"%j":function(k){for(var u=0,x=0;x<=k.Kb-1;u+=(xd(k.lb+1900)?Od:Pd)[x++]);return f(k.Wb+u,3)},"%m":function(k){return f(k.Kb+1,2)},"%M":function(k){return f(k.gd,2)},"%n":function(){return"\n"},"%p":function(k){return 0<=
k.Jb&&12>k.Jb?"AM":"PM"},"%S":function(k){return f(k.hd,2)},"%t":function(){return"\t"},"%u":function(k){return k.eb||7},"%U":function(k){return f(Math.floor((k.kb+7-k.eb)/7),2)},"%V":function(k){var u=Math.floor((k.kb+7-(k.eb+6)%7)/7);2>=(k.eb+371-k.kb-2)%7&&u++;if(u)53==u&&(x=(k.eb+371-k.kb)%7,4==x||3==x&&xd(k.lb)||(u=1));else{u=52;var x=(k.eb+7-k.kb-1)%7;(4==x||5==x&&xd(k.lb%400-1))&&u++}return f(u,2)},"%w":function(k){return k.eb},"%W":function(k){return f(Math.floor((k.kb+7-(k.eb+6)%7)/7),2)},
"%y":function(k){return(k.lb+1900).toString().substring(2)},"%Y":function(k){return k.lb+1900},"%z":function(k){k=k.fd;var u=0<=k;k=Math.abs(k)/60;return(u?"+":"-")+String("0000"+(k/60*100+k%60)).slice(-4)},"%Z":function(k){return k.jd},"%%":function(){return"%"}};c=c.replace(/%%/g,"\x00\x00");for(t in n)c.includes(t)&&(c=c.replace(new RegExp(t,"g"),n[t](d)));c=c.replace(/\0\0/g,"%");t=Za(c,!1);if(t.length>b)return 0;C.set(t,a);return t.length-1}
function xb(a,b,c,d){a||(a=this);this.parent=a;this.fb=a.fb;this.tb=null;this.id=pb++;this.name=b;this.mode=c;this.Na={};this.Oa={};this.vb=d}Object.defineProperties(xb.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}},Lc:{get:function(){return 16384===(this.mode&61440)}},Kc:{get:function(){return 8192===(this.mode&61440)}}});Qb();
qb=Array(4096);Eb(N,"/");P("/tmp",16895,0);P("/home",16895,0);P("/home/web_user",16895,0);(()=>{P("/dev",16895,0);bb(259,{read:()=>0,write:(b,c,d,e)=>e});Fb("/dev/null",259);ab(1280,db);ab(1536,eb);Fb("/dev/tty",1280);Fb("/dev/tty1",1536);var a=Xa();Wb("/dev","random",a);Wb("/dev","urandom",a);P("/dev/shm",16895,0);P("/dev/shm/tmp",16895,0)})();
(()=>{P("/proc",16895,0);var a=P("/proc/self",16895,0);P("/proc/self/fd",16895,0);Eb({fb:()=>{var b=ib(a,"fd",16895,73);b.Na={rb:(c,d)=>{var e=ob[+d];if(!e)throw new M(8);c={parent:null,fb:{ic:"fake"},Na:{wb:()=>e.path}};return c.parent=c}};return b}},"/proc/self/fd")})();var Zb;g.FS_createPath=Tb;g.FS_createDataFile=Vb;g.FS_createPreloadedFile=$b;g.FS_unlink=Hb;g.FS_createLazyFile=Yb;g.FS_createDevice=Wb;oc=g.InternalError=nc("InternalError");for(var Rd=Array(256),Sd=0;256>Sd;++Sd)Rd[Sd]=String.fromCharCode(Sd);
tc=Rd;uc=g.BindingError=nc("BindingError");Ic.prototype.isAliasOf=function(a){if(!(this instanceof Ic&&a instanceof Ic))return!1;var b=this.La.Sa.Qa,c=this.La.Pa,d=a.La.Sa.Qa;for(a=a.La.Pa;b.$a;)c=b.xb(c),b=b.$a;for(;d.$a;)a=d.xb(a),d=d.$a;return b===d&&c===a};
Ic.prototype.clone=function(){this.La.Pa||vc(this);if(this.La.ub)return this.La.count.value+=1,this;var a=Hc,b=Object,c=b.create,d=Object.getPrototypeOf(this),e=this.La;a=a(c.call(b,d,{La:{value:{count:e.count,nb:e.nb,ub:e.ub,Pa:e.Pa,Sa:e.Sa,Xa:e.Xa,Za:e.Za}}}));a.La.count.value+=1;a.La.nb=!1;return a};Ic.prototype["delete"]=function(){this.La.Pa||vc(this);this.La.nb&&!this.La.ub&&S("Object already scheduled for deletion");xc(this);yc(this.La);this.La.ub||(this.La.Xa=void 0,this.La.Pa=void 0)};
Ic.prototype.isDeleted=function(){return!this.La.Pa};Ic.prototype.deleteLater=function(){this.La.Pa||vc(this);this.La.nb&&!this.La.ub&&S("Object already scheduled for deletion");Bc.push(this);1===Bc.length&&Dc&&Dc(Cc);this.La.nb=!0;return this};g.getInheritedInstanceCount=function(){return Object.keys(Ec).length};g.getLiveInheritedInstances=function(){var a=[],b;for(b in Ec)Ec.hasOwnProperty(b)&&a.push(Ec[b]);return a};g.flushPendingDeletes=Cc;g.setDelayFunction=function(a){Dc=a;Bc.length&&Dc&&Dc(Cc)};
Rc.prototype.Dc=function(a){this.lc&&(a=this.lc(a));return a};Rc.prototype.bc=function(a){this.gb&&this.gb(a)};Rc.prototype.argPackAdvance=8;Rc.prototype.readValueFromPointer=hc;Rc.prototype.deleteObject=function(a){if(null!==a)a["delete"]()};
Rc.prototype.fromWireType=function(a){function b(){return this.Eb?Gc(this.Qa.ob,{Sa:this.Qc,Pa:c,Za:this,Xa:a}):Gc(this.Qa.ob,{Sa:this,Pa:a})}var c=this.Dc(a);if(!c)return this.bc(a),null;var d=Fc(this.Qa,c);if(void 0!==d){if(0===d.La.count.value)return d.La.Pa=c,d.La.Xa=a,d.clone();d=d.clone();this.bc(a);return d}d=this.Qa.Cc(c);d=Ac[d];if(!d)return b.call(this);d=this.Db?d.wc:d.pointerType;var e=zc(c,this.Qa,d.Qa);return null===e?b.call(this):this.Eb?Gc(d.Qa.ob,{Sa:d,Pa:e,Za:this,Xa:a}):Gc(d.Qa.ob,
{Sa:d,Pa:e})};Vc=g.UnboundTypeError=nc("UnboundTypeError");g.count_emval_handles=function(){for(var a=0,b=5;b<W.length;++b)void 0!==W[b]&&++a;return a};g.get_first_emval=function(){for(var a=5;a<W.length;++a)if(void 0!==W[a])return W[a];return null};Ga("library_fetch_init");
(function(a,b){try{var c=indexedDB.open("emscripten_filesystem",1)}catch(d){b(d);return}c.onupgradeneeded=d=>{d=d.target.result;d.objectStoreNames.contains("FILES")&&d.deleteObjectStore("FILES");d.createObjectStore("FILES")};c.onsuccess=d=>a(d.target.result);c.onerror=d=>b(d)})(a=>{Fd=a;Ha("library_fetch_init")},()=>{Fd=!1;Ha("library_fetch_init")});
var Xd={ra:function(a,b,c){(new Sa(a)).Ic(b,c);Ta++;throw a;},F:function(a,b,c){dc=c;try{var d=bc(a);switch(b){case 0:var e=ec();return 0>e?-28:Db(d,e).hb;case 1:case 2:return 0;case 3:return d.flags;case 4:return e=ec(),d.flags|=e,0;case 5:return e=ec(),ua[e+0>>1]=2,0;case 6:case 7:return 0;case 16:case 8:return-28;case 9:return-1;default:return-28}}catch(f){if("undefined"==typeof Q||!(f instanceof M))throw f;return-f.Wa}},da:function(a,b){try{var c=bc(a);return cc(Ib,c.path,b)}catch(d){if("undefined"==
typeof Q||!(d instanceof M))throw d;return-d.Wa}},ea:function(a,b,c){dc=c;try{var d=bc(a);switch(b){case 21509:case 21505:return d.Ta?0:-59;case 21510:case 21511:case 21512:case 21506:case 21507:case 21508:return d.Ta?0:-59;case 21519:if(!d.Ta)return-59;var e=ec();return E[e>>2]=0;case 21520:return d.Ta?-28:-59;case 21531:a=e=ec();if(!d.Oa.Jc)throw new M(59);return d.Oa.Jc(d,b,a);case 21523:return d.Ta?0:-59;case 21524:return d.Ta?0:-59;default:return-28}}catch(f){if("undefined"==typeof Q||!(f instanceof
M))throw f;return-f.Wa}},ba:function(a,b,c,d){try{b=v(b);var e=d&256;b=ac(a,b,d&4096);return cc(e?Jb:Ib,b,c)}catch(f){if("undefined"==typeof Q||!(f instanceof M))throw f;return-f.Wa}},G:function(a,b,c,d){dc=d;try{b=v(b);b=ac(a,b);var e=d?ec():0;return Mb(b,c,e).hb}catch(f){if("undefined"==typeof Q||!(f instanceof M))throw f;return-f.Wa}},ca:function(a,b){try{return a=v(a),cc(Ib,a,b)}catch(c){if("undefined"==typeof Q||!(c instanceof M))throw c;return-c.Wa}},d:function(a){var b=fc[a];delete fc[a];var c=
b.Sb,d=b.gb,e=b.dc,f=e.map(h=>h.Fc).concat(e.map(h=>h.cd));qc([a],f,h=>{var l={};e.forEach((m,n)=>{var t=h[n],p=m.Cb,q=m.Ec,k=h[n+e.length],u=m.bd,x=m.dd;l[m.Bc]={read:z=>t.fromWireType(p(q,z)),write:(z,F)=>{var H=[];u(x,z,k.toWireType(H,F));gc(H)}}});return[{name:b.name,fromWireType:function(m){var n={},t;for(t in l)n[t]=l[t].read(m);d(m);return n},toWireType:function(m,n){for(var t in l)if(!(t in n))throw new TypeError('Missing field:  "'+t+'"');var p=c();for(t in l)l[t].write(p,n[t]);null!==m&&
m.push(d,p);return p},argPackAdvance:8,readValueFromPointer:hc,ab:d}]})},Q:function(){},la:function(a,b,c,d,e){var f=sc(c);b=R(b);rc(a,{name:b,fromWireType:function(h){return!!h},toWireType:function(h,l){return l?d:e},argPackAdvance:8,readValueFromPointer:function(h){if(1===c)var l=C;else if(2===c)l=ua;else if(4===c)l=E;else throw new TypeError("Unknown boolean type size: "+b);return this.fromWireType(l[h>>f])},ab:null})},s:function(a,b,c,d,e,f,h,l,m,n,t,p,q){t=R(t);f=V(e,f);l&&(l=V(h,l));n&&(n=V(m,
n));q=V(p,q);var k=lc(t);Kc(k,function(){Zc("Cannot construct "+t+" due to unbound types",[d])});qc([a,b,c],d?[d]:[],function(u){u=u[0];if(d){var x=u.Qa;var z=x.ob}else z=Ic.prototype;u=mc(k,function(){if(Object.getPrototypeOf(this)!==F)throw new uc("Use 'new' to construct "+t);if(void 0===H.ib)throw new uc(t+" has no accessible constructor");var O=H.ib[arguments.length];if(void 0===O)throw new uc("Tried to invoke ctor of "+t+" with invalid number of parameters ("+arguments.length+") - expected ("+
Object.keys(H.ib).toString()+") parameters instead!");return O.apply(this,arguments)});var F=Object.create(z,{constructor:{value:u}});u.prototype=F;var H=new Lc(t,u,F,q,x,f,l,n);x=new Rc(t,H,!0,!1);z=new Rc(t+"*",H,!1,!1);var y=new Rc(t+" const*",H,!1,!0);Ac[a]={pointerType:z,wc:y};Sc(k,u);return[x,z,y]})},u:function(a,b,c,d,e,f){0<b||oa();var h=$c(b,c);e=V(d,e);qc([],[a],function(l){l=l[0];var m="constructor "+l.name;void 0===l.Qa.ib&&(l.Qa.ib=[]);if(void 0!==l.Qa.ib[b-1])throw new uc("Cannot register multiple constructors with identical number of parameters ("+
(b-1)+") for class '"+l.name+"'! Overload resolution is currently only performed using the parameter count, not actual type info!");l.Qa.ib[b-1]=()=>{Zc("Cannot construct "+l.name+" due to unbound types",h)};qc([],h,function(n){n.splice(1,0,null);l.Qa.ib[b-1]=ad(m,n,null,e,f);return[]});return[]})},i:function(a,b,c,d,e,f,h,l){var m=$c(c,d);b=R(b);f=V(e,f);qc([],[a],function(n){function t(){Zc("Cannot call "+p+" due to unbound types",m)}n=n[0];var p=n.name+"."+b;b.startsWith("@@")&&(b=Symbol[b.substring(2)]);
l&&n.Qa.Rc.push(b);var q=n.Qa.ob,k=q[b];void 0===k||void 0===k.Va&&k.className!==n.name&&k.yb===c-2?(t.yb=c-2,t.className=n.name,q[b]=t):(Jc(q,b,p),q[b].Va[c-2]=t);qc([],m,function(u){u=ad(p,u,n,f,h);void 0===q[b].Va?(u.yb=c-2,q[b]=u):q[b].Va[c-2]=u;return[]});return[]})},ka:function(a,b){b=R(b);rc(a,{name:b,fromWireType:function(c){var d=X(c);cd(c);return d},toWireType:function(c,d){return T(d)},argPackAdvance:8,readValueFromPointer:hc,ab:null})},I:function(a,b,c){c=sc(c);b=R(b);rc(a,{name:b,fromWireType:function(d){return d},
toWireType:function(d,e){return e},argPackAdvance:8,readValueFromPointer:dd(b,c),ab:null})},B:function(a,b,c,d,e,f){var h=$c(b,c);a=R(a);e=V(d,e);Kc(a,function(){Zc("Cannot call "+a+" due to unbound types",h)},b-1);qc([],h,function(l){Sc(a,ad(a,[l[0],null].concat(l.slice(1)),null,e,f),b-1);return[]})},m:function(a,b,c,d,e){b=R(b);-1===e&&(e=4294967295);e=sc(c);var f=l=>l;if(0===d){var h=32-8*c;f=l=>l<<h>>>h}c=b.includes("unsigned")?function(l,m){return m>>>0}:function(l,m){return m};rc(a,{name:b,
fromWireType:f,toWireType:c,argPackAdvance:8,readValueFromPointer:ed(b,e,0!==d),ab:null})},h:function(a,b,c){function d(f){f>>=2;var h=G;return new e(h.buffer,h[f+1],h[f])}var e=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array][b];c=R(c);rc(a,{name:c,fromWireType:d,argPackAdvance:8,readValueFromPointer:d},{Hc:!0})},J:function(a,b){b=R(b);var c="std::string"===b;rc(a,{name:b,fromWireType:function(d){var e=G[d>>2],f=d+4;if(c)for(var h=f,l=0;l<=e;++l){var m=
f+l;if(l==e||0==w[m]){h=v(h,m-h);if(void 0===n)var n=h;else n+=String.fromCharCode(0),n+=h;h=m+1}}else{n=Array(e);for(l=0;l<e;++l)n[l]=String.fromCharCode(w[f+l]);n=n.join("")}Yc(d);return n},toWireType:function(d,e){e instanceof ArrayBuffer&&(e=new Uint8Array(e));var f="string"==typeof e;f||e instanceof Uint8Array||e instanceof Uint8ClampedArray||e instanceof Int8Array||S("Cannot pass non-string to std::string");var h=c&&f?ta(e):e.length;var l=Cd(4+h+1),m=l+4;G[l>>2]=h;if(c&&f)A(e,w,m,h+1);else if(f)for(f=
0;f<h;++f){var n=e.charCodeAt(f);255<n&&(Yc(m),S("String has UTF-16 code units that do not fit in 8 bits"));w[m+f]=n}else for(f=0;f<h;++f)w[m+f]=e[f];null!==d&&d.push(Yc,l);return l},argPackAdvance:8,readValueFromPointer:hc,ab:function(d){Yc(d)}})},A:function(a,b,c){c=R(c);if(2===b){var d=gd;var e=hd;var f=jd;var h=()=>D;var l=1}else 4===b&&(d=kd,e=ld,f=md,h=()=>G,l=2);rc(a,{name:c,fromWireType:function(m){for(var n=G[m>>2],t=h(),p,q=m+4,k=0;k<=n;++k){var u=m+4+k*b;if(k==n||0==t[u>>l])q=d(q,u-q),
void 0===p?p=q:(p+=String.fromCharCode(0),p+=q),q=u+b}Yc(m);return p},toWireType:function(m,n){"string"!=typeof n&&S("Cannot pass non-string to C++ string type "+c);var t=f(n),p=Cd(4+t+b);G[p>>2]=t>>l;e(n,p+4,t+b);null!==m&&m.push(Yc,p);return p},argPackAdvance:8,readValueFromPointer:hc,ab:function(m){Yc(m)}})},e:function(a,b,c,d,e,f){fc[a]={name:R(b),Sb:V(c,d),gb:V(e,f),dc:[]}},c:function(a,b,c,d,e,f,h,l,m,n){fc[a].dc.push({Bc:R(b),Fc:c,Cb:V(d,e),Ec:f,cd:h,bd:V(l,m),dd:n})},ma:function(a,b){b=R(b);
rc(a,{Mc:!0,name:b,argPackAdvance:0,fromWireType:function(){},toWireType:function(){}})},na:function(a){var b=Ed[a];b&&(delete Ed[a],0<b.readyState&&4>b.readyState&&b.abort())},ga:function(){return!0},U:function(){throw Infinity;},o:function(a,b,c){a=X(a);b=nd(b,"emval::as");var d=[],e=T(d);G[c>>2]=e;return b.toWireType(d,a)},M:function(a,b,c,d){a=X(a);c=od(b,c);for(var e=Array(b),f=0;f<b;++f){var h=c[f];e[f]=h.readValueFromPointer(d);d+=h.argPackAdvance}a=a.apply(void 0,e);return T(a)},r:function(a,
b,c,d){a=rd[a];b=X(b);c=qd(c);a(b,c,null,d)},b:cd,N:function(a,b){a=X(a);b=X(b);return a==b},t:function(a){if(0===a)return T(sd());a=qd(a);return T(sd()[a])},q:function(a,b){var c=od(a,b),d=c[0];b=d.name+"_$"+c.slice(1).map(function(h){return h.name}).join("_")+"$";var e=ud[b];if(void 0!==e)return e;var f=Array(a-1);e=td((h,l,m,n)=>{for(var t=0,p=0;p<a-1;++p)f[p]=c[p+1].readValueFromPointer(n+t),t+=c[p+1].argPackAdvance;h=h[l].apply(h,f);for(p=0;p<a-1;++p)c[p+1].yc&&c[p+1].yc(f[p]);if(!d.Mc)return d.toWireType(m,
h)});return ud[b]=e},C:function(a,b){a=X(a);b=X(b);return T(a[b])},v:function(a){4<a&&(W[a].Ub+=1)},sa:function(a,b){a=X(a);b=X(b);return a instanceof b},w:function(a,b,c,d){a=X(a);var e=wd[b];e||(e=vd(b),wd[b]=e);return e(a,c,d)},k:function(){return T([])},g:function(a){return T(qd(a))},l:function(){return T({})},n:function(a){var b=X(a);gc(b);cd(a)},f:function(a,b,c){a=X(a);b=X(b);c=X(c);a[b]=c},j:function(a,b){a=nd(a,"_emval_take_value");a=a.readValueFromPointer(b);return T(a)},O:function(a){a=
X(a);return T(typeof a)},ha:function(a,b){a=new Date(1E3*(G[a>>2]+4294967296*E[a+4>>2]));E[b>>2]=a.getSeconds();E[b+4>>2]=a.getMinutes();E[b+8>>2]=a.getHours();E[b+12>>2]=a.getDate();E[b+16>>2]=a.getMonth();E[b+20>>2]=a.getFullYear()-1900;E[b+24>>2]=a.getDay();E[b+28>>2]=Ad(a)|0;E[b+36>>2]=-(60*a.getTimezoneOffset());var c=(new Date(a.getFullYear(),6,1)).getTimezoneOffset(),d=(new Date(a.getFullYear(),0,1)).getTimezoneOffset();E[b+32>>2]=(c!=d&&a.getTimezoneOffset()==Math.min(d,c))|0},ia:function(a){var b=
new Date(E[a+20>>2]+1900,E[a+16>>2],E[a+12>>2],E[a+8>>2],E[a+4>>2],E[a>>2],0),c=E[a+32>>2],d=b.getTimezoneOffset(),e=(new Date(b.getFullYear(),6,1)).getTimezoneOffset(),f=(new Date(b.getFullYear(),0,1)).getTimezoneOffset(),h=Math.min(f,e);0>c?E[a+32>>2]=Number(e!=f&&h==d):0<c!=(h==d)&&(e=Math.max(f,e),b.setTime(b.getTime()+6E4*((0<c?h:e)-d)));E[a+24>>2]=b.getDay();E[a+28>>2]=Ad(b)|0;E[a>>2]=b.getSeconds();E[a+4>>2]=b.getMinutes();E[a+8>>2]=b.getHours();E[a+12>>2]=b.getDate();E[a+16>>2]=b.getMonth();
E[a+20>>2]=b.getYear();return b.getTime()/1E3|0},Z:function(a,b,c,d,e,f,h){try{var l=bc(d);if(0!==(b&2)&&0===(c&2)&&2!==(l.flags&2097155))throw new M(2);if(1===(l.flags&2097155))throw new M(2);if(!l.Oa.sb)throw new M(43);var m=l.Oa.sb(l,a,e,b,c);var n=m.Pa;E[f>>2]=m.Yb;G[h>>2]=n;return 0}catch(t){if("undefined"==typeof Q||!(t instanceof M))throw t;return-t.Wa}},_:function(a,b,c,d,e,f){try{var h=bc(e);if(c&2){if(32768!==(h.node.mode&61440))throw new M(43);d&2||h.Oa.Gb&&h.Oa.Gb(h,w.slice(a,a+b),f,b,
d)}}catch(l){if("undefined"==typeof Q||!(l instanceof M))throw l;return-l.Wa}},ja:function(a,b,c){function d(m){return(m=m.toTimeString().match(/\(([A-Za-z ]+)\)$/))?m[1]:"GMT"}var e=(new Date).getFullYear(),f=new Date(e,0,1),h=new Date(e,6,1);e=f.getTimezoneOffset();var l=h.getTimezoneOffset();G[a>>2]=60*Math.max(e,l);E[b>>2]=Number(e!=l);a=d(f);b=d(h);a=Bd(a);b=Bd(b);l<e?(G[c>>2]=a,G[c+4>>2]=b):(G[c>>2]=b,G[c+4>>2]=a)},a:function(){oa("")},p:function(a,b,c){Dd.length=0;var d;for(c>>=2;d=w[b++];)c+=
105!=d&c,Dd.push(105==d?E[c]:wa[c++>>1]),++c;return Na[a].apply(null,Dd)},H:function(){return Date.now()},Y:function(){return 2147483648},y:()=>performance.now(),pa:function(){return!ha},fa:function(a,b,c){w.copyWithin(a,b,b+c)},X:function(a){var b=w.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);var e=Math,f=e.min;d=Math.max(a,d);d+=(65536-d%65536)%65536;a:{var h=pa.buffer;try{pa.grow(f.call(e,2147483648,d)-h.byteLength+65535>>>16);xa();var l=
1;break a}catch(m){}l=void 0}if(l)return!0}return!1},oa:function(a,b,c,d,e){function f(I){if(z)I();else if(!qa)try{I()}catch(Qa){Qa instanceof Oa||"unwind"==Qa||ea(1,Qa)}}var h=a+112,l=v(h),m=G[h+36>>2],n=G[h+40>>2],t=G[h+44>>2],p=G[h+48>>2],q=G[h+52>>2],k=!!(q&4),u=!!(q&32),x=!!(q&16),z=!!(q&64),F=I=>{f(()=>{m?U(m)(I):b&&b(I)})},H=I=>{f(()=>{t?U(t)(I):d&&d(I)})},y=I=>{f(()=>{n?U(n)(I):c&&c(I)})},O=I=>{f(()=>{p?U(p)(I):e&&e(I)})};q=I=>{Gd(I,F,y,H,O)};var B=(I,Qa)=>{Hd(I,Qa.response,Ra=>{f(()=>{m?
U(m)(Ra):b&&b(Ra)})},Ra=>{f(()=>{m?U(m)(Ra):b&&b(Ra)})})},Y=I=>{Gd(I,B,y,H,O)};if("EM_IDB_STORE"===l)l=G[h+84>>2],Hd(a,w.slice(l,l+G[h+88>>2]),F,y);else if("EM_IDB_DELETE"===l)Jd(a,F,y);else if(x){if(u)return 0;Gd(a,k?B:F,y,H,O)}else Id(a,F,u?y:k?Y:q);return a},$:function(a,b){var c=0;Ld().forEach(function(d,e){var f=b+c;e=G[a+4*e>>2]=f;for(f=0;f<d.length;++f)C[e++>>0]=d.charCodeAt(f);C[e>>0]=0;c+=d.length+1});return 0},aa:function(a,b){var c=Ld();G[a>>2]=c.length;var d=0;c.forEach(function(e){d+=
e.length+1});G[b>>2]=d;return 0},L:function(a){if(!noExitRuntime){if(g.onExit)g.onExit(a);qa=!0}ea(a,new Oa(a))},z:function(a){try{var b=bc(a);Nb(b);return 0}catch(c){if("undefined"==typeof Q||!(c instanceof M))throw c;return c.Wa}},E:function(a,b,c,d){try{a:{var e=bc(a);a=b;for(var f,h=b=0;h<c;h++){var l=G[a>>2],m=G[a+4>>2];a+=8;var n=e,t=l,p=m,q=f,k=C;if(0>p||0>q)throw new M(28);if(null===n.hb)throw new M(8);if(1===(n.flags&2097155))throw new M(8);if(16384===(n.node.mode&61440))throw new M(31);
if(!n.Oa.read)throw new M(28);var u="undefined"!=typeof q;if(!u)q=n.position;else if(!n.seekable)throw new M(70);var x=n.Oa.read(n,k,t,p,q);u||(n.position+=x);var z=x;if(0>z){var F=-1;break a}b+=z;if(z<m)break;"undefined"!==typeof f&&(f+=z)}F=b}G[d>>2]=F;return 0}catch(H){if("undefined"==typeof Q||!(H instanceof M))throw H;return H.Wa}},P:function(a,b,c,d,e){try{b=c+2097152>>>0<4194305-!!b?(b>>>0)+4294967296*c:NaN;if(isNaN(b))return 61;var f=bc(a);Ob(f,b,d);K=[f.position>>>0,(J=f.position,1<=+Math.abs(J)?
0<J?(Math.min(+Math.floor(J/4294967296),4294967295)|0)>>>0:~~+Math.ceil((J-+(~~J>>>0))/4294967296)>>>0:0)];E[e>>2]=K[0];E[e+4>>2]=K[1];f.Nb&&0===b&&0===d&&(f.Nb=null);return 0}catch(h){if("undefined"==typeof Q||!(h instanceof M))throw h;return h.Wa}},x:function(a,b,c,d){try{a:{var e=bc(a);a=b;for(var f,h=b=0;h<c;h++){var l=G[a>>2],m=G[a+4>>2];a+=8;var n=Pb(e,C,l,m,f);if(0>n){var t=-1;break a}b+=n;"undefined"!==typeof f&&(f+=n)}t=b}G[d>>2]=t;return 0}catch(p){if("undefined"==typeof Q||!(p instanceof
M))throw p;return p.Wa}},qa:function(){var a=stackTrace(),b=ta(a)+1,c=Cd(b);A(a,w,c,b);return c},V:Nd,R:Td,D:Ud,S:Vd,T:Wd,K:Qd,W:function(a,b,c,d){return Qd(a,b,c,d)}};
(function(){function a(e){g.asm=e.exports;pa=g.asm.ta;xa();ya=g.asm.xa;Aa.unshift(g.asm.ua);Ha("wasm-instantiate")}function b(e){a(e.instance)}function c(e){return Ma().then(function(f){return WebAssembly.instantiate(f,d)}).then(function(f){return f}).then(e,function(f){r("failed to asynchronously prepare wasm: "+f);oa(f)})}var d={a:Xd};Ga("wasm-instantiate");if(g.instantiateWasm)try{return g.instantiateWasm(d,a)}catch(e){r("Module.instantiateWasm callback failed with error: "+e),ba(e)}(function(){return na||
"function"!=typeof WebAssembly.instantiateStreaming||Ia()||"function"!=typeof fetch?c(b):fetch(Ja,{credentials:"same-origin"}).then(function(e){return WebAssembly.instantiateStreaming(e,d).then(b,function(f){r("wasm streaming compile failed: "+f);r("falling back to ArrayBuffer instantiation");return c(b)})})})().catch(ba);return{}})();g.___wasm_call_ctors=function(){return(g.___wasm_call_ctors=g.asm.ua).apply(null,arguments)};
var Cd=g._malloc=function(){return(Cd=g._malloc=g.asm.va).apply(null,arguments)},Yc=g._free=function(){return(Yc=g._free=g.asm.wa).apply(null,arguments)},Xc=g.___getTypeName=function(){return(Xc=g.___getTypeName=g.asm.ya).apply(null,arguments)};g.__embind_initialize_bindings=function(){return(g.__embind_initialize_bindings=g.asm.za).apply(null,arguments)};
var gb=g._emscripten_builtin_memalign=function(){return(gb=g._emscripten_builtin_memalign=g.asm.Aa).apply(null,arguments)},Yd=g._setThrew=function(){return(Yd=g._setThrew=g.asm.Ba).apply(null,arguments)},Zd=g.stackSave=function(){return(Zd=g.stackSave=g.asm.Ca).apply(null,arguments)},$d=g.stackRestore=function(){return($d=g.stackRestore=g.asm.Da).apply(null,arguments)};g.___cxa_is_pointer_type=function(){return(g.___cxa_is_pointer_type=g.asm.Ea).apply(null,arguments)};
g.dynCall_ji=function(){return(g.dynCall_ji=g.asm.Fa).apply(null,arguments)};g.dynCall_jiji=function(){return(g.dynCall_jiji=g.asm.Ga).apply(null,arguments)};g.dynCall_viijii=function(){return(g.dynCall_viijii=g.asm.Ha).apply(null,arguments)};g.dynCall_iiiiij=function(){return(g.dynCall_iiiiij=g.asm.Ia).apply(null,arguments)};g.dynCall_iiiiijj=function(){return(g.dynCall_iiiiijj=g.asm.Ja).apply(null,arguments)};g.dynCall_iiiiiijj=function(){return(g.dynCall_iiiiiijj=g.asm.Ka).apply(null,arguments)};
g.__ZN2MB2NN28LinearDefragmentingAllocator10Allocation4nullE=1024;g.___start_em_js=457344;g.___stop_em_js=457767;function Ud(a,b){var c=Zd();try{U(a)(b)}catch(d){$d(c);if(d!==d+0)throw d;Yd(1,0)}}function Wd(a,b,c,d){var e=Zd();try{U(a)(b,c,d)}catch(f){$d(e);if(f!==f+0)throw f;Yd(1,0)}}function Vd(a,b,c){var d=Zd();try{U(a)(b,c)}catch(e){$d(d);if(e!==e+0)throw e;Yd(1,0)}}function Td(a,b,c,d){var e=Zd();try{return U(a)(b,c,d)}catch(f){$d(e);if(f!==f+0)throw f;Yd(1,0)}}g.addRunDependency=Ga;
g.removeRunDependency=Ha;g.FS_createPath=Tb;g.FS_createDataFile=Vb;g.FS_createPreloadedFile=$b;g.FS_createLazyFile=Yb;g.FS_createDevice=Wb;g.FS_unlink=Hb;var ae;Fa=function be(){ae||ce();ae||(Fa=be)};
function ce(){function a(){if(!ae&&(ae=!0,g.calledRun=!0,!qa)){g.noFSInit||Rb||(Rb=!0,Qb(),g.stdin=g.stdin,g.stdout=g.stdout,g.stderr=g.stderr,g.stdin?Wb("/dev","stdin",g.stdin):Gb("/dev/tty","/dev/stdin"),g.stdout?Wb("/dev","stdout",null,g.stdout):Gb("/dev/tty","/dev/stdout"),g.stderr?Wb("/dev","stderr",null,g.stderr):Gb("/dev/tty1","/dev/stderr"),Mb("/dev/stdin",0),Mb("/dev/stdout",1),Mb("/dev/stderr",1));rb=!1;Pa(Aa);aa(g);if(g.onRuntimeInitialized)g.onRuntimeInitialized();if(g.postRun)for("function"==
typeof g.postRun&&(g.postRun=[g.postRun]);g.postRun.length;){var b=g.postRun.shift();Ba.unshift(b)}Pa(Ba)}}if(!(0<Da)){if(g.preRun)for("function"==typeof g.preRun&&(g.preRun=[g.preRun]);g.preRun.length;)Ca();Pa(za);0<Da||(g.setStatus?(g.setStatus("Running..."),setTimeout(function(){setTimeout(function(){g.setStatus("")},1);a()},1)):a())}}if(g.preInit)for("function"==typeof g.preInit&&(g.preInit=[g.preInit]);0<g.preInit.length;)g.preInit.pop()();ce();


  return BlinkIDWasmSDK.ready
}
);
})();
if (typeof exports === 'object' && typeof module === 'object')
  module.exports = BlinkIDWasmSDK;
else if (typeof define === 'function' && define['amd'])
  define([], function() { return BlinkIDWasmSDK; });
else if (typeof exports === 'object')
  exports["BlinkIDWasmSDK"] = BlinkIDWasmSDK;
